### ISSUE TITLE
Attempting to get .well-known/openid-configuration from wrong URL path

### ISSUE THREAD

**Issue by Gillardo** [aspnet/Security#1006]
My code all works when i am developing which i use localhost:5000.

I have now published my code and uploaded to the site which uses child folders....Eg.
http://www.my-url.co.uk/folder1
http://www.my-url.co.uk/folder2

When i call folder1/connect/token or folder2/connect/token with a valid username and password, i get a token returned.

But if i try to connect to a protected api resource, i get this weird message returned on the server??

> An unhandled exception occurred while processing the request.
> 
> HttpRequestException: Response status code does not indicate success: 404 (Not Found).
> MoveNext
> 
> IOException: IDX10804: Unable to retrieve document from: 'http://www.my-url.co.uk/.well-known/openid-configuration'.
> MoveNext
> 
> InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://www.my-url.co.uk/.well-known/openid-configuration'.
> MoveNext

I am using JWT Token, and have added this to my `Startup.cs` file
```
// enable JWTBearer
app.UseJwtBearerAuthentication(new JwtBearerOptions
{
	Authority = "http://www.my-url.co.uk/folder1",
	AutomaticAuthenticate = true,
	AutomaticChallenge = true,
	Audience = "http://www.my-url.co.uk/folder1",
	RequireHttpsMetadata = false
});
```

And in my `AuthorizationController.cs` file (I am using OpenIddict) i have added this line as well to my `Exchange` and `Accept` methods
```
// Set resource
ticket.SetResources(new string[] { "http://www.my-url.co.uk/folder1" });
```

Why is it trying to download the document from 

http://www.my-url.co.uk/.well-known/openid-configuration

instead of 

http://www.my-url.co.uk/folder1/.well-known/openid-configuration

Any help on the issue would be helpful.

**Comment by vishpriya** [comment]
Is this resolved?
I am having the same issue what is the solution?

**Comment by Gillardo** [comment]
Mine is now working but cant remember how i "fixed" the issue.  I am also using JWT.  Have you got the settings above set?  If you can make a small example, i can take a look if needed?

**Comment by fedoranimus** [comment]
@Gillardo @vishpriya I too am having this issue. Any solutions?
