### ISSUE TITLE
OAuth: Expose the result of the token request to the notification

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#101]
When the code is exchanged for a token there may be additional data returned from the provider. Expose the whole `TokenResponse` in the `GetUserInformationAsync/Authenticated` notifications.

Example: Google OpenId -> Oauth2 migrations
https://katanaproject.codeplex.com/workitem/359
https://katanaproject.codeplex.com/SourceControl/network/forks/suhasj/Katana/contribution/7719

**Comment by Eilon** [comment]
@HaoK please work with @PinpointTownes on his PR so we can try to get it in by end of next week.

**Comment by HaoK** [comment]
Merged 9bb8b6114697f14a42e747acd1d1a41e6eed5af1
