### ISSUE TITLE
External Login SignInManager problem

### ISSUE THREAD

**Issue by coddo** [aspnet/Security#1010]
Hi,

I have an issue with using external authentication methods, more precisely, I'm trying to sign in using Google. I always get `null` when calling `await _signInManager.GetExternalLoginInfoAsync()`. The application appears as authorized in my google account and requests seem to have no errors in the developer console.

I am using the latest .NET Core Web Application templates, with Individual Accounts authentication in place. So my code is the standard one:

```C#
private readonly SignInManager<ApplicationUser> _signInManager;

[HttpPost]
[AllowAnonymous]
[ValidateAntiForgeryToken]
public IActionResult ExternalLogin(string provider, string returnUrl = null)
{
    // Request a redirect to the external login provider.
    var redirectUrl = Url.Action("ExternalLoginCallback", "Account", new { ReturnUrl = returnUrl });
    var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
    return Challenge(properties, provider);
}

public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
{
	if (remoteError != null)
	{
		ModelState.AddModelError(string.Empty, $"Error from external provider: {remoteError}");
		return View(nameof(Login));
	}
	var info = await _signInManager.GetExternalLoginInfoAsync();
	
	// info is always null
	if (info == null)
	{
		return RedirectToAction(nameof(Login));
	}
	
	// Sign in the user with this external login provider if the user already has a login.
	var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false);
	if (result.Succeeded)
	{
		_logger.LogInformation(5, "User logged in with {Name} provider.", info.LoginProvider);
		return RedirectToLocal(returnUrl);
	}
	if (result.RequiresTwoFactor)
	{
		return RedirectToAction(nameof(SendCode), new { ReturnUrl = returnUrl });
	}
	if (result.IsLockedOut)
	{
		return View("Lockout");
	}
	else
	{
		// If the user does not have an account, then ask the user to create an account.
		ViewData["ReturnUrl"] = returnUrl;
		ViewData["LoginProvider"] = info.LoginProvider;
		var email = info.Principal.FindFirstValue(ClaimTypes.Email);
		return View("ExternalLoginConfirmation", new ExternalLoginConfirmationViewModel { Email = email });
	}
}
```

I have tried using the standard GoogleAuthentication with GoogleOptions, OAuth and the OpenIdConnect (which I actually want to use out of these three).
Here is my configuration for app cookies and OIDC:

```C#
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
	AuthenticationScheme = CookieAuthenticationDefaults.AuthenticationScheme,

	AutomaticAuthenticate = false,
	AutomaticChallenge = false
});

app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
{
	DisplayName = "Google",
	AuthenticationScheme = "Google",

	ClientId = "*********",
	ClientSecret = "***********",
	Authority = "https://accounts.google.com",

	ResponseType = OpenIdConnectResponseType.Code,
	GetClaimsFromUserInfoEndpoint = true,
	SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme,

	Scope = { StandardScopes.Email.Name, StandardScopes.OpenId.Name}
});
```

Because the info is null on the callback, I get redirected to the login page and I am not authenticated. What is even worse is that if I click the external authentication button again, I get redirected to *http://localhost:5000/Account/AccessDenied?ReturnUrl=%2FAccount%2FExternalLoginCallback* and a blank page is shown because there is no endpoint for AccessDenied. In order to fix this problem, I have to forcibly delete the cookies in the browser. I can tell that the authentication worked on Google's part because this time I am not prompted the Consent page anymore and the flow continues normally, with me still getting a null value on the callback.

I have tried looking at other similar issues and tried the fixes suggested in them, but nothing worked.

Thank you.

**Comment by coddo** [comment]
It seems that the problem for OIDC was that I was setting the DisplayName and AuthenticationScheme to "Google". Cutting out those to lines from the code, made it work.

The authentication scheme seems logic now why it didn't work, but if I try to change the DisplayName it still silently breaks (get null as described above). Is this how it should really behave?

**Comment by Tratcher** [comment]
Changing DisplayName shouldn't affect anything. @HaoK, is DisplayName recorded in the user database?

Changing AuthenticationScheme should be fine, but you may need to change it in multiple places.

**Comment by HaoK** [comment]
The display name should only controls what is shown for the text.  See: Account/Login.cshtml is where these are used.  DisplayName is not stored in the database by default

**Comment by coddo** [comment]
Clearing the browser cache and removing the cookies for the domain seems to have fixed the DisplayName issue also. 

Something must have been cached from my previous configurations and attempts to make this work.
The OIDC is now fully functional with Google provider now.

Thanks!
