### ISSUE TITLE
Allow access to PolicyMap in AuthorizationOptions

### ISSUE THREAD

**Issue by atuzovic** [aspnet/Security#1011]
This request is related to AuthorizationOptions class in Microsoft.AspNetCore.Authorization library.

Due to architectural reasons, we need to access registered policies that are stored in AuthorizationOptions class as:
`private IDictionary<string, AuthorizationPolicy> PolicyMap { get; } = new Dictionary<string, AuthorizationPolicy>(StringComparer.OrdinalIgnoreCase);
`

This class has method allows retrieval of single policy by its name:

```
    public AuthorizationPolicy GetPolicy(string name)
        {
            if (name == null)
            {
                throw new ArgumentNullException(nameof(name));
            }

            return PolicyMap.ContainsKey(name) ? PolicyMap[name] : null;
        }
```

What we need is a similar method that would return all policies, something as simple as:

```
        public IDictionary<string, AuthorizationPolicy> GetPolicies()
        {
            return PolicyMap;
        }
```

Or, even easier version - PolicyMap property can be changed to have public gettter.

If this request is approved, I'd like to create pull request and make change myself.

**Comment by Eilon** [comment]
@atuzovic can you share more info about why you need to list them? This is probably something we can implement, but the more we know about the scenario we can make sure we offer the right solution.

**Comment by atuzovic** [comment]
Scenario that we want to support is to implement visibility management on certain components in AngularJS based on server-side policies.

When the user logs in, names of the policies that are satisfied are returned in the response.

On the client side, AngularJS components are secured like this:
`<some-component policy="RequiredPolicyName"></some-component>
`

In order for us to return policies that are satisfied, we need to access them from the code and validate if they are satisfied which we currently cannot.

**Comment by HaoK** [comment]
@atuzovic feel free to submit a PR for this if you like as a starting point for discussion

**Comment by HaoK** [comment]
We can do this in 2.1 as its not a breaking change

**Comment by Eilon** [comment]
Closing because we think this change along would be insufficient for proper case-insensitivity support.

**Comment by hikalkan** [comment]
Did you finally decided to not implement this?

I think it's essential for the case @atuzovic explained: https://github.com/aspnet/Security/issues/1011#issuecomment-264634640
And it's a very common scenario for a SPA.
