### ISSUE TITLE
Microsoft Account Authentication not working

### ISSUE THREAD

**Issue by 01binary** [aspnet/Security#1012]
Following basic steps below, Microsoft Account Authentication is returning the following:

`We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later.`

with this URI:

`https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The provided value for the input parameter 'redirect_uri' is not valid. The expected value is 'https://login.live.com/oauth20_desktop.srf' or a URL which matches the redirect URI registered for this client application.`

My application is at `https://localhost:5001`.
On apps.dev.microsoft.com, the Web platform has redirect Uri `https://localhost:5001`

The Uri's match as expected and application ID appears to be correct.

When the auth dialog opens, the middleware in this repository is sending it to:

`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=5bb9d901-c7a7-4ad0-9ece-38a198d0ae07&scope=https%3A%2F%2Fgraph.microsoft.com%2Fuser.read&response_type=code&redirect_uri=https%3A%2F%2Flocalhost%3A5001%2Fsignin-microsoft&state=CfDJ8PBr0ftoFZpOtmnt4M_GOfu4U3UPbmGEMKjR0UWaErs29D9sl6CV560TBn56h0up9FYS-MtgiYwciVTdWukiAcb49-1rBGsMg4fERmgl_ypU8qSIlNhn1qbZ-j2tndsUMpOgv3-Kg9EhvES36z9iHXE4_QwHsmSiNyidxSoPgQXbeUBV6f1jesj7njNZb9h8C1cYirnRfeSZVRUvcacRYqbWhdX-lmJEoqk1QVf_b8_71rEyXuYl0MD-212HutaiKa2hXGoNe0DT46iMCsMIEZyxl6mFis4cvq44Op0-YbyuusEVfz-dcQ0XOc9A2uN5VA`

The only two options that are sent as defaults are Scope and Response Type. Are these incorrect?

The branch with this non-working code can be found here:
https://github.com/01binary/zeroweb/tree/%2319-MicrosoftLogin

**Comment by 01binary** [comment]
Tried entering a different email address, and this time got a different error:
<img width="566" alt="screen shot 2016-10-23 at 12 10 16 pm" src="https://cloud.githubusercontent.com/assets/19985964/19628763/d1d4fa32-9919-11e6-9df1-515e188d36ac.png">

Turns out it is something wrong with the middleware. I don't have `https://localhost:5001/signin-microsoft` configured in my app, since I don't have any routes in my site to handle `signin-microsoft`. This must be a default for some options that isn't being sent.

**Comment by 01binary** [comment]
Allright, so the default CallbackPath was set to a value that didn't match what was going on in my app.

Two questions here:

- Would it be better not to supply a default for CallbackPath so calling `UseMicrosoftAccountAuthentication` will throw an error telling you this param is required must be provided?

- When I did supply CallbackPath, the setting didn't work correctly. It sent `https://localhost:5001/services/users/callback` to the endpoint but then actually redirected to `https://localhost:5001/services/users/services/users/callback` which failed the flow since I don't have that route. Fortunately I installed my own middleware for 404s that caught this. I then specified `https://localhost:5001/callback` and it redirected to `https://localhost:5001/services/users/callback` as expected. I'm glad I got it to work but it's confusing. What's going on here?

Thanks.

**Comment by Tratcher** [comment]
Check out the docs comments:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationOptions.cs#L31-L35

CallbackPath is used for the middleware to receive the results of the remote auth. You do not need a route/controller/action for this path. Once it has processed the results and generated the sign-in identity/cookie, then it will redirect back to your app code, either to where it started or where you told it to return to in the initial challenge.

Recommendation: keep the default CallbackPath value `/signin-microsoft` and register `https://localhost:50001/signin-microsoft` in the MSA portal.

**Comment by 01binary** [comment]
Confirmed, that works. Does anything in the docs mention that to make this work:

- You need to register root site Uri with the login provider. For example, `https://localhost:5001`
- You also need to register the provider-specific middleware listen route. For example, `https://localhost:5001/signin-providerName`

This was not a straight-forward thing to figure out at all. I don't recall anything noted about this.

**Comment by Tratcher** [comment]
Here's the doc we have on setting these up, however it does not mention this issue.
https://docs.asp.net/en/latest/security/authentication/sociallogins.html
Feel free request clarification here: https://github.com/aspnet/Docs/issues/727 (or a new bug there).

Why did you need to register the root url? You should have only needed to register `https://localhost:5001/signin-providerName` with the provider. They do sometimes ask for an app identifier, and the root url is convenient for that.

**Comment by 01binary** [comment]
I really want to get to this in next few days. Going to attempt a PR for:
https://github.com/aspnet/Docs/blob/master/aspnet/security/authentication/sociallogins.rst

- Split Facebook into its own section
- Add sections for Twitter, Microsoft, Google+
- Recommend https://github.com/aspnet-contrib and add sections for Github, Reddit, LinkedIn and Yahoo
- Document special considerations for supporting Facebook logins in popup, as it requires hooking a redirection event to add query string parameter
- Document special considerations for some providers requiring HTTPS. This may need to later point to a additional section for setting up Kestrel HTTPS and how to generate self-signed cert (this wasted a day for me).

This issue is already linked to the other one so people looking for a solution will hit this thread until I have time.

**Comment by Tratcher** [comment]
Sounds promising.

The callout to aspnet-contrib should be fine, but the asp.net docs should not include instructions for components in contrib (e.g. Yahoo). It's up to contrib to provide their own documentation.

Login flows should always use HTTPS, even if it's not required. FYI: https://docs.asp.net/en/latest/fundamentals/servers.html is in the process of being updated and will include basic kestrel HTTPS instructions. Watch for the PR.

**Comment by PinpointTownes** [comment]
> The callout to aspnet-contrib should be fine, but the asp.net docs should not include instructions for components in contrib (e.g. Yahoo). It's up to contrib to provide their own documentation.

We can't reasonably provide a tutorial for every provider supported (~35 IIRC), at least not without some help :trollface: 

The good news is that all the aspnet-contrib OAuth2 providers work exactly like their built-in ASP.NET Core friends, so the instructions to configure them shouldn't differ much (thanks to the lovely OAuth2 base middleware). 

That said, you might want to create a list of links pointing to the OAuth2 documentation of popular providers like Yahoo or Linked.

**Comment by Tratcher** [comment]
@PinpointTownes  No need for full tutorials for each provider, just links to each provider's setup pages/docs.

**Comment by 01binary** [comment]
Of the extra providers I mentioned, Yahoo does not behave like the others and cannot be run from localhost (would love to be proved wrong on this). I would say that was 80% of the reason I wanted to call it out, the other 30% being more likely for someone to try to implement because they want to support the top X popular providers. So perhaps a PR into @PinpointTownes about the Yahoo special case if time allows, otherwise just make a quick note about those providers and no separate sections.
