### ISSUE TITLE
How to show message when cookie expires

### ISSUE THREAD

**Issue by frostymarvelous** [aspnet/Security#1017]
I am trying to show a message to the user when the Authorization Cookie expires.

I'm not sure exactly where this happens, but when I checked, I found 

`ApplicationCookie.Events` which is an instance of `Microsoft.AspNetCore.Authentication.Cookies.ICookieAuthenticationEvents`. I suspect this might be what I need, but I don't know which event to hook up to.

Any help will be greatly appreciated.

**Comment by Tratcher** [comment]
For most purposes the system does not distinguish between an anonymous user and a user with an invalid/expired cookie. Cookie expiration also isn't a one-time event. On each request the client can send a valid cookie, an invalid/expired cookie, or no cookie. The client can keep sending an invalid cookie as long as they like. The cookie middleware only takes action for valid cookies.
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L106

You could check if an apparently anonymous user has an an expired cookie:
```
var authenticateContext = new AuthenticateContext(signInScheme);
await httpContext.Authentication.AuthenticateAsync(authenticateContext);
```
And check `authenticateContext.Error`

**Comment by frostymarvelous** [comment]
Thanks a lot.

I've been digging through the code and noticed what you said.

Your workaround will work fine enough for me. Thanks.

**Comment by frostymarvelous** [comment]
I can't seem to find out what the "signInScheme" is.

I've tried "Cookie", "Cookies", "cookie", "cookies" and even "Bearer".

I keep getting `No authentication handler is configured to authenticate for the scheme: cookie`.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationDefaults.cs#L16 if you're only using cookie auth. If you're using Identity then it assigns it's own.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Identity/blob/5480aa182bad3fb3b729a0169d0462873331e306/src/Microsoft.AspNetCore.Identity/IdentityCookieOptions.cs#L17

**Comment by frostymarvelous** [comment]
Thanks so much. I am using Identity.
This solves my problem.
