### ISSUE TITLE
AuthorizeAttribute for roles only work if role claims are in an array

### ISSUE THREAD

**Issue by ajtowf** [aspnet/Security#1018]
When using [AspNetCoreIdentity](https://github.com/aspnet/Identity) if the user only has one role the claim will look as:

```
role: "Administrator"
```

and if they have several:

```
role: [
    "Administrator",
    "User"
]
```

Decorating a controller with one of following lines:

```
[Authorize(Policy = "RequireAdministratorRole")]
[Authorize(Roles = "Administrator")]
```

where the policy is defined as:

```
services.AddAuthorization(options =>
{
    options.AddPolicy(
        "RequireAdministratorRole", 
        policy => policy.RequireRole("Administrator"));
});
```

we'll get access denied for the case where the user only has the Administrator role. As soon as the user role claims are in an array it works as expected.

Now I don't know if this should be an AspNetIdentity bug or security bug. You might as well just say that they should always wrap the result in an array, but on the other hand, why not handle both here?

I'm getting this behavior when using 1.1.0-preview1-final of all the involved libs.
This is really basic stuff, I'm hoping that I've missed something obvious, but I doubt it.

Workaround for now is to always add users to at least two roles...

**Comment by Eilon** [comment]
@ajtowf where are the roles actually defined? The issue shows some JSON-like syntax but without knowing where it comes from it's hard to say how to fix it.

**Comment by ajtowf** [comment]
@Eilon the roles are defined with [AspNetIdentity](https://github.com/aspnet/Identity), and persisted with EntityFramework Core.

**Comment by Eilon** [comment]
@ajtowf got it. In what place are the roles then represented as either an array or a string? I'm not aware of any place in the ASP.NET Core libraries where roles are represented in multiple ways - it's generally fairly consistent.

**Comment by ajtowf** [comment]
For some reason I have the roles added as two different role claim types, I've issued a claimsidentity from an identityserver with only "role" as claimtype for roles, but for some reason when debugging from the RP I have "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" as claimtype as well. Nevertheless, it's clear that the roleclaimtype is "role", so I'm guessing this should work anyways, right?

![image](https://cloud.githubusercontent.com/assets/3427270/20132517/a59f715c-a663-11e6-9594-0feaf3ef638a.png)

And it's very clear that if I only have one role, Administrator, the authorize attribute will fail to validate, but if I also have the user role as seen in the image, it will succeed.

**Comment by ajtowf** [comment]
Oh my god, just added the following line to the MVC app and everything looked fine and worked as expected after that.

    JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

![image](https://cloud.githubusercontent.com/assets/3427270/20133967/f0cbef56-a669-11e6-9046-81b5c30cc345.png)

Sorry for wasting your time!

**Comment by Eilon** [comment]
No worries, glad you got it figured out!
