### ISSUE TITLE
Consider an AzureAD middleware? (Multi tenant)

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#102]
_From @mbeckenbach on November 22, 2014 19:44_

An azure ad middleware (that supports also multi tenant or mixed mode with local users) should be as important as the facebook login. 

.Net is still mostly used in enterprise. Enterprises need something made for enterprises. not facebook. 

Please extend your development, documentation and support for your own authorization technologies.
On MyGet there are already vnext packages for google, facebook and co. but nothing for windows auth or azure ad. Even on "vLast" azure ad via oauth / open id is not really good documented or implemented until today.

_Copied from original issue: aspnet/Identity#267_

**Comment by jaredcnance** [comment]
What is the status on being able to treat Azure AD like any other OAuth provider as @Tratcher demonstrates above?

It seems odd to me that Azure AD provides OAuth endpoints but I can't seem to get the middleware to work with it.

**Comment by Tratcher** [comment]
@jaredcnance Any reason you can't use the OpenIdConnect middleware?
