### ISSUE TITLE
Different login pages for different claims

### ISSUE THREAD

**Issue by andreymir** [aspnet/Security#1022]
To do some actions on the web site user should be authenticated. Different actions require different claims. For example, to make an order user is authenticated by phone number only, to view the purchase history user should be authenticated by phone number and password, and to change the phone number user should be authenticated using two-factor authentication.

I create a login page for each of the authentication methods and when user is authenticated I give her a set of claims depending on the authentication method. I add `[Authorize(Policy="CanCreateOrder")]` to the `CreateOrder` action method. The policy has the logic what claims required to authorize user. In case user is not authorized I want to redirect the user to the appropriate login page.

The question is how I could specify the url where user should be redirected for authentication?

Looking at `CookieAuthenticationMiddleware` I could not see how to to specify login page depending on what claims required. Documentation suggests to set `LoginPath` property at the configuration time, but in my case login url depends on what claims I need to authorize the user.

**Comment by Tratcher** [comment]
Given the multiple overlapping kinds of auth it may be appropriate to have three instances of the cookie auth middleware. On Authorize you'd specify the appropriate scheme.

Or you could store that information somewhere and override OnRedirectToLogin.
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/Events/CookieAuthenticationEvents.cs#L41

Or you store the login type required in a cookie or session and check it when you get to the login page.

**Comment by andreymir** [comment]
Thanks! `OnRedirectToLogin` looks promising.
