### ISSUE TITLE
Bring back OAuth bearer authentication

### ISSUE THREAD

**Issue by chrisdrobison** [aspnet/Security#1023]
In the Katana implementation, there was a middleware piece that allowed for authenticating OAuth 2 bearer tokens, whether from the Authorization header, query string or form body. Although, that implementation seemed to be tied to having the token generated from the companion OAuth 2 server. ASP.NET Core has a Jwt bearer midddleware option, but that is too specific for OAuth 2 access tokens. Access tokens can be anything. Would it be possible to add back a middleware piece that would allow for validating generic OAuth 2 bearer tokens? This is important for doing APIs.

**Comment by brockallen** [comment]
If your token is backed by the OAuth2 introspection spec, then there is already a middleware for that: https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection

**Comment by PinpointTownes** [comment]
@chrisdrobison if you're looking for an `OAuthBearerAuthenticationMiddleware` equivalent in the vNext world, you can look at the [aspnet-contrib validation middleware](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/tree/dev/src/AspNet.Security.OAuth.Validation).

**Comment by chrisdrobison** [comment]
Those are some good suggestions. I will try those.
