### ISSUE TITLE
OIDC response messages should remain unchanged during processing

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#1025]
When OIDC is flowing messages through events such as: RunTokenValidatedEventAsync the values obtained from the wire should be sent to the OIDCProtocolValidator as they are received. Currently the runtime can modify what is passed to the user.

**Comment by Tratcher** [comment]
All of the events do this, this is part of the extensibility. For better or worse all of the properties on the event context objects are settable. If the dev decides to override these values we want to make sure they flow through the remainder of the auth processing and events. One reason they may want to replace the value is that it's the only way to inject a message object that derives from OpenIdConnectMessage to override behavior.

**Comment by Tratcher** [comment]
By design. This is intentional extensibility.
