### ISSUE TITLE
SAML-P Authentication

### ISSUE THREAD

**Issue by axelheer** [aspnet/Security#1026]
Any plans for a SAML authentication middle-ware?

I know, it's not the shiny new thing, but it's still out there. Any guidance on how to use a SAML Identity Provider for a ASP.NET Core application would be very much appreciate as well.

**Comment by Tratcher** [comment]
You mean WsFederation? https://github.com/aspnet/Security/issues/43

**Comment by PinpointTownes** [comment]
@axelheer if by SAML you mean the SAML 2.0 protocol (SAMLP), then you can find a community implementation here: https://github.com/KentorIT/authservices/blob/aspnetcore/Kentor.AuthServices.AspNetCore

It's still a WIP and it doesn't work on .NET Core, but it's pretty much your best chance (AFAIK, SAMLP has never been officially supported on ASP.NET/OWIN/Katana, so I doubt it will ever be)

**Comment by axelheer** [comment]
I mean the SAML 2.0 protocol (SAMLP), not WsFederation.

The Kentor repository says "The build is not working yet", so I didn't look any further.

There are also:
https://github.com/i8beef/SAML2
https://github.com/elerch/SAML2

But both don't seem to make any progress towards .NET Core.

Maybe I try to invest some work into one of these, but right now I'm just interested if there will be some kind of official / recommended solution. Since we're talking about security, I find the idea of just hacking something together not very appealing...

And just because there was no support doesn't mean there won't be any either. ;)

On the commercial side is something going on too, by the way:
http://www.componentspace.com/Products.aspx
http://www.componentspace.com/Forums/3170/ComponentSpace-SAML-10-with-ASPNET-Core-Rc2

**Comment by Gillardo** [comment]
Did you manage to implement this or find a working project to implement SAML2?

**Comment by axelheer** [comment]
@Gillardo the Saml2 library by @ITFoxtec works with ASP.NET Core, although you have to stick with the full .NET Framework as the runtime -- .NET Core does not work!

I've now a working prototype for my project using that library, but maybe I'm going to implement something on my own. But I only need to support one specific Identity Provider, which shouldn't be that hard without the whole ceremony...

**Comment by PinpointTownes** [comment]
@Tratcher any chance you could remove the duplicate flag from this ticket? SAML-P and WS-Fed are two separate protocols, so the other ticket is not a duplicate.

**Comment by agc93** [comment]
Has there been any movement on this? 

My customer uses SAML for SSO and it looks like I'm going to have to move away from ASP.NET Core as I can't find a working SAML 2.0 provider for ASP.NET Core.

**Comment by Gillardo** [comment]
I am using saml with dotnet core... but I had to pur cu ase the software... although it was very cheap. If u want to PM me I will let u know details

**Comment by Eilon** [comment]
Closing because we are not planning to add support for SAML.
