### ISSUE TITLE
OIDC: reconcile claims from multiple endpoints

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1028]
OIDC may receive claims from the Authorization Endpoint (id_token), the Token Endpoint (id_token), and the UserInfoEndpoint. In the code+id_token Hybrid flow it's possible to receive all three of these on the same login. Currently in this flow claims from the Token Endpoint are ignored in favor of those from the Authorization Endpoint. The UserInfoEndpoint claims are then added on top (how does it manage conflicts/duplicates today?).

The spec (http://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken2) says that "If either ID Token contains Claims about the End-User, any that are present in both SHOULD have the same values in both. Note that the OP MAY choose to return fewer Claims about the End-User from the Authorization Endpoint, for instance, for privacy reasons.". By this logic we should prefer the claims from the Token Endpoint, or at least merge them.

**Comment by Eilon** [comment]
Looks like we'll do https://github.com/aspnet/Security/issues/1027 instead of this so that the app developer can handle this.
