### ISSUE TITLE
Support Client Credentials Grant Access Token Request

### ISSUE THREAD

**Issue by manbearwiz** [aspnet/Security#1036]
I am attempting to implement the Client Credentials Flow for server to server communication as outlined in the [OAuth 2.0 standard](https://tools.ietf.org/html/rfc6749#section-4.4) and do not see a way to easily do this using OAuthHandler/OAuthMiddleware.

**Comment by leastprivilege** [comment]
If you need token issuance capabilities, you can use identityserver for that. See here:
http://docs.identityserver.io/en/release/quickstarts/1_client_credentials.html





On Fri, Nov 11, 2016 at 6:01 PM +0100, "Kevin Brey" <notifications@github.com> wrote:












I am attempting to implement the Client Credentials Flow for server to server communication as outlined in the OAuth 2.0 standard and do not see a way to easily do this using OAuthHandler/OAuthMiddleware.

**Comment by manbearwiz** [comment]
I already have the auth server set up and I can successfully get a bearer token by forwarding the credentials passed in from the basic authorization header. I just would like to move this code into middleware so it is invoked by the AuthorizeAttribute rather then having to do it manually on each call. Maybe I'm way off-base here.

```
[HttpGet]
public async Task<string> Get()
{
    string token = await this.GetRenLearnApiTokenAsync();

    using (var client = new HttpClient())
    {
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

        var response = await client.GetAsync(Options.ServiceBAddress);

        return await response.Content.ReadAsStringAsync();
    }
}

private async Task<string> GetRenLearnApiTokenAsync()
{
    string token = memoryCache.Get("token")?.ToString();
    if (string.IsNullOrEmpty(token))
    {
        using (var tokenClient = new PassthroughTokenClient(Options.TokenEndpoint, /* encoded credentials from request */))
        {
            var tokenResponse = await tokenClient.RequestClientCredentialsAsync(Options.ServiceBIdentifier);

            token = tokenResponse.AccessToken;

            memoryCache.Set("token", token, new DateTimeOffset(DateTime.Now.AddSeconds(tokenResponse.ExpiresIn)));
        }
    }

    return token;
}
```

Extending TokenClient so it can take credentials that have already been encoded.

```
public class PassthroughTokenClient : TokenClient
{
    public PassthroughTokenClient(string address, string encodedCredentials )
        : base(address, new HttpClientHandler())
    {
        AuthenticationStyle = AuthenticationStyle.BasicAuthentication;
        _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", encodedCredentials);
    }
}
```

**Comment by PinpointTownes** [comment]
@manbearwiz IMHO, the client credentials grant type is not a very good fit for the OAuth2 or the OIDC middleware, that are specially designed to handle interactive flows involving user agents (= user's browser).

**Comment by manbearwiz** [comment]
Yah that is the impression I was getting the more I dug into the OAuth middleware. I had assumed that the OAuth middleware was attempting to support all of the OAuth grant types but it seems to mostly be meant for redirection-based flows. Any guesses as to the easiest way to implement client credentials using aspnet auth?

**Comment by PinpointTownes** [comment]
>  I had assumed that the OAuth middleware was attempting to support all of the OAuth grant types but it seems to mostly be meant for redirection-based flows.

Yep, the OAuth2 base middleware only supports the authorization code flow.

> Any guesses as to the easiest way to implement client credentials using aspnet auth?

Your approach seems fine (it's also how I'd personally implement it)

**Comment by manbearwiz** [comment]
>Your approach seems fine (it's also how I'd personally implement it)

My issue with that is that it requires code in each api method. I would much prefer to just stick `[Authorize]` on the controller and be done. I had originally planned on writing a custom authorization filter until I read the below in the documentation.

>You should only write a custom authorization filter if you are writing your own authorization framework.

Would this still be a case to implement a custom authorization filter?

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
