### ISSUE TITLE
OpenIdConnectMiddleware:  Not redirecting to Identity Provider

### ISSUE THREAD

**Issue by mclark1129** [aspnet/Security#1038]
After upgrading from 1.0.0 to 1.1.0-preview1-final my client is no longer being redirected to the Identity Provider on initial challenge.  The result is that any request to an action secured by `[Authorize]` fails immediately with a 401.  I see that the handler is getting configuration from the discovery endpoint, and building the correct redirect URI to the authorize endpoint.  However, when it calls `Response.Redirect` in OpenIdConnectHandler.cs#367 the request is never received by my Identity Server.

After upgrading I made no changes to my middleware, which was working in 1.0.0 so I'm not sure if the latest version requires any kind of additional adjustments to my configuration.  I've tried clearing out and rebuilding all the packages from source and so far no luck.  I expect this is most likely something I'm doing wrong, but I have no idea what would have changed from 1.0.0 that would change this behavior.

**Comment by PinpointTownes** [comment]
Just to be sure: have you set `AutomaticChallenge` to `true` in the OpenID Connect options?

**Comment by mclark1129** [comment]
I did not have that there already, but even after setting that property the result is the same.  Regardless of whether or not I specify it I see the middleware execute the challenge for my `oidc` scheme.  I did not have to specify this property in 1.0.0 either.

It looks like the code is behaving almost exactly as before, but just that the call to `Response.Redirect(redirectUri)` just fails silently and moves on.

**Comment by Tratcher** [comment]
Please share your relevant startup code. In fiddler what does the response look like? Is there a Location header?

There was a regression here with IIS that should have been fixed for preview1. https://github.com/aspnet/IISIntegration/commit/3181c3f2e39fdf49a38bae6ea1dc606b884236e9

**Comment by mclark1129** [comment]
@Tratcher Looks the IISIntegration issue is the problem.  I only upgraded the relevant Authentication libraries from this repository to 1.1.0-preview1-final.  I did not realize I would have to upgrade any other packages.  After upgrading IISIntegration my issue is resolved, are there any other packages beyond Authentication that I should upgrade for my MVC application?  Right now I have:

**Authentication:**
"Microsoft.AspNetCore.Authentication.Cookies": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.1.0-preview1-final",
    "Microsoft.IdentityModel.Tokens": "5.0.1-pre-310121323",
    "Microsoft.AspNetCore.Authentication": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Http.Abstractions": "1.1.0-preview1-final",
    "Microsoft.AspNetCore.Authorization": "1.1.0-preview1-final",

**IIS**
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0-preview1-final",

And went to MVC 1.0.1 for good measure, everything else is 1.0.0.

**Comment by Tratcher** [comment]
Avoid mixing versions when possible, update everything to 1.1.0-preview1.

**Comment by mclark1129** [comment]
Ok my mistake, I didn't realize all packages across aspnet were in the same release cycle.  Will keep that in mind for future upgrades!

Thanks again.
