### ISSUE TITLE
RemoteAuthenticationTimeout and Correlation Failed

### ISSUE THREAD

**Issue by muena** [aspnet/Security#1042]
Hi,
I know it's not a bug but a question, but can someone please explain me how it is designed to work?

I have a client using oidc. When the user stays on the logon page (longer than the configured RemoteAuthenticationTimeout) and then submits it, a RemoteFailure event gets triggered on the client with a "Correlation failed" message. But it is authenticated.

AFAIK the correlation cookie prevents the authentication from being hijacked.
Can you please explain me how I should handle the correlation failed error in that case?
Thank you!

**Comment by Tratcher** [comment]
If the login takes too long such that the temp state like the correlation cookie are discarded then you should ask the user to re-start the login flow.
