### ISSUE TITLE
Depending on Microsoft.AspNetCore.Authentication 1.1.0 causes a failure to resolve System.Net.Http when targeting the full framework.

### ISSUE THREAD

**Issue by jkells** [aspnet/Security#1046]
### Minimal repro steps
*I have attached a project that reproduces the issue.*
[SystemNetHttpClientIssue.zip](https://github.com/aspnet/Security/files/605636/SystemNetHttpClientIssue.zip)
1. Create a NetCore library project and NetCore console project targeting *net46*
2. In the Library project depend on NetStandard.Library 1.6.1
3. In the Library project make use of System.Net.Http
4. In the console app, reference Microsoft.AspNetCore.Authentication 1.1.0
5. In the console app reference and use the library project.

### Expected result
The application should use System.Net.Http == 4.3.0 as defined in NetStandard 1.6.1 which correctly works on both the core and full framework.

### Actual result
The application doesn't copy any System.Net.Http dll into the output folder.

The application will crash with FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### Further technical details
I believe this issue is related to a problem in the 4.1.0 version of the System.Net.Http package.
https://github.com/dotnet/corefx/issues/9884
https://github.com/dotnet/corefx/issues/9846

With the release of Asp.NET Core 1.1 the issue is fixed across all the packages I'm using except for this one. I believe it's related to this entry in your project.json file.

```
    "net451": {
      "frameworkAssemblies": {
        "System.Net.Http": ""
      }
```

Building a custom version of Microsoft.AspNetCore.Authentication without the dependency on "System.Net.Http" from the framework does fix the issue for me.

**Comment by RaviDesai** [comment]
I'm having this issue on a aspnetcore 1.1 app in VisualStudioCode (on my mac) targeting dotnet 5.6 and portable-net45+win8.  Just upgraded this app from aspnetcore 1.0, where the reference to System.Net.Http worked fine.  

```
"frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.1.0",
          "type": "platform"
        }
      },
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },
```

It sounds like you have some kind of work-around, but I'm not sure I understand it.  Can you elaborate?

**Comment by Eilon** [comment]
@anurse, @muratg will come talk to you about this.

**Comment by anurse** [comment]
This appears to be a packaging issue with our Authentication package. I've updated @muratg and @pranavkm with some information on it, and we'll investigate how best to fix this issue. Unfortunately I haven't been able to find a good workaround, short of downgrading back to `net451` which should not exhibit this issue.

**Comment by Tratcher** [comment]
Yes, I was able to work around this in the given repro app by downgrading the Lib project from net46 to net452.

**Comment by SteveSandersonMS** [comment]
@anurse Might this also be the underlying cause for https://github.com/aspnet/JavaScriptServices/issues/487? Please let me know if this is likely to be fixed in 1.1.1.

**Comment by anurse** [comment]
It certainly could be related. I don't know exactly what the plan is for fixing the issue in 1.1.1, since I've been OOF for a week, but in theory there are a few cases in our repositories where this issue could arise.

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by Tratcher** [comment]
Note the frameworkAssemblies references were removed from dev as part of the xproj->csproj conversion. We only need to clean this up in the patch branches.

**Comment by sm-g** [comment]
@anurse your commit in `rel/1.1.1` branch, does that mean that AspNetCore 1.1.1 nuget packages will contain it soon? If yes - when?

**Comment by Eilon** [comment]
@sm-g we're working on the 1.1.1 release right now (obviously 😄 ) and we hope to have the official release out within 1 month.

**Comment by FelschR** [comment]
Is it right to assume that 1.1.1 will be published before/alongside VS2017's release in March?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Home/wiki/Roadmap Feb, with 1.0.4

**Comment by Eilon** [comment]
@FelschR we're still figuring out the details on exactly when the two releases will go live, but it'll certainly be close!

**Comment by emirhosseini** [comment]
What do you mean by Asp.Net Core 1.1.1?  There's no such NuGet package.  There's "Microsoft.AspNetCore.**Mvc**" which is already on 1.1.1.  Please clarify exactly what you're talking about.

**Comment by Tratcher** [comment]
@emirhosseini 1.1.1 is the version of the upcoming patch for this repo.

**Comment by marianosz** [comment]
When will be released?

**Comment by Eilon** [comment]
@marianosz the plan is to have it out later this month. We're just nearly done with all the fixes, and we're working on getting the final builds put together and doing additional testing.

**Comment by marianosz** [comment]
Thanks for the info!

**Comment by marianosz** [comment]
I'm still facing the same issue with all the packages updated using net462... Any workarounds?

**Comment by Maritims** [comment]
I am also experiencing this issue with everything updated and running net461
