### ISSUE TITLE
Correlation cookie expire date and invalid client time

### ISSUE THREAD

**Issue by FredrikK** [aspnet/Security#1047]
When creating the correlation cookie an absolute expire date is set:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs#L193
If Options.RemoteAuthenticationTimeout is 0 then the expire date will be set to now.

If the clients computer time is not correct and is set to sometime in the future that is greater than Options.RemoteAuthenticationTimeout the correlation cookie will never be sent back.

##### EXAMPLE:
The time is 1:00 AM UTC
The users computer clock is 2:00 AM UTC
The correlation cookie will expire with the default value of 15 minutes at 1:15 AM UTC
When the user returns after authentication (computer clock 2:02 AM) no correlation cookie will be sent since it expired 47 minutes ago.

##### NOTE:
Browsers handle cookie expiration differently. IE has this problem while Chrome and Firefox checks the server time header. See more here: https://bugs.chromium.org/p/chromium/issues/detail?id=150066#c50

> IE does not compare the expiration date of the cookie to the server time (both will be in the response), it only compares the cookie expiration date to the client machine date, and it sets it accordingly.
> 
> Chrome and Firefox, they compare the cookie expiration date with both the server time and the client machine time, and if it finds that it already expired compared to server time then it will not set the cookie.

##### SOLUTION:
Do not use cookie expiration date. If RemoteAuthenticationTimeout is needed, set a timestamp in the state?

**Comment by Tratcher** [comment]
FYI: This timeout was added to limit the buildup of stale cookies on the client due to incomplete auth flows.

I agree this is a problem in theory, but how frequently have you seen clients fail because of it in production? This is the first report we've had for this issue. Most computers sync their time automatically.

**Comment by FredrikK** [comment]
Yes, we understand the need of not leaving a lot of dead cookies behind. 
Even a session cookie could be quite ugly, especially on Chrome you could build up a lot of old cookies that are not deleted until you reboot your computer.

Our quick analyze shows that 0.1% of the users are experiencing this. Not that many, but for them it's a show stopper as they will not be able to log in.

Is it possible to set a session cookie if Options.RemoteAuthenticationTimeout is zero?

**Comment by Tratcher** [comment]
Timeout.InfinateTimeSpan (-1 s) would be more conventional.

**Comment by FredrikK** [comment]
Yes. That would work.

**Comment by FredrikK** [comment]
If this is an acceptable solution, would you like a pull request or will this do?

**Comment by Eilon** [comment]
We are not planning to change this behavior, so the recommended workaround is to set the default timeout to a higher value (e.g. 2 hours, or even 2 centuries 😄 ).
