### ISSUE TITLE
signin-oidc callback fails with 502 Bad Gateway at Azure/IIS with cookie session store

### ISSUE THREAD

**Issue by LeandroPT** [aspnet/Security#1049]
Hey guys,

I don't know what you have done in 1.1.0 but openid does not seem to be working at all at Azure.

I have upgraded my webapp from 1.0.1 to 1.1.0, and besides the nag about the automatic[Challenge/Authenticate] between cookie and openid it works just fine on local machine.

However in Azure, when processing the callback for /signin-oidc i just get "The specified CGI application encountered an error and the server terminated the process."

stdout Log files show nothing:
```
trce: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware[35]
      => RequestId:0HL0K066O9S44 RequestPath:/signin-oidc
      User information received: {
        "sub": "ea961c94-9bcf-4ff0-a458-6750fbd27942",
        "updated_at": 1473159001,
        "preferred_username": "leandropt",
        "email": "leandro.teixeira@lost.com",
        "email_verified": "false",
        "name": "Leandro Teixeira"
      }
trce: Client.Portal.App_Start.CoreStartup[0]
      => RequestId:0HL0K066O9S44 RequestPath:/signin-oidc => OnUserInformationReceived
      Obtaining other special needed Claims...
trce: Client.Portal.App_Start.CoreStartup[0]
      => RequestId:0HL0K066O9S44 RequestPath:/signin-oidc => OnUserInformationReceived
      Got 132 claims.
```
however, if i activate the log stream, i get an html with the following content:
HTTP Error 500.0 - Internal Server Error
The page cannot be displayed because an internal server error has occurred.
Detailed Error Information:
Module	   AspNetCoreModule
Notification	   ExecuteRequestHandler
Handler	   aspNetCore
Error Code	   0x00000000
Requested URL	   https://**app-dev**:80/signin-oidc
Physical Path	   D:\home\site\wwwroot\signin-oidc
Logon Method	   Anonymous
Logon User	   Anonymous

The application then auto restarts.

What i find weird is that the html generated in log does not show up anywhere on the browser.
Another weird thing is that the "requested URL" misses the azurewebsites.net, it should be requesting app-dev.azurewebsites.net.....

I have been reading #930 #1044 but i think i should be able to replicate on local machine....

I also thought it was related to #140, but it seems that is not the problem.

Any thoughts?

**Comment by LeandroPT** [comment]
Found out some more things...

Because of cookie size restriction in IOS i used to store cookie info on azure... apparently there is an issue there i did not yet discovered..

Any thoughts?

**Comment by Tratcher** [comment]
What cookie session store are you using? We don't actually ship any implementations. Does your app work if you disable the cookie session store?

**Comment by LeandroPT** [comment]
Hello,

Yep, i made a custom one using REdis Cache.

If i turn it off it works, apparently it is a "hack" like this:

`public class RedisCacheTicketStore : ITicketStore
    {
        private const string KeyPrefix = "AuthSessionStore-";
        private IDistributedCache _cache;

        public RedisCacheTicketStore(IServiceProvider serviceProvider)
        {
            this._cache = serviceProvider.GetRequiredService<IDistributedCache>();
        }

        public async Task<string> StoreAsync(AuthenticationTicket ticket)
        {
            var guid = Guid.NewGuid();
            var key = KeyPrefix + guid.ToString();
            await RenewAsync(key, ticket);
            return key;
        }

        public async Task RenewAsync(string key, AuthenticationTicket ticket)
        {
            try
            {
                var options = new DistributedCacheEntryOptions();
                var expiresUtc = ticket.Properties.ExpiresUtc;
                if (expiresUtc.HasValue)
                {
                    options.SetAbsoluteExpiration(expiresUtc.Value);
                }
                if (ticket.Properties.AllowRefresh.GetValueOrDefault(false))
                {
                    options.SetSlidingExpiration(TimeSpan.FromMinutes(30)); // TODO: configurable.
                }
                await _cache.SetAsync(key, TicketSerializer.Default.Serialize(ticket), options);
            }
            catch
            {
                //ignore
            }
        }

        public async Task<AuthenticationTicket> RetrieveAsync(string key)
        {
            AuthenticationTicket ticket = null;
            try
            {
                byte[] value = await _cache.GetAsync(key);
                if (value != null)
                {
                    ticket = TicketSerializer.Default.Deserialize(value);
                }
                else
                {
                    ticket = null;
                }
            }
            catch
            {
                //ignore
            }
            return ticket;
        }

        public async Task RemoveAsync(string key)
        {
            try
            {
                await _cache.RemoveAsync(key);
            }
            catch
            {
                //ignore
            }
        }`

I will see what is going on with 1.1.0 [Not working] vs 1.0.1 [Was working] and post conclusions later.

**Comment by danroth27** [comment]
@LeandroPT Any update on your investigation?

**Comment by LeandroPT** [comment]
Hello,

Yeah, i found it was caused by incorrect runtime and build.

I am using the build on Team Services online, and despite i changed the en var for dotnet path it was building incorrectly.

Changed back to the RC2 build script  with the correct version and it works like a charm.

**Comment by danroth27** [comment]
OK. Are we ok to close this issue then? It sounds like you've resolved your own issue. Let us know though if there is more here for us to investigate. We want to ensure that 1.1 is as compatible as possible with 1.0.

**Comment by LeandroPT** [comment]
Hey,

Yes, it can be closed. The major issues i am facing now is the change in .Net framework Core behavior change.

**Comment by danroth27** [comment]
> The major issues i am facing now is the change in .Net framework Core behavior change.

Which changes are you referring to? As I said previously our intent is that 1.1 should be fully compatible with 1.0. If you are seeing that this is not the case then please let us know.

**Comment by LeandroPT** [comment]
The changes i am referring to is the change of behavior on left Joins, Outer Joins, Contains, etc.

Bu i kind of expected those, the issue is that the same query in EF1.0 does not behave same way on 1.1.

And since, it is much faster now, a mis-written/mis-parsed query will eat all CPU in a snap, since it will execute on "client side".

But all is good, almost there :)

**Comment by danroth27** [comment]
> The changes i am referring to is the change of behavior on left Joins, Outer Joins, Contains, etc.
> But i kind of expected those, the issue is that the same query in EF1.0 does not behave same way on 1.1.

@rowanmiller @divega Are these expected changes?

**Comment by divega** [comment]
@danroth27 @leandropt we made several improvements to EF Core 1.1 that are expected to change SQL generation and in the majority of cases move more of the query processing to the database server.

If you hit unexpected changes in behavior that break your applications please report those to the EntityFramework repo.
