### ISSUE TITLE
Extract classes to use social login infrastructure independently

### ISSUE THREAD

**Issue by hikalkan** [aspnet/Security#1050]
I suggest you to extract classes to use social login infrastructure independently.
I'm creating an Angular2 SPA which will have social login feature. But I can not use ASPNET Core's built-in social login middlewares, since this is a SPA. On the other hand, ASPNET Core has already contains code to get user information (name, email...) from facebook, google, twitter... but highly mixed with the middleware code and not inpdependently usable. It would be very good if you extract that functionality into their own classes and make them directly usable by us.
Thanks.

**Comment by Webbanditten** [comment]
Yes the social login middleware would be awesome to have decoupled.

**Comment by Tratcher** [comment]
These providers all have SDKs that you should be using for this.

**Comment by hikalkan** [comment]
We know that we can find some libraries to do that (while some of them are outdated and not official) but it would be nice to get basic user information with a given access key and this is already done in aspnet core social login provider packages.
