### ISSUE TITLE
FileLoadException with Microsoft.AspNetCore.Authentication.JwtBearer

### ISSUE THREAD

**Issue by kierenj** [aspnet/Security#1051]
I get the following exception when I try to create an instance of `JwtBearerOptions`:

```
Exception thrown: 'System.IO.FileLoadException' in MyProj.Authentication.dll

Additional information: Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.1.0.832, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

My project.json:

```json
{
  "version": "1.2.0-*",
  "description": "MyProj authentication module",

  "dependencies": {
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.Extensions.Options": "1.1.0",
    "Newtonsoft.Json": "9.0.1",
    "MyProj.Core": "0.2.0-*"
  },

  "frameworks": {
    "netstandard1.6": {
      "dependencies":{
        "NETStandard.Library": "1.6.1"
      }
    }
  }
}
```

Adding `"Microsoft.IdentityModel.Tokens": "5.1.0",` as a dependency results in the same exception.

In VS at least, I don't get any underlines in project.json, `dotnet restore` doesn't give any warnings/errors.  I'm happy to help debug, but fuslogvw is a mess (which version do I have to use?  It never seems to work!).

**Comment by davidfowl** [comment]
This is a single `project.json` and I'm assuming you didn't run a library project. Where is the application? Can you also post the lock files?

**Comment by kierenj** [comment]
Ok sure, like I say, happy to help.  There's quite a graph of projects, and I wasn't sure what would be most useful to diagnose.  I'll prep a bundle of this stuff.

**Comment by davidfowl** [comment]
Best would be a github repository.

**Comment by kierenj** [comment]
It will take a little longer to get a buildable repro project together, but here's a repo with the appropriate structure, `project.json` and lock files.

https://github.com/RedRiverSoftware/netcore-repros/tree/aspnet_security_1051_repro

Startup project is at https://github.com/RedRiverSoftware/netcore-repros/tree/aspnet_security_1051_repro/src/myproj .

**Comment by JaPawel** [comment]
Same here:
`Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.IdentityModel.Logging, Version=1.1.0.832, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler..cctor()
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler..ctor()
   at Microsoft.AspNetCore.Builder.JwtBearerOptions..ctor()
   at JwtBearerSample.Startup.Configure(IApplicationBuilder app) in C:\test\Security-rel-1.1.0\Startup.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at JwtBearerSample.Program.Main(String[] args) in C:\test\Security-rel-1.1.0\Program.cs:line 11`

To reproduce this error I simply downloaded sample "JwtBearerSample" from this repo (rel-1.1.0 or rel-1.1.0-preview1 or dev). When I switch to 1.0.0:
`"Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0"`
sample works without error.

In my nuget package Microsoft.IdentityModel.Logging is 1.1.0.143

What's important, this happens only on one computer (PC). This sample (and also my app where I use Jwt middleware) works fine on my other PC and on my MAC.

**Comment by Tratcher** [comment]
@kierenj  There was an issue with the 1.1 packages when we first uploaded them where we had built against the wrong version of the IdentityModel packages. We quickly deleted the affected packages and uploaded a corrected version. If you delete your local package cache and then run restore you should get the correct package.
Go to `C:\Users\[username]\.nuget\packages` and delete `Microsoft.AspNetCore.Authentication.JwtBearer` and `Microsoft.AspNetCore.Authentication.OpenIdConnect`.

**Comment by JaPawel** [comment]
@Tratcher tried that before but as I suppose I was removing wrong files (not those you listed). Now to be sure, removed whole .nuget\packages and everything works fine. Awesome thanks!

**Comment by kierenj** [comment]
@Tracher, for whatever reason, this didn't solve the issue for me.  I deleted the folders, and after a restore, they were re-created.  The exception remained however.  I then tried clearing out the entire package folder, and using `dotnet restore --no-cache` just in case.  I get the same exception, unfortunately - both from commandline and running under VS.

What else can I try / do to diagnose?

**Comment by Tratcher** [comment]
Try closing everything and doing
`nuget.exe locals all -clear`
https://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference#locals

Also clean your project (git clean -xdf if it's a git repo) before running restore again.

**Comment by kierenj** [comment]
Thanks for the suggestion, cleaned everything with NuGet and the repo, then it took a long while to restore, then:

```
An unhandled exception of type 'System.IO.FileLoadException' occurred in System.Private.CoreLib.ni.dll

Additional information: Could not load file or assembly 'Microsoft.IdentityModel.Protocols, Version=2.1.0.832, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

It's not `.Tokens`, but `.Protocols`, now.

**Comment by Tratcher** [comment]
That doesn't make much sense, Microsoft.IdentityModel.Protocols is what depends on System.IdentityModel.Tokens.Jwt and Microsoft.IdentityModel.Tokens. You don't have any other nuget feeds configured do you? Like our nightly feeds?

My only other idea is to clear all your caches and use Fiddler or a network trace to verify where you're pulling the package from. I wonder if the bad packages are cached on a proxy somewhere.

**Comment by kierenj** [comment]
Yes indeed as per my final line there (and demo repo), I have the nightly feeds too.  I feel like that should be an "aha" moment based on your last comment, but it doesn't quite all add up just yet - no package restore warnings, is it just that the nightlies still have the 'wrong' versions, or refer to something not publicly published, but that wouldn't cause a package restore error?

**Comment by Tratcher** [comment]
It's not a package restore issue per say, it's the fact that we published a bad JwtBearer 1.1 package, deleted it, and then published a new JwtBearer 1.1 package. Nuget can't tell the difference, so it may be picking up the bad version from a cache somewhere. We initially had this issue with the CDN but we got that fixed pretty quickly.

Even the nightly feed shouldn't cause a problem if you reference "1.1.0" exactly, with no `-*` suffix. 1.1.0 only exists on nuget.org.

**Comment by kierenj** [comment]
Humm OK, I see.  I've tried this from the coffee shop I was in the first time around, then the office, and at home.   I tried a fiddler trace, but nuget doesn't like the HTTPS interception (failed to establish connection..) even after trusting the cert, and specifying http in the nuget.config didn't change anything - it still tried https.
Anything else I can do - with the debugger, with ilspy, or ildasm, or something else?

**Comment by kierenj** [comment]
Well, ignoring the connection errors, it does still seem to download the JwtBearer package.

First request to regular feed:

```http
GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.authentication.jwtbearer/index.json HTTP/1.1
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
User-Agent: NuGet xplat/3.5.0-beta2-1484 (Microsoft Windows 10.0.14393 )
Host: api.nuget.org
```

This yields the main release versions, including 1.1.0.

Next it tries the nightlies:

```http
GET https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-dev/nuget/v3/flatcontainer/microsoft.aspnetcore.authentication.jwtbearer/index.json HTTP/1.1
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
User-Agent: NuGet xplat/3.5.0-beta2-1484 (Microsoft Windows 10.0.14393 )
Host: dotnetmyget.blob.core.windows.net
```

This gives only preview versions.  So, it decides to download 1.1.0 proper:

```http
GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.authentication.jwtbearer/1.1.0/microsoft.aspnetcore.authentication.jwtbearer.1.1.0.nupkg HTTP/1.1
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
User-Agent: NuGet xplat/3.5.0-beta2-1484 (Microsoft Windows 10.0.14393 )
Host: api.nuget.org
```

Fiddler response:

```http
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-ms-request-id,Server,x-ms-version,Content-Length,Date,Transfer-Encoding
Cache-Control: max-age=120
Content-MD5: nXaCJFzoLWYyYaH2gYOc4A==
Content-Type: application/octet-stream
Date: Fri, 02 Dec 2016 07:05:33 GMT
Etag: 0x8D40E2F8E3E32B0
Last-Modified: Wed, 16 Nov 2016 14:47:57 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
X-Cache: HIT
X-CDN-Rewrite: Lowercase blobs in v3-flatcontainer
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: 004ebe0a-0001-0077-536a-4c0ce5000000
x-ms-version: 2009-09-19
Content-Length: 43429

...nuget zip starts here...
```

Anything we can do with this?

**Comment by kierenj** [comment]
This seems wrong? -

dotnet nuget download, https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-dev/nuget/v3/flatcontainer/microsoft.identitymodel.tokens/5.1.0/microsoft.identitymodel.tokens.5.1.0.nupkg is 5.1.0.832

Manual download, https://api.nuget.org/packages/microsoft.identitymodel.tokens.5.1.0.nupkg is 5.1.0.0

**Comment by Tratcher** [comment]
Ah, so the bad package is on our nightly myget feed. The good news is you can remove the nightly feed for now. We'll get it cleaned up. @pranavkm @muratg

**Comment by kierenj** [comment]
Wahey! https://youtu.be/q-Rqdgna3Yw .  Thank you :)

**Comment by kierenj** [comment]
Sorry to turn it around and be a pest so quickly, but would it be possible to guess an ETA for the fix?

I changed the priority order of feeds in my NuGet.configs, but when pushing to Azure it's proving a lot of hassle and keeps grabbing the bad package.  I need the nightly feed in there for some other dependencies. Thanks

**Comment by pranavkm** [comment]
Try it now. I removed the bad packages from the feed.

**Comment by kierenj** [comment]
That solved it, thank you.
