### ISSUE TITLE
Microsoft.AspNetCore.Authentication.JwtBearer not working for Bear reference tokens

### ISSUE THREAD

**Issue by levilxw** [aspnet/Security#1052]
I use IdentityServer3 aithority and token type use reference tokens, can I use Microsoft.AspNetCore.Authentication.JwtBearer middleware to do the authentication?

**Comment by brockallen** [comment]
If you're using reference tokens you need to use this: https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation

**Comment by levilxw** [comment]
Yes, it is working to use IdentityServer4.AccessTokenValidation. Thanks, @brockallen 
Then I use IdentityServer3 as IDP but use IdentityServer4.AccessTokenValidation as authentication middleware, do you have concern for this?
