### ISSUE TITLE
.NET 2 / Asp.net 3.5 forms auth cookie compat

### ISSUE THREAD

**Issue by dazinator** [aspnet/Security#1053]
Not sure if this is the best place to raise this.

I had a need to be able to encrypt and decrypt a Forms Authentication ticket that is compatible with .NET 2 / asp.net 3.5 forms authentication.

I created this library in the end, using reference source to help me work out what was going on:

https://github.com/dazinator/AspNetCore.LegacyAuthCookieCompat

Usage looks like:

```csharp
 
          var issueDate = new DateTime(2015, 12, 22, 15, 09, 25);
          var expiryDate = new DateTime(0001, 01, 01, 00, 00, 00);
          var authTicket = new FormsAuthenticationTicket(2, "someuser@some-email.com", issueDate, expiryDate, false, "custom data", "/");

          var sha1Hasher = new Sha1HashProvider(_ValidationKeyText);
          var sut = new LegacyFormsAuthenticationTicketEncryptor(_DecryptionKeyText);

          // Act
          // We encrypt the forms auth cookie.
          var encryptedText = sut.Encrypt(authTicket, sha1Hasher);
          
          // We'd now usually write this as an authentication cookie..

```

To Decrypt: (We'd usually read the encrypted text from the auth cookie)

```csharp
           
            FormsAuthenticationTicket decryptedTicket = sut.DecryptCookie(encryptedText, new Sha1HashProvider(_ValidationKeyText));

```

This is useful because it lets you create asp.net core applications alongside legacy asp.net 3.5 applications on the same domain, that share an authentication cookie.

This only works on windows because there are a couple of DllImports for some windows dll's that are involved in the encryption / decryption process.

Would microsoft consider referencing this project for those wishing to achieve this kind of scenario - or providing an alternative I don't mind!

**Comment by Tratcher** [comment]
Thanks for doing this. https://github.com/aspnet-contrib may be a good home for this.
