### ISSUE TITLE
Can AccessDeniedPath be optional?

### ISSUE THREAD

**Issue by cheesemacfly** [aspnet/Security#1056]
Refering to this proposal: https://github.com/aspnet/Announcements/issues/40 and the explanation for the `AccessDeniedPath` property in `CookieAuthenticationOptions`: 

> The AccessDeniedPath property informs the middleware that it should change an outgoing 403 Forbidden status code into a 302 redirection onto the given path.

As of right now, when not setting the `AccessDeniedPath` option it is defaulted to '/Account/AccessDenied'. So if the browser makes a call that is [not Ajax](https://github.com/aspnet/Security/blob/rel/1.1.0/src/Microsoft.AspNetCore.Authentication.Cookies/Events/CookieAuthenticationEvents.cs#L60) it will send a redirect to the `AccessDeniedPath` value. 
My understanding of this parameter was that if it wasn't set, an access denied request would always return a 403.

For now, I have a workaround that is not ideal which implements a different version of the `OnRedirectToAccessDenied` event:

```
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
    Events = new CookieAuthenticationEvents
    {
        OnRedirectToAccessDenied = context =>
        {
            context.Response.StatusCode = (int)HttpStatusCode.Forbidden;
            return TaskCache.CompletedTask;
        }
    }
});
```

**Comment by Tratcher** [comment]
Is this for an API endpoint? If so you should probobly be using something like JwtBearer. Otherwise sending a user an empty 403 response is not recommended.

**Comment by cheesemacfly** [comment]
Hey @Tratcher, thanks for your answer.

I get your point but this is an issue in our configuration because we actually use [github/fetch](https://github.com/github/fetch) on the frontend which [does not set the X-Requested-With header](https://github.com/github/fetch/issues/17). So in this case `IsAjaxRequest(context.Request)` will return false. And we rely on the status code we get back from the API call to then act on the frontend. We do not want to handle redirect from the layer where the fetch calls are made.

Now I understand this is a specific case and this can be fixed by writing a wrapper for fetch or by using the custom `OnRedirectToAccessDenied` like I did. But I do not see why we force a redirect by default or at least why we do not have an option to return a raw 403 if this is what is needed. And the description of the field seems to agree that the redirect should be optional. I also feel like having 2 differents behavior based solely on the X-Requested-With header might be counter intuitive (I had to actually look at the CookieAuthenticationEvents.cs code to understand what was happening).

**Comment by cheesemacfly** [comment]
@Tratcher should I propose a pull request? (haven't done anything yet just wondering if that'd help)

**Comment by Tratcher** [comment]
Honestly I've never seen a good explanation for why CookieAuth special cases ajax requests. Sending a 401 with a location header doesn't make much sense.

**Comment by cheesemacfly** [comment]
Agreed. Maybe @HaoK who added the special cases for ajax can shade some light? (commit: https://github.com/aspnet/Security/commit/1d2c6ba1223748df02a879622e8deb6ac23db5b7)

**Comment by Tratcher** [comment]
That was just a refactor, the behavior has been there since Katana: http://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Security.Cookies/Provider/DefaultBehavior.cs

**Comment by cheesemacfly** [comment]
Well the original commit message is rather short so not sure it's gonna help: 

> adding event for cookie middleware redirection
> Default implementation also uses json response header for ajax requests instead of sending non-200 status codes
> 

http://katanaproject.codeplex.com/SourceControl/changeset/572641551a2ca1ed27f0b639d6c4bf8e29cf4966

Is this something that is going to need further investigation or can the decision to ditch the condition be made at this point? (I have to admit I'm not too familiar with how decisions are taken here)

**Comment by Tratcher** [comment]
I don't understand the client end of this enough to make a decision yet. I'll need to consult a few client side devs to see what makes sense here.

**Comment by Eilon** [comment]
Closing this issue because as far as we can tell it is possible to implement all scenarios.

If the client sends the appropriate "Is AJAX request" header, then for the most part the right thing will happen. Even if some clients don't send that header, it seems that it is fairly easy to add that custom header to the request.

If the default behavior is insufficient, there are events to customize the redirect behavior (e.g. to stop doing a redirect).

Ultimately, cookie authentication is intended for browser requests and not AJAX/API calls. As such, the default behavior of doing redirects makes sense.
