### ISSUE TITLE
‘AutomaticChallenge = false’ cause exception：No authentication handler...

### ISSUE THREAD

**Issue by cuiliang** [aspnet/Security#1058]
Hi,
I am using custom cookie authentication, and want no redirection to login page when no cookie presented,
so I set AutomaticChallenge to false followed by document : 
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie
`
AutomaticChallenge - this flag indicates that the middleware should redirect the browser to the LoginPath or AccessDeniedPath when authorization fails.
`
here is my code:
```
app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationScheme = Schema,
                LoginPath = PathString.Empty,
                AutomaticAuthenticate = true,
                AutomaticChallenge = false,
                ExpireTimeSpan = new TimeSpan(5, 0, 0, 0)
            });
```
but when accessing actions marked by [Authorize], browser whill show this exception:
```
InvalidOperationException: No authentication handler is configured to handle the scheme: Automatic
...
```

Is `AutomaticChallenge` must be true? 
Is there any way to control some actions redirect to login and other actions just return 401?

Thanks.

**Comment by HaoK** [comment]
`[Authorize]` with is basically syntax sugar for not specifying a scheme (using the automatic challenge)

You need to either create an AuthorizationPolicy that lists your Schema, or directly ask for it via `[Authorize(ActiveAuthenticationSchemes = Schema)]`

**Comment by cuiliang** [comment]
thanks

**Comment by Tratcher** [comment]
If you want a 401 then you should be using something like JwtBearer rather than cookies, and specify the scheme in Authorize like Haok said.

**Comment by cuiliang** [comment]
Thanks @Tratcher 
Tokens bring much more complexity.  
People need to handle generating tokens, keeping tokens, sending tokens, validating tokens, dealing with token expiration and much more. 

For OAuth Implicit Flow which is recommended for browser apps,  the access token should have minimal expiration time. But the client have no  refresh token and have to redirect to somewhere to regenerate a new access token. And when user logout from cookie, the access token is not expired.  Trouble.

For small web project with no external API client, the cookie is sending in each request. 
I think it's not a good idea to create another security token with different expiration time for just avoid 302 redirect.

**Comment by Tratcher** [comment]
Trying to use cookies for APIs opens a range of security vulnerabilities. Yes, tokens can be harder for a basic site, but they're still the right answer.

It's our responsibility as framework authors to give you the right tools and guidance, both of which are clearly lacking in this scenario. I'll see about putting together some proper guidance for starters.

**Comment by cuiliang** [comment]
Thank you 👍
