### ISSUE TITLE
The DataProtectionHelpers.CreateDataProtector extension method should be renamed

### ISSUE THREAD

**Issue by anurse** [aspnet/Security#106]
IDataProtectorProvider already defines a `CreateProtector` method, this extension method appears to be attempting to provide an overload, but because it has a different name, it results in slightly odd intellisense:

![image](https://cloud.githubusercontent.com/assets/7574/5403258/3d60c388-8140-11e4-9a3b-a061fb5f1f4f.png)

The purpose of the extension method appears to be to add an overload that takes multiple purposes, but the name mismatch is a little confusing. I suggest renaming this one to `CreateProtector` to match the method actually defined on the interface.

**Comment by HaoK** [comment]
@GrabYourPitchforks since the extension methods have been moved to DataProtection, I'll leave this one to you
