### ISSUE TITLE
Provide an implementation of `IAuthenticationHandler` targeting `ISession`

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Security#1060]
Bit of a mouthful, but it would be nice to just have a default implementation between your interfaces rather than having to come up with my own and risk getting it wrong.
Ideally I'd like to be able to store my authentication state in my session, backed by a distributed cache, backed by SQL.

A package like `Microsoft.AspNetCore.Authentication.Session` maybe?

I guess this can also get confusing because right now the system seems geared towards storing an identity cookie separately to the session cookie.

General advice always welcome here as well.  Maybe the solution already exists and I just haven't found all the docs to make it obvious to me ;)

**Comment by atrauzzi** [comment]
Here's a little bit of discussion on the idea: https://gitter.im/aspnet-contrib/AspNet.Security.OpenIdConnect.Server?at=58485a570da034021b7f84ed

Based on the discussion above, I've made this:

```
public class SessionTicketStore : ITicketStore
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        private readonly TicketSerializer _ticketSerializer;

        public SessionTicketStore(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
            _ticketSerializer = TicketSerializer.Default;
        }

        public async Task<string> StoreAsync(AuthenticationTicket ticket)
        {
            var key = Guid.NewGuid().ToString();
            _httpContextAccessor.HttpContext.Session.Set($"identity-{key}", _ticketSerializer.Serialize(ticket));
            return key;
        }

        public async Task RenewAsync(string key, AuthenticationTicket ticket)
        {
            throw new NotImplementedException();
        }

        public async Task<AuthenticationTicket> RetrieveAsync(string key)
        {
            var serializedTicket = _httpContextAccessor.HttpContext.Session.Get(key);

            if (serializedTicket != null)
            {
                return _ticketSerializer.Deserialize(serializedTicket);
            }

            return null;
        }

        public async Task RemoveAsync(string key)
        {
            _httpContextAccessor.HttpContext.Session.Remove(key);
        }
    }
```

However I don't like it because it piggybacks a key as a second cookie rather than just resorting to using the current session for all identity information.  I might still try my hand at writing my own `IAuthenticationHandler`, but doing so seems like pretty deep plumbing.

**Comment by Tratcher** [comment]
@blowdart

**Comment by blowdart** [comment]
When ASP.NET was started we very specifically made the decision to split authentication from session due to session hijacking and enumeration attacks. We won't be stepping back from that protection.
