### ISSUE TITLE
Framework appears to be missing a way to remove identities

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Security#1066]
I've created my own `AuthenticationHandler` which is working nicely.  Once my authentications are complete however, I'd like to clear the created identity from my ticket store.  Mainly for two reasons:

 - To transparently handle subsequent authentications as currently I get a "not authorized" when a duplicate identity is already present _(see https://github.com/aspnet/Security/issues/1067)_
 - Overall, once I receive a few key bits of information, I no longer require the information, so there's really no point in holding onto it

**Comment by Tratcher** [comment]
I don't understand enough of your scenario. AuthenticationHandlers and their state have a lifespan of one request. No idea what your ticket store is and how it's related.  A flow chart may help explain what you're trying to do.

**Comment by atrauzzi** [comment]
Well, I'm referring to the ticket store.

I'm not talking about `AuthenticationHandler` internal state.

**Comment by Tratcher** [comment]
What ticket store? CookieAuthenticationOptions.SessionStore?

**Comment by atrauzzi** [comment]
Using this one here: https://github.com/atrauzzi/praxis/blob/master/Praxis/Authentication/SessionTicketStore.cs

Not sure that matters in this case though.  I'm talking about removing an identity from the current `ClaimsPrincipal`.

**Comment by Eilon** [comment]
It seems that the way to achieve this is to create a new `ClaimsPrincipal` with the identities you want (if any) and set it on the current request. There doesn't appear to be a way to remove identities from a `ClaimsPrincipal` (this might be for security reasons - different components holding onto the same instance might make assumptions about its behavior).

**Comment by atrauzzi** [comment]
Is that disingenuous given that a `ClaimsPrincipal` can be represented by multiple transient `ClaimsIdentities`?

**Comment by Eilon** [comment]
@atrauzzi sorry, I'm not sure exactly what you mean by this - can you provide more details?

**Comment by atrauzzi** [comment]
I'm not sure I can put that any other way.  Combined with what I've said already, I think this is pretty clear.

**Comment by Eilon** [comment]
@atrauzzi if this is specifically about suggesting a change to the `ClaimsPrincipal` type then please log a new issue in https://github.com/dotnet/corefx/issues because that's where that type is implemented (https://github.com/dotnet/corefx/blob/master/src/System.Security.Claims/src/System/Security/Claims/ClaimsPrincipal.cs). Any additional information you can provide about the scenario would be helpful to the owners of that code. Thanks!

**Comment by Eilon** [comment]
Closing because we don't think there's any further action required in the ASP.NET Core security libraries.
