### ISSUE TITLE
Allow an identity to be received multiple times

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Security#1067]
If I successfully authenticate as a specific identity and I attempt another log in through the same provider again, I end up getting redirected to the access denied route.  This prevents me from creating an idempotent single signin flow.

 - Because the handler remains in control for the entirety of the flow, I'm unable to preempt it in any way.  
 - Even if I could preempt, I then run into this issue: https://github.com/aspnet/Security/issues/1066
 - Configuring a different access denied path seems disingenuous as there could still be legitimate reasons for denying access outside of this scenario.

_Related to this, but a slightly different problem, is https://github.com/aspnet/Security/issues/1056. Maybe addressing this ticket can be rolled in with the design work to be done there?_

**Comment by Tratcher** [comment]
This check was added to prevent infinite loops that people often found themselves in due to authorization issues. Why are you issuing a challenge for an already authenticated user? This seems like an issue in your authorization policy.

**Comment by atrauzzi** [comment]
I'm not the one issuing the challenge, the user comes in from an external system.  It's plausible that they could authenticate from the external system as different users, so even though I may already have my own user established for them, the scheme could be used multiple times.

**Comment by Tratcher** [comment]
For example you want them to be able to authenticate with multiple AAD accounts at the same time?

**Comment by atrauzzi** [comment]
Really it could be any account multiple times.  So imagine:

`bob.red@gmail.com` and `bob.blue@gmail.com`

If he signs in with `bob.red@gmail.com`, he'll at some point establish an identity belonging to my site as I'll have maintained associations of `@gmail.com` users to my internal domain users.

If he signs out of `bob.red@gmail.com` google-side and then signs into `bob.blue@gmail.com`, he'll still be authenticated as the first domain user in my application.

Authenticating as `bob.blue@gmail.com` will go through a clever flow to determine whether a user already exists (in which case that 2nd internal domain user would be authenticated), or Bob would be prompted if he wishes to associate `bob.blue@gmail.com` to the first domain user.

**Comment by testaco23** [comment]
Any news on this? Just came across the same issue.

**Comment by atrauzzi** [comment]
Yeah, the middleware is making an assumption that really should be up to me. The assumption being one identity per scheme. Which isn't correct or helpful.

**Comment by Tratcher** [comment]
Our template (e.g. Identity framework) uses two cookies to manage scenarios like this. The first is a temporary cookie that stores the external login data during the signin flow. Once you've completed the external login then you cross reference the external id with a local id and issue an 'application' cookie for the local id. At this point the temporary cookie can/should be deleted. Then you can start another external login flow with any provider and associate it with the local id when it's done.

**Comment by atrauzzi** [comment]
I'm not sure what you described speaks to the issue here.

The problem isn't about not being able to use two separate authentication schemes.  The problem is about not being able to use the same one twice.

**Comment by Tratcher** [comment]
The multiple cookies approach allowes you to hold onto one identity while processing a second one, from the same or different provider.

@haok, this ask is similar to the discussion we had about moving the challenge vs forbid logic to the authorization layer so it could be a policy decision.

**Comment by HaoK** [comment]
Challenge vs Forbid is not an authorization concern, the authorization service is given the claims principal and requirements to authorize against, it doesn't know how to get a principal at all (that's authentication).  Today its the MVC authorization filter that has the logic to build the principal to pass into the actual authorization service, certainly we can make adjustments in the filter's logic, but the core Authorization package doesn't depend on authentication today.

**Comment by Eilon** [comment]
@HaoK in our meeting you thought there might be a way to do this with a custom auth filter - can you share some pointers?

**Comment by HaoK** [comment]
You can try replacing the default authorize filter with one where: instead of returning the build in challenge result, you return a result that explicitly passes in the challenge behavior:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs#L160

Use the overload of context.Authentication.Challenge that specifies the ChallengeBehavior.Unauthorized explicitly instead
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ChallengeResult.cs#L111
