### ISSUE TITLE
UseOpenIdConnectAuthentication fails when updated to 1.1.0

### ISSUE THREAD

**Issue by obryckim** [aspnet/Security#1068]
I have an asp.net core application that was running on 1.0.1 that I have updated to 1.1.0.  Once the app was updated and Microsoft.AspNetCore.Authentication.OpenIdConnect was updated from 1.0.0 to 1.1.0, my authentication started hitting the OnAuthenticationFailed event.
The message received is **_Unable to validate the 'id_token', no suitable ISecurityTokenValidator was found for: ''."_**

If I revert only Microsoft.AspNetCore.Authentication.OpenIdConnect back to 1.0.0 and leave .net core and all other dependencies updated, the authentication works again.  I'm not aware of any breaking changes int Microsoft.AspNetCore.Authentication.OpenIdConnect from 1.0.0 to 1.1.0.

Other events are hit successfully before OnAuthenticationFailed (OnRedirectToIdentityProvider, OnTokenValidated, OnAuthorizationCodeReceived).

Startup.cs
    
    public class Startup
    {
        private readonly ILogger<Startup> logger;

        public Startup(IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            this.logger = loggerFactory.CreateLogger<Startup>();

            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", true, true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", true, true)
                .AddEnvironmentVariables();

            this.Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; set; }

        public void ConfigureServices(IServiceCollection services)
        {
            // app insights
            services.AddApplicationInsightsTelemetry(this.Configuration);

            // authentication and authorization
            services.AddAuthentication(ConfigureSharedAuthenticationOptions);
            services.AddAuthorization(ConfigureAuthorizationOptions);

            // options
            services.AddOptions()
                .Configure<ConfigurationOptions>(this.Configuration)
                .AddDataLayerConfigurationOptions(this.Configuration)
                .AddServicesLayerConfigurationOptions(this.Configuration)
                .AddWebAppLayerConfigurationOptions(this.Configuration);

            // caching/session
            services.AddDistributedSqlServerCache(this.ConfigureSqlServerCacheOptions);
            services.AddSession(this.ConfigureSessionOptions);

            // mvc
            services.AddMvc(ConfigureMvcOptions);

            // custom services from layers
            services
                .AddConfigurationLayerServices()
                .AddCommonLayerServices()
                .AddServicesLayerServices(this.Configuration)
                .AddWebLayerServices();
        }

        public void Configure(
            IApplicationBuilder app,
            IHostingEnvironment env,
            IServiceProvider serviceProvider,
            ILoggerFactory loggerFactory,
            ITicketStore distributedCacheTicketStore)
        {
            // setup logging
            loggerFactory.AddDebug((category, logLevel) => category.StartsWith("DeveloperTools."));

            // app insights request telemetry (this must be first)
            app.UseApplicationInsightsRequestTelemetry();

            // exceptions
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage(new DeveloperExceptionPageOptions { SourceCodeLineCount = 10 });
            }
            else
            {
                app.UseExceptionHandler("/error");
            }

            // app insights exception telemetry (right after exception config)
            app.UseApplicationInsightsExceptionTelemetry();

            // status code pages (redirect to error controller)
            app.UseStatusCodePagesWithRedirects("/error/{0}");

            // static files
            app.UseStaticFiles();

            // auth
            app.UseCookieAuthentication(this.BuildCookieAuthenticationOptions(distributedCacheTicketStore));
            app.UseOpenIdConnectAuthentication(this.BuildOpenIdConnectOptions());

            // session
            app.UseSession();
            app.UseSessionStartupConfiguration();

            // mvc
            app.UseMvc();
        }

        private static void ConfigureAuthorizationOptions(AuthorizationOptions authzOptions)
        {
            // role-based policies
            authzOptions.AddPolicy(AuthorizationPolicies.RequireDevelopersRole, policy => policy.RequireRole(AuthorizationRoles.Developers));
        }

        private static void ConfigureMvcOptions(MvcOptions options)
        {
            var defaultAuthPolicy = new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build();

            options.Filters.Add(new AuthorizeFilter(defaultAuthPolicy));
            options.Filters.Add(new RequireHttpsAttribute());
        }

        private static void ConfigureSharedAuthenticationOptions(SharedAuthenticationOptions sharedOptions)
        {
            sharedOptions.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        }

        private CookieAuthenticationOptions BuildCookieAuthenticationOptions(ITicketStore ticketStore)
        {
            var configuration = new ConfigurationOptions();
            this.Configuration.Bind(configuration);

            return new CookieAuthenticationOptions
            {
                CookieSecure = CookieSecurePolicy.SameAsRequest,
                CookieName = configuration.Session.AuthenticationCookieName,
                AccessDeniedPath = "/access-denied",
                SessionStore = ticketStore
            };
        }

        private OpenIdConnectOptions BuildOpenIdConnectOptions()
        {
            var configuration = new ConfigurationOptions();
            this.Configuration.Bind(configuration);

            return new OpenIdConnectOptions
            {
                ClientId = configuration.AzureActiveDirectory.ClientID,
                Authority = configuration.AzureActiveDirectory.Authority,
                PostLogoutRedirectUri = configuration.AzureActiveDirectory.PostLogoutRedirectUri,
                ResponseType = OpenIdConnectResponseType.CodeIdToken,
                RemoteAuthenticationTimeout = TimeSpan.FromMinutes(configuration.Session.TimeoutMinutes),
                TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    RoleClaimType = ClaimTypes.Role
                },
                Events = new OpenIdConnectEvents
                {
                    OnRedirectToIdentityProvider = this.OnRedirectToIdentityProvider,
                    OnRemoteFailure = this.OnRemoteFailure,
                    OnTokenValidated = this.OnTokenValidated,
                    OnAuthorizationCodeReceived = this.OnAuthorizationCodeReceived,
                    OnAuthenticationFailed = this.OnAuthenticationFailed
                }
            };
        }

        private void ConfigureSessionOptions(Microsoft.AspNetCore.Builder.SessionOptions options)
        {
            var configuration = new ConfigurationOptions();
            this.Configuration.Bind(configuration);

            options.CookieName = configuration.Session.SessionCookieName;
            options.IdleTimeout = TimeSpan.FromMinutes(configuration.Session.TimeoutMinutes);
        }

        private void ConfigureSqlServerCacheOptions(SqlServerCacheOptions options)
        {
            var configuration = new ConfigurationOptions();
            this.Configuration.Bind(configuration);

            options.ConnectionString = configuration.Database.ConnectionStrings.DeveloperTools;
            options.SchemaName = configuration.Session.SqlServer.Schema;
            options.TableName = configuration.Session.SqlServer.Table;
        }

        private Task OnAuthenticationFailed(AuthenticationFailedContext context)
        {
            this.logger.AuthenticationFailed(context.Exception);

            context.HandleResponse();
            context.Response.Redirect("/auth-error?message=" + context.Exception.Message);
            return Task.CompletedTask;
        }

        private async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedContext context)
        {
            var configuration = new ConfigurationOptions();
            this.Configuration.Bind(configuration);

            var request = context.HttpContext.Request;
            var currentUri = UriHelper.BuildAbsolute(request.Scheme, request.Host, request.PathBase, request.Path);
            var clientCredential = new ClientCredential(configuration.AzureActiveDirectory.ClientID, configuration.AzureActiveDirectory.ClientSecret);
            var authContext = new AuthenticationContext(configuration.AzureActiveDirectory.Authority, AuthPropertiesTokenCache.ForCodeRedemption(context.Properties));

            await authContext.AcquireTokenByAuthorizationCodeAsync(context.ProtocolMessage.Code, new Uri(currentUri), clientCredential, configuration.MicrosoftGraphApi.ResourceUri);
            this.logger.AcquiredTokenByAuthorizationCode(configuration.MicrosoftGraphApi.ResourceUri);

            context.HandleCodeRedemption();
        }

        private Task OnRedirectToIdentityProvider(RedirectContext context)
        {
            var configuration = new ConfigurationOptions();
            this.Configuration.Bind(configuration);

            context.ProtocolMessage.DomainHint = configuration.AzureActiveDirectory.DomainHint;

            return Task.CompletedTask;
        }

        private Task OnRemoteFailure(FailureContext context)
        {
            this.logger.RemoteFailure(context.Failure);

            context.HandleResponse();
            context.Response.Redirect("/auth-error?message=" + context.Failure.Message);
            return Task.CompletedTask;
        }

        private Task OnTokenValidated(TokenValidatedContext context)
        {
            var configuration = new ConfigurationOptions();
            this.Configuration.Bind(configuration);

            var claimTenantID = context.Ticket.Principal.FindFirst(AzureActiveDirectoryClaimTypes.TenantId).Value;
            var approvedTenantIds = new List<string> { configuration.AzureActiveDirectory.TenantID };

            if (approvedTenantIds.Contains(claimTenantID) == false)
            {
                this.logger.TenantIdNotApprovedForTokenValidation(claimTenantID);
                throw new SecurityTokenValidationException();
            }

            this.logger.TokenValidatedForTenantID(claimTenantID);

            return Task.CompletedTask;
        }
    }

Project.json

    {
      "version": "2.0.0-*",

      "dependencies": {
        "DT.Common": "2.*",
        "DT.Configuration": "2.*",
        "DT.Services": "2.*",
        "DT.Web.ViewModels": "2.*",
        "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
        "Microsoft.AspNetCore.Authentication": "1.1.0",
        "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
        "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.1.0", // WORKS WHEN CHANGED BACK TO "1.0.0"
        "Microsoft.AspNetCore.Diagnostics": "1.1.0",
        "Microsoft.AspNetCore.Mvc": "1.1.0",
        "Microsoft.AspNetCore.Razor.Tools": {
          "version": "1.1.0-preview4-final",
          "type": "build"
        },
        "Microsoft.AspNetCore.Routing": "1.1.0",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
          "version": "1.1.0-preview4-final",
          "type": "build"
        },
        "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
        "Microsoft.AspNetCore.Server.Kestrel.Https": "1.1.0",
        "Microsoft.AspNetCore.Session": "1.0.0",
        "Microsoft.AspNetCore.StaticFiles": "1.1.0",
        "Microsoft.Extensions.Caching.SqlServer": "1.0.0",
        "Microsoft.Extensions.Configuration.Abstractions": "1.1.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
        "Microsoft.Extensions.Configuration.Json": "1.1.0",
        "Microsoft.Extensions.Logging.Console": "1.1.0",
        "Microsoft.Extensions.Logging.Debug": "1.1.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
        "Microsoft.Graph": "1.1.1",
        "Microsoft.IdentityModel.Clients.ActiveDirectory": "3.13.6"
      },

      "tools": {
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
        "Microsoft.AspNetCore.Razor.Tools": {
          "version": "1.1.0-preview4-final",
          "imports": "portable-net45+win8+dotnet5.6"
        },
        "Microsoft.Extensions.Caching.SqlConfig.Tools": "1.1.0-preview4-final"
      },

      "frameworks": {
        "netcoreapp1.1": {
          "imports": [
            "dotnet5.6",
            "portable-net45+win8"
          ],
          "dependencies": {
            "Microsoft.NETCore.App": {
              "version": "1.1.0",
              "type": "platform"
            }
          }
        }
      },

      "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
      },

      "runtimeOptions": {
        "configProperties": {
          "System.GC.Server": true
        }
      },

      "publishOptions": {
        "include": [
          "wwwroot",
          "views/**/*.cshtml",
          "appsettings.json",
          "web.config"
        ]
      },

      "scripts": {
        "prepublish": [ "bower install", "gulp buildprod" ],
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
      }
    }

**Comment by Tratcher** [comment]
This may be related to https://github.com/aspnet/Security/commit/415055ebabcee656475e1f22e65045851641701c. In the CodeIdToken scenario additional validation was added for the id_token received from the TokenEndpoint. If you hook up the TokenResponseReceived event and examine the TokenEndpointResponse what do you see?

**Comment by obryckim** [comment]
@Tratcher 

It looks like the TokenEndpointResponse has nothing set:

    {
        "AccessToken": null,
        "AcrValues": null,
        "AuthorizationEndpoint": null,
        "ClaimsLocales": null,
        "ClientAssertion": null,
        "ClientAssertionType": null,
        "ClientId": null,
        "ClientSecret": null,
        "Code": null,
        "Display": null,
        "DomainHint": null,
        "Error": null,
        "ErrorDescription": null,
        "ErrorUri": null,
        "ExpiresIn": null,
        "GrantType": null,
        "IdToken": null,
        "IdTokenHint": null,
        "IdentityProvider": null,
        "Iss": null,
        "IssuerAddress": "",
        "LoginHint": null,
        "MaxAge": null,
        "Nonce": null,
        "Parameters": {},
        "Password": null,
        "PostLogoutRedirectUri": null,
        "PostTitle": "Working...",
        "Prompt": null,
        "RedirectUri": null,
        "RefreshToken": null,
        "RequestType": 0,
        "RequestUri": null,
        "Resource": null,
        "ResponseMode": null,
        "ResponseType": null,
        "Scope": null,
        "ScriptButtonText": "Submit",
        "ScriptDisabledText": "Script is disabled. Click Submit to continue.",
        "SessionState": null,
        "Sid": null,
        "State": null,
        "TargetLinkUri": null,
        "TokenEndpoint": null,
        "TokenType": null,
        "UiLocales": null,
        "UserId": null,
        "Username": null
    }

The protocol message has some of the properties set:

    {
        "AccessToken": null,
        "AcrValues": null,
        "AuthorizationEndpoint": null,
        "ClaimsLocales": null,
        "ClientAssertion": null,
        "ClientAssertionType": null,
        "ClientId": null,
        "ClientSecret": null,
        "Code": "AQABAA...",
        "Display": null,
        "DomainHint": null,
        "Error": null,
        "ErrorDescription": null,
        "ErrorUri": null,
        "ExpiresIn": null,
        "GrantType": null,
        "IdToken": "eyJ0eX...",
        "IdTokenHint": null,
        "IdentityProvider": null,
        "Iss": null,
        "IssuerAddress": "",
        "LoginHint": null,
        "MaxAge": null,
        "Nonce": null,
        "Parameters": {
            "code": "AQABAA...",
            "id_token": "eyJ0eX...",
            "session_state": "b8c9fb..."
        },
        "Password": null,
        "PostLogoutRedirectUri": null,
        "PostTitle": "Working...",
        "Prompt": null,
        "RedirectUri": null,
        "RefreshToken": null,
        "RequestType": 0,
        "RequestUri": null,
        "Resource": null,
        "ResponseMode": null,
        "ResponseType": null,
        "Scope": null,
        "ScriptButtonText": "Submit",
        "ScriptDisabledText": "Script is disabled. Click Submit to continue.",
        "SessionState": "b8c9fb...",
        "Sid": null,
        "State": null,
        "TargetLinkUri": null,
        "TokenEndpoint": null,
        "TokenType": null,
        "UiLocales": null,
        "UserId": null,
        "Username": null
    }

**Comment by Tratcher** [comment]
Seems like something is going wrong here: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L709
Any logs? Or failing that a fiddler trace of the token endpoint response would help.

**Comment by shobman** [comment]
I was having this same problem since upgrading to 1.1.0.  First thing I had to do was change thre ResponseType from Code to CodeIdToken.

```
ResponseType = OpenIdConnectResponseType.CodeIdToken
```

Next i added a call to tell the OIDC middleware that the response was handled.

```
private async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedContext context)
{
    ...

    context.HandleCodeRedemption();
    context.HandleResponse();
}
```

I don't know if there will be any side effects of this, but at least I can login again.

**Comment by shobman** [comment]
I found another issue when deploying to an Azure Web App after updating to 1.1.0.  The website fails with the error:

```
HTTP Error 502.3 - Bad Gateway
The specified CGI application encountered an error and the server terminated the process.
```

And the trace files came up with this warning...
```
MODULE_SET_RESPONSE_ERROR_STATUS
ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="502", HttpReason="Bad Gateway", HttpSubStatus="3", ErrorCode="2147954430", ConfigExceptionInfo=""	
```

My issues was the home page had an [Authorize] attribute.  This was working fine in 1.0.1 with the redirect to login happening on the first page request.  So with 1.1.0 this appears to be broken.  

The work around for me was to allow anonymous on the home page and redirect to another action that has the [Authorize] attribute and that seems to be working.  It would be good to know what's going on so I can remove the hack.

**Comment by Tratcher** [comment]
Sounds like an unhandled exception in the app. Turning on logging would be a good start.

**Comment by shobman** [comment]
I'll do a bit more digging into the logs.

**Comment by obryckim** [comment]
@Tratcher 

There is nothing being logged that I can see.  I did a fiddler trace and the call to microsoft to receive the token succeeds.  The response has the full token in there.  Right after that call, I see the redirect to my auth-error page.

Note, I tried, just for the heck of it, putting "context.HandleResponse();" at the end of my OnAuthorizationCodeReceived method, and I no longer get that error.  Though, OnTokenResponseReceived is no longer raised when that is in there.  I'm not sure if that line is a band-aid, coincidence, or what I should be doing anyway.

**Comment by Tratcher** [comment]
Ah, I see the problem.
```
    private async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedContext context)
    {
        var configuration = new ConfigurationOptions();
        this.Configuration.Bind(configuration);

        var request = context.HttpContext.Request;
        var currentUri = UriHelper.BuildAbsolute(request.Scheme, request.Host, request.PathBase, request.Path);
        var clientCredential = new ClientCredential(configuration.AzureActiveDirectory.ClientID, configuration.AzureActiveDirectory.ClientSecret);
        var authContext = new AuthenticationContext(configuration.AzureActiveDirectory.Authority, AuthPropertiesTokenCache.ForCodeRedemption(context.Properties));

        await authContext.AcquireTokenByAuthorizationCodeAsync(context.ProtocolMessage.Code, new Uri(currentUri), clientCredential, configuration.MicrosoftGraphApi.ResourceUri);
        this.logger.AcquiredTokenByAuthorizationCode(configuration.MicrosoftGraphApi.ResourceUri);

        context.HandleCodeRedemption();
    }
```
You call HandleCodeRedemption but don't give it the results, so when it tries to validate the the response it fails. Either give it the results or call HandleResponse to bypass further processing.

**Comment by obryckim** [comment]
@Tratcher 
Thank you for your help on this.  That solved my problem.  Here is the final piece of code:

    private async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedContext context)
    {
        var configuration = new ConfigurationOptions();
        this.Configuration.Bind(configuration);

        var request = context.HttpContext.Request;
        var currentUri = UriHelper.BuildAbsolute(request.Scheme, request.Host, request.PathBase, request.Path);
        var clientCredential = new ClientCredential(configuration.AzureActiveDirectory.ClientID, configuration.AzureActiveDirectory.ClientSecret);
        var authContext = new AuthenticationContext(configuration.AzureActiveDirectory.Authority, AuthPropertiesTokenCache.ForCodeRedemption(context.Properties));

        var result = await authContext.AcquireTokenByAuthorizationCodeAsync(context.ProtocolMessage.Code, new Uri(currentUri), clientCredential, configuration.MicrosoftGraphApi.ResourceUri);
        this.logger.AcquiredTokenByAuthorizationCode(configuration.MicrosoftGraphApi.ResourceUri);

        // passed the access/id tokens into HandleCodeRedemption
        context.HandleCodeRedemption(result.AccessToken, result.IdToken);
    }
