### ISSUE TITLE
Cookie Middleware CookieAuthenticationHandler not redirecting correctly

### ISSUE THREAD

**Issue by h3smith** [aspnet/Security#1070]
Out solution is sitting behind a load balancer that terminates the SSL connection. .NET Core app just handles the HTTP request.

When this is an SSL connection on a non-standard port `https://something:8443`, when the redirect occurs, it is pushing to `http://something:8443`, disregarding the HTTPS scheme. 

The CookieAuthenticationHandler is not looking to validate the scheme before performing the redirect on an authentication failure.

**Comment by Tratcher** [comment]
Duplicate: https://github.com/aspnet/Security/issues/929

**Comment by h3smith** [comment]
For anyone else with the issue, 

```
app.Use((context, next) =>
{
  context.Request.Scheme = "https";
  return next();
});
```

Fixes the problem. We disable this with an environment variable if we need to use port 80.
