### ISSUE TITLE
Data protection system is far too onerous by default

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Security#1071]
https://github.com/aspnet/Home/issues/466

https://github.com/aspnet/DataProtection/issues/115

I've just had my hands forced into the data protection system with something I'm working on and I absolutely cannot believe how complicated this has been made and how many assumptions have been dumped on developers.

Why can't I just put a string in my environment and be done with it?

I know what the security concerns are, but ratcheting things up like this is too much too early!  Especially when the only default implementations available assume a shared filesystem between machines - completely unrealistic!

I'm not encrypting anything that is sensitive at the moment, frankly just signing my information to prevent tampering would be sufficient in my situation.

This has to be pointed out: https://github.com/aspnet/Home/issues/466#issuecomment-205832926

Maybe there just needs to be a guide or some code snippets, but here's what I need:

 - Let me manage my own business
 - A key in my `appsettings.json`
 - Tell the data protection system to use that
 - If I want to encrypt at-rest, I'll opt-in
 - If I want to secure access to the at-rest data, I'll opt-in
 - Get out of my way!

In terms of right away, any guidance on just getting this very overbearing and time consuming design off of my back would be very greatly appreciated.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/DataProtection#192

**Comment by atrauzzi** [comment]
Thank you 👍
