### ISSUE TITLE
Google provider does not populate GivenName or Surname claims on request

### ISSUE THREAD

**Issue by StummeJ** [aspnet/Security#1072]
When you break in the middle of a request I noticed that the `GivenName` and `Surname`, which are there when logging in with google, are not in the `context.User.Claims` list.  I also notice that `Name` is set to the email instead of the full name as it is when logging in.

Is this by design?  Is there any way to get the name from the google oauth provider?

**Comment by Tratcher** [comment]
Related: https://github.com/aspnet/Security/issues/969

**Comment by PinpointTownes** [comment]
Does your application use Identity? If so, consider reading https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/issues/26 and https://github.com/aspnet/Identity/issues/628.

**Comment by Eilon** [comment]
Closing as dup of https://github.com/aspnet/Security/issues/969.
