### ISSUE TITLE
ChunkingCookieManager is not honoring the "secure" flag when deleting cookies

### ISSUE THREAD

**Issue by luis-goncalves-bold** [aspnet/Security#1073]
The [`ChunkingCookieManager`](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.ChunkingCookieManager.Sources/ChunkingCookieManager.cs) class is not honoring the `CookieOptions.Secure` flag on the [`DeleteCookie` method](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.ChunkingCookieManager.Sources/ChunkingCookieManager.cs#L223). Since the flag is honored when creating the cookie(s), this will result on the cookies not being deleted by the browser. Also, security audit tools will report that cookies are being set without the secure flag on HTTPS websites.

I've bumped into this when using the new [`CookieTempDataProvider`](https://github.com/aspnet/Mvc/blob/rel/1.1.0/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/CookieTempDataProvider.cs#L82) on MVC.

**Comment by luis-goncalves-bold** [comment]
The same applies to the `HttpOnly` flag.

**Comment by Tratcher** [comment]
Which browsers/clients have you tested?

**Comment by luis-goncalves-bold** [comment]
I was mislead by a security assessment tool. And by double checking the RFC, those flags aren't supposed to be part of the cookie "lookup key" that the UA uses.

Sorry about this.
