### ISSUE TITLE
AuthorizeAttribute -> JWT and Identity.Cookie

### ISSUE THREAD

**Issue by patsadow2** [aspnet/Security#1074]
Hello,
Could anyone explain me how [Authorize] attribute in .net core knows and validate correctly when we use

app.UseJwtBearerAuthentication -> (Authorization: Bearer ..... )
or
 app.UseIdentity -> ( AspNet.Cookie.Identity )

Thanks :)

**Comment by Tratcher** [comment]
See automatic challenge and automatic authenticate:  https://github.com/aspnet/Security/issues/1062
