### ISSUE TITLE
Inconsistent behavior of Windows authentication between IIS integration and WebListener

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#1076]
Both add Negotiate and NTLM.

WebListener gives the schemes display names of `Windows:Negotiate` and `Windows:NTLM`.
With IIS integration the display names are empty.

Since display name is often used in generic code to populate the login page - it would be nice to always have a display name - or never. But be consistent ;)

**Comment by Tratcher** [comment]
This issue was moved to aspnet/WebListener#287
