### ISSUE TITLE
JWT signature validation does strange things

### ISSUE THREAD

**Issue by wdmeeste1** [aspnet/Security#1079]
I have ASP.Net core project with an implemented system to request (JWT bearer) tokens. The token request works perfect and when I use the token to make an api call it works perfect aswell. But I noticed when I remove some parts of the signature the request still works.

**Example**

**Works with original bearer token:**
`curl "http://localhost:5000/Api/Sample/2" --include --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJURVNUIiwianRpIjoiMDgyMTQxOTYtYzYyOC00ZjIzLWFjNjItNWUwMTQ4YjRlODYxIiwiaWF0IjoxNDgzOTcxNjExLCJuYmYiOjE0ODM5NzE2MTEsImV4cCI6MTQ4Mzk3MTkxMSwiaXNzIjoidGVzdCIsImF1ZCI6InRlc3QifQ.Fm2akyXaWlUKVz-lcBZV2XoURfy-D8sDcV4TfPwWMM8`

**Still works**
`curl "http://localhost:5000/Api/Sample/2" --include --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJURVNUIiwianRpIjoiMDgyMTQxOTYtYzYyOC00ZjIzLWFjNjItNWUwMTQ4YjRlODYxIiwiaWF0IjoxNDgzOTcxNjExLCJuYmYiOjE0ODM5NzE2MTEsImV4cCI6MTQ4Mzk3MTkxMSwiaXNzIjoidGVzdCIsImF1ZCI6InRlc3QifQ.Fm2a`

**Doesnt work (base64 decode error)**
`curl "http://localhost:5000/Api/Sample/2" --include --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJURVNUIiwianRpIjoiMDgyMTQxOTYtYzYyOC00ZjIzLWFjNjItNWUwMTQ4YjRlODYxIiwiaWF0IjoxNDgzOTcxNjExLCJuYmYiOjE0ODM5NzE2MTEsImV4cCI6MTQ4Mzk3MTkxMSwiaXNzIjoidGVzdCIsImF1ZCI6InRlc3QifQ.Fm2akyXaWlUKVz-lcBZV2XoURfy-D8sDcV4TfPwWM`

**Doesnt work (changed 4the letter of signature)**
`curl "http://localhost:5000/Api/Sample/2" --include --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJURVNUIiwianRpIjoiMDgyMTQxOTYtYzYyOC00ZjIzLWFjNjItNWUwMTQ4YjRlODYxIiwiaWF0IjoxNDgzOTcxNjExLCJuYmYiOjE0ODM5NzE2MTEsImV4cCI6MTQ4Mzk3MTkxMSwiaXNzIjoidGVzdCIsImF1ZCI6InRlc3QifQ.Fm2b`

I really don't understand how the control works? Anyone an idea?

**Error: WWW-Authenticate: Bearer error="invalid_token"**

**Startup.cs**

```
           string secretKey  = Configuration["API:secret"];
            string audience   = Configuration["API:audiance"];
            string issuer     = Configuration["API:issuer"];
            var signingKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(secretKey));

           //For the creation of jwt token (tutorial: https://stormpath.com/blog/token-authentication-asp-net-core)
            var jwtOptions = new TokenProviderOptions
            {
                Audience = audience,
                Issuer = issuer,
                SigningCredentials = new SigningCredentials(signingKey, SecurityAlgorithms.HmacSha256),
            };

            app.UseMiddleware<TokenProviderMiddleware>(Options.Create(jwtOptions));
            
            //Token validator
            var tokenValidationParameters = new TokenValidationParameters
            {
                ValidateIssuer = true,
                ValidIssuer = issuer,

                ValidateAudience = true,
                ValidAudience = audience,

                ValidateIssuerSigningKey = false,
                IssuerSigningKey = signingKey,

                RequireExpirationTime = true,
                ValidateLifetime = true,
                
                RequireSignedTokens=true,

                ClockSkew = TimeSpan.Zero
            };

            app.UseJwtBearerAuthentication(new JwtBearerOptions
            {
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                TokenValidationParameters = tokenValidationParameters
            });
```

**SampleController**

```
[Authorize(ActiveAuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
public async Task<ActionResult> GetById(int id){
...
}
```

**Comment by blowdart** [comment]
Can you post your project.json? There is/was a bug in the identity model pieces, but AFAIK none of our templates used that version by default. https://technet.microsoft.com/library/security/3214296 has the details, and the instructions to update.

**Comment by PinpointTownes** [comment]
@blowdart the JWT bearer middleware indirectly references the affected package.

**Comment by blowdart** [comment]
Ah, then you need to follow the package update instructions to get the fixed version

**Comment by wdmeeste1** [comment]
Alright validation works now (after updating the token package to 5.1.2)! Thought I was going crazy there for a moment :)

Initial project.json file:
`"System.IdentityModel.Tokens.Jwt":` "5.1.0"

Update to:
```
"System.IdentityModel.Tokens.Jwt": "5.1.2",
"Microsoft.IdentityModel.Tokens": "5.1.2"
```

Thxs for the quick reply and the help!
