### ISSUE TITLE
ChunkingCookieManager bug

### ISSUE THREAD

**Issue by mamort** [aspnet/Security#1081]
There seems to be a bug in Microsoft.AspNetCore.Authentication.Cookies.ChunkingCookieManager that causes problems when sharing cookies between .NET Core and .NET 4.X projects. The problem is that .NET Core uses a separator that is different from the implementation in Katana/.NET 4.X when assigning a value to the chunk count. 

In Katana the value is called "chunks:XX" 
In .NET Core the value is called "chunks-XX" 
XX is the chunk count, but notice that Owin uses a colon while .NET Core uses a hyphen in the value

It is also reported as a problem in the comments to the article about cookie sharing in .net core/.net 4.X:
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/cookie-sharing

See the Katana/Owin source here:
https://github.com/jchannon/katanaproject/blob/master/src/Microsoft.Owin/Infrastructure/ChunkingCookieManager.cs 

For some reason I can't find the source for the ChunkingCookieManager in the .NET Core repo (I looked at the decompiled version), but is is used here:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationMiddleware.cs

It does not appear to be fixed in .NET Core 1.1

**Comment by Tratcher** [comment]
This was an intentional change, there were problems with using `:` in a cookie.

There's an interoperable version of cookie manager in the interop package:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.Owin.Security.Interop/ChunkingCookieManager.cs

**Comment by mamort** [comment]
Thanks for the quick reply! That makes sense. I also notice that someone has pointed out the same solution in the comments to the article. 

The article/documentation also needs to be updated to help people to avoid this issue. It is very easy to implement the cookie sharing according to the article and think everything is working correctly, only to get some very weird errors when suddenly the cookie data is broken up into several cookie chunks.
