### ISSUE TITLE
Update IdentityModel dependencies to 5.1.2

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1082]
@blowdart @muratg recommended for 1.1.1

**Comment by muratg** [comment]
Putting this in 1.1.1 for the patch release triage.

**Comment by blowdart** [comment]
Not just recommended. Mandatory.

**Comment by Tratcher** [comment]
https://technet.microsoft.com/library/security/3214296

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.
