### ISSUE TITLE
Microsoft.AspNetCore.Authentication.OpenIdConnect 1.1.0 does not redirect to identity provider

### ISSUE THREAD

**Issue by qvsmith** [aspnet/Security#1084]
### Functional impact
Cannot log in (blank page displayed).

### Minimal repro steps

1. Get repro project - https://github.com/qvsmith/IdentityServer4.Samples
2. Open /Quickstarts/3_ImplicitFlowAuthentication solution.
3. Start QuickstartIdentityServer and MvcClient project.
4. On MvcClient project's home page click 'Secure' link.

### Expected result
User should be redirected to login page.

### Actual result
Blank page is displayed. Redirect not occurring.

### Further technical details
The response status code is 401. If I add custom middleware (just before oidc mw) that changes the response status code to 302 it resolves the problem. Perhaps has something to do with me using netcoreapp1.0 ipo 1.1...

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Security/issues/1062

**Comment by Eilon** [comment]
This is a known issue, which we are fixing in the upcoming 1.1.1 patch. You can refer to https://github.com/aspnet/Security/issues/1062 for more details, plus workarounds.

**Comment by qvsmith** [comment]
@Eilon Tx! I tried some of those workarounds mentioned in #1062 but, I couldn't get them to work. The workaround with custom middleware that I mentioned above at least does the trick... Fortunately this is not critical for me at this stage... just wanted to log it :)

**Comment by Eilon** [comment]
@qvsmith got it, thanks for the info!
