### ISSUE TITLE
IAuthorizationService/Requirement/Handler workflow - recursive authorization handling

### ISSUE THREAD

**Issue by nth-commit** [aspnet/Security#1086]
I think you should be able to defer authorization for a requirement inside a handler. Having consumed the IAuthorizationService for well over a year, I can think of a lot of use-cases where this would work well.

For example, you want to authorize access to a resource, but access to that resource depends on checking the access to another resource. The caller shouldn't need to know the implementation details of the handlers to decide how to make a correct authorization call.

For a concrete example, say you have two types of resources - a bookcase and a book. Both resources have their own requirements and handlers to determine authorization. But to access a book you might also need to determine that you also have access to the bookshelf it is on. You shouldn't need to repeat the logic to access a bookshelf inside the handler for the book IMHO - you should be able to defer the authorization to a requirement and/or resource. Some books might be in a safe instead, you see how the complexity grows exponentially without some sort of recursive authorization implementation?

The consumer of this should need not know the access rules inside the handler (although they might for database optimizations).

For the above example, I would suggest something like this:
```
protected override async Task HandleRequirementAsync(AuthorizationHandlerContext context, BookOperationAuthorizationRequirement requirement, Book resource)
{
    if (book.Bookshelf != null)
    {
        context.Defer(requirement, new BookshelfAuthorizationRequirement(), book.Bookshelf);
    }
    else if (book.Safe != null)
    {
        context.Defer(requirement, new SafeAuthorizationRequirement(), book.Safe);
    }
    else
    {
        // Something went wrong.
        context.Fail();
    }
}
```

```context.Defer()``` would signal the AuthorizationService to spawn a new auth cycle for the new requirement and/or new resource. It would also create and track a new AuthorizationHandlerContext for each call to ```Defer()```. If all child contexts succeed, the requirement should be successful. If not, the authorization should fail.

Please let me know if you think there is a better way to do this in the current API.

Thanks,
Michael

**Comment by Eilon** [comment]
Putting in backlog for now, but this sounds like a good feature that we'll consider in a future version.

**Comment by nth-commit** [comment]
@Eilon 
Hey, thanks a lot. I'll send you guys a PR for you to peruse over at your leisure. I've got another feature request as well - I'm so demanding ;)

Love the API btw, kutgw.

**Comment by Eilon** [comment]
@nth-commit thanks! If you send a PR we'll certainly review it. We've got a pretty big set of features for 2.0 already so we can't commit to accepting the feature in this 2.0 release, but we'll certainly consider it for a 2.x update or similar.

**Comment by guillerglez88** [comment]
As a workaround you can require IServiceProvider from constructor instead, and resolve the service just before calling AuthorizeAsync, that worked for me.

**Comment by HarleyBartles** [comment]
Plus 1 for this. I'm building an application to handle groups in a kind of tree view.

A manager of a group has a claim of CanManageGroup: GroupId, but that manager should also be able to manage all the groups which report into his group and all the groups that report into that group and so on - so for example the CEO at the top of the tree can perform management actions on any group as they all eventually resolve underneath the Senior Management group but a mid-level manager can only perform those actions on groups below in the hierarchy.

I can fudge this together in the controller or a custom service (IMemberManager) with a recursive function, but that doesn't feel very right at all.

Bear with me, I'm only just learning authorization and indeed Net Core itself.

**Comment by MarcusKohnert** [comment]
Eagerly awaiting this feature, too. 🙌

**Comment by xucito** [comment]
+1 for this functionality.
@guillerglez88 thanks for the workaround.

**Comment by Eilon** [comment]
Closing because we are not planning to implement this pattern. We recommend that the app's auth rules should handle this behavior on its own.
