### ISSUE TITLE
[Announcement] Functional changes to OpenIdConnectOptions.PostLogoutRedirectUri 

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1087]
Milestone 1.1.0, RE: https://github.com/aspnet/Security/pull/925

PostLogoutRedirectUri defines the default address clients are directed to after they sign out of the remote identity provider. The AuthenticationProperties.RedirectUri from the SignOut call takes precedence over this option. Relative uris are resolved against the current scheme, host, and PathBase.

In 1.0.0 the client was sent directly to this address (or the dynamic RedirectUri) after signing out. For some identity providers that required pre-registering every destination as a valid redirect uri. There was no default value for PostLogoutRedirectUri so the client would not be returned to the application after signing out. 

In 1.1.0 there is a new option SignedOutCallbackPath with a default value `/signout-callback-oidc`. This mirrors CallbackPath as a single destination within the middleware where the client returns before being redirected to the specified PostLogoutRedirectUri or AuthenticationProperties.RedirectUri address. This allows the application to register just `/signout-callback-oidc` (and `/signin-oidc`) as a valid redirect uri with the identity provider and then redirect to dynamic destinations. The default value for PostLogoutRedirectUri is now `/`.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
