### ISSUE TITLE
CookieAuthenticationHandler returns authentication ticket in the cookie value instead of sessionKey

### ISSUE THREAD

**Issue by aagarwal10** [aspnet/Security#1093]
I have defined a Redis implementation of ITicketStore to CookieMiddleware. Is my assumption not right that when SessionStore is defined for the cookiemiddleware that middleware needs to return the SessionKey in the cookie value instead of value of AuthenticationTicket. Please help me understand this little more.
```
 **var cookieValue = Options.TicketDataFormat.Protect(ticket, GetTlsTokenBinding());**

                var cookieOptions = BuildCookieOptions();
                if (ticket.Properties.IsPersistent && _refreshExpiresUtc.HasValue)
                {
                    cookieOptions.Expires = _refreshExpiresUtc.Value.ToUniversalTime();
                }

                Options.CookieManager.AppendResponseCookie(
                    Context,
                    Options.CookieName,
                    cookieValue,
                    cookieOptions);
```

**Comment by Tratcher** [comment]
Scroll up a few lines:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L189-L197

**Comment by aagarwal10** [comment]
I saw these lines before, my question is should we be sending the sessionKey as "cookieValue"instead of whole Authenticket if SessionStore is not null??

**Comment by Tratcher** [comment]
We do it this way because the serialization logic only understands auth tickets. We could bypass it but it would require divergent code paths. It would also make the serializer less pluggable.

**Comment by aagarwal10** [comment]
OK, make sense.
