### ISSUE TITLE
Sharing cookie distributed system

### ISSUE THREAD

**Issue by ngonzalezromero** [aspnet/Security#1098]
If possible, sharing the cookie between distributed systems?
I have many app running in different machines (in dockers containers) and I'd like  get the authentication from the login system

**Comment by Chrissx** [comment]
Maybe you can take a look for this documentation : https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/cookie-sharing

**Comment by ngonzalezromero** [comment]
@Chrissx I saw it, but it doesn't work for me because the  cookie is saved in the same host.
and my apps are saved in different host

**Comment by Eilon** [comment]
Is the scenario here that there are multiple servers on different sub-domains? E.g. `web1.example.com`, `service1.example.com`? Can you give us examples of the layout of the app?

If it's just sub-domains then you can set the cookie path to be `.example.com`.

**Comment by Eilon** [comment]
Closing because this appears to be a duplicate of https://github.com/aspnet/Security/issues/993.
