### ISSUE TITLE
AuthorizeAttribute and other attributes outside of MVC

### ISSUE THREAD

**Issue by dustinmoris** [aspnet/Security#1099]
Hi,

It seems that the `AuthorizeAttribute` and `AllowAnonymousAttribute` are both part of the `Microsoft.AspNetCore.Authorization` NuGet package, which is AFAIK independent from MVC.

How can I use these attributes in an ASP.NET Core application without MVC? Is it possible to include this to the [official documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple) or to demo this during an upcoming ASP.NET standup? @shanselman @DamianEdwards 

On the other hand if these attributes are tied to MVC I would like to raise this as an issue here to move them (and any other MVC coupled code) out of the `Microsoft.AspNetCore.Authorization` NuGet package and namespace and move it to the MVC NuGet package, because it is confusing otherwise and it doesn't make sense to have MVC specific code in an ASP.NET Core application which is not using MVC (e.g. [Nancy](https://github.com/NancyFx/Nancy), [Suave](https://github.com/dustinmoris/Suave.AspNetCore), [pure routes](https://github.com/aspnet/Routing/issues/367)).

**Comment by Tratcher** [comment]
The attributes are just a marker for any web framework to use. SignalR also uses them. 
https://github.com/aspnet/SignalR/blob/cd9ed9228ae2b27980ddda7d5cd5f127aaad366a/samples/ChatSample/Hubs/Chat.cs#L12

**Comment by dustinmoris** [comment]
Thank you that makes sense.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
