### ISSUE TITLE
Some methods in IAuthorizationService should be moved to extension methods

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Security#11]
As @Eilon suggested, the overloads without a resource should be extension methods rather than methods on the interface. In most of the cases, whoever implements this service will just call the overload with the resource parameter with a "null" value.

~~~C#
namespace Microsoft.AspNet.Security.Authorization
{
    public interface IAuthorizationService
    {
        bool Authorize(IEnumerable<Claim> claims, ClaimsPrincipal user);
        bool Authorize(IEnumerable<Claim> claims, ClaimsPrincipal user, object resource);
        Task<bool> AuthorizeAsync(IEnumerable<Claim> claims, ClaimsPrincipal user);
        Task<bool> AuthorizeAsync(IEnumerable<Claim> claims, ClaimsPrincipal user, object resource);
    }
}
~~~

**Comment by HaoK** [comment]
While this was talking about the old iteration of Auth service, it still applies to the new overloads we are going to add, so I'll keep this bug around until the next iteration moves some of the new methods to extension methods
