### ISSUE TITLE
TestServer guidance to mock/replace auth services

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/Security#1100]
I am currently using the `JwtBearerAuthentication` middleware and was looking at integration my controllers and logic there with `TestHost`. My current issue is testing such that I could bypass the actual authentication and set appropriate mock claims that my app uses to identifier the user in these tests.

I currently setup the `IWebHostBuilder` instance as below.

```csharp
var host = new WebHostBuilder()
    .ConfigureServices(services =>
    {
        services.AddEntityFramework()
            .AddEntityFrameworkSqlite()
            .AddDbContext<MyDbContext>(efOptions => {
                efOptions.UseSqlite($"Data Source={GetType().ToString()}.sqlite");
            });
    })
    .UseKestrel()
    .UseContentRoot(Directory.GetCurrentDirectory())
    .UseIISIntegration()
    .UseStartup<Startup>();
```

And the bearer auth is setup in Startup.cs as so:

```csharp
app.UseJwtBearerAuthentication(new JwtBearerOptions
{
    AutomaticAuthenticate = true,
    AutomaticChallenge = true,
    Audience = "clientId",
    Authority = "authority"
});
```

Is there some guidance and/or docs on how to appropriately run integration tests in this circumstance? I would imagine I would have to replace some of the appropriate services in my TestHost `ConfigureServices` block (similar to overriding EF to use sql lite as above)? Or maybe mock the claims set/get that my `User` object on the controller has?

The two documentation articles I found on [Testing controllers](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing) and [Integration Testing](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing) don't take into consideration user authentication.

Thanks in advance and I'd be happy to follow up and contribute my learnings back to the aspnet docs for integration testing if I can get this working.

**Comment by Tratcher** [comment]
TestHost is not well set up to sub out pieces of your pipeline for you. In the test environment you either need to hook into the JWT events and override the identity, or you need to replace the JWT middleware completely.

**Comment by Eilon** [comment]
`TestServer` is largely just for the ASP.NET team to test its own features and is not meant as a general purpose testing harness. As such, we are not planning to add this kind of behavior to it.

**Comment by damienpontifex** [comment]
That's surprising @Eilon Why do they have the docs on controller and integration testing then if it's just for the team to test features? I've found the `TestServer` to be a great tool to extend tests past unit tests and I thought similarly existed back in OWIN/Web API 2. I'll raise the issue on the Hosting repo if I need further assistance. Thanks

**Comment by AArnott** [comment]
ping. Can we please get an official response to this? I'd very much like to know how to mock up authentication when doing integration testing.

**Comment by Eilon** [comment]
A month ago we release ASP.NET Core 2.1.0 Preview 1, which has some fully supported testing features: https://blogs.msdn.microsoft.com/webdev/2018/03/05/asp-net-core-2-1-0-preview1-functional-testing-of-mvc-applications/

And this week we just release Preview 2 as well.

Please give those a try and let us know if you have feedback on them by logging new issues.

**Comment by AArnott** [comment]
Thanks. That documentation actually directs us to use the same package that includes the `TestServer` class, which you indicated earlier is just for the ASP.NET team to test its own features. Is that still the policy?

**Comment by Eilon** [comment]
Well that was 1+ years ago, and things have changed 😄 

Pretty much any public type (except types in `.Internal` namespaces) is fair game to use and supported, but that doesn't necessarily mean we invest a lot of effort in it due to competing priorities. In this case we still use `TestServer` as part of the new testing feature, but the new features were pretty much all external to `TestServer` (which has changed very little).
