### ISSUE TITLE
HandleRequirementAsync not called for resource based authorization

### ISSUE THREAD

**Issue by FramnkRulez** [aspnet/Security#1103]
I've been attempting to get resource based authorization working following the examples online but for some reason when I do this I cannot get the HandleRequirementAsyc override to get called on my AuthorizationHandler.

I defined a requirement and handler as follows:

```
    public class MyPermissionRequirement : IAuthorizationRequirement
    {
        public MyPermissionRequirement(Permissions permission)
        {
            Permission = permission;
        }

        protected Permissions Permission { get; set; }
    }

    public class MyAuthorizationHandler : AuthorizationHandler<MyPermissionRequirement, MyResource>
    {
        protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, 
                         MyPermissionRequirement requirement, MyResource resource)
        {
            return Task.CompletedTask;
        }
    }
```

I inject the handler into my services in Startup.cs:

`services.AddSingleton<IAuthorizationHandler, MyAuthorizationHandler>();`

Then in my controller method I call:

```
if (await _authorizationService.AuthorizeAsync(User, resource: myResource, requirement: new 
       MyPermissionRequirement(Permissions.Read)))
{
}
```

However if I set a breakpoint in HandleRequirementAsync and call my controller method it never gets hit (and doesn't seem to execute based on the behavior I see).  Of note, if I override HandleAsync() in my custom AuthorizationHandler it *does* get called and I can see my resource and requirement in the supplied context.  

I suppose I could do my authorizatoin in HandleAsyc() but I'm curious what is going wrong that causes HandleRequirementAsync() to get skipped?

**Comment by HaoK** [comment]
Is your resource null?

**Comment by FramnkRulez** [comment]
No, as I mentioned I can see both the requirement and the resource (non-null) as members of the context if I override the HandleAsync() method.

**Comment by HaoK** [comment]
HandleAsync does this by default, you can put this into your handler and debug it to see whats going on exactly:
```C#
        public virtual async Task HandleAsync(AuthorizationHandlerContext context)
        {
            if (context.Resource is TResource)
            {
                foreach (var req in context.Requirements.OfType<TRequirement>())
                {
                    await HandleRequirementAsync(context, req, (TResource)context.Resource);
                }
            }
        }

```

**Comment by HaoK** [comment]
I can't repro this, here's the unit test I added to double check your scenario:

```
        public class MyResource { }

        public class MyPermissionRequirement : IAuthorizationRequirement
        {
        }

        public class MyAuthorizationHandler : AuthorizationHandler<MyPermissionRequirement, MyResource>
        {
            protected override Task HandleRequirementAsync(AuthorizationHandlerContext context,
                             MyPermissionRequirement requirement, MyResource resource)
            {
                context.Succeed(requirement);
                return Task.FromResult(0);
            }
        }

        [Fact]
        public async Task AuthorizeHandlerCalledWithCustomResource()
        {
            // Arrange
            var authorizationService = BuildAuthorizationService(services =>
            {
                services.AddAuthorization(options =>
                {
                    options.AddPolicy("policy", policy => policy.AddRequirements(new MyPermissionRequirement()));
                });
                services.AddTransient<IAuthorizationHandler, MyAuthorizationHandler>();
            });
            var user = new ClaimsPrincipal();

            // Act
            // Assert
            Assert.True(await authorizationService.AuthorizeAsync(user, new MyResource(), "policy"));
        }
```

Feel free to reopen this if you can tweak this test to fail in the way you are seeing.

**Comment by yshpakov** [comment]
How about
authorizationService.AuthorizeAsync(user, **(MyResource)null**, "policy")
?
It will never trigger HandleRequirementAsync 
You know
null is SomeClass
will always be false.
