### ISSUE TITLE
Validating Issuer for RS256

### ISSUE THREAD

**Issue by jerriep** [aspnet/Security#1104]
I have a token which is signed using RS256, and I have my JWT middeware configured as follows:

```
JwtBearerOptions options = new JwtBearerOptions
{
    Audience = Configuration["Auth0:ApiIdentifier"],
    Authority = $"https://{Configuration["Auth0:Domain"]}"
};
app.UseJwtBearerAuthentication(options);
```

with the following config values:

```
{
  "Auth0": {
    "Domain": "jerrie.auth0.com",
    "ApiIdentifier": "https://rs256.test.api"
  }
}
```

My token validation passes, but I have a concern about the validation of the issuer. It would appear that the Issuer is validated based on my `Authority`, but I am not sure where and how this happens.

I hooked up the `OnTokenValidated` event to be able to inspect the `TokenValidationParameters`, and even though the `ValidateIssuer` property is `true`, the `ValidIssuer` and `ValidIssuers` properties are null

![image](https://cloud.githubusercontent.com/assets/1006420/22411091/a725c8be-e6d2-11e6-8666-9c0759820c9d.png)

The I went one step further and added a bogus Issuer to the JWT middleware registration:

```
JwtBearerOptions options = new JwtBearerOptions
{
    Audience = Configuration["Auth0:ApiIdentifier"],
    Authority = $"https://{Configuration["Auth0:Domain"]}",
    TokenValidationParameters = new TokenValidationParameters()
    {
        ValidIssuer = "http://this.should-fail"
    },
    Events = new JwtBearerEvents()
    {
        OnTokenValidated = context =>
        {
            return Task.FromResult(0);
        },
        OnChallenge = context =>
        {
            return Task.FromResult(0);
        }
    }
};
app.UseJwtBearerAuthentication(options);
```

And when I inspect the `TokenValidationParameters`, my `ValidIssuer` is clearly wrong and should fail:

![image](https://cloud.githubusercontent.com/assets/1006420/22411187/c56140f0-e6d3-11e6-8b73-2f773b8b9b55.png)

(BTW, the correct issuer is `https://jerrie.auth0.com/`)

So it would appear that somewhere along the line, the value of the `Authority` property gets also used as a valid issuer (which is what I expect to happen) since the token validation is successful.

The thing is however that I need to confirm that this is what is happening. Can someone please explain this, and perhaps even point me to the source code where this happens?

Thanks :)

**Comment by PinpointTownes** [comment]
> perhaps even point me to the source code where this happens?

Exactly here: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L78-L86

**Comment by jerriep** [comment]
Hey Kevin, thanks for the link. I looked at that source code before, but it is still not clear where and how it gets the value from the `Authority`?

**Comment by PinpointTownes** [comment]
> but it is still not clear where and how it gets the value from the Authority?

It doesn't. At least, not directly. Instead, it retrieves the `issuer` property from the discovery document, which, in practice, coincides with the `Authority` setting.

**Comment by jerriep** [comment]
Aah, that explains it. Thank you!

You're a genius as always ;)
