### ISSUE TITLE
The purpose of RefreshOnIssuerKeyNotFound

### ISSUE THREAD

**Issue by Pikhulya** [aspnet/Security#1105]
The file Security/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs 
contains the following code in the lines 106-111:

```
// Refresh the configuration for exceptions that may be caused by key rollovers. The user can also request a refresh in the event.
if (Options.RefreshOnIssuerKeyNotFound && Options.ConfigurationManager != null
	&& ex is SecurityTokenSignatureKeyNotFoundException)
{
	Options.ConfigurationManager.RequestRefresh();
}

```
Which looks like it will force configuration refresh but only for the *next* request rather than for *this* current one which means that the current one would fail, is that really by design? If so, what is the rationale behind that if there is a chance to recover from emergency key rollover by refreshing the configuration and then try validating the signature again?

Looking at [Modern  Authentication with Azure Active Directory for Web Applications ](https://ptgmedia.pearsoncmg.com/images/9780735696945/samplepages/9780735696945.pdf)(please search there for RefreshOnIssuerKeyNotFound) it looks like the idea of the property RefreshOnIssuerKeyNotFound was to automatically fix stale keys, but looking at the code it doesn't look like the current request has chances to succeed (in case of emergency key rollover described in the book), only *next* one has those chances.
And one more question: Why does that property exist at all instead of always assuming it would have value of True? What are the scenarios when someone would not want to recover from emergency key rollover?

**Comment by leastprivilege** [comment]
Yes - I don't like this behavior as well.

Unless there is some really good reason for this design - I would also prefer that the current request succeeds - and not the next one.

**Comment by Tratcher** [comment]
There are a couple of issues here:
1. There's no guarantee that SecurityTokenSignatureKeyNotFoundException was caused by out of date config, though that may be the most common scenario.
2. The middleware has no way of knowing how long it will take config to refresh, or if a config refresh is even supported. Blocking all requests in the pipeline during a non-deterministic external resource access is concerning to say the least.
3. Config refresh is rate limited, it will only attempt it so often. RequestRefresh is just a hint that maybe it should try again.
4. Code complexity / re-entrance / loops. Resetting the handler state and starting over is complex and error prone. We also can't reset any app state from the extension events.

**Comment by Pikhulya** [comment]
1. May be, at the same time an attempt to recover from hypothetically stale keys by re-reading them from the JWKS document seems like not a bad idea if that re-read would really took place in *this* current request.
2. There are legitimate cases when the code would eventually need to re-read those keys (once they are expired by the ConfigurationManager's definition) from external resource, so, I am trying to say that the external endpoint will in any case be accessed at certain moments in time to update the keys even if there is no SecurityTokenSignatureKeyNotFoundException, to me it looks like normal and expected behavior. If those attempts to access JWKS endpoint would be done for every request or otherwise too often then, of course, it would not be acceptable but since the results are cached it doesn't look like a problem.
3. Agreed that the protection you outlined makes sense, at the same time it would be good if that hint is "materialized"/"executed" right a way in case the refresh rate is not violated. Seems like the main purpose of that flag was to recover from Emergency Keys Rollovers which, theoretically, could of course took place more often than ConfigurationManager.DefaultAutomaticRefreshInterval but in practice that is probably not realistic, as a result I think it is safe to assume that those Emergency Rollovers will not happen more often than ConfigurationManager.DefaultAutomaticRefreshInterval so it would be safe to re-read the configuration **just once** if it is known that all keys in the cache are outdated and if this re-read will not violate the refresh rate.
4. I understand that a refactoring would be needed to achieve that but it would probably pay back because then the middleware could be for sure said "it does support majority of emergency keys rollover cases without sacrificing any requests".

**Comment by leastprivilege** [comment]
@Tratcher I understand. thanks for the explanation.

**Comment by Tratcher** [comment]
2. In a normal key roll there will be an overlap period so a periodic refresh is sufficient. It's only emergency key rolls that hurt you, and honestly if you're doing an emergency key roll then a few failed requests are the least of your worries.

I haven't seen any scenarios where RefreshOnIssuerKeyNotFound would need to be turned off. @brentschmaltz?

**Comment by Pikhulya** [comment]
@Tratcher Yeah, thanks, after reading the book I mentioned in the first post I had the same understanding that the purpose of the flag is to help with Emergency Key Rollover only.
As for 

> _"... the least of your worries..."_

 - could you please provide an example on why my application would experience any additional issues if **an Identity Provider** initiated Emergency Key Rollover? Per my understanding that rollover could only affect token validation and only in this current implementation of the middleware where that property is used the way we are being discussing.

**Comment by Tratcher** [comment]
I meant that if an identity provider initiated an emergency key rollover it's because they feared their keys were compromised (e.g. a security breach). At which point you have to start wondering if that breach transitively affects you too and if you should freeze your site to investigate. Uptime is far less relevant in the face of a potential security breach.

**Comment by Pikhulya** [comment]
Ahh, OK, I see your point, hard to disagree with that but at the same time I don't think that middleware/application should just "give up" if something else went wrong - every part of the system still has to behave as much ideal as possible instead of "saying": if one part of the system has failed it is OK for me to not do my best with my responsibilities.

**Comment by Eilon** [comment]
Given the rarity of this event we are putting this in the backlog for now.

**Comment by Pikhulya** [comment]
Thanks for looking into this.

**Comment by Eilon** [comment]
Closing because no further action is planned on this issue.
