### ISSUE TITLE
How to customize the OpenIdConnect Url when Redirecting To an IdentityProvider?

### ISSUE THREAD

**Issue by carlos-sarmiento** [aspnet/Security#1106]
We are building a SaaS application in which we are using IdentityServer4 as our IdentityProvider.

Something we want to do is that every tenant gets its own vanity subdomain, including login/logout functionality. We have IdentityServer4 configured to issue all tickets with the same issuer regardless of which domain was used to access it.

The problem we are facing is on how we can change the Url to which the application that uses OpenIdConnectAuthentication is redirecting so that it goes to appropriate vanity login for the request and not the authorityUrl?

**Comment by Tratcher** [comment]
Have you tried using the RedirectToIdentityProvider Event on OpenIdConnectOptions?
http://www.jerriepelser.com/blog/adding-parameters-to-openid-connect-authorization-url/

**Comment by carlos-sarmiento** [comment]
I was trying to use it to do another kind of redirect, but when the Event gets called, the Location Header isn't set yet, so I thought it wasn't useful.

That blog post was a lifesaver. Thanks
