### ISSUE TITLE
Use same naming convention for all returned values (errors) in all places

### ISSUE THREAD

**Issue by Misiu** [aspnet/Security#1107]
I'm not sure if this is correct place, so please excuse me if I'm posting this issue in wrong place.
I've found this issue building WebAPI 2.2 application, not sure if this is an issue, but probably is.

Inside my custom `OAuthAuthorizationServerProvider` inside `GrantCustomExtension` I'm setting errors using: 
```C#
context.SetError("invalid_grant", "Account locked.");
```
this is returned as below JSON:
```JSON
{
  "error": "invalid_grant",
  "error_description": "Account locked."
}
```
as You can see error and error_details are returned with snake_case.

When I return BadRequest inside ApiController I get this response:
```JSON
{
  "message": "The request is invalid.",
  "modelState": {
    "client.Email": [
      "Email is not valid."
    ],
    "client.Password": [
      "Password is required."
    ]
  }
}
```
as You can see there is property `modelState`.

I'd like to ask if it is possible to unify naming so that `OAuthAuthorizationServerProvider` would use formatter set in HttpConfig, so that we would be able to define naming rules globally.

**Comment by Eilon** [comment]
Hi @Misiu , the difference in casing/style here is due to different requirements of the data. The MVC BadRequest data uses a style that is more similar/compatible to what JavaScript frameworks use, whereas the Security data doesn't have that requirement. It would also be a breaking change to switch the style.

As such, there are no plans to change this behavior.

**Comment by Misiu** [comment]
@Eilon thanks for reply. I wasn't proposing changing the style by default, but allowing us (developers) to specify style and (if possible) name of properties.
In my case, I'd like returned value to have same property names (not error and message). I'd like to unify that, bus as I wrote that's just my personal preference, but framework should allow that.
