### ISSUE TITLE
[Question] Opening the soution in VS2015 Community Edition

### ISSUE THREAD

**Issue by alokshriram** [aspnet/Security#1108]
I just cloned this project, and wanted to look/step through some of this code.  However when I open this in VS 2015, I see the following fpr all the projects.

```
CookieSessionSample.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\ANM-HomePC\Source\Repos\Security\samples\CookieSessionSample\CookieSessionSample.csproj
```

I have 2015 Update3 which I just installed and Download .NET Core 1.0.1 tools Preview 2. Any hints as to what dumb thing I am missing ?

![notopening](https://cloud.githubusercontent.com/assets/2653351/22535366/871f8d32-e8af-11e6-96fa-11dd0812d0d3.png)

thanks

**Comment by Tratcher** [comment]
VS2017 RC is now required for ASP.NET Core projects.

**Comment by alokshriram** [comment]
@Tratcher  Thanks !

**Comment by arpit-nagar** [comment]
Any plans to support .csproj (.net core) type of projects in VS15?

**Comment by Tratcher** [comment]
No
