### ISSUE TITLE
JwtBearerHandler always returning 401 (even when 403 expected)

### ISSUE THREAD

**Issue by codefactorydevelopment** [aspnet/Security#1114]
When using JwtBearerToken in the following way:

```
app.UseJwtBearerAuthentication(new JwtBearerOptions
            {
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                TokenValidationParameters = tokenValidationParameters
            });
```

and then checking user roles on controller action like:

`[Authorize(Roles="whateverrole"]`

for a valid token that does contain roles claim (and claims are correctly mapped to roles which is confirmed by checking User.IsInRole("whateverroleisinJWT") being true for all roles assigned in JWT) but does not assign specific "whateverrole" to user JWTBearerMiddleware/Handler returns 401 instead of 403.

I have already seen some discussions about it but, honestly, haven't found out any satisfying explanation nor direction how to solve that actualy.

So, the question is...Is it really expected behavior that if user IsAuthenticated (so, token is valid and Identity is created) but not Authorized (does not have sufficient roles/claims) JWTBearerMiddleware should return 401 instead of 403? or is that just a bug?

Furthermore, if its expected, is there any non-workaround, non-hack way to use JWTBearerMiddleware so that it returns 403 when its supposed so?

Am i missing something or is this causing always to have that 401?
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L212

**Comment by Tratcher** [comment]
Hmm..
The Challenge vs Forbid code is in the base class.
https://github.com/aspnet/Security/blob/da4730a3922dd885fdda013f5efa72010a7d0170/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L353
Jwt doesn't implement HandleForbidAsync, so it should inherit it from the base class:
https://github.com/aspnet/Security/blob/da4730a3922dd885fdda013f5efa72010a7d0170/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L332

We'll have to reproduce this and see why it's not taking the forbid code path.

**Comment by codefactorydevelopment** [comment]
Could the problem be the following:

1) in ChallengeAsync it calls:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L353

with parameter context.AuthenticationScheme which, for JWT, should be 'Bearer' (set in JWTBearerOptions constructor)

2) in 
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L210

it compares that authentication scheme ('Bearer' in this case) to AuthenticationManager.AutomaticScheme (which is 'Automatic'). that returns false and that might be the reason not going into handling Forbidden.

**Comment by Tratcher** [comment]
@codefactorydevelopment I don't think that's it, you missed the prior line https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L209

**Comment by codefactorydevelopment** [comment]
hm...right.

would be great if someone could try to reproduce this and confirm what is it about.

**Comment by HaoK** [comment]
We do have a test for this scenario simulating what the authorize attribute does, can you try replacing the authorize attribute with the equivalent logic that's going on behind the covers that the filter is doing:

See https://github.com/aspnet/Security/blob/dev/test/Microsoft.AspNetCore.Authentication.Test/JwtBearer/JwtBearerMiddlewareTests.cs#L380

First turn off automatic challenge/authenticate
And in your action do this instead and see if it gives you a 403:
```
                            var result = await context.AuthenticateAsync(JwtBearerDefaults.AuthenticationScheme);
                            await context.ChallengeAsync(JwtBearerDefaults.AuthenticationScheme);
```

**Comment by codefactorydevelopment** [comment]
Thanks for your response.
So, i can confirm that when i remove Authorize attribute and put those lines into my action, i do get 403.

Now, what does that mean?

**Comment by HaoK** [comment]
Looks like it might be an issue with automatic challenge, try setting the scheme explicitly in your Authorize

either

`[Authorize(Roles = "whatever", ActiveAuthenticationScheme = "Bearer")]`

Or setting it via the default policy: 

```C#
            services.AddAuthorization(options =>
            {
                options.DefaultPolicy = new AuthorizationPolicyBuilder("Identity.Application").RequireAuthenticatedUser().Build();
            });
```

For more details see https://github.com/aspnet/Announcements/issues/210

**Comment by codefactorydevelopment** [comment]
Thank you.

I can confirm that setting a scheme explicitly worked and now returns 403 as expected.

Now, i am not familiar with publish process, so what does this mean? Should we use it this way with explicit setting? And, what is usual time to expect some real fixes for things like this?

Thanks

**Comment by Tratcher** [comment]
Can you share your project.json file? This is similar to an issue caused by mixing 1.0 and 1.1 packages

**Comment by codefactorydevelopment** [comment]
Sure. Here it is:

`{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "System.IdentityModel.Tokens.Jwt": "5.1.2",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.1.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`

**Comment by Tratcher** [comment]
Yup, don't mix 1.0 and 1.1. there's a known issue here with IISIntegration 1.0

**Comment by codefactorydevelopment** [comment]
oh, had now idea about that. thank you very much for that finding!

you are talking JwtBearer 1.1, right?
what do you suggest to do?

**Comment by Tratcher** [comment]
Update everything to 1.1 (or highest available)

**Comment by codefactorydevelopment** [comment]
Great, i will do that.

Thank you very much!

**Comment by codefactorydevelopment** [comment]
Ok, just to post a final confirmation for the case someone else run into this situation.

I can confirm that upgrading to Asp.Net Core 1.1 and upgrading all packages to latest versions did the job. Now 403 is return when expected.

Instructions on how to upgrade to 1.1 are here:
https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/

Thanks one more time!
