### ISSUE TITLE
Resource based authorization: Multiple resources

### ISSUE THREAD

**Issue by Tobias-Gr** [aspnet/Security#1115]
Hi,
does resource based authorization aim only at securing a single resource per call (e. g. GetDocument)? Or does the mechanism cover securing multiple resources (e. g. GetDocuments ->all documents that I am allowed to read), too? I didn't find any samples for the second scenario. 
Thanks!

**Comment by Eilon** [comment]
The definition of "resource" is somewhat arbitrary - that is, you can define a "resource" to be whatever you want. So, given that, you could define a resource as a "collection of documents" and authorize based on that.

If you meant something else, it would be great if you could provide additional details and examples.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
