### ISSUE TITLE
Create Client Certificate Authentication middleware

### ISSUE THREAD

**Issue by blowdart** [aspnet/Security#1118]
Spawning from https://github.com/aspnet/KestrelHttpServer/issues/1344

1) By default should reject revoked certs and certs without a client auth EKU (note a cert without any EKUs at all means it's valid for every EKU).
2) Expose X509 Chain so users don't have to recreate it, as this is expensive once CRLs get involved.
3) Have a method where users get the cert and the chain, and can then make decisions and construct an identity based on their decision.

This is analogous to the IIS client cert pieces.

**Comment by Tratcher** [comment]
Additional research: How can you define an Authorization Policy that requires multiple concurrent auth types? E.g. Client Cert & Bearer.

Also, what should Callenge/Forbid do for this middleware?
https://support.microsoft.com/en-us/help/186812/-403.7-forbidden-client-certificate-required-error-when-you-open-an-iis-webpage
Nginx has a few status codes that may be useful for this:
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#nginx

**Comment by HaoK** [comment]
Just list multiple schemes and the filter will authenticate/challenge for both at the same time.

**Comment by Yves57** [comment]
@blowdart Sorry for the question, but because the middleware is (currently?) missing, I need to create a simple version myself :-).
The client certificates that I need to verify are from an self-signed root certificate. Is it enough to check the client certificate validation date and the thumbprint, or more verifications are needed (check if the parent is the same root, or anything else)?
Thank you for the answer that may interest other people.

**Comment by blowdart** [comment]
Certificate thumbprint is based on SHA1 (We're looking at adding a new property to make it SHA256 based, but changing classes is hard compat wise). Although there's not been any demonstrations that you can generate an X509 certificate with a SHA1 collision yet it's probably going to happen at some point. So I'd look at the thumbprint, the expiration date, the valid from date, the lack of a signing chain, and get a subject name check in there too.

**Comment by larsw** [comment]
Any status on this middleware?

**Comment by xavierjohn** [comment]
While we wait, you can try out the package I made for me https://www.nuget.org/packages/CWiz.ClientCertificateMiddleware/1.0.0
till something official comes out.

**Comment by xavierjohn** [comment]
I have updated the middleware to .net standard 2.0
https://github.com/xavierjohn/ClientCertificateMiddleware/pull/1/files

It will be nice to incorporate it into the security package.

**Comment by herecydev** [comment]
@HaoK Is that actually true? If I read [this](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authorization.Policy/PolicyEvaluator.cs#L47) right, it requires any scheme to succeed for authentication to  be a success. Obviously, only the authenticated schemes are merged into the principal

**Comment by abatishchev** [comment]
Any news on a built-in middleware?

**Comment by Eilon** [comment]
Closing this because we have https://github.com/aspnet/Security/issues/1575 logged for the 3.0 milestone.
