### ISSUE TITLE
How facebook authentication middleware validates facebook access token

### ISSUE THREAD

**Issue by waqaskhan540** [aspnet/Security#1119]
I wonder how the facebook authentication middleware is validating the access token generated by facebook , if it is actually validating it. 

Because I don't see the debug_token endpoint listed in the code.? can u guide me that how are you validating the facebook access token in your middleware?..

thanks..

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io

**Comment by Tratcher** [comment]
The middleware doesn't perform any validation on the token, it forwards the token to facebook's user-info endpoint and they perform the validation.
