### ISSUE TITLE
Cannot redirect to the end session endpoint on HandleSignOutAsync

### ISSUE THREAD

**Issue by ErezSavir** [aspnet/Security#1120]
Hello,

I'm trying to configure OpenIDConnect authentication and I think I configured something wrong.

My Startup class:

On ConfigureServices:
`            services.AddAuthentication(options =>
            {
                options.SignInScheme = "ClientCookie";
            });`

On Configure:
`

    app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                AuthenticationScheme = "ClientCookie",
                CookieName = CookieAuthenticationDefaults.CookiePrefix + "ClientCookie",
                ExpireTimeSpan = TimeSpan.FromMinutes(5),
                LoginPath = new PathString("/signin"),
                LogoutPath = new PathString("/signout")
            });
    app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions()
            {
                RequireHttpsMetadata = false,
                SaveTokens = true,
                ClientId = ClientID,
                ClientSecret = ClientSecert,
                PostLogoutRedirectUri = "http://localhost:55462/",
                ResponseType = OpenIdConnectResponseType.Code,
                Authority = "https://accounts.google.com",
            });`
The login is working as expected and I get all the information.
However when calling
`return SignOut("ClientCookie", OpenIdConnectDefaults.AuthenticationScheme);`

I get 
InvalidOperationException: Cannot redirect to the end session endpoint, the configuration may be missing or invalid.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler+<HandleSignOutAsync>d__17.MoveNext()

What am I missing?

Thank you.

**Comment by PinpointTownes** [comment]
> What am I missing?

Google doesn't have an end session endpoint.

**Comment by ErezSavir** [comment]
:) OK. Did not know that. 
Thank you. 
Can be closed.
