### ISSUE TITLE
signin-oidc is pending when authorize is finished [ubuntu16.04]

### ISSUE THREAD

**Issue by atpyk** [aspnet/Security#1121]
Everything work fine on my local(windows platform). When I deploy them onto **linux(ubuntu16.04)**, the issue raised.

![](https://raw.githubusercontent.com/atpyk/LinksOutside/master/signinoidc_pending.png)

I can't get any response after I sign in successfully, it always loading until receive  a blank page.

**Comment by Tratcher** [comment]
What's the status code and headers for that 'blank page'? If it's a 500 then you should check your server logs for an error.

**Comment by atpyk** [comment]
Snapshot1: It takes too long time that is about 15mins.
![](https://raw.githubusercontent.com/atpyk/LinksOutside/master/gatewaytimeout.png)

Snapshot2: 
![](https://raw.githubusercontent.com/atpyk/LinksOutside/master/gatewaytimeout2.png)

**Comment by atpyk** [comment]
It's my configuration for OpenId middle ware:

` app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                AuthenticationScheme = "oidc",
                SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme,
                AutomaticAuthenticate = false,

                Authority = Settings["AuthorityUrl"],
                RequireHttpsMetadata = false,

                ClientId = "*****.dashboard",
                ClientSecret = "secret",
                ResponseType = OpenIdConnectResponseType.CodeIdToken,
                Scope = { "basicinfo **** ***" },
                GetClaimsFromUserInfoEndpoint = true,
                SaveTokens = true,

                Events = new OpenIdConnectEvents()
                {
                    OnMessageReceived = context =>
                    {
                        if (context.ProtocolMessage.Error != null)
                        {
                            context.SkipToNextMiddleware();
                            context.Response.Redirect("/Home/Error");
                        }

                        return Task.FromResult(0);
                    },

                    OnRemoteFailure = context =>
                    {
                        if (context.Failure is OpenIdConnectProtocolException)
                        {
                            context.Response.Redirect("/Home/AccessDenied");
                            context.HandleResponse();
                            return Task.FromResult(0);
                        }
                        else
                        {
                            context.SkipToNextMiddleware();
                            context.Response.Redirect("/Home/Error");
                        }

                        throw context.Failure;
                    }
                }
            });`

**Comment by Tratcher** [comment]
Likely unrelated, but
```
context.SkipToNextMiddleware();
context.Response.Redirect("/Home/Error");
```
is a nonsensical combination. You should use HandleResponse() with Redirect.

**Comment by Tratcher** [comment]
Also, don't re-throw the exception in OnRemoteFailure.

**Comment by atpyk** [comment]
I forget to remove "OnMessageReceived" section, thanks for your mention.

**Comment by atpyk** [comment]
The error still have.

**Comment by Eilon** [comment]
@atpyk we recommend enabling logging so that it'll be easier to see at what point the server is taking too long. If you could do that and share your logs we can investigate further.

**Comment by atpyk** [comment]
I report this issue to IdentityServer4 too: [https://github.com/IdentityServer/IdentityServer4/issues/730](url)

No error log in Idsvr side, the client portal side's log is:

fail: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware[17]
Exception occurred while processing message.
Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired.
ValidTo: '01/22/2017 01:00:59'
Current time: '01/22/2017 01:05:59'.
at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable1 notBefore, Nullable1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateLifetime(Nullable1 notBefore, Nullable1 expires, JwtSecurityToken securityToken, TokenValidationParameters validationParameters)
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateToken(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters, JwtSecurityToken& jwt)
at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.d__20.MoveNext()
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware[4]
Error from RemoteAuthentication: IDX10223: Lifetime validation failed. The token is expired.
ValidTo: '01/22/2017 01:00:59'
Current time: '01/22/2017 01:05:59'..

**Comment by PinpointTownes** [comment]
> ValidTo: '01/22/2017 01:00:59'
Current time: '01/22/2017 01:05:59'

I'm really tempted to say that @leastprivilege already gave you the right answer: https://github.com/IdentityServer/IdentityServer4/issues/730#issuecomment-274463452.

That said, you likely have another issue (with your proxy?), as the request is not supposed to hang when it's rejected by the OIDC middleware.

**Comment by atpyk** [comment]
We use the nginx to deploy the Idsvr4 and webportal on the same sever, and just to do the easy setting for mapping to the corresponding ports, Idsvr4 is 5000; webportal is 5005. 
Did you guys reproduce this issue by nginx. That's a very tough issue.

**Comment by Eilon** [comment]
@atpyk can you try changing the `OnRemoteFailure` handler to check for an additional exception type?

Currently it checks `context.Failure is OpenIdConnectProtocolException`, but in this case you might want to also handle a `Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException`.

Also, please check the `else` class of the `OnRemoteFailure` where it currently has these two lines:

```c#
context.SkipToNextMiddleware();
context.Response.Redirect("/Home/Error");
```

And you probably want to remove the call to `context.SkipToNextMiddleware();`.

**Comment by atpyk** [comment]
Guys, I found the root cause, so far it took our lots of time. So tough.
We use the .net core 1.1 to develop and deploy the Idsvr4 and Webportal, all the version of packages are >= 1.1.0.  
Eventually we had to downgrade these 2 packages to 1.0.1, it has been fixed:
   "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.1.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    **"Microsoft.AspNetCore.Mvc": "1.0.1",**
    "Microsoft.AspNetCore.Mvc.Formatters.Json": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    **"Microsoft.AspNetCore.Server.Kestrel": "1.0.1",**
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",

**Comment by atpyk** [comment]
Many thanks for @Eilon and @PinpointTownes  and @Tratcher 's help. :)

**Comment by Eilon** [comment]
@atpyk ah, yes, mixing versions like that is not supported, so that could definitely be the cause of weird behavior.

Given that this issue appears to be resolved, I'm closing it. Thanks!

**Comment by atpyk** [comment]
Let me clarify it. Not mixed versions lead to this issue; this issue will happen when use the same version for all packages. The above solution that is the way to work around.

**Comment by henkmollema** [comment]
@Eilon it looks like @atpyk means that mixing version _does_ resolve this issue. This can't be the correct solution, can it?

**Comment by Tratcher** [comment]
Certainly not, but it does hint that the actual problem is in one of the packages you downgraded.

**Comment by Tratcher** [comment]
@cesarbs

**Comment by Eilon** [comment]
> @Eilon it looks like @atpyk means that mixing version _does_ resolve this issue. This can't be the correct solution, can it?

Oops, I missed that. This is definitely bizarre.

**Comment by cesarbs** [comment]
@atpyk Did you downgrade both packages at once? Do you still have the issue when downgrading only one of them?

Can you share the relevant bits of your nginx config?

**Comment by atpyk** [comment]
Yes, both. If I only downgrade either, it cannot work.
Below is our config of nginx:


server {
  listen 443;

  ssl on;
        ssl_certificate /etc/ssl/xxx_chain.crt;
  ssl_certificate_key /etc/ssl/xxx.key;
  server_name account-test.xxx.com;

  location / {
    proxy_pass http://localhost:5000;   //IdentityServer4
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_buffer_size 64k;
    proxy_buffers   32 32k;
    proxy_busy_buffers_size 128k;
    fastcgi_buffers 8 16k;
    fastcgi_buffer_size 32k;
    sendfile on;
    }
}

server {
  listen 443;

  ssl on;
ssl_certificate /etc/ssl/xxx_chain.crt;
  ssl_certificate_key /etc/ssl/xxx.key;
  server_name mvcclient-test.xxx.com;

  location / {
    proxy_pass http://localhost:5005;   //MVC Client
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_buffer_size 64k;
    proxy_buffers   32 32k;
    proxy_busy_buffers_size 128k;
    fastcgi_buffers 8 16k;
    fastcgi_buffer_size 32k;
    sendfile on;
    }
}

server {
  listen 80;
  server_name*.xxx.com;
  return 301  https://$host$request_uri;
}

server {
  listen 80 default_server;
  return 444;
}

**Comment by Eilon** [comment]
@cesarbs I'm parking this on your plate to investigate in case there's some Kestrel issue here.

**Comment by cesarbs** [comment]
@atpyk I am currently investigating this issue, but so far I haven't been able to reproduce it.

I noticed from your screenshots that you seem to be running behind Squid. Do you have access to its configuration? Authentication takes a while in my environment, and I could see a proxy timing that out.

But most important, can you try changing this line in your `nginx.conf`:

```
    proxy_set_header Connection 'upgrade';
```

To:

```
    proxy_set_header Connection $http_Connection;
```

And check if that fixes your problem (with Kestrel 1.1.1 and MVC 1.1.2, given your setup works on 1.0.x versions).

**Comment by cesarbs** [comment]
@atpyk I am now able to reproduce your issue. The change to the `Connection` header on nginx works for me - let me know if it works for you.

And indeed, downgrading to Kestrel 1.0.1 makes things work, even with nginx always sending `Connection: upgrade`. I'm currently trying to get to the bottom of it.

**Comment by cesarbs** [comment]
The reason this only repros on Kestrel 1.1.x and not in Kestrel 1.0.x is due to a subtle difference in how it handles requests with a `Connection: upgrade` header.

In Kestrel 1.0.x, a request with a `Connection: upgrade` AND a `Content-Length` header is handled as if its body's content length is known (internally uses `MessageBody.ForContentLength` to read the request body).

In Kestrel 1.1.x though, `Connection: upgrade` takes precedence in deciding how to handle the request body and it ends up being handled as a "read until client closes the connection" request body (internally uses `MessageBody.ForRemainingData` to read the request body).

What's causing the hang in this issue is that at some point in the authentication process the OIDC middleware attempts to read the request body from a POST request that is sent with a content length. However, because nginx is always sending a `Connection: upgrade` header, the middleware hangs waiting for data past what's in the request body, and that read never completes because the remote peer has no reason to close the connection.

Fortunately this issue can be mitigated by telling nginx to forward the client's `Connection` header (`proxy_set_header Connection $http_Connection`), instead of always sending `Connection: upgrade` (which doesn't seem reasonable anyways since not every request will be upgraded).

**We should consider patching Kestrel 1.1.x to match the behavior in 1.0.x** (i.e. `Content-Length` should take precedence over `Connection: upgrade` in determining how to handle the request body). The same change should be done in dev. cc @muratg @Eilon @davidfowl

**Comment by cesarbs** [comment]
I will close this issue and open a new one on Kestrel to consider the change in behavior on how to handle the request body.

**Comment by cesarbs** [comment]
@atpyk Please re-open if you still have issues with OIDC after changing your nginx configuration.

**Comment by ZOXEXIVO** [comment]
@cesarbs It's really problem.  We see this behaviour at OWIN OpenIdConnect provider.
If server long time not serving requests and IIS stop it - all requests, that need redirect to OpenIdConnect never ends. 
We get 504 timeout error for all our requests! iisreset helps

**Comment by ZOXEXIVO** [comment]
OWIN problem caused by deadlock in method System.Owin.Security

```
private static void OnSendingHeaderCallback(object state)
{
     AuthenticationHandler handler = (AuthenticationHandler)state;
     handler.ApplyResponseAsync().Wait();
}
```

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.

OWIN components are over here: https://github.com/aspnet/aspnetkatana
