### ISSUE TITLE
Manually setting cookie via header fails on new connections / sessions

### ISSUE THREAD

**Issue by snickler** [aspnet/Security#1123]
I have a web application running version 1.1 of all libraries that is configured with `UseCookieAuthentication` and `UseOpenIdConnectAuthentication` (Although I've commented it out for sake of troubleshooting this issue). I have a login method used for Forms Auth for use with legacy applications that we don't want on our third party IdP at the moment. The Login method creates a ClaimsIdentity using the CookieAuth scheme, adds a name claim to it and then uses SigninAsync to return a Cookie at the end of this request: 

```
var authIdentity = new System.Security.Claims.ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

authIdentity.AddClaims(new List<Claim> { new Claim(ClaimTypes.Name, _username) });

var authPrincipal = new ClaimsPrincipal(authIdentity);

await HttpContext.Authentication.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, authPrincipal, 
       AuthenticationProperties() { IsPersistent = true});
```
I can see the cookie in the response header when I hit the Login endpoint from my client and appending the cookie to the `DefaultRequestHeaders` works when hitting an a route that has the `Authorize` attribute in a secondary HttpClient.GetAsync request . As soon as I try a new request with that same cookie that I passed in, it seems to fail validation and redirects to the Signin page. 

Is there something I'm missing here? I want to retain the functionality I had back on MVC 5, but without having any extra code creation. Can anyone else reproduce this issue?

Sample client code
```
//This Works

HttpClient client = new HttpClient();
var signinResult = await client.PostAsync("http://localhost:2424/api/V1/auth/login",new StringContent("{Email: \"blah@blah.com\", Password: \"pass\"}",System.Text.Encoding.UTF8));
var cookie = signinResult.Headers.GetValues("Cookie");
client.DefaultRequestHeaders.Add("Cookie",cookie);
var requestWithCookie = await client.GetAsync("http://localhost:2424/api/V1/auth/checkauth"); //CheckAuth just returns Ok(), but has an Authorized attribute


//This Doesn't work
var client2 = new HttpClient();
client2.DefaultRequestHeaders.Add("Cookie",cookie);
var requestWithSavedCookie = await client2.GetAsync("http://localhost:2424/api/V1/auth/checkauth"); //Triggers auth

```

**Comment by Tratcher** [comment]
Shouldn't that be `var cookie = signinResult.Headers.GetValues("Set-Cookie");`? Also, the response Set-Cookie header has a different format from the Request Cookie header. Here's a parser you can use to get the values:
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/SetCookieHeaderValue.cs#L244

**Comment by snickler** [comment]
Sorry about that. I was trying to format the code. I've changed it around numerous times testing things. That's correct, it should be `var cookie = signinResult.Headers.GetValues("Set-Cookie")`. Basically, I DO get that cookie back in the format of `AspNetCore.Cookies=encryptedtext`. That gets passed along to a new HttpClient and it fails.

**Comment by Tratcher** [comment]
Is this .NET or .NET Core? HttpClient cookie management is different on the two. I suspect HttpClientHandler inside HttpClient is managing the cookie for you and your `client.DefaultRequestHeaders.Add("Cookie",cookie);` isn't actually doing anything. Try removing it.  The handler probably overwrites the Cookie header.

**Comment by snickler** [comment]
.NETCore. I'll post the LinqPad output if that'll help.

**Comment by Tratcher** [comment]
You can capture the traffic with fiddler to isolate if the problem is the client or server.

**Comment by snickler** [comment]
Thanks for the Fiddler suggestion. I feel VERY stupid now, forgetting that HttpClient requires a HttpHandler that sets a CookieContainer. This can be closed due to user error :).
