### ISSUE TITLE
InvalidOperationException when trying to do SignInAsync

### ISSUE THREAD

**Issue by Lutando** [aspnet/Security#1126]
I am trying to sign a user in, in a normal controller. I have something along the lines of:

```
var claims = new List<Claim>
{
    new Claim(JwtClaimTypes.Subject, "xxx-xxx-xx-xxx),
    new Claim(JwtClaimTypes.PreferredUserName, "someusername"),
    new Claim(JwtClaimTypes.Email, "foo@bar"),
    new Claim(JwtClaimTypes.EmailVerified, "foo@bar:),
    new Claim(JwtClaimTypes.IdentityProvider, "idsvr"),
};

var ci = new ClaimsIdentity(claims, "password", JwtClaimTypes.PreferredUserName, JwtClaimTypes.Role);
var cp = new ClaimsPrincipal(ci);
await HttpContext.Authentication.SignInAsync("myscheme", cp);
```

And I get an exception saying `InvalidOperationException: name claim is missing`

In the constructor of the ClaimsIdentity I specified my name claim to be `JwtClaimTypes.PreferredUsername` (which is "preferred_username")

If I do add a name claim to my claims list, then sign in works fine with the above snippet. However we actually don't have name claims in our system. We want to use the "preferred_username" as the name claim in your abstractions.

**Comment by PinpointTownes** [comment]
`InvalidOperationException: name claim is missing` is not an exception thrown by the security stack.

It sounds like an IdSrv exception: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/IdentityServerPrincipal.cs#L81

**Comment by Lutando** [comment]
Thanks seems like it is, I could not find where this would be thrown. Thanks for the pointer.
