### ISSUE TITLE
Provide a way to inject OpenId options like other middlewares

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Security#113]
Like this: 
https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/Startup.cs#L61

**Comment by brentschmaltz** [comment]
Can you add some detail, perhaps a code snippet?

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Security.Facebook/FacebookAuthenticationExtensions.cs#L26

**Comment by HaoK** [comment]
I'll do this as part of fixing https://github.com/aspnet/Security/issues/107
