### ISSUE TITLE
AuthenticationMiddleware and dependency injection

### ISSUE THREAD

**Issue by kampilan** [aspnet/Security#1134]
Why does AuthenticationMiddleware take it's dependencies on the constructor and not on Invoke? Very hard to build handler with dependencies. Why would TearDownAsync be internal!?!? This prevents me from writing my own AuthentionMiddleware and using proper DI pattern for Middleware.

**Comment by HaoK** [comment]
Yeah we are aware of the issues with the current design, we working on addressing these in the next version, you should be able implement a handler with normal dependencies on the new stack, see https://github.com/aspnet/Security/pull/1113

**Comment by Eilon** [comment]
Closing because this is a key part of the Great Auth Redesign of 2017.

**Comment by epot** [comment]
Is there a way to inject IOptions that is parsing the application settings into an AuthenticationHandler (instanciated by an AuthenticationMiddleware) in asp.net core 1.x? Or at least a workaround?

**Comment by HaoK** [comment]
You can use the configuration extensions in options for that https://github.com/aspnet/Options/blob/dev/src/Microsoft.Extensions.Options.ConfigurationExtensions/OptionsConfigurationServiceCollectionExtensions.cs#L22 that's been around since 1.x
