### ISSUE TITLE
ValidateUserInternal could be called prior to UpdatePasswordHash?

### ISSUE THREAD

**Issue by Ponant** [aspnet/Security#1135]
When `CreateAsync ` a user, `UpdatePasswordHash` is called prior to checking `ValidateUserInternal` , whereas one could reverse the order such that, e.g. if UserName is already taken `ValidateUserInternal` will return an error without the need to go through `UpdatePasswordHash.`

**Comment by HaoK** [comment]
The general pattern for identity is to update the user with all the changes, and then run validation as the last step before saving changes.  There's nothing preventing a validator from wanting to inspect the password hash which it would not be able to do if it ran before the password hash was updaated.
