### ISSUE TITLE
Update the OAuth2 generic handler to allow setting the scope when calling ChallengeAsync

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#1139]
_Moved from https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/146:_

___________

I'm currently working with the EVEOnline provider and I want to let the user choose what scopes to use due to it giving access to sensitive information and the functionality it opens up on my site being entirely optional.

So is there an easy way to set different scopes for every authentication request?

**Comment by PinpointTownes** [comment]
@Gronsak not directly, but you can use the `RedirectToAuthorizationEndpoint` event to dynamically update the authorization request: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OAuth/Events/IOAuthEvents.cs#L25

Ideally, the OAuth2 generic handler could be updated to allow setting the scope dynamically using a specific authentication property, that could be set when calling `ChallengeAsync`.

**Comment by Gronsak** [comment]
@PinpointTownes Thanks for the response,
I was looking for just that kind of property so it currently not working that way explains why I couldn't find anything. It would most certainly be the best solution to the problem.

I'll do a monkey patch, or solve it using the event, for now since I really don't want to carpet bomb the scopes. But it would have been nice to see this actually be officially implemented in some capacity, unless there's a really good reason to why you shouldn't set your scopes dynamically.

**Comment by Tratcher** [comment]
The Google provider has something like this and there's a bug somewhere to explore generalizing that feature.

**Comment by Eilon** [comment]
This sounds like a good feature to add and we will consider it in a future version.

**Comment by PinpointTownes** [comment]
@Eilon IMHO, this work item sounds like a good candidate for the "up for grabs" label :smile:

**Comment by Eilon** [comment]
@PinpointTownes if someone wants to offer up a design proposal for this we'll definitely take a look. Sometimes we're a bit hesitant to mark non-trivial bugs as up-for-grabs if we think it's a bigger design item 😄

**Comment by brockallen** [comment]
> This sounds like a good feature to add and we will consider it in a future version.

Does this mean you are accepting new modifications for the security stack (or [not](https://github.com/aspnet/Security/issues/1039#issuecomment-284016681))?

**Comment by HaoK** [comment]
The OAuthHandler still exists in the new stack so any features done to any actual handlers like this will still flow into the new 2.0 stack.

**Comment by Eilon** [comment]
This should now be possible in ASP.NET Core 2.1: https://github.com/aspnet/Security/issues/1575

Tagging @poke because he did all the great work to make this happen.
