### ISSUE TITLE
ASP.NET Web API Authentication Using HMAC

### ISSUE THREAD

**Issue by danroth27** [aspnet/Security#1141]
_From @Xavierh95 on October 10, 2016 12:47_

Hi everyone,

I want to secure an ASP.NET Web API project with HMAC auth.

This REST API project will be used by third-party developers to access my application's data.

I'm trying to adapt [this post](http://www.codeguru.com/csharp/.net/net_asp/learn-to-secure-an-asp.net-web-api-using-hmac.html)  in .NET Core without success...

Some of the class / interface used don't exist anymore (ex: IAuthenticationFilter, HttpAuthenticationContext, HttpAuthenticationContext, IHttpActionResult)

How can I add a sample HmacAuthentication attribute to my API methods in order to protect them with HMACSHA256 ?

Thanks for your answers! 

_Copied from original issue: dotnet/core#283_

**Comment by danroth27** [comment]
_From @Petermarcu on November 4, 2016 6:45_

@danroth27 Whats the best place to ask this question where some ASP.NET folks can help?

**Comment by danroth27** [comment]
I don't think we have a good built-in solution for this today in the framework.

@leastprivilege @brockallen Is this something you can setup with [IdentityServer](http://identityserver.io)?

**Comment by danroth27** [comment]
_From @blowdart on November 4, 2016 15:10_

@danroth27 No - it's something entirely different. It's signing the request, with a preshared key. It's not something we support out of the box, but you should be able to do it with authorization middleware.

**Comment by danroth27** [comment]
_From @blowdart on November 4, 2016 15:17_

@Xavierh95 Do you mean something like https://github.com/blowdart/Idunno.WebApi.SharedKeyAuth, except for core?

**Comment by danroth27** [comment]
_From @Xavierh95 on November 4, 2016 17:41_

@blowdart Yes, or something like : http://www.codeguru.com/csharp/.net/net_asp/learn-to-secure-an-asp.net-web-api-using-hmac.html

**Comment by danroth27** [comment]
_From @blowdart on November 4, 2016 17:55_

I could look at porting my one.

**Comment by danroth27** [comment]
_From @richlander on March 10, 2017 8:7_

Please re-activate if this is still an issue.

**Comment by brockallen** [comment]
We had some HAWK support a while back. Perhaps as a reference it might be useful. https://github.com/IdentityModel/Thinktecture.IdentityModel/tree/master/source/Hawk.

**Comment by Eilon** [comment]
There are no plans to do this in-the-box in ASP.NET Core, so moving this item to Discussions.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
