### ISSUE TITLE
Consider removing of "profile" scope as a default in OpenIdConnectOptions

### ISSUE THREAD

**Issue by BorisWilhelms** [aspnet/Security#1147]
The OIDC Core Specc states the "profile" scope as an optional scope (http://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims). Therefor it should not be added by default to the scope hashset of the OpenIdconnectOptions. 
The specc only states only the "openid" scope as a required scope.

**Comment by leastprivilege** [comment]
Yes. Absolutely agreed.

**Comment by Eilon** [comment]
The Great Auth Redesign of 2017 should make it easier to remove/control the scopes, but we are not planning on changing the default list of scopes because we've seen from customer feedback that it's very commonly used.
