### ISSUE TITLE
UTC in the JwtBearer

### ISSUE THREAD

**Issue by OskarKlintrot** [aspnet/Security#1149]
When validating the JWT with `ValidateLifetime = true` in `TokenValidationParameters` it won't work if the timestamps (iat, exp, nbf) in the JWT is based on UTC (`var now = DateTimeOffset.UtcNow;`) but it will work if the timestamps  is based on the servers time (`var now = DateTimeOffset.Now;`) since both my issuer and consumer runs on the same machine.

This code is working but the validation fails (in the API, this is issued in another application) when I change `.Now` to `.UtcNow` (see above):

```c#
public object GenerateToken(ClaimsPrincipal user)
{
  var now = DateTimeOffset.Now; // Should be UtcNow, see https://tools.ietf.org/html/rfc7519

  // Specifically add the jti (random nonce), iat (issued timestamp), and sub (subject/user) claims.
  // You can add other claims here, if you want:
  var claims = new List<Claim>
  {
    new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
    new Claim(JwtRegisteredClaimNames.Iat, now.ToUnixTimeSeconds().ToString(), ClaimValueTypes.Integer64)
  };

  // Create the JWT
  var jwt = new JwtSecurityToken(
    issuer: _settings.Issuer,
    audience: _settings.Audience,
    claims: claims,
    notBefore: now.DateTime,
    expires: now.DateTime.Add(_settings.Expiration),
    signingCredentials: _settings.SigningCredentials
  );

  var encodedJwt = new JwtSecurityTokenHandler().WriteToken(jwt);

  return new
  {
    accessToken = encodedJwt,
    expiresIn = (int)_settings.Expiration.TotalSeconds
  };
}
```

To validate the JWT in the API I use the JwtBearer:

```c#
private static readonly string secretKey = "mysupersecret_secretkey!123";

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
  var signingKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(secretKey));

  var tokenValidationParameters = new TokenValidationParameters
  {
    ValidateIssuerSigningKey = true,
    IssuerSigningKey = signingKey,

    ValidateIssuer = true,
    ValidIssuer = "ExampleIssuer",

    ValidateAudience = true,
    ValidAudience = "ExampleAudience",

    ValidateLifetime = true,
  };

  app.UseJwtBearerAuthentication(new JwtBearerOptions
  {
    AutomaticAuthenticate = true,
    AutomaticChallenge = true,
    TokenValidationParameters = tokenValidationParameters
  });

  app.UseMvc();
}
```

**Comment by Tratcher** [comment]
JwtSecurityToken and related components are over here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

**Comment by OskarKlintrot** [comment]
Is JwtBearer just using JwtSecurityToken for the validation?

**Comment by Eilon** [comment]
@brentschmaltz can you take a look and see if we need to move this bug to another repo?

**Comment by Eilon** [comment]
Ping @brentschmaltz .

**Comment by brentschmaltz** [comment]
Validation is preformed by JwtSecurityTokenHandler.ValidateToken

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L735

**Comment by Eilon** [comment]
Closing because there doesn't seem to be any further action required here. If there are further issues with this, please open a new issue in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet. Thanks!
