### ISSUE TITLE
Fail authentication from events through BaseControlContext

### ISSUE THREAD

**Issue by kyschouv** [aspnet/Security#1153]
I have a situation where I'm using MessageReceived in JwtBearerMiddleware to unwrap a JWT token (it's compressed and encrypted). Unfortunately, I have no way to fail the request if the decryption fails, I can only skip or handle it. The failure is analogous to the SecurityTokenValidators all failing in the JWT middleware, which ends up calling AuthenticateResult.Fail.

Could BaseControlContext add a failure state, and have that handled appropriately in authentication middlewares? Or is there a better way for me to accomplish this task?

**Comment by Eilon** [comment]
From triage discussion, it seems like @brentschmaltz might have some ideas on how to plug in the decryption/decompression, and then once that's plugged in correctly, the rest should work. That is, once plugged in correctly, a failure in that event would bubble up as a proper failure in the system.

**Comment by Eilon** [comment]
Ping @brentschmaltz

**Comment by brentschmaltz** [comment]
This is going to take a two pronged solution.
1. Add decryption keys to the TokenValidationParameters on the options.
2. Set a derived JwtSecurityTokenHandler with ValidateSignature overridden that will perform the deflate and then return base.ValidateSignature.

**Comment by Eilon** [comment]
Closing because there's no action here. Whatever gets added as part of https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/593 will be available from ASP.NET Core via its options.
