### ISSUE TITLE
Track recent breaking changes in `exceptions.net*.json` files

### ISSUE THREAD

**Issue by dougbu** [aspnet/Security#1160]
This repo contains untracked breaking changes. To find and address them
1. Revert 75a4d00
2. Run `.\build.cmd /t:Pack` in projects 75a4d00 touched or `.\build.cmd /t:Package` in the repo root
3. Update `exceptions.net45.json` and `exceptions.netcore.json` to track the changes
4. If not already announced, suggest filing issues at https://github.com/aspnet/Announcements

**Comment by Eilon** [comment]
@HaoK we should do this *before* your mega-change to see what existing breaking changes we have (and making sure they're all deliberate), and then you'll of course need to run it and update again *after* your mega-change.

**Comment by HaoK** [comment]
9797d4bc5f3e54ffca3487c038044990585e278c
