### ISSUE TITLE
netstandard1.6

### ISSUE THREAD

**Issue by AxelAndersen** [aspnet/Security#1162]
Hi

Will this be ported to be able to run on netstandard1.6 instead of the old netstandard1.3?
I tried it my self, but ran into a lot of problems.

**Comment by davidfowl** [comment]
Why would you want to target a higher netstandard? What APIs are you trying to use? What capabilities are you trying to enable?

**Comment by AxelAndersen** [comment]
Actually I was trying to use the dlls from these projects in a .NETCoreApp 1.1 project and that failed.
I then read that the 2 frameworks could not be used together in that version.

Is there another way of doing it?¨

**Comment by Eilon** [comment]
Anything that runs on netstandard1.3 will run on all platforms that support any higher netstandard.

.NET Cor App 1.1 supports netstandard1.6 just fine.

Can you share your project and the error you're seeing?

**Comment by AxelAndersen** [comment]
Hi again, yes .NET Core App 1.1 does support netstandard1.6, but it does not support netstandard1.3 as this is build with.
I am having a lot of difficulties moving this to netstandard1.6, is that why it has not been done yet?

**Comment by brockallen** [comment]
I suspect his issue is that he wants to build a netstandard1.3 library so he only has to target one thing and be able to run on both .NET Core and .NET Framework 4.6, but he has a dependency on MVC which requires netstandard1.6.

**Comment by davidfowl** [comment]
I'm sorry, I still don't understand.

**Comment by Eilon** [comment]
@AxelAndersen can you show us what your project looks like, and what error(s) you're getting? This should all work, regardless of .NET Standard 1.3, 1.6, etc. All .NET Standard 1.x should run just fine on .NET Core App 1.x.

If it's what @brockallen is saying, then that's a different story - MVC requires .NET Standard 1.6 so if you need that, you have to target .NET Standard 1.6 or higher - there's no getting around that.

**Comment by AxelAndersen** [comment]
Hi all

Thank you for your feed back and interest.

Due to your suggestions that it should work just fine, I cleaned my solution for all dependencies and started all over. And you were right, it does actually build with a netstandard1.3 version.
However, in my solution under Dependencies/Nuget i have 3 referenced dll's that get a yellow triangle, why is that?
I will upload an image showing it:

![image](https://cloud.githubusercontent.com/assets/14222668/24389262/84e0885e-1380-11e7-93d8-d67276969921.png)

**Comment by Eilon** [comment]
@AxelAndersen do you see anything in the "Output" window of VS and select "Package Manager Output"? If there are NuGet restore failures, that's usually where they'd be.

If the errors are already gone, you could try closing VS, run `git clean -xdf` to reset your Git repo (or whatever source control you're using), then open the project again in VS, and that should show the errors again.

**Comment by Eilon** [comment]
Closing because we are unable to repro this.
