### ISSUE TITLE
Consider supporting WeChat OAuth

### ISSUE THREAD

**Issue by kchanlee** [aspnet/Security#1164]
[WeChat](http://www.wechat.com/en/) is a free messaging and calling app owned by Tencent, China. As of September 2016, it has [768 million daily active users](http://www.zdnet.com/article/wechat-daily-active-users-top-768-million/) which is more than twice as Twitter ([313 million/monthly](https://about.twitter.com/company)). Almost all Chinese have it installed in their smart phones. Meanwhile, it is going to be more and more international.

Twitter OAuth has been officially supported by both Katana and Asp.Net Core. Considering the active user number, I think it is reasonable for Asp.Net Core to support WeChat OAuth officially to benefit more developers.

BTW, I am implementing WeChat OAuth login based on Asp.Net Core and I am willing to contribute.

**Comment by Tratcher** [comment]
We recomend adding additional OAuth providers to https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers. 

That said, the base class is often adequate for standard OAuth providers. See https://github.com/aspnet/Security/blob/75a4d006aa7e53c110b3c71c66473adbd45becd6/samples/SocialSample/Startup.cs#L202-L238.

**Comment by kchanlee** [comment]
@Tratcher Thanks for you timely response!
