### ISSUE TITLE
Cookie authentication does not work when host URL includes a path

### ISSUE THREAD

**Issue by mjrousos** [aspnet/Security#1171]
Repro Steps
-------------

1. Create new ASP.NET Core web application from the new project template in VS 2017. Use 'individual accounts' authentication.
2. dotnet ef database update, if needed.
3. Add `.UseUrls("http://localhost:5000/testapp")` in program.cs to set the URL for the host to listen on.
4. Switch to Kestrel host, F5, and navigate to http://localhost:5000/testapp

_Actual behavior_:
The web application loads fine and all assets are retrieved properly (despite the URL in the path). New users can be registered. However, **logging in a user fails**. After logging in, the web app acts as if no user is logged in. The Kestrel log says:

```
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware[7]
      Identity.Application was not authenticated. Failure message: Unprotect ticket failed
```

_Expected behavior_:
Users can properly log in even when the web host listens on a URL including a path.

If "/testapp" is removed from the URL (so that it doesn't include any path but the root), then logging in works again, as expected.

**Comment by Tratcher** [comment]
It should be noted that Kestrel has removed support for application root paths (e.g. `/testapp` in UseUrls). https://github.com/aspnet/Announcements/issues/230

That said, the application root path should not have anything to do with the data protection context. The path is set on the response cookie, but it's not part of the protection. https://github.com/aspnet/Security/blob/305ccf9cc5d2ce777e5fb147013966924c9aca8e/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L151
https://github.com/aspnet/Security/blob/305ccf9cc5d2ce777e5fb147013966924c9aca8e/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L81

We'll need to reproduce this and see what's going on.

**Comment by mjrousos** [comment]
Ah, I didn't realize that application root paths weren't supported in `UseUrls` anymore; thanks for the pointer!

For what it's worth, I just tried `UsePathBase` and everything works as expected when I go that route. So, this is probably lower priority since the recommended scenario is working. Still would be interesting to understand why it didn't work with an application root path in `UseUrls`, though, since that also *seems* like it should work.

**Comment by Tratcher** [comment]
@mjrousos there shouldn't have been any difference between what kestrel was doing and what UsePathBase does. But since the feature is now removed then I'll close this.
