### ISSUE TITLE
Middleware for handling HTTP 401 unauthorized response

### ISSUE THREAD

**Issue by darxis** [aspnet/Security#1174]
1. I have an `AuthenticationHandler<>` that I would like to apply to only a single controller. How do I do that using Attributes? I tried using `[MiddlewareFilter(typeof(MyCustomAuthHandlerPipeline))]` but it does not seem to work when also using an `AuthorizeAttribute`.
2. On the same controler I use an `AuthorizeAttribute` (`[Authorize(Policy = "SomePolicy")]`). When this authorization fails I would like not to return the HTTP 401/403 code, but the 404 one. How do I do that?

Code:
```c#
[Authorize(Policy = "MyPolicy")]
[MiddlewareFilter(typeof(MyAuthenticationPipeline), Order = int.MinValue)]
[Route("api/[controller]")]
public class MyController : Controller
{
    [HttpGet]
    [Route("[action]")]
    public IActionResult Index()
    {
        return new JsonResult("Hello world");
    }
}

public class MyAuthenticationPipeline
{
    public void Configure(IApplicationBuilder app)
    {
        app.UseMiddleware<MyAuthenticationMiddleware>();
    }
}

public class MyAuthenticationMiddleware : AuthenticationMiddleware<MyAuthenticationOptions>
{
    public MyAuthenticationMiddleware(RequestDelegate next,
        IOptions<MyAuthenticationOptions> options,
        ILoggerFactory loggerFactory,
        UrlEncoder encoder)
        : base(next, options, loggerFactory, encoder)
    {
    }

    protected override AuthenticationHandler<MyAuthenticationOptions> CreateHandler()
    {
        return new MyAuthenticationHandler();
    }
}

public class MyAuthenticationHandler : AuthenticationHandler<MyAuthenticationOptions>
{
    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
            // Custom logic
    }

    protected override Task<bool> HandleUnauthorizedAsync(ChallengeContext context)
    {
        return Task.FromResult(true);
    }

    protected override Task<bool> HandleForbiddenAsync(ChallengeContext context)
    {
        return Task.FromResult(true);
    }
}
```

**Comment by Tratcher** [comment]
You're looking for `[Authorize(ActiveAuthenticationSchemes = "MyAuthScheme")]`

Then you can override AuthenticationMiddleware.HandleUnauthorizedAsync to set the status code you want.

**Comment by darxis** [comment]
@Tratcher I assume that I also need to remove `[MiddlewareFilter(typeof(MyAuthenticationPipeline), Order = int.MinValue)]`.

How do I register `MyAuthenticationHandler` as an AuthenticationHandler with SchemeName = "MyAuthScheme"?

Thanks!

**Comment by Tratcher** [comment]
MiddlewareFilter may work, but you can also move it to Startup.Configure.

AuthenticationOptions.AuthenticationScheme
https://github.com/aspnet/Security/blob/2d7cd6038fea34b84084685648ac9d0c97be610b/src/Microsoft.AspNetCore.Authentication/AuthenticationOptions.cs#L21

**Comment by darxis** [comment]
@Tratcher But I would like to use this AuthenticationHandler only for this specific controller. 

I forgot to said that my `MyAuthenticationOptions` looks like:
```c#
public class MyAuthenticationOptions : AuthenticationOptions
{
    public MyAuthenticationOptions()
    {
        AuthenticationScheme = "MyAuthScheme";
        AutomaticAuthenticate = true;
    }
}
```

Even with the `MiddlewareFilter` applied to this specific controller, I got the "No authentication handler is configured to authenticate for the scheme" exception.

**Comment by darxis** [comment]
Ok, I got this:

- `app.UseMiddleware<MyAuthenticationMiddleware>()`
- `AutomaticAuthenticate = false` in the MyAuthenticationOptions
- `[Authorize(ActiveAuthenticationSchemes = "MyAuthScheme")]`

The configuration above will trigger the MyAuthHandler only for controller actions where `[Authorize(ActiveAuthenticationSchemes = "MyAuthScheme")]` is used.

Thanks
