### ISSUE TITLE
Allow for a separate "RedirectAuthority" URL in OpenIdConnectOptions

### ISSUE THREAD

**Issue by JoshYaxley** [aspnet/Security#1175]
I think it would be useful to be able to have separate authorities defined for internal HTTP communication and browser redirects.

## My scenario

I'm setting up a dockerised Identity Server with example APIs and clients, for me to get to grips with the technology and provide a base for future projects.

For example, my MVC client middleware can be set up like this:

``` csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
{
    AuthenticationScheme = "oidc",
    SignInScheme = "Cookies",

    Authority = "http://identityserver:5000",
    RequireHttpsMetadata = false,

    ClientId = "example-mvc-client",
    SaveTokens = true
});
```

Because both my client and identity server are within the docker network, they can communicate using their aliases. Setting the authority like this allows my client to communicate to my identity server. However, the authority is also used for browser redirects (when a user accesses a secured part of the client, they are redirected to the identity server to sign in). Because the user has no concept of the "identityserver" container, this redirection obviously fails.

Alternatively, I can set:

``` csharp
Authority = "http://localhost:5000"
```

Where `identityserver:5000` is port-forwarded to `localhost:5000` in my `docker-compose.yml`.

This allows the redirects to work, but the internal HTTP communication will now fail because my client container will try to talk to its own localhost, rather than the identityserver container.

There is a workaround for this by setting the `identityserver:localhost` in the docker-compose links or network alias sections. However, this doesn't strike me as a good solution for production (and I can't seem to properly get it working, though I think it should work in theory).

## Suggestion

I think, ideally, you would be able to set-up your middleware like this:

``` csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
{
    AuthenticationScheme = "oidc",
    SignInScheme = "Cookies",

    Authority = "http://identityserver:5000",
    RedirectAuthority = "http://localhost:5000",
    RequireHttpsMetadata = false,

    ClientId = "example-mvc-client",
    SaveTokens = true
});
```

The `Authority` property would be used for internal HTTP communication (container to container), and the `RedirectAuthority` property would be used for redirecting the user to the identity server's login UI.

The `RedirectAuthority` property could be optional, and, if not set, the `Authority` property would be used for redirects, thus not breaking anyone's existing code and not adding extra configuration for people that don't need it.

-----------------------------------------------

This would be useful in any situation where the user's machine and the client cannot both refer to the identity server via the same URL. Is there a need for this? Is it low priority? Have I misunderstood the problem?

**Comment by Tratcher** [comment]
I think the field you're looking for is the MetadataAddress. This defaults to the authority, but you can replace it to directly point at your identityserver.

**Comment by JoshYaxley** [comment]
I also thought that MetadataAddress might be my solution, so I played with it a bit.

If I use the following configuration in my middleware:

``` csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
{
    AuthenticationScheme = "oidc",
    SignInScheme = "Cookies",

    Authority = "http://localhost:5000",
    MetadataAddress = "http://identity/.well-known/openid-configuration",
    RequireHttpsMetadata = false,

    ClientId = "example-mvc-client",
    SaveTokens = true
});
```

And then navigate to a secured page, the internal HTTP call to grab the metadata seems to work, but the browser is then redirected to the following URL:

> http://identity/connect/authorize?client_id=example-mvc-client&redirect_uri=http%3A%2F%2Flocalhost%3A5002%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=636275274535445870.MTcyYzIwMzgtNzdkOC00ZWVjLTg1MDgtYTc2NzUwZTMwMGQ4NjAwNzlkNDQtYzNkMy00OGNlLTk3NGYtZTdiOWFhMzQzN2I1&state=CfDJ8Hl6cMccEvRPpfKNaqRh9-MRevkAnun7-oYT9DAJpAA2cICFkeJh4zl2b_YRA7DgFSCLef-Vs2NbzLyNrGhWf4Y8R82Nc4_AiZiX-swP3iKOrUtEXIQtmzeKngdrSCpA8vAExl-EjVs4yPXXVhdqNYhftfJGzIipRvVtgy48UKbdXI2LrZYy6Uwur5aD_SO9jnElOQpyyLGY3zVqi9cVabkbkpjUeH7tgk_DUUr4lQdc8caitBJ9_rCPKySfSLvP_v2bqADsTM8h20T-79jprdtAwwz4huvf0b-bT9OxDsDvLFhGO9BP3AVOdjlljmMKtL4D0wgq3czOHe4FcBucYAk

I can manually get past this by replacing "identity" to "localhost:5000" in the URL bar, but this then yields the following (somewhat expected) error:

> SecurityTokenInvalidIssuerException: IDX10205: Issuer validation failed. Issuer: 'http://localhost:5000'. Did not match: validationParameters.ValidIssuer: 'http://identity' or validationParameters.ValidIssuers: 'null'.

I also tried setting `Authority = "http://identity"` in the vain hope that this would at least fix the issuer mismatch problem, but the same errors occurred.

So, this way, even if I manage to get the redirects correct, the issuer in the token is not going to match.

Is there any hope for me? Or am I barking up the wrong tree? I'm very hesitant to start introducing complicated proxies or something to get around a problem that I'm sure other people must be having.

**Comment by Tratcher** [comment]
Check what the metadata doc actually contains, that controls the initial redirect uris. You may have to fix that on the identityserver side.

**Comment by JoshYaxley** [comment]
Performing a curl command to `http://identity/.well-known/openid-configuration` inside of the client docker container results in the following JSON:

``` json
{
   "issuer":"http://identity",
   "jwks_uri":"http://identity/.well-known/openid-configuration/jwks",
   "authorization_endpoint":"http://identity/connect/authorize",
   "token_endpoint":"http://identity/connect/token",
   "userinfo_endpoint":"http://identity/connect/userinfo",
   "end_session_endpoint":"http://identity/connect/endsession",
   "check_session_iframe":"http://identity/connect/checksession",
   "revocation_endpoint":"http://identity/connect/revocation",
   "introspection_endpoint":"http://identity/connect/introspect",
   "frontchannel_logout_supported":true,
   "frontchannel_logout_session_supported":true,
   "scopes_supported":[
      "openid",
      "profile",
      "example-api",
      "offline_access"
   ],
   "claims_supported":[
      "sub",
      "name",
      "family_name",
      "given_name",
      "middle_name",
      "nickname",
      "preferred_username",
      "profile",
      "picture",
      "website",
      "gender",
      "birthdate",
      "zoneinfo",
      "locale",
      "updated_at"
   ],
   "grant_types_supported":[
      "authorization_code",
      "client_credentials",
      "refresh_token",
      "implicit",
      "password"
   ],
   "response_types_supported":[
      "code",
      "token",
      "id_token",
      "id_token token",
      "code id_token",
      "code token",
      "code id_token token"
   ],
   "response_modes_supported":[
      "form_post",
      "query",
      "fragment"
   ],
   "token_endpoint_auth_methods_supported":[
      "client_secret_basic",
      "client_secret_post"
   ],
   "subject_types_supported":[
      "public"
   ],
   "id_token_signing_alg_values_supported":[
      "RS256"
   ],
   "code_challenge_methods_supported":[
      "plain",
      "S256"
   ]
}
```

In this case, I suppose I want the URLs to contain "localhost:5000" rather than "identity".

However, in other cases (for example, a console application client that lives inside of the docker network and has no concept of what "localhost:5000" would really mean), I want it to stay as "identity".

It might also be worth mentioning that if I navigate to `http://localhost:5000/.well-known/openid-configuration` in my browser (outside of the docker network), then I get the same JSON but with "localhost:5000" replacing "identity" in the URLs.

**Comment by Tratcher** [comment]
So your identity server is dynamically generating the metadata based on your request url. Too smart for its own good...
You may just have to create your own metadata, or intercept and update theirs. The Configuration or ConfigurationManager Option will help with this.
https://github.com/aspnet/Security/blob/2d7cd6038fea34b84084685648ac9d0c97be610b/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L105-L111
See https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/master/src/Microsoft.IdentityModel.Protocols/Configuration

**Comment by brockallen** [comment]
> Too smart for its own good...

Isn't this the same situation as using a reverse proxy? If this is an issue, put middleware in front to correct the request host to suit your custom deployment scenario.

**Comment by JoshYaxley** [comment]
> put middleware in front to correct the host value

Would this still not result in the issuer mismatch?

I will try it before trying a custom Configuration object.

**Comment by brockallen** [comment]
> Would this still not result in the issuer mismatch?

That I do not know -- I didn't quite follow all of the context of how your container deployment mechanics and DNS aliases work.

**Comment by JoshYaxley** [comment]
I'm not entirely sure how I can put middleware in front to correct the host value of a redirect: if the host value of a redirect is incorrect then it won't come anywhere near my web application, and hence is completely out of my control at that point.

I've hacked together an experiment using a custom `OpenIdConnectConfiguration` object, which looks like this:

``` csharp
var openIdConnectConfiguration = OpenIdConnectConfiguration.Create("{'issuer':'http://localhost:5000','jwks_uri':'http://localhost:5000/.well-known/openid-configuration/jwks','authorization_endpoint':'http://localhost:5000/connect/authorize','token_endpoint':'http://localhost:5000/connect/token','userinfo_endpoint':'http://localhost:5000/connect/userinfo','end_session_endpoint':'http://localhost:5000/connect/endsession','check_session_iframe':'http://localhost:5000/connect/checksession','revocation_endpoint':'http://localhost:5000/connect/revocation','introspection_endpoint':'http://localhost:5000/connect/introspect','frontchannel_logout_supported':true,'frontchannel_logout_session_supported':true,'scopes_supported':['openid','profile','example-api','offline_access'],'claims_supported':['sub','name','family_name','given_name','middle_name','nickname','preferred_username','profile','picture','website','gender','birthdate','zoneinfo','locale','updated_at'],'grant_types_supported':['authorization_code','client_credentials','refresh_token','implicit','password'],'response_types_supported':['code','token','id_token','id_token token','code id_token','code token','code id_token token'],'response_modes_supported':['form_post','query','fragment'],'token_endpoint_auth_methods_supported':['client_secret_basic','client_secret_post'],'subject_types_supported':['public'],'id_token_signing_alg_values_supported':['RS256'],'code_challenge_methods_supported':['plain','S256']}");

app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
{
    AuthenticationScheme = "oidc",
    SignInScheme = "Cookies",

    Authority = "http://localhost:5000",
    Configuration = openIdConnectConfiguration,

    ClientId = "example-mvc-client",
    SaveTokens = true
});
```

As you can see, I just copied and pasted the results of manually visiting the metadata endpoint from `localhost:5000`. This is obviously not an ideal solution, but, for testing, simulates the client receiving the desired metadata.

This way, everything actually works perfectly fine until the redirect to `localhost:5002/signin-oidc`, at which point I get the following error:

> SecurityTokenInvalidSignatureException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.

in

> System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(string token, TokenValidationParameters validationParameters)

For reference, the `id_token` of the request is:

> eyJhbGciOiJSUzI1NiIsImtpZCI6IjJiNzQ3YWY4MWFiYmRjMDEyNDdhNGM2OGYxZTcwODJlIiwidHlwIjoiSldUIn0.eyJuYmYiOjE0OTE5MzgyMzksImV4cCI6MTQ5MTkzODUzOSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiZXhhbXBsZS1tdmMtY2xpZW50Iiwibm9uY2UiOiI2MzYyNzUzNTAxMDk3ODk3NDAuTlRObFpEVTVOVFV0WVdObFl5MDBZakF4TFRnM1pqY3RPV1JrTldJek0yTXlOR1EzT0dOa09UbGpZMlF0WmpGaE55MDBOVFV4TFRobE9URXRNelJpWlRjeU9UWm1OREpoIiwiaWF0IjoxNDkxOTM4MjM4LCJzaWQiOiIzMDAzMzdhMTA2ZGVkMTJlMjk5OTAxYmE4NDQ3OTZmNiIsInN1YiI6IjE1YTJiMjAyLTY4YjctNGFhOC04YTdlLTNjMDMxOWQ1ZTk0NCIsImF1dGhfdGltZSI6MTQ5MTkzODIzOCwiaWRwIjoibG9jYWwiLCJuYW1lIjoiYXNkN0Bhc2QuY29tIiwiYW1yIjpbInB3ZCJdfQ.IicW6E8ioFHQlHVcQIchf2pklqIhFrnTnPMcNEV50i2GEixIjDSYvkc_yxhx0mdhI38tRNsFQRKnAcBq1YHKh5bvbhIidTZFGSoyyzV9aUJNu90XIBrG_lWVuaTHduZQcDAUHqK-gK0hfBtKnLk4P959zXodz_LJ9Ow5WVDiC31llyQxe76TZmcme52w1yhxr-wkezo9hxPfJ5elgv9GUB4Y-BLepu9M1KdZdH51E0qv7-Mc3LICu1EYS8sccy5H7SFf9IJQnj7w3tVZWjpgG35PSlt5ipTpVDuuoBoqortT9Rl9fD4n_5rYI2LWxCWPXGtI5GJA5GeRn05yYdphsA

Pasting that into [jwt.io](jwt.io) indicates it has an invalid signature. I've tried this with and without a client secret, and I get the same error.

In terms of my design, I want a .Net Core MVC client application to be able to single sign on with IdentityServer (using Asp.Net Identity). I want the client application and identity server to be inside of a docker network. I've done no further alias configuration than what docker-compose does for you. My problem started because my client has to request metadata from identity server via "http://identity", but this returns URLs containing "http://identity", when they need to be "http://localhost:5000" for the browser to actually be able to resolve them. I'm not entirely sure how having multiple token servers would solve this (I must admit I am beginning to feel quite out of my depth).

![identity](https://cloud.githubusercontent.com/assets/16490056/24926892/06ff8f22-1ef5-11e7-9593-9f3d994fb2f1.png)

Any further help would be greatly appreciated!

**Comment by brockallen** [comment]
> I'm not entirely sure how I can put middleware in front to correct the host value of a redirect: if the host value of a redirect is incorrect then it won't come anywhere near my web application, and hence is completely out of my control at that point.

Perhaps I'm not understanding the issue. I thought the problem was that in your container environment you want to use a non-public DNS entry to refer to IdentityServer? This is the same situation if you have a proxy server in front of web server that that web server needs to render absolute URLs back to itself. If this is the problem, then the general approach for this is to put middleware in front of the app to change the incoming host header of each request to be the value that it needs to be (e.g. the public value). That way when the server needs to generate a URL back to itself it looks at the host value in the request. This is what the ["Basic" middleware](https://github.com/aspnet/BasicMiddleware) is doing -- it accepts a environment variable from the IIS host and changes the host header on each incoming request.

As I said, I have a feeling I'm totally misunderstanding the situation.

**Comment by JoshYaxley** [comment]
Thanks, it hadn't occurred to me to change the headers of the incoming request.

I added the following middleware to my identity server:

``` csharp
app.Use((context, next) =>
{
    context.Request.Host = new HostString("localhost", 5000);

    return next();
});
```

And used the following configuration in my client middleware:

``` csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
{
    AuthenticationScheme = "oidc",
    SignInScheme = "Cookies",

    Authority = "http://localhost:5000",
    MetadataAddress = "http://identity/.well-known/openid-configuration",
    RequireHttpsMetadata = false,

    ClientId = "example-mvc-client",
    SaveTokens = true
});
```

The call to grab the metadata is internal, so needs to reference "identity".
The host header on this request is changed to "localhost:5000", so the desired metadata is returned.
The next thing that happens is an internal http call is made to the "jwks_uri", which now references "localhost:5000", which won't resolve because any internal http call needs to reference "identity"!

It seems that actually I want some kind of mix of url hosts, something like:

``` json
{
   "issuer":"http://localhost:5000",
   "jwks_uri":"http://identity/.well-known/openid-configuration/jwks",
   "authorization_endpoint":"http://localhost:5000/connect/authorize",
   
    ...
}
```

Any URL queried by an internal http call needs to reference "identity".
Any URL used for a browser redirect needs to reference "localhost:5000".

If any are used for both, then I don't know what to do.

I feel like I'm starting to misuse this tbh, but I thought my use case wouldn't be very complicated (mvc client doing SSO with an identity server inside of a docker network)!

**Comment by brockallen** [comment]
Yea, sounds like your original workaround with docker-compose feels better.

**Comment by JoshYaxley** [comment]
In which case, I'm still stuck in the same place I was on [this comment](https://github.com/aspnet/Security/issues/1175#issuecomment-293376825).

i.e.

> SecurityTokenInvalidSignatureException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.

I'm using the TemporarySigningCredential, but I don't think it's because of that. I have noted the comment made in the IdentityServer docs [here](http://docs.identityserver.io/en/release/quickstarts/3_interactive_login.html):

> During development you might sometimes see an exception stating that the token could not be validated. This is due to the fact that the signing key material is created on the fly and kept in-memory only. This exception happens when the client and IdentityServer get out of sync. Simply repeat the operation at the client, the next time the metadata has caught up, and everything should work normal again.

The "kid" from the JWT token matches the "kid" from the metadata endpoint. Quite confused, though I suppose this is a separate problem (unless it's a problem introduced by me using a custom configuration object).

**Comment by herecydev** [comment]
I'm also completely stuck on this situation. Browser redirection is fine for localhost, but within docker it can't route localhost (as this refers to the container).

@JoshYaxley did you get anywhere with this?
@brockallen does the proposed solution seem reasonable?

**Comment by brockallen** [comment]
Isn't this a DNS issue? It's logically a separate machine, so the fact that they're hijacking localhost is somewhat deceptive. I'd ask the docker folks (which is certainly not me).

**Comment by JoshYaxley** [comment]
I managed to hack a solution for the problem by using a custom `Configuration` object where I hard-coded the correct URLs into it (see [this](https://github.com/aspnet/Security/issues/1175#issuecomment-293376825) comment).

Unfortunately, I then ran into a security validation error [here](https://github.com/aspnet/Security/issues/1175#issuecomment-293620896), and I don't know if it is because of the changes I made to how the metadata is read or to do with something else.

I couldn't get past this error and have, unfortunately, stopped working on my docker identity server for now. However, it does strike me that there may be more success if the identity server is hosted outside of the docker network, so that it can always be referenced by the same URL:

![untitled diagram](https://cloud.githubusercontent.com/assets/16490056/25269187/82a9ce64-2673-11e7-8863-9c755685f86d.png)

This is what I will try next, if I get the time (and the ability to host an identity server somewhere other than localhost).

**Comment by herecydev** [comment]
Yep that's exactly the approach I've taken. It kind of makes more sense from a SSO perspective.

**Comment by JoshYaxley** [comment]
Does it work? Was there anything noteworthy that I should keep in mind when attempting it myself?

**Comment by herecydev** [comment]
Haven't tested fully yet, but yer I see no reason. The `identitydomain.com` is accessible because it lookup this domain from any dns server (like 8.8.8.8).

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by jonaskello** [comment]
FWIW I have run into the same problem.
I have two servers:
1. IdentityServer
2. Mvc Application Server
The servers have a private address and a public address. 
The servers are allowed to communicate internally only using their internal addresses.
The servers are not allowed to communicate using their public addresses (for some security reason I don't understand).
The client can only reach the servers on the public address.
So what happens is:
Server (2) gets the meta data document from server (1) using the internal address. 
The meta data document now has all URLs as internal.
Then server (2) fetches the public key from server (1) using the jwks adress the meta data, this address is internal so it works.
Then server (2) redirects the client to the autohorization endpoint from the meta data, this address is internal so it fails (because the client can only reach the server on it's public address).

**Comment by BizarroDavid** [comment]
I was wrestling with this myself and came upon a solution. My setup was

1. IdentityServer running as, say, netcoreauth:8001
2. WebAPI  running as, say, netcoreapi:5001

using docker-compose to perform local development. The solution was for IdentityServer to explicitly specify the issuing authoritiy as, in my example, `netcoreauth`. Otherwise it would default to whatever location the browser/postman was calling (i.e. `localhost`.) and cause the error.

The following configuration snippet on my IdentityServer did the trick:

```
public void ConfigureServices(IServiceCollection services)
{
   ...
   services.AddIdentityServer(options =>
   {                             
      options.IssuerUri = "netcoreauth";
   })
  ...
}
```

Obviously for development purposes only...

**Comment by OndeVai** [comment]
@BizarroDavid This will work for securing the API, but not for the hybrid flow for and MVC client described above ---this is because the MVC client needs to triple hop:
1) Make a server-side request to the Discovery endpoint
2) Make a server-side request to the JWKS endpoint
3) Make a client-side request to the Authorization endpoint
All need 3 need to happen using the same domain for auth to be successful.

I'm glad you guys have run into this issue as well :) I'm also just going to host my IDP publically and outside of Docker. Any other solution and it feels like I'm compromising the source code.
