### ISSUE TITLE
OnAuthenticationFailed should be called when the OIDC authorization request returns an error

### ISSUE THREAD

**Issue by danroth27** [aspnet/Security#1178]
When I make an OIDC authorization request and the response is an error (ex. a post back with an error property) I expect the OnAuthenticationFailed event to be fired so that I can see the protocol message and potentially handle the event. Currently I have to handle this case using the OnRemoteFailure event, which only gives you the failure exception, and not the actual protocol message details.

I ran into this trying to port some Azure AD B2C sample code from Katana to ASP.NET Core. When you try to reset your password with Azure AD B2C you get back an error response with a particular error code in the error description that you need to handle. It's a bit ugly to do that with the OnRemoteFailure event.

**Comment by Eilon** [comment]
@Tratcher let's take a look at this for 2.0.0.

**Comment by brockallen** [comment]
IIRC there's another similar issue already open related to this // @Tratcher

**Comment by Tratcher** [comment]
@brockallen https://github.com/aspnet/Security/issues/884 ?

**Comment by brockallen** [comment]
Actually, this is the one I was thinking of: https://github.com/aspnet/Security/issues/1188

**Comment by Tratcher** [comment]
Offline discussion: how can we flow information into OnRemoteFailure in a more structured way? #1188 asks for the auth properties. @danroth27 is asking for the structured failure response. Right now the failures are rendered as an exception message:
https://github.com/aspnet/Security/blob/bd19ba9533cfd3ffd81e4ef2c874109e8b3dbccd/src/Microsoft.AspNetCore.Authentication.OAuth/OAuthHandler.cs#L51
https://github.com/aspnet/Security/blob/bd19ba9533cfd3ffd81e4ef2c874109e8b3dbccd/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L1211

**Comment by brockallen** [comment]
There are several places where just throwing is not really helpful. One big one is in the JwtSecurityTokehNalder itself -- what a bad design. I don't know/recall if the OIDC MW suppresses that exception, but it'd be nice for it to.

So, then, how about an "ErrorPageUrl", akin to how the cookie MW has login and access denied path properties to redirect the user to? As for capturing the error info, another all purpose error event seems like an idea.... but yikes, that's a lot of events.

**Comment by Tratcher** [comment]
@brockallen Yes, OIDC and JWT middleware capture the JwtSecurityTokenHandler exceptions and raise them to the events. What happens from there still needs work as you suggest. The error page url is something I've considered, but it's not clear that we can flow any useful details there, nor is the page even likely to exist unless we add it to templates.

**Comment by Eilon** [comment]
Closing because this hasn't come up a whole lot recently. There are some ways to handle these types of failures, though they're not ideal.
