### ISSUE TITLE
Auth 2.0 Cleanup: Revisit cleanup events/context

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#1181]
Sharing context for core IAuthenticationHandler and the events might be a bit awkward, also see if there's any improvements that can be made for the events as a whole

**Comment by PinpointTownes** [comment]
@HaoK now that the authentication scheme is not longer stored in the options, retrieving it from the events is next to impossible. What do you think of introducing a `Scheme` property in `BaseContext`?

```csharp
public class BaseContext
{
    protected BaseContext(HttpContext context, string scheme);

    public string Scheme { get; }
}
```

If `BaseContext` was moved to this repo, we could even expose it as a strongly typed property:

```csharp
public class BaseContext
{
    protected BaseContext(HttpContext context, AuthenticationScheme scheme);

    public AuthenticationScheme Scheme { get; }
}
```

**Comment by PinpointTownes** [comment]
@HaoK another question: do you remember why you've decided to rename `BaseControlContext.SkipToNextMiddleware()` to `Skip()`? The new name is not as clear as the old one, and doesn't really reflect what happens in practice.

**Comment by HaoK** [comment]
For events, we have: https://github.com/aspnet/Security/issues/1181 to revisit exactly that question.

The whole Skip/Handled thing is a bit weird, and what makes sense in some uses (SkipToNextMiddleware) makes sense when its being run in the HandleRequest of a callback for an auth request, but doesn't make sense anywhere else.  We can use the same events issue to track revisiting that as well.

**Comment by PinpointTownes** [comment]
> For events, we have: #1181 to revisit exactly that question.

So this is the right place? :trollface: 

> The whole Skip/Handled thing is a bit weird.

Weird... but insanely powerful :sweat_smile: 

> What makes sense in some uses (SkipToNextMiddleware) makes sense when its being run in the HandleRequest of a callback for an auth request, but doesn't make sense anywhere else.

Sure, but doesn't the `BaseControlContext` name imply that the event should be used only where we have flow control (i.e from `HandleRequestAsync`) and where `Skip` really means "skip the default logic and invoke the rest of the pipeline"?

**Comment by HaoK** [comment]
Possibly, I think we were using it in a variety events, not just ones that are invoked through the request processing pipeline.

**Comment by PinpointTownes** [comment]
@Eilon I see you moved this item to preview3. If it can help make it happen sooner, I'd love to work on it and come up with a formal API change :sweat_smile:

**Comment by Eilon** [comment]
@PinpointTownes we'd certainly be open to that. If you can share a concrete proposal then we can start the discussion! I don't recall the exact background of this issue, so I'm not entirely in the loop on what the requirements/proposals are here.

**Comment by HaoK** [comment]
Yeah feel free to submit a PR @PinpointTownes, I'm just slammed right now

**Comment by PinpointTownes** [comment]
@HaoK will do, thanks!

Quick question: do you recall why the context classes derived from `BaseAuthenticationContext` class (i.e `SignIn/SignOut/Challenge/ForbidContext`) need to expose both the `HttpContext` and the authentication scheme?

It seems a bit weird, because both the context and the scheme are already injected into the handler via `Task InitializeAsync(AuthenticationScheme scheme, HttpContext context);`.

I may be wrong, but the context classes living in aspnet/HttpAbstractions don't seem to be really useful. We could probably get rid of them and simplify the signatures:

```csharp
Task InitializeAsync(AuthenticationScheme scheme, HttpContext context);
Task<AuthenticateResult> AuthenticateAsync();
Task ChallengeAsync(ChallengeContext context);
Task SignInAsync(SignInContext context);
Task SignOutAsync(SignOutContext context);
```

->

```csharp
Task InitializeAsync(AuthenticationScheme scheme, HttpContext context);
Task<AuthenticateResult> AuthenticateAsync();
Task ChallengeAsync(AuthenticationProperties properties);
Task SignInAsync(ClaimsPrincipal principal, AuthenticationProperties properties);
Task SignOutAsync(AuthenticationProperties properties);
```

**Comment by Tratcher** [comment]
They were on there because the base class is shared with the events (which it shouldn't be).

**Comment by PinpointTownes** [comment]
So it's really just a side-effect of sharing the same base class when you shouldn't be, not an intentional decision to enable some sort of edge scenarios?

I this case, I guess we can remove all the context classes from aspnet/HttpAbstractions, right?

**Comment by HaoK** [comment]
Yeah I was feeling that way as well, the context classes were needed when we were doing the accept dance, but they have basically no value now, I can do that as part of my change to removing ChallengeBehavior

**Comment by PinpointTownes** [comment]
> I can do that as part of my change to removing ChallengeBehavior

FYI, I already revamped the `IAuthenticationHandler` methods signatures locally, but feel free to go ahead :smile:

**Comment by HaoK** [comment]
You want to rebase and push your changes into the haok/forbid branch in https://github.com/aspnet/HttpAbstractions/pull/842

**Comment by HaoK** [comment]
I haven't updated any of the downstream repos for that change yet, so I might as well update them with this change at the same time

**Comment by HaoK** [comment]
ff9f145a8e89c9756ea12ff10c6d47f2f7eb345f

**Comment by PinpointTownes** [comment]
nit: I'm all for squashing PRs, but not giving public credits to folks who work on stuff you end up reusing in your own PRs and not even saying "thanks for your participation" is... meh.

**Comment by HaoK** [comment]
Yeah sorry, not sure how best to keep changes sane in a mega change like this, I did name the PR after you, I can give you credit in the announcement for the event changes section?

**Comment by brockallen** [comment]
Not sure where else to add this, and I didn't want to open a new issue. Here's the question: 

Now that this has all been redone -- do you think it's better/cleaner than in 1.x? Have the problems been solved (while not introducing a lot of new ones)?

**Comment by HaoK** [comment]
Yeah, most of the problematic behaviors we were aware of have been eliminated (multiple automatic challenge, chaining) and regressions like those in: https://github.com/aspnet/Announcements/issues/210 should be much less likely going forward.
