### ISSUE TITLE
Add ASP.NET Core 1 and 2 cookie auth interop tests

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1182]
Cookie auth between ASP.NET Core 1 and 2 should inter-operable. Add some functional tests to verify. If at any point they diverge then we should provide an interop package like we did for Katana.

Note this almost regressed in https://github.com/aspnet/Security/pull/1170

**Comment by muratg** [comment]
@mikaelm12 will verify this manually for Preview2 and in 2.0.0 we'll look into automating this. (maybe?)

https://github.com/aspnet/Security/issues/1182

**Comment by mikaelm12** [comment]
Verified this behavior. Looks good to me.  
In the future the person verifying should remember to make sure that the application discriminators in the two apps are the same or else the cookies across the apps won't be the same.
You do this in `DataProtectionOptions `like this
```csharp
services.AddDataProtection(options =>
            {
                options.ApplicationDiscriminator = "test";
            });`
```

**Comment by Eilon** [comment]
Been quite a while and we haven't done this, so closing.
