### ISSUE TITLE
External Provider Authentication

### ISSUE THREAD

**Issue by dkrooke** [aspnet/Security#1183]
Hi, I appologise if this is the wrong place to post this question.

I have created a project in VS 2017 and setup external authentication for Facebook, Google & Microsoft.  When testing this feature from within VS using IIS Express it works as expected.  However, I am getting issues when I publish my project to a test environment which is hosted by IIS.

e.g. When I click on my Facebook login link, I am taken to the correct login page.  When I then log in and then passed back to my web site I get the following error:

WinHttpException: A connection with the server could not be established
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

HttpRequestException: An error occurred while sending the request.
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

AggregateException: Unhandled remote failure. (An error occurred while sending the request.)
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRemoteCallbackAsync>d__6.MoveNext()

What have I missed when publishing to IIS?

Many thanks.

**Comment by Tratcher** [comment]
That doesn't look like a publish error. Your server does not appear to have outgoing internet access to exchange the oauth code for an auth token. You can use Microsoft Message Analyzer or similar to examine the server's incoming and outgoing traffic.

Note IIS runs as a different user, so if you require proxy settings it can't get those from your profile.

**Comment by Eilon** [comment]
This seems like the likely case:

> Your server does not appear to have outgoing internet access to exchange the oauth code for an auth token. 

There might be some proxy configuration or firewall setup that is preventing the web server from contacting Facebook's endpoints.
