### ISSUE TITLE
Revisit SchemeBuilder/AddScheme

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#1186]
We probably need some more sugar around adding schemes today, namely:

`authOptions.AddScheme<handlerType>(schemeName, displayName)`

which today looks like:

```
authOptions.AddScheme(schemeName, o => {
   o.DisplayName = displayName;
   o.HandlerType = typeof<HandlerType>;
});
```

In fact, now that we don't have settings in the scheme anymore, we can probably just remove the scheme builder and only have this api.

Thoughts @Tratcher ?

**Comment by Tratcher** [comment]
The current one is more future proof, but adding the sugar on top wouldn't hurt.

**Comment by HaoK** [comment]
Yeah I guess knowing how auth usually goes, the ability to add stuff later will probably be nice :)

**Comment by HaoK** [comment]
df5c6730f772775bfc9c14fbff050a1a56d9fef6
