### ISSUE TITLE
More granular schemes for hosting.

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#1189]
Currently we are just adding one "Windows" auth handler for IISIntegration/HttpSysServer, this is to see if we can support more granular schemes.

**Comment by Tratcher** [comment]
With https://github.com/aspnet/AspNetCoreModule/issues/82 IIS will tell us which kind of auth is enabled. Then we can figure out how to register more granular schemes. This would be useful if you have stricter security requirements for some endpoints (e.g. Basic vs Negotiate).

For HttpSys we could register one scheme per auth type, but then you have to specify what the default is in AuthOptions.Default....

**Comment by Eilon** [comment]
No current plans to do this. Will revisit based on feedback.
