### ISSUE TITLE
Consolidate identities in AuthenticationTicket

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#119]
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Security/AuthenticationTicket.cs

https://github.com/aspnet/Security/commit/49e66f03110b486f8dd9959dd2cee802d676c28f added a ClaimsPrincipal in addition to the ClaimsIdentity. These need to be reconciled because most code paths do not check for both.

**Comment by brentschmaltz** [comment]
The underlying layer that receive tokens produces ClaimsPrincipal. Since a user can plug in any ISecurityTokenValidator they choose, we should using what they return.

**Comment by blowdart** [comment]
Which underlying layer are you talking about here? 

Facebook auth produces an identity. Google auth produces an identity. Cookie auth produces an identity. 

ISecurityTokenValidator is only used by a limited number of scenarios around JWT and OIC.

**Comment by HaoK** [comment]
Will address as part of https://github.com/aspnet/Security/issues/154
