### ISSUE TITLE
Offline access window not displaying

### ISSUE THREAD

**Issue by anitchanana** [aspnet/Security#1192]
I am using asp.net core and i have integrated external authentication with google oauth.
When i am trying to login with google,it directly logs me in once i provide the crendentials.

Earlier it was asking me for the permission with Deny/Allow button. I had the option to do either of the two and i was working on the process of handling the case when a user deny permissions to app.

Have there been any changes to this process ?

**Comment by Eilon** [comment]
In general the provider (such as Google), will only ask allow/deny the first time, unless either the prompt is *forced* (which it isn't by default), or the list of scopes has changed.

We're not aware of any behavior change in ASP.NET Core that would cause this. Perhaps something in Google's auth flow changed?

**Comment by Eilon** [comment]
Closing because there is not enough information for the investigation.
