### ISSUE TITLE
aspnetcore : UseGoogleAuthentication throwing "System.Exception: The oauth state was missing or invalid"

### ISSUE THREAD

**Issue by AlexandreOuellet** [aspnet/Security#1198]
Essentially this.

When running on my machine and using a dns wildcard (xip.io), I am able to authenticate through google, and everything seems fine.

When I take the exact same code, and deploy it to a docker container under linux (aspnetcore), I suddenly get errors about "The oauth state was missing or invalid".  At first, I thought it was about related to the redirectURL, but it seems to work just fine.

I have also found [this very similar issue](https://github.com/aspnet/Security/issues/821), but it is essentially a non-answer.

I am using automatic challenge and authenticate, if that makes any difference.

            app.UseIdentity();
            app.UseGoogleAuthentication(new GoogleOptions()
            {
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                ClientId = Configuration["ClientId"],
                ClientSecret = Configuration["ClientSecret"],
                AuthenticationScheme = "Google",
                //SignInScheme = "Cookies",
                //CallbackPath = new PathString("/Home/Login/")
            });

**Comment by Tratcher** [comment]
What does a network/fiddler trace of the requests look like?

**Comment by AlexandreOuellet** [comment]
The initial load of the page, I see a http 302 redirect : 
HTTP/1.1 302 Found
Date: Wed, 03 May 2017 22:10:26 GMT
Content-Length: 0
Server: Kestrel
Location: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=58661652085-9rql92o8is2u2a793p7u4cqv768vfm3k.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Fsem-armory-dev.eidos.com%2Fsignin-google&scope=openid%20profile%20email&state=CfDJ8MnVEDswM59EnvWrEtgmAPgy_U0ede9zZPBnlPskUFgCs8oGIBBlvLyjqzXSkCqJ2-04rVg9iw1OVl4iIoAP_KHH2WtQ_lr4ZXUvfdpCEzv3SYa_nmh5opn9_5D7au1TGmYIO0G38kC_r0Esfk8QJFqGZ5VsZEgohcjkg2iPrwka4wk31Bni-1EWNxxAQzO_Zh4ik_SdSSYrMR7u2FhkyCvuv1x3woicLOhJ6vmD9d1iqGNovP3768DdrOkwNFHNuw
Set-Cookie: .AspNetCore.Correlation.Google.igjOZgFLOFo4vbTiylV9ox2k2Bv7tgEb_9Jf1CCeFNI=N; expires=Wed, 03 May 2017 22:25:26 GMT; path=/; httponly



and then I see the web page exception when coming back from the google authentication.

Is that what you were looking for?

**Comment by Tratcher** [comment]
That request has the state, we need to see the next request.

**Comment by AlexandreOuellet** [comment]
Er...that's about it.

The order is as follow : 

1. Initial request to the website with the 302 (the copy/pasted one)
2. Traffic to host accounts.google.com/o/auth2/auth with status 302
3. Traffic to host accounts.google.com/AccountChooser with status 200
4. Traffic to host accounts.google.com/AccountChooser with status 302
5. Traffic to host accounts.google.com/ServiceLogin with ttus 302
6. Traffic to host accounts.google.com/o/oauth2/auth with status 302
7. Back to my server with status 500 (the exception page mentionning the oauth state was missing or invalid
8. favicon.ico request to my server


The weird thing is that the 7th request, there are tabs about Stack, Query, Cookies and Headers.  Within the Quey tab, I can see that it has a couple of key/value, and "state" is one of the key here.

**Comment by AlexandreOuellet** [comment]
derp me...forgot to include the actual value : 
state	CfDJ8MnVEDswM59EnvWrEtgmAPh9UOvefAXWsNe5njsitdirLkRP9a_zF-ORKWI2CD3zGbHu-jy0DY-smHg0sFXAywAI5Xp9WLpnhnlL8yT8SOrVpXMwBEcNiKAJaeOQ8lzshlyVjfnqO3nZdBODFITuZWqZuGW3yta6l_aS7U3GtfLw4Qpi3KXuYRrrgjfyS_EXt5h3SJ57qtxikqSvoIfKsSoKToxIXZcOdFW9cPIugGLtpBvqAoOoXniJ8-rO7iH_wQ

**Comment by Eilon** [comment]
@AlexandreOuellet can you share with us a more complete trace, such as from Fiddler, which includes the full set of request/response for this authentication?

**Comment by brockallen** [comment]
> @AlexandreOuellet can you share with us a more complete trace, such as from Fiddler, which includes the full set of request/response for this authentication?

Including your google password, please :)

**Comment by Eilon** [comment]
A fair point 😄 Please redact any tokens that are in there!

Or, in the future... we will all have token binding!

**Comment by Eilon** [comment]
Closing because there is not enough information for the investigation.
