### ISSUE TITLE
Consider dropping Active in AuthorizeAttribute.ActiveAuthenticationSchemes 

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#1199]
The active was removed everywhere else, but left in the attribute property.  Would be nice to cleanup if possible.

**Comment by PinpointTownes** [comment]
Ideally, you should consider removing the authentication part from `AuthorizeAttribute` and move that to a separate attribute, which would allow doing things like that:

```
[Authenticate("Bearer")]
public class ApiController : Controller
{
    public IActionResult ActionWithOptionalAuthentication() { ... }

    [Authorize]
    public IActionResult ActionWithRequiredAuthentication() { ... }

    [Authorize(Policy = "HasSuperPrivilege")]
    public IActionResult ActionWithRequiredAuthenticationAndSpecifiedPolicy() { ... }
}

[Authenticate("Cookie")]
public class WebController : Controller
{
    public IActionResult ActionWithOptionalAuthentication() { ... }

    [Authorize]
    public IActionResult ActionWithRequiredAuthentication() { ... }

    [Authorize(Policy = "HasSuperPrivilege")]
    public IActionResult ActionWithRequiredAuthenticationAndSpecifiedPolicy() { ... }
}
```

**Comment by HaoK** [comment]
That doesn't sound unreasonable to me, @rynowak @blowdart @Tratcher thoughts?

**Comment by HaoK** [comment]
Would we keep the existing semantic today of [Authorize] => [Authenticate] implied?

**Comment by blowdart** [comment]
And what would happen if you put Authorize against a method without Authenticate anywhere near?

**Comment by PinpointTownes** [comment]
> And what would happen if you put Authorize against a method without Authenticate anywhere near?

It would use the default authentication scheme handler, as specified in the authentication options. If no is specified, an exception would be thrown, exactly like what already happens in the 1.0 bits.

**Comment by blowdart** [comment]
That's not what it looks like.

Consider the average dev.

I want authentication, so I'm going to put authenticate on my controller. What happens now when there's no authorize attribute? Do we assume one on every method? This looks confusing.

**Comment by PinpointTownes** [comment]
> Would we keep the existing semantic today of [Authorize] => [Authenticate] implied?

Yeah, the default authorization policy should still use `RequireAuthenticatedUser()`.

**Comment by PinpointTownes** [comment]
> I want authentication, so I'm going to put authenticate on my controller.

Authentication = determining who's the caller.
Authorization = determine whether the caller is allowed to perform a given action (which may or may not imply requiring authentication).

This design is exactly the same as the one that Web API + OWIN used to have (with `HostAuthenticationAttribute`), and I don't think people have ever found that confusing.

**Comment by HaoK** [comment]
I'd imagine `[Authenticate]` would be somewhat akin to DefaultAuthenticateScheme, where it will control what's on httpContext.User for the request.  It'd affect how Authorize works since it controls what's the user being authorized against, but that's it.

**Comment by PinpointTownes** [comment]
> It'd affect how Authorize works since it controls what's the user being authorized against, but that's it.

Yep, that's the idea: decoupling the authorization policy evaluation from the authentication schemes.

**Comment by blowdart** [comment]
I'd put to you that the average developer doesn't know, or care about the differences here.

**Comment by PinpointTownes** [comment]
The average developer is not as stupid as you think. And if you really cared about that, you'd have named `AuthorizeAttribute` `RequireAuthenticationAttribute`, which is a more descriptive name (at least for the default authorization policy) :trollface: 

Note: as I said, the design I suggest was already present in Katana and didn't cause any confusion.

**Comment by Eilon** [comment]
After some discussion about breaking changes, we feel it would be better for 2.0.0 to:

1. Add the new property that has the new name we want
2. Keep the old property, but mark it as obsolete and point people to use the new property. The old property would just call into the new property.
3. In 3.0.0 delete the old (obsolete) property: https://github.com/aspnet/Security/issues/1221

**Comment by PinpointTownes** [comment]
So the plan only consists in renaming `ActiveAuthenticationSchemes` to `AuthenticationSchemes`? :open_mouth: 

I really doubt it's worth introducing a breaking change for such a trivial/pointless thing.

**Comment by Eilon** [comment]
@PinpointTownes we think that trying to have more consistent names has advantages, especially when the cost is very low.

**Comment by PinpointTownes** [comment]
@Eilon I'm not saying that name changes are bad (I'm looking at you, `AuthenticateResult`...), but if you decide to break things, then maybe you should go further and revamp this part a bit.

In 2.0, there'll be no way to do per-request authentication middleware selection using pipeline branching (see https://github.com/openiddict/openiddict-samples/blob/master/samples/CodeFlow/AuthorizationServer/Startup.cs#L103-L158 for a concrete example). That would be the perfect moment to have a real "authentication policy" story that is separate from the authorization stack and can be used independently.

**Comment by Eilon** [comment]
@PinpointTownes - we've been doing some thinking around modular applications (e.g. tenants) so there might be a story for this. I agree it's not easy at all with what we are working on.

**Comment by HaoK** [comment]
e940cdb36bc7617af3d762ff9cc853a8fef55b0a
