### ISSUE TITLE
From Pinpoint: OAuthBearer crashes if header is null.

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#120]
This line is totally bugged: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Security.OAuthBearer/OAuthBearerAuthenticationHandler.cs#L63 

2:40:28 PM 

    

It crashes if there's no Authorization header.

**Comment by tushargupta51** [comment]
Fixed and Created pull request.

**Comment by PinpointTownes** [comment]
That would be cool if you could also fix the regression I mentioned here: https://github.com/aspnet/Security/pull/112/files#r22966020

**Comment by PinpointTownes** [comment]
@brentschmaltz @tushargupta51  I just gave it a try and it works like a charm, thanks! :ghost:

**Comment by brentschmaltz** [comment]
thanks Pinpoint and Tushar!
