### ISSUE TITLE
Bring back Microsoft.Owin.Security.Interop and tests

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1201]
These got removed during the netcoreapp2.0 conversion due to complicated dependencies. Figure out how to bring them back.

**Comment by Tratcher** [comment]
Offline discussion:
- Bring this back for preview1
- DataProtection goes to netstandard2.0 (not netcoreapp2.0)
- Invert the dependency between Hosting and DataProtection by moving the one extension method to the Extensions.Hosting.Abstractions package.

**Comment by PinpointTownes** [comment]
On a related note, have you considered moving the DP core APIs to `Microsoft.Extensions.*` and having the hosting adapter in a `Microsoft.AspNetCore.*` package, so OWIN/Katana apps using the interop packages wouldn't have to reference all the ASP.NET Core primitives, that are not used at all in this case?

**Comment by Tratcher** [comment]
In hindsight the DataProtection packages should have been named MS.Extensions.DP, but renaming them is not a break we're planning to make right now.

**Comment by Tratcher** [comment]
Problem: We can bring back the interop package now, but the test project doesn't work anymore because it targets both Core and net46 scenarios.
Proposal: Postpone to preview2 and split the test to two full functional tests apps, one for Katana/net46 and one for Core/netcoreapp2.0 and an orchestration test project that sends cookies from one to the other.

**Comment by PinpointTownes** [comment]
> Problem: We can bring back the interop package now, but the test project doesn't work anymore because it targets both Core and net46 scenarios.

What's the problem, exactly? This test project used to target `net451` (`net452` would be required with the new xUnit version), so why would it be suddenly impossible to run it?

**Comment by Tratcher** [comment]
It was pulling in MS.A.A.Cookies to make sure it could round trip the cookies, and that project no longer supports net451.

**Comment by PinpointTownes** [comment]
Arf... :disappointed:

**Comment by Eilon** [comment]
We'll get it out for Preview2, there just wasn't time for Preview1. Preview2 isn't very far out 😄

**Comment by PinpointTownes** [comment]
That's fine, I had not planned to start using 2.0 before preview2 anyway (and with the recent events, I'm not sure it's even worth it, TBH).

**Comment by PinpointTownes** [comment]
Curious: will the RTM version of this package target Katana 3 or Katana 4?

**Comment by Tratcher** [comment]
I'm targeting Katana 3.0.1 right now (same as before). None of these features are affected by the changes in Katana 4, so I don't see the need to raise the dependency.

**Comment by PinpointTownes** [comment]
Good. As long as there's no API change, binding redirects should allow using it with Katana 4.

**Comment by Tratcher** [comment]
yeah. Katana 4 primarily affects OIDC, WsFed, Bearer, & AAD.
