### ISSUE TITLE
Amazon login support?

### ISSUE THREAD

**Issue by martincostello** [aspnet/Security#1204]
I recently implemented support for [Amazon login](http://login.amazon.com/website) in a project by building on top of the OAuth NuGet package.

Would there be any interest in accepting a PR to make an implementation of that available in this repo like there is for Facebook, Twitter etc.?

**Comment by brockallen** [comment]
This seems like a more appropriate place: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers

**Comment by martincostello** [comment]
Ah, interesting. I wasn't aware of that.. It does indeed look like a sensible place for it.

**Comment by martincostello** [comment]
Moved to aspnet-contrib/AspNet.Security.OAuth.Providers#156.
