### ISSUE TITLE
Question: Using Oauth Provider without Asp.Net Core Identity

### ISSUE THREAD

**Issue by borgdylan** [aspnet/Security#1207]
I implemented authentication manually without core identity and issue cookies. I wanted to allow the user to login with an oauth compatible site such as facebook with using core identity. Is there some customization hook that allows me to implement a handler so that I can handle facebook's return callback myself so that I can link in the new identity with my existing identity system?

**Comment by Tratcher** [comment]
The flow for associating multiple logins wasn't built into the Identity framework, it's in the templates:
https://github.com/aspnet/Templates/blob/c91664a01f6b429b9ff3ac17cacd906037f11b19/src/Rules/StarterWeb/IndividualAuth/Controllers/ManageController.cs#L305-L342
You just need to replace the SignInManager and UserManager with your own identity system.

**Comment by mclasson** [comment]
@borgdylan  Is this in 2.0? Just hook up the middleware for facebook and you should be good to go.

**Comment by reft** [comment]
@Tratcher How do I replace _signInManager.GetExternalLoginInfoAsync(await _userManager.GetUserIdAsync(user));?

Please see: https://stackoverflow.com/questions/48120508/net-core-external-authentication-without-asp-net-identity

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
