### ISSUE TITLE
Review Jwt vs OIDC handling of TVP.ValidIssuer vs ValidIssuers

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1208]
Inspired by: https://github.com/aspnet/AspNetKatana/issues/55
Jwt and OIDC don't use the same logic for dealing with Issuers:
https://github.com/aspnet/Security/blob/99aa3bd35dd5fbe46a93eef8a2c8ab1f9fe8d05b/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L136-L150
https://github.com/aspnet/Security/blob/99aa3bd35dd5fbe46a93eef8a2c8ab1f9fe8d05b/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L1216-L1228

**Comment by Tratcher** [comment]
@brentschmaltz

**Comment by Eilon** [comment]
@Tratcher - can you set up a few minutes with @brentschmaltz to go over this?

**Comment by Tratcher** [comment]
IM will look at both the single value and the list, so we can simplify the code to always work with the list at our layer.
