### ISSUE TITLE
Expiring cookies not renewed if exception is thrown

### ISSUE THREAD

**Issue by corruptmem** [aspnet/Security#1209]
It seems that if you're using cookie authentication with `SlidingExpiration = true`, and the next middleware throws an exception, the new Set-Cookie will not be sent.

I have written a minimal test case here: https://gist.github.com/corruptmem/9b88e4a9c658e9d6243dcc6aa6fa8231

## Steps to reproduce
1. Request /login to set auth cookie
2. Request /exception every 20 seconds or so

## Actual behaviour
After a minute, it will start outputting "authenticated? False" in the exception method

## Expected behaviour
It will send a Set-Cookie header after 30 seconds to renew the sliding window, as it does for non-exception pages.

For example, if instead of /exception, you repeatedly request the root, you will notice the cookie is renewed as expected.

**Comment by Tratcher** [comment]
If you have unhandled exceptions blowing out your stack on every request then sliding refresh is the least of your worries. Also, even if the cookie middleware refreshed itself here, the server would clear all response headers when dealing with the unhandled exception.

Note the sliding refresh policy kicks in when the cookie is half way to being expired so if you have an occasional unhandled exception then you still have plenty of time to renew the cookie on the next request.

**Comment by corruptmem** [comment]
Of course, and I've fixed the underlying unhanded exception. It just happened to notice because it was a failing endpoint that was repeatedly called as part of a very long running process

However, it is still behavior that I didn't see documented anywhere or expect, given that it has the error handling middleware and was correctly returning a friendly error response.

**Comment by Eilon** [comment]
In this type of "fatal" error condition the only safe thing to do is to reset the request as much as possible and show the error page. The error handler can't by default do anything such as let cookies go through because it can't know what's safe or not. If you have a custom error handler you could certainly customize it to have more advanced or custom behaviors.
