### ISSUE TITLE
Is there a way to disable the post-login redirect?

### ISSUE THREAD

**Issue by Halofreak1990** [aspnet/Security#1211]
For our web application, the user needs to perform an optional, custom post-login action, for which we return another view from our login action. However, the user never gets to see this view, because the authentication middleware always redirects to the returnUrl, regardless of whatever result is returned from the Login action.

Is there an easy way to circumvent this automatic post-login redirect? It would be nice if the developer had the final say about these redirects, and not the middleware.

**Comment by Eilon** [comment]
We think this should be possible. The AccountController's Login method for handling the POST operation typically returns a `Redirect` result. You should be able to change that to return something else, if you like, such as a View. You can then handle the Redirect however you want (if at all).

If this doesn't work for you, please show us your Login method for the POST operation.

**Comment by Halofreak1990** [comment]
@Eilon I've pasted some of the code below:
```C#
var p = HttpContext.Session.Get<Person>("User");

if (string.IsNullOrEmpty(p.PreferredCompanyId))
{
	ViewData["returnUrl"] = returnUrl;

	return View("CompanySelect");
}

if (!string.IsNullOrEmpty(returnUrl))
{
	return LocalRedirect(returnUrl);
}

return Redirect("/Book/Hierachy/?val=");
```

So, what happens here, is that our SignInManager implementation has set a 'Person' object in the session, which contains a bunch of properties. A Person can be connected to multiple companies, but can only act for one company at a time. If the user does not yet have a 'preferred' company, then this code will return a view that will allow the person to select the company they wish to use for the remainder of their login session.

The problem is that while the 'CompanySelect' View is processed by MVC, as I can see when single-stepping through the code and the view, the end result remains a redirect to the returnUrl.

**Comment by Eilon** [comment]
@Halofreak1990 - the code you have there in general looks fine, but it depends on which action it's part of. Can you share with us which action on your controller this is part of?

**Comment by Halofreak1990** [comment]
@Eilon I've decided to include the entire action (containing the previous snippet) for the sake of clarity
```csharp
//
// POST: /Account/Login
[HttpPost]
[AllowAnonymous]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
{
	ViewData["ReturnUrl"] = returnUrl;

	if (ModelState.IsValid)
	{
		// This doesn't count login failures towards account lockout
		// To enable password failures to trigger account lockout, set lockoutOnFailure: true
		var result = await _signInManager.PasswordSignInAsync(model.UserName, model.Password, model.RememberMe, lockoutOnFailure: false);

		if (result.Succeeded)
		{
			_loggingRepository.LogLogin(model.UserName);

			var p = HttpContext.Session.Get<Person>("User");

			if (string.IsNullOrEmpty(p.PreferredCompanyId))
			{
				ViewData["returnUrl"] = returnUrl;

				return View("CompanySelect");
			}

			if (!string.IsNullOrEmpty(returnUrl))
			{
				return LocalRedirect(returnUrl);
			}

			return Redirect("/Book/Hierachy/?val=");
		}
	}

	// If we got this far, something failed, redisplay form
	return View(model);
}

**Comment by Eilon** [comment]
Thanks for posting the complete code, this definitely looks weird.

Have you been able to step through the code in the debugger to make sure that the `return View("CompanySelect")` line is what's being executed in your case? We've looked at the code and we think that as long as that line runs that it should all work... (but perhaps not!)

@HaoK - any other ideas around what might be "forcing" a redirect even when the account controller isn't redirecting?

**Comment by Halofreak1990** [comment]
> Have you been able to step through the code in the debugger to make sure that the `return View("CompanySelect")` line is what's being executed in your case?

Yes. The line is executed, and, by setting a breakpoint anywhere in the view, I can also see the view being executed properly.

**Comment by Eilon** [comment]
Thanks. It appears that `PasswordSignInAsync` causes the status code and location header to be set, which means that even if you render a view, the redirect will happen.

We suggest setting the status code back to 200 and clearing the `Location` HTTP response header to prevent the redirect.
