### ISSUE TITLE
Add a helper extension for setting up JWT bearer authentication

### ISSUE THREAD

**Issue by danroth27** [aspnet/Security#1213]
To setup JWT bearer authentication you have to: 1. add JWT bearer, 2. setup the default auth schemes. We should add a helper extension that does this for you:

The templates currently have this code that should be in the framework:

```c#
        public static IServiceCollection AddWebApiAuthentication(this IServiceCollection services)
        {
            services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            });

            services.AddJwtBearerAuthentication();
            return services;
        }
```

Alternative names: `AddDefaultJwtBearerAuthentication`, ...

**Comment by brockallen** [comment]
Shared options should die in a tire fire, with all due respect :)

**Comment by danroth27** [comment]
@HaoK @davidfowl 

@brockallen Could you please file a separate issue with that feedback (if you haven't already) and add some more details on what you'd like to see changed?

**Comment by HaoK** [comment]
So shared options are basically a sugar/hack that allow not specifying the scheme for things like Authorize and automatically getting a httpContext.User from cookies, and having remote OAuth providers automatically create an 'Application' cookie.  That said, I'm not sure most people want to see or understand all that complexity, which is why we've always sort of hidden them with default 'shared' options.

**Comment by brockallen** [comment]
> shared options are basically a sugar/**hack**

Thus the ask :) I see them as analogous to shared/static state that we've all been trying to move away from.

**Comment by HaoK** [comment]
Yeah well, templates need to be simple/pretty/clean is the other argument, and in many apps, there really is a good candidate for 'default' authentication scheme (usually a cookie), and if you don't like the sugar, you don't have to use it anyways.

But I'll grant you the fact that the sugar is there has hidden the fact that you can explicitly set a lot of these things...

**Comment by brockallen** [comment]
Yea, it's just a reminder about magic am ambient stuff not helping people understand things. As said elsewhere, we already have enough issues about people not knowing how any of this works.

**Comment by Tratcher** [comment]
Isn't this a non-issue for bearer since you only have to set the defaults if there's more than one?

**Comment by HaoK** [comment]
Yeah so if this method is the only AddXyzAuthentication called for that template, you should just call AddJwtBearerAuthentication directly and avoid setting the defaults

**Comment by danroth27** [comment]
Ah, I didn't realize that. I'll try that out, but it sounds like we don't need this one then.

**Comment by Eilon** [comment]
Closing this issue because it ends up being a one-liner anyway.
