### ISSUE TITLE
Add a helper extension for setting up authentication with Azure AD

### ISSUE THREAD

**Issue by danroth27** [aspnet/Security#1214]
We should provide some extensions that simplify setting up authentication with Azure AD for both web apps and web APIs. Here is what the templates current do:

https://github.com/dotnet/templating/tree/rel/vs2017/3-Preview2/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Extensions/AzureAd

https://github.com/dotnet/templating/tree/rel/vs2017/3-Preview2/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/WebApi-CSharp/Extensions/AzureAd

See also #1213 and #1212

**Comment by danroth27** [comment]
@vibronet

**Comment by PinpointTownes** [comment]
Pretty much what I suggested in November when the AzureAD-specific/non-standard telemetry stuff was added directly in IdentityModel:

https://github.com/aspnet/Security/issues/1035#issuecomment-260133984
https://github.com/aspnet/Security/issues/1035#issuecomment-261291374

**Comment by Tratcher** [comment]
@danroth27 AzureAdOpenIdConnectOptionsSetup has code that looks intended to be customized.

**Comment by HaoK** [comment]
Well customers can just tweak the resulting options with a normal `services.Configure<OpenIdConnectOptions>` instead of editing the setup class too

**Comment by danroth27** [comment]
Right, all the places where we want to point customers to customize the code we would recreate in the template using a call to `services.Configure<OpenIdConnectOptions>`

**Comment by danroth27** [comment]
@ajcvickers @Eilon @muratg 

@HaoK I believe this should be assigned to you, correct? Are you going to be able to get to this by EOW?

**Comment by PinpointTownes** [comment]
@danroth27 now that Azure AD is going to have its own OIDC extension/wrapper, is moving the non-standard/implementation-specific "telemetry" stuff from IdentityModel to this new helper something you could consider?

**Comment by danroth27** [comment]
@vibronet @Tratcher @brentschmaltz 

@PinpointTownes I'm not familiar with the "telemetry" stuff you're referring to. Adding some folks who probably have more context.

**Comment by PinpointTownes** [comment]
@danroth27 here's the _feature_ in question: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/529/files

It was discussed here: https://github.com/aspnet/Security/issues/1035.

**Comment by HaoK** [comment]
@danroth27 now that we are down to 2-3 files, are we ok with this living in the template for preview 2?  The AzureAd/B2C Options concept is just a template concern, and the OptionsInitialize (which we'll need to rename to PostConfigure once the Options PR is in), is pretty simple (sets authority using the Azure options).  And you wanted the other events code in the template anyways
