### ISSUE TITLE
removing returnuri from OpenIdConnectOptions cause some problems

### ISSUE THREAD

**Issue by farshid3003** [aspnet/Security#1216]
when you code works behind an proxy server like nginx with http protocol and from out you have https (ssl) now when you go to authority server your client redirect_uri is not valid as it will post with http not https.
it is now automatically set my current uri which is not correct for authentication

let explain more
I have a client application which is running on linux on 5000 port : http://127.0.0.1:5000
and I have an nginx which forward https://mydomain.com to http://localhost:5000
I have an Identityserver (Identityserver4) and I configured my client in this server
on authentication time I got this error:unauthorized_client
in logs I saw that in the request return_url set to http://mydomain.com and this url is not valid in identityserver

**Comment by Tratcher** [comment]
See my comment on your other post: https://github.com/aspnet/Security/issues/553#issuecomment-300909604

**Comment by farshid3003** [comment]
I did it actually  the problem is that when you go to ids with http//* and ids is wating for https.
in the app middle ware set the return_url automatically and set it to http
now I solve it by using events

` Events = new OpenIdConnectEvents
                {
                    OnRedirectToIdentityProvider = OnRedirectToIdentityProvider
                },

and in the method
arg.Properties.RedirectUri = idsConfig.ReturnUri;`

but I think it should let me to set return_url. if I didnot set it It can set it automatically

**Comment by Eilon** [comment]
@Tratcher - can you show how to specifically set the URL to HTTPS without specifying the entire URL?

**Comment by farshid3003** [comment]
you nees to set entie url

**Comment by farshid3003** [comment]
Now I have 
`            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });
 `
in my code and in nginix config ihave
`        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
`
and also set return_url in event

but after login it shows 502 Bad Getway :(

**Comment by farshid3003** [comment]
I solve 502 after oaut2 
the problem is by nginx buffer size 
` proxy_buffer_size   256k;
        proxy_buffers   4 256k;
        proxy_busy_buffers_size   256k;`


but this issue does not change any thing microsoft should re open return_url

**Comment by Tratcher** [comment]
If you're trying to require HTTPS for some or all of your app then consider using the rewrite components to enforce it. MVC has a similar RequireHttps attribute that you can put on your endpoints that require/initiate auth.

https://github.com/aspnet/BasicMiddleware/blob/08a8493ecc2681668b5a1fff49add9c4c0d8dde0/samples/RewriteSample/Startup.cs#L20

**Comment by farshid3003** [comment]
thank you, you are right but i did it in nginx. connection to nginx is https and it redirects http requests to https and connection from nginx to app is http

**Comment by Eilon** [comment]
@farshid3003 - have you solved your problem here? If so, we will close this issue. Thanks!

**Comment by Eilon** [comment]
Closing because we haven't heard back. Please re-open or log a new issue if there's still a problem.

**Comment by farshid3003** [comment]
as İ said I solve it by event
