### ISSUE TITLE
Consider making Auth handlers public

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#1218]
They are internal today (prior to 2.0 they weren't really easy to extend/reuse).  There's no reason they can't be public today.  Before events used to be the sole extensibility points, but handlers should now be able to be extended/replaced.

**Comment by Eilon** [comment]
Let's wait until 2.1 so that we can come up with the right API surface for these.

**Comment by brockallen** [comment]
@HaoK I don't recall if overriding the handler is how you suggested IdentityServer can inject the claims it needs to or not... but if it is, then delaying this to 2.1 causes an issue for us with IdentityServer.

**Comment by HaoK** [comment]
Can you point me to the relevant thread for that if we had one?

**Comment by brockallen** [comment]
Yea... might have been email... @leastprivilege might have an easier time of finding it. We'll look and get back. Thx.

**Comment by HaoK** [comment]
Sounds like you should be good, decorating the default AuthenticationService implementation to validate/add your own claims for every call to SignIn.  That's not affected this issue of not exposing our OAuth handler implementations right now.

**Comment by brockallen** [comment]
okies, thx

**Comment by Eilon** [comment]
Closing because we have no plans to do this. Many extensibility points are available via existing events.
