### ISSUE TITLE
Example for how to configure CookieAuthentication in ASP.NET Core 2 Preview

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/Security#1219]
Is there an example somewhere on how to configure Cookie Authenticaiton in the preview?

The [old configuration mentioned in the documentation ](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie) now breaks, and so is no longer valid.

Any examples on how to configure Cookie authentication would be useful. In the meantime app's broken which is kind of sad given that this was working and now fails with a hard compiler error.

**Comment by davidfowl** [comment]
https://github.com/aspnet/Security/blob/bdd4d219962201907393734d9fab2903921fec9d/samples/CookieSample/Startup.cs#L16-L21

**Comment by davidfowl** [comment]
The gist of the changes are that things were moved from middleware into services.

**Comment by damienbod** [comment]
How would you do something like this?

https://github.com/damienbod/AspNetCoreMvcAngular/blob/master/AspNetCoreMvcAngular/Startup.cs#L91-L112

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/blob/bdd4d219962201907393734d9fab2903921fec9d/samples/OpenIdConnectSample/Startup.cs

**Comment by damienbod** [comment]
Hi @Tratcher 

The new way is more complicated than before. Why was this changed?

Greetings Damien

**Comment by HaoK** [comment]
The startup changes for any individual auth aren't really that different except that they have moved to ConfigureServices as opposed to Configuring a middleware.  You can see https://github.com/aspnet/Announcements/issues/232 for more details.

The main things that are different in startup is moving the concept of AutomaticChallenge/Authenticate out of each options into a shared place eliminating the possibility of multiple auth setting these flags, and having only a single `UseAuthentication()` middleware.

**Comment by RickStrahl** [comment]
Thanks for some of the links but neither of those show how to set specific values for the cookie authentication.

My old code used this to specify custom login path:

```cs
    app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AutomaticAuthenticate = true,
                AutomaticChallenge = false,
                LoginPath = "/api/login"
            });
```

I can't find the place (or whatever replaced them) where I can apply these options.

**Comment by HaoK** [comment]
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCookieAuthentication(o => o.LoginPath = "/api/login");
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseAuthentication();
        }
```

**Comment by RickStrahl** [comment]
Aaargh - yes thank you. This is a case where Visual Studio Intellisense didn't show the AddCookieAuthenitcation() and tried working off AddAuthentication() only which didn't have the right settings to set.

This gets me a little further:

```cs
public void ConfigureServices(IServiceCollection services)
{
	services.AddCookieAuthentication(o =>
    {
		o.LoginPath = "/api/login";
		o.LogoutPath = "/api/logout";				
    });
}
```
and `app.UseAuthentication()` in `Configure()`. 

However this gets me:

> No authentication handler is configured to handle the scheme: Cookies

So there's something else missing here.


       
+++ Rick ---

**Comment by Tratcher** [comment]
Stack trace? The calling methods also changed. See the announcement.

**Comment by RickStrahl** [comment]
The announcement doesn't give much info. I'm not sure what I can't figure out what this is trying to say:

       context.Authenticate|Challenge|SignInAsync("scheme"); // Calls 2.0 auth stack

Here's what I have in my existing auth method that works in 1.1:

```cs
        [AllowAnonymous]                    
        [HttpPost]
        [Route("api/login")]
        public async Task<bool> Login([FromBody]  User loginUser)
        {            
            var user = await accountRepo.AuthenticateAndLoadUser(loginUser.Username, loginUser.Password);
            if (user == null)
                throw new ApiException("Invalid Login Credentials", 401);

            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(ClaimTypes.Name, user.Username))    ;
           
            if (user.Fullname == null)
                user.Fullname = string.Empty;
            identity.AddClaim(new Claim("FullName", user.Fullname));

			
			//context.Authenticate | Challenge | SignInAsync("scheme"); // Calls 2.0 auth stack

			await HttpContext.Authentication.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(identity));

            return true;
        }
```

Stacktrace:

```
Application started. Press Ctrl+C to shut down.
fail: AlbumViewerAspNetCore.ApiExceptionFilter[0]
      No authentication handler is configured to handle the scheme: Cookies
System.InvalidOperationException: No authentication handler is configured to handle the scheme: Cookies
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<SignInAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AlbumViewerAspNetCore.AccountController.<Login>d__2.MoveNext() in C:\projects2010\AlbumViewerVNext\src\AlbumViewerNetCore\Controllers\AccountController.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__15.MoveNext()
```

I also tried this in addition to `AddCookieAuthentication()` in `ConfigureServices()`:

```cs
services.AddAuthentication(o =>
			{
				o.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
			});
```

but no luck. Something is still missing?

**Comment by HaoK** [comment]
HttpContext.Authentication.SignInAsync is the old  auth 1.0 stack. Drop the authentication. We will depreciate the old apis in preview2 so it will be more obvious in the future.

**Comment by RickStrahl** [comment]
I'm not sure what you're saying? What do you mean drop the authentication? I have an API that needs to create a signin cookie. 

Are you saying this isn't implemented in this preview?

**Comment by dotnetchris** [comment]
The authentication system of ASP.NET CORE is nightmarishly over-engineered. 

What in the world happened to the simplicity override the Authorize method that used to exist in ASP.NET MVC?

I get that Microsoft is trying to do everything possible to eliminate people from rolling their own auth by making it pretty much impossible to roll your own, but that one size fits all is a very naive end product. Especially when Identity and the schema/models it uses is almost wholly wrong IMO. 

I feel like we've taken multiple steps backwards. Literally since 2010 one of the chores of .NET has always been rip out all of the membership and identity stuff and roll your own on top of FormsAuthentication to ensure properly cookie protection. Now Identity is even worse than the Membership stuff. 

Crazy and very sad at the same time.

**Comment by HaoK** [comment]
@RickStrahl I mean you need to call `httpContext.SignInAsync` instead to call the 2.0 authentication stack.

**Comment by RickStrahl** [comment]
LOL! Sure enough that's it! 

Miscommunication. So this now works:

```cs
		[AllowAnonymous]                    
		[HttpPost]
		[Route("api/login")]
		public async Task<bool> Login([FromBody]  User loginUser)
		{            
			var user = await accountRepo.AuthenticateAndLoadUser(loginUser.Username, loginUser.Password);
			if (user == null)
				throw new ApiException("Invalid Login Credentials", 401);

			var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
			identity.AddClaim(new Claim(ClaimTypes.Name, user.Username))    ;
           
			if (user.Fullname == null)
				user.Fullname = string.Empty;
			identity.AddClaim(new Claim("FullName", user.Fullname));

			
			//context.Authenticate | Challenge | SignInAsync("scheme"); // Calls 2.0 auth stack
			
			await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
				new ClaimsPrincipal(identity));

			return true;
		}
```

I'll write that up tonight for my own sanity.

Thank you.

**Comment by RickStrahl** [comment]
@dotnetchris It doesn't have to be all difficult. The code I use here is an example of a very simple auth implementation that's no more complicated than Forms Auth in classic ASP.NET. You still need the config stuff, but the new config that's mentioned here is actually less than 10 lines of code, so not exactly difficult.

I do agree if you go full bore with the entire identity system then things are  a lot more complicated. But if you just need to do the auth and let a backend application deal with customer/user mapping (as is usually the case anyway), it's not that difficult to make that happen.

**Comment by snibe** [comment]
hoping someone can help me as I have had a similar issue and i am stuck with using this code  described in this thread here and getting this error   

No IAuthenticationSignInHandler is configured to handle sign in for the scheme: Cookies


any ideas?

**Comment by mikeball** [comment]
@dotnetchris completely agree with you after battling this new stuff for an entire week in an attempt to get something running that was trivial in forms auth.

**Comment by plsft** [comment]
AddCookieAuthentication() doesn't seem to work for me. I thought i added the correct packages. any thoughts? gettting:

InvalidOperationException: No IAuthenticationSignInHandler is configured to handle sign in for the scheme: Cookies

with following code:

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthorization(o =>
            {
                o.AddPolicy("Users", p => p.RequireClaim("Users"));
                o.AddPolicy("SuperUsers", p => p.RequireClaim("SuperUsers"));
                o.AddPolicy("PlatformUsers", p => p.RequireClaim("PlatformUsers"));
            });

            services.AddAuthentication(options =>
            {
                options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            }).AddCookie("Cookieauth", options =>
            {
                options.LoginPath = new PathString("/login");
                options.AccessDeniedPath = new PathString("/error?unauth");
            });



            services.AddMvc();
        }

**Comment by Tratcher** [comment]
Your scheme names don't match. That should be
```
        services.AddAuthentication("Cookieauth")
        .AddCookie("Cookieauth", options =>
        {
            options.LoginPath = new PathString("/login");
            options.AccessDeniedPath = new PathString("/error?unauth");
        });
```

**Comment by davidfowl** [comment]
@Tratcher @HaoK can we list out the all registered schemes in the exception message?

**Comment by Tratcher** [comment]
It's possible, and may help people that keep mismatching their scheme names. https://github.com/aspnet/Security/issues/1502

**Comment by peirens-bart** [comment]
Hi 
I know this topic is closed but I still have question where I can't find the answer for.
in core 1.1 I can do 

```
app.UseCookieAuthentication(_cookieOptions);
            app.UseJwtBearerAuthentication(new JwtBearerOptions()
            {
                Audience = ...,
                ClaimsIssuer = ...,
                AutomaticAuthenticate = true,
                RequireHttpsMetadata = !env.IsDevelopment(), 
                TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    ValidIssuer = ...,
                    ValidateAudience= true,
                    ValidAudience = ...,
                    RequireExpirationTime= false,
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(...))
                }
            });
```

when i create the cookie and de jwt token with the same claims, i can get the claims in a middelware from `(httpContext.User.Identity as ClaimsIdentity).Claims`

in core 2.0
I do this
```
services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = <<AUTHENTICATIONSCHEME>>;
                options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
            }).AddCookie(<<AUTHENTICATIONSCHEME>>,options =>
            {
                options.LoginPath = new PathString("/Account/login");
                options.AccessDeniedPath = new PathString("/Account/login");
                options.LogoutPath = new PathString("/Account/Logoff");
            })
            .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme,options =>
            {
                options.Audience = ...;
                options.ClaimsIssuer = ...;
                options.RequireHttpsMetadata = !_hostingEnvironment.IsDevelopment();
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    ValidIssuer = ...,
                    ValidateAudience = true,
                    ValidAudience = ..,
                    RequireExpirationTime = false,
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(...))
                };
            });
```
in the middleware I can read the claims from the cookie but nor for the jwt token
the request I'm using is adding in the header Key:Authorization, value: bearer <<token>>

can someone explain me why this was working in 1.1 and not in 2.0

Thanks
