### ISSUE TITLE
EditProfile page doesn't load Azure AD B2C 

### ISSUE THREAD

**Issue by piolo94** [aspnet/Security#1220]
Hi everyone! I'm trying to use the authentication service given by Azure AD B2C with the new AspNetCore 2.0 template, but I'm having a little issue. I've build a new WebApp application from the given template in Visual Studio 2017 15.3 Preview and I've configured the Signup, Signin and EditProfile policies, but while the first twos are working perfectly, the last one's giving me some problems: in particular, when I log on and I try to reach the user's profile page, the right method in the controller is called, but after this I'm redirected to the home page with no further explanation. Does someone have the same issue?

**Comment by Tratcher** [comment]
@javiercn @danroth27

**Comment by danroth27** [comment]
@gsacavdm @vibronet

@piolo Could you please share the Azure AD B2C configuration in your appsettings.json file?

**Comment by piolo94** [comment]
Sure! Here you are: 
`"Authentication": {
    "AzureAdB2C": {
      "AzureAdB2CInstance": "https://login.microsoftonline.com/tfp",
      "ClientId": "<MyClientId>",
      "CallbackPath": "/signin-oidc",
      "Domain": "<MyDomain>.onmicrosoft.com",
      "SignUpSignInPolicyId": "B2C_1_SignIn",
      "ResetPasswordPolicyId": "B2C_1_ResetPassword",
      "EditProfilePolicyId": "B2C_1_Edit"
    }
  }`
ClientId is the application guid given from azure.
MyDomain is the domain of active directorty B2C.
The only one custom configuration that we've made directly on Azure B2C is that we use the username instead of email for the login.
I've noticed that also the ResetPassword operation has the same behaviour of the EditProfile, but probably it's just a consequence. Thanks for your support!

**Comment by danroth27** [comment]
When you browse to https://login.microsoftonline.com/tfp/<MyDomain>.onmicrosoft.com/B2C_1_Edit/v2.0/.well-known/openid-configuration and https://login.microsoftonline.com/tfp/<MyDomain>.onmicrosoft.com/B2C_1_ResetPassword/v2.0/.well-known/openid-configuration do you get back a JSON configuration document? I'm just trying to check that the Policy IDs are correct.

Also, can you look at the network trace (F12 in the browser should work) and see what Azure AD B2C is returning in it's authorize response? Is it reporting back an error message?

**Comment by piolo94** [comment]
When I check the two policies with the urls, I get back the corrects Json files, containing the configuration. 
When I run the project and after login i try to open the profile page, the authorize response contains valid "state" value and "id_token", without any error. Right after. the browser calls signin-oidc passing "state" and "id_token" but the response is a redirect to the localhost home page instead of the B2C Edit profile page. Thanks for your support!

**Comment by gsacavdm** [comment]
Hey @piolo94 , as @danroth27 indicated, the best way to help debug this is by looking at the network trace (F12 in the browser) to see the request sent to Azure AD B2C and the response from it.

Generally, those redirects are a result of B2C dealing with a bad request and redirecting back to the app with error details embedded in the query string or the post body.

**Comment by piolo94** [comment]
Hey everyone! Thank you very much for your patience! We've tried to find any message of error in the network trace, but none was found. We tried to call directly the request URL  to EditProfile policy and we got an error page. So we've put a break point in the AzureAdB2COpenIdConnectOptionsSetup class and we found that the OnRemoteFailure method was called. The failure message contains "Correlation Error".

**Comment by piolo94** [comment]
Ok guys! Now everything is working! I've recreated several times each single policy and I've found that probably there's a problem with the cases: when the request in local is prepared, the name of the requested policy is always passed in lowercase and everything works only when also on Azure a policy is written in lowercase. Is that possible, or I should check for another problem? Thanks!

**Comment by danroth27** [comment]
@Tratcher Does the OIDC auth handler mess with the casing of the Issuer URI?

**Comment by Tratcher** [comment]
No

**Comment by danroth27** [comment]
@piolo94 I just tried creating a new ASP.NET Core 2.0 app that uses policy IDs with mixed casing and it worked fine. Can you help me out with the exact steps need to reproduce this issue?

@gsacavdm Any ideas on where this casing issue might be happening?

**Comment by gsacavdm** [comment]
If @piolo94 shares the Correlation ID from that correlation error he mentioned we should be able to take a look from our end, or even the tenantID might suffice. As @danroth27, policy names aren't case sensitive.

@piolo94 , out of curiosity, was this using built-in policies or custom policies?

**Comment by piolo94** [comment]
Ok guys, I've done some tests and I think that I've found something. My SignIn/SignUp policy on Azure is named "B2C_1_Customer-Web-Access". If I copy this string in the appsettings.json, I am able to login but the other polcies doesn't work at all. If I let this name on Azure and in the appsettings.json I refer to this policy with the same string, but in lowercase ("b2c_1_customer-web-access"), everything works perfectly. It seems that putting in uppercase one or more letters,  makes all fail except for the login and signup which work anyway. The other policies ( ResetPassword and EditProfile) seems  to be not affected by this "case" problem: if I refer to the signin/signup policy with the string in lowercase in the appsettings.json, the other policies can have one or more characters in uppercase and everything still works.

**Comment by gsacavdm** [comment]
Ah, great catch @piolo94 , this is due to the `.Replace(defaultPolicy, policy)` statement in the `OnRedirectToIdentityProvider`.

@danroth27, can you fix this in the template, we should just add a .ToLower() where we retrieve the policies.

**Comment by danroth27** [comment]
Ugh, yeah, we should probably do a case insensitive replace:

```c#
context.ProtocolMessage.IssuerAddress = context.ProtocolMessage.IssuerAddress.Replace(defaultPolicy, policy, StringComparison.OrdinalIgnoreCase);
```

**Comment by Eilon** [comment]
@cesarbs - according to @HaoK this is fixed in the Preview 2 *template* already. Can you confirm this as part of your Preview 2 verification? If it's fixed, please change the milestone to preview2 and close the bug.

**Comment by cesarbs** [comment]
@Eilon Will do.

**Comment by cesarbs** [comment]
@Eilon Just confirmed that the edit profile stuff is working in the latest template.

**Comment by Eilon** [comment]
Cool, so we can just close this bug then?
