### ISSUE TITLE
AddOpenIdConnectAuthentication doesn't work with 2.0.0-preview2-25108

### ISSUE THREAD

**Issue by vRITHNER** [aspnet/Security#1224]
Hi,
Any app I try to create with aspnetcore 2.0.0-preview2-25108 doesn't work because

> ArgumentException: Options.ClientId must be provided
> Parameter name: ClientId
> Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions.Validate()
> 
> Stack Query Cookies Headers
> ArgumentException: Options.ClientId must be provided
>  Parameter name: ClientId

Even your sample 
`OpenIdConnectSample`
doesn't work

**Comment by Tratcher** [comment]
While I did find a number of other issues with the samples (https://github.com/aspnet/Security/pull/1226), I'm not reproducing your issue in the latest dev branch. It sounds like a legitimate configuration error. OpenIdConnectSample does not include the ClientId config, it needs to be added on your own machine. I have mine set as an environment variable.

**Comment by vRITHNER** [comment]
Hi, 
Thanks for the tip.

I've a request about the other sample with Azure AD connect; it could be great to have access (read-only) to a Azure sample instance to see all settings; I tried to replicate the sample with my own Azure instance and I surely made a mistake somewhere because when I click login, nothing happen...

Txs
-Vince

**Comment by Tratcher** [comment]
Have you tried these docs?
https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/

**Comment by vRITHNER** [comment]
FYI, still not working with latest template 

```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview2-25149" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0-preview2-25149" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0-preview2-25149" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0-preview2-25149" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0-preview2-25149" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview2-25149" />
  </ItemGroup>
```

```
Product Information:
 Version:            2.0.0-preview2-006215
 Commit SHA-1 hash:  e67962b0de

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16199
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\vrith\.dotnet\x64\sdk\2.0.0-preview2-006215\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25319-02
  Build    : 7983b575ebcbdc3a825eea4b141ff7fb69d25f9d
```

**Comment by Tratcher** [comment]
The same error as in your first post?

**Comment by vRITHNER** [comment]
Yep; sorry to come back with it but didn't change since I posted the first time and I try with a lot of different cli / sdk / template.

This is quite frustrating to simply open VS, create new aspnet.core mvc auth individual and press F5 to get the ClientID error.

txs
-Vince

**Comment by justin-ruffin** [comment]
Yes, I have confirmed this as well. Working version in preview1, preview2 an error about the same error "ArgumentException: Options.ClientId must be provided Parameter name: ClientId
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions.Validate()"

**Comment by eddyekofo94** [comment]
I am having the same error also:
`Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.ArgumentException: Options.ClientId must be provided
Parameter name: ClientId`

**Comment by Tratcher** [comment]
@eddyekofo94 what does your Startup code look like?

**Comment by eddyekofo94** [comment]
My fault, I didn't set my OpenID ClientID nor ClientSecret. 
@Tratcher Thanks.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
