### ISSUE TITLE
alg=none for Microsoft.AspNetCore.Authentication.JwtBearer middleware

### ISSUE THREAD

**Issue by george-ayris** [aspnet/Security#1227]
Hi there,

I'm using the JwtBearer middleware as part of an ASP.NET Core application and I'm trying to get it to accept tokens that have the `alg` field in the JWT header set to `none`. This is primarily to make automated testing easier on non-production environments.

My understanding was that the middleware would use the configured Authority's `.well-known/openid-configuration` endpoint to retrieve the required information for token validation and therefore I have this within the configuration endpoint response:
` "id_token_signing_alg_values_supported": [
    "RS256",
    "none"
  ]`

However, the API is still returning a 401 with the following error in the logs:
`Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware:Information: Bearer was not authenticated. Failure message: No SecurityTokenValidator available for token`

I'd be very thankful if somone could point me to where I've configured things incorrectly. Currently the middleware just has the Authority, AutomaticAuthenticate (set to true) and Audience set in the JwtBearerOptions.

Cheers,
George

**Comment by Tratcher** [comment]
@brentschmaltz ?

**Comment by brentschmaltz** [comment]
@george-ayris by default we don't allow algorithm 'none'. There are know attacks. 
Assuming that "none" means there will be no signature. If you leave the signature off an do not specify any algorithm in the header.
You can set BearerOptions, TokenValidationParameters.RequireSignature = false. Then if a signature is not found, IdentityModel will not fault.

Audience, Issuer, Lifetime will still be validated, these can be controlled using TokenValidationParameters switches.

**Comment by george-ayris** [comment]
@brentschmaltz thank you very much for your help.
