### ISSUE TITLE
Usermanager.GetuserAsync and User.IsInRole don't work with v. 2.0.0-xxxxxx

### ISSUE THREAD

**Issue by vRITHNER** [aspnet/Security#1228]
Hi,

I don't know if I'm in right repo to speak about that but with 2.0.0-preview1-final
my web mvc app with identity individual 
` services.AddIdentityServiceAuthentication();`

with 1,1.0, my controller or view used a method:
`await _userManager.GetUserAsync(User);` to get user properties

with 2.0.xxx
please find attached the result in the capture:

![image](https://cloud.githubusercontent.com/assets/238842/26358830/1a0fd068-3fd4-11e7-824b-221ed4eccb93.png)

What am I missing  or the all model to get access to the stuff changed ?
Txs
-Vince

**Comment by Tratcher** [comment]
@HaoK @javiercn

**Comment by javiercn** [comment]
@danroth27

**Comment by muratg** [comment]
This issue was moved to aspnet/Identity#1243
