### ISSUE TITLE
Breaking changes on asp.net core 2 middlewares - guidance

### ISSUE THREAD

**Issue by Jonathan34** [aspnet/Security#1229]
Hi,

Is there any guide to port a asp.net core 1.x middleware to asp.net core 2 preview 1?

I know about the great auth refactoring but can't seem to find guidance/recommendation to upgrade. Will it change a lot again in preview 2, 3 etc?

For instance AuthenticationMiddleware does not take a TOptions as parameter, so i am not sure how we then retrieve the handler...

```
internal class MyAuthValidationMiddleware : AuthenticationMiddleware<MyAuthValidationOptions>
```

Any sample somewhere would be helpful, thanks.

Also our current code targets `.net **standard** 1.6` and upgrading requires `.net **core** 2.0` but i understand this will be resolved in `.net core 2.0 preview 2`.

**Comment by Jonathan34** [comment]
A middleware built with 1.1 is obviously not compatible with .net core 2.0.
i saw documentation is planned and tracked via this issue: https://github.com/aspnet/Docs/issues/3054

i will wait

**Comment by Tratcher** [comment]
@Jonathan34 aspnet/Docs#3054 will primarily focus on app developers consuming auth, not those implementing it.

There are more changes for preview2, but not as dramatic. What kind of auth provider are you implementing? I suggest looking at the JwtBearer or Facebook implementations for reference.
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerExtensions.cs
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Facebook/FacebookExtensions.cs
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Facebook/FacebookHandler.cs
