### ISSUE TITLE
Support for OAuth token refresh on OnValidatePrincipal with cookie authorization

### ISSUE THREAD

**Issue by bgever** [aspnet/Security#1238]
In my apps I'm using OAuth middleware together with cookie authorization. All is hooked up and working well.

However, since the cookie may be persisted or should live for the duration of the session, the underlying access token of the OAuth middleware may expire. OAuth offers to refresh the access token with a refresh token if the server supports this.

The `OnValidatePrincipal` event of the `CookieAuthenticationEvents` is a great moment to hook in the refresh functionality. Especially when combined with the `SaveTokens` option on the OAuth middleware, as it allows to call `context.Properties.GetTokens()` in the `OnValidatePrincipal` event handler to get access to the tokens and to know whether the access token has expired.

Unfortunately [I got stuck there](https://github.com/msdevsHK/website/blob/master/MSDevsHK.Website/Services/AuthManager.cs). My Google-fu uncovered an [ASP.NET Forums thread](https://forums.asp.net/t/2099921.aspx) dating back to 25 July 2016 where @diggerton hit the exact same problem. There's even [example code in a GitHub repo](https://github.com/diggerton/EveSSOMiddleware) showing exactly this approach. Kudos to you @diggerton. 👍  I share in your frustration with your last `stuck` commit message. 😜

Ideally, there should be some way to call the OAuth middleware, or say a call to (non-existent) `await context.HttpContext.Authentication.RefreshAsync()` to refresh the access token, and save it again in the cookie.

**Comment by Eilon** [comment]
There is no built-in support for this. I think @Tratcher might have some further thoughts on how to achieve this with plain middleware.

**Comment by Tratcher** [comment]
OnValidatePrincipal is not the best fit. It can be invoked on every request (even for all of your static files) and may trigger overlapping refreshes.

One reason the OAuth middleware has no support for refresh is that providers are very inconsistent with how they implement it, if at all.

I'd recommend managing your token lifetimes and refresh only at points in your app where you actually use the tokens. E.g. Before you take an action that uses the token first check if it's expired and refresh it. Your auth provider may even have an SDK available for handling this refresh. You can persist the new token by calling SignIn again.

**Comment by diggerton** [comment]
Sometimes use of the token is needed upon refresh.  Having the ability to check it anywhere in the middleware would be nice.  Omitting the ability to check and refresh earlier in the pipeline seems counterintuitive to me.  However, the example project is fairly old and I haven't worked ASP.net since.

**Comment by bgever** [comment]
Thanks @Tratcher for pointing out the challenge around handling multiple requests. That is indeed a problem in our case as we would hit OnValidatePrincipal repeatedly when loading a list of (controller generated) images on the page.

Refreshing *is* part of the OAuth spec, and it can be optionally implemented. Maybe a solution is that the Auth manager has a `RefreshAsync` that may throw a `NotImplementedException` when the provider lacks support.

For now, I think we will go for a custom filter that does the refresh for specific action methods. It would be nice if the framework supports the refresh, rather than us needing to implementing this manually.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
