### ISSUE TITLE
OpenID Connect logout with Azure AD v2 endpoint not working

### ISSUE THREAD

**Issue by Zenuka** [aspnet/Security#1239]
I've tried logging out with the Azure AD v2 endpoint but I always get redirected to my application on the following url: `https://localhost:5000/signout-callback-oidc`. This url gives me a 200 http status code and a blank page. I think the problem is that it's missing `?state=some-encrypted-state`. [I noticed that the open id connect nuget needs the state param to redirect back to the application](https://github.com/aspnet/Security/blob/1f5a27e20adf5438adcd9caf8587230307b685ce/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L279).
When I use the v1 endpoint everything works as expected. 

I've just hung op with Microsoft and they are contacting the development team about also passing the state parameter back when logging out for the v2 endpoint.
I'm not sure if and when they will be supporting the state parameter, so is there another way to get this to work without the state parameter?

**Comment by Tratcher** [comment]
Not really. This code path still needs events that let you customize the behavior: https://github.com/aspnet/Security/issues/956

**Comment by Eilon** [comment]
Closing because this appears to be an issue with Azure AD.

**Comment by Zenuka** [comment]
For anyone finding this issue; the issue in Azure AD has been fixed
