### ISSUE TITLE
Unable to build Release 1.1.2

### ISSUE THREAD

**Issue by bgever** [aspnet/Security#1240]
Release 1.1.1 works fine, however, when I check out branch rel/1.1.2 (17fa77941ddea9c50f1aef541b37965f734292ab) (note, there seems no rel/1.1.2 tag) I get an error that Microsoft.NETCore.App 1.1.2 cannot be found.

The error as mentioned in https://github.com/dotnet/cli/issues/6143#issuecomment-304789441 seems to be related to that the `build.sh` creates a new `.dotnet` folder under my home directory, and in there, the `shared/Microsoft.NETCore.App/1.1.2/` is not present.

**Comment by Eilon** [comment]
@pranavkm / @smitpatel - any idea if maybe we missed pinning some versions for the patch branches?

**Comment by smitpatel** [comment]
Build working fine for me. Testing failing at runtime in some assembly load failure.
Using Ubuntu 16.04.5
I had to install mono-complete

I am not seeing error with 1.1.2 of NETCore.App
The build script installs everything correctly.
