### ISSUE TITLE
VS 2017 15.3 Required ?

### ISSUE THREAD

**Issue by Serexx** [aspnet/Security#1242]
For me loading this solution resulted in a protracted stream of load errors and package restores. I gave up after 20 minutes thinking it must be in a loop of some kind. I did notice that one of the first errors was as follows:

The version of Microsoft.NET.Sdk used by this project is insufficient to support this package.  Please ensure you are using the .NET Core SDK 2.0 or higher, which is included in Visual Studio 2017 Update 15.3.  This error may be suppressed by setting PackagingToolsInsufficientSDKVersion=false.	
CookieSample	
C:\Users\me\nuget\packages\microsoft.packaging.tools\1.0.0-preview2-25316-01\build\Microsoft.Packaging.Tools.targets	34	

Suppressing the error seems silly if in fact there is a mismatch of capabilities . I am using VS 2017 Community 15.2 and upon investigation discover that 15.3 is in pre-release preview. It seems incongruous that we would want samples to only be supported by a prerelease IDE.

I am perhaps misinterpreting all of this and perhaps more patience is required but it seems to me something is amiss.

Any thoughts on a resolution appreciated.

**Comment by Tratcher** [comment]
Those are pre-release samples. VS is out of sync with pre-release runtime we're using. We have a hard time making it work on a day to day basis, even with 15.3-pre. The only guaranteed way to build the dev branch is to run build.cmd from the command line. VS can sometimes be used after a command line restore/build.

**Comment by Eilon** [comment]
Yeah pretty much what @Tratcher said. Unfortunately sometimes the latest changes in the `dev` branch require features that aren't yet public in Visual Studio 2017. But, with the rapid pace of Visual Studio 2017 public updates, the wait generally isn't long. We try to avoid doing anything that prevents using the public VS2017, but sometimes it just isn't possible.
