### ISSUE TITLE
Add extension method overloads that take a specific config section to bind to

### ISSUE THREAD

**Issue by danroth27** [aspnet/Security#1246]
By default the authentication components have a default config schema, but you should be able to specify a specific config section to bind to.

**Comment by HaoK** [comment]
Why do we need this?  Call `services.Configure<XyzOptions>(config.GetSection("<yourpath>")`

**Comment by danroth27** [comment]
That works as long as the component uses the default config binder, but not all components do. Ex. I believe the kestrel config is custom. We want a consistent pattern.

**Comment by HaoK** [comment]
Sure but was there something specific in the security repo you were asking about, because all the options for auth work reasonably well with the binder.

If you want a general pattern, I'd recommend something like this:

```
  public class MyOptions {
     public void Bind(IConfiguration config) {
       // Do yo binding.
     }
  }
  
  var config = GetYoConfig();
  services.Configure<MyOptions>(o => o.Bind(config));
```

**Comment by Eilon** [comment]
No plans to do this.
