### ISSUE TITLE
IAuthorizationService somehow incomplete

### ISSUE THREAD

**Issue by frankabbruzzese** [aspnet/Security#1247]
I think the actual definition of `IAuthorizationService `is somehow incomplete, since the `AuthorizeAsync `method handles properly just  in-memory resources. More specifially, if the resource has already been loaded in memory from a DB it may give an answer to all needed authorization queries, but what if one would like to load and page from a DB  just all resources the current user has the permission to read? 

An in-memory test would be inadequate, since it would force loading uneusefull resources in memory(also the ones the user can't read), and would interfere with a LinQ skip/take paging.  

Accordingly, the developer would be forced to spread authorization rules all over the DB queries instead of encapsulating them only into `IAuthorizationHandler `implementations! In other word with the actual implementation the user is forced to break `IAuthorizationHandler  `encapsulation, loosing most of modularity-related advantages of the `IAuthorizationService`/`IAuthorizationHandler  `framework.

The problem I sketched shortly might be solved by adding a new method to `IAuthorizationService `, say something like:

`Expression<Func<T, bool>> AuthorizePredicate<T>(ClaimsPrincipal user, IEnumerable<IAuthorizationRequirement> requirements)`

That would return a LinQ predicate the developer may insert in a LinQ `Where` to filter out all not authorized resources. Clearly, also the `IAuthorizationHandler `should be enriched properly to give the devolper the possibility to define all needed predicates. The predicate returned by `AuthorizePredicate `should be the "logical or" of all predicated provided in all relevant `IAuthorizationHandlers`.

**Comment by davidfowl** [comment]
> Accordingly, the developer would be forced to spread authorization rules all over the DB queries instead of encapsulating them only into IAuthorizationHandler implementations! In other word with the actual implementation the user is forced to break IAuthorizationHandler encapsulation, loosing most of modularity-related advantages of the IAuthorizationService/IAuthorizationHandler framework.

Can you show some examples of what type of logic you want to write int your `IAuthorizationHandler`? Returning a predicate seems awfully coupled to LINQ (which we don't really do in services at this level in the stack). What if you were using a repository or a queries that weren't LINQ based? How does the `IAuthorizationHandler` produce filters for an arbitrary `T`?

**Comment by frankabbruzzese** [comment]
@davidfowl ,
Actually, the problem is just for authorization on resources. Thus `IAuthorizationHandler ` can't contain a method specific for any T since it doesn't contain any generic. It should contain something like: Task `HandlePredicateAsync(PredicateAuthorizationHandlerContext context)`.  The abstract class AuthorizationHandler<TRequirement, TResource> that already contains a generic for the resource type should contain something specific for TResource:

```
HandleRequirementAsync(PredicateAuthorizationHandlerContext context,
                                   OperationAuthorizationRequirement requirement,
                                   TResource resource)
```

Then the developer should provide a concrecte class WITHOUT generics(ie with all generics instantiated) that is specific for a single concrete resource.

On the other side IAuthorizationService can contain a  AuthorizePredicate<T> method with a generic T that  basically performs just a a cast of an expression that contains all constraints specific for the concrete  type passed as T.

> What if you were using a repository or a queries that weren't LINQ based?

Expression<Func<T, bool>> is not specific for LinQ. It is just a "meta-description" of the code that computes a predicate. It may be used to create a retrieval procedure for any envirnoment. It might be also parsed to get an elastic search json snippet. 
However, one might think also to a different way to encode a predicate, such as the one used by the OData library.

I admit the overall idea is not very "elegant". However, resource handlers should encapsulate all logics to verify authorization, but in all pratical applications resource are contained in store external to the program (db, not sql dbs, redis, etc.) so the authorization framework should somehow contain logics to interact also with external data structures. Otherwise, the overall authorization logics can't be encapsulated in the authorization framework, which, in turn, would make the part of the authorization framework that is specific for resources, quite uneusefull: "partial encapsulations" usually do not offer valuable advantages.

The solution I propose is not necessarely the best one but the problem I raise exists and should be adressed somehow.


In a few days I'll provide a pratical  example of what I have in mind.

**Comment by frankabbruzzese** [comment]
Maybe, the difficulty of encapsulating completely Authorizations on a resource in a presentation layer framework depends on resource authorizatins being business layer stuffs. 

Maybe, Authorization on resources in asp.net is not an useful stuff. Developer should handle authorizations on resources in the business layer with the same tools they use to interact with the persistence layer. The presentation layers should receive DTO already containing information on the allowed operations for the current user.

**Comment by Eilon** [comment]
Moving this to discussions. We generally recommend policies and authorization to be done below the UI/presentation layer, aside from just basic visibility logic, but leaving this issue open to monitor discussions about more concrete examples.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
