### ISSUE TITLE
No authentication handler is configured to handle the scheme: Automatic

### ISSUE THREAD

**Issue by Vakterman** [aspnet/Security#1251]
I have some issue like [this](https://github.com/aspnet/Security/issues/967), but i can't understand how to solve it for Debian.

At first, i configure my application as described below
 
```
app.UseCookieAuthentication(new CookieAuthenticationOptions
				{
					AuthenticationScheme =MyAuthSchemeName,
					CookieName = MyCookiName,
					AutomaticAuthenticate = true,
					AutomaticChallenge = false,
					SlidingExpiration = true,
					ExpireTimeSpan = TimeSpan.FromDays(1),
					DataProtectionProvider = DataProtectionProvider.Create(MyApplicationName)
				});

	app.UseJwtBearerAuthentication(new JwtBearerOptions
				{ 
					AutomaticChallenge = false,
					AutomaticAuthenticate = true,
					Authority = IdentityServerConnectionString,
					RequireHttpsMetadata = false,
					BackchannelHttpHandler = new HttpClientHandler().ServerCertificateCustomValidationCallback = (request, cert, chain, errors) => true,
					TokenValidationParameters = new TokenValidationParameters
					{
						ValidateAudience = false,
						ValidateIssuer = false,
					}
				});

	app.UseMvc();
```

For windows it works perfectly (I use  Host for launching this code, not IIS !), but for Debian  it fails.
Could you provide any solution?

**UPD:** I see next message in logs:  Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware MyAuthSchemeName was not authenticated. Failure message: Unprotect ticket failed

**Comment by Tratcher** [comment]
What action caused that error message, Challenge? You have AutomaticChallenge disabled on both middleware.

It's not clear why you're mixing cookies and Jwt

**Comment by Tratcher** [comment]
Note this works in IIS/Express because IISMiddleware is present and it always assumes windows auth is enabled and sets 401s. If you were to run this on windows without IIS/Express you'd see the same error.

**Comment by Vakterman** [comment]
Hi, Tratcher!
Thank you for your answer. 
Yes, that error  message caused by Challenge
I run it as host both for Windows and Linux, but i don't see this problem for windows. And it's not a problem.
I catch it on Linux virtual machine. Call stack is provided below

Microsoft.AspNetCore.Server.Kestrel Connection id "0HL5DN1G84KD7": An unhandled exception was thrown by the application. System.InvalidOperationException: No authentication handler is configured to handle the scheme: Automatic
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<ChallengeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.<ExecuteResultAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Security/issues/1062

**Comment by Vakterman** [comment]
It was very intresting, but it doesn't work for me.
Or i don't understand something. 
I tried to set AutomaticChallenge to true for Coockie. 
But nothing to happen

**Comment by Vakterman** [comment]
I found solution for this issue. Key cause is a settings of DataProtectionProvider. For Debian it's needed to use code below

Startup.cs :

public void ConfigureServices(IServiceCollection services)
    {
      services.AddDataProtection().SetApplicationName(ApplicationName).
               PersistKeysToFileSystem(
                    new DirectoryInfo(Configuration["/some_path_to_folder_for_keys"]))
    }
And dataprovider initialization should be removed for cookie (from UseCookieAuthentication());

**Comment by Eilon** [comment]
Closing because it looks like you got this working.
