### ISSUE TITLE
Consider removing AuthenticationSchemeOptions.Validate()

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#1257]
@HaoK is there any particular reason to have a virtual `Validate()` method in `AuthenticationSchemeOptions` now that we have post configuration initializers?

**Comment by HaoK** [comment]
We wanted Validation to run on every request unlike options which are only run once or on changes.

**Comment by PinpointTownes** [comment]
@HaoK hum, what's the point of doing that? We only need to validate the options once, no? (once per options instance).

**Comment by HaoK** [comment]
Well options can certainly change between requests for example binding against config which is coming back in some form in 2.1.

**Comment by PinpointTownes** [comment]
But in this case, isn't `OptionsSnapshot` supposed to re-run the post configuration initializers?

**Comment by HaoK** [comment]
Yes but we decided to not try and tackle validation in options itself for 2.0. And while we could have tried to stick it in a PostConfigure we'd again be dealing with trying to make sure it ran last. 

Plus given that our options classes are mutable it doesn't seem that harmful to validate every time as snapshots don't prevent anyone from mutating the options instances directly.

**Comment by PinpointTownes** [comment]
> And while we could have tried to stick it in a PostConfigure we'd again be dealing with trying to make sure it ran last.

Well, is it really a problem? Post configuration initializers are meant to be invoked when the options are "almost" ready to be used. In a way, they should be regarded as "options validators" (which would be a way better name, but whatever :sweat_smile:).

> Plus given that our options classes are mutable it doesn't seem that harmful to validate every time...

It's not harmful, it just runs unnecessary validation routines for each handler/request :sweat_smile: 

> As snapshots don't prevent anyone from mutating the options instances directly.

Well, the most common (bad) way to mess up the options is to alter them from an event.
In this case, your `Validate()` won't be helpful at all as it won't detect that.

**Comment by HaoK** [comment]
Well today we use them to set defaults for required things that would fail validate otherwise. So order would matter :). Most of the validations are just null checks today I believe. 

Validate actually would eventually detect event driven modifications just on the next call to that scheme which should be enough to warn them that they are doing something very wrong.

**Comment by Eilon** [comment]
I think per @HaoK 's comments, if & when Options gains the full feature for doing this, we would start using that, but until then, we think it's valuable to have this check to prevent certain common types of errors. It certainly doesn't do all error checks for all possible cases, but we think it still has value. The current default built-in checks are quite cheap, so the cost of doing them on every request should be trivial.
