### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by risogolo** [aspnet/Security#1258]
Is it possible to authorize a method inside a controller which is manually instantiated with Authorize attribute, was not instantiated within HTTP pipeline. Now it looks like this part of this logic is skipped somehow. How do I have to create an instance of controller with all properties properly instantiated to make the authorization/authentication work properly. 
Reason: I'm trying to reuse MVC controller logic, which has been already written for communicating and make it work via web sockets, so I want to route messages to controller methods (some routinf class based on some rules), and I need then to authorize inside the controller ideally. Then covert result via some adapter to create message supported by custom protocol and sent it back via web sockets.

**Comment by Tratcher** [comment]
MVC does a lot more than just new up controllers. The piece you're missing here is the authorization filter that runs before each action if the Authorize attribute is present.
https://github.com/aspnet/Mvc/blob/rel/1.1.3/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs

In 2.0 (dev) more of this has been extracted to a common source in this repo.
https://github.com/aspnet/Mvc/blob/c27b07ef3f8b07dfe1d1de38a8d7bf2d6a9298f4/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs

**Comment by risogolo** [comment]
No I don't think is that, I'm having all the necessary middleware registered using Identityserver4 (everything works fine for standard MVC scenario), the problem is when I created new instance of Controller manually (kind of hack) new SomeController() and that controller has decorated methods with Authorize attribute, then this attribute seems to be skipped or not evaluated.

**Comment by Tratcher** [comment]
Newing up a class and calling its methods does in .NET does not trigger any form of attribute execution. Attributes are just metadata. See that the AuthorizeAttribute contains no meaninful code to execute: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authorization/AuthorizeAttribute.cs

It's MVC that adds the functionality to inspect for attributes and take actions based on their presence and parameters.

**Comment by Eilon** [comment]
Per @Tratcher 's comment, it is not supported to manually instantiate MVC controllers. If you do, it's not MVC anymore - it's simply a class with methods on it.

To run MVC's filter attribute, such as for authorization, the controller must be created and run by MVC itself.
