### ISSUE TITLE
Stop logging any PII

### ISSUE THREAD

**Issue by mattmazzola** [aspnet/Security#1259]
Currently the JwtBearerMiddleware logs success or failure of authorization and token validation as seen in the below locations:

"Authorization was successful for user: {UserName}."
https://github.com/aspnet/Security/blob/22d2fe99c6fd9806b36025399a217a3a8b4e50f4/src/Microsoft.AspNetCore.Authorization/LoggingExtensions.cs#L18
Call to: _logger.UserAuthorizationSucceeded(GetUserNameForLogging(user));
https://github.com/aspnet/Security/blob/e940cdb36bc7617af3d762ff9cc853a8fef55b0a/src/Microsoft.AspNetCore.Authorization/DefaultAuthorizationService.cs#L101
 
"Failed to validate the token {Token}."
https://github.com/aspnet/Security/blob/22d2fe99c6fd9806b36025399a217a3a8b4e50f4/src/Microsoft.AspNetCore.Authentication.JwtBearer/LoggingExtensions.cs#L19
Call to: Logger.TokenValidationFailed(token, ex);
https://github.com/aspnet/Security/blob/e940cdb36bc7617af3d762ff9cc853a8fef55b0a/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L122

For our particular usage of this middleware we don't want to be liable for this PII data in our logs.

In other libraries such as ADAL (Active Directory Authentication Library) which also deal with tokens they hash the token and username so that they are still unique within the logs to allow metrics of particular user without identifying them or exposing token.

See example of hashing:
`string accessTokenHash = PlatformPlugin.CryptographyHelper.CreateSha256Hash(result.AccessToken);`
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/8f6d560fbede2247ec0e217a21f6929d4375dcaa/src/ADAL.PCL/Flows/AcquireTokenHandlerBase.cs#L351

In the future versions perhaps this PII is hashed by default to match behavior of other microsoft libraries, but for backwards compatibility perhaps add new flag to the `JwtBearerOptions` class that's used to configure the middleware's logging such as:

```
var options = new JwtBearerOptions
{
  ...
  HashPersonallyIdentifiableInformation = true
};
```
And the logging would then be:

"Authorization was successful for user: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855."
Instead of:
"Authorization was successful for user: johndoe@microsoft.com."

**Comment by HaoK** [comment]
We will be removing all PII from log messages instead of adding an option

**Comment by mattmazzola** [comment]
Great!

To clarify, when you say 
> removing all PII from log messages 
By 'removing' does this mean you will be hashing the PII data within the log messages so it is unique but not personally identifiable or are you removing the data from logs completely?

**Comment by HaoK** [comment]
Just removing username from the log message, it'll just say Authorization was successful, or failed.

**Comment by mattmazzola** [comment]
This issue was about more than just the user name and the "Authorization was successful" message. The new title is misleading. I referenced 4 unique places which different types of data, most importantly is the token as this allows people with access to logs to impersonate the user.

**Comment by HaoK** [comment]
Fair enough, I'll change the title to removing all PII from logs

**Comment by PinpointTownes** [comment]
> We will be removing all PII from log messages instead of adding an option

That's a bad idea, which will make debugging more painful than it already is.

Instead, consider changing the log level of the messages containing personal information to `Trace`, which is made for that.

**Comment by mattmazzola** [comment]
I disagree with using log level as a solution. Changing the log level affects the entire message not just the parts of it that are PII.  People will still expect to see the non-PII portion such as "Authentication successful" to be logged in normal `Informational` or `Debug` levels. 

I don't really think this should be up for debate though. I expect all libraries from the entire aspnet GitHub organization to follow the same patterns.  There should be standard procedure for handling all PII data and not having each different package maintainer deciding if it should be removed completely, hashed, or changed log level.   Given that other Microsoft libraries use hash I believe this is the best solution.

**Comment by PinpointTownes** [comment]
> People will still expect to see the non-PII portion such as "Authentication successful" to be logged in normal Informational or Debug levels.

Nothing prevents splitting the existing `Information` message into two new logs: an informational one containing no PII and a trace one containing sensitive data.

> Given that other Microsoft libraries use hash I believe this is the best solution.

I doubt that giving a single example is enough to pretend that, I'm afraid. Here are two projects that don't use the hashing method you suggest:

  - IdentityModel, developed by the Azure AD team (that also develops ADAL): it's the perfect counterexample as it even includes sensitive things like the tokens themselves in its exception messages/log traces.

  - EntityFramework Core: it doesn't include query parameters in logs by default, but it offers an `EnableSensitiveDataLogging()` option that can be used to easily include them.

> Also, if you're saying it will make debugging painful please explain why otherwise it's just your opinion.

As someone who has to deal with that every day, I like to think that my opinion counts, just like yours... :trollface:

Not including super basic things like the username makes debugging painful because it's way harder to re-create the conditions that caused the request to fail and determine _why_ it failed. If you don't have the user identifier, you can't verify whether he or she has the right permissions or the correct roles in your DB, etc. It would be like trying to determine why all your unit tests using `Assert.Equal` fail without even knowing what the expected and actual values are...

Actually, I wish the authorization stack logged more data by default. It should at least log the requirements that were not satisfied, and ideally why there were not satisfied (e.g the claims requirement could log both the expected value and the actual value while the roles requirement could mention the missing role).

**Comment by Tadimsky** [comment]
Is there any update on this? We're currently logging both Token and UserName due to this.

**Comment by HaoK** [comment]
@blowdart any updates from legal?

**Comment by blowdart** [comment]
Of course not. So, it is what it is, we should/will not log anything PII related, in plain texts, or in hashes (because meta-data can still be considered PII in some circumstances), users can choose to add extra logging.

**Comment by HaoK** [comment]
So we are good to go on https://github.com/aspnet/Security/pull/1478 ?

**Comment by blowdart** [comment]
Yes, LGTM

**Comment by HaoK** [comment]
Was there anything else other than the token/username that you wanted removed from the logs?

**Comment by mattmazzola** [comment]
This feels like it's taking the easy solution instead of the best.  There is value in the information and I think exposing some configuration for the developer would be better, but given that it's not clear how to do this and complexity is much higher for all the scenarios I could understand going forward with the safe solution of removing everything.

> users can choose to add extra logging.

If you're passing this responsibility on to the developer, please make sure to document a recommended place to do this since some applications may have been relying on these logs in 1.x and want to preserve similar behavior when migrating to 2.x.  

Since the logging code written by dev would be outside the JwtBearerMiddleware it doesn't have the same context.  I assume developer would have to add their own middleware before and after JwtBearerMiddleware.  The middleware before has to look at exceptions and check if it was due to auth exception, and the middleware after would be making assumption that auth succeeded.  This seems a bit sloppy

> Was there anything else other than the token/username that you wanted removed from the logs?

Not that I'm aware of although I think there is open documentation about what qualifies as identifiable information whether it is personal, organizational, etc...

**Comment by Tratcher** [comment]
The JwtBearerMiddleware events could also be used for dev logging, they would give you almost all of the context.

**Comment by Tadimsky** [comment]
Is this fix going to be backported to 2.0 or is it only going into 2.1?

**Comment by Eilon** [comment]
The change is only in 2.1.0. No plans to port this to any other releases.

**Comment by Tadimsky** [comment]
@Eilon what is the best way to remove these logs then if we're not on 2.1?
Filter out all logs for JwtBearer?
Or else, when is 2.1 going to RTM?

**Comment by Eilon** [comment]
2.1 RTM is planned for the current quarter (2018 Q2), which is April/May/June, so it shouldn't be too far away.

The logging system does support filtering so if you need the change immediately you can write a logging filter that strips out certain logs.

**Comment by Tadimsky** [comment]
Yeah, I was hoping to do it with minimum levels for different contexts.
However, this is being logged as Information with the `Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler` context which is the same level and context as success messages that we do want :(
