### ISSUE TITLE
Authentication failures are not properly logged

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#1265]
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/issues/73#issuecomment-308709255

The fix is simple: `AuthenticationHandler.AuthenticateAsync()` should be updated to log the authentication failure when it's not null: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L133

Note: the issue exists in both 1.0/1.1 and 2.0 but it's more terrible in 2.0 because it also manifests when enabling automatic authentication (1.0/1.1 correctly log the failure in this case: https://github.com/aspnet/Security/blob/1.0.0/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L107)

/cc @HaoK

**Comment by PinpointTownes** [comment]
@Eilon can you please make sure it gets fixed for 2.0 by adding the appropriate milestone/label?
It makes debugging ultra painful.

**Comment by muratg** [comment]
Fixed with https://github.com/aspnet/Security/commit/66b939725ed6d1b4eb8ce5d4823b635990c086b4

**Comment by NinoFloris** [comment]
Ah thanks @PinpointTownes I was just scratching my head for an hour why I wouldn't get a valid ClaimsIdentity, all along our auth handler was returning failures... Great to see this fixed!
