### ISSUE TITLE
Remove top level methods on IServiceCollection that configure authentication

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Security#1269]
`services.AddScheme` is too general of a name to put on the top level container:

![image](https://user-images.githubusercontent.com/95136/27261329-d09ab052-53f5-11e7-8bc6-a525d4841819.png)

Is it even meaningful to add a scheme without adding the authentication service? Why isn't it an extension method off on an `IAuthenticationBuilder` or something similar.

```C#
services.AddAuthentication()
              .AddScheme(...)
```

**Comment by HaoK** [comment]
Not a bad idea to switch to a builder pattern.  Do we want to move everything under, i.e.?

`services.AddAuthentication[Core]().AddScheme/Xyz()`

**Comment by HaoK** [comment]
So something like:
`Authentication.Core`  has `void services.AddAuthenticationCore()` // unchanged
`Authentication` has `AuthenticationBuilder services.AddAuthentication()`
Authentication.Xyz` => `AuthenticationBuilder.AddXyz()`

**Comment by davidfowl** [comment]
I was also thinking we should hang the services like cookie, jwt, etc off the builder.

services.AddAuthentication()
              .AddCookies(...);

**Comment by HaoK** [comment]
Yup that's what I meant with the AddXyz.
