### ISSUE TITLE
Shared AuthorizeAttribute

### ISSUE THREAD

**Issue by halter73** [aspnet/Security#127]
We should create a new metadata-only `AuthorizeAttribute` in `Microsoft.AspNet.Security` that will be respected by both MVC and SignalR.

This attribute will implement an interface (`IAuthorizeMetadata`?) that will have a single `Policy` property. We are considering whether or not this attribute should be sealed.

Optional framework-specific metadata can be attached to separate interfaces. For example, SignalR can have it's own `HubAuthorizeAttribute` that will implement an additional interface that includes the `RequireOutgoing` property. However, using the shared `AuthorizeAttribute` should be sufficient for most use cases.

**Comment by HaoK** [comment]
Added in 5094b85ac92df0035f15e94b87d72cd4bc716905, still need to update SignalR to consume
