### ISSUE TITLE
JwtBearerAuthentication throwing exception on Authorize when hosted in Azure

### ISSUE THREAD

**Issue by fuocor** [aspnet/Security#1271]
I have JwtBearerAuthentication (2.0.0-preview3-25813) working flawlessly in locally but it is throwing exception on Authorize when hosted in Azure.

`System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.
   at Microsoft.AspNetCore.Authentication.AuthenticationService.<ChallengeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
`

Attached is the startup code I use
[Startup.txt](https://github.com/aspnet/Security/files/1089976/Startup.txt)

Any help is appreciated

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/blob/879f0b7f4053a34b44e34bd22c788c6129115175/samples/JwtBearerSample/Startup.cs#L47-L51

**Comment by fuocor** [comment]
Thanks, but it begs the question as to why it works locally on kestrel?
