### ISSUE TITLE
Passing in an AuthoritizationPolicy allocates an array everytime

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Security#1274]
https://github.com/aspnet/Security/blob/879f0b7f4053a34b44e34bd22c788c6129115175/src/Microsoft.AspNetCore.Authorization/AuthorizationServiceExtensions.cs#L65

It would be great if there was a way to avoid this allocation per call. `AuthorizationPolicy` already has an `IReadOnlyList<Requirements>` https://github.com/aspnet/Security/blob/879f0b7f4053a34b44e34bd22c788c6129115175/src/Microsoft.AspNetCore.Authorization/AuthorizationPolicy.cs#L52, yet we allocate a mutable array every time we need to check if a user is authorized.

/cc @HaoK

**Comment by HaoK** [comment]
80383606d3988095abb74ff726439261f168ce43
