### ISSUE TITLE
ClaimActions.DeleteClaim in OpenIdConnectOptions

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#1276]
Will an entry in DeleteClaim result in removal of the claim from the ClaimsIdentity?
If so, we may want to consider keeping, amr and acr. 
Some of the claims, such as 'nonce' have little value one the OIDC message has been validated. 
amr and acr are not used to validate the message and may be of interest to the application layer.

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L54

**Comment by Tratcher** [comment]
Yes, that's what it's for.  amr and acr are both optional. Are they actually implemented by AAD, ADFS, Google?

**Comment by brentschmaltz** [comment]
@Tratcher these claims {amr, acr} can be of interest to the application layer. So I wouldn't remove them by default.

The others seem fine.
