### ISSUE TITLE
Question about: ClaimActions.MapUniqueJsonKey("sub", "sub");

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#1277]
I am wondering what the effects of MapUniqueJsonKey to understand how is will interact with mappings inside IdentityModel

**Comment by Tratcher** [comment]
MapUniqueJsonKey is used for pulling claims from the user-info endpoint but avoiding duplication with claims already added from the IdentityModel processing.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
