### ISSUE TITLE
Claims and HTTP 431

### ISSUE THREAD

**Issue by shishir28** [aspnet/Security#1278]
Has the support for ClaimsTransformation been dropped from ASP.NET Core 2.0 ? If yes , what is the best way to maintain cookie based authentication and avoid HTTP 431?

**Comment by HaoK** [comment]
Claims transformation is still there, you just directly add it to the container:

See https://github.com/aspnet/Security/blob/dev/test/Microsoft.AspNetCore.Authentication.Test/GoogleTests.cs#L1049

**Comment by shishir28** [comment]
Thank You. Was looking at wrong place.
