### ISSUE TITLE
multitenancy authentication

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Security#1280]
I'm trying to use OpenidConnect with a multitenant aspnetcore application; but I'm unable to find how I can setup the middleware properties at runtime from a repository based of the host address from with in the httpcontext ? any guidance would be great

**Comment by Tratcher** [comment]
There's no way to do this in 1.x, but it may be possible with the new infrastructure in 2.0.

**Comment by RickBlouch** [comment]
I have this working in 1.1 with saaskit, unless I am misunderstanding your ask.

https://github.com/saaskit/saaskit

**Comment by HaoK** [comment]
You can take a look at https://github.com/aspnet/AuthSamples/tree/dev/samples/DynamicSchemes which is the sample for how you can add/remove/configure auth dynamically at runtime
