### ISSUE TITLE
Why does RemoteAuthenticationHandler.CorrelationMarker have a value of "N"?

### ISSUE THREAD

**Issue by TheCloudlessSky** [aspnet/Security#1286]
According to bbcabc0212a298ec5d30ed7f25aa9ee40c511a20, the way the cookies are created for OAuth 2 CSRF protection was changed. It introduced `CorrelationMarker = "N"`. Where does the value of `N` come from? I know that the cookie needs a value, but why was this value chosen?

**Comment by Tratcher** [comment]
The unique value was moved into the cookie name to avoid collisions for concurrent flows. The N value is just a placeholder that we copied from OIDC's nonce cookie.
https://github.com/aspnet/Security/commit/bbcabc0212a298ec5d30ed7f25aa9ee40c511a20#diff-fc6866236621c72eb7137090f51af9b8R132

**Comment by TheCloudlessSky** [comment]
@Tratcher Thanks for the explanation. From your diff, I assume you're talking about `OpenIdConnectHandler.NonceProperty`? Do you know why that value was chosen to be `N` (does it just represent "**N**once")? The reason I ask is that I'm implementing OAuth 2 CSRF in an MVC 5.2.3 application and want to model it how ASP.NET Core is doing it. So, I've been digging through the source and want to make sure I understand why things are the way they are.

**Comment by Tratcher** [comment]
Yes, it just stands for Nonce. Any value will do.

**Comment by TheCloudlessSky** [comment]
Great, thanks!
