### ISSUE TITLE
Retrieve PUID using MicrosoftAccount authentication

### ISSUE THREAD

**Issue by InDieTasten** [aspnet/Security#1288]
Migrating from a legacy system that was identifying users using PUID, how can I associate users coming from the new middleware `Microsoft.AspNetCore.Authentication.MicrosoftAccount` to their respective PUID?

When I check, the nameidentifier claim is different from the old PUID, right?

I've been looking for a couple hours now and still don't have much of a clue, because the entire authentication stuff, live id connect, all the AD stuff has been evolving so much that articles on PUID, that are  still correct, are hard to find for me.

Thanks

**Comment by InDieTasten** [comment]
Ok, after some more research, I think it's safe to say that PUID officially died and only RPS server can access this property/claim.

I will now migrate users using their live email address. I would still like to get confirmation for that conclusion I've drawn regarding PUID.

Thanks

**Comment by Eilon** [comment]
cc @vibronet to comment on PUID.

**Comment by InDieTasten** [comment]
Is there any hope to get an answer. It's been a while and this is still relevant to me

**Comment by Eilon** [comment]
@InDieTasten I sent another email to see if we can get someone to help with this.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.

**Comment by InDieTasten** [comment]
Can you please reopen this and not add Discussion label? And fix that bot to close issues after 2 months of silence, jeez

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
