### ISSUE TITLE
Can't override AuthorizationAttribute's ActiveAuthenticationSchemes

### ISSUE THREAD

**Issue by Mardoxx** [aspnet/Security#1291]
Let's say I have two authentication schemes, one that is default `AuthenticationScheme = "Bearer"` and another is `AuthenticationScheme = "Bearer2"` with `AutomaticAuthenticate = false`

My controller is similar to this

```
[Authorize]
public class SomeController {
    public IActionResult SomeMethod() {
        // Auth'd based on "Bearer"
    }
    
    [Authorize(ActiveAuthenticationSchemes = "Bearer2")]
    public IActionResult SomeOtherMethod() {
        // Should be auth'd with Bearer2
        // However we get a 403 presumably due to "Bearer" being still active
    }
}
```

Is there an elegant way of doing this? One solution is to decorate all my actions instead of at the controller level - but I want to avoid this -- more to forget to do when someone adds a new action.

**Comment by Tratcher** [comment]
@HaoK @rynowak? I would expect the Action's attribute to take precedence. Or are they both running?

**Comment by rynowak** [comment]
`[Authorize]` doesn't override, they all run. AFAIK that is the legacy behavior

**Comment by PinpointTownes** [comment]
That's precisely one reason why I believe `[Authorize]` should be linked to authentication.

https://github.com/aspnet/Security/issues/1199#issuecomment-299273255

**Comment by Mardoxx** [comment]
@rynowak was this changed just for the sake of changing it?

Feels much better to look at the attributes on the actions and be like "oh this one uses Bearer and Bearer2, this other one uses just Bearer". Rather than... "this one Uses just Bearer2... oh wait no if we scroll up a few hundred lines to the controller's root it also uses Cookie scheme".

**Comment by HaoK** [comment]
Yeah the authorize attributes are all combined into one mega policy

**Comment by Mardoxx** [comment]
I'd really have expected them to override. I have my policies in their own classes and they are already in order of increasing permissivness, I wouldn't expect the code to do combination magic for me.

Poor example, if I have a SiteStats controller that is only for admins (class is decorated with Auth attr) and then there becomes a requirement for normal users to access some of these, what now? I have to add the same Auth attribute to every action instead of just adding it to certain actions to override.

Doesn't AllowAnonymous work in a similar way, ignoring implementation details, where you have an Auth controller then AllowAnon on acton overrides (disables) Auth policies?

**Comment by PinpointTownes** [comment]
> @PinpointTownes and helps train people that Authentication and Authorization are different things!

The hard part would be convincing @blowdart that the "average developer" is not as stupid as he can imagine :trollface:

**Comment by Eilon** [comment]
This feature would likely end up being implemented in MVC, but keeping the bug here for now until we settle on a design.

**Comment by davidfowl** [comment]
We'll tackle this as part of https://github.com/aspnet/Security/issues/1359
