### ISSUE TITLE
Remove obsolete cookie options API

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Security#1292]
Follow up to https://github.com/aspnet/Security/pull/1285

Remove these obsoleted API in the next major release
```
CookieAuthenticationOptions
  .CookieName
  .CookieDomain
  .CookiePath
  .CookieHttpOnly
  .CookieSecure

```
~~.ExpireTimeSpan~~ - https://github.com/aspnet/Security/pull/1296

**Comment by Tratcher** [comment]
Not ExpireTimeSpan: https://github.com/aspnet/Security/issues/1293

**Comment by muratg** [comment]
@HaoK forgot to close this one? :)
