### ISSUE TITLE
AuthenticationHandler should throw if UseAuthentication wasn't called

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#1301]
Add logic in our base AuthenticationHandler IAuthenticationService methods to throw if UseAuthentication wasn't called by checking if IAuthenticationFeature has been set.

We should do this anywhere we use the feature instead of defaulting (i.e. CookieSlidingExpiry)

**Comment by Eilon** [comment]
Because we haven't done this yet, let's close it.
