### ISSUE TITLE
Removing vs Deprecating the old AuthN APIs

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#1305]
We started porting IdentityServer4 to ASP.NET Core 2.0 - it's a mess ;)

I personally would prefer you to remove the old deprecated classes and extension methods - like `UseCookieAuthentication`, `AuthenticationManager` etc..

I also get ambiguous references for `AuthenticationProperties`.

Removing them would make that much clearer - especially with the new .All package where everything shows up everywhere.

**Comment by brockallen** [comment]
If the reason is to allow easy migrations from 1.x to 2.0, but it's not technically supported, then what's the point? 

+1 to ripping off the band-aid.

**Comment by Eilon** [comment]
The migration guide from ASP.NET Core 1.1 to 2.0 will include information that assists with the migration. The content includes removing references to the previous namespace, which would mitigate this issue.

Here are some links to the in-progress migration documentation:
* Issue tracking the migration doc work: https://github.com/aspnet/Docs/issues/3548
* Migration doc PR in-progress: https://github.com/aspnet/Docs/pull/3768
* Preview page of the content: https://review.docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x?branch=scottaddie%2Fmigrating-to-2x

**Comment by Eilon** [comment]
Oh I forgot to add: One reason we kept the old methods was to have a place to put Obsolete messages, to help guide the developers to the migration doc. The obsolete messages include a link to the doc. We didn't obsolete every single type but instead chose to obsolete the key entry points.
