### ISSUE TITLE
Update Google API version to v2

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1307]
https://github.com/aspnet/Security/blob/df325deaf355f99239c1319932bc28eb3a837372/src/Microsoft.AspNetCore.Authentication.Google/GoogleDefaults.cs
https://developers.google.com/identity/protocols/OAuth2WebServer
AuthorizationEndpoint = "https://accounts.google.com/o/oauth2/auth"; => "https://accounts.google.com/o/oauth2/v2/auth"

https://developers.google.com/+/web/people/

https://github.com/aspnet/Security/issues/92

**Comment by d-saravanan** [comment]
Can I take up this task and do it
