### ISSUE TITLE
Google external authentication fails to authenticate

### ISSUE THREAD

**Issue by wgrs** [aspnet/Security#1309]
I am trying to get aspnetcore identity to work with version 1.12.  When calling _signInManager.ExternalLoginSignInAsync the result returns Failure. However, if I downgrade all the necessary packages to 1.0.2, the external login is authenticated correctly. What changes need to be made to get things working with AspnetCore.Authentication.Google 1.12 ?

**Comment by Tratcher** [comment]
1.12? Do you mean 1.1.2?

**Comment by wgrs** [comment]
Yes, sorry 1.12

**Comment by Tratcher** [comment]
I'm not aware of any changes required. What's the error?

**Comment by wgrs** [comment]
I'm not sure on how to access further details - the result to ExternalLoginSignInAsync just returns a Fail result

**Comment by Tratcher** [comment]
Run it under the debugger? Or turn on application logging?

**Comment by wgrs** [comment]
OK - logging revealed the authentication was successful - seems the issue is elsewhere... thanks
