### ISSUE TITLE
Question: How to access configured CookieAuthenticationOptions in controller/view/etc

### ISSUE THREAD

**Issue by NielsKruse** [aspnet/Security#1312]
Purpose: I want to redirect razor pages to the configured LoginPath if no authenticated user is found.

I add cookie authentication to the services in startup.cs...
```csharp
            .AddCookie(Core.Security.Schemes.Cookie.Name, o => //CookieAuthenticationDefaults.AuthenticationScheme
            {
                o.CookieName = ".nktest.Authentication";

                o.ReturnUrlParameter = "returnUrl";
                o.CookieHttpOnly = true;
                o.CookieSecure = CookieSecurePolicy.SameAsRequest;
                o.SlidingExpiration = true;
                o.ExpireTimeSpan = TimeSpan.FromMinutes(60);

                o.AccessDeniedPath = new PathString("/Authentication/AccessDenied");
                o.LoginPath = new PathString("/Authentication/Login");
                o.LogoutPath = new PathString("/Authentication/Logout");
            })
```

Now, on the razor page model (seprarate file), I add the following, amongst others, to the constructor...

```
MyModelCtr(..., IOptions<CookieAuthenticationOptions> cookieAuthenticationOptions,
IOptions<AuthenticationOptions> authenticationOptions,
IOptions<JwtBearerOptions> jwtBearerOptions,...)
```
It seems that the AuthenticationOption inject properly as configured, but that the CookieAthenticationOptions (and the JwtBearerOption for that matter) get a new instance with only the default settings.

When accessing the LoginPath from the injected CookieAuthenticationOptions, I simply get the default "/Account/Login" instead of my configured "/Authentication/Login".

I even injectd the IPostConfigurationOptions<CookieAuthenticationOptions> to see what all that's about, but did not really make any progress.

Any hints / ideas / pointers?

**Comment by Tratcher** [comment]
Resolving the new IAuthenticatonService would make more sense here.

But rather than look up the value manually, why not invoke an authentication challenge? @danroth27 is that thing for razor pages?

**Comment by NielsKruse** [comment]
Returning Challenge works in that particular context. Thanks for pointing me towards it.


More generally, though,... if I wanted to read the configured CookieAuthenticationOptions (for whichever purpose - maybe simply for display), how would I do that in a controller or view?

I thought they'd be available via DI.
For example...
```csharp
    public class MyController : Controller
    {
        private CookieAuthenticationOptions _cookieAuthenticationOptions;

        public MyController(IOptions<CookieAuthenticationOptions> cookieAuthenticationOptions)
        {
            _cookieAuthenticationOptions = cookieAuthenticationOptions.Value;
        }
```
.. but that only gives me what looks like a new instance of the options, not my actual settings.

In the service collection (inspected at the end of startup) I have this
Lifetime = Singleton, ServiceType = {Microsoft.Extensions.Options.IConfigureOptions`1[Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationOptions]}, ImplementationType = null


btw... if I'm posting this in the wrong section, please let me know

**Comment by PinpointTownes** [comment]
@NielsKruse in 2.0.0-preview3/rtm, you'd have to use `IOptionsMonitor<CookieAuthenticationOptions>` (if you're still using preview2, use `IOptionsSnapshot<CookieAuthenticationOptions>` instead):

```csharp
public class MyController : Controller
{
    private CookieAuthenticationOptions _cookieAuthenticationOptions;

    public MyController(IOptionsMonitor<CookieAuthenticationOptions> options)
    {
        _cookieAuthenticationOptions = options.Get(Core.Security.Schemes.Cookie.Name);
    }
}
```

**Comment by NielsKruse** [comment]
@PinpointTownes Thanks a lot. Particularly for including the code snippet. Without it (without using the Get function), I would have used "options.CurrentValue", which would have pointed to the default scheme. I am on preview 3 and getting somewhere by googling is next to impossible.

**Comment by PinpointTownes** [comment]
> I am on preview 3 and getting somewhere by googling is next to impossible.

Would you be interested if I wrote a blog post about the new options changes in the security stack? It's more complicated than before, but there are cool things you can now do w.r.t multi-tenancy.

**Comment by NielsKruse** [comment]
@PinpointTownes I think I speak for tons of people when I say "yes, any posted information on the current state of the security stack would be hugely appreciated" ^^
Some of the problems I ran into were due to me wanting to build things from scratch and deliberately changing various default settings to see what happens.
As I next step, I want to implement multiple auth providers (facebook, MS, github, etc) to see how that's done now.

**Comment by Eilon** [comment]
Looks like we can close this.
