### ISSUE TITLE
Add logging scope for auth flows

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Security#1317]
We can scope help diagnosing authentication issues by correlating multi request auth flows.

/cc @PinpointTownes

**Comment by PinpointTownes** [comment]
Sounds like a very good idea . For that, I presume you'd store a correlation identifier in the `AuthenticationProperties` of the correlation/anti-forgery cookie?

**Comment by davidfowl** [comment]
@PinpointTownes yep!

**Comment by Eilon** [comment]
Closing because we don't feel this would add sufficient information to aid in most debugging scenarios that we've seen people run into.
