### ISSUE TITLE
HttpContext.User.Identity.IsAuthenticated is false after successful sign in with Cookies.

### ISSUE THREAD

**Issue by lachis** [aspnet/Security#1318]
I'm using the new .Net Core 2.0 Preview 2 along with Visual Studio Community 2017 15.3 preview. Ive been struggling with this for days, Im not sure if my code is wrong or if this is an actual bug. I successfully sign in a user and receive the following message in output `Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler:Information: AuthenticationScheme: Cookies signed in.`. However when debugging, immediately after sign in i check `HttpContext.User.Identity` for my identity i created for the user. It doesnt exist and the user is not authenticated.

My ConfigureServices method:

      public void ConfigureServices(IServiceCollection services)
      {
             services.AddCookieAuthentication(options =>
             {
                  options.LoginPath = "/Auth/GetAuth";
                  options.LogoutPath = "/Auth/Logout";
             });
            services.AddAuthorization();
            services.AddSingleton<ISpotifyService, SpotifyService>();
            services.AddMvc();
     }

and inside my Configure method i called:
`app.UseAuthentication();`

My login method inside my AuthController

        private async Task Login(SpotifyPrivateProfile profile, string spotifyToken)
        {
            if (!string.IsNullOrWhiteSpace(spotifyToken))
            {

                var iidentity = new Identity();
                iidentity.IsAuthenticated = true;
                iidentity.Name = profile.DisplayName;
                iidentity.Email = profile.Email;
                iidentity.Id = profile.Id;
                iidentity.AuthenticationType = CookieAuthenticationDefaults.AuthenticationScheme;
                var identity = new ClaimsIdentity(iidentity, new[] { new Claim("Token", spotifyToken, "Spotify Token") });
                
                var claimsPrinciple = new ClaimsPrincipal(identity);

                var token = JsonConvert.DeserializeObject<Token>(spotifyToken);
                var time = token.expires_in / 60;
                
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrinciple);
               }
        }

I have a try catch around the login method so it does successfully sign in. I really dont understand why I am unable to access my identity that I just signed in as. Is this a bug or have I done something wrong?

Thanks!

**Comment by Tratcher** [comment]
SignIn persists the given information for future requests, it does not set HttpContext.User on the current one.

**Comment by lachis** [comment]
Thanks for the reply. I will check this (tomorrow morning, just gone to bed)

**Comment by lachis** [comment]
Ok so i checked by looking at HttpContext.User on subsequent requests on login, its still not persisting my identity :(

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/issues/1310
```
services.AddAuthentication(sharedOptions =>
{
  sharedOptions.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
  sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
  // sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
})
```
This will get a bit cleaner in RTM

**Comment by lachis** [comment]
Thank you so much that solved my issue!

**Comment by LuohuaRain** [comment]
I have the same question, and I cannot solve it.. :(

**Comment by khonsari** [comment]
Just Call app.UseAuthentication() before app.UserMvc(...) in ConfigureServices Method.
