### ISSUE TITLE
DisplayName in new AuthN Plumbing?

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#1319]
How do I set it? It's gone from the options class.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/blob/ff9f145a8e89c9756ea12ff10c6d47f2f7eb345f/src/Microsoft.AspNetCore.Authentication/AuthenticationBuilder.cs#L37
https://github.com/aspnet/Security/blob/df325deaf355f99239c1319932bc28eb3a837372/src/Microsoft.AspNetCore.Authentication/AuthenticationServiceCollectionExtensions.cs#L50
@haok is this exposed anywhere else? E.g. I don't see a way to change it for Google, OIDC, etc..

**Comment by leastprivilege** [comment]
but not here

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectExtensions.cs#L20

**Comment by Tratcher** [comment]
It's set here to match the scheme name: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectExtensions.cs#L23
Needs an overload to set the display name.

**Comment by HaoK** [comment]
Yeah we don't have those overloads in the security layer right now, so you'd have to drop down and use the lower overload to tweak the display name

**Comment by PinpointTownes** [comment]
If you decide to fix that in 2.0 (and I personally hope you will), please also fix https://github.com/aspnet/IISIntegration/issues/391 (I'm fine submitting a PR if you prefer).

**Comment by HaoK** [comment]
Doubt we are doing that now, since its a non breaking change in 2.1

You can probably workaround this via directly tweaking the DisplayName via AuthenticationOptions.SchemeMap:

`services.Configure<AuthenticationOptions>(o => o.SchemeMap["OIDC"].DisplayName = whatever`

**Comment by leastprivilege** [comment]
That's ridiculous.

**Comment by PinpointTownes** [comment]
> Doubt we are doing that now, since its a non breaking change in 2.1

Well, it automatically means waiting maybe 5 or 6 months more before moving to 2.x.
And while you can indeed work around this limitation with the "classical" handlers, it's not possible with the host handlers.

**Comment by HaoK** [comment]
What are you trying to do with display name that is so critical?  Check if its null?

**Comment by PinpointTownes** [comment]
@HaoK https://github.com/aspnet/IISIntegration/issues/391#issue-240282870

**Comment by HaoK** [comment]
So you can just write your own filtering for which handlers to display for the external schemes, you don't have to use DisplayName != null as your condition.  Why don't you just merge the list you have with the Windows scheme?

**Comment by HaoK** [comment]
You are able to inspect the schemes yourself via IAuthenticationSchemeProvider, just compute the display list using that directly...

**Comment by HaoK** [comment]
Its up to the app to decide which schemes are appropriate anyways, we wrote some sugar (that I think lives in Identity?) that filters the schemes using DisplayName != null, but its just sugar

**Comment by PinpointTownes** [comment]
Sure, why not reinventing the wheel and using a hardcoded display name in your views when you could simply rely on `SignInManager.GetExternalAuthenticationSchemesAsync()`, that does the right thing for you and is used in the default templates...

**Comment by HaoK** [comment]
Well, you can just wait til 2.1 as you said if you prefer that instead of using the workaround

**Comment by PinpointTownes** [comment]
@HaoK maybe I wasn't clear enough: you CAN'T use the workaround you suggested with the host handlers due to the way you've decided to register them (in the IIS middleware constructor... dynamically :trollface:).

**Comment by HaoK** [comment]
The sugar is not meant to the final arbiter of what schemes should be displayed, that is template sugar for the Individual auth template basically.  I never liked having that in the framework, but it is what it is.  External clearly doesn't hosts as written either.

**Comment by HaoK** [comment]
The workaround for your case is to not use GetExternalAuthenticationSchemesAsync and compute that list yourself.

**Comment by HaoK** [comment]
Again, all that method does is:


```
var schemes = await _schemes.GetAllSchemesAsync();
return schemes.Where(s => !string.IsNullOrEmpty(s.DisplayName));
```

You really don't gain very much by calling it :p

**Comment by PinpointTownes** [comment]
Okay so @leastprivilege was right. Arguing so hard for a zero-risk change that will take 10 minutes to do is truly ridiculous.

**Comment by PinpointTownes** [comment]
> You really don't gain very much by calling it :p

That's not the problem. The problem is that you can't use `await _schemes.GetAllSchemesAsync();` as the display name will always be null. You'll have to hardcode it or import it from somewhere else, which makes no sense.

**Comment by HaoK** [comment]
Doesn't matter how long the fix takes, bar is higher than this bug, shipstoppers only.

**Comment by PinpointTownes** [comment]
Updating the display name associated with the host handlers was possible in 1.x. Since it's no longer possible in 2.x, that's a regression. Does that qualify as a shipstopper? :trollface: 

```csharp
services.Configure<IISOptions>(options =>
{
    options.AuthenticationDescriptions.Clear();

    options.AuthenticationDescriptions.Add(new AuthenticationDescription
    {
        AuthenticationScheme = IISDefaults.Negotiate,
        DisplayName = "Intranet"
    });

    options.AutomaticAuthentication = false;
});
```

**Comment by HaoK** [comment]
Most apps do not have a dynamic list of schemes, most have a couple of schemes they want to show, it really doesn't seem the end of the world for them to either:

- use the sugar, and tweak (hardcode "Windows" in your case).
- Or hardcode the entire list you return

**Comment by HaoK** [comment]
If there was no way for you to workaround this in your app, you'd have a stronger argument :)

**Comment by PinpointTownes** [comment]
> Most apps do not have a dynamic list of schemes, most have a couple of schemes they want to show

Then I you should strongly consider revisiting how you handle that in 2.x/3.x because even if you don't like it, setting the display name in the options and using `SignInManager.GetExternalAuthenticationSchemesAsync()` was - and still is - the "official" way to do that.

But okay, point taken. I'll send a PR against the release branch as suggested by @Tratcher and try to bribe the guy in charge of approving the late PRs... :trollface:

**Comment by HaoK** [comment]
Yeah this is a case of sugar overload in my mind.  Those 2 lines should have just lived in the app, I tried to get rid of the concept entirely of DisplayName, but we couldn't come up with anything better, and we just ran out of time to spend on it so we brought it back late in preview 2 for the templates
