### ISSUE TITLE
Support for Basic Auth for Webhooks

### ISSUE THREAD

**Issue by joshbartley** [aspnet/Security#1322]
I am setting up some webhooks for some well known products, like SendGrid, Stripe, and another credit card processing system, etc. I only have two options, 1, send a webhook over and not have basic authentication enabled and hope no one finds out my URL, 2, roll my own using community provided code and maintain it myself. I feel this is an issue with the current state of the security package for the newer versions of aspnet. I get it, basic auth is old and horrible, but with webhooks, there is not a lot of other alternatives and basicauth is the best we have. Now, in the current state I have to worry about hash timing attacks and make sure I don't have a oracle timing attack on my hands for building my own solution.

What I would like to see is some option, and we can limit it to webhooks, to provide basic auth. It could be something simple and use a function like "RegisterWebHookAuth(WebHookAuthType.Basic)". That way no one should be confused as to it's purpose, and we could limit it to just POST types to prevent abuse. Thoughts?

**Comment by Eilon** [comment]
Hi @joshbartley we are not planning to implement HTTP basic auth as a built-in feature of ASP.NET Core due to the complexity of implementing it securely. However, we do have an **unofficial sample** that you can check out here: https://github.com/blowdart/idunno.Authentication

cc @blowdart
