### ISSUE TITLE
Identity with OpenID Connect

### ISSUE THREAD

**Issue by mmillican** [aspnet/Security#1327]
Using ASP.NET Core 1.1, I am trying to do a type of "hybrid" authentication for a web app.

I am using Identity as essentially a user store on the "client" side, but I want the users to solely log in through an Open ID Connect provider.  

_Why?_  I want "local" references to the users for various use cases, but I don't want to have login individually supported in each application.

I tried mimic'ing the current External Login functionality (on `AccountController`) that comes with Identity out of the box, but I can't get the callback URL to be hit when the response comes back.  I also tried to tie into the `OpenIdConnectEvents` when configuring the middleware, but had issues using `_signInManager.GetExternalLoginInfoAsync()` (it always returned a `null` result).

Here is my configuration code (I've taken most of my attempts out):

**ConfigureServices()**
```
services.AddIdentity<User, Role>()
    .AddEntityFrameworkStores<CmsDbContext, int>()
    .AddDefaultTokenProviders();
```

**Configure()** 
```
app.UseIdentity();

var clientId = config["auth:openId:clientId"];
var authority = config["auth:openId:authority"];

var openIdOptions = new OpenIdConnectOptions
{
    SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme,
    DisplayName = "MyCompany ID",
    Authority = authority,
    ClientId = clientId,
    RequireHttpsMetadata = true,
    ResponseType = OpenIdConnectResponseType.CodeIdToken,
    GetClaimsFromUserInfoEndpoint = true,

    TokenValidationParameters = new TokenValidationParameters
    {
        NameClaimType = "name",
        RoleClaimType = "role"
    }
};
app.UseOpenIdConnectAuthentication(openIdOptions);      
```

**AccountController**
```
[HttpGet]
[AllowAnonymous]
public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
{
    // TODO: Handle remote error

    var info = await _signInManager.GetExternalLoginInfoAsync();
    if (info == null)
    {
        return RedirectToAction("Index", "Home"); // FOR NOW
    }

    var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, false);
    if (result.Succeeded)
    {
        return RedirectToLocal(returnUrl);
    }
    else
    {
        var email = info.Principal.FindFirstValue(ClaimTypes.Email);
        var newUser = new User
        {
            UserName = email,
            Email = email,
            FirstName = info.Principal.FindFirstValue("firstName") ?? "unk",
            LastName = info.Principal.FindFirstValue("lastName") ?? "unk"
        };

        var userResult = await _userManager.CreateAsync(newUser);
        if (userResult.Succeeded)
        {
            userResult = await _userManager.AddLoginAsync(newUser, info);

            await _signInManager.SignInAsync(newUser, false);
        }
    }

    return RedirectToLocal(null);
}
```

Is this possible?  Potentially a different/better way to achieve this?  Hopefully I'm going in the right direction here.

**Comment by HaoK** [comment]
This should work, you basically want to treat OIDC as an external login provider, so you don't want to configure the SignInScheme, and let it use the default Identity ExternalSignInScheme, which would allow you to link the login to the local identity cookie instead of just directly using the OIDC produced identity (that's what the external flow does)

**Comment by mmillican** [comment]
@HaoK I removed the `SignInScheme, but now I'm being redirected the "Access Denied" page.  Is there additional configuration I'm missing?

Also, I updated my original comment with my account controller code which should be responsible for authenticating or creating a new user.

**Comment by mmillican** [comment]
@HaoK @blowdart  sorry to bug - wondering if you had any other guidance here?

**Comment by HaoK** [comment]
You got rid of "SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme" in the OIDC options right?

**Comment by mmillican** [comment]
Correct - the rest of the code above is the same.

**Comment by HaoK** [comment]
Are you able to sign in with OIDC directly?  Basically the flow is get sign in working with any of the auth providers (where you setup a cookie for the auth scheme).

Once you are able to login with that flow properly, you want to point the sign in scheme at the Identity.ExternalCookie instead, and that will take care of linking the accounts (using the Email/login provider).

One other thing to try to make sure the external code is correct, is to add another 3rd parth auth like google/facebook to make sure that you are able to login with those.  Then at least you'll be able to narrow down the issue to something specific to your OIDC setup

**Comment by mmillican** [comment]
@HaoK Yup - with just the OIDC, I was able to sign in fine.

Regarding this:

> point the sign in scheme at the Identity.ExternalCookie instead

Do I do that in the OIDC configuration or Identity configuration.

Thanks for your help - greatly appreciated!

**Comment by HaoK** [comment]
You can try hardcoding it for onw in the OIDC signIn scheme: set it to:

"Identity.External"

https://github.com/aspnet/Identity/blob/rel/1.1.2/src/Microsoft.AspNetCore.Identity/IdentityCookieOptions.cs#L18

**Comment by mmillican** [comment]
Seems like progress.  I see an `Identity.External` cookie being set, but now I am being redirected to an `Access Denied` page

**Comment by mmillican** [comment]
To clarify the above:

I get the access denied when trying to visit a page (after sign in) that has an `Authorize` attribute on it.  

I tried setting `[Authorize(ActiveAuthenticationSchemes = "Identity.External")]` and am now being redirect to my `Login` action, which is just issuing a `Challenge` like so:

```
public IActionResult Login(string returnUrl = null)
{
    var provider = OpenIdConnectDefaults.AuthenticationScheme;

    var redirectUrl = Url.Action(nameof(ExternalLoginCallback), "Account", new { ReturnUrl = returnUrl });
    var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, returnUrl);
    return Challenge(properties, provider);
}
```

After that, it appears to log me in, however my `ExternalLoginCallback` is not being hit, therefore my user is not being created locally.

I feel like we are going in the right direction here.

**Comment by mmillican** [comment]
Sorry to spam, but quick update:  I got my `ExternalLoginCallback` get called (was a typo in the return URL 🤕 and now just have to get claims correct.

Continuing on...

**Comment by blowdart** [comment]
Well the claims come from the provider, so we can happily say "Not us" now *grin*

**Comment by mmillican** [comment]
@HaoK Making good progress, however something else I can't figure out... is there a way / what is the "default" `AuthenticationScheme` used by the `AuthorizeAttribute`?  I keep getting redirected to Access when I would expect to be redirected to my Login page (and then onto my OIDC provider)

**Comment by mmillican** [comment]
So it looks like setting `AutomaticAuthenticate = false` and `AutomaticChallenge = false` on the OIDC config did the trick.  Here's my current configuration for reference


```c#
app.UseIdentity();

var clientId = config["auth:openId:clientId"];
var authority = config["auth:openId:authority"];

var openIdOptions = new OpenIdConnectOptions
{
    AutomaticAuthenticate = false,
    AutomaticChallenge = false,
    SignInScheme = "Identity.External",
    DisplayName = "Graydient ID",
    Authority = authority,
    ClientId = clientId,
    RequireHttpsMetadata = true,
    ResponseType = OpenIdConnectResponseType.CodeIdToken,
    GetClaimsFromUserInfoEndpoint = true,
    Scope =  { "openid", "profile", "email", "given_name", "family_name", "customer_groups", "role"},

    TokenValidationParameters = new TokenValidationParameters
    {
        NameClaimType = "name",
        RoleClaimType = "role"
    }
};

app.UseOpenIdConnectAuthentication(openIdOptions);
```

In my `Login` action, I'm issuing a challenge to the OIDC provider and then my `ExternalLoginCallback` action, I'm validating the user creating an ASP.NET Identity user if they don't already have one, and logging them in with that. 

```c#
[HttpGet]
[AllowAnonymous]
public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
{
    var info = await _signInManager.GetExternalLoginInfoAsync();
    if (info == null)
    {
        return RedirectToAction("Index", "Home"); // FOR NOW
    }

    var externalUser = await _userManager.FindByLoginAsync(info.LoginProvider, info.ProviderKey);
    if (externalUser != null)
    {
        await _signInManager.SignInAsync(externalUser, false);
        await SignOutExternal();
        return RedirectToLocal(returnUrl);
    }
    else
    {
        var email = info.Principal.FindFirstValue(ClaimTypes.Email);
        var newUser = new User
        {
            UserName = email,
            Email = email,
            FirstName = info.Principal.FindFirstValue(ClaimTypes.GivenName) ?? "unk",
            LastName = info.Principal.FindFirstValue("family_name") ?? "unk"
        };

        var userResult = await _userManager.CreateAsync(newUser);
        if (userResult.Succeeded)
        {
            userResult = await _userManager.AddLoginAsync(newUser, info);

            await _signInManager.SignInAsync(newUser, false);
            await SignOutExternal();
        }

        return RedirectToLocal(returnUrl);
    }
}

private Task SignOutExternal()
{
    return HttpContext.Authentication.SignOutAsync(_idOptions.Cookies.ExternalCookieAuthenticationScheme);
}
```

So, as of now, this seems to be working.  I'll try to do a blog post on this journey as soon as time permits.
