### ISSUE TITLE
AuthZ Regression: PolicyEvaluator always passes HttpContext for resource

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#1329]
See line: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authorization.Policy/PolicyEvaluator.cs#L80

The resource should be taken by IPolicyEvaluator.AuthorizeAsync() and passed into the IAuthorizationService instead of always passing in the HttpContext.

This is a regression from 1.0 in MVC where there's no longer any way to access the AuthorizationFilterContext from a policy requirement.  Previously the context.Resource was set to the AuthorizationFilterContext.

Fix is https://github.com/aspnet/Security/pull/1328

**Comment by Eilon** [comment]
Approved for 2.0, incl. the MVC and SignalR changes:

* https://github.com/aspnet/Mvc/pull/6574
* https://github.com/aspnet/SignalR/pull/675

**Comment by HaoK** [comment]
869d98e28d60b49063af8bdcb7a16742b983994b
