### ISSUE TITLE
Custom jwt validator

### ISSUE THREAD

**Issue by hey-red** [aspnet/Security#1331]
Better way to create your own token validator? By default it uses JwtSecurityTokenHandler and validate jwt payload itself, but I'm want to add additional payload validator.
Or maybe better use events for that?

**Comment by Tratcher** [comment]
Replacing the default SecurityTokenValidators in JwtBearerOptions is a good way to do this.
https://github.com/aspnet/Security/blob/ae63c32bff6c3bf025e7ca162bc8b3fdc8193ffc/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerOptions.cs#L92

**Comment by hey-red** [comment]
@Tratcher yes, but it requires to write a implementation of ISecurityTokenValidator i.e token validation/decrypt instead of working with JwtSecurityToken payload like here

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L773

There is no other ways to achieve this?

**Comment by Tratcher** [comment]
Are you only trying to add additional checks on top of  the current validator?

**Comment by hey-red** [comment]
@Tratcher yes.

**Comment by Tratcher** [comment]
I don't know what you're trying to add, but does OnTokenValidated give you enough access?https://github.com/aspnet/Security/blob/644f34e90d35b369efdce9c11ab1db42e0a7f4a7/src/Microsoft.AspNetCore.Authentication.JwtBearer/Events/JwtBearerEvents.cs#L27

**Comment by hey-red** [comment]
Yes, its give me token, but I'm don't know how to correctly abort authentication(I'm just check one field) on this event.
