### ISSUE TITLE
Usability: Obosolete messages don't contain enough information and are therefore painful to use

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Security#1334]
The obsolete messages lack details that enable to tell quickly what the replacement APIs are. Also, because the included link is not clickable you need to take a number of steps to be able to get to content. 

For instance, without building the solution I see this in VS (an interesting thing is that for UseGoogleAuthentication VS did not add squiggles and the build passes without an error even though you can see the message when you hover over the call):

![image](https://user-images.githubusercontent.com/1438884/28478876-fce8eee8-6e0e-11e7-800a-c9706d313730.png)

Since it does not contain the name of the replacement API I don't know what to search for. The link is not clickable so I have to actually build the solution (or try to type the link which I would have to memorize first because if I just move the mouse the message disappears). Note that if I am in the middle of updating my app from 1.1 to 2.0 I may not even be able to build the application in which case you will have to find the right error first . 

If I build the application I see this:
![image](https://user-images.githubusercontent.com/1438884/28479079-c5635ebc-6e0f-11e7-9d87-833573a4b5f4.png)

Again the link is not clickable. Right-click copy copies the entire line not only link. 

Finally I have to go to MSBuild output to get this:
![image](https://user-images.githubusercontent.com/1438884/28479126-edfe5b4c-6e0f-11e7-8c8a-c9bbce3004d5.png)

Where the link is clickable.

The link takes me to https://github.com/aspnet/Security/issues/1310

I quickly try to search for UseMicrosoftAccountAuthentication or UseGoogleAccount on this page and I don't find anything because it is under `Xyz` umbrella (UseXyzAuthentication)

I would prefer to see a message like: `UseGoogleAuthentication is obsolete. Configure Google authentication with AddGoogle in ConfigureServices. See https://go.microsoft.com/fwlink/?linkid=845470 for more details.`

It's more work to create a dedicated message for each obsolete API but it is much more helpful.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/issues/1305

**Comment by HaoK** [comment]
The link to 1310 is also temporary, eventually it will go to the migration doc instead of the announcment

**Comment by moozzyk** [comment]
Regardless, getting to this link is painful. With a more detailed message I could just google/bing things. It could also be helpful in finding help on stackoverflow (as opposed to the generic message).

**Comment by Tratcher** [comment]
@Eilon? This won't be worth changing after RTM

**Comment by Tratcher** [comment]
@blowdart

**Comment by blowdart** [comment]
Not clickable is one for web tooling?

**Comment by Eilon** [comment]
This is not a ship-stopper. Fixing in 2.1 could still have value. Many docs/sites/examples will be mentioning the obsolete APIs for some time.
