### ISSUE TITLE
Resource based authorization is broken in .NET Core 2.0

### ISSUE THREAD

**Issue by andrewlock** [aspnet/Security#1343]
Original thread: [blowdart/AspNetAuthorizationWorkshop/#23](https://github.com/blowdart/AspNetAuthorizationWorkshop/issues/23)

With the various changes to authentication and authorization made in 2.0, the current pattern for performing resource based authorisation no longer works. 

For example, previously resource based authorization could be performed using code similar to: 

```c#
    public class DocumentController : Controller
    {
        IDocumentRepository _documentRepository;
        IAuthorizationService _authorizationService;

        public async Task<IActionResult> Edit(int id)
        {
            var document = _documentRepository.Get(id);

            var authorizationResult = await _authorizationService.AuthorizeAsync(User, document, new EditRequirement());

            if (authorizationResult.Succeeded)
            {
                return View(document);
            }
            else
            {
                return new ChallengeResult();
            }
        }
    }
```

In 1.X, returning a `ChallengeResult` would either result in a 401 (and redirect to login page) or a 403 (and redirect to access denied page).

In 2.0, returning a `ChallengeResult`  *always* result in a 401 (And redirect to a login page). If the user is already logged in (and just doesn't satisfy the handler requirements) then they will be stuck in a redirect loop.

@HaoK Suggested the correct approach is to use the `IPolicyEvaluator` instead of the `IAuthorizationService`. Unfortunately: 

> The policy evaluator is mostly a shared service for frameworks to use, as you've discovered, its currently not really designed to be used in the views, we can definitely expose this in a more friendlier way

A naive attempt to implement the required behaviour results in code that looks something like: 

```c#
public class DocumentController : Controller
{
    IDocumentRepository _documentRepository;
    IPolicyEvaluator _policyEvaluator;

    public DocumentController(IDocumentRepository documentRepository,
                                IPolicyEvaluator policyEvaluator)
    {
        _documentRepository = documentRepository;
        _policyEvaluator = policyEvaluator;
    }

    public async Task<IActionResult> Edit(int id)
    {
        var document = _documentRepository.Get(id);

       // Everything below here to do resource-based auth?!
        var scheme = "SOMETHING?!";
        
        var effectivePolicy = new AuthorizationPolicy(new [] {new EditRequirement()}, new [] {scheme});
        var user = User; 
        var authenticateResult = await _policyEvaluator.AuthenticateAsync(effectivePolicy, HttpContext);
        HttpContext.User = user; // work around issue https://github.com/aspnet/Security/issues/1341

        var authorizeResult = await _policyEvaluator.AuthorizeAsync(effectivePolicy, authenticateResult, HttpContext, document);

        if (authorizeResult.Challenged)
        {
            return new ChallengeResult(effectivePolicy.AuthenticationSchemes.ToArray());
        }
        else if (authorizeResult.Forbidden)
        {
            return new ForbidResult(effectivePolicy.AuthenticationSchemes.ToArray());
        }

        return View(document);
    }
}
```

This is clearly more effort than it should be, and it's not obvious if this is the correct approach. 

1. You can no longer just pass in an `IAuthorizationRequirement`, you have to provide a `Policy`
2. You need to know the auth scheme for your new policy
3. `AuthorizeAsync` requires an `AuthenticateResult` so you either have to manually create one or call `AuthenticateAsync` as above
4. If you want to do imperative auth without a resource (e.g. in Razor views), you need to pass in a `null` resource object (presumably?)

This could likely all be handled by creating a simple wrapper to use for imperative auth, that could be injected into views and controllers for this situation. 

At the very least, explicit guidance needs to be provided on handling this situation in ASP.NET Core 2.0

**Comment by leastprivilege** [comment]
This seems related to https://github.com/aspnet/Security/issues/1341

How is this *not* a big deal.

Fix the authz API *before* shipping 2.0!

**Comment by HaoK** [comment]
The tutorial that is broken is doing things in a weird way (i.e. no login page, not using `[Authorize]`)

**Comment by leastprivilege** [comment]
The above DocumentController is weird? I disagree.

I generally stay away from the `[Authorize]` and prefer the imperative usage of the authz APIs.

**Comment by davidfowl** [comment]
@HaoK it's not weird and this is actually pretty broken. FWIW I'm glad the challenge behavior is gone but all of that logic has now moved into the policy evaluator which means using the authz service imperatively is harder 😢 .

We might need to do something here.

**Comment by davidfowl** [comment]
@andrewlock Why can't this logic look like this:

```C#
public class DocumentController : Controller
{
    IDocumentRepository _documentRepository;
    IAuthorizationService _authorizationService;

    public async Task<IActionResult> Edit(int id)
    {
        var document = _documentRepository.Get(id);

        var authorizationResult = await _authorizationService.AuthorizeAsync(User, document, new EditRequirement());

        if (authorizationResult.Succeeded)
        {
            return View(document);
        }
        else if(User.IsAuthenticated)
        {
           return new ForbidResult();
        }
        else
        {
            return new ChallengeResult();
        }
    }
}
```

**Comment by HaoK** [comment]
Yeah so things are basically okay when doing AuthZ against context.User (via automatic auth scheme)

Things start start getting pretty nasty once you try to specify some other (passive) auth schemes in your policy which brings in the the 401/403 and needing to mimic the authentication logic that the evaluator does.

**Comment by HaoK** [comment]
@davidfowl that will work, it's option 2 that he mentioned in the original issue https://github.com/blowdart/AspNetAuthorizationWorkshop/issues/23 for how to get things working

I asked him to open this issue since we should expose the evaluator logic in a friendlier way

**Comment by HaoK** [comment]
But I think imperatively doing AuthZ just means the callee has to do AuthN themselves, using context.User you've already shown above.

Doing explicit authentication is just:

```C#
        var document = _documentRepository.Get(id);

        var authenticateResult = await context.AuthenticateAsync("YourAuthScheme");
        if (authenticateResult != null && authenticateResult.Succeeded) {
           var authorizationResult = await _authorizationService.AuthorizeAsync(authenticateResult.User, document, new EditRequirement());
            if (authorizationResult.Succeeded)
            {
                return View(document);
            }
            return new ForbidResult();     
        }
        return new ChallengeResult("YourAuthScheme");
```

**Comment by HaoK** [comment]
Wrapping the requirement into a policy and using the IPolicyEvaluator is basically equivalent to that.

**Comment by HaoK** [comment]
We could consider a sugar overload to IPolicyEvaluator like:

```
   Task<PolicyAuthorizationResult> IPolicyEvaluator.AuthorizeAsync(string authenticationScheme, HttpContext context, object resource, IEnumerable<IAuthorizationRequirements> requirements)
```

So then once we had that it'd just be:

```
public class DocumentController : Controller
{
    IDocumentRepository _documentRepository;
    IPolicyEvaluator _eval;

    public async Task<IActionResult> Edit(int id)
    {
        var document = _documentRepository.Get(id);

        var authorizationResult = await _eval.AuthorizeAsync("YourAuthScheme", HttpContext, document, new EditRequirement());

        if (authorizationResult.Succeeded)
        {
            return View(document);
        }
        else if (authorizationResult.Forbidden)
        {
           return new ForbidResult("YourAuthScheme");
        }
        else
        {
            return new ChallengeResult("YourAuthScheme");
        }
    }
}
```

**Comment by davidfowl** [comment]
I see TBH this code https://github.com/aspnet/Security/issues/1343#issuecomment-318999978, looks pretty simple. The sugar method doesn't save much here. You still end up repeating the scheme..(which I think is nice and explicit)

**Comment by andrewlock** [comment]
I actually think the sugar method is quite a bit nicer - everywhere else it seems assumed that authentication has already occurred, so it seems odd to need to explicitly authenticate again here. Also, do we _have_ to specify the auth scheme? It's optional everywhere else right, and I presume most people are only going to have one scheme?

@davidfowl If it's simply a case of the logic checking `User.Identity.IsAuthenticated`, then that's fine by me, and makes sense I think. But I'd definitely prefer a sugar method (preferably without having to specify the scheme), over having to duplicate the code in [#1343 (comment)](https://github.com/aspnet/Security/issues/1343#issuecomment-318999978) in every action that uses resource based auth

**Comment by davidfowl** [comment]
>  actually think the sugar method is quite a bit nicer - everywhere else it seems assumed that authentication has already occurred, so it seems odd to need to explicitly authenticate again here.

Except, you haven't authenticated if the scheme you've chosen to imperatively authenticate against isn't the default scheme. Any other scheme requires an explicit call to AuthenticateAsync, which IMO is clearer. 

> Also, do we have to specify the auth scheme? It's optional everywhere else right, and I presume most people are only going to have one scheme?

You need to specify the auth scheme if you have more than one and you don't want the default scheme. Most people will a default scheme, but it's *very* common to have more than one scheme .e.g Twitter, Google, and Cookies.

> @davidfowl If it's simply a case of the logic checking User.Identity.IsAuthenticated, then that's fine by me, and makes sense I think.

It is. That's why I see zero value in the sugar method. Unless you're trying to authenticate against multiple schemes and merging principals (https://github.com/aspnet/Security/blob/a4458191c700437a00603116ad92633d1590319d/src/Microsoft.AspNetCore.Authorization.Policy/PolicyEvaluator.cs#L37-L45) this helper code doesn't help much...

> But I'd definitely prefer a sugar method (preferably without having to specify the scheme), over having to duplicate the code in #1343 (comment) in every action that uses resource based auth

You can't though, the scheme needs to be specified if you're doing imperative auth and want to get the non default scheme's claims principal.

**Comment by HaoK** [comment]
So is the conclusion that we are happy with where things stand for now for imperative authZ (and can close this issue)?

**Comment by HaoK** [comment]
Other than updating @blowdart docs to include the new example above

**Comment by Eilon** [comment]
We'll make some improvements to this area in https://github.com/aspnet/Security/issues/1348 (details to be filled in).

**Comment by Jingkun-Hu** [comment]
@andrewlock Does resource based auth in 2.0 still fit for "I think the simple answer is really to only use resource-based authorisation when you have to." excerpt from https://andrewlock.net/resource-specific-authorisation-in-asp-net-core/?
