### ISSUE TITLE
How to create a custom authentication middle-ware in 2.0?

### ISSUE THREAD

**Issue by malichishti** [aspnet/Security#1345]
Hi,

I need to create a custom auth middle-ware. I have been following instructions [here](https://zogface.wordpress.com/2016/09/13/custom-authentication-in-asp-net-mvc-core/) but unfortunately i'm unable to find respective base classes in Core 2.0; is it still possible to achieve something similar in 2.0?

Regards,
Ali

**Comment by Tratcher** [comment]
Quite a bit has changed for authentication authors. Reviewing a similar implementation might be the best way to get started.
https://github.com/aspnet/Security/tree/a4458191c700437a00603116ad92633d1590319d/src/Microsoft.AspNetCore.Authentication.JwtBearer

Highlights:
You don't need a middleware class anymore, just the handler class.
The registration has moved from Configure to ConfigureServices
Options are injected via DI
https://github.com/aspnet/Announcements/issues/262

**Comment by blowdart** [comment]
A simpler sample to follow might be https://github.com/blowdart/idunno.Authentication which is stripped down to the bare minimum.

**Comment by malichishti** [comment]
@Tratcher Thank you that solved my problem.

@blowdart thank you for the link, however that approach doesn't work anymore as those base classes have changed:
![image](https://user-images.githubusercontent.com/17155996/28861305-997efa52-77a3-11e7-8573-3f5dd6a7d24d.png)

**Comment by HaoK** [comment]
Make sure you look at the core2-rtm branch not master

**Comment by blowdart** [comment]
What @HaoK said :) That's up to date as of Sunday.
