### ISSUE TITLE
Event OnRedirectToLogin ctx.Response.StatusCode is 200 instead of 401

### ISSUE THREAD

**Issue by chikien276** [aspnet/Security#1347]
I'm experiencing AspNet 2.0 then I found this changed in 2.0 from 1.1.2. When a anonymous user access resource protected by `[Authorize]` annotation `OnRedirectToLogin func` in configured `CookieAuthenticationEvents` got context with `Response.StatusCode == 200` instead of 401 in 1.1.2.
Steps to reproduce is pretty easy. Create new AspNet Core web application using VS 2017 15.3.0 Preview 7.0 then add following block of code to `ConfigureServices` method 
```
services.ConfigureApplicationCookie(options =>
            {
                options.Events = new CookieAuthenticationEvents
                {
                    OnRedirectToLogin = ctx =>
                    {
                        // ctx.Response.StatusCode should be 401 isn't it? It was in 1.1.2
                        if (ctx.Response.StatusCode == 200)
                        {
                            Console.Write("200");
                        }

                        ctx.Response.Redirect(ctx.RedirectUri);
                        return Task.FromResult<object>(null);
                    }
                };
            });
```

**Comment by Tratcher** [comment]
It may have inadvertently been set before, but it would be overwritten by the Response.Redirect anyways. Ultimately it's the handlers job to produce the challenge response it wants, including the status code.

**Comment by Eilon** [comment]
There shouldn't be a reason to check just about anything in the handler of this event. If the event handler callback is getting called, that means a Challenge took place, so the logic to do a redirect, return a 401, etc. should just run.

Is there a particular reason you're checking for the status code?

**Comment by chikien276** [comment]
TBH, no. It just breaks my old code in 1.1.x cause I though I would be 401. And I'm just curious is this behave intended or not. So you could close it if you want.

**Comment by Eilon** [comment]
@chikien276 yes this was a deliberate change in the big restructuring of the auth code in 2.0.
