### ISSUE TITLE
Revisit imperative and resource auth given the re-architecture 

### ISSUE THREAD

**Issue by blowdart** [aspnet/Security#1348]
From https://github.com/aspnet/Security/issues/1343

**Comment by Eilon** [comment]
@HaoK please add your thoughts to here.

**Comment by HaoK** [comment]
I'm thinking we should just add some new extension methods to HttpContext that are analogous to AuthenticateAsync...

```C#
AuthorizationResult context.AuthorizeAsync(ClaimsPrincipal user, object resource IEnumerable<IAuthorizationRequirements> reqs);
AuthorizationResult context.AuthorizeAsync(object resource, IEnumerable<IAuthorizationRequirements> reqs) // uses context.User
// And more sugar overloads

// Basically a cleaned up version of PolicyEvaluator that doesn't set context.User, and returns success/challenge/forbid
PolicyAuthorizationResult context.AuthorizePolicyAsync(AuthorizationPolicy policy, object resource)
```

Thoughts?  @Tratcher @davidfowl @blowdart

**Comment by Tratcher** [comment]
If the result is challenge or forbid it will have called those internally, right? Or do you need to provide an auth scheme for that to work?

**Comment by HaoK** [comment]
The first 2 overloads are just sugar on top of the old IAuthorizationService.Authorize, so those are just returning success/failure (with errors).

The 3rd one that takes a policy could directly call challenge/forbid if we wanted instead of just returning a status that corresponded to that.

**Comment by HaoK** [comment]
The auth scheme comes from the policy.  We could add an overload that took a list of AuthenticationSchemes, and a list of requirements (which is basically all a policy is)

**Comment by Tratcher** [comment]
I imagine code like:
```
if (context.AuthorizeAsync(resource, reqs,...))
{
  // do restricted stuff
}
else
{
  // denied. either skip the restricted action or send an error. Challenge/Forbid here?
}
```

**Comment by HaoK** [comment]
Yep, the first two leave it up to the callee to do any authentication themselves, so it would be up to them to determine if they want to challenge/forbid.  Its just some sugar letting them authorize in code similar to [Authorize], so we'd probably have an overload that took a policy name as well.

**Comment by davidfowl** [comment]
Can we write out the before and after for each of those sugar methods. I'd like to see the code reduction.

**Comment by HaoK** [comment]
Sure:

```C#
// OLD to check if user meets the Owner policy imperatively

// Ctor injection
Controller(IAuthorizationService auth) 
// In the action
await authorizationService.AuthorizeAsync(httpContext.User, someResource, "Owner")

// NEW
// With sugar, no injection, simply becomes (can also pass in a principal, otherwise defaults to httpContext)
await httpContext.AuthorizeAsync(someResource, "Owner");
```

For the more complex policy sugar:

Today:
```C#
        var document = _documentRepository.Get(id);

        var authenticateResult = await context.AuthenticateAsync("YourAuthScheme");
        if (authenticateResult != null && authenticateResult.Succeeded) {
           var authorizationResult = await _authorizationService.AuthorizeAsync(authenticateResult.User, document, new EditRequirement());
            if (authorizationResult.Succeeded)
            {
                return View(document);
            }
            return new ForbidResult("YourAuthScheme");     
        }
        return new ChallengeResult("YourAuthScheme");
```

With some Sugah:
```C#
        // Assuming we have a DocumentPolicy that specified AuthenticationScheme = "YourAuthScheme", and EditRequirement has been configured, or we can just add sugar that takes schemes + requirements
        var document = _documentRepository.Get(id);

        // This will call Forbid/Challenge as needed
        var authResult = await context.AuthorizePolicyAsync("DocumentPolicy", document);
        if (authResult.Succeeded) {
             return View(document);
        }
        return new EmptyResult(); // do nothing since the helper will have already called challenge/forbid
```

**Comment by davidfowl** [comment]
The first one is a nice-ish simplification but part of me hates the fact that it hides the `IAuthorizationService`. How do I test that method?

The second example circumvents setting the MVC action results which means filters can't act. They directly call into the http context which kinda sucks...

**Comment by HaoK** [comment]
Its basically analogous to the AuthenticateAsync extension methods, you can test them by mocking an IAuthorizationService and putting that into the RequestServices for the httpContext.

For the second one, we can make it an MVC specific helper then?
```
var failedResult = await MvcAuthorizePolicyAsync("DocumentPolicy", document);
if (failedResult != null) {
    return failedResult; // helper will return Forbid/Challenge result for failures
}
return View(document); // success when result is null.
```

**Comment by davidfowl** [comment]
> Its basically analogous to the AuthenticateAsync extension methods, you can test them by mocking an IAuthorizationService and putting that into the RequestServices for the httpContext.

Yea, it's not the very DI friendly. We're just hiding calls to GetService, it's the service locator pattern. It makes testing pretty awful. If anything, we should revisit what that actually looks like with our new extension methods. The service makes it easy to test things but we now that we've opted to hang things off the http context, it makes it harder to do so.

> For the second one, we can make it an MVC specific helper then?

Possibly, but I'm just not seeing the big value. We removed a single if statement.

**Comment by HaoK** [comment]
Sure but that if is what exposes the whole 401/403 that wasn't exposed in 1.x.  It makes seem a lot less complicated:

```C#
var failedResult = await MvcAuthorizePolicyAsync("DocumentPolicy", document);
if (failedResult != null) {
    return failedResult; // helper will return Forbid/Challenge result for failures
}
return View(document); // success when result is null.
```

 vs 

```C#
        var authenticateResult = await context.AuthenticateAsync("YourAuthScheme");
        if (authenticateResult != null && authenticateResult.Succeeded) {
           var authorizationResult = await _authorizationService.AuthorizeAsync(authenticateResult.User, document, new EditRequirement());
            if (authorizationResult.Succeeded)
            {
                return View(document);
            }
            return new ForbidResult("YourAuthScheme");     
        }
        return new ChallengeResult("YourAuthScheme");
```

**Comment by HaoK** [comment]
Not to mention that it also takes care of the authentication as well that they otherwise would need to do

**Comment by HaoK** [comment]
@blowdart are we happy with the state of things for resource based imperative auth, as things stands it typically would look something like:

```
        var document = _documentRepository.Get(id);

        var authenticateResult = await context.AuthenticateAsync("YourAuthScheme");
        if (authenticateResult != null && authenticateResult.Succeeded) {
           var authorizationResult = await _authorizationService.AuthorizeAsync(authenticateResult.User, document, new EditRequirement());
            if (authorizationResult.Succeeded)
            {
                return View(document);
            }
            return new ForbidResult("YourAuthScheme");     
        }
        return new ChallengeResult("YourAuthScheme");
```

**Comment by HaoK** [comment]
If we are I'll close this issue

**Comment by Eilon** [comment]
Reviewed with @davidfowl and we don't think we have anything else to do here.
