### ISSUE TITLE
Make default value of ChunkingCookieManager.ThrowForPartialCookies be 'false'

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1349]
When an auth cookie gets chunked it's possible that the client may drop some of those chunks due to storage capacity limits. When ChunkingCookieManager then tries to reassemble the chunks and fails it defaults to throwing a format exception. This exception is not caught by the cookie auth handler and can result in a 500 response.
https://github.com/aspnet/Security/blob/5d802a798847f61c8c32368f5690a48caefbca97/shared/Microsoft.AspNetCore.ChunkingCookieManager.Sources/ChunkingCookieManager.cs#L116

Alternatively the cookie auth handler could catch and log the exception.
https://github.com/aspnet/Security/blob/5d802a798847f61c8c32368f5690a48caefbca97/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L107

In practice customers end up disabling this option (if they find it).
```
var cookieManager = new ChunkingCookieManager
{
    ThrowForPartialCookies = false
};
```

**Comment by Eilon** [comment]
I think this goes well with our guidance of making it hard for a client to inadvertently "poison" themselves by having some bad cookies.
