### ISSUE TITLE
AuthorizeFilter always returns 401

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#1350]
_From @epot on August 3, 2017 11:51_

I added a dummy AuthorizationHandler with a IAuthorizationRequirement that does not do anything, but the code is never reached and asp.net core returns a 401 without any details. I read https://stackoverflow.com/questions/37276005/asp-net-core-policy-based-authorization-ends-with-401-unauthorized but my case seems to be different as my user is authenticated after exiting the AuthenticationHandler callback. Can I debug somehow what is happening?

_Copied from original issue: aspnet/Mvc#6622_

**Comment by Eilon** [comment]
_From @epot on August 3, 2017 13:33_

I found the following logs:

Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed for user: exxxx@xxxx.com.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Information: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Microsoft.AspNetCore.Mvc.ChallengeResult: Information: Executing ChallengeResult with authentication schemes ().
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Information: Executed action Gna.Controller.test (Gna) in 28.5914ms

**Comment by epot** [comment]
Answered here:
https://stackoverflow.com/questions/45499636/asp-net-core-custom-authorization-always-ends-with-401-unauthorized
Not sure why it was moved to security as it seems more related to MVC integration.

**Comment by davidfowl** [comment]
That's because it's not related to MVC. MVC just calls into the auth system.

**Comment by epot** [comment]
Well regarding this specific ticket, the issue was when trying to integrate my security code in MVC, that was the part that was not working.

**Comment by davidfowl** [comment]
Is the issue resolved? Can this be closed?

**Comment by epot** [comment]
yes (see stackoverflow)

**Comment by davidfowl** [comment]
Kewl
