### ISSUE TITLE
Possible to prevent ReturnUrl query being appended when redirecting to the LoginPath?

### ISSUE THREAD

**Issue by bryanwood** [aspnet/Security#1351]
Is it possible to prevent the `ReturnUrl` querystring being appended to the `LoginPath` when redirected to login?

**Comment by Tratcher** [comment]
Where do you want them to go back to after logging in? Or are you proposing a different way of flowing that information?

**Comment by bryanwood** [comment]
I've got a scenario where a user will login via an email link but they'll always be directed to a specific page after following the link. The `ReturnUrl` isn't required for this, removing it is just an aesthetic thing.

**Comment by Tratcher** [comment]
You can always customize the redirect in the OnRedirectToLogin event.
https://github.com/aspnet/Security/blob/5d802a798847f61c8c32368f5690a48caefbca97/src/Microsoft.AspNetCore.Authentication.Cookies/Events/CookieAuthenticationEvents.cs#L40
