### ISSUE TITLE
Authorization should be more dynamical and configurable 

### ISSUE THREAD

**Issue by Jingkun-Hu** [aspnet/Security#1352]
I have read articles of guys like Dominick, andrewlock, Ben, those from MS and stackingoverflow and the like. I not sure where the new authorization will guide us to. As a man suffering from doing the authorization part in my company, I describe the requirement and principles from my perspectives. 
requirements:
(1) I need to configure the authorization more dynamically. that means I need to admin like frontend to add resource name, the policies that protect the resource, the underlying database operation automatically. The resource, which has a one-to-one map with access policy name(rules on who or which can access) can bind to specific policies, requirements on the fly. Do not put the mass policies into startup.cs every time I create a new one, but into database.
(2) Resource based authorization can be notation style like claim based policy example in official doc. In this way can we decouple the authorization part in separated project.

**Comment by VahidN** [comment]
You can create a dynamic role based permission system using the new policies system very easily.
First define a dynamic `AuthorizationHandler`. Here you can access the current requested area,controller and action names (`resources` here) and then you can decided to authorize the current user or not. You can create an admin page to list all of these resources and then add them to the RoleClaims table. RoleClaims table is a new table in ASP.NET Core identity which lets you to dynamically assign new claims to each role. These claims will be added to the authentication cookie of the current user after login automatically. So you just need to have an admin page to complete this table. Define users, define roles and finally change the RoleClaims based on the required resources.
```csharp
    public class DynamicPermissionRequirement : IAuthorizationRequirement
    {
    }

    public class DynamicPermissionsAuthorizationHandler : AuthorizationHandler<DynamicPermissionRequirement>
    {
        protected override async Task HandleRequirementAsync(
             AuthorizationHandlerContext context,
             DynamicPermissionRequirement requirement)
        {
            var mvcContext = context.Resource as AuthorizationFilterContext;
            if (mvcContext == null)
            {
                return;
            }

            var actionDescriptor = mvcContext.ActionDescriptor;
            var area = actionDescriptor.RouteValues["area"];
            var controller = actionDescriptor.RouteValues["controller"];
            var action = actionDescriptor.RouteValues["action"];

            if (_decisionMakingService.CanCurrentUserAccess(area, controller, action))
            {
                context.Succeed(requirement);
            }
            else
            {
                context.Fail();
            }
        }
    }
```
Here `_decisionMakingService` just checks the current user's claims:
```
return user.HasClaim(claim => claim.Type == ConstantPolicies.DynamicPermissionClaimType &&
                                          claim.Value == currentClaimValue);
```
A user gets its permissions claims from the `ApplicationClaimsPrincipalFactory` class automatically and it includes the role claims too.
How to register it:
```csharp
            services.AddScoped<IAuthorizationHandler, DynamicPermissionsAuthorizationHandler>();
            services.AddAuthorization(opts =>
            {
                opts.AddPolicy(
                    name: "DynamicPermission",
                    configurePolicy: policy =>
                    {
                        policy.RequireAuthenticatedUser();
                        policy.Requirements.Add(new DynamicPermissionRequirement());
                    });
            });
```
And How to use it
```csharp
    [Authorize(Policy = "DynamicPermission")]
    public class DynamicPermissionsTestController : Controller
```
Here you don't need to predefine any policies or roles. you can change them on the fly.

**Comment by davidfowl** [comment]
> (1) I need to configure the authorization more dynamically. that means I need to admin like frontend to add resource name, the policies that protect the resource, the underlying database operation automatically. The resource, which has a one-to-one map with access policy name(rules on who or which can access) can bind to specific policies, requirements on the fly. Do not put the mass policies into startup.cs every time I create a new one, but into database.

You can replace the `IAuthorizationPolicyProvider` so that you can map policy names to policies on the fly without having to map everything in `Startup.cs`.

> (2) Resource based authorization can be notation style like claim based policy example in official doc. In this way can we decouple the authorization part in separated project.

Do you mean you want the resource to be declarative? Can you give an example of what you mean? I have some ideas around this but I'd like to see what you're trying to do to see my suggestion matches your expectations.


@VahidN That's pretty creative! It does feel a bit like a hack though. You've coupled to MVC which this auth system was supposed to help you avoid.

**Comment by Jingkun-Hu** [comment]
@VahidN Thanks for your detailed example, awesome! From my understanding, it uses "DynamicPermission" notation on every protected resources, put auth work in _decisionMakingService where you get claims, resources(action, controller, area), then apply access rules on claims to resource. Very creative.

**Comment by Jingkun-Hu** [comment]
@davidfowl Thank you David, IAuthorizationPolicyProvider is powerful. I found another thread https://github.com/aspnet/Security/issues/670 where you gave codes. The "indirection" is what I want. Decoupled. Then the concern turns to performance.
Yes, I mean declarative. Appreciate if  you would share your ideas.

**Comment by HaoK** [comment]
AuthZ improvements have been consolidated into this issue: https://github.com/aspnet/Security/issues/670
