### ISSUE TITLE
Cookies and OIDC emit invalid Expires header values

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1353]
CookieHandler and OpenIdConnectHandler set `Response.Headers[HeaderNames.Expires] = "-1";` for responses that should not be cached. However, `-1` is an invalid value for the expires header which should be a full date string `Expires: Sun, 06 Nov 1994 08:49:37 GMT`.
https://tools.ietf.org/html/rfc7234#section-5.3
It's abusing one line in the spec that says `A cache recipient MUST interpret invalid date formats, especially the value "0", as representing a time in the past (i.e., "already expired").`

Some tools hide/drop invalid headers, making it harder to inspect them. (E.g. HttpClient).

We should use the epoc date used by Response.Cookies.Delete instead. ` new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc),`
https://github.com/aspnet/HttpAbstractions/blob/e8123db21ece289e30abf174a37a908b9e5e1e98/src/Microsoft.AspNetCore.Http/Internal/ResponseCookies.cs#L131

**Comment by Tratcher** [comment]
@JunTaoLuo ResponseCaching doesn't handle this special case of an invalid expires headers does it?

**Comment by JunTaoLuo** [comment]
ResponseCaching relies on `HeaderUtilities.TryParseDate` which returns `DateTimeOffset.MinValue` when given an invalid value. For the purpose of ResponseCaching logic, this ensures that invalid date formats are treated as time in the past.
