### ISSUE TITLE
OpenIdconnect throws MissingManifestResourceException on exceptions

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Security#136]
An unhandled exception occurred while processing the request.

MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture. Make sure "Microsoft.Owin.Security.OpenIdConnect.Resources.resources" was correctly embedded or linked into assembly "Microsoft.AspNet.Security.OpenIdConnect" at compile time, or that all the satellite assemblies required are loadable and fully signed.
System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)

**Comment by Praburaj** [comment]
@brentschmaltz @Tratcher

**Comment by PinpointTownes** [comment]
I've also seen this weird exception. Any chance it could be related to https://github.com/aspnet/XRE/issues/668?

**Comment by Praburaj** [comment]
I see the `.resx` file missing in OpenIdc project where as the others have it. May be that's causing the issue?

**Comment by Praburaj** [comment]
This is fixed now.
