### ISSUE TITLE
How to get access to auth_token in Specflow testing scenario

### ISSUE THREAD

**Issue by romeelk** [aspnet/Security#1361]
Hello,
We are trying to test our API which is being called by an MVC application. We have setup OpenId hybrid flow. So our users can connect to the MVC app and then call the backend API. We are having trouble as we cannot find a way to access the auth_token which is created by the OpenIdConnectMiddleware. We note that the login process and OpenId protocol requests the auth_token via a back channel call to Identity server. We have tried to use Postman to request a token but it does not work. How can we extract the auth_token which is pushed into a cookie?? We are currently blocked with our Acceptance testing and would appreciate your assistance.
Thanks,
Romeel

**Comment by Tratcher** [comment]
Something like this?
https://github.com/aspnet/Security/blob/c1250220508996a494d51627a8bd02b7792c012f/samples/OpenIdConnectSample/Startup.cs#L166
(note this is a 2.0 sample)
@haok where was GetTokenValue in 1.x?

**Comment by HaoK** [comment]
In 1.x it should be the same, hanging off of AuthenticationProperties as an extension method

**Comment by Tratcher** [comment]
Sure, I just couldn't find the src.

**Comment by HaoK** [comment]
Ah sure: https://github.com/aspnet/Security/blob/patch/1.1.3/src/Microsoft.AspNetCore.Authentication/TokenExtensions.cs#L49

**Comment by romeelk** [comment]
Thanks for the replies. The sample you have given is the server retrieving a refresh token. We need the auth_token for the specflow tests to be able to set the bearer token on all api calls? We already do this for our client credential api's

**Comment by Tratcher** [comment]
Getting the auth_token is the same as getting the refresh_token, just change the parameter.
