### ISSUE TITLE
Get token from HttpContext in test

### ISSUE THREAD

**Issue by user1336** [aspnet/Security#1368]
I've upgraded to ASP.NET 2.0.0 and had a test that looked a lot like this test:
https://github.com/aspnet/Security/blob/rel/2.0.0/test/Microsoft.AspNetCore.Authentication.Test/TokenExtensionTests.cs#L159

I see that the `AuthenticationHandler` is obsolete. So now I created a stub that implements `Microsoft.AspNetCore.Authentication.IAuthenticationService` like this: 
```c#
public Task<AuthenticateResult> AuthenticateAsync(HttpContext context, string scheme)
{
    return Task.FromResult(AuthenticateResult.Success(new AuthenticationTicket(new ClaimsPrincipal(new ClaimsIdentity(scheme)), scheme)));
}
public Task SignInAsync(HttpContext context, string scheme, ClaimsPrincipal principal, AuthenticationProperties properties)
{
    return Task.FromResult(AuthenticateResult.Success(
        new AuthenticationTicket(new ClaimsPrincipal(new ClaimsIdentity(scheme)), properties, scheme)));
}
```
```csharp
var token = await httpContext.GetTokenAsync("access_token");
var result = await httpContext.AuthenticateAsync();
var props = result.Properties;
token = props.GetTokenValue("access_token");
```
Both ways do not seem to work, how do I do this in ASP.NET Core 2.0.0?

**Comment by HaoK** [comment]
https://github.com/aspnet/HttpAbstractions/blob/dev/test/Microsoft.AspNetCore.Authentication.Core.Test/TokenExtensionTests.cs#L128
