### ISSUE TITLE
AddMicrosoftAccount fails: There was no DefaultChallengeScheme found.

### ISSUE THREAD

**Issue by brijesh-1111** [aspnet/Security#1369]
I was trying to understand the Azure AD Authentication. I am using Aspnet Core 2.0 Final Release version with Visual Studio 2017.

Based on the guideline suggested [https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x](url), 
I have tried to use Microsoft Authentication using following code snippet 
```C#
services.AddAuthentication().AddMicrosoftAccount(options =>
{
    options.ClientId = Configuration["auth:microsoft:clientid"];
    options.ClientSecret = Configuration["auth:microsoft:clientsecret"]; });
}
```

But this fails with the error `InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.`

I have tried to understand what the Default I should provide but so far have no success. However I can run the same Authentication using the following code

```C#
services.AddAuthentication(auth =>
{
    auth.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
    auth.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    auth.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
})
.AddCookie()
.AddOpenIdConnect(options => 
{
     options.ClientId = configuration["Authentication:AzureAd:ClientId"];
     options.Authority = configuration["Authentication:AzureAd:Authority"];
     options.CallbackPath = configuration["Authentication:AzureAd:CallbackPath"];
});
```

Can anyone help me to understand this more?

**Comment by DerAlbertCom** [comment]
did you put UseAuthentication() the pipeline?
```C#
app.UseAuthentication();
app.UseMvc();
```

**Comment by Tratcher** [comment]
Your second sample is correct. Just replace AddOpenIdConnect with AddMicrosoftAccount and `auth.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;` with auth.DefaultChallengeScheme = MicrosoftAccountDefaults.AuthenticationScheme;`
