### ISSUE TITLE
No authentication handler is configured to handle the scheme: OpenIdConnect

### ISSUE THREAD

**Issue by jamesgurung** [aspnet/Security#1370]
I've tried to follow the instructions [here](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x) to use ASP.NET 2.0 authentication (with Google OAuth2), but it isn't working.

## Repro

```
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System;

namespace App
{
  public class Startup
  {
    public Startup(IHostingEnvironment env)
    {
      var builder = new ConfigurationBuilder()
          .SetBasePath(env.ContentRootPath)
          .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
          .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
          .AddEnvironmentVariables();
      Configuration = builder.Build();
    }

    public IConfigurationRoot Configuration { get; }

    public void ConfigureServices(IServiceCollection services)
    {
      services
        .AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
        .AddCookie(o => {
          o.LoginPath = "/signin";
          o.LogoutPath = "/signout";
          o.ExpireTimeSpan = TimeSpan.FromDays(7);
        })
        .AddGoogle(o => {
          o.ClientId = "...";
          o.ClientSecret = "...";
          o.SaveTokens = true;
          o.CallbackPath = "/signin-oauth2";
        });

      services.AddMvc();
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
      app.UseAuthentication();

      if (env.IsDevelopment()) {
        app.UseDeveloperExceptionPage();
      }

      app.UseStaticFiles();

      app.UseMvc(routes => {
        routes.MapRoute(
            name: "default",
            template: "{controller=Home}/{action=Index}/{id?}");
      });
    }
  }
}
```

## Error

I get the following error on navigating to the homepage, which is decorated with `[Authorize]`:

> **InvalidOperationException: No authentication handler is configured to handle the scheme: OpenIdConnect**
> Microsoft.AspNetCore.Authentication.AuthenticationService+<ChallengeAsync>d__11.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Mvc.ChallengeResult+<ExecuteResultAsync>d__14.MoveNext()
> ...

**Comment by jamesgurung** [comment]
@davidfowl Thanks for the tip about simplifying the `Startup` constructor.

I'm really sorry, I can't get my head around this! Every time I change something I get a different error. Please can you let me know where I'm going wrong?

The flow I'm expecting is:
1. Unauthenticated user navigates to `/`
1. Middleware sees `[Authorize]` and redirects to `/login`
1. The login method redirects the user straight to the Google sign in page
1. Google sends a token back to `/signin-oauth2`
1. The middleware signs the user in and redirects to `/`

I've changed `ConfigureServices` to this:
```C#
services
  .AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
  .AddCookie(o => {
    o.LoginPath = "/signin";
    o.LogoutPath = "/signout";
    o.ExpireTimeSpan = TimeSpan.FromDays(7);
  })
  .AddGoogle(o => {
    o.ClientId = Configuration["auth:google:clientid"];
    o.ClientSecret = Configuration["auth:google:clientsecret"];
    o.SaveTokens = true;
    o.CallbackPath = "/signin-oauth2";
  });
  services.AddMvc();
```

And here's my Home controller:
```C#
[Authorize]
public IActionResult Index() => View()

[Route("/signin")]
public IActionResult SignIn()
{
  var authProperties = new AuthenticationProperties {
    RedirectUri = "/"
  };
  return new ChallengeResult(authProperties);
}
```

This throws a runtime error:
> InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.

However, I did set the auth scheme with `AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)`.

If I change this to `CookieAuthenticationDefaults.AuthenticationScheme` then there's no error but the browser says "Too Many Redirects" trying to reach `/signin?ReturnUrl=%2F`.

Please can you show me what to do?

**Comment by davidfowl** [comment]
I'll try to describe the flow piece by piece. 

First, we'll change your startup to be this:

```C#
services
  .AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
  .AddCookie(o => {
    o.LoginPath = "/signin";
    o.LogoutPath = "/signout";
    o.ExpireTimeSpan = TimeSpan.FromDays(7);
  })
  .AddGoogle(o => {
    o.ClientId = Configuration["auth:google:clientid"];
    o.ClientSecret = Configuration["auth:google:clientsecret"];
    o.SaveTokens = true;
    o.CallbackPath = "/signin-oauth2";
  });
  services.AddMvc();
```

This configures the "Cookies" and "Google" authentication schemes and sets "Cookies" as the default scheme. This means that any authN operation performed without specifying a name, will use the default scheme "Cookies".

> Unauthenticated user navigates to /

```C#
[Authorize]
public IActionResult Index() => View();
```

The user ends up at your HomeController Index route (assuming that's configured for /) and the HttpContext.User is unauthenticated.

> Middleware sees [Authorize] and redirects to /login

The middleware doesn't see `[Authorize]` nor does it redirect you. The MVC authentication filter sees authorize attribute and issues a Challenge. Since you didn't specify an authN scheme on the attribute, it will use the default "Cookies". The CookieAuthentiationHandler issues a redirect to the configured `LoginPath` which in this case is `/signin`.

> The login method redirects the user straight to the Google sign in page

```C#
[Route("/signin")]
public IActionResult SignIn()
{
  var authProperties = new AuthenticationProperties {
    RedirectUri = "/"
  };
  return new ChallengeResult(authProperties);
}
```

Your SignIn action issues a Challenge without an authentication scheme specified. Like the above examples, when no scheme is specified, the default is used which is "Cookies" in this case. That will end up redirecting you back to the configured `LoginPath` "/signin". 

There is a your infinite redirect loop. 

What you *actually* want is to change the SignIn logic to look like this:

```C#
[Route("/signin")]
public IActionResult SignIn()
{
  var authProperties = new AuthenticationProperties {
    RedirectUri = "/"
  };
  return new ChallengeResult(GoogleDefaults. AuthenticationScheme, authProperties);
}
```

This will trigger the GoogleAuthenticationHandler to execute its challenge behavior which is a redirect to google.

**Comment by jamesgurung** [comment]
Thanks for the detailed tutorial! :+1: All working now.

Your explanation has led me to save a redirect by doing:

```C#
[Authorize(AuthenticationSchemes = GoogleDefaults.AuthenticationScheme)]
public IActionResult Index() => View();
```

This seems to work well. So I thought I could simplify it even more by setting in `ConfigureServices`:
```C#
services
  .AddAuthentication(GoogleDefaults.AuthenticationScheme)
  .AddCookie(/* ... */)
  .AddGoogle(/* ... */);
```

However, the app then crashes with a "Bad Gateway" error. Why is this? (Just curious now!)

Anyway, I've secured the whole app with this and it's all working great!

```C#
services.AddMvc(config => {
  var policy = new AuthorizationPolicyBuilder()
    .RequireAuthenticatedUser()
    .AddAuthenticationSchemes(GoogleDefaults.AuthenticationScheme)
    .Build();
  config.Filters.Add(new AuthorizeFilter(policy));
});
```

**Comment by davidfowl** [comment]
> This seems to work well. So I thought I could simplify it even more by setting in ConfigureServices:

> services
  .AddAuthentication(GoogleDefaults.AuthenticationScheme)
  .AddCookie(/* ... */)
  .AddGoogle(/* ... */);

> However, the app then crashes with a "Bad Gateway" error. Why is this? (Just curious now!)

The piece of logic you don't see is what happens when the google issues the callback. Each of the remote/external auth handlers (google, twitter, other external oauth auth handlers) delegate "SignIn" to another auth handler. The reason you have google *and* cookies is because you're using google for identity information but using cookies for storage of the identity. 

When you change the default scheme to google, it ends up trying to "SignIn" with Google which doesn't do anything. Another way to do things would be to set it up like this:

```C#
services
  .AddAuthentication(options =>
  {
      options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
      options.DefaultChallengeScheme = GoogleDefaults.AuthenticationScheme;
  })
  .AddCookie(...)
  .AddGoogle(...);
```

That says:
- For challenges, use the google scheme
- For anything else (sign in, sign out, authenticate, forbid), use the cookies scheme

**Comment by jamesgurung** [comment]
Thanks!

**Comment by vnextcoder** [comment]
in my Case, i had this `SigninScheme` set in the Appsettings which was causing various kind of issues.

once I removed that `SigninScheme` and it worked fine. 
````json
{
"Google": {
     /* Commenting the below line worked for me */
    /*"SignInScheme": "Google",*/  
    "ClientId": "myid"
  }
}
````
I also removed `AddCookie` call and it works still . Could somebody shed some light if `AddCookie` is called automatically somewhere during `AddAuthentication` calls ?

the below is working code. 

````C#
    services
                .AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = GoogleDefaults.AuthenticationScheme;
                })
                //..AddCookie(o => {
                //    o.LoginPath = "/signin";
                //    o.LogoutPath = "/signout";
                 //   o.ExpireTimeSpan = TimeSpan.FromDays(7);}
                //)
                .AddGoogle("Google", options => 
                {
                    Configuration.GetSection("Google").Bind(options);
                    options.SaveTokens = true;
                }
            );
````

**Comment by Tratcher** [comment]
SignInScheme should almost always be Cookies, it should never refer to itself (e.g. Google).
