### ISSUE TITLE
IServiceCollection does not contain definition for 'AddJwtBearerAuthentication'

### ISSUE THREAD

**Issue by elmojo** [aspnet/Security#1371]
I have the Microsoft.AspNetCore.Authentication.JwtBearer nuGet packaged added to my project.  I have "using Microsoft.AspNetCore.Authentication.JwtBearer;" within my file.  The compiler still cannot find the IServiceCollection extension method "AddJwtBearerAuthentication".  I cannot find it within the Object Browser either.  Am I missing something or doing something wrong?

**Comment by davidfowl** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x

**Comment by elmojo** [comment]
Thanks, I read up on it.  I guess there are a lot of old samples out there.
