### ISSUE TITLE
JWT tid claim transformation to "http://schemas.microsoft.com/identity/claims/tenantid"

### ISSUE THREAD

**Issue by cartervms** [aspnet/Security#1372]
Is there any way to disable this conversion? This is causing issues for us when requests flow between different services, where some are using ASP.NET core and others aren't. This is really inconvenient, because now our shared claim lookup code is having to do .Where( c => c.Equals("http://schemas.microsoft.com/identity/claims/tenantid") || c.Equals("tid"));

**Comment by cartervms** [comment]
For reference: https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/claims

<i>This table lists the claim types as they appear in the ID token. In ASP.NET Core, the OpenID Connect middleware converts some of the claim types when it populates the Claims collection for the user principal:
oid > http://schemas.microsoft.com/identity/claims/objectidentifier
tid > http://schemas.microsoft.com/identity/claims/tenantid
unique_name > http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
upn > http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn</i>

**Comment by Tratcher** [comment]
This issue was moved to AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#685
