### ISSUE TITLE
Multiple Authentication Schemes?

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Security#1373]
I'm trying to support cookies for my authorized views and jwt tokens for my APIs in one project. Is this even possible in Identity Core 2 (or whatever I'm supposed to call it).

In my Configure Services i'm doing this to create two schemes:

```
      services.AddAuthentication(o =>
      {
        o.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        o.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
      })
        .AddCookie();

      services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
        .AddJwtBearer(cfg =>
        {
          cfg.TokenValidationParameters = new TokenValidationParameters()
          {
            ValidIssuer = _config["Tokens:Issuer"],
            ValidAudience = _config["Tokens:Audience"],
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_config["Tokens:Key"])),
            ValidateLifetime = true
          };
        });
```

And when I set the scheme for a specific API:

```
  [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
  [Route("api/[controller]")]
  public class OrdersController : Controller
```

I get "there is no handler for the authentication scheme" error. I would do this with policies instead but it doesn't seem very logical. Any pointers to how to do this (or a blog post that explains it) would really help.

**Comment by davidfowl** [comment]
Why are you're calling AddAuthentication twice instead of doing this:

```C#
services.AddAuthentication()
        .AddCookie();
        .AddJwtBearer(cfg =>
        {
          cfg.TokenValidationParameters = new TokenValidationParameters()
          {
            ValidIssuer = _config["Tokens:Issuer"],
            ValidAudience = _config["Tokens:Audience"],
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_config["Tokens:Key"])),
            ValidateLifetime = true
          };
        });
```

**Comment by shawnwildermuth** [comment]
I've tried that, and it's working but I can't get Auth to work yet, but i'm close.

**Comment by davidfowl** [comment]
What's not working exactly?

**Comment by shawnwildermuth** [comment]
I'm never being logged in. I think it's something wierd. I'm going to recreate with a new 2.0 project and see what I can do (i'm using a 2.0 preview codebase so who knows what is left in there).

**Comment by shawnwildermuth** [comment]
We can close this. I got it working. It was simpler than I was making it. What you showed me was exactly correct.
