### ISSUE TITLE
InvalidOperationException on context.Succeed of PendingRequirements in ASP.NET Core 2.0

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/Security#1375]
Found while understanding ``AuthorizationHandlerContext`` and ``IAuthorizationHandler``:

I tried to ``context.Succeed`` PendingRequirements (which from both name and comment looks like the correct one to use). This leads to the following exception because the succeeded ones are removed from the hashset. https://github.com/aspnet/Security/blob/1867eab2e99d6828dda20e29483a0821de8e9ce9/src/Microsoft.AspNetCore.Authorization/AuthorizationHandlerContext.cs#L92-L96

System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Collection was modified; enumeration operation may not execute.
  Source=System.Core
  StackTrace:
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at WebApplication1.TestAuthorizationHandler.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.<AuthorizeAsync>d__7.MoveNext()

Repro:
[WebApplication1.zip](https://github.com/aspnet/Security/files/1236172/WebApplication1.zip)

Steps to reproduce:
- Create ASP.NET Core 2.0 Web Project (in my case .NET 4.7, but that shouldn't matter)
- Add Authorization and change the policy to require Authentication
- Add AuthorizationHandler like below
- Run and wait for Exception

```csharp

    public class TestAuthorizationHandler : IAuthorizationHandler
    {
        public Task HandleAsync(AuthorizationHandlerContext context)
        {
            foreach (var contextPendingRequirement in context.PendingRequirements)
            {
                context.Succeed(contextPendingRequirement);
            }
            return Task.CompletedTask;
        }
    }
```

Workaround:
- ``ToList()``
- Use ``Requirements`` instead of ``PendingRequirements``

**Comment by Eilon** [comment]
We could change this property to return a copy of the collection:
https://github.com/aspnet/Security/blob/1867eab2e99d6828dda20e29483a0821de8e9ce9/src/Microsoft.AspNetCore.Authorization/AuthorizationHandlerContext.cs#L60

**Comment by Eilon** [comment]
In the meantime, please use the workaround. Thanks for the report!

**Comment by Eilon** [comment]
Closing because we are not planning on making this change.
