### ISSUE TITLE
Refactor some of external login out of Identity and into Security

### ISSUE THREAD

**Issue by jeffputz** [aspnet/Security#1377]
[Enhancement request]

I find myself generally skipping on Identity for any non-trivial project (or any not using EF), but I love having the plumbing for the external logins (Google, Facebook, etc.). There are two things that make this feel harder than it should be:
* You need to write a bit of plumbing code to land and process the callback before rolling any persistence. In the default project templates currently shipping, there are three methods in the `AccountController` that are involved.
* Stuff that isn't necessarily specific to Identity exists in its `SignInManager` class and associated container classes. `GetExternalLoginInfoAsync()` is the biggest part, `ConfigureExternalAuthenticationProperties()` is another.
* Moving the `Challenge()` method into `ControllerBase` was a step in the right direction. :)

If I were coming up with some kind of design acceptance criteria, I'd want:
* `SignInManager.ConfigureExternalAuthenticationProperties()` sets up the callback, and `SignInManager.GetExternalLoginInfoAsync()` processes the callback, both are moved to Security, so I don't need a dependency on Identity. This packages everything that I want to know: the auth provider and the resulting principle and claims, so I can persist the data and associate it with my own user data. There isn't any obvious reason to me that this should be in Identity.
* The above probably takes a scheme as a parameter, as Identity uses its own constants for that.
* `ExternalLoginInfo` is moved into Security.

The current workaround is to look at the source of Identity and pull out the above parts into your own solution.

**Comment by Eilon** [comment]
This sounds like a reasonable request, but it is not a high priority at this time, so we are putting it in the backlog.

**Comment by Eilon** [comment]
Closing because we are not planning to implement this.
