### ISSUE TITLE
Should RemoteAuthenticationOptions validate SignInScheme != null?

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#1378]
This should validation was lost at some point, SignInScheme is required for remote auth.

**Comment by HaoK** [comment]
Or maybe we removed this validation to enable calling the default sign in scheme...

**Comment by davidfowl** [comment]
Can we also validate and SignInScheme != Scheme, are the schemes stored on the instances of the handlers themselves?

**Comment by HaoK** [comment]
We will likely have to validate that outside of the normal validation (not AuthenticationSchemeOptions.Validate, but inside of the base RemoteAuthenticationHandler itself to have access to the scheme name, and we'd likely have to also explicitly check for when its the default that fallback to itself as well.

**Comment by PinpointTownes** [comment]
> Can we also validate and SignInScheme != Scheme, are the schemes stored on the instances of the handlers themselves?

Exactly what I had recommended here: https://github.com/aspnet/Security/issues/1264#issuecomment-309100351

> We will likely have to validate that outside of the normal validation

You can easily do that in `EnsureSignInScheme` as you have access to both names: https://github.com/aspnet/Security/blob/488eb44467eb677eab62bdc49aa6255cc1be3119/src/Microsoft.AspNetCore.Authentication/AuthenticationServiceCollectionExtensions.cs#L98-L101

**Comment by Tratcher** [comment]
Related issue to address:
https://github.com/aspnet/Security/blob/488eb44467eb677eab62bdc49aa6255cc1be3119/src/Microsoft.AspNetCore.Authentication/AuthenticationServiceCollectionExtensions.cs#L98-L101
There should be an additional `?? _authOptions.DefaultScheme;` for when DefaultSignInScheme isn't set. That's what was starting some of the stack overlfows by passing nulls.

**Comment by HaoK** [comment]
b9d9418f6d4fecd8e3b0c60538bb985c15e31fcc
