### ISSUE TITLE
AuthenticationProperties allows non-local redirect URLs

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#1382]
Is there a scenario where this should be allowed? (because it is)

``
var props = new AuthenticationProperties
{
    RedirectUri = "https://evil.com
};
``

**Comment by HaoK** [comment]
How are you consuming the redirect Uri?  Cookies typically blocks absolute uris https://github.com/aspnet/Security/blob/23da47617624cfed065cd1cdd552d34e5ea5b821/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L377

**Comment by leastprivilege** [comment]
I am using it as a redirect URI for Google authN challenge.

It indeed redirects me to evil.com after google is done.

**Comment by HaoK** [comment]
@Tratcher @blowdart should the OAuth handler be blocking absolute redirect uris in the challenge similar to cookies which has a IsHostRelative check?  Doesn't look like this ever had a check going back to the Katana days

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OAuth/OAuthHandler.cs#L195

**Comment by PinpointTownes** [comment]
That's deliberate: the `AuthenticationProperties.RedirectUri` property is assumed to be set and controlled by the developers themselves. If you rely on user input, you're responsible of validating it first (which is no different than returning `return Redirect([user-provided URL])` in MVC).

Related: https://github.com/aspnet/Security/pull/940 and https://github.com/aspnet/Security/pull/943.

**Comment by leastprivilege** [comment]
Sure - but is it needed to have that feature?

**Comment by PinpointTownes** [comment]
Why not? It's even quite common (e.g you can have your login stuff hosted at `https://login.domain.com/` and redirect the user agent to `https://www.domain.com/` when the authentication flow is done... and for that, you need to use absolute URLs).

Plus changing that at this point would be a (big) breaking change.

**Comment by leastprivilege** [comment]
> Why not?

Just asking - because you know it all :P

**Comment by PinpointTownes** [comment]
"Sarcasm is the lowest form of wit, but the highest form of intelligence" - Oscar Wilde :four_leaf_clover: 

Joking aside, I knew that because I'm the guy who recommended making the `RedirectUri` handling consistent in the cookies handler: https://github.com/aspnet/Security/pull/940#r74350492 (and additionally, I've since used this pattern a few times in 1.1 :trollface:)

**Comment by blowdart** [comment]
Wait, so changing this would break @PinpointTownes? This seems a win all around. :trollface:

**Comment by Eilon** [comment]
I agree with the comments in https://github.com/aspnet/Security/issues/1382#issuecomment-324332727.

Disallowing this would be a breaking change and I think there's little value in the change.
