### ISSUE TITLE
Configure claims filtering/mapping for OpenID Connect middleware

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#1386]
I saw you filter out a bunch of OIDC protocol claims now - that's generally good - but `amr` is gone, and that is important information for some clients.

Also you still do this funny mapping to MS proprietary claim types.

* what's the best way to control what claims you filter
* is there a *nicer* way to turn off claim mapping besides calling a global static?

**Comment by Tratcher** [comment]
The claim filtering is via OpenIdConnectOptions.ClaimActions. If you want to keep amr you can remove that filter via `options.ClaimActions.Remove("amr");`
https://github.com/aspnet/Security/blob/5b29bced0d2f1cfc78843bcd9ec9a828c6fb5fef/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L47

The proprietary claim type mapping you're asking about all takes place at the IdentityModel layer. @brentschmaltz ?  That said, you could try re-mapping them using ClaimActions.

**Comment by Tratcher** [comment]
There was some debate on this before: https://github.com/aspnet/Security/pull/1297

**Comment by brockallen** [comment]
So then that's 2 votes for amr.

**Comment by HaoK** [comment]
This is now just a question of the default behavior right?  People who want to preserve amr would just have to add options.ClaimActions.Remove("amr") to there `AddOpenIdConnect()`.  That doesn't seem too much of a burden if most people don't care about amr.

**Comment by HaoK** [comment]
Note: @Tratcher maybe we should consider adding some sugar/renaming the public API for the claimactions, its pretty counter intuitive to read with no context.

**Comment by Eilon** [comment]
Do we have specific examples where this would be used? I think we're hearing a lot of "someone might think it's interesting" but it's not clear if it rises from "interesting" up to "actual need."

From the previous threads on this, it sounds like everyone agrees that "extraneous" claims shouldn't be included because of issues such as cookie size. We just need to debate which bucket some particular claims fall into.

**Comment by brockallen** [comment]
"amr" lets the app know what you used to authenticate, password for example. Let's say the use then tries to modify their account and the app then wants stronger authentication to do so, like 2FA. The amr lets the app know these things.

**Comment by leastprivilege** [comment]
`amr` is essential metadata about the authentication event.

**Comment by Eilon** [comment]
Ah, ok, that scenario makes a lot of sense.

Having said that, it's not a *super* common scenario from what I've seen in apps. I think the only site I've really seen do anything like that is where GitHub doesn't "trust" the session login cookie to change "dangerous" settings and forces you to re-enter a password. I can't think of any other site I've seen that does anything like that.

So from my own perspective, this seems relatively rare in terms of usage, and for whoever needs it, it's 1 line to bring back the `amr` claim.

How do we strike the balance between bloating cookie sizes (which people agree on), compared to scenarios that aren't so common?

**Comment by leastprivilege** [comment]
I'd draw the line between at the claims that are def only protocol specific and have no-use for the application - e.g. issuer, exp, nbf, nonce etc ...

amr i think is useful.

**Comment by PinpointTownes** [comment]
@leastprivilege I don't think it's as easy as you describe. Even protocol claims can be potentially useful for some scenarios. E.g I could use the `iat`/`nbf` claim to determine when the OIDC flow was initiated and decide whether my users need to re-authenticate to access security-critical parts of my app based on this information. Same reasoning for `auth_time`.

**Comment by leastprivilege** [comment]
True.

`ClaimActions.DeleteClaim("amr");` 

is def a super counter-intuitive way of saying "keep the amr claim" ;)

**Comment by PinpointTownes** [comment]
> `ClaimActions.DeleteClaim("amr");` is def a super counter-intuitive way of saying "keep the amr claim" ;)

I couldn't agree more: https://github.com/aspnet/Security/pull/1297#issuecomment-313766969.

I remember @Tratcher pinged me when he introduced the "claims actions" but frankly, I wasn't really inspired to find a better API. Maybe that would be worth reworking it in 2.1 or 3.0? (even the layering isn't perfect, because the OIDC now has to reference the OAuth2 package).

**Comment by leastprivilege** [comment]
Well - in our libs we had a simple array of strings - called `ClaimsToFilter` or similar. 

super simple - not over engineered.

**Comment by Tratcher** [comment]
It's `options.ClaimActions.Remove("amr");` ...

**Comment by brentschmaltz** [comment]
FWIW, JwtSecurityTokenHandler provides the ability to filter claims from ending up inside the ClaimsIdentity. 

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L170

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
