### ISSUE TITLE
[Suggestion] Improve CookieSessionSample

### ISSUE THREAD

**Issue by glatzert** [aspnet/Security#1393]
The Cookie Session Sample https://github.com/aspnet/Security/tree/dev/samples/CookieSessionSample does not use DI, the sample should show, how to use a DI aware SessionStore.

**Comment by Tratcher** [comment]
There isn't a built in way to resolve it from DI, you'd have to resolve it manually by calling GetRequiredService when configuring the options.

**Comment by glatzert** [comment]
I would do that, but GetRequiredService<...>() is not available on `ServiceCollection`

**Comment by davidfowl** [comment]
Isn't it on the cookie options? You wouldn't manually call GetService, there's a pattern for DI when using options.

**Comment by glatzert** [comment]
It's on the Options indeed - can you point to that pattern?

**Comment by davidfowl** [comment]
@glatzert here you go https://github.com/davidfowl/AuthCookieOptions

**Comment by glatzert** [comment]
@davidfowl thank you! I _really_ appreciate providing that sample. I'll put it to good use 👍 - Besides the SessionStore the Events will probably take advantage of that, too :)

Also I think this would make a nice sample for the docs somewhere near "Fundamentals > Configuration > Advanced Option Scenarios"?

**Comment by davidfowl** [comment]
> Also I think this would make a nice sample for the docs somewhere near "Fundamentals > Configuration > Advanced Option Scenarios"?

I already pinged @HaoK about that.

**Comment by Eilon** [comment]
Closing this issue because we're working on documentation for this area in this issue: https://github.com/aspnet/Docs/issues/4055
