### ISSUE TITLE
How to Return 403 Forbidden by Forbid() when using Windows Authentication?

### ISSUE THREAD

**Issue by WilliamWsyHK** [aspnet/Security#1396]
Hey guys,

I want to have my ASP.NET Core MVC app to use Windows Authentication (since it is an intranet app) to let users to enter the site without login, but only allow certain roles to access **_some_** of the pages.

Here is the Startup.cs
``` CSharp
public void ConfigureServices(IServiceCollection services)
{
    // skip
    services.Configure<IISOptions>(options =>
    {
        options.AutomaticAuthentication = true;
        // options.ForwardWindowsAuthentication = true;
    });
    
    // services.AddAuthentication(IISDefault.AuthenticationScheme);
    services.AddAuthentication(options =>
    {
        options.DefaultScheme = IISDefaults.AuthenticationScheme;
        options.DefaultAuthenticationScheme = IISDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = IISDefaults.Negotiate;
        options.DefaultForbidScheme = IISDefaults.AuthenticationScheme;
    });
    services.AddAuthorization(options =>
    {
        options.AddPolicy("Admin", policy => policy.RequireRole(@"DOMAIN\Domain Admins"));
    });
    // skip
}
```

And AdminController.cs (for whole controller needed to authorize)
```CSharp
[Authorize(Policy = "Admin")] // <------ returned HTTP/1.1 200 OK, but 403 Forbidden wanted.
public class AdminController : Controller
{
    // ctor omitted
}
```

And HomeController.cs (only some of the action requires elevated access)
```CSharp
public class HomeController : Controller
{
    /* Here either using AuthorizeAttribute, or inside action, the result of HTTP 403 Forbidden are turned into HTTP 200 OK */
    [Authorize(Policy = "Admin")] // <------ returned HTTP/1.1 200 OK, but 403 Forbidden wanted.
    public IActionResult ViewLog()
    {
        // You can try comment the following if block when using AuthorizeAttribute;
        // Or comment AuthorizeAttribute and use the following if block
        if (User.IsInRole(@"DOMAIN\Domain Admins"))
        {
            return Forbid();  // <------ returned HTTP/1.1 200 OK, but 403 Forbidden wanted.
        }
        // does not matter
    }
}
```

(Enough for the code)
For a user without admin access and try to view those page requiring elevated access, the result viewed in upstream middleware of this action is that the action thrown System.InvalidOperationException, stating that "One or more errors occurred. (No authenticationScheme was specified, and there was no DefaultChallengeScheme found.)", but you can see this option is set in Startup.cs, so I am wondering
1. Why this exception is still be thrown; and
2. When exception is thrown, why is the status code will be 200????

**Comment by WilliamWsyHK** [comment]
Oh, to complete the story, here is some runtime info
Run debug mode in VSCode (MSBuild 15.3)
`dotnet --version` 2.0.0

**Comment by Tratcher** [comment]
For 2.0 IISDefaults.Negotiate is no longer used, you only need to specify `options.DefaultScheme = IISDefaults.AuthenticationScheme;`. The 200 is concerning. Are you getting the full content or something else? I wonder if you're getting an exception and are sent to the error page or similar.

**Comment by Tratcher** [comment]
Or just `services.AddAuthentication(IISDefaults.AuthenticationScheme)`

**Comment by WilliamWsyHK** [comment]
@Tratcher 
For `services.AddAuthentication(IISDefaults.AuthenticationScheme)` I tried and still the same (and the "Step-Into" source code of this statement is only available when looking at dev branch, so I decided to write those lines for `AddAuthentication` after viewing the source)

For the 
> The 200 is concerning. Are you getting the full content or something else? I wonder if you're getting an exception and are sent to the error page or similar.

I just got a blank page with HTTP 200, the exception is viewed via middleware, just before the controller action.
```CSharp
result = await _next(context);
// result has properties Exception and Exceptions
// so the Exception of the result can be viewed thru debugger
```
And this is how `One or more errors occurred. (No authenticationScheme was specified, and there was no DefaultChallengeScheme found.)` comes out from the exception.

**Comment by Tratcher** [comment]
Is Windows Auth actually enabled in IIS/Express? 2.0 checks for that.

**Comment by WilliamWsyHK** [comment]
Hmm, I was using Kestral as the server, and not deployed to IIS yet... Will try it later.

Anyway, I was using some workaround by adding a `if` in the actions to limit only those users with allowed roles to access.

**Comment by Tratcher** [comment]
Kestrel doesn't have Windows Auth....

**Comment by WilliamWsyHK** [comment]
I just use VSCode to run the debug (default settings of launch.json, no special stuffs added). So I guess it should be Kestrel; and it successfully do the SSO, getting the user via `System.Security.Principal.WindowsIdentity.GetCurrent();`, and make a middleware to inject this `ClaimsPrincipal` to `HttpContext`.

**Comment by Tratcher** [comment]
The Startup code you provided above does not add any auth handlers, and ASP.NET Core does not set WindowsIdentity.GetCurrent();. You're getting the identity the process is started under, not the remote user. What SSO are you referring to? There was nothing in your Startup.

**Comment by WilliamWsyHK** [comment]
Yes that's true the process is running using the account's identity, while using Kestrel-only scenario.
And I had deployed to the environment with IIS+Kestrel, and the application can eventually use the real Windows' identity of the user.

But lets get back to the question: the workaround (posted in some previous comment) is not working as expected, and I still not tried to use the `[Authorize(Policy = "Some Policy")]`; get back to you soon after the trial.

Thanks anyway.

**Comment by Tratcher** [comment]
Your policy definition appears to be missing `RequireAuthenticatedUser()`. @HaoK that's required in addition to RequireRole right?

**Comment by HaoK** [comment]
Well what's required is up to the app, but:

`RequireAuthenticatedUser` basically just adds a check for `User.Identity.IsAuthenticated`
`RequireRole` is a check on `User.Identity.IsInRole`

**Comment by philip-reed** [comment]
I have been battling with a similar issue, not sure if it is what you need, but adding Microsoft.AspNetCore.Server.IISIntegration from Nuget got rid of the error `No authenticationScheme was specified, and there was no DefaultChallengeScheme found`.  Might be worth a try.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
