### ISSUE TITLE
Support for OpenIdConnect prompt parameter

### ISSUE THREAD

**Issue by gb056** [aspnet/Security#1398]
This may be a duplicate of [Issue 99](https://github.com/aspnet/Security/issues/99).

It would be good if this could support the inclusion of the [prompt](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) parameter as part of the `OpenIdConnectOptions`. Similar to how we currently pass through the ResponseType, Resource etc.

The fix in this case may be as simple as adding `Prompt = Options.Prompt` [here](https://github.com/aspnet/Security/blob/f00efc46348c5e89d4c1665e6892427524069880/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L314) and adding a `Prompt` property to `OpenIdConnectOptions`.

Happy to do a PR on this if required.

**Comment by Eilon** [comment]
We would be happy to work with you on a PR for this!

We think adding a new `ICollection<string> Prompt { get; }` property would be great. It should be similar to the `Scope` property:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L212-L215

**Comment by brockallen** [comment]
Can we keep it as space delimited? The only reason scope was a collection was to normalize those in the ASP.NET programming model because of the inconsistencies in the OAuth2 implementations (mainly facebook as the oddball, IIRC). This is a whitespace delimited set of values and your MW will just pass it along verbatim. Is there really a need for a collection in the options?

**Comment by Eilon** [comment]
I guess it's a matter of which is easier to use. I don't have a strong feeling about it. Though it also might depend a bit on what any downstream APIs use in IdentityModel.

**Comment by Tratcher** [comment]
@brockallen Assigning more than one needs to be clean. How would you do that? Perhaps with constants that already contain the permutations?

**Comment by Tratcher** [comment]
OpenIdConnectResponseType does exactly that: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/f10a045459e7cb07548806561a47ecdb3471f5f6/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectResponseType.cs
We could ask IdentityModel for similar constants for Prompt.

**Comment by brockallen** [comment]
> I guess it's a matter of which is easier to use. I don't have a strong feeling about it. Though it also might depend a bit on what any downstream APIs use in IdentityModel.

9 times out of 10 you just want prompt=login

**Comment by gb056** [comment]
There are a few use cases for wanting to set this statically. Say the RP wants to add an extra layer of security to their site and force the user to log in specifically for them rather than just reusing a cookie obtained when logging in to another RP. We have a few different sites that currently force this flow in PHP, it would be nice for it to be supported here too.

Use cases aside, it's in the spec as an option so in my view should be supported by the library regardless of whether the consumer wants to do it per challenge or globally for the provider. At the end of the day, that's just my view and I'm new here so I'll obviously bow to the consensus on the issue.

Using constants for the permutations seems would get my vote in this case as there aren't many combinations. A list seems a bit bloated for maximum 8(?) combinations.

**Comment by HaoK** [comment]
Instead of constants for every combination, why not a suboptions?

```C#
OIDCOptions.PromptOptions Prompt { get }

class PromptOptions {
   bool Login
   bool Consent
   bool None
   bool select_account
}
```

**Comment by gb056** [comment]
It should be made as hard as possible to set `none` with any of the other options as it's invalid, and constants are already used for `ResponseType` and `ResponseMode` so it would fit with the pattern.

**Comment by Tratcher** [comment]
@gb056 None is invalid? It's listed right in the spec.

@HaoK No, it needs to be extensible. I suspect @brockallen is right, multiple values are likely rare so we're probobly overthinking it.

**Comment by brentschmaltz** [comment]
@Tratcher @HaoK  IdentityModel has defined a set of OIDC prompts see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectPrompt.cs#L33

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/pull/1401 looks fine and the constants already exist. I agree that the app will usually set only one value, but we can ask for other constants if we see common combinations.

**Comment by brentschmaltz** [comment]
@Tratcher for scenarios where multi-value is required, one could use extensibility to set the request.
It's rare enough.

**Comment by Tratcher** [comment]
Extensibility? I was just expecting them to set `options.Prompt = OpenIdConnectPromt.Login + " " + OpenIdConnecPrompt.Consent;`

**Comment by brentschmaltz** [comment]
@Tratcher that will work too. I was thinking they could do this with todays bits with OnRedirectToIdentityProvider

**Comment by Tratcher** [comment]
Ah, yes, but those take much more effort to use.

**Comment by brentschmaltz** [comment]
I agree with you 100%.

**Comment by Tratcher** [comment]
Related: https://github.com/aspnet/AspNetKatana/pull/81/files
