### ISSUE TITLE
2.0: IClaimsTransformation runs each time AuthenticateAsync is called

### ISSUE THREAD

**Issue by brockallen** [aspnet/Security#1399]
Perhaps related or dup of: #1395 (I can't tell).

`AuthenticateAsync` caches the result from the authentication handler, but the outcome of claims transformation is not cached. IOW, if I call:

```
await HttpContext.AuthenticateAsync();
await HttpContext.AuthenticateAsync();
```

Then claims transformation is invoked twice (and given how implemented, could easily be duplicating claims in the principal).

Is that design intentional?

**Comment by brockallen** [comment]
This would also happen if (for whatever reason) the Authentication middleware were registered twice in a pipeline.

**Comment by HaoK** [comment]
That is indeed the current behavior, your claims transformer could check if its already added the claims before adding them again to prevent duplication.  We can definitely consider adding some kind of switch to prevent transformation from running twice in the future

**Comment by brockallen** [comment]
> That is indeed the current behavior

But not clear if it's by design or not :)

Anyway, the moral of the story here is to return a new ClaimsPrincipal from the transformer. Perhaps that should be mentioned in the docs/FAQ/whatever.

**Comment by brockallen** [comment]
Another idea would be to put a flag on the authentication service to cache the results of claims transformation (and make sure it's scoped in DI if it's not already). I think it's fair to say that setting this flag to cache by default wouldn't be a huge concern in a 2.1 release.

**Comment by Eilon** [comment]
In this scenario we have two suggestions:

1. Instead of modifying the claims principal, always return a new one (as mentioned above)
2. Add a custom "marker" claim that indicates whether the transformation was done. Check that claim prior to running transformation

I logged https://github.com/aspnet/HttpAbstractions/issues/936 to improve the doc comments for item (1).
