### ISSUE TITLE
OAuthBearerAuthenticationNotifications.SecurityTokenValidated is never triggered

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#140]
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Security.OAuthBearer/OAuthBearerAuthenticationHandler.cs#L134-L148

/cc @brentschmaltz @Tratcher

**Comment by brentschmaltz** [comment]
Thanks.

**Comment by PinpointTownes** [comment]
@brentschmaltz I'm preparing a PR for that. The fix is really trivial but I realized that the OAuth2 Bearer middleware tests weren't not totally effective (they just check if the response status code is 200).

**Comment by PinpointTownes** [comment]
Here we go: https://github.com/aspnet/Security/pull/142

**Comment by HaoK** [comment]
Merged 4a2a742ad5e52b2f9e0529b8c6f5f9decd3e80f0
