### ISSUE TITLE
LogLevels in Microsoft.AspNetCore.Authentication/LoggingExtensions.cs

### ISSUE THREAD

**Issue by x2764tech** [aspnet/Security#1400]
As I get more experienced, I realise more and the more the important of careful logging to diagnose problems in live environments. 

With that in mind - I'm struggling to see the logic in the LogLevels used in `Microsoft.AspNetCore.Authentication/LoggingExtensions.cs`.

In my view, Authentication failed is at probably a warning, and Authentication succeeded is information, or probably even debug... Other people may have different views on this, but I can't see any particular logic in the way they're used in this component.

As these are logged using the Authentication middleware's logger, it's really difficult to filter them (especially if you have your own authentication middleware).

Could there be a way to customise these, or replace them?

**Comment by Eilon** [comment]
The log levels are defined as having meaning to someone going through logs to understand why/how something happened. As such, a "Warning" event means "something bad and unexpected happened, but the application was able to recover." You can see the definition of this log level here: https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/LogLevel.cs#L28-L32

A failed login is different from that. A failed login means "a user typed their password incorrectly," which is a pretty normal occurrence.

There is no way to change the log levels or messages, though given that the event names/ids/categories don't change (even across versions of the product), you could easily filter those via whatever logging system you use.
