### ISSUE TITLE
Azure AD v2.0 (Graph) Identity.Name not set

### ISSUE THREAD

**Issue by tbolon** [aspnet/Security#1402]
Hi,

I am trying to use the OpenID Connect library with [Azure AD v2.0](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-appmodel-v2-overview) endpoint(https://login.microsoftonline.com/{tenant}/v2.0). My end-goal is to also use the [MS Graph](https://developer.microsoft.com/en-us/graph/) api, so it requires that my app is registered in the new portal.

Everything works (you only need to append the /v2.0 to the sign in authority url), but the ClaimsIdentity.Name stays empty.

Browsing the claims set on the Identity, I get the following entries returned after authentication:

| Type | ShortTypeName |
|-|-|
| aio | |
| name | |
| http://schemas.microsoft.com/identity/claims/objectidentifier | oid |
| preferred_username | |
| http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier | sub |
| http://schemas.microsoft.com/identity/claims/tenantid | tid |

It seems that by default, ClaimsIdentity looks after a [ClaimTypes.Name](https://github.com/dotnet/corefx/blob/7f1c480a6a280fbced29606120b507596bafbefc/src/System.Security.Claims/src/System/Security/Claims/ClaimTypes.cs#L58) json type, which maps to `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name`.

Because the property is set using the shortTypeName directly, the name is not resolved and then not displayed.

My questions are:
- Is this behavior "normal" and supposed to be handled by the library (if not, I will certainly raise an issue to the Azure AD team) ?
- Is there any workaround to set this property ? I have tried to add `options.ClaimActions.MapUniqueJsonKey(System.Security.Claims.ClaimTypes.Name, "name");` on configuration, but it does not seems to work.

**Comment by blowdart** [comment]
@brentschmaltz how would you configure this?

**Comment by brentschmaltz** [comment]
@blowdart @tbolon I am not familiar with 'MapUniqueJsonKey'.
You are correct about how ClaimsIdentity.Name works.

I believe that TokenValidationParameters.NameClaimType set to 'name' would result in your result.
This would require you setting TVP on options.

What happens If set MapUniqueJsonKey("name", "System.Security.Claims.ClaimTypes.Name")?

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.
