### ISSUE TITLE
Ability to check if User passes given Policy

### ISSUE THREAD

**Issue by Mardoxx** [aspnet/Security#1404]
Imagine the following situation whereby you have a forum and want users to delete their own posts, but also allow certain users to delete others' posts determined by a policy.

```cs
[Authorize]
[HttpDelete]
public IActionResult DeleteComment([FromRoute] Guid commentId)
{
    var currentUserId = Guid.Parse(User.FindFirst(JwtClaimTypes.Subject).Value);
    var comment = _context.Comments.Get(x => x.Id == commentId);
    
    if (comment.CreatedBy == currentUserId || /* User.PassesPolicy(nameof(policyName)) */)
    {
        // do the delete
       return NoContent();
    }
    
    return Unauthorized();
}
```

How can this be achieved?

Either I'd want, `User.Check(string policyName);` for example, or an example of how to achieve a similar result using library methods.

[This](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies#accessing-mvc-request-context-in-handlers) seems to say you can access the request context, so from here would it be possible to build up a policy which takes a comment Id, but here we would have no access to `comment.CreatedBy` -- so this looks like a non-starter!

**Comment by Eilon** [comment]
Hi @Mardoxx we have a concept called resource-based authorization that is documented here: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased

Please check that out and let us know if you have questions.

cc @blowdart
