### ISSUE TITLE
Get the user's e-mail address from Twitter

### ISSUE THREAD

**Issue by AlexOliinyk1** [aspnet/Security#1405]
Hi

based on this issue https://github.com/aspnet/Security/issues/765 I'm tried to configure twitter social login to get email. 
But for now without any luck.

startup.cs code 

![image](https://user-images.githubusercontent.com/10448723/30035801-80c2287c-91b6-11e7-9ceb-caa085331582.png)

here error appear, email is null

![image](https://user-images.githubusercontent.com/10448723/30035835-df0e87ea-91b6-11e7-9c5d-f4294d470e59.png)

My twitter account already had required settings

![image](https://user-images.githubusercontent.com/10448723/30035849-fd7c2f84-91b6-11e7-866f-72a4334996a0.png)

**Comment by Tratcher** [comment]
I'm not able to repro this. It works fine for both 1.1 and 2.0 apps.

The code in your screenshot does not match the 1.1 templates. Try this:
```c#
        //
        // GET: /Account/ExternalLoginCallback
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
        {
            if (remoteError != null)
            {
                ModelState.AddModelError(string.Empty, $"Error from external provider: {remoteError}");
                return View(nameof(Login));
            }
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                return RedirectToAction(nameof(Login));
            }

            // Sign in the user with this external login provider if the user already has a login.
            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false);
            if (result.Succeeded)
            {
                _logger.LogInformation(5, "User logged in with {Name} provider.", info.LoginProvider);
                return RedirectToLocal(returnUrl);
            }
            if (result.RequiresTwoFactor)
            {
                return RedirectToAction(nameof(SendCode), new { ReturnUrl = returnUrl });
            }
            if (result.IsLockedOut)
            {
                return View("Lockout");
            }
            else
            {
                // If the user does not have an account, then ask the user to create an account.
                ViewData["ReturnUrl"] = returnUrl;
                ViewData["LoginProvider"] = info.LoginProvider;
                var email = info.Principal.FindFirstValue(ClaimTypes.Email);
                return View("ExternalLoginConfirmation", new ExternalLoginConfirmationViewModel { Email = email });
            }
        }
```

**Comment by AlexOliinyk1** [comment]
@Tratcher  I will try it and let you know. Thanks.

**Comment by AlexOliinyk1** [comment]
@Tratcher  Problem was secret manager uses old key. Sorry for this.

**Comment by ricsierics** [comment]
@Tratcher , may I ask if you are referring to .Net Core 1.1 and 2.0? If so, I would like to ask how to solve this in .Net standard (4.6.1)? My solution/project cannot resolve the type "TwitterOptions", only "TwitterAuthenticationOptions"

**Comment by Tratcher** [comment]
ASP.NET Core 1.1 and 2.0, which supports .NET Standard.

[TwitterAuthenticationOptions](https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/src/Microsoft.Owin.Security.Twitter/TwitterAuthenticationOptions.cs) is a much older version. What package are you using, Microsoft.Owin.Security.Twitter? No, it does not have this feature.

**Comment by ricsierics** [comment]
Yes, I'm using **Microsoft.Owin.Security.Twitter**. I tried to use the **TwitterOptions** by adding the **Microsoft.AspNetCore.Authentication.Twitter** in my MVC 5 project using Nuget. There's now compilation error "_cannot convert from Microsoft.AspnetCore.Authentication.Twitter.TwitterOptions to Microsoft.Owin.Security.Twitter.TwitterAuthenticationOptions_".

This code block is under **Startup.Auth.cs** and I have working external logins for Facebook and Google and I am trying to add Twitter. I guess I should stick to the older version or else the whole Owin middleware will have to change.

![image](https://user-images.githubusercontent.com/17517314/46992267-cdc02f00-d13b-11e8-9101-0a460e33718a.png)

**Comment by ricsierics** [comment]
Thanks @Tratcher , will do this. Sorry for commenting on an already closed thread
