### ISSUE TITLE
SAML2P authentication in .NET Core

### ISSUE THREAD

**Issue by Jenan** [aspnet/Security#1406]
Hello,

is there any implementation of SAML2P in .NET Core?

I would like to use the SAML2P as the Identity Provider on my project that is running on .NET Core.

Thank you.

**Comment by Tratcher** [comment]
@brentschmaltz is this related to the saml2 support coming in WsFed?

**Comment by brockallen** [comment]
If you're looking for SAML2-P support in ASP.NET Core, then you should look at: https://github.com/Sustainsys/authservices. They are working on a SAML2-P authentication middleware for ASP.NET Core.

**Comment by brentschmaltz** [comment]
@Tratcher Saml2 support is about tokens and wsFed. Samlp usually refers to Saml protocol which is in someways similar to OIDC or WsFed but much richer. 

We do not have a POR for Samlp.

**Comment by Eilon** [comment]
There are no plans to support it at this time due to lack of demand.

Can you share info on what service it is that requires SAML2P?

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
