### ISSUE TITLE
"WinHttpException: The connection with the server was terminated abnormally" on first sign on with Open Id Connect

### ISSUE THREAD

**Issue by darickc** [aspnet/Security#1407]
I will get a "WinHttpException: The connection with the server was terminated abnormally" error the first time the CallbackPath is run.  If I refresh the browser or even close the browser and try again, this does not happen.  It is only after it runs for the first time.  I can recycle to the app pool and it will give the error the first time it runs.  This does not happen when running against the full .Net framework either.

I have created my own middleware, inheriting from the open id connect middleware.  The only change I made was in the OpenIdConnectHandler class I overwrote the RedeemAuthorizationCodeAsync method to catch the error and to retry it, which works:

```c#
protected override async Task<OpenIdConnectMessage> RedeemAuthorizationCodeAsync(
            OpenIdConnectMessage tokenEndpointRequest)
        {
            try
            {
                return await base.RedeemAuthorizationCodeAsync(tokenEndpointRequest);
            }
            catch
            {
                return await base.RedeemAuthorizationCodeAsync(tokenEndpointRequest);
            }
        }
```

Why would this be throwing an error the first run?
Thanks

**Comment by Tratcher** [comment]
That's odd. The first request from the middleware to the IDP should be to get metadata. The login requests should reuse that connection.

Which auth provider are you using?

Also, what OS and package versions are you using? This may be an issue with HttpClient/WinHttpHandler.

**Comment by darickc** [comment]
No, I'm not hardcoding the metadata.  So it downloads it just fine.  It redirects the user to the IDP to login just fine.  It isn't until it is coming back from the IDP that the error happens.

The auth provider is WSO2.

This was happening in .Net core 1.1 and now in 2.0.  It happens when running in IIS in windows server 2008 R2.  I haven't been able to try it on any other versions of windows server.

**Comment by darickc** [comment]
This will also happens when running from IIS Express from Visual Studio and using dotnet run in windows.  It doesn't seem to be doing it when running dotnet run on a Mac.

**Comment by Tratcher** [comment]
This seems like an WinHttpHandler issue on Windows, but it may also be provider specific. I haven't seen this with AAD or Google.

Can you include the full stack trace?

**Comment by Tratcher** [comment]
Possibly related: https://github.com/dotnet/corefx/issues/21612

**Comment by darickc** [comment]
System.Net.Http.WinHttpException (0x80072EFF): The connection with the server was terminated abnormally
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()

And 

System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware.<ExecuteWithFilter>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by Eilon** [comment]
@Tratcher can you try to repro this using HttpClient directly? Then we can move to CoreFX if it seems like the right place.

**Comment by Tratcher** [comment]
@darickc can you share the urls accessed for the metadata and the token endpoint? Are they public?

**Comment by darickc** [comment]
They are public, but my boss would rather I didn't post them here, is there another way I can send it to you?

**Comment by Tratcher** [comment]
You can e-mail it to the address in my profile.

**Comment by Tratcher** [comment]
I'm using HttpClient on Win10 and .NET Core 2.0. I don't get quite the same error against your urls, but close. The first request succeeds and the second one fails.
```
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
{
  Date: Wed, 27 Sep 2017 17:38:40 GMT
  Accept-Ranges: bytes
  ETag: "61a141db4c2d21:0"
  Server: Microsoft-IIS/7.5
  X-Powered-By: ASP.NET
  Access-Control-Allow-Headers: *
  Access-Control-Allow-Origin: *
  Content-Length: 583
  Content-Type: application/json
  Last-Modified: Mon, 01 May 2017 19:49:58 GMT
}

Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server returned an invalid or unrecognized response
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ConsoleApp15.Program.HttpClientTest() in c:\temp\ConsoleApp15\ConsoleApp15\Program.cs:line 73
   at ConsoleApp15.Program.Main(String[] args) in c:\temp\ConsoleApp15\ConsoleApp15\Program.cs:line 14
Press any key to continue . . .
```

Multiple Get requests to your urls work, it's only the POST request that fails, and only if it's after a GET request.

If I drop down to sockets then I see that the first request works fine and then I get disconnected after sending the second request. If I only send the second request then it also works fine. The net461 client handles this a little better, it retries the request on a new connection but only if the server hasn't drained the request body (no idea why).

I'd be curious to see why the server disconnects the POST request. Any chance you could ask the admins? The server is definitely not behaving as expected.

For my own repro app I set up the server to always cancel the second request. .NET Core HttpClient does not handle this well regardless of if the second request is a GET or a POST. net461 will automatically retry GETs, and some POSTs due to a possible race condition based on how much of the request body the server reads.

Repro code (minus tls):
```
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Net.Security;
using System.Net.Sockets;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp15
{
    class Program
    {
        static void Main(string[] args)
        {
            RunServer();
            HttpClientTest();
            // TestSockets();
        }

        private static void RunServer()
        {
            var server = new HttpListener();
            server.Prefixes.Add("http://localhost:8080/");
            server.Start();

            Task.Run(() =>
            {
                var context = server.GetContext();
                Console.WriteLine("Server received: " + context.Request.HttpMethod);
                context.Response.ContentLength64 = 11;
                context.Response.OutputStream.Write(Encoding.ASCII.GetBytes("Hello World"), 0, 11);
                context.Response.Close();
                
                context = server.GetContext();
                Console.WriteLine("Server received: " + context.Request.HttpMethod);

                // If you drain the request on net461 then you get an error on the client when aborting. Otherwise it retries. Race?
                var buffer = new byte[1024 * 10];
                var read = context.Request.InputStream.Read(buffer, 0, buffer.Length);
                Console.WriteLine("Server read: " + read);

                Console.WriteLine("Server Aborting.");
                context.Response.Abort();

                context = server.GetContext();
                Console.WriteLine("Server received: " + context.Request.HttpMethod);
                context.Response.ContentLength64 = 11;
                context.Response.OutputStream.Write(Encoding.ASCII.GetBytes("Hello World"), 0, 11);
                context.Response.Close();
            });
        }

        public static void HttpClientTest()
        {
            Console.WriteLine("Hello World!");

            var client = new HttpClient();
            var result = client.GetAsync("http://localhost:8080").Result;
            Console.WriteLine(result);

            result = client.GetAsync("http://localhost:8080").Result;
            Console.WriteLine(result);
            /*
            var tokenRequestParameters = new Dictionary<string, string>()
            {
                { "client_id", "Foo" },
                { "redirect_uri", "http://localhost" },
                { "client_secret", "bar" },
                { "code", "baz" },
                { "grant_type", "authorization_code" },
            };

            var requestContent = new FormUrlEncodedContent(tokenRequestParameters);
            
            var result2 = client.PostAsync("http://localhost:8080", requestContent).Result;
            Console.WriteLine(result2);*/
        }

        public static void TestSockets()
        {
            var client = new TcpClient();
            client.Connect("localhost", 8080);
            var stream = client.GetStream();

            Console.WriteLine("Connected");

            var request = "GET /.well-known/openid-configuration HTTP/1.1\r\nHost: localhost:8080\r\nConnection: Keep-Alive\r\n\r\n";
            var requestBytes = Encoding.ASCII.GetBytes(request);

            stream.Write(requestBytes, 0, requestBytes.Length);

            byte[] buffer = new byte[1024 * 10];

            var read = stream.Read(buffer, 0, buffer.Length);
            Console.WriteLine("Read: " + read);
            Console.WriteLine(Encoding.ASCII.GetString(buffer, 0, read));

            request = @"POST /token HTTP/1.1
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 106
Host: localhost:8080

client_id=Foo&redirect_uri=http%3A%2F%2Flocalhost&client_secret=bar&code=baz&grant_type=authorization_code";
            requestBytes = Encoding.ASCII.GetBytes(request);

            stream.Write(requestBytes, 0, requestBytes.Length);

            buffer = new byte[1024 * 10];
            read = stream.Read(buffer, 0, buffer.Length);
            Console.WriteLine("Read: " + read);
            Console.WriteLine(Encoding.ASCII.GetString(buffer, 0, read));
        }
    }
}
```
Next steps (ordered by effectiveness and TTL):
A) You can hook into the Backchannel option and add retries.
B) You can ask the admins why the server is disconnecting your POST requests.
C) We can add retries in the security handlers.
D) We can ask .NET Core about being more resilient to disconnects.

**Comment by darickc** [comment]
Interesting.  I'm not sure what we can do on the server side.  It is WSO2 and we are a little limited right now on linux admins being more of a .Net shop.  Making .NET Core more resilient would be nice though.

**Comment by Tratcher** [comment]
@glennc @rynowak this could be an interesting use of your new client factory.

**Comment by Eilon** [comment]
Closing because there are no plans to make changes in this scenario.
