### ISSUE TITLE
No IAuthenticationSignInHandler is configured to handle sign in for the scheme: Cookies in .NET core MVC application after Signin

### ISSUE THREAD

**Issue by pavanbanakar** [aspnet/Security#1409]
I receive  " IAuthenticationSignInHandler is configured to handle sign in for the scheme" on the Auth handler (Identity server) which is calling the AuthenticationHttpContextExtensions.SignInAsync . I am trying to call the Identity server which handles the signin for a .NET Core MVC app.

ConfigureServices method on the  MVC app

      ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            }).AddCookie()
            .AddOpenIdConnect(o =>
                {
                    o.SignInScheme = "Cookies";
                    o.ClientId = Configuration["oidc:clientid"];
                    o.ClientSecret = Configuration["oidc:clientsecret"]; // for code flow
                    o.Authority = Configuration["oidc:authority"];
                    o.ResponseType = Configuration["oidc:responsetype"];
                    o.GetClaimsFromUserInfoEndpoint = true;
                    o.SaveTokens = true;

                    o.Events = new OpenIdConnectEvents()
                    {
                        OnAuthenticationFailed = c =>
                        {
                            c.HandleResponse();

                            c.Response.StatusCode = 500;
                            c.Response.ContentType = "text/plain";

                            return null;
                        },
                        OnMessageReceived = c =>
                        {
                            var l = c.HttpContext;
                            return null;
                        }
                    };
                    o.Scope.Clear();
                    o.Scope.Add("openid");
                    o.Scope.Add("profile");
                });

            services.AddMvc();

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            //JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseAuthentication();

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}

The Login method on the Identity server has the following code which throws the exception

  
                  var user = _users.FindByUsername(model.Username);
                    //cookie login
                    
                    //step 1:create one claims 
                    var claims = new List<Claim>();
                    claims.Add(new Claim(ClaimTypes.Name, user.Username));
                    
                   
                    //step2 create ClaimsIdentity and ClaimsPrincipal
                    var userIdentity = new ClaimsIdentity(claims, "Password");

                    var userPrincipal = new ClaimsPrincipal(userIdentity);

                    //step3 login

                    await AuthenticationHttpContextExtensions.SignInAsync(this.HttpContext, CookieAuthenticationDefaults.AuthenticationScheme, userPrincipal);

**Comment by Tratcher** [comment]
Side note: Do not return null from OpenIdConnectEvents events. The return parameter is Task, so make your lambda async or return Task.CompletedTask.

**Comment by Eilon** [comment]
Hi @pavanbanakar can you provide more info about this? Could you upload your app to a GitHub repo so we can take a look?

**Comment by pavanbanakar** [comment]
Hey @Eilon Here is the link for the repository https://github.com/pavanbanakar/cassini

**Comment by Tratcher** [comment]
Your basic problem is that IdentityServer4 uses different scheme names for their cookies.
https://github.com/pavanbanakar/cassini/blob/9a26aa6d2a10821de89014b2c8f13d32a38d62fb/Cassini.IDP/Quickstart/Account/AccountController.cs#L110
Should use `IdentityServerConstants.DefaultCookieAuthenticationScheme`
https://github.com/IdentityServer/IdentityServer4/blob/53f20267d9d1858869c7cce1810f8062c2b06c6f/src/IdentityServer4/Configuration/DependencyInjection/BuilderExtensions/Core.cs#L53
