### ISSUE TITLE
Implement an Auth 1.0 login provider

### ISSUE THREAD

**Issue by xrkolovos** [aspnet/Security#1411]
Implement an Auth 1.0 provider.

thank you

**Comment by davidfowl** [comment]
Why?

**Comment by xrkolovos** [comment]
:) 
Because I have come with 2 cases that are still using Auth 1.0. Twitter was using it 1 year ago.

**Comment by davidfowl** [comment]
Can you be more specific? What exactly are you asking for? Do you need to write an oauth 1.0 server?

**Comment by xrkolovos** [comment]
I though "Provider" is the write name. I am talking about this https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNetCore.Authentication.OAuth.
The clients that connect to an OAuth 1.0 server

**Comment by Tratcher** [comment]
Twitter uses OAuth 1.0a. You're asking for a generic version that you can use with other services? What services?

If there are just a few then I recommend copying the Twitter code. There's little incentive to go back and improve support for obsolete protocols.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this. The OAuth 1.0 protocol is very old at this point and we've seen almost no demand for it. You should be able to fairly easily get something working by copying any existing OAuth 1.0-based provider and modify it for your needs.
