### ISSUE TITLE
Support for OpenId Key Discovery in 2.0

### ISSUE THREAD

**Issue by glennsills** [aspnet/Security#1413]
I see that there is planned work to improve the usability of Jwt Bearer tokens in the  [2.1.0,](https://github.com/aspnet/Security/milestone/25)  milestone but is there any support for OpenId Key discovery in 2.0. Do I need to write my own token validator?

**Comment by leastprivilege** [comment]
This is built-in. Set the `Authority` property and it will try to find the OpenID discovery document.

**Comment by Eilon** [comment]
Yup, this exists. See @leastprivilege 's comment.
