### ISSUE TITLE
User.Identity.IsAuthenticated is False after upgrading to .Net Core 2

### ISSUE THREAD

**Issue by radenkozec** [aspnet/Security#1414]
After I call 
`var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);`
which results in successful. 
`User.Identity.IsAuthenticated` 
is always false.

I have this in ConfigureServices:
```
    services.AddAuthentication(sharedOptions =>
	        {
				sharedOptions.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
		        sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
			});



			services.AddSession();
	        services.AddMemoryCache();


			services.AddMvc()
		        .AddRazorPagesOptions(options =>
		        {
			        options.Conventions.AuthorizeFolder("/Account/Manage");
			        options.Conventions.AuthorizePage("/Account/Logout");
		        });

```

and this in Configure:
```
app.UseSession();
app.UseAuthentication();
```

**Comment by Tratcher** [comment]
_signInManager is part of the Identity system. You shouldn't need AddAuthentication if you have AddIdentity.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Security/issues/1338

**Comment by Tratcher** [comment]
And https://github.com/aspnet/Identity/issues/1364

**Comment by radenkozec** [comment]
@Tratcher You are right. When I removed AddAuthentication it works fine. Thanks
