### ISSUE TITLE
.net core 2.0 Authentication

### ISSUE THREAD

**Issue by blowdart** [aspnet/Security#1418]
_From @chintan3100 on September 12, 2017 14:53_

I have upgrade code 1.1 to 2.0.

We have used app.UseJwtBearerAuthentication and app.UseCookieAuthentication both Authentication.

How i can set both authentication in 2.0. It's looks like only one authentication working at a time.

    services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
             .AddCookie(options =>
             {
                 options.Cookie.Name = JWtToken.CookieName;
                 options.TicketDataFormat = new CustomJwtDataFormat(
                     SecurityAlgorithms.HmacSha256,
                     TokenValidationParameters,
                     authenticationService);
             });
             services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
                options.SaveToken = true;
                options.TokenValidationParameters = TokenValidationParameters;
                options.RequireHttpsMetadata = false;
                options.Events = new JwtBearerEvents
                {
                    OnTokenValidated = async (context) =>
                    {
                        // Add the access_token as a claim, as we may actually need it
                        var accessToken = context.SecurityToken as JwtSecurityToken;
                        if (accessToken != null)
                        {
               
                        }
                    }
                };
            });

_Copied from original issue: dotnet/core#965_

**Comment by blowdart** [comment]
What are you trying to achieve? A single endpoint that accepts both cookies and bearer?

**Comment by mubarakadeimam** [comment]
@chintan3100, I was able to use both Cookie and JwtBearer together using the approach below 

`public void ConfigureServices(IServiceCollection services)
{
   //Some codes here
   services.AddAuthentication()
       .AddCookie()
       .AddJwtBearer(options =>
       {
           options.RequireHttpsMetadata = false;
           options.SaveToken = true;
           options.TokenValidationParameters = tokenValidationParameters;
       });
}
`

**Comment by blowdart** [comment]
Having an extra services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme) shouldn't matter though.

**Comment by Tratcher** [comment]
@mubarakadeimam when neither are provided, which challenge do you want to issue? The 301 or 401?

**Comment by mubarakadeimam** [comment]
@Tratcher, I want Cookie as default and JwtBearer when explicitly specifies.

I added this

```services.AddAuthorization(options =>
            {
                options.AddPolicy("Authenticated", policy =>
                {
                    policy.AddAuthenticationSchemes(
                        JwtBearerDefaults.AuthenticationScheme,
                        CookieAuthenticationDefaults.AuthenticationScheme)
                        .RequireAuthenticatedUser()
                        .Build();
                });
            });
```
in my `ConfigureServices``` hoping to have `[Authorize(policy: "Authenticated")]` on my controller.

This currently only works for JwtBearer, which makes me think the problem is from the `CookieAuthentication`

**Comment by Tratcher** [comment]
@HaoK is there any policy that lets you specify multiple Authenticate schemes but only one challenge?

**Comment by HaoK** [comment]
Not in 2.0, that's why we are adding AuthenticationPolicies in 2.1 so you can accomplish exactly that, different sets of schemes per action

**Comment by Tratcher** [comment]
That said, it's fishy that both would be used on the same endpoint. I would expect JWT for APIs and cookies for interactive endpoints. What kind of endpoint is it?

**Comment by davidfowl** [comment]
This is why multiple challenges are broken 😬.

**Comment by chintan3100** [comment]
Below are practical senari.
We created web api project some of api consume by other window application which use Bear Authentication.
We have UI project (Angular 4.0) which used cookie authentication.

This is working fine in .net core 1.1. but in 2.0 we can only enable default one authenticaion at a time.

Any work around to resoved this issue ?

**Comment by HaoK** [comment]
Have two different endpoints, one for APIs and one for the UI project which uses cookies instead of a single one for both

**Comment by chintan3100** [comment]
Yes, I have two different controller one use Bear Authentication and other use cookie but to configure this different authentication in .net core 2.0.
can you please provide code ?

**Comment by HaoK** [comment]
You just need to setup a policy for each controller's authorize to use, something like this:

```
                options.AddPolicy("Bearer", policy =>
                {
                    policy.AddAuthenticationSchemes(
                        JwtBearerDefaults.AuthenticationScheme)
                        .RequireAuthenticatedUser()
                        .Build();
                });
                options.AddPolicy("Cookie", policy =>
                {
                    policy.AddAuthenticationSchemes(
                        CookieAuthenticationDefaults.AuthenticationScheme)
                        .RequireAuthenticatedUser()
                        .Build();
                });
```

`[Authorize("Bearer")]` or `Authorize["Cookies")] ` as appropriate

**Comment by chintan3100** [comment]
in .net core 1.1 i have used policy to define role in Authorization. 

` services.AddAuthorization(options =>
            {
                options.AddPolicy(EOPolicy.Engagement, policy => policy.RequireRole(UserType.Engagement));
                options.AddPolicy(EOPolicy.FirmUser, policy => policy.RequireRole(UserType.FirmAdmin));
                options.AddPolicy(EOPolicy.Organizer, policy => policy.RequireRole(UserType.Organizer));
                options.AddPolicy(EOPolicy.OrganizerLogin, policy => policy.RequireRole(UserType.OrganizerLogin));
                options.AddPolicy(EOPolicy.SysAdmin, policy => policy.RequireRole(UserType.SysAdmin));
                options.AddPolicy(EOPolicy.FirmUserOrOrganizer, policy => policy.RequireRole(UserType.FirmAdmin, UserType.Organizer));
                options.AddPolicy(EOPolicy.UserResetOrChangePass, policy => policy.RequireRole(UserType.UserResetOrChangePass));
                options.AddPolicy(EOPolicy.FirmUserOrOrganizerOrAdmin, policy => policy.RequireRole(UserType.FirmAdmin, UserType.Organizer, UserType.FirmAdmin));
            });`

**Comment by chintan3100** [comment]
Can i use like below code in 2.0
 [Authorize(Policy = EOPolicy.Engagement, AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]

**Comment by blowdart** [comment]
From a security PoV (and I realise this is being strict) you don't share the same API endpoints. Look at Gmail, the APIs it uses in the web site are not the apis available to mobile apps. There's a different attack surface, a different trust level, a different threat model. Is there a reason you can't just abstract the endpoints which then call the same service?

**Comment by HaoK** [comment]
@chintan3100 yes that should be fine

**Comment by mubarakadeimam** [comment]
@blowdart, If I get you right, Are you suggesting I should have seperate endpoints to handle requests from Cookie Authenticated Clients and JwtBearer Authenticated clients respectively?

**Comment by blowdart** [comment]
That's how I'd do it, but then I do care more about security than practicality, so feel free to reject it :)

**Comment by HaoK** [comment]
@mubarakadeimam  Yes, the idea the endpoints would be identical except for having different [Authorize] attributes, and they could just call into a common method

**Comment by mubarakadeimam** [comment]
Good @Haok, but won't you be a bit surprised if I tell you that `CookieAuthentication` don't work on endpoints using `Authorize(AuthenticationSchemes = "Cookies")` in ASP.NET Core 2.0?

**Comment by HaoK** [comment]
Define "don't work"

**Comment by mubarakadeimam** [comment]
@Haok, Take a look at the following:

```
services.AddAuthentication()
    .AddCookie("Cookies", options =>
    {
        options.Cookie.Name = "AuthCookie";
        options.Cookie.Domain = "localhost";
        options.Cookie.Path = "/";
        options.Cookie.HttpOnly = false;
        options.Cookie.SameSite = SameSiteMode.Lax;
        options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
   });
```
[Authorize(AuthenticationSchemes = "Cookies")]
public class MyController : Controller
{
     \\\
}
```
This is what I am talking about.

**Comment by davidfowl** [comment]
@mubarakadeimam did you mean the opposite? In your code sample there is no default so the latter example (no specified AuthenticationSchemes should fail).

**Comment by chintan3100** [comment]
Can you please share sample project in Github. Which has two different api use different authentication "Cookie" and "Bearer"

**Comment by mubarakadeimam** [comment]
@davidfowl, the work with no default works with Cookie, maybe due to AspNetCore Identity.

**Comment by chintan3100** [comment]
Solved issue :) :) :)
    var policy = new AuthorizationPolicyBuilder()
                .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme, CookieAuthenticationDefaults.AuthenticationScheme)
                  .RequireAuthenticatedUser()
                  .Build();

I have add policy to RequireAuthenticatedUser which has missing \

  .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme, CookieAuthenticationDefaults.AuthenticationScheme)

Thanks you all for your help

**Comment by chintan3100** [comment]
Please close issue

**Comment by kausett** [comment]
if someone is still looking for the solution to this issue.
the problem is from  AspNetCore Identity @codeprefect  you right. i took a look at the `httpContext` and check the Authentication parameter and i saw some `AutomaticSchema` on there. the value was set to `Identity.Application ` if you use that instead `CookieAuthenticationDefaults.AuthenticationScheme` it will work as intended other wise youll get a 401.
