### ISSUE TITLE
Bad Request - Request Too Long - Http Error 400

### ISSUE THREAD

**Issue by callranjithkani** [aspnet/Security#1419]
Hi,
Bad Request - Request Too Long - Http Error 400
Have you got answer, me too face this same issue, my sso proxy developed by asp.net core 1.1 and few client applications also developed by core  1.1 it working fine , if i try to implement 4.5.2 developed client app i faced Bad Request - Request Too Long Error, have any idea please let me know

My Response URI:

http://localhost:4000/connect/authorize?client_id=devtest&redirect_uri=http%3a%2f%2flocalhost%3a4002%2fsignin-oidc&response_mode=form_post&response_type=id_token+code&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dO3LnGgSMQdDkOZI9AxWTqT9183vBYw7YcEPAoRENX5Kg0zp6Qr4MBOI96fJ2rOFX64ka4S7zPwjezWfTZz6J7OQ_D-_eHbYSOamRdV8_BoRghBopcmwGXdGTKRuPTxilO9p3exS5NL6AjeydBZD-5o9eJxR_x46r43jAwvnN0TwjwUq-i9KJ2HpxbM-lTEloQ6pXo-FVhQoBTEdJJTHgmqeuH80l5E_0hlLGFb0wg5E&nonce=636409049642654741.MzE5YWJkOWQtMTAyMy00YTcxLWExMjYtNTI2YjA2NWI0ZmFmYmY4Njc2MDEtNWY3Ni00NjdiLWI5ZjctMTE1MTQ1YTRiOGQ5

**Comment by Tratcher** [comment]
"Request too long" may refer to the url and headers. Can you share a Fiddler trace showing the failing request?

**Comment by callranjithkani** [comment]
I found solution #1521 issue, thanks for the reply @Tratcher  , please admin close this issue

**Comment by aqbjteddy** [comment]
@callranjithkani hi, I got that problem too, state value is too long, where is #1521 issue? Can you give a link? Thanks.

**Comment by callranjithkani** [comment]
@aqbjteddy 

Link: https://github.com/IdentityServer/IdentityServer4/issues/1521
