### ISSUE TITLE
Sharing application cookie across multiple apps. Working on localhost, but not on server.

### ISSUE THREAD

**Issue by AnthonyMascia** [aspnet/Security#1420]
So I recently followed [this example](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/cookie-sharing) how to share cookies between my applications.

Code snippet:

    services.ConfigureApplicationCookie(options =>
    {
        var protectionProvider = DataProtectionProvider.Create(new DirectoryInfo(@"c:\shared-auth-ticket-keys\"));

        options.Cookie.Name = ".AuthCookie";
        options.Cookie.Expiration = TimeSpan.FromDays(7);
        options.LoginPath = "/Account/Login";
        options.Cookie.Domain = ".example.com";
        options.DataProtectionProvider = protectionProvider;
        options.TicketDataFormat = new TicketDataFormat(protectionProvider.CreateProtector("Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware", "Cookies", "v2"));
    });

This works flawlessly when using localhost. I log in to my site, an XML key is saved to `c:\shared-auth-ticket-keys\`, and then I'm successfully able to log in across all of my apps simultaneously.

However, when I publish this to the live server using my domain `.example.com`, they key gets created in the server's C: drive and the other apps supposedly aren't finding/calling/using it . Does this possibly have something to do with IIS security settings? I'm at a loss.

**Comment by yoummr** [comment]
I am fetching same problem. Did get any solution or anyone know the solution. Please let me know.
