### ISSUE TITLE
AuthenticationOptions.Validate should take the authenticationScheme

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#1423]
Currently the signature is simply `Validate()`, the missing information is what scheme this options represents.  This prevents validation from doing thing like ensuring that something isn't set to itself (i.e. RemoteAuthentication SignInScheme should never be itself).

We should fix this in 3.0 or whenever we can make breaking changes (we should also move the validation logic in the PostConfigure for https://github.com/aspnet/Security/pull/1422 into Validate when we do this)

**Comment by Eilon** [comment]
Let's do this but without a breaking change.
