### ISSUE TITLE
How to get current user for web API request ?

### ISSUE THREAD

**Issue by blowdart** [aspnet/Security#1427]
_From @Awd60 on September 6, 2017 17:32_

How to get current user for web API request ?
 this example does not work
var claims = ((ClaimsIdentity)User.Identity).Claims;

_Copied from original issue: aspnet/Identity#1416_

**Comment by blowdart** [comment]
How are you authenticating to the webapi?

**Comment by blowdart** [comment]
_From @Awd60 on September 7, 2017 8:28_

We are using AAD to register App for WebAPI.  (Active Directory Authentication)

**Comment by blowdart** [comment]
And how are you getting the AAD token? What are you doing with it after? How are you sending it with each request to the api endpoint?

**Comment by blowdart** [comment]
_From @Awd60 on September 13, 2017 9:19_

We are using standard Azure authentication.
![authentication](https://user-images.githubusercontent.com/30531953/30369536-28a18852-9875-11e7-9d4a-ecf732bab8c6.PNG)
![authentication1](https://user-images.githubusercontent.com/30531953/30369535-2890f2d0-9875-11e7-895f-88bd496a2c2e.PNG)
Application itself does not handle authentication and rely for Azure .

**Comment by blowdart** [comment]
_From @Awd60 on September 13, 2017 9:29_

Issue was closed by my mistake

**Comment by Eilon** [comment]
Azure App Services "Easy Auth" is currently not supported with ASP.NET Core, but we are investigating what it would take to make it work. We'll update this issue when we have news.

**Comment by Eilon** [comment]
Closing because there is no further action on this issue. We don't have any new info from the Easy Auth experts.
