### ISSUE TITLE
How do you compile the ASP.NET/Security.sln in VS2017 (15.3)?

### ISSUE THREAD

**Issue by bleepzter** [aspnet/Security#1428]
I am trying to create a custom implemenation of JWT for my company and for the the life of me I can't compile the Security.sln in Visual Studio 2017 (15.3). How do compile this in Visual Studio?

**Comment by Tratcher** [comment]
Start by building from the command line `build.cmd`. That pulls down a lot of dependencies. Then it should work in VS.

**Comment by jkotalik** [comment]
You may need to also add %USERPROFILE%\\.dotnet\\x64 to your path.

**Comment by Eilon** [comment]
Yup, and running build from the command line tells you that as well in a message.

**Comment by Eilon** [comment]
I'm closing this issue because this should work. If it's still not working for you after running build, please show us the exact error(s) you're seeing.

**Comment by bleepzter** [comment]
So no. Update the documentation about the env variable. Visual Studio gives
1700 errors because it can't find referred, the projects do not target core
2 or standard 2. It's a nightmare while you are omitting quite important
info for building and ruining this.

**Comment by jkotalik** [comment]
To be clear, when you ran build.cmd, did you see an error message? If so what was that exact error message?

**Comment by bleepzter** [comment]
When ruining the build.cmd i don't get any error messages. But thereafter
opening the solution file in vs2017 (15.3) shows 1700 errors. None of the
projects have target framework, none of the projects have references, none
of the projects can even compile.

**Comment by jkotalik** [comment]
Here is a step-by-step guide: https://github.com/aspnet/Home/wiki/Building-from-source. Double check you did all of these steps. It explains the path environment variable issue.

**Comment by bleepzter** [comment]
Thank you

On Sep 14, 2017 5:28 PM, "Justin Kotalik" <notifications@github.com> wrote:

Here is a step-by-step guide: https://github.com/aspnet/
Home/wiki/Building-from-source. Double check you did all of these steps. It
explains the path environment variable issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aspnet/Security/issues/1428#issuecomment-329635992>,
or mute
the thread
