### ISSUE TITLE
dotnet run with windows authentication and without httpsys or weblistener

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#1432]
_From @reft on September 14, 2017 20:25_

## Steps to reproduce
1. Start a new dotnet 2.0 project with windows authentication.
2. dotnet run

## Expected  behavior
Should authenticate user.

Is windows authentication not supported without httpsys or weblistener?
How are you supposed to develop locally when you deploy your app in IIS without httpsys or weblistener. Am I forced to use iis express?! :(

## Actual behavior
Should authenticate user! ;)

## Environment data
2.0

_Copied from original issue: dotnet/cli#7656_

**Comment by Eilon** [comment]
@Tratcher / @blowdart - I believe this is by design because for Windows auth you need IIS or WebListener, right?

**Comment by blowdart** [comment]
Correct. No Windows, no Windows auth.

**Comment by Tratcher** [comment]
Correct, your options are IIS, IIS Express, or HttpSys (formerly WebListener).
