### ISSUE TITLE
User.Identity.Name Returns null

### ISSUE THREAD

**Issue by callranjithkani** [aspnet/Security#1433]
Hi,
User.Identity.Name Returns null
Have you got answer, me too face this same issue, my SSO proxy developed by asp.net core 1.1 and few client applications also developed by core 1.1 it working fine , if i try to implement 4.5.2 developed client app it authenticated successful , but try to retrieve user name i faced this issue.
, have any idea please let me know

My Code:

    [Authorize]
    public ActionResult Index()
    {
       ClaimsPrincipal icp = Thread.CurrentPrincipal as ClaimsPrincipal;
        // Access IClaimsIdentity which contains claims
        ClaimsIdentity claimsIdentity = (ClaimsIdentity)icp.Identity;
        Response.Write("User Name:"+ User.Identity.Name + "<br>");
        // Access claims
        foreach (Claim claim in claimsIdentity.Claims)
         {
            Response.Write(claim.Type+"<br>");
            Response.Write(claim.Value + "<br>");
            Response.Write(claim.ValueType + "<br>");
        }
        return View();
    }

**Comment by Tratcher** [comment]
Why are you accessing `Thread.CurrentPrincipal` but displaying `User.Identitiy.Name`? Note Thread.CurrentPrincipal is not used by ASP.NET Core.

What authentication are you using? OpenIdConnect?

**Comment by callranjithkani** [comment]
@Tratcher 

using Microsoft.Owin.Security;


 JwtSecurityTokenHandler.InboundClaimFilter.Clear();
            var cookie = new CookieAuthenticationOptions
              {
                AuthenticationType = "Cookies",
                ExpireTimeSpan = TimeSpan.FromMinutes(20),
              };
            app.UseCookieAuthentication(cookie);
            app.SetDefaultSignInAsAuthenticationType(cookie.AuthenticationType);
            app.UseOpenIdConnectAuthentication(
                    new OpenIdConnectAuthenticationOptions
                    {
                        AuthenticationType = "oidc",
                        SignInAsAuthenticationType = "Cookies",
                        Authority = "http://localhost:4000/", //SSO Proxy URL
                        ClientId = "devtest", // Client Id for this Application
                        ClientSecret = "secret",// Secret Key For this client application 
                        ResponseType = "id_token code",
                        RedirectUri = "http://localhost:4002/", //Client URI
                        UseTokenLifetime = true,
                  
                    });

**Comment by Eilon** [comment]
@callranjithkani can you clarify whether you're using ASP.NET 4.x w/ Katana and OWIN, or if you're using ASP.NET Core? We do not recommend mixing the two because it is not a supported scenario.

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.
