### ISSUE TITLE
authentication with view component core 2.0

### ISSUE THREAD

**Issue by omansak** [aspnet/Security#1434]
ASP.NET CORE 2.0
----------------
if this view component invoke after CompanyUserController controller , "User.Identity.IsAuthenticated"(with [Authorize(AuthenticationSchemes=...)]) works fine but invoke after HomeController "User.Identity.IsAuthenticated" (without [Authorize(AuthenticationSchemes=...)]) returns null

This code block works on asp.net core 1.1. but doesnt 2.0 . is this a bug on asp.net core 2.0? I need a component for  if user is logged Invoke Logged.cshtml (partial view) , is not logged invoke default.cshtml (partial view).

      //Controller
        [Authorize(AuthenticationSchemes = "...")]
        public class CompanyUserController : Controller
        {
        ...
        }
        //Controller
        public class HomeController : Controller
        {
        ...
        }
    
      //ViewComponent
    
        public class ProfileViewComponent : ViewComponent
        {
            public async Task<IViewComponentResult> InvokeAsync()
                        {
                            var principal = User as ClaimsPrincipal;
                            
                            if (User.Identity.IsAuthenticated) 
                            {
                             ... 
                             return View("..logged.cshtml");        
                            }
                            else
                            {
                             ...
                              return View("..default.cshtml"); 
                            }
                        }
        }

**Comment by Tratcher** [comment]
User should never be null, but may be anonymous. Is it the User property are you seeing is null, or some sub property?

You can get the user via the setting system defaults or you can invoke `HttpContext.AuthenticateAsync` directly in your ViewComponent. Do you have defaults specified in startup?
```
services.AddAuthentication(sharedOptions =>
{
    sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
})
```

You also need `app.UseAuthentication()` in Startup.Configure to process the defaults.

**Comment by omansak** [comment]
@Tratcher  no does not work. i have multiple Authentication Schemes . 

 Answer :           
              ```
  services .AddAuthentication()
                .AddCookie("UserProfilCookie", options =>
                {
                })
                .AddCookie("AdminPanelCookie", options =>
                {
                })
                .AddCookie("CompanyUserProfilCookie", options =>
                {
                });
```
```
app.Use(async (context, next) =>
            {
                var principal = new ClaimsPrincipal();

                var resultUser = await context.AuthenticateAsync("UserProfilCookie");
                if (resultUser?.Principal != null)
                {
                    principal.AddIdentities(resultUser.Principal.Identities);
                }

                var resultCompany = await context.AuthenticateAsync("CompanyUserProfilCookie");
                if (resultCompany?.Principal != null)
                {
                    principal.AddIdentities(resultCompany.Principal.Identities);
                }

                var resultAdmin = await context.AuthenticateAsync("AdminPanelCookie");
                if (resultAdmin?.Principal != null)
                {
                    principal.AddIdentities(resultAdmin.Principal.Identities);
                }
                context.User = principal;

                await next();
            });
```

**Comment by Tratcher** [comment]
Looks great.
