### ISSUE TITLE
Port SignInScheme fix to 2.0.x

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1435]
See https://github.com/aspnet/Security/pull/1422

**Comment by HaoK** [comment]
@Eilon is this ok to backport to 2.0.1?

**Comment by Eilon** [comment]
Yes it is, sorry I missed it. I had already even marked it as approved in my list 😄 

This patch bug is **approved** for the 2.0.x patch. Please send a PR to the `feature/2.0.1` branch and get it reviewed and merged. When we have the `rel/2.0.1` branches ready please port the commit to that branch.

**Comment by HaoK** [comment]
Merged 5035359253674c8cb30d36b39d14c4b3a79692f1 into feature/2.0.1

**Comment by Eilon** [comment]
Hi, we have a public test feed that you can use to try out the ASP.NET/EF Core 2.0.3 patch!

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

We are looking for feedback on this patch. We'd like to know if you have any issues with this patch by updating your apps and libraries to the latest packages and seeing if it fixes the issues you've had, or if it introduces any new issues. If you have any issues or questions, please reply on this issue to let us know as soon as possible.

Thanks,
Eilon
