### ISSUE TITLE
AllowAnonymous to wwwroot (static files)

### ISSUE THREAD

**Issue by jcmordan** [aspnet/Security#1437]
Hi I has implemented Authentication with JwtBearer, but now Im getting 401 response requesting the root path of my app:

![image](https://user-images.githubusercontent.com/8495623/30528055-3b220f66-9bfd-11e7-8f78-65e64e68b2ee.png)

How can I allow anonymous access to static files or the full wwwroot folder?
Can you anybody give a hand with this?

**Comment by davidfowl** [comment]
What does your Startup.cs look like?

**Comment by jcmordan** [comment]
`using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Tokens;
using School360.Api.Configurations;
using School360.Core.Repositories;
using School360.Core.Rules;
using School360.Data;
using School360.Models;
using System;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace School360.Api
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddOptions();

            services.AddDbContext<School360DbContext>(options =>
            {
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
            });

            ConfigIdentity(services);

           

            services.AddTransient<UserRepository>();
            services.AddTransient<UserRules>();


    
            services.AddMvc(config =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                config.Filters.Add(new AuthorizeFilter(policy));
            });
        }

        private void ConfigIdentity(IServiceCollection services)
        {
            var jwtOptions = new JwtOptions();
            Configuration.GetSection(nameof(JwtOptions)).Bind(jwtOptions);

            SymmetricSecurityKey signingKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(jwtOptions.SecretKey));

            // Configure JwtIssuerOptions
            services.Configure<JwtOptions>(options =>
            {
                options.Issuer = jwtOptions.Issuer;
                options.Audience = jwtOptions.Audience;
                options.SigningCredentials = new SigningCredentials(signingKey, SecurityAlgorithms.HmacSha256);
            });

            var tokenValidationParameters = new TokenValidationParameters
            {
                ValidateIssuer = true,
                ValidIssuer = jwtOptions.Issuer,

                ValidateAudience = true,
                ValidAudience = jwtOptions.Audience,

                ValidateIssuerSigningKey = true,
                IssuerSigningKey = signingKey,

                RequireExpirationTime = true,
                ValidateLifetime = true,

                ClockSkew = TimeSpan.Zero
            };

            var tokenCache = new JwtTokenCache();
            services.AddSingleton(tokenCache);

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(options =>
            {
                options.TokenValidationParameters = tokenValidationParameters;
                options.Events = new JwtBearerEvents()
                {
                    OnAuthenticationFailed = OnRedirectToLogin,
                    OnTokenValidated = (context) =>
                    {
                        if (!tokenCache.Contains(context.SecurityToken.Id))
                        {
                            context.Fail(new UnauthorizedAccessException("Invalid token"));
                        }

                        return Task.CompletedTask;
                    }
                };
            });

            var identityOptions = new CustomIdentityOptions();
            Configuration.GetSection(nameof(CustomIdentityOptions)).Bind(identityOptions);
            IdentityBuilder builder = services.AddIdentityCore<User>(options =>
            {
                options.User.RequireUniqueEmail = identityOptions.UserRequireUniqueEmail;
                options.Password.RequiredLength = identityOptions.PasswordRequiredLength;
                options.Password.RequireDigit = identityOptions.PasswordRequireDigit;
                options.Password.RequireLowercase = identityOptions.PasswordRequireLowercase;
                options.Password.RequireNonAlphanumeric = identityOptions.PasswordRequireNonAlphanumeric;
                options.Password.RequireUppercase = identityOptions.PasswordRequireUppercase;
                options.Lockout.MaxFailedAccessAttempts = identityOptions.LockoutMaxFailedAccessAttempts;
            });

            builder = new IdentityBuilder(builder.UserType, typeof(Role), builder.Services)
                 .AddEntityFrameworkStores<School360DbContext>()
                .AddDefaultTokenProviders();

            builder.AddRoleValidator<RoleValidator<Role>>();
            builder.AddRoleManager<RoleManager<Role>>();
            builder.AddSignInManager<SignInManager<User>>();
            builder.AddUserValidator<UserValidator<User>>();
        }

        private static Task OnRedirectToLogin(AuthenticationFailedContext context)
        {
            if (context.Request.Path.StartsWithSegments("/api"))
            {
                // return 401 if not "logged in" from an API Call
                context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                return Task.CompletedTask;
            }

            // Redirect users to login page
            return Task.CompletedTask;
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env,
            UserManager<User> userManager, RoleManager<Role> roleManager)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }


            app.UseAuthentication();

            app.UseMvc();

            CreateAdminUser(userManager, roleManager).Wait();

            AutoMapperExtensions.Configure(app);

    }
}`

**Comment by Tratcher** [comment]
Aren't you missing `app.UseStaticFiles()` in your Configure method?

**Comment by jcmordan** [comment]
> Aren't you missing app.UseStaticFiles() in your Configure method?

Sorry I had uploaded an outdated version of the file.

**Comment by Eilon** [comment]
@jcmordan can you upload the whole app to GitHub so we can take a look? It sounds like the static file middleware just isn't matching the request, so it goes to MVC, and you might have MVC set up to match all requests, and you also might have MVC set up to require auth, which of course would return a 401.

One thing to look at changing is to swap the order of `.UseDefaultFiles()` and `.UseStaticFiles()` because the current order above is incorrect.

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.
