### ISSUE TITLE
Move OpenIdConnectAuthentication from Startup.cs to custom middleware

### ISSUE THREAD

**Issue by nukec** [aspnet/Security#1440]
I have this part of code in Startup.cs to register open Id and it works:

        app.UseCookieAuthentication(new CookieAuthenticationOptions()
        {
            AuthenticationScheme = "Cookies",
            CookieName = Configuration.GetSection("AppSettings:OpenIdAuthentication:CookieName").Value
        });

        var openIdConnectOptions = new OpenIdConnectOptions()
        {
            ClientId = Configuration.GetSection("AppSettings:OpenIdAuthentication:ClientId").Value,
            Authority = Configuration.GetSection("AppSettings:OpenIdAuthentication:Authority").Value,
            CallbackPath = Configuration.GetSection("AppSettings:OpenIdAuthentication:CallbackPath").Value,
            ResponseType = "id_token",
            UseTokenLifetime = false,
            SignInScheme = "Cookies",
            AuthenticationScheme = "oidc",
            AutomaticChallenge = true,

            Events = new OpenIdConnectEvents()
            {
                OnRedirectToIdentityProvider = (context) =>
                {
                    context.ProtocolMessage.SetParameter("acr_values", Configuration.GetSection("AppSettings:OpenIdAuthentication:AcrValues").Value);
                    return Task.FromResult(0);
                }
            }
        };
        openIdConnectOptions.Scope.Clear();
        openIdConnectOptions.Scope.Add("openid");
        openIdConnectOptions.Scope.Add("all_claims");

        app.UseOpenIdConnectAuthentication(openIdConnectOptions);

Now I want to move this to middleware, where I can access HttpContext. I created new middleware named **PartnerAuthMiddleware** and class:

    public class PartnerAuthMiddleware
        {
            private readonly RequestDelegate _next;
            private readonly IApplicationBuilder _app;
    
            public PartnerAuthMiddleware(
                RequestDelegate next,
                IApplicationBuilder app)
            {
                _next = next;
                _app = app;
            }
    
            public async Task Invoke(HttpContext context)
            {
                var currentPartner = context.Features.Get<IPartnerFeature>().Partner;
    
                _app.UseCookieAuthentication(new CookieAuthenticationOptions()
                {
                    AuthenticationScheme = "Cookies",
                    CookieName = "CookieTest"
                });
    
                var openIdConnectOptions = new OpenIdConnectOptions()
                {
                    ClientId = currentPartner.AuthenticationConfiguration.ClientId,
                    Authority = currentPartner.AuthenticationConfiguration.Authority,
                    CallbackPath = currentPartner.AuthenticationConfiguration.CallbackPath,
                    ResponseType = "id_token",
                    UseTokenLifetime = false,
                    SignInScheme = "Cookies",
                    AuthenticationScheme = "oidc",
                    AutomaticChallenge = true,
    
                    Events = new OpenIdConnectEvents()
                    {
                        OnRedirectToIdentityProvider = (ctx) =>
                        {
                            ctx.ProtocolMessage.SetParameter("acr_values", currentPartner.AuthenticationConfiguration.AcrValues);
                            return Task.FromResult(0);
                        }
                    }
                };
                openIdConnectOptions.Scope.Clear();
                openIdConnectOptions.Scope.Add("openid");
                openIdConnectOptions.Scope.Add("all_claims");
    
                _app.UseOpenIdConnectAuthentication(openIdConnectOptions);
    
                await _next(context);
            }
        }

I then use extension for it:

    public static class MiddlewareExtensions
    {
        public static IApplicationBuilder UsePartnerAuthMiddleware(this IApplicationBuilder builder)
        {
            builder.Use(next => new PartnerAuthMiddleware(next, builder).Invoke);
            return builder;
        }
    }

and call it in Startup.cs in Configure() method like this:

    app.UsePartnerAuthMiddleware();

Result is blank screen. What am I doing wrong with chaining?

Custom middleware is put in the middle before  **UseMvc** and **UseStaticFiles** middleware.

**Comment by Tratcher** [comment]
You can't modify the pipeline after startup. That said, there's a new mechanic in 2.0 where you can add new authentication handlers dynamically. Start by migrating over to 2.0 and then we can go through the details.

**Comment by nukec** [comment]
@Tratcher thanks for reply. I didn't know that adding something in middle-ware type and include it inside of Startup.cs is "after" startup. Isn't this happening at the same time as Startup.cs is actually initializing, or does authentication registration has to happen in Startup.cs methods itself and not possible to put as I put in middle-ware and include in Startup? I don't really understand what do you mean with "after" startup, when you include middleware in pipeline is basically not after startup, it's just basic "include" but that's what I don't understand.

@Tratcher I will convert to 2.0 it is small test app, can you show an example of how to add new authentication handler dynamically?

**Comment by nukec** [comment]
@Tratcher I resolved this without 2.0.

```
public class PartnerAuthMiddleware
    {
        private readonly RequestDelegate _next;
        private readonly IApplicationBuilder _app;
        private readonly Action<FilingCabinetPartnerSetting, IApplicationBuilder> _configuration;

        private readonly ConcurrentDictionary<FilingCabinetPartnerSetting, Lazy<RequestDelegate>> _pipelines
            = new ConcurrentDictionary<FilingCabinetPartnerSetting, Lazy<RequestDelegate>>();

        public PartnerAuthMiddleware(
            RequestDelegate next,
            IApplicationBuilder app,
            Action<FilingCabinetPartnerSetting, IApplicationBuilder> configuration)
        {
            _next = next;
            _app = app;
            _configuration = configuration;
        }

        public async Task Invoke(HttpContext context)
        {
            var currentPartner = context.Features.Get<IPartnerFeature>().Partner;

            if (currentPartner != null)
            {
                var brandPipeline = _pipelines.GetOrAdd(currentPartner, new Lazy<RequestDelegate>(() => BuildBrandPipeline(currentPartner)));

                await brandPipeline.Value(context);
            }
        }

        private RequestDelegate BuildBrandPipeline(FilingCabinetPartnerSetting brand)
        {
            var branchBuilder = _app.New();
            _configuration(brand, branchBuilder);
            branchBuilder.Run(_next);
            return branchBuilder.Build();
        }
    }
```

Then create new factory for each partner and call like this:
```
         app.UsePartnerAuthMiddleware((partner, builder) =>
            {
                UsePartnerMiddleware(partner, builder);
            });
```

```
        private void UsePartnerMiddleware(FilingCabinetPartnerSetting partner, IApplicationBuilder app)
        {
            var brandMiddleware = app.ApplicationServices.GetServices<IPartnerAuthMiddlewareManager>()
                .FirstOrDefault(p => p.BrandName.Equals(partner.PartnerName, StringComparison.CurrentCultureIgnoreCase));
            brandMiddleware?.Register(partner, app);
        }
```

**Comment by Tratcher** [comment]
Clever.
You missed an else if currentPartner == null, you likely want to call _next. Otherwise you'll return an empty 200.

**Comment by Tratcher** [comment]
And here's the 2.0 dynamic scheme sample: https://github.com/aspnet/Security/blob/1367a5d3858d4446c126940fe5c26267d0ac2512/test/Microsoft.AspNetCore.Authentication.Test/DynamicSchemeTests.cs#L140-L142
