### ISSUE TITLE
Requests With Custom Bearer Token Dropped/Not Processed

### ISSUE THREAD

**Issue by bleepzter** [aspnet/Security#1444]
I created a simple AuthenticationHandler based on Jwt. The only difference is that the token I generate is based on a key coming from a certificate. The clients get issued  a token and they relay that token with every request in the Authorization header. The value of the header is similar to JwtBearer token where the word "Bearer "  is concatenated with the token. 

To process the token from the header I load up the key from the cert store, and I read the token using the certificate with a given symmetric algorithm. After decryption I get a set of values that I can act upon similar in a way to how Jwt works. 

Either way - long story short - If the custom authentication handler is used, any request not having that Authorization header is rejected with a 403. This is part of normal operation.

Any request that has the ("Authorization") header gets dropped somehow. The handler doesn't get called, endpoints do not get called, the request seems to go in a black hole without a trace.

**Comment by Eilon** [comment]
@bleepzter can you show us some code about what you're doing?

**Comment by AlwaysAbhl001** [comment]
@Elion I'm just trying to handle 401 to redirect to login page if authorization header is misssing but unable to figure out in JWTBEAR. I also posted a [stackoverflow question](https://stackoverflow.com/questions/46650256/redirect-to-login-if-is-not-login-aspnetcore-2-0/46651809#46651809)  any help would be appreciated.

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.
