### ISSUE TITLE
OIDC should use AuthenticationProtocolMessage.BuildFormPost()

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1448]
When OIDC does redirects using the FormPost mode it generates an HTML form redirect.
https://github.com/aspnet/Security/blob/31dd4ebd9c0c26fc9592aa08d7fb3804bf34011b/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L237-L252

However, `AuthenticationProtocolMessage.BuildFormPost()` already has this code so we can remove our redundant copy.

**Comment by PinpointTownes** [comment]
This doesn't sound like a good idea.

When I introduced POST authorization requests support in the OIDC middleware 2 years ago, I deliberately avoided using `BuildFormPost()` for a simple reason: [it was - and is still - broken as it URLencodes the form action attribute](https://github.com/aspnet/Security/pull/392#r36568911).

**Comment by Tratcher** [comment]
Fair, but we can fix it first.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/755
@brentschmaltz

**Comment by brentschmaltz** [comment]
@Tratcher @PinpointTownes ,  @616b2f fixed OIDC 755

**Comment by Tratcher** [comment]
This depends on getting updated versions. See https://github.com/aspnet/Security/issues/1468
