### ISSUE TITLE
Substring match should be case-insensitive

### ISSUE THREAD

**Issue by prosser** [aspnet/Security#1450]
https://github.com/aspnet/Security/blob/5abcfe7e3d78f777d45503b50de5cea17cf9aa5e/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L75

The outer check is case-insensitive, but the inner String.Substring call is not.

**Comment by Tratcher** [comment]
That's just a length check, there's no character comparison there too make case insensitive.
