### ISSUE TITLE
Role Authorization not working when changing role.

### ISSUE THREAD

**Issue by MeikelLP** [aspnet/Security#1451]
### Scenario
I have a user A and a user B.

#### Work
* A was in role "Admin" -> no role (removed all roles).
* B was never in any role -> no role.

#### Result
* A has still access to features for "Admin"s. 
* B does not.

#### Info
* Authorization via `[AuthorizeAttribute(Roles = "Admin")]`
* Roles removed via `UserManger.RemoveRolesAsync(user, role)`

### Code (irrelevant snippets hidden <- in my opinion)

_Startup.cs_
```
public void ConfigureServices(IServiceCollection services)
{
  ...
  services.AddMvc();
  services.AddAuthorization();
  ...
}

public void Configure(IApplicationBuilder app, ...)
{
  ...
  app.UseAuthentication();
  ...
}
```

_Controllers/UserController.cs_ (shall mange user administration)
```
[Authorize(Roles = "Admin")]
public class UserController : Controller
{
  ... 
  [HttpGet("/[controller]s")]
  public async Task<IActionResult> Index()
  {
     return View();
  }
}
```

_Project.csproj_
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <UserSecretsId>...</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" PrivateAssets="All" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.0" />
  </ItemGroup>
</Project>
```

### My Questions
* [ ] Is this a bug?
* [ ] Am I doing something wrong?
* [ ] Do you need more information?
* [x] Does it have something to do with cookies? I tried to experiemt with cleaning them, but I don't know whether or not it influences the authorization behaviour (yes after re-login).

### For Your Information
* Yes I tried looking for a result.
* I didn't found anything on the web for this specific topic.

**Comment by Tratcher** [comment]
Is it fixed when user A logs out and logs back in? A lot of the user information is cached in the auth cookie, which is what the Authorize attribute checks.

@HaoK how do you trip the single sign-out flag to invalidate the cookie?

**Comment by MeikelLP** [comment]
@Tratcher Yes it is fixed once re-login!

Isn't that a **security issue**? If a user stays admin until he logs out, although he hasn't the role anymore??

**Comment by HaoK** [comment]
The `UserManager.UpdateSecurityStampAsync(user)` method is what triggers invalidation of that users cookies next time its validated

**Comment by MeikelLP** [comment]
So one has to call `UserManager.UpdateSecurityStampAsync(user)` when updating roles? Why isn't this automatically?

**Comment by HaoK** [comment]
That's expected behavior, you don't want to hit the database on every login, so there's built in throttling.  Its a tradeoff between occasional outdated claims vs database hits.

**Comment by MeikelLP** [comment]
That still does not fix my Problem. I expect `UserManager.UpdateSecurityStampAsync(user)` to "kick" the user out of the system so he has to login again. But that does not happen.

**Comment by Tratcher** [comment]
The alternative is having the cookie re-validated against the database on every request which would destroy your site performance.

**Comment by MeikelLP** [comment]
But isn't the `UserManager.UpdateSecurityStampAsync(user)` method going to invalidate my cookie, if I changed my role? Why do I still have admin access although I removed my admin role and updated my security stamp?

**Comment by HaoK** [comment]
It invalidates the stamp that will cause the cookie to be invalidated the next time it checks...  it doesn't check on every request.

**Comment by MeikelLP** [comment]
So I cannot prevent this efficiently?

**Comment by Tratcher** [comment]
You can turn it down with the ValidationInterval setting you mentioned above, but it will destroy your application performance. Your choice.

**Comment by MeikelLP** [comment]
I'm really dissatisfied with that...
Will there be any chance for this in future releases?

**Comment by Tratcher** [comment]
Chance for what? There are no proposed alternatives.

**Comment by MeikelLP** [comment]
To actually kick out a user instantly?

**Comment by Tratcher** [comment]
How? You have to verify the cookie against something. That something is currently the user database which is too expensive to access on every request.

**Comment by MeikelLP** [comment]
Yes, I know that it's too expensive by now. But I want something like:
Make a specific user/identity have to reverify its cookie on the next request. Is that possible or is my thinking just to simple?

**Comment by Tratcher** [comment]
The user database is the source of true for that kind of information. To verify any user you have to verify all users because you don't know which ones need to be verified without accessing a central list.

**Comment by MeikelLP** [comment]
Okay still not satisfied, even if I understand the situation now, I am not amused about this :(
Is there any best practice for my scenario? Like what if you have an admin who u want to instantly degrade but not blocked? Or will this never be an scenario?

**Comment by HaoK** [comment]
You should always check that the user has proper authorization on the server, not rely on cached claims.

**Comment by MeikelLP** [comment]
So for critial (rare) admin functionality can you recommend doing this?
