### ISSUE TITLE
JWT Bearer middleware giving current time in the future

### ISSUE THREAD

**Issue by Gimly** [aspnet/Security#1452]
I have a very strange behavior with the JWT bearer middleware. I'm developing a .net core 2.0 app that uses Keycloak as an identity provider and I'm using the jwt bearer middleware to secure my application.

When I was working in debug mode everything was working as expected, but now that I moved to a production server, I can't get it to work correctly, I'm always getting a `SecurityTokenExpiredException` even for freshly created token. That's where it gets really weird. If I look at the token itself, the `exp` property is correctly set, 5 minutes after the token is issued, as configured in Keycloak. But, in the error message, the "Current time" is in the future compared to the server time.

![image](https://user-images.githubusercontent.com/168669/30814086-84c886b4-a20f-11e7-8d7b-2395f8f918d0.png)

As you can see from the screenshot, the token should be valid since its validity is 5 minutes in the future regarding the server's clock, but the "Current time" is more than 1 hour in future. What makes this bug even weirder is that the clock seems to be drifting away. When I restart the server it works fine for something like a minute, but then the difference between the real server time and the value given in the error message "Current time" grows.

Both the Keycloak server and the Windows Server are on the same time zone and their clocks seem synchronized (at least at the minute).

For reference, here's how I have configured the bearer middleware.

```C#
public void ConfigureServices(IServiceCollection services)
{
    ...

    services.AddAuthentication(options =>
    {
        options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
    }).AddJwtBearer(o =>
    {
        o.Authority = Configuration["Jwt:Authority"];
        o.Audience = Configuration["Jwt:Audience"];
        o.Events = new JwtBearerEvents()
        {
            OnAuthenticationFailed = c =>
            {
                c.NoResult();

                c.Response.StatusCode = 500;
                c.Response.ContentType = "text/plain";

                return c.Response.WriteAsync(c.Exception.ToString());
            }
        };
    });

    services.AddAuthorization(options =>
    {
        options.AddPolicy("Administrator", policy => policy.RequireClaim("member_of", "[Administrator]"));
    });
}

public void Configure(IApplicationBuilder app)
{
   ...
   app.UseAuthentication();
   ...
}
```

PS: I have also created a question on [StackOverflow](https://stackoverflow.com/questions/46406303/jwt-bearer-middleware-giving-current-time-in-the-future), I hope it's not frowned upon to cross post questions, but since I think it might be a bug in the JwtBearer middleware I thought it would make sense to post here. Thanks!

**Comment by Tratcher** [comment]
What time zone are all of these clocks and dates in?

**Comment by Gimly** [comment]
They are all set at UTC+01 (Amsterdam, Berlin, Bern, ...) the Keycloak server is a linux server, but I don't think that has any impact since the exp property in Unix time is correctly set in the jwt token.

**Comment by Gimly** [comment]
@Tratcher I don't think this issue has anything to do with the time zone, I've left the server up during the night and now it's 15 hours in the future, the distance between the real hour and the hour returned by the error message gets bigger and bigger.

![image](https://user-images.githubusercontent.com/168669/30848412-62098250-a29f-11e7-99db-995d2473bb2b.png)

I did more research, and first I tried to add a simple "getDate" method to my API that returns `DateTime.Now` and, to my surprise it did return a date that has nothing to do with the server time. So I did something even simpler and created a console app with the following code:

```C#
using System;

namespace datetime
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine($"DateTime.Now: {DateTime.Now.ToString("o")}");
            Console.WriteLine($"DateTime.UtcNow: {DateTime.UtcNow.ToString("o")}");
        }
    }
}
```

On my development machine everything is working as expected, getting a date that is the same as the Windows clock, but on the server, here's what happens:

![image](https://user-images.githubusercontent.com/168669/30849065-6464422c-a2a1-11e7-8747-665fc5b6f88c.png)

Here's PowerShell's output for more readability:

```PowerShell
PS C:\Users\Administrator\Documents\test> dotnet .\datetime.dll
DateTime.Now: 2017-09-27T04:29:16.6493531+02:00
DateTime.UtcNow: 2017-09-27T02:29:16.6630150Z
PS C:\Users\Administrator\Documents\test> [DateTime]::Now.ToString("o")
2017-09-26T09:58:44.8530092+02:00
PS C:\Users\Administrator\Documents\test> Get-Date
Tuesday, September 26, 2017 9:58:51 AM
```

First call is calling the app I pasted above with .Net Core, the next call is the "standard" .Net Framework and the last is PowerShell's own method.

I guess this makes the bug not a bug of the JwtBearer middleware... so should I close this and open it somewhere else? If so, can you tell me where? Thanks!

**Comment by Tratcher** [comment]
Try https://github.com/dotnet/corefx

**Comment by Gimly** [comment]
I've opened an issue directly in the coreclr repository since that's where DateTime is implemented. 
https://github.com/dotnet/coreclr/issues/14187

Closing this issue since it's not really the root cause of the problem I'm facing. Thanks for your help @Tratcher .
