### ISSUE TITLE
ClaimsTransformationContext is not recognised in ASP Core 2.0.0

### ISSUE THREAD

**Issue by fido9dido** [aspnet/Security#1454]
The following code is not recognized in asp mvc core 2.0.0

` app.UseClaimsTransformation`

both UseClaimsTransformation and ClaimsTransformationContext  is  not recognized

```
using Microsoft.AspNetCore.Authentication;
public static Task<ClaimsPrincipal> AddClaims(ClaimsTransformationContext context)
{
    ....
}
```

What I'm doing wrong?!

**Comment by tverboon** [comment]
In 2.0.0 it isn't middleware anymore. Reason is we are now able to use dependency injection.

To use ClaimsTransformation, register it in the service collection:

```csharp
services.AddSingleton<IClaimsTransformation, ClaimsTransformer>();
``` 

And have a transformer class:

```csharp
public class ClaimsTransformer : IClaimsTransformation
{
    public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
    {
    }
}
```

**Comment by fido9dido** [comment]
ah thanks
