### ISSUE TITLE
OpenId Connect JWT as client secret (for ADFS)

### ISSUE THREAD

**Issue by uringeller** [aspnet/Security#1455]
Hi, we are using your Microsoft.AspNetCore.Authentication.OpenIdConnect middleware to connect a client to an AD FS 2016 server using a shared secret, but we would like to authenticate the client using a certificate based secret instead.

To our understanding, AD FS accepts a signed JWT as a secret, and it is possible to configure ADFS to manually set or periodically download a certificate or a public key -  although it's hard to come across any documentation that describes this feature :/

In your middleware the options class only defines the secret as a string, do you have any plans to extend this to include a feature that allows to generate secrets as JWTs?

**Comment by blowdart** [comment]
We use the libraries provided to us by the AD team. @brentschmaltz do you expose this and we're just missing docs, or is it not possible right now?

**Comment by brentschmaltz** [comment]
ADAL has an API that allows you to specify an X509 Cert OR create a signed JWT yourself.

@uringeller Is this what you are looking for?

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/180c9f2d87fb687cbf121bc28258de3d12c1bb15/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Features/WinCommon/AuthenticationContextIntegratedAuthExtensions.cs

https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/

**Comment by uringeller** [comment]
Hey! Our client is a IdentityServer4 (running on asp.net core), and the identity provider is an AD DS with an AD FS (2016) as the STS. 
We've considered generating the JWT ourselves, but wanted to check if you had any plans for a feature that supported this in the middleware itself (or by using some API) - or if something already existed.

I'm not sure if I understand you correctly @brentschmaltz, but you suggest we can use ADAL to generate the JWT when we instantiate  the OpenIdConnectOptions class? In other words, set the value of the client secret to the generated token as a base64 encoded string?

**Comment by brentschmaltz** [comment]
@uringeller I am pointing out that you can use ADAL to obtain a token from the 'token endpoint'. There are two API's, one takes a JWT that you create (with we need to improve IdentityModel) OR you can pass an X509Certificate2 and ADAL will create the JWT for you. ADAL does not generate JWT for you, but does so internally before calling the 'token endpoint'.

I am not following the OnRedirectToIdentityProviderEvent as that is the OIDC flow to the 'authorize endpoint'.

**Comment by uringeller** [comment]
Haha, at least now I understand that I dont understand well enough to form meaningful questions :)

Thanks for your help!
