### ISSUE TITLE
Losing Cookies from login redirect with Core 2.0 (worked in 1.1)

### ISSUE THREAD

**Issue by mrjavaguy** [aspnet/Security#1456]
We have a slightly unusual use case. Our application runs inside an iframe of a third-party site. They post to our login url, we do some validation on our side and set a cookie. This all worked fine in 1.1 however when we upgraded to 2.0, the auth cookie (and the culture cookie) are no longer going a long for the ride on the redirect. I can see the cookies being set in fiddler on the redirect, but not being passed back to the app on the get. Any ideas on what this the issue might be?

Authentication setup:
``` CSharp            
            service.AddAuthentication(options =>
            {
                options.DefaultScheme = AuthSchemes.CookieAuthName;
                options.DefaultChallengeScheme = AuthSchemes.CookieAuthName;
                options.DefaultSignInScheme = AuthSchemes.CookieAuthName;
                options.DefaultSignOutScheme = AuthSchemes.CookieAuthName;
                options.DefaultAuthenticateScheme = AuthSchemes.CookieAuthName;
                options.DefaultForbidScheme = AuthSchemes.CookieAuthName;
            })
            .AddCookie(AuthSchemes.CookieAuthName, options =>
            {
                if (config.IsNotProduction())
                {
                    options.LoginPath = new PathString("/auth/login");
                    options.Cookie.HttpOnly = false;
                }
            });
```
Login Code:
``` CSharp
        [HttpPost]
        public async Task<IActionResult> Login(string jwt, string returnUrl = "/")
        {
            var getClaimsFromJwtCommand = new GetClaimsFromJwtCommand(jwt);
            var identity = await commandRouter.ExecuteFunctionAsync(getClaimsFromJwtCommand);

            SetCultureCookie(identity.Culture);

            var claims = CreateClaimsPrincipal(identity);

            var properties = GetAuthenticationProperties();

            await CreateSession(claims, properties);

            // Custom activities provide the redirect in the jwt
            var destination = identity.LoginRedirectLink ?? returnUrl;

            if (Url.IsLocalUrl(destination))
            {
                return Redirect(destination);
            }
            else
            {
                return BadRequest();
            }
        }
```

Fiddler traces:
[3_Full.txt](https://github.com/aspnet/Security/files/1338693/3_Full.txt)

I created a simple repo (https://github.com/mrjavaguy/cookieredirect) that shows the same issue.

**Comment by Tratcher** [comment]
If the IFrame is hosted by a different domain then you may be affected by the new cookie samesite setting. The default is lax, but for your scenario you may need to disable it entirely. See CookieAuthenticationOptions.Cookie.SameSite.

**Comment by brockallen** [comment]
FWIW, in IdentityServer we had to disable same site cookies because of this.

**Comment by mrjavaguy** [comment]
I do not think this is the issue as the simple repo is a plain MVC app. Also I just tested by adding `options.Cookie.SameSite = SameSiteMode.None;` and got the same results (the cookie not longer has `samesite=lax` in it).

**Comment by mrjavaguy** [comment]
Spoke too soon, apparently fiddler does not pass cookies on redirect., Postman doe. Simple repo works as expected. Trying main application now (takes awhile to deploy).

**Comment by mrjavaguy** [comment]
Closing this issue as fixed with `SameSite = SameSiteMode.None`. Thanks for the help. @Tratcher @brockallen
