### ISSUE TITLE
When creating an AuthorizationHandler it doesn't use custom dependency injection container

### ISSUE THREAD

**Issue by FruitAndAShape** [aspnet/Security#1458]
```
public class AuthHandler : AuthenticationHandler<AuthOptions>
{
    private readonly IUserIdentifierProvider userIdentifierProvider;

    public AuthHandler(IUserIdentifierProvider userIdentifierProvider, IOptionsMonitor<AuthOptions> options, ILoggerFactory logger, UrlEncoder encoder, ISystemClock clock) :
        base(options, logger, encoder, clock)
    {
        this.userIdentifierProvider = userIdentifierProvider;
    }
...
}

public static class AuthMiddlewareAppBuilderExtensions
{
    public static AuthenticationBuilder AddCustomAuth(this AuthenticationBuilder builder, Action<AuthOptions> configureOptions)
    {
        return builder.AddScheme<AuthOptions, AuthHandler>("Custom Scheme", "Custom Auth", configureOptions);
    }
}
public IServiceProvider ConfigureServices(IServiceCollection services)
{
            services.AddMvc();

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = "Custom Scheme";
                options.DefaultChallengeScheme = "Custom Scheme";
            })
            .AddCustomAuth(o => {});

            var serviceProvider = ConfigureUnity(services);

            return serviceProvider;
}

```

`IUserIdentifierProvider` is in my Unity container but the system can't find it when it's creating `AuthHandler`. If I add...

`services.AddTransient<IUserIdentifierProvider, UserIdentifierProvider>();`

it works.

My theory is that whatever is creating the `AuthHandler` has retained a reference to the system's collection of services and is using that instead of my Unity container.

**Comment by Tratcher** [comment]
You can start to backtrack the services here:
https://github.com/aspnet/HttpAbstractions/blob/321639b0eb2098a6fe3b0d763f48ac3ed025a688/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationHandlerProvider.cs#L52-L53

**Comment by FruitAndAShape** [comment]
Thanks but I think I've wasted enough time on this already. :)

**Comment by Eilon** [comment]
@FruitAndAShape is there a complete app you can share with us that demonstrates this problem? There could very well be a bug here but it's hard to know without seeing more of the code.

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.

**Comment by FruitAndAShape** [comment]
This has cropped up again. This time it's not using a custom service provider when resolving Razor pages.

**Comment by Tratcher** [comment]
Please file a new bug in Razor.
