### ISSUE TITLE
Custom Authentication dependency injection

### ISSUE THREAD

**Issue by dgstpierre** [aspnet/Security#1461]
I'm trying to move custom auth code from 1.0 to 2.0 and am not seeing how to do dependency injection so I can use it in HandleAuthenticateAsync().

In ConfigureServices I have the following:
            services.AddAuthentication(o =>
            {
                o.DefaultScheme = "LicenseKeyScheme";
            }).AddLicenseKeyAuthentication("LicenseKeyScheme", "License Key Scheme", o => { });

I've created an extension
public static class LicenseKeyAuthenticationExtensions
    {
        public static AuthenticationBuilder AddLicenseKeyAuthentication(this AuthenticationBuilder builder, string authenticationScheme, string displayName, Action<LicenseKeyAuthenticationOptions> configureOptions)
        {
            return builder.AddScheme<LicenseKeyAuthenticationOptions, LicenseKeyAuthenticationHandler>(authenticationScheme, displayName, configureOptions);
        }
    }

I have a scheme options
    public class LicenseKeyAuthenticationOptions : AuthenticationSchemeOptions
    {
    }

And I have an Authentication handler

    public class LicenseKeyAuthenticationHandler : AuthenticationHandler<LicenseKeyAuthenticationOptions>
    {

        public LicenseKeyAuthenticationHandler(IOptionsMonitor<LicenseKeyAuthenticationOptions> options, ILoggerFactory logger, UrlEncoder encoder, ISystemClock clock) : base(options, logger, encoder, clock)
        {
        }

        protected override Task<AuthenticateResult> HandleAuthenticateAsync()
        {

            return Task.FromResult(
                 AuthenticateResult.Success(
                    new AuthenticationTicket(
                        new ClaimsPrincipal(),
                        new AuthenticationProperties(),
                        this.Scheme.Name)));
        }
    }

Lets say I have my own IAuthManager that I want to use inside HandleAuthenticationAsync, how do I inject it in?  If I add to the constructor it desn't seem to work...

Thanks

**Comment by dgstpierre** [comment]
My mistake, have it working, I was missing a nested dependency.

**Comment by EIDIVANDI** [comment]
Is there any clear response to DI ? i have the same problem , just need be able to inject my dependency to handler , but constructor not working , and it's a bit blocked

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
