### ISSUE TITLE
Net Core 2.0 connection to AAD B2C - WebAPI Authentication issue - Authorization failed for the request at filter

### ISSUE THREAD

**Issue by MichalJankowskii** [aspnet/Security#1463]
I am trying to build solution in .net Core 2.0 and use AAD B2C for authentication. Is it MVC application with separated WebAPI project. And I have problem with token validation in WebAPI layer. Probably I missed something.

I managed to build similar solution with net Core 1.0 and everything works like a charm. In case on net Core 2.0 I managed to authenticate user only in WebApp layer.

Below you can find code for:
- WebApp 

Startup.cs:

        public Startup(IHostingEnvironment env)
        {
            Configuration = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json")
                .Build();
        }

        public IConfigurationRoot Configuration { get; set; }

        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                })
                .AddCookie()
                .AddOpenIdConnect(options =>
                {
                    options.Authority = String.Format(Configuration["AzureAd:AadInstance"], Configuration["AzureAd:Tenant"]); ;
                    options.ClientId = Configuration["AzureAd:ClientId"];
                    options.ClientSecret = Configuration["AzureAd:ClientSecret"];
                    options.GetClaimsFromUserInfoEndpoint = false;
                    options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
                    options.SaveTokens = true;
                });

            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseAuthentication();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }

Controller:

    [Authorize]
    public class HomeController : Controller
    {
        private static string APIUrl = "http://localhost:5000";

        public async Task<IActionResult> Index()
        {
            string accessToken = await HttpContext.GetTokenAsync("access_token");

            HttpClient client = new HttpClient();
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, APIUrl + "/api/values");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            HttpResponseMessage response = await client.SendAsync(request);

            string data = await response.Content.ReadAsStringAsync();

            return this.View();
        }
    }

- WebAPI:

Startup.cs:

        public Startup(IHostingEnvironment env)
        {
            Configuration = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json")
                .Build();
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            }).AddJwtBearer(o =>
            {
                o.RequireHttpsMetadata = false;
                o.Authority = String.Format(Configuration["AzureAd:AadInstance"], Configuration["AzureAD:Tenant"]);
                o.Audience = Configuration["AzureAd:Audience"];
            });

            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseAuthentication();
            app.UseMvc();
        }

Controller:

    [Authorize]
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }
    }

With this code I get 401 Unauthorized after execution of HttpResponseMessage response = await client.SendAsync(request);. 

In AppInsights I can find following errors:
-  {AuthenticationScheme} was not authenticated. Failure message: {FailureMessage} / No SecurityTokenValidator available for token...
- Authorization failed for user: (null).
- Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.

Could you please help me with configuration following solution.

**Comment by Eilon** [comment]
Looks like maybe this code is incorrect:

```c#
            o.Authority = String.Format(Configuration["AzureAd:AadInstance"], Configuration["AzureAD:Tenant"]);
```

Because it's not passing in a format string. The first parameter to `string.Format()` is the format string, and the parameters after that are the values to format into it.

Try this instead:

```c#
            o.Authority = Configuration["AzureAd:AadInstance"] + Configuration["AzureAD:Tenant"];
```

Here you can see what the default template does for these values: https://github.com/aspnet/templating/blob/0dfb43b15a355f59b83a6453e71248e197831fed/src/Microsoft.DotNet.Web.ProjectTemplates.1.x/content/WebApi-CSharp/Startup.cs#L60-L61

**Comment by MichalJankowskii** [comment]
No this is not a problem. AaaInstance contains following string "https://login.microsoftonline.com/{0}"

I have the same configuration in WebApp and it works there fine.
