### ISSUE TITLE
AuthenticateAsync and TransformAsync should only be called once by request

### ISSUE THREAD

**Issue by POFerro** [aspnet/Security#1464]
Hi,

After defining a IClaimsTransformation class to perform some logic and load aditional claims I realized that this method is called many times per request.
Since the authentication process and claims loading might carry some weight is there a way to have this done only once per request.
Why is this done this way? Once a RequestPrincipal is authenticated and loaded why is there a need to authenticate again?

All documentation on this issue refers that TransformAsync should return a new Principal because it's called many times, is this a design feature? How can I add claims loaded from custom Store only once per request?

Thanks in advance
POFerro

**Comment by brockallen** [comment]
dup: https://github.com/aspnet/Security/issues/1399
