### ISSUE TITLE
NTLM and cookie authentication

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#1467]
_From @drauch on September 28, 2017 12:16_

Our application uses windows authentication by default, however, for testing purposes, if a certain cookie is set, it should authenticate using cookie authentication.

So in the testing environment we tried to add the following to our pipeline:

    app.UseCookieAuthentication (new CookieAuthenticationOptions ()
      {
        AuthenticationScheme = "TestingCookieAuthenticationScheme",
        AutomaticAuthenticate = true,
        AutomaticChallenge = false,
        CookieName = "TestingCookieAuthenticationSchemeCookie"
      });

Our testers can surf to a special controller where they can login as any user (again, the controller is only available in our testing environment). The controller action looks like this:

    public async Task<IActionResult> SwitchUser (string user)
    {
      var nameClaim = new Claim("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name", user);
      var claimsIdentity = new ClaimsIdentity(new[] { nameClaim });
      await HttpContext.Authentication.SignInAsync("TestingCookieAuthenticationScheme", new ClaimsPrincipal(claimsIdentity));

      return View();
    }

However, even when the cookie is present (checked this via F12 tools), the `User.Identity.Name` still shows the NTLM authenticated user and not the cookie-authenticated user.

What are we doing wrong?

(ASP.NET Core 1.1)

_Copied from original issue: aspnet/Mvc#6893_

**Comment by Eilon** [comment]
_From @davidfowl on October 1, 2017 4:47_

Why don't the schemes match? You configured the cookie with the "TestingCookieAuthenticationSchemeCookie" scheme but then signed in with the "WebTestingCookieAuthenticationScheme" scheme.

Are you expecting the user to have both the windows identity and the cookie identity? Is the windows identity always there?

**Comment by Eilon** [comment]
_From @drauch on October 1, 2017 15:6_

@davidfowl : Sorry, that's been a copy&paste error when creating a minimal repro sample. Actually they are the same, re-checked it & fixed in the original post.

**Comment by Tratcher** [comment]
This is likely because the NTLM and Cookie identities are being merged. If you look at User.Identities you will see two instances, one for NTLM and one for Cookies.

**Comment by drauch** [comment]
@Tratcher : Thanks, you're right. Identities contains both, the windows identity and the cookie identity. Unfortunately, there is no easy way to tell the principal to use the cookie identity as "first" identity and a lot of ASP.NET infrastructure simply uses the primary Identity.

We are now working with a wrapper around the principal which returns the cookie identity as the primary identity.

**Comment by drauch** [comment]
It looks like with `ClaimsPrincipal`s you can set a static `Func<IEnumerable<ClaimsIdentity>, ClaimsIdentity>` called `PrimaryIdentitySelector` which you can use in order to select the primary identity to work with. Just FYI.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
