### ISSUE TITLE
Raise the IdentityModel dependencies version to 5.2.0-*

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1468]
IdentityModel is adding WsFederation support in 5.2.0-*. To merge our WsFederation port into dev we'll need to update all of the IdentityModel dependencies to at least `5.2.0-preview1-408290725` (currently available on nuget.org). We'll want to move to their latest myget nightly builds to give them final feedback before 5.2.0 RTMs.

Note that for the 5.2.0 release they are leveling all of their package versions to 5.2.0. Before some were 2.x and some were 5.x.

**Comment by Eilon** [comment]
@javiercn can you update this issue?

**Comment by javiercn** [comment]
This was done in Universe (and Common)
https://github.com/aspnet/BuildTools/tree/5153bbdfa98dcc27a61d591ce09a0d632875e66f
https://github.com/aspnet/Universe/commit/f6bb10696084174ed1726c71b4645cc8976e7361
