### ISSUE TITLE
Why is AuthorizationHandlerContext.Resource of type object?

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/Security#1470]
Why is the `Resource` property in the `AuthorizationHandlerContext` class declared as `object` type?

I expected this property to be of the type `PathString`.

**Comment by Eilon** [comment]
The resource can be any type, depending on the resource being authorized. For example, in typical MVC scenarios it's one of these: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/Filters/AuthorizationFilterContext.cs

This allows the code to get access to whatever MVC was doing to make its decision.

And of course in other scenarios it could be other types of objects.

**Comment by vanillajonathan** [comment]
I see. I thought it was always a `PathString`. I can use `.ToString()` on it.

```cs
var resource = new PathString(context.Resource.ToString());
```

**Comment by Eilon** [comment]
@vanillajonathan it could sometimes be, it depends on what the component that calls Authorize passes in. Components can choose to pass in whatever type of resource they want so that the policies can process it to make a decision.

**Comment by vanillajonathan** [comment]
I see. I just foolishly assumed it was always a `PathString` because that is what I passed into it and what was passed into it from the example code I've seen in documentation I've read.

Thanks for the explanation. 👍
