### ISSUE TITLE
Documentation for super simple authentication

### ISSUE THREAD

**Issue by mjwsteenbergen** [aspnet/Security#1471]
I am running a simple rest-client for a hobby project and do not want to leave this api open to the rest of the world. I do not want to set up an entire framework for only one user (myself). [Open source security frameworks](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/community) I found are way too heavy for me. Is there something for this use case?

**Comment by damianh** [comment]
basic auth?

**Comment by mjwsteenbergen** [comment]
Do you have any idea about how I would do that? [The only library](https://github.com/blowdart/idunno.Authentication) that I found, is no longer updated. Furthermore it itself is advocating against it and asking to implement further features to make it safer. [Another example](https://github.com/aspnet/Security/issues/395) I found in this repository is even simpler, using a username and password, but is also out of date.

**Comment by Eilon** [comment]
@blowdart can you update your awesome sample that everyone wants?

**Comment by blowdart** [comment]
But it's horrible and clearly marked "Not for production". It is kind of updated, when I feel like writing horrible insecure code.

Fine, I'll take a lot when I have some free time.

**Comment by Daniel15** [comment]
I have a project for simple username/password auth via the regular cookie-based authentication: https://github.com/Daniel15/SimpleIdentity. It works on ASP.NET Core 2.0 (I just pushed an update, but it worked fine even before).

Since I built it for forms auth, it's likely not a good fit for a REST API. Fine for a regular site though.

**Comment by blowdart** [comment]
OK, my implementation of [Basic Auth](https://github.com/blowdart/idunno.Authentication) has been fixed for 1.1, and also updated for 2.0. 

The caveat of don't use this in production still stands though :)

**Comment by DomZZ** [comment]
@blowdart, does your implementation can works together with [AllowAnonymous] attribute ?
I would like to have Basic Auth on all actions except one which need to be anonymous and I've read that it isnot possible to do that with a Middleware.

Thanks

**Comment by blowdart** [comment]
It'd work just fine. However there's a caveat, with basic auth once you're auth-ed you stay auth-ed, so even if you hit the anonymous end point it'd still send credentials and parse them.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
