### ISSUE TITLE
Cookie authentication overrides Cache-Control, Pragma & Expires headers

### ISSUE THREAD

**Issue by a13531a** [aspnet/Security#1474]
https://github.com/aspnet/Security/blob/e0ad6ed6b9abbb73e3ca68c6abdf2a0126defec1/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L360-L362

This overrides values that may have already been set to some specific values in other middleware (for example, Web API). 

For instance, in my app that is vitally important to have "Cache-Control" to be set to this: "no-store, no-cache, must-revalidate", but when sliding expiration happens, this value gets overwritten by this middleware to just "no-cache"

**Comment by Tratcher** [comment]
This is by design. Responses with auth cookies must not be cached.
Also, WebAPIs should not be using cookie auth. JWT Bearer would be more appropriate.

**Comment by blowdart** [comment]
`no-cache` implies `must-revalidate` by making the response immediately stale. This is not a case of "just", it's an upgrade from a security POV.

**Comment by a13531a** [comment]
Thank you for your quick replies. I very appreciate it.
I actually understand the thing about no-cache & must-revalidate but for some reasons (not known to me), the INetCache thing in Windows sometimes caches those results that don't have "must-revalidate" in the Cache-Control header... That is the only reason why it was decided to specify one more option in Cache-Control header...
This Web API is used by a WPF app. This app communicates with the web service using the HttpClient class:

`var webRequestHandler = new WebRequestHandler()
            {
                UseCookies = true,
                CookieContainer = _cookieContainer,
                CachePolicy = new RequestCachePolicy(RequestCacheLevel.Default)
            };

            _httpClient = new HttpClient(webRequestHandler)
            {
                BaseAddress = baseUrl
            };`

The auth cookie is stored in the app's memory until it is closed. To talk to the Web API, only one instance of HttpClient class is used; and this instance holds the auth token that has been issued during signing in into this WPF app.
Those HTTP responses that should be cached are returned from the Web API to the WPF app with these headers specified (Cache-Control, Pragma, Expires).

**Comment by Tratcher** [comment]
Interesting. I wonder if it would work if we were setting the right Expires value. https://github.com/aspnet/Security/issues/1353

**Comment by a13531a** [comment]
I think I may have found the reason of such a behavior...

I am using:
1) ASP.NET 4.6
2) Cookie Authentication from Microsoft.Owin.Security.Cookies

I noticed that every time when cookie slides (sliding expiration is turned on), the HttpClient in the WPF app receives a response from the server which contains "Set-Cookie" header + "Cache-Control: private".
It is PRIVATE for some reason! And I am confused why it is so...

I cannot find any extension point neither in ASP.NET nor in OWIN so that I could change "Cache-Control" from PRIVATE to different value (I guess, to "no-cache" value).

Is it expected behavior that the response that contains "Set-Cookie" header has "Cache-Control" set to PRIVATE? To my understanding, it is a bug... Or, I doubt, but maybe something is not configured appropriately in the web service?

Thank you.

**Comment by Tratcher** [comment]
The Microsoft.Owin version set the same headers.
https://github.com/aspnet/AspNetKatana/blob/a4ad9a82cde44ac27242a2d23238aada2ec5b4be/src/Microsoft.Owin.Security.Cookies/CookieAuthenticationHandler.cs#L275-L285
There is no private set here. It's possible the header is being overwritten by a separate part of the application.

**Comment by a13531a** [comment]
Tratcher, you were right.
I found that the Web API project uses the SystemWebCookieManager class from http://katanaproject.codeplex.com/wikipage?title=System.Web%20response%20cookie%20integration%20issues

```
    public partial class Startup
    {
        public void ConfigureAuth(IAppBuilder app, TimeSpan expirationInMins, bool slidingExpiration)
        {
            app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationMode = AuthenticationMode.Active,
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                CookieHttpOnly = true,
                CookieSecure = CookieSecureOption.SameAsRequest,
                ExpireTimeSpan = expirationInMins,
                SlidingExpiration = slidingExpiration,
                **CookieManager = new SystemWebCookieManager()**
            }
        }
    }
```

So, it seems like it may not be enough to use the code from the link above as it is. After I added the following lines to the end of the AppendResponseCookie method, everything began to work. I mean, the "Cache-Control: private" thing is no longer sent in the response when the "Set-Cookie" header is present:

```
var cache = webContext.Response.Cache;
cache.SetCacheability(HttpCacheability.NoCache);
webContext.Response.AppendHeader("Pragma", "no-cache");
cache.SetExpires(new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc));
```

**Comment by Tratcher** [comment]
Interesting, it looks like some of the caching headers are subject to the same System.Web collision issues as the cookies but the symptoms are a lot more subtle so nobody has ever reported it.

**Comment by a13531a** [comment]
Tratcher, you were right.
I found that the Web API project uses the SystemWebCookieManager class from http://katanaproject.codeplex.com/wikipage?title=System.Web%20response%20cookie%20integration%20issues

```
    public partial class Startup
    {
        public void ConfigureAuth(IAppBuilder app, TimeSpan expirationInMins, bool slidingExpiration)
        {
            // Enable the application to use a cookie to store information for the signed in user
            app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationMode = AuthenticationMode.Active,
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                CookieHttpOnly = true,
                CookieSecure = CookieSecureOption.SameAsRequest,
                ExpireTimeSpan = expirationInMins,
                SlidingExpiration = slidingExpiration,
                CookieManager = new SystemWebCookieManager()
            }
        }
```

It seems it is not enough to use the code from the link above as it is. After I added the following lines to the end of the AppendResponseCookie method, everything began to work:

```
            var cache = webContext.Response.Cache;
            cache.SetCacheability(HttpCacheability.NoCache);
            cache.SetExpires(new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc));
            webContext.Response.AppendHeader("Pragma", "no-cache");
```
