### ISSUE TITLE
How use PKCE in OpenIdConnect Middleware

### ISSUE THREAD

**Issue by Jenan** [aspnet/Security#1476]
Hello,

I want to use for getting code the PKCE and I am wondering if is possible setup the OpenIdConnect middleware for generating of the PKCE and use it in the request for the code and then for getting the access token?

I follow this post about PKCE - https://leastprivilege.com/2016/02/02/pkce-support-in-identityserver-and-identitymodel/

Prepare PKCE for request:

```cs
var nonce = CryptoRandom.CreateRandomKeyString(64);
var verifier = CryptoRandom.CreateRandomKeyString(64);
var challenge = verifier.ToCodeChallenge();
 
var request = new AuthorizeRequest("https://my.server/authorization");
var url = request.CreateAuthorizeUrl(
    clientId: "myclient",
    responseType: "code id_token",
    scope: "openid myapi",
    redirectUri: "https://my.client/cb",
    nonce: nonce,
    codeChallenge: challenge,
    codeChallengeMethod: OidcConstants.CodeChallengeMethods.Sha256);
```

and the TokenClient to exchange the code with the token:

```cs
var tokenClient = new TokenClient(
    "https://my.server/token",
    "client",
    "secret");
 
var response = await tokenClient.RequestAuthorizationCodeAsync(
    code: code,
    redirectUri: "https://my.client/cb",
    codeVerifier: verifier);
```

Thank you

**Comment by Eilon** [comment]
@javiercn can you share your thoughts on this?

**Comment by javiercn** [comment]
PKCE is meant to be used mainly by mobile/native clients.

That said, nothing should prevent you from configuring the existing OpenIdConnectMiddleware to do PKCE yourself. You need to hook into the OpenIdConnectEvents OnRedirectToIdentityProvider and OnAuthorizationCodeReceived, set the challenge on the first one and send the verifier on the second one.

That said,  **I don't think this adds any significant value if you are using a web application. Specially if your client is confidential**

As I said, this is meant mostly for native/mobile clients that require the ability to get refresh_tokens (only available through the authorization_code flow) and can't securely store a client secret.

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Events/OpenIdConnectEvents.cs

**Comment by brockallen** [comment]
> PKCE is meant to be used mainly by mobile/native clients.

Not true. PKCE is great at mitigating against the code copy and paste attack for clients that don't use hybrid flow and only use code flow.

**Comment by Jenan** [comment]
@javiercn Please, what is the property in `RedirectContext` for setting codeChallenge? Thank you.

**Comment by Jenan** [comment]
I have tried something like this:

```cs
private async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedContext authorizationCodeReceivedContext)
        {
            var authenticateResult = await authorizationCodeReceivedContext.HttpContext.AuthenticateAsync("TempStateCodeVerifier");
            var codeVerifier = authenticateResult.Principal.FindFirst("code_verifier").Value;

            authorizationCodeReceivedContext.ProtocolMessage.Parameters.Add("code_verifier", codeVerifier);
        }

        private async Task OnRedirectToIdentityProvider(RedirectContext redirectContext)
        {
            var verifier = CryptoRandom.CreateRandomKeyString(64);
            var challenge = verifier.ToCodeChallenge();

            var tempId = new ClaimsIdentity("TempStateCodeVerifier");
            tempId.AddClaim(new Claim("code_verifier", verifier));

            var claimsPrincipal = new ClaimsPrincipal(tempId);
            await redirectContext.HttpContext.SignInAsync("TempStateCodeVerifier", claimsPrincipal);

            redirectContext.ProtocolMessage.Parameters.Add("code_challenge", challenge);
            redirectContext.ProtocolMessage.Parameters.Add("code_challenge_method", "S256");
        }
```

It get an error: 

`OpenIdConnectProtocolException: Message contains error: 'invalid_grant', error_description: 'error_description is null', error_uri: 'error_uri is null'.`

An authorization request contains - `code_challenge `and `code_challenge_method `correctly but request for getting access token - doesn't contain in request body `code_verifier`.

The POST request - on `/signin-oidc` - contains only: `code, id_token, scope, state, session_state`

**Comment by joaco-espinosa** [comment]
> > PKCE is meant to be used mainly by mobile/native clients.
> 
> Not true. PKCE is great at mitigating against the code copy and paste attack for clients that don't use hybrid flow and only use code flow.

@brockallen Isn't PKCE **also** useful for clients **using hybrid**, when these include "code" in the response_type? (which later on will be used to obtain refresh tokens)
