### ISSUE TITLE
How to use B2C and Multiple organization Authentication  in the same Asp.Net Core 2.0 app

### ISSUE THREAD

**Issue by Ahmad-Magdy** [aspnet/Security#1479]
Hello 
i need some help in something i don't know how to do in ASP Core 2.0
i'm using both 
https://login.microsoftonline.com/tfp which is **B2C**
and also using https://login.microsoftonline.com/common for **Multiple organization** 

i looked in the internet how to configure both of them together but i didn't find any guide.
i used https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp/tree/core2.0 for first one 
and i can use Multiple organization from code generator in VS 2017 
but how to combine them together to use it for example if route myUrl/B2C use tfp and if localhost/auth use common one (Multiple organization).

i'm not able to do something like 
`app.Map(new PathString("/B2C"), i => i.UseAzureAd());`
in Configure Method.

and also Signin Method if i need to do in Action

```
var redirectUrl = Url.Action(nameof(HomeController.Index), "Home");
            var properties = new AuthenticationProperties { RedirectUri = redirectUrl };
            return Challenge(properties,
                OpenIdConnectDefaults.AuthenticationScheme);
```

both ways uses OpenId

**Comment by Tratcher** [comment]
Sharing more of your Startup would help.

The main issue is how you want to decide which provider the users should log in with. Do different endpoints have different requirements? Or do you want the user to be able to choose which provider to use?

**Comment by brockallen** [comment]
Sounds like you need a federation gateway: http://docs.identityserver.io/en/release/topics/federation_gateway.html

**Comment by Ahmad-Magdy** [comment]
@Tratcher  I'm migrating from ASP.NET MVC 5 to Asp MVC Core 2.0 so my startup very simple, 
it will be depends on the url so if the url like 'url/B2C' i'll use B2C Method and if the url like 'url/auth' i'll use Multiple organization method, the app will choose depends on the route not on the user choice.


@brockallen  i think it's near the idea but i didn't find any instructions about  specifying the right auth method b2c or multi org or something else.

**Comment by Eilon** [comment]
@javiercn can you take a look?

**Comment by Ahmad-Magdy** [comment]
@Tratcher @Eilon @javiercn  Any news ?

**Comment by Eilon** [comment]
Ping @javiercn .

**Comment by javiercn** [comment]
@Ahmad-Magdy Are you trying to use B2C for production and AAD for local development or do you intend for both to work at the same time?

**Comment by Ahmad-Magdy** [comment]
@javiercn i intend to work with both of them at the same time

**Comment by javiercn** [comment]
Are you trying to protect an API or login in users in a web application? (Are you validating access tokens or stamping a cookie after a successful login flow).

In any case, something along the lines of the PR below should work for your scenario:
You can do something along the lines on this PR https://github.com/aspnet/Security/pull/1486/files.

**Comment by Ahmad-Magdy** [comment]
@javiercn i'm trying to "login in users in a web application",
sorry but i didn't understand anything from this PR

**Comment by Eilon** [comment]
@javiercn can you provide an update on this?

**Comment by Ahmad-Magdy** [comment]
@Eilon  @javiercn  if my problem still not clear enough i want to use B2C(https://login.microsoftonline.com/tfp) and  Multiple organization (https://login.microsoftonline.com/common) in the same application and i choose which one to use depends on the URL.
Is there is any clue when someone can check this problem ??

**Comment by javiercn** [comment]
Hi,

sorry for the delayed response.

In order to do what you want, you need to implement your own authentication handler and based on the path
decide what of the two authentication handlers to use. Something along the lines below (beware its pseudocode):

```csharp
public class RoutingAuthenticationHandler : IAuthenticationHandler, IAuthenticationSignInHandler
    {
        public AuthenticationScheme Scheme { get; private set; }
        protected HttpContext Context { get; private set; }

        public Task InitializeAsync(AuthenticationScheme scheme, HttpContext context)
        {
            if (scheme == null)
            {
                throw new ArgumentNullException(nameof(scheme));
            }
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            Scheme = scheme;
            Context = context;

            return Task.CompletedTask;
        }

        public virtual Task<AuthenticateResult> AuthenticateAsync()
        {
            if(context.Request.Path == "/common")
            {
                return context.AuthenticateAsync("AADScheme")
            }
            if(context.Request.Path == "/tfp")
            {
                return context.AuthenticateAsync("B2C");
            }
        }

        public virtual Task SignInAsync(ClaimsPrincipal user, AuthenticationProperties properties)
        {
            if (context.Request.Path == "/common")
            {
                return context.SignInAsync("AADScheme", user, properties)
            }
            if (context.Request.Path == "/tfp")
            {
                return context.SignInAsync("B2C", user, properties);
            }
        }

        public virtual Task SignOutAsync(AuthenticationProperties properties)
        {
            // Look at the authentication type in the Identity for the claims identity principal.
            var currentScheme = ResolveScheme(Context.User);
            if (currentScheme == "AADScheme")
            {
                return context.SignOutAsync("AADScheme", properties)
            }
            if (currentScheme == "B2C")
            {
                return context.SignOutAsync("B2C", properties);
            }
        }

        public virtual Task ChallengeAsync(AuthenticationProperties properties)
        {
            if (context.Request.Path == "/common")
            {
                return context.ChallengeAsync("AADScheme", properties)
            }
            if (context.Request.Path == "/tfp")
            {
                return context.ChallengeAsync("B2C", properties);
            }
        }

        public virtual Task ForbidAsync(AuthenticationProperties properties)
        {
            var currentScheme = ResolveScheme(Context.User)
            if (currentScheme == "AADScheme")
            {
                return context.ForbidAsync("AADScheme", properties)
            }
            if (currentScheme == "B2C")
            {
                return context.ForbidAsync("B2C", properties);
            }
        }
    }
```

Then on your startup class you can register the virtual scheme and the B2C and AAD and set the B2C scheme as your default

```csharp
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddAuthentication(o => o.DefaultScheme = "Routing")
        .AddB2C(o => ConfigureB2C(o))
        .AddAAD(o => ConfigureAAD(o))
        .AddScheme<RoutingSchemeHandler>("Routing")
    ...
}
```

**Comment by Ahmad-Magdy** [comment]
@javiercn  Perfect!, Thank you for that. 
I'll check it.
