### ISSUE TITLE
Make Authorization available outside of ASP.NET Core

### ISSUE THREAD

**Issue by DerAlbertCom** [aspnet/Security#1480]
I, and others, like the authorization System in ASP.NET Core. But i would like to use it on a deeper level.

In its core, ASP.NET Core is an UI Layer. Which has to present Information to the User, via HTML, JSON or whatever and receive input from a User do something with the data.

With ASP.NET Core the UI has to check the Authorization if a certain kind of operation is allowed for the
User. But the authorization should be a concern of the Business Domain, not the UI. Authorization must be of course exposed to the UI, so that UI can adapt based on the authorization. But the Authorization should be done in the Domain Model.

Today it can looks like this

```C# 
var result = await _authorizationService.AuthorizeAsync(User, new DocumentIdResource(model.DocumentId), Operations.View);
if (result.Succeeded)
{
   var document = _service.LoadDocument(model.DocumentId);
}
```

If you would like to access the document in different places, you have to check in different places multiple times. Of course, it is possible to wrap the call to LoadDocument() to make it simplier.

What you really want is that the *LoadDocument()* method in the domain model/logic check if the current User is able to access access/modify the document. Because the Domain Model is the master of the data and has to decide, not the UI. And of course, the Domain Model should not have dependencies on ASP.NET. So that it can be reused on other Plattforms/UI etc. If i remember .NET Standard was invented to make code reuse a lot easier.

To do it right, you have to implement the authorization in the Domain Model. But then you must duplicate the Authorization in the ASP.NET Core Authorization. Even if you reuse the Domain Model Authorization in the ASP.NET Authorization in a complex application there is a lot of code needed only to fullfill the ASP.NET Authorization.

So I propose a move from **Microsoft.AspNetCore.Authorization** to **Microsoft.Extensions.Authorization**. To have an Standard Authorization Framework which could be used in all kind of Application WPF/UWP/ASP.NET/WinForms.

While writing this issue I disovered that *Microsoft.AspNetCore.Authorization* does not even have other AspNetCore Dependencies. 
Which is a clear sign that it not belong there ;)

For me, I can decide to use Microsoft.AspNetCore.Authorization now in my business logic, but i asume Microsoft can't give a guarantee the the Dependencies will be neutral for the rest of the lifetime. Also it a little weird and it must be explained evertime if someone stumbled over that.

With *Microsoft.Extensions.Authorization* it is clear that there are no AspNetCore Dependecies. And Type Forwarding could be used for compatiblity.

In the Past the MemoryCache was moved outside System.Web, because it was usefull in other places too.

So, please move it ;) And now, discuss.

**Comment by HaoK** [comment]
As you pointed out, the core authorization package already doesn't have any AspNetCore dependencies, so what is preventing you from using it today as is?

**Comment by DerAlbertCom** [comment]
@HaoK Because in the next update there could be some AspNetCore dependencies, maybe because it is easier to get a specific feature. It is in the AspNetCore Namespace is has the right to do this.

Also it is weird to have AspNetCore Dependecies in a UWP Applciation. As it was weird to have dependecies to System.Web only for using MemoryCache (also this broke with the .NET Client Profile long time ago)

**Comment by Eilon** [comment]
Given that this comes down to choice of namespace, and changing the namespace is a breaking change, I'm closing this issue.

**Comment by pi3k14** [comment]
@Eilon wouldn't namespace aliases be a fix for that?

**Comment by Eilon** [comment]
The C# `using` keyword supports namespace aliases, but then everyone would need to do that in their own code. The change we would make would still be a breaking change and break any existing app/library using the API.

Type forwarding only lets you change the assembly, not the namespace.

**Comment by pi3k14** [comment]
Well, strictly speaking, it wouldn't break existing applications. It would demand a change in new versions of existing applications.

**Comment by Eilon** [comment]
It would break any existing application that updated to the new version.

**Comment by pi3k14** [comment]
@Eilon, exactly, as I said.
Hasn't that been the case for all  (ASP).NET Core releases?

**Comment by Eilon** [comment]
@pi3k14 there have been some breaking changes, yes, but we wouldn't make a breaking change for renaming a type in this case.

**Comment by DerAlbertCom** [comment]
What  about a compile compat shim?
```
public interface Microsoft.AspNetCore.Authorization.IAuthorisationService : Microoft.Extensions.Authorization.IAuthorizationService {
}
```

**Comment by Eilon** [comment]
Hi folks, the proposals here simply don't seem to have enough value compared to their cost, so we are not planning to make these changes.

**Comment by freaktoe** [comment]
Given all of the good things being done with .net standard and .net core, this is a disappointing stance.  These libraries do not being in the ASP namespace for the reasons listed above and failure to address it is just lazy.  Asking the community to trust that, just because there's no asp dependency now you will never add them, is asking a lot.

**Comment by DerAlbertCom** [comment]
Now with 3.0 on the horizon there is a chance for the breaking change. Together with a Shim Assembly to maintain compile time compatibilty with current source code.
