### ISSUE TITLE
[Authorzie] doesn't work published on Debian .net Core 2

### ISSUE THREAD

**Issue by BlackBackground** [aspnet/Security#1487]
Hay,

we write a .net core 2.0 application how will be used on a iis or a linux server.

Important controller actions gets the tag [Authorize]. If we debug and publish the application on iss, they work. After sign in with this command line:

`_signInManager.PasswordSignInAsync(`

the User is authenticated and can use the controller actions with the tag [Authorize]. If the application published on debian 8.9 server the [Authorize] seems to work, so I can not access to the protected controller actions. But the signIn seems not to work. After sign in I don't have access to the protected controller actions.

ConfigureServices:

```c#
services.AddIdentity<ApplicationUser, IdentityRole>(config =>
            {
                config.SignIn.RequireConfirmedEmail = true;
            })
                .AddEntityFrameworkStores<DatenContext>()
                .AddDefaultTokenProviders();
            services.Configure<IdentityOptions>(options =>
            {
                // Lockout settings
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(10);
                options.Lockout.MaxFailedAccessAttempts = 10;
                // User settings
                options.User.RequireUniqueEmail = true;
            });
```

Configure:

`app.UseAuthentication();`

Anyone have an idea? Please ask if you need specially informations.

**Comment by Tratcher** [comment]
A Fiddler trace may help show the problem. The application logs may also help.

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.
