### ISSUE TITLE
[Authorize] on both Controller and Method won't work with ASP.Net Core 2.0

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1489]
_From @sadjadbp on October 13, 2017 7:55_

Using ASP.Net Core 1, I had this this controller that had [Authorize] attrib so it would go to default schema which is Cookie in my case and then on some of its methods I would go [Authorize("Bearer")], so those specific ones would have Jwt Authentication enabled.

Now that I upgraded to ASP.Net Core v2, for those JWT enabled methods I'll get 302 even if I pass JWT. So the fix for me is to remove the [Authorize] attrib from class and put it on all methods, but this way it opens my controller to developers mistake that they might forget to add [Authorize] per method.

_Copied from original issue: aspnet/Home#2242_

**Comment by Tratcher** [comment]
@HaoK

**Comment by Eilon** [comment]
@HaoK can you try to repro this based on what we think the scenario is?

@sadjadbp can you provide a complete repro app and upload to GitHub? That will make it easier for us to make sure we're looking at the exact problem you're having.

**Comment by sadjadbp** [comment]
I'll try to create a repo to contain the whole code, but gist of the question is that the code below used to work in ASP.Net Core 1.1 and now that I've updated to V2 calling from an authorized user with Role="Services" will 302 me to login page. But if I remove that class attrib and put it on Method1 everything works fine. Make sense?

`    [Authorize]
    public class MyController : Controller
    {
        [HttpGet("[controller]/Method1")]
        public IActionResult Method1(int clientID)
        {
        }

        [Authorize(Roles = "Services")]
        [HttpGet("api/Services/[controller]/Method2")]
        public IActionResult Method2()
        {
        }
   }`

**Comment by sadjadbp** [comment]
Seems like the above code works unless Roles = "Services" are coming from Bearer.

The situation is I have dual authentication "Cookie and Bearer". Cookies have a default Role and Bearer ones have Services role. So now I want all my controllers to have that [Authorize] attrib so I know it's secure and some methods should be called only from Services roles. Now this used to work in ASP.Net Core 1.1 and now it's broken.

**Comment by HaoK** [comment]
The code you have listed is exactly what we expect you would need for 2.0.  Method1 is using cookie authentication via the inherited attribute.  The second Method2 is using Bearer via Policy, and also requires the Services role.  

What are you hoping the code looks like instead?

**Comment by sadjadbp** [comment]
@HaoK the problem is once Method2 is called, using Bearer it used to work in v1 but now that moved to .net core v2 it won't work and will return 302 to login page.

**Comment by Tratcher** [comment]
Sounds like it's challenging both the default (Cookies) and the explicit (Bearer). It was probably doing the same in v1 but in the reverse order so you didn't notice, as Bearer's 401 would overwrite Cookie's 302.

**Comment by HaoK** [comment]
Hrm seems like there's something weird going on with MVC.  I debugged/stepped thru all of the combine tests, and the behavior at those layers is correct.

But it appears that in a controller, when `[Authorize]` and `[Authorize(AuthenticateScheme = "Bearer")]` are combined, that is resulting in a challenge to both Cookies and Bearer.  I can't repro this at unit test level using just the attributes and the underlying service.  But I can hit it when doing it via Controllers methods.

**Comment by HaoK** [comment]
Okay looks like there's a mismatch in expectations here.

@rynowak It appears that if you have `[Authorize]` on a Method, and a Controller, you end up with an AuthorizationFilterContext with two `AuthorizeFilters`.  While the authorize filter was written with the assumption that `AuthorizeData` property would contain all of the attributes.  Was there any changes in this stuff since 1.x?  (Its also possible that this has always been broken even in 1.x since it would have been hard to notice this behavior until auth 2.0 which is more rigid)

Regardless, there's a functional issue now, where Controller `[Authorize]` is not combined with Method `[Authorize]` attributes to form a single authZ policy, and basically both are run, which is wrong...

**Comment by HaoK** [comment]
Filed https://github.com/aspnet/Mvc/issues/6995 in MVC to track

**Comment by rynowak** [comment]
> Was there any changes in this stuff since 1.x?

No, I was told that it was always this way and that it was cool and good.

**Comment by Eilon** [comment]
@HaoK @Tratcher @rynowak @javiercn - can you guys meet to figure out the best way to fix this?

**Comment by Eilon** [comment]
Issue moved to https://github.com/aspnet/Mvc/issues/6995 because MVC is where the fix would be.
