### ISSUE TITLE
OpenIdConnect Middleware doesn't send the code_verifier in params for getting access token

### ISSUE THREAD

**Issue by Jenan** [aspnet/Security#1490]
Hello,

I have tried to use PKCE with OpenIdConnect middleware - something like this:

Startup:
```
.AddOpenIdConnect("oidc", options =>
{
...
options.Events = new OpenIdConnectEvents()
{
OnRedirectToIdentityProvider = OnRedirectToIdentityProvider,
OnAuthorizationCodeReceived = OnAuthorizationCodeReceived
 };
}
```

Events:
```
 private async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedContext authorizationCodeReceivedContext)
        {
            var authenticateResult = await authorizationCodeReceivedContext.HttpContext.AuthenticateAsync("TempStateCodeVerifier");
            var codeVerifier = authenticateResult.Principal.FindFirst("code_verifier").Value;

            authorizationCodeReceivedContext.ProtocolMessage.Parameters.Add("code_verifier", codeVerifier);
        }

        private async Task OnRedirectToIdentityProvider(RedirectContext redirectContext)
        {
            var verifier = CryptoRandom.CreateRandomKeyString(64);
            var challenge = verifier.ToCodeChallenge();

            var tempId = new ClaimsIdentity("TempStateCodeVerifier");
            tempId.AddClaim(new Claim("code_verifier", verifier));

            var claimsPrincipal = new ClaimsPrincipal(tempId);
            await redirectContext.HttpContext.SignInAsync("TempStateCodeVerifier", claimsPrincipal);

            redirectContext.ProtocolMessage.Parameters.Add("code_challenge", challenge);
            redirectContext.ProtocolMessage.Parameters.Add("code_challenge_method", "S256");            
        }
```

In method `OnAuthorizationCodeReceived` I have tried add the `code_verifier` but in POST request doesn't contain this parameter.

It get an error:

> OpenIdConnectProtocolException: Message contains error: 'invalid_grant', error_description: 'error_description is null', error_uri: 'error_uri is null'.

An authorization request contains - `code_challenge` and `code_challenge_method` correctly but request for getting `access token` - doesn't contain in request body `code_verifier`.

The POST request - on `/signin-oidc` - contains only: `code, id_token, scope, state, session_state`

This issue is connected with this: https://github.com/aspnet/Security/issues/1476 

How can I solve this problem?

Thank you.

**Comment by PinpointTownes** [comment]
> How can I solve this problem?

You add your `code_verifier` to the wrong `OpenIdConnectMessage` instance. Use `authorizationCodeReceivedContext.TokenEndpointRequest` instead of `authorizationCodeReceivedContext.ProtocolMessage` and it should work.

**Comment by Jenan** [comment]
@PinpointTownes You are awesome - works perfectly!
Thank you for your reply. :)

**Comment by PinpointTownes** [comment]
Glad I coud help! :call_me_hand:

**Comment by Jenan** [comment]
@PinpointTownes I am still wondering about if it is correct solution store the code_verifier in temp cookie like above - what do you think about it? Thank you.

**Comment by PinpointTownes** [comment]
> I am still wondering about if it is correct solution store the code_verifier in temp cookie like above - what do you think about it?

You don't have many options.

You could store the code verifier in the authentication properties (that are later encrypted and are serialized in the `state` parameter), but this would almost defeat the whole purpose of using PKCE... because if an attacker managed to steal the `code`, changes would be very high he'd also be able to steal the `state` (containing the correct code verifier) and use it on his own machine.

Other options might include manually storing the verifier in a database, or using sessions + a distributed cache like Redis. Not sure they'd be better, tho'.

**Comment by Jenan** [comment]
@PinpointTownes Thank you for your ideas. :) I appreciate that. For now I stay in the cookie and maybe later I'll try implement another solution as you mentioned.
