### ISSUE TITLE
Middleware ordering changes when specifying AuthenticationSchemes in [Authorize]

### ISSUE THREAD

**Issue by upta** [aspnet/Security#1492]
### Title
*Middleware ordering changes when specifying AuthenticationSchemes in [Authorize]*

### Functional impact
*Adding a custom middleware.  When using .AddAuthentication( ... ), it fires Auth -> Middleware (as expected).  When using  [Authorize( AuthenticationSchemes = ... )], it fires Middleware -> Auth*  

### Minimal repro steps
https://github.com/upta/AspNetCore-MiddlewareIssues

### Expected result
*Custom middleware should fire in the correct order regardless of how the authentication scheme is specified*

### Actual result
*Custom middleware fires before auth regardless of specified order*

**Comment by Tratcher** [comment]
This is intentional. The UseAuthentication middleware authenticates the default scheme if specified so that the User is available on the HttpContext for the rest of the pipeline. If no default scheme is specified then auth does not run until you reach your controller with [Authorize] attributes.

**Comment by upta** [comment]
So it's basically "default scheme or nothing" if you want User available to your middleware?

**Comment by Tratcher** [comment]
Or your middleware can invoke the auth service itself.

**Comment by upta** [comment]
How would I go about doing that? (sorry, total noob with .Net core stuff, didn't start really even looking at it until 2.0 came out).

Thanks for your help!

**Comment by Tratcher** [comment]
`HttpContext.AuthenticateAsync("MyAuthScheme");`
