### ISSUE TITLE
Specifying AuthenticationSchemes on [Authorize] attribute behaves very differently than using a default scheme

### ISSUE THREAD

**Issue by upta** [aspnet/Security#1493]
### Title
*Specifying AuthenticationSchemes on [Authorize] attribute behaves very differently than using a default scheme*

### Functional impact
*There are several, but the underlying issue is that the two means of specifying a scheme behave differently.  I ran into issues both trying to override an authentication scheme as well as trying to use [AllowAnonymous] when AuthenticationSchemes is used.  My repro project details it better (I hope ;))*  

### Minimal repro steps
*https://github.com/upta/AspNetCore-SchemeIssues*

### Expected result
*Consistency between the way of specifying scheme. The default scheme way seems behave a bit more how I'd expect in general (e.g. doesn't still process the authentication when using [AllowAnonymous], etc)*

### Actual result
*Much inconsistency*

**Comment by Tratcher** [comment]
I don't quite follow the comments in your repro. This one for example:
https://github.com/upta/AspNetCore-SchemeIssues/blob/7ff1f5a2b7c4b8a67afffdab08addef0270115a6/SchemeIssues/Anonymous/NoScheme/OnClass.cs#L13
You refer to an [Authorize] attribute without schemes, but there are no Authorize attributes in this file. There is a similar mismatch between the comments and code in the remaining files.

**Comment by upta** [comment]
They use a base class with [Authorize] on it (https://github.com/upta/AspNetCore-SchemeIssues/blob/7ff1f5a2b7c4b8a67afffdab08addef0270115a6/Shared/BaseNoScheme.cs)

Sorry, that really should have ended up in the same project (did the middleware one first and it was useful there to have it in a "Shared" project; not so much for this one, but I'd copied it over ;)

**Comment by Eilon** [comment]
All the `[Authorize]` attributes are unioned to get the full set of requirements, and then that new set is what gets used to determine the state of the request. If there are either too many or not enough, then the data in the attributes need to be modified to create the right result.

**Comment by upta** [comment]
Honestly, I've completely given up on trying to support multiple authentication schemes for a given request.  It's too awkward and behaves too strangely compared to the single, default setup.

Thanks anyway for looking at it!

**Comment by Eilon** [comment]
@HaoK can you work with @blowdart to describe what the combination behavior is so that we can get a doc published on this?

**Comment by HaoK** [comment]
The behavior that's confusing is actually this bug: https://github.com/aspnet/Mvc/issues/6995

**Comment by HaoK** [comment]
We added a new CombineAuthorizeFilters option to MVC which will fix this issue, should start showing up in 2.1-preview1 73bd09dc1c8abe2ff71cd33679fa17ebd04ff189

**Comment by HaoK** [comment]
I believe the plan is to turn this on by default using the compatibility switches in MVC, so this should just start working automatically starting in 2.1
