### ISSUE TITLE
net core 2.0 -- cookie authentication not working

### ISSUE THREAD

**Issue by plsft** [aspnet/Security#1496]
AddCookieAuthentication() doesn't seem to work for me. I thought i added the correct packages. any thoughts? getting:

InvalidOperationException: No IAuthenticationSignInHandler is configured to handle sign in for the scheme: Cookies

with following code:

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddAuthorization(o =>
        {
            o.AddPolicy("Users", p => p.RequireClaim("Users"));
            o.AddPolicy("SuperUsers", p => p.RequireClaim("SuperUsers"));
            o.AddPolicy("PlatformUsers", p => p.RequireClaim("PlatformUsers"));
        });

        services.AddAuthentication(options =>
        {
            options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        }).AddCookie("Cookieauth", options =>
        {
            options.LoginPath = new PathString("/login");
            options.AccessDeniedPath = new PathString("/error?unauth");
        });

        services.AddMvc();
    }

**Comment by Tratcher** [comment]
Your scheme names don't match. That should be
```
        services.AddAuthentication("Cookieauth")
        .AddCookie("Cookieauth", options =>
        {
            options.LoginPath = new PathString("/login");
            options.AccessDeniedPath = new PathString("/error?unauth");
        });
```

**Comment by plsft** [comment]
I removed the follow code 
,options =>
            {
                options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            }

new code:
public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthorization(o =>
            {
                o.AddPolicy("Users", p => p.RequireClaim("Users"));
                o.AddPolicy("SuperUsers", p => p.RequireClaim("SuperUsers"));
                o.AddPolicy("PlatformUsers", p => p.RequireClaim("PlatformUsers"));
            });

            services.AddAuthentication("_AUTH")
            .AddCookie("_AUTH", options =>
                {
                    options.Cookie = new CookieBuilder()
                    {
                        Expiration = TimeSpan.FromDays(3)
                    };
                options.LoginPath = new PathString("/login");
                options.AccessDeniedPath = new PathString("/error?unauth");
            });      

             services.AddMvc();
        }

Still getting:

InvalidOperationException: No IAuthenticationSignInHandler is configured to handle sign in for the scheme: Cookies

**Comment by plsft** [comment]
OK, this works. 

 public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthorization(o =>
            {
                o.AddPolicy("Users", p => p.RequireClaim("Users"));
                o.AddPolicy("SuperUsers", p => p.RequireClaim("SuperUsers"));
                o.AddPolicy("PlatformUsers", p => p.RequireClaim("PlatformUsers"));
            });

            services.AddAuthentication(options =>
            {
                options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            }).AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
            {
                options.LoginPath = new PathString("/login");
                options.AccessDeniedPath = new PathString("/error?unauth");
            });

             services.AddMvc();
        }

**Comment by dennis3001** [comment]
Still can't get this to work. Seems that when using Identity the cookie options are ignored. The options callback is not even firing:

`services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).
                AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
                {
                    // The line below  never get's fired ...
                    options.Cookie.Name = "SessionCookie";
                 });
            
            services.AddIdentity<ApplicationUser, IdentityRole>()
            .AddEntityFrameworkStores<ApplicationDbContext>()
            .AddDefaultTokenProviders();`

**Comment by Tratcher** [comment]
AddIdentity calls AddAuthentication and AddCookie internally. To configure the identity cookie call ConfigureApplicationCookie like this: https://github.com/aspnet/Identity/blob/85f8a49aef68bf9763cd9854ce1dd4a26a7c5d3c/src/Service/IdentityServiceServiceCollectionExtensions.cs#L63-L68
