### ISSUE TITLE
Trying to use the library with IdentityServer IdP / WS-Federation, and getting the following error

### ISSUE THREAD

**Issue by homam1** [aspnet/Security#1497]
Trying to use the library with IdentityServer IdP / WS-Federation, and getting the following error

```
An unhandled exception occurred while processing the request.

XmlReadException: IDX21011: Unable to read XML. Expecting XmlReader to be at ns.element: 'http://schemas.xmlsoap.org/ws/2005/02/trust.RequestSecurityTokenResponse', found: 'http://docs.oasis-open.org/ws-sx/ws-trust/200512.RequestSecurityTokenResponseCollection'.
```
Using JWT Token.

Any idea ?

**Comment by leastprivilege** [comment]
The current public preview is missing support for WS-Trust 1.3. This is supposed to be fixed in RTM.

In the dev branch
https://github.com/IdentityServer/IdentityServer4.WsFederation

I switched to an older version of WS-Trust to make it work.

**Comment by homam1** [comment]
I am using Identity Server 2. Any work around in the client .net core library I can do ?

**Comment by leastprivilege** [comment]
No.

**Comment by homam1** [comment]
Thanks alot for your answers. Any idea when will it be released? 
As I can see, the workaround is to use a [library ](https://github.com/chrisdrobison/aspnetcore-wsfed)made by chrisdrobison. And this is ASP.Net core with .Net Framework.

**Comment by leastprivilege** [comment]
I am not working for Microsoft..

**Comment by Tratcher** [comment]
See https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/739#issuecomment-337341650

**Comment by Eilon** [comment]
Indeed, please follow the AzureAD repos for the latest on those features.
