### ISSUE TITLE
Programmatically build the redirectUri that HandleChallengeAsync does in OpenIdConnect

### ISSUE THREAD

**Issue by ghstahl** [aspnet/Security#1500]
Feature Request:  

I am using the Microsoft.AspNetCore.Authentication.OpenIdConnect provider configured against Google.
I have this angular app that wants to make an Ajax call to get google uri that was built as a result of HandleChallengeAsync being called.
The uri looks something like this.

https://accounts.google.com/o/oauth2/v2/auth?client_id=1096301616546-edbl612881t7rkpljp3qa3juminskulo.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Flocalhost%3A44300%2Fsignin-google&blah-blah-blah

The angular app will then decide when to do a window.location = theLoginUri;

Nobody wants to intercept a 302 client side.

I want a variation of this method that exists in the stock AccountController.cs
```
        public IActionResult ExternalLogin(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.Action(nameof(ExternalLoginCallback), "Account", new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return Challenge(properties, provider);
        }
```
where I can do something like;

var whatifResult = WhatIf(Challenge(properties,provider));
var theLoginUrl = whatifResult.redirectUri;

where WhatIf is the final result of what would happen if this Challenge went through the middleware.

Any alternative to this that produces that final google url would be great.

I can then expose this via a RestAPI to my angular app.

**Comment by Tratcher** [comment]
The OpenIdConnect handler is not designed for Rest APIs, it's for user interactive flows.
JwtBearer is designed for Rest APIs, but it requires the addition of a token server to issue you JWTs.
This looks promising: https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow

**Comment by ghstahl** [comment]
@Tratcher My first thoughts were hoping that the code that the OpenIdConnect handler is using was just a library anyone could call.  The OIDCHandler uses it one one, I use it another by front-ending the result with a REST API.  Arguable simplistic and I can see you guys just telling me to copy the code and have at it, as it isn't something that is going in the framework.   Before I do that...is it even a reasonable ask to expose that code in a library form?

**Comment by ghstahl** [comment]
@Tratcher I just stepped the code, and see what you mean.  I can't just blindly get the google login url and use it, because there is some nonce cookie you are dropping.  When it comes back it rightly fails in the context I would use it as.  
So yeah, I am going to abandon this request ;)

**Comment by Tratcher** [comment]
I suspect you have the entire flow wrong, not just that you're missing a library. Check out that sample I linked.
