### ISSUE TITLE
Implement ClaimActions and cull WsFed claims

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1504]
WsFed does not currently implement ClaimActions. Add it.

Also, review what claims WsFed provides by default. In OIDC we opted to cull the claims referring to protocol details and not user specific information. Purging these will reduce cookie sizes.
Compare to OIDC:
https://github.com/aspnet/Security/blob/794e9c79fd15ccd550737c6ee41dc96722a303f2/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L47-L61
https://github.com/aspnet/Security/blob/794e9c79fd15ccd550737c6ee41dc96722a303f2/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L700-L704

**Comment by brockallen** [comment]
>  ClaimActions.DeleteClaim("acr"); 
> ClaimActions.DeleteClaim("amr"); 

I know we discussed this already, but at a customer last week they specifically need step up authN for a user and depend on amr and acr for this. Please consider not stripping these (or the equivalents for ws-fed) by default.

**Comment by Tratcher** [comment]
What are the equivalents for WsFed?

**Comment by Tratcher** [comment]
This might not be a good fit. The ClaimActions were designed for OAuth and OIDC user information which is Json based. WsFed doesn't have a user info endpoint and only gives you the claims from the frontchannel. You'd be restricted to actions that delete claims, and the default list of AAD claims isn't that bad:
```
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier | 4PYNmfodMrVGtFA2kGuR4g4DIG46Z8x4Rgujk8xwOJo
http://schemas.microsoft.com/identity/claims/tenantid | cdc690f9-b6b8-4043-813a-bae7143d1f87
http://schemas.microsoft.com/identity/claims/objectidentifier | 5820498e-ab4b-434b-bbe2-56022eeed26e
http://schemas.microsoft.com/identity/claims/displayname | chthgoss
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress | chtghoss@microsoft.com
http://schemas.microsoft.com/identity/claims/identityprovider | https://sts.windows.net/72f988bf-86f1-41af-70ab-2d7cd011db47/
http://schemas.microsoft.com/claims/authnmethodsreferences | urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod | urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationinstant | 2017-11-01T23:11:45.004Z
```
