### ISSUE TITLE
Does loading the openid configuration happen on every request ? And if not, is it thread-safe ? 

### ISSUE THREAD

**Issue by sirajmansour** [aspnet/Security#1505]
https://github.com/aspnet/Security/blob/442df16e265ab1955d7b8468cf1d8b38b8d915c7/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L175

**Comment by Eilon** [comment]
The current implementation loads it once when the app starts, and then it's cached, and it will expire once per day.

There should be no particular threading concerns here.

**Comment by sirajmansour** [comment]
For those interested, the caching and refresh of the configuration is handled by the class [ConfigurationManager\<T\>](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.protocols.configurationmanager-1?view=azure-dotnet)
