### ISSUE TITLE
How to get jwt from my asp client application?

### ISSUE THREAD

**Issue by efrainmejiasc** [aspnet/Security#1506]
Hello ...
I need to develop an application that requests a JWT and I do not know how to do it I only have the authentication data that the client gave me ... I need a good tutorial or example code.

OpenId Connect Data :
Access Token URL = https: // unsitio / web / token
Grant Type = zzzzz
Authorization Grants = xxxxxx
Client Id = nnnnnnnn
Client Secret = [Empty]
Scope = [Empty]
Username = hhhhhh@vvvv.ggg.oooo.lll
Password = sssssssss

**Comment by Eilon** [comment]
@efrainmejiasc can you provide more info about what you're trying to do?

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.
