### ISSUE TITLE
Twitter authentication throws exception when user cancels the login

### ISSUE THREAD

**Issue by rmarskell** [aspnet/Security#1507]
I set up Twitter authentication and everything works fine if the login is successful. However, if I hit the cancel button on Twitter's login page (and the subsequent "Return to web app" button), it hits the callback URL (site.com/signin-twitter) with a "denied" query string parameter instead of the expected "oauth_token" parameter. This causes the page to throw an exception. The code that causes this can be found [here](https://github.com/aspnet/Security/blob/144ee21696e838c1f96676573ffe30e8f2ba8bd6/src/Microsoft.AspNetCore.Authentication.Twitter/TwitterHandler.cs#L63:L67).

I feel like this should be handled better by default.

Is there some way for me to catch this exception and show the user something that's not an error screen or even just return them to the login page with a message?

**Comment by Tratcher** [comment]
Yes, we should handle this better. There's a proposal in this issue: https://github.com/aspnet/Security/issues/1165#issuecomment-321692471

In the meantime you can hook into the OnRemoteFailure event and handle it as you like.
https://github.com/aspnet/Security/issues/1165#issuecomment-289522941

Closing as a duplicate.

**Comment by rmarskell** [comment]
@Tratcher Thanks! I searched all over for this Twitter cancel issue but never came across that thread. That was super helpful.

For anyone else that finds this, this is what I ended up with for my `Startup.cs` `services.AddTwitter` method:
```
.AddTwitter( cfg => {
    cfg.ConsumerKey = Configuration["Authentication:Twitter:ConsumerKey"];
    cfg.ConsumerSecret = Configuration["Authentication:Twitter:ConsumerSecret"];

    cfg.Events = new TwitterEvents() {
        OnRemoteFailure = ctx => {
            ctx.Response.Redirect( "/Account/Login?error=" + HttpUtility.UrlEncode( "We were unable to log you in. Please try again." ) );
            ctx.HandleResponse();
            return Task.FromResult( 0 );
        }
    };
} )
```
