### ISSUE TITLE
OpenId Connect Authentication doesn't work when behind a reverse proxy with an url prefix

### ISSUE THREAD

**Issue by waldo2188** [aspnet/Security#1508]
Hello,

I use An OpenId Connect Authentication in an ASP.NET Core 2 project. I use a custom `CallbackPath`.
During development everything work fine (like ever). When I reach the protected page, the OpenId Connect middleware redirect me to the right URI with the good redirect url.

But on my production server…
My App is host inside a Docker behind a reverse proxy and has an url prefix. The app is reachable at https://app.domain.org/api/app1, and `/api/app1` is his url prefix.

I must add the url prefix to the `CallbackPath`, because when the `redirect_url` is generated, the url prefix isn’t add automatically from the header property ` X-Forwarded-Prefix `.

But it’s look like, if I add this url prefix, when the user’s browser come back from the authentication system, the OpenId Connect middleware never understoud that’s the redirect uri. Because the URL in the context has no url prefix and so is not the same who was stored the `CallbackPath`.
So, the OpenId Connect middleware never process the authentication and send back the user to the authentication page.

I’ve checked in the header received from the reverse proxy that the value for the properties `X-Forwarded-For`, `X-Forwarded-Host`, `X-Forwarded-Prefix` and `X-Forwarded-Proto` was well set.

I don’t know what I’ve missed to configure the OpenId Connect middleware ?

**Comment by Tratcher** [comment]
This is not an OIDC specific issue, it's a general reverse-proxy issue. All link generation in your app depends on knowing the proper scheme, host, and pathbase.

The UseForwardedHeaders middleware is used to process x-forwarded-for, host, and proto. There's no built in support for x-fowarded-prefix. If this is a constant value you can hard code it in your app with app.UsePathBase("/api/app1"). If it's dynamic you can map this yourself via middleware like this:
```
app.Use((context, next) =>
{
  var prefix = context.Request.Headers["x-forwarded-prefix"];
  if (!StringValues.IsNullOrEmpty(prefix))
  {
    context.Request.PathBase = PathString.FromUriComponent(prefix.ToString());
    // TODO: subtract PathBase from Path if needed.
  }
  return next();
});
```

I'll close this and refer you to the main discussion at https://github.com/aspnet/Docs/issues/2384.

**Comment by waldo2188** [comment]
Thanks for your answer.

`app.UsePathBase("/api/app1")` doesn't work for me, but `context.Request.PathBase` did the trick!

You save my day ;)
