### ISSUE TITLE
Authentication: OpenIdConnect + IdentityServer (Bearer)

### ISSUE THREAD

**Issue by wyle-e-coyote** [aspnet/Security#1509]
I've read almost every post I can find on the new updates to the authentication in 2.0.  I'm 98% of the way there, I just can not seem to get the last 2% working.

Setup: We have a service that is used for user authentication (OpenIdConnect) and has some API endpoints secured with JWT (IdentityServer/Bearer).  We are using an identity server for all of our token creation/validation.

Issue: OpenIdConnect authentication works as expected.  The IdentityServer/Bearer authentication fails to get called.

Startup.cs
 
```
// ConfigureServices
services.AddAuthentication(options =>
{
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
})
.AddCookie()
.AddOpenIdConnect((options) => GetOpenIdConnectOptions(options))
.AddIdentityServerAuthentication(options => GetIdentityServerAuthenticationOptions(options));

// Configure
app.UseAuthentication();
app.Map("/organizations", app2 => 
    app2.UseAuthenticationScheme(IdentityServerAuthenticationDefaults.AuthenticationScheme))
```

Controller
```
    [Authorize(AuthenticationSchemes = IdentityServerAuthenticationDefaults.AuthenticationScheme)]
    [Route("organizations")]
    public class OrganizationController : Controller
    ...
```
^ According to what I've read -- by specifying the authentication scheme in the attribute it should know which authentication scheme to use.  I have not found this to be the case.  It _always_ uses the default.  Which is why I went the route of writing my own middleware -- which does help.

AuthenticationSchemeMiddleware (Picked up from other posts)
```
    public class AuthenticationSchemeMiddleware
    {
        private readonly RequestDelegate _next;
        private readonly string _scheme;

        public AuthenticationSchemeMiddleware(RequestDelegate next, string scheme)
        {
            _next = next;
            _scheme = scheme ?? throw new ArgumentNullException(nameof(scheme));
        }

        public async Task Invoke(HttpContext httpContext)
        {
            var result = await httpContext.AuthenticateAsync(_scheme);

            if (result.Succeeded)
            {
                httpContext.User = result.Principal;
            }

            await _next(httpContext);
        }
    }

    public static class AuthenticationMiddlewareExtensions
    {
        public static IApplicationBuilder UseAuthenticationScheme(this IApplicationBuilder builder, string scheme)
        {
            return builder.UseMiddleware<AuthenticationSchemeMiddleware>(scheme);
        }
    }
```

This allows my token to be validated.  However, the _next(httpContext) returns 404... 

Any help on this would be greatly appreciated.

**Comment by wyle-e-coyote** [comment]
This can be closed.

The reason I was getting 404 was due to the ```app.Map``` ending the pipe (from what I read).  By updating this to ```app.UseWhen``` the pipe would continue on to MVC and everything worked as expected.

**Comment by Tratcher** [comment]
To clarify, httpContext.User is always initialized to the default by the UseAuthentication middleware. However, this should be overridden by `[Authorize(AuthenticationSchemes...`
Were you seeing the wrong user on httpContext.User in your MVC Controllers?

**Comment by wyle-e-coyote** [comment]
> However, this should be overridden by [Authorize(AuthenticationSchemes...

This was a problem for me.  Even though I was specifying the AuthenticationScheme in the Authorize attribute, it would always use the default authentication scheme (OpenIdConnect).  This is the only reason I wrote the middleware -- which did end up working.
