### ISSUE TITLE
Multiple OpenIdConnect providers causes correlationId error if not using first provider in list

### ISSUE THREAD

**Issue by shahiddev** [aspnet/Security#1510]
(first time submitting issue to aspnet so hopefully everything is in order).
Slightly weird issue I'm finding using OpenIdConnect with brand new aspnet.core 2.0 web app.

 `<TargetFramework>netcoreapp2.0</TargetFramework>`
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>
```
OS: Windows 10 FCU
IIS Express (defaults from new project template)
Steps:
Create brand new asp.net core MVC application with Individual accounts.
In `startup.cs` configure 2 OpenId connect providers in the ConfigureServices method.

Issue:
Calling the first provider works fine, if you call the second provider when the token service returns it causes a correlation failed exception. 
**Swapping the order of the declaration shows that its always the second provider declared that is throwing .**
Configuration here:
```csharp
services.AddAuthentication()
             .AddOpenIdConnect("idservoidc1", "OpenID Connect 1", options =>
                {
                    options.Authority = "https://demo.identityserver.io/";
                    options.ClientId = "implicit"; 
                })
               .AddOpenIdConnect("idservoidc2", "OpenID Connect 2", options =>
                {
                    options.Authority = "https://demo.identityserver.io/";
                    options.ClientId = "implicit";                    
                });
```

Created repro here: https://github.com/shahiddev/openIdConnectIssue/tree/master
Note: this uses the demo IdentityServer as the token provider twice but I've tested with IdServer & AzureAD as the two providers with same issue

Exception:
`System.Exception: Correlation failed.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()`

**Comment by Tratcher** [comment]
When you have multiple AddOpenIdConnect's they each need a unique CallbackPath. The default is "/signin-oidc".

**Comment by shahiddev** [comment]
Thank you @Tratcher! That's resolved it, I didn't see this in the docs anywhere  :(  
I'll close the issue now

**Comment by jay-vacc-2018** [comment]
Hi Shahidev,
I had a look at the code, and was wondering if you could help me with figuring out which Controller/Action will get authenticated using idservoidc1, and idservoidc2?
I am trying to validate user using Azure Active Directory, and Azure B2C. So if authentication fails in one, go the B2C. Will this be similar scenario to what you are trying to achieve?
Thanks,
Jay

**Comment by shahiddev** [comment]
Hi Jay,
assuming your authentication flow completes it should return to the `accountcontroller` `ExternalLoginCallback` method where you can then decide what to do. There are also some events exposed by the in the openidconnect middleware if you need to make some decisions in the middleware.

**Comment by ydekova** [comment]
This requirement was not present in 1.1. Please, add this here https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x?view=aspnetcore-2.1

**Comment by Tratcher** [comment]
? Yes, this was a 1.1 requirement though the error messages may have changed.

**Comment by ydekova** [comment]
Interesting, we had the "/signin-oidc" endpoint configured as the callback URL for two OIDC authentications (Microsoft and Google). This was working for quite some time, and the problem occurred only after the upgrade. We also use Identity Server 4 in the same project to issue tokens, I'm not sure if it matters in this case.
