### ISSUE TITLE
Optionally disable certificate check?

### ISSUE THREAD

**Issue by Compufreak345** [aspnet/Security#1511]
Hi,

for development purposes we use a self-signed certificate for the WsFederation-server. Is it possible to disable the verification of the certificate, like if I add --insecure to a curl-command?

I get this error:
```
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://server/FederationMetadata/2007-06/FederationMetadata.xml'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://server/FederationMetadata/2007-06/FederationMetadata.xml'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
```

Thanks & best regards,
Christoph

**Comment by celeste-pu** [comment]
I may be misunderstanding what you're looking for, but would this work for you?
jwtOptions.TokenValidationParameters.ValidateIssuerSigningKey = false;

alternately, implement your own validator:
jwtOptions.TokenValidationParameters.IssuerSigningKeyValidator = mySigningKeyValidator;

**Comment by Tratcher** [comment]
`options.BackchannelHttpHandler = new HttpClientHandler() { ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator }`

**Comment by Eilon** [comment]
BTW please be extremely careful to set this **only** for development purposes, for example, by guarding it in a check for `environment.IsDevelopment()` (with environment being an IHostingEnvironment instance) to make sure that this code doesn't make it into production.

You can get the `IHostingEnvironment` by adding a parameter `IHostingEnvironment hostingEnvironment` to your app's Startup.ConfigureServices method.
