### ISSUE TITLE
context.Properties.Items no longer contains key after upgrading to 2.0.0

### ISSUE THREAD

**Issue by smatsson** [aspnet/Security#1513]
Hi!

I'm not really an expert on OpenId so please forgive if I mess up the terminology :) 

We are using OpenIdConnect from a ASP.NET Core web app. The authority is Auth0 but the login is done through our Azure AD.

Before redirecting to Auth0's login page we set a "connection" parameter to the protocol message. This tells Auth0 to redirect to our Azure AD login page.

After upgrading to ASP.NET Core 2.0 (and upgrading Microsoft.AspNetCore.Authentication.OpenIdConnect from 1.1.2 to 2.0.0) the following code no longer works:

```
options.Events = new OpenIdConnectEvents
                    {
                        OnRedirectToIdentityProvider = context =>
                                                       {
                                                           if (context.Properties.Items.ContainsKey("connection"))
                                                               context.ProtocolMessage.SetParameter("connection", context.Properties.Items["connection"]);

                                                           return Task.FromResult(0);
                                                       },
....
}
```

context.Properties.Items does no longer contain "connection" resulting in failed logins over at Auth0.
If I manually set the connection protocol parameter then everything works fine.

Is there any way to get this information automatically in 2.0.0 or do I have to handle it manually from now on?

**Comment by Tratcher** [comment]
Can you show your code where you start the challenge for OIDC and set Properties.Items["connection"]? If you're using a simple `[Authorize]` you won't get the chance to set it properties.

**Comment by smatsson** [comment]
Hi @Tratcher ! 

Thanks for your reply. It got me in the right direction. Our challenge is initiated in our Login action in our Account controller. This action was never hit as we had set OpenIdConnect as the default scheme for authentication. Changing the default scheme to `CookieAuthenticationDefaults.AuthenticationScheme` fixed the issue.

Do you know if this is a common setup? It seems a bit weird to me.

**Comment by Tratcher** [comment]
That sounds fine. 
Does connection have a dynamic value? Why not hard code it in the redirect event rather than passing it from the login page?

**Comment by smatsson** [comment]
Cool thanks for the help. Connection is a constant value. Not really sure why it's done this way as I inherited the code base. I guess we could just remove the entire controller and use the new functionality in ASP.NET Core 2.0 for sign in/sign out instead.
