### ISSUE TITLE
Authorization in Middleware

### ISSUE THREAD

**Issue by user1336** [aspnet/Security#1514]
Imagine some Middleware setup like this and that you want to protect some other middleware from unauthorized users. 
```
.Configure(app =>
{
    app.UseSomeMiddleware);
    app.UseAuthorizationMiddleware();
    app.UseProtectedMiddleware();
})
```
In the `UseAuthorizationMiddleware` we inject the `IAuthorizationService` and `IAuthorizationPolicyProvider` and see if the Users matches the policy and return if that's not true:
```
var defaultPolicy = await _authorizationPolicyProvider.GetDefaultPolicyAsync();
var result = await _authorizationService.AuthorizeAsync(httpContext.User, defaultPolicy);
```
Basically we want to do the same thing in MVC with `[Authorize(Policy = "SomePolicy")]`

Is there a more convient way to do this in ASP.NET Core 2.0?

**Comment by Tratcher** [comment]
Directly calling the IAuthorizationService is the expected pattern for a middleware scenario like this.
