### ISSUE TITLE
WsFederationOptions.EventsType pattern unusable because WsFederationEvents class is missing virtual members.

### ISSUE THREAD

**Issue by lzandman** [aspnet/Security#1520]
I've placed my custom cookie authentication events inside a custom class that inherits from CookieAuthenticationEvents and specify that class using the EventsType property of CookieAuthenticationOptions as specified in [this Microsoft document](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?tabs=aspnetcore2x#reacting-to-back-end-changes).

I tried to apply the same pattern to the WsFederationEvents class, but noticed it doesn't contain any virtual members that I can override in my own custom class. It only inherits one overrideable virtual member, TicketReceived, from its base class RemoteAuthenticationEvents. So it seems this pattern isn't applicable and the WsFederationOptions.EventsType property mechanism cannot be used.

I'm using the latest nightly build of the WsFederation 2.0.0-preview1 package.

**Comment by PinpointTownes** [comment]
Actually, the missing virtual methods are not the only issue: `WsFederationHandler` directly uses `Options.Events`, which means the `EventsType` option is never used.

/cc @Tratcher
