### ISSUE TITLE
OpenIdConnectOptions validate exception

### ISSUE THREAD

**Issue by EricMKaufman** [aspnet/Security#1523]
Calling validate throws an exception even when Authority is provided:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L102

**Comment by Tratcher** [comment]
Please share your relevant Startup code and the full exception.

**Comment by EricMKaufman** [comment]
```
services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies;
                options.DefaultChallengeScheme = "oidc";
            })
            .AddCookie(SsoServiceConstants.AuthenticationSchemes.Cookies, options =>
            {
                options.CookieManager = new ChunkingCookieManager();
            })
            .AddOpenIdConnect("oidc", options =>
            {
                options.SignInScheme = "Cookies";

                options.Authority = configuration.BaseUrl;
                options.RequireHttpsMetadata = true;
                options.SaveTokens = true;
                options.ClientId = configuration.ClientId;
                options.ClientSecret = configuration.ClientSecret;
                options.ResponseType = "code id_token";
                options.GetClaimsFromUserInfoEndpoint = true;

                options.Validate();
            });
```

Looks like line 102 of OpenIdConnectOptions should be:
```
            if (ConfigurationManager == null || Authority == null || MetadataAddress == null)
            {
                throw new InvalidOperationException($"Provide {nameof(Authority)}, {nameof(MetadataAddress)}, "
                + $"{nameof(Configuration)}, or {nameof(ConfigurationManager)} to {nameof(OpenIdConnectOptions)}");
            }
```

**Comment by Tratcher** [comment]
Why do you use different values for `options.DefaultScheme = "Cookies;` and `.AddCookie(SsoServiceConstants.AuthenticationSchemes.Cookies`?

Also, are you sure configuration.BaseUrl has a value at runtime? Inspect it in the debugger or write it to the logs.

This code runs before Validate makes sure ConfiguraitonManager gets set if possible:
https://github.com/aspnet/Security/blob/bd8ecd02684d490ece96c484e1092386f3515dec/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectPostConfigureOptions.cs#L31

**Comment by EricMKaufman** [comment]
Sorry, I was replacing the constants with string literals and missed that one. The value is also "Cookies"
BaseUrl is set correctly. The exception I am receiving is:

> Provide Authority, MetadataAddress, Configuration, or ConfigurationManager to OpenIdConnectOptions

Perhaps I am not calling Validate() in the correct spot?

The code works fine authenticating with an OP (IDSRV4). I just noticed the exception when adding a call to Validate()

**Comment by Tratcher** [comment]
You should not be invoking Validate directly. The handler will call that when it reads the options.

**Comment by EricMKaufman** [comment]
Okay that clears it up. I thought maybe I could given the public access modifier. Thanks.

**Comment by HaoK** [comment]
There's nothing particularly wrong with calling Validate yourself, but it will fail if do it before PostConfigure runs if you are relying on some of the default inference logic that's built in.
