### ISSUE TITLE
OpenIDConnect error 500

### ISSUE THREAD

**Issue by samdzirasa** [aspnet/Security#1527]
I get this error after authenticating.
This page isn’t working

**localhost is currently unable to handle this request.
HTTP ERROR 500**

It seems to me the OpenIDConnect Middleware is not handling the the providers POST to "https://localhost:44359/signin-oidc"

I thought the middleware is supposed to handle this endpoint automatically.

I am using Microsoft.AspNetCore.Authentication.OpenIdConnect 2.0.0

![openidconnecterror](https://user-images.githubusercontent.com/25889211/32418467-85b76f10-c238-11e7-8258-31e80bc67c7a.png)

**Comment by Tratcher** [comment]
500 usually means an exception was thrown while processing the request. Run it under the debugger or enable logging to see the exception.
