### ISSUE TITLE
Custom absolute login redirect URL 

### ISSUE THREAD

**Issue by Glebby** [aspnet/Security#1529]
Is it possible to specify an absolute redirect login URL in ASP.NET Core 2? The standard method does not accept absolute URLs

```
        services.ConfigureApplicationCookie(x => {
            x.LoginPath = new PathString("https://localhost:88/account/login");
        });  
```

Produces a runtime error as the URL is expected to start with "/".

The initial problem is that my app service is served over HTTPS, which terminates at CloudFlare, so when user is not authorised, ASP.NET redirects the user to HTTP address, rather than to HTTPs.

**Comment by Tratcher** [comment]
Closing as a duplicate of https://github.com/aspnet/Docs/issues/2384.
