### ISSUE TITLE
Question: How to retrieve the reason for an Authorization Policy Failure?

### ISSUE THREAD

**Issue by Ponant** [aspnet/Security#1530]
.Net Core 2.0
Take https://github.com/blowdart/AspNetAuthorizationWorkshop/tree/core2
and consider the case where the user has claims, but no Administrator Claim, in which case he is redirected to the Forbidden View when he hits `[Authorize(Policy = "AdministratorOnly")]`
. Is there a way I can retrieve in the forbidden view (or elsewhere) the reason why he has been redirected, i.e.
"You do not satisfy the AdminsitratorOnly policy"
or even more precise in the case this policy has several requirements
"You are not an Admin". ?

**Comment by HaoK** [comment]
In 2.0, IAuthorizationService.Authorize was changed to return https://github.com/aspnet/Security/blob/rel/2.0.0/src/Microsoft.AspNetCore.Authorization/AuthorizationResult.cs instead of only a bool, when a failure occurs the Failure contains the failed requirements or if `Fail()` was called, but you will need to explicit authorization (use the service in the controller action manually) (as opposed to using [Authorize]) to look at the errors.

**Comment by HaoK** [comment]
cc @blowdart @scottaddie we should add this to the docs somewhere as this was a commonly asked for scenario that we enabled in 2.0

**Comment by Ponant** [comment]
.@Haok, do you have some code where I can check out explicit injection of the service with check ups for Fail etc?

**Comment by HaoK** [comment]
Sure you can look at https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?tabs=aspnetcore2x

I believe the docs for 2.0 are being updated still, the 2.0 PR is here: https://github.com/aspnet/Docs/pull/4715#discussion_r149468638

Right now there's no example code around using the new failures, but basically its up to you to generate the appropriate error message based on the failed requirements. So I'd imagine you could just write a helper method that generates the appropriate error message to display for a given list of failed requirements.

**Comment by Ponant** [comment]
I saw this page already but thought that was for resource based stuff, whereas you seem to say the `IAuthorizationService.Authorize` can be used beyond this .

**Comment by Eilon** [comment]
@HaoK per our discussion, can you add this to the discussion about auth improvements and then close this bug as a dup of it?

**Comment by HaoK** [comment]
Linked to #1359 and will be tracked as part of that
