### ISSUE TITLE
Web Api Bearer JWT Token Authentication with Api Key fails on successive calls after successful token authentication

### ISSUE THREAD

**Issue by flatproject** [aspnet/Security#1532]
I have posted my question on stackoverflow here [https://stackoverflow.com/questions/47168452/web-api-bearer-jwt-token-authentication-with-api-key-fails-on-successive-calls-a](url) and i would really appreciate it if someone could help me work out what the issue is. My question includes sample code for reproducing the issue. It is made up of two projects, one mvc core 2 web api and a console app.

The issue that i have is: 
I have created an MVC Core 2 Web Api that uses an API KEY to authenticate and on success it returns a JWT token to be used for any subsequent requests.
I can successfully call the token endpoint, validate my api key and get a JWT token back. Then i can successfully call a protected resource ([Authorize attribute]).
The problem starts when i want to make more than one call, one after the other. The first call will succeed but the subsequent calls will generate me this error message on the web api project:

`Bearer was not authenticated. Failure message: No SecurityTokenValidator available for token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyNmFiNjQzYjFjOTM0MzYwYjI4NDAxMzZjNDIxOTBlZSIsImlhdCI6MTUxMDA2NDg0MywiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxIiwiR2xvYmFsSWQiOiI2NjVjYWEzYjYxYmY0MWRmOGIzMTVhODY5YzQzMmJkYyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmF0b3IiLCJuYmYiOjE1MTAwNjQ4NDMsImV4cCI6MTUxMDA2NjY0MywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0NDM2MCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDQzNjAifQ.wJ86Ut2dmbDRDCNXU2kWXeQ1pQGkiVtUx7oSyJIZMzc`

I have spent too much time trying to fix this issue but i cannot understand what fails, which part of the jwt token validation fails. I would have expected some sort of console message in the Output window to tell me 'it failed because such and such'. All i get back from the www-authenticate header is "invalid_token" but both calls i'm making are using exactly the same token.

If you require any more information from me or you want me to copy the code from stackoverflow in this thread please let me know.

**Comment by Tratcher** [comment]
I don't see anything obvious. Here are a few things to try:
a) Use the same token for Get() and GetAll()
b) Share a Fiddler trace of the full repro so we can compare the requests
c) Share the full repro as a github repo so it's easy to clone and debug

**Comment by Tratcher** [comment]
I don't see anything obvious. Here are a few things to try:
a) Use the same token for Get() and GetAll()
b) Share a Fiddler trace of the full repro so we can compare the requests
c) Share the full repro as a github repo so it's easy to clone and debug

**Comment by flatproject** [comment]
@Tratcher Thanks for coming back to me.
a) I'm already storing the token for reuse instead of generating a new one in the method
> GetAuthenticationToken()

b) I'm really struggling to get this trace. Fiddler doesn't seem to capture anything. I will try a few more times and see if i can get it.
c) done. Its here: [https://github.com/flatproject/1532](url)

Again thanks for your help.

**Comment by flatproject** [comment]
I have resolved the issue. Apologies for any time wasted. The issue was that `TryAddWithoutValidation("Authorization", $"Bearer {token}");` doesn't clear the header before adding the new one. As a result when you call methods in success it keeps adding the bearer token in the header ending up with more than one value e.g. `Bearer xyz Bearer xyz`
