### ISSUE TITLE
Not working Roles 

### ISSUE THREAD

**Issue by KANekT** [aspnet/Security#1534]
I reed https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles
But if i use 2 roles anf more - not working 
`[Authorize(Roles = AuthConstants.Realtor)]`
`[Authorize(Roles = AuthConstants.Administrator)]`
`[Authorize(Roles = AuthConstants.Agency)]`
`[Authorize(Roles = AuthConstants.CentralAgency)]`
`[Authorize(Roles = AuthConstants.Developer)]`

working only `[Authorize(Roles = "Administrator,Agency,CentralAgency,Developer,Realtor")]`

i use net core 2.0

**Comment by Eilon** [comment]
Hi @KANekT , the docs do specify that if you specify multiple `Authorize` attributes it is an "AND" operation, but if you specify multiple roles within a single attribute it is an "OR" operation.
