### ISSUE TITLE
Question: Why so many cookies created?

### ISSUE THREAD

**Issue by mjnorman** [aspnet/Security#1536]
Using openid authentication + cookies, I see a total of 5 cookies created.  Is that normal and what is the use for each?

```
services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;

            })

            .AddCookie()
            .AddOpenIdConnect(options =>
            {
           ........
```

.AspNetCore.Antiforgery.0XStZnTEh0M
.AspNetCore.Cookies
.AspNetCore.CookiesC1
.AspNetCore.CookiesC2
.AspNetCore.CookiesC3

**Comment by Tratcher** [comment]
The C1, C2, etc... cookies are what we call cookie chunks. When your primary cookie (.AspNetCore.Cookies) gets larger than 4kb some browsers may not accept it. We work around that by slicing it up into 4kb chunks and adding numbering the pieces C1, C2, etc..

Usually this means you have too many claims in your identity, most commonly role claims. Enumerate your claims and see what's taking up all of that space. SaveTokens can also contribute to this.

**Comment by mjnorman** [comment]
Thanks for the reply, yes I have a lot of bloat right now, but did not occur to me it would split it up into separate cookies.  Makers perfect sense, thanks!

**Comment by mum6ojum6o** [comment]
Could you suggest in this case, how can we decrypt the cookie chunks?
