### ISSUE TITLE
[Authorize] [Antiforgery] and SPA

### ISSUE THREAD

**Issue by patsadow2** [aspnet/Security#1537]
Hello,

Is there any good solution to make [Authorize] [Antiforgery] and SPA work together ?

There is a bunch of article and people with that error:
" the provided anti-forgery token was meant for a different claims-based user than the current user"

Could anyone from .net support could tell how to do it correctly ?

BR

**Comment by Eilon** [comment]
@patsadow2 can you show more info about your scenarios? Does your app redirect to a plain HTML page after logging in?

**Comment by patsadow2** [comment]
I use

 ```
app.UseAuthentication();
app.Use(next => context =>
{
    var tokens = antiforgery.GetAndStoreTokens(context);
    context.Response.Cookies.Append("X-XSRF-TOKEN", tokens.RequestToken, new CookieOptions() { HttpOnly = false, SameSite = SameSiteMode.Strict });
});
```

And after login the first request in redirected page doesn't replay correctly. After redirect to another page it validate it.
