### ISSUE TITLE
SignInManager.IsSignedIn(User) == false, yet User.Identity.IsAuthenticated == true

### ISSUE THREAD

**Issue by ghstahl** [aspnet/Security#1538]
https://github.com/ghstahl/P7.Core-2.0/blob/master/src/A.OIDC/Startup.cs

I would like to have an example that shows how to get OIDC tokens using the following method;
```
if (User.Identity.IsAuthenticated)
{
  string accessToken = await HttpContext.GetTokenAsync("access_token");
}
```
When I do the following, I can log in, the user gets authenticated, and I can get the access_tokens when logging in to Google using OpenIdConnect.  However, then calling  SignInManager.IsSignedIn(User) == false.
When I play around with other options, I can get my SignInManager.IsSignedIn(User) == true, but then I cant get my access_tokens. 

**Why is SignInManager.IsSignedIn(User) == false in this case?**
 
1. Out of the box asp.net core 2 webapp with user accounts.
2. Upgrade to 2.0.1
3. Add OpenIdConnect as follows, where I changed only the following in the original starter app;
```
 var authenticationBuilder = services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            }).AddCookie();
            var configuration = Configuration;

            if (!(string.IsNullOrEmpty(configuration["Google-ClientId"]) ||
                  string.IsNullOrEmpty(configuration["Google-ClientSecret"])))
            {
                authenticationBuilder.AddOpenIdConnect(GoogleDefaults.AuthenticationScheme, GoogleDefaults.DisplayName,
                    o =>
                    {
                     
                        o.CallbackPath = new PathString("/signin-google"); 

                        o.ClientId = configuration["Google-ClientId"];
                        o.ClientSecret = configuration["Google-ClientSecret"];

                        o.Authority = "https://accounts.google.com";
                        o.ResponseType = OpenIdConnectResponseType.Code;
                        o.GetClaimsFromUserInfoEndpoint = true;
                        o.SaveTokens = true;

                        o.Events = new OpenIdConnectEvents()
                        {
                            OnTicketReceived = (context) =>
                            {
                                ClaimsIdentity identity = (ClaimsIdentity)context.Principal.Identity;
                                return Task.CompletedTask;

                            }
                        };

                    });
            }
```

**Comment by dallancarr** [comment]
Check your auth flow maybe.

https://github.com/aspnet/Identity/issues/1452

**Comment by Tratcher** [comment]
SignInManager is part of the Identity framework. The configuration you're showing is now using the Identity framework, it's only using the Authentication components.

**Comment by HaoK** [comment]
Yeah, SignInManager is looking specifically for the identity application cookie, you only want to use that method if you are using SignInManager to sign in typically.

**Comment by brockallen** [comment]
> SignInManager is part of the Identity framework. The configuration you're showing is not using the Identity framework, it's only using the Authentication components.

I think this is the first time I've ever heard anyone at Microsoft delineate the two. It's refreshing :)

But seriously, the docs don't make this distinction -- perhaps that leads to this type of confusion.

**Comment by ghstahl** [comment]
@Haok,
So if I do this, I should trash all the SignInManager stuff and just use User.Identity.IsAuthenticated for decisions in _LoginPartial.cshtml.   That cshtml file is where I first saw that it didn't show I was logged in.

Saying that, what do I do if I want Identity and still want those access tokens.  I stepped the OpenIdConnect handler and it was definitely saving the Tokens in that AuthTicket.  SigninManager.IsSignedIn worked, but calling HttpContext.GetTokenAsync("access_tokens") failed.  

I really want Identity and those access_tokens too.

**Comment by ghstahl** [comment]
@dallancarr 
` string accessToken = await HttpContext.GetTokenAsync(IdentityConstants.ExternalScheme,"access_token");`
doesn't work for me, when I changed my config to the following; 
```
            var authenticationBuilder = services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme;
                options.DefaultChallengeScheme = IdentityConstants.ApplicationScheme;
                options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
            });
```
Now SigninManager.IsSignedIn == true.

**Comment by dallancarr** [comment]
You need swap out your defaults...mixture of oidc and cookies should do it. Then the token get should work without specifying scheme.

**Comment by ghstahl** [comment]
@dallancarr 
I am using asp.net core 2.0.1, which doesn't have AddCookieAuthentication().  I used .AddCookie().  I got the same result though, where I get the access_token but SignInManager.IsSignedIn is still false.  

Can you guys to tell me if I am wrong?
I decided to manage the OIDC tokens myself where I harvested them from the OnTicketReceived, and stuffed them into the session.

here is my code snippets;
```
 var authenticationBuilder = services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme;
                options.DefaultChallengeScheme = IdentityConstants.ApplicationScheme;
                options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
            });
```
so no Cookie stuff.

And writing the OIDC stuff into the session OnTicketReceived;
```
 authenticationBuilder.AddOpenIdConnect(GoogleDefaults.AuthenticationScheme, GoogleDefaults.DisplayName,
                    o =>
                    {
                        var openIdConnectOptions = new GoogleOpenIdConnectOptions();
                        o.CallbackPath = openIdConnectOptions.CallbackPath;

                        o.ClientId = configuration["Google-ClientId"];
                        o.ClientSecret = configuration["Google-ClientSecret"];

                        o.Authority = openIdConnectOptions.Authority;
                        o.ResponseType = openIdConnectOptions.ResponseType;
                        o.GetClaimsFromUserInfoEndpoint = openIdConnectOptions.GetClaimsFromUserInfoEndpoint;
                        o.SaveTokens = openIdConnectOptions.SaveTokens;

                        o.Events = new OpenIdConnectEvents()
                        {
                            OnRedirectToIdentityProvider = (context) =>
                            {
                                if (context.Request.Path != "/Account/ExternalLogin"
                                    && context.Request.Path != "/Account/ExternalLoginWhatIf"
                                    && context.Request.Path != "/Manage/LinkLogin")
                                {
                                    context.Response.Redirect("/account/login");
                                    context.HandleResponse();
                                }

                                return Task.FromResult(0);
                            },
                            OnTicketReceived = (context) =>
                            {
                                ISession Session = context.HttpContext.Session;
                                var query1 = from item in context.Properties.Items
                                    where item.Key.StartsWith(".Token.")
                                    select item;
                                var query2 = from item in context.Properties.Items
                                    where !item.Key.StartsWith(".Token.")
                                    select item;
                                var ap = new AuthenticationProperties();
                                foreach (var a in query2.Where(a => a.Key != ".TokenNames"))
                                {
                                    ap.Items.Add(a.Key, a.Value);
                                }
                                context.Properties = ap;
                                var oidc = new Dictionary<string, string>();
                                foreach (var a in query1)
                                {
                                    var keys = a.Key.Split('.');
                                    oidc.Add(keys[2], a.Value);
                                }
                                Session.SetObject(".oidc", oidc);

                                ClaimsIdentity identity = (ClaimsIdentity)context.Principal.Identity;
                                var query = from claim in context.Principal.Claims
                                    where claim.Type == ClaimTypes.Name || claim.Type == "name"
                                    select claim;
                                var nameClaim = query.FirstOrDefault();
                                var nameIdentifier = identity.FindFirst(ClaimTypes.NameIdentifier);


                                var claimsToKeep =
                                    new List<Claim>
                                    {
                                        nameClaim,
                                        nameIdentifier,
                                        new Claim("DisplayName", nameClaim.Value),
                                        new Claim("UserId", nameIdentifier.Value)
                                    };

                                var newIdentity = new ClaimsIdentity(claimsToKeep, identity.AuthenticationType);

                                context.Principal = new ClaimsPrincipal(newIdentity);
                                return Task.CompletedTask;

                            }
                        };

                    });
```

**Comment by dallancarr** [comment]
It looks like your using third party google so Identity + Google is an option.

**Comment by ghstahl** [comment]
@dallancarr I am using google as a placeholder for other OpenIdProviders.  I have always had Identity + a bunch of external OIDC providers, but then all of a sudden there was a need to get a hold of those tokens.  As it is, it looks like when I configure "SaveTokens", the only thing that does for me is allow me to harvest them via OnTicketReceived.  I was hoping to use what the asp.net team provided, HttpContext.GetTokenAsync("access_token").  At the moment it doesn't look like I can have Identity and use HttpContext.GetTokenAsync("access_token"), hence my harvesting technique.  Let me know if I am missing something that lets me still use Identity and HttpContext.GetTokenAsync("access_token").

**Comment by HaoK** [comment]
@ghstahl so this is a fairly common ask, where you want to get something on the external identity (which lives in the "Identity.External" cookie, which gets cleared out when the "Identity.Application" cookie is signed in.  

https://github.com/aspnet/Identity/issues/628 is a similar issue which you can read for context.

But the gist of it is, you will need to harvest the token via HttpContext.GetTokenAsync(IdentityConstants.ExternalScheme , "access_token") on the externallogin callback action request, since after that request the external cookie (and token) will get cleared.  You just need to take that token and store it somewhere you will have access to on subsequent requests (you could store it in the user claims (`userManager.AddClaimAsync`) which would show up in the normal identity application cookie for example)

**Comment by Eilon** [comment]
We logged https://github.com/aspnet/AuthSamples/issues/6 to track creating a sample for this.

**Comment by ghstahl** [comment]
@HaoK  As usual it always turns out to be the most simple thing.  Verified your gist of it.

I get to keep my Identity.
```
var authenticationBuilder = services.AddAuthentication(options =>
{
  options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme;
  options.DefaultChallengeScheme = IdentityConstants.ApplicationScheme;
  options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
});
```
And harvest the tokens before they get cleared out after signin.,
```
 [HttpGet]
 [AllowAnonymous]
 public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
 {
  var at = await HttpContext.GetTokenAsync(IdentityConstants.ExternalScheme, "access_token");
  var idt = await HttpContext.GetTokenAsync(IdentityConstants.ExternalScheme, "id_token");
  var rt = await HttpContext.GetTokenAsync(IdentityConstants.ExternalScheme, "refresh_token");
  var tt = await HttpContext.GetTokenAsync(IdentityConstants.ExternalScheme, "token_type");
  var ea = await HttpContext.GetTokenAsync(IdentityConstants.ExternalScheme, "expires_at");
  // put this data into the session, or
 // add them as a user claim
 ...
 }
```

Thanks
