### ISSUE TITLE
Cookie auth doesn't work with an app running on root (localhost:xxx/) and subfolder (localhost/app) at the same time

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Security#1539]
I have an aspnetcore app with cookie auth. 
Registered like:
```
            services.AddAuthentication("myscheme")
                .AddCookie("myscheme", options =>
                {
                    options.Cookie.Name = "X_AUTH";
                    options.Cookie.HttpOnly = true;
                    options.ExpireTimeSpan = TimeSpan.FromMinutes(60);
                    options.SlidingExpiration = true;
                });
```
Then `app.UseAuthentication();` in `Startup.Configure`.
It works fine both when I run from VS with F5 (on localhost:40386) and under IIS (publish to a folder registered as app in IIS).

But. If I first run the app on localhost:40386 (from VS), authenticate in it (get a cookie) and then do the same in app under IIS I'll get another cookie for IIS's path:
![image](https://user-images.githubusercontent.com/1203230/32891427-8807b15e-cae3-11e7-8b12-790229e051e9.png)

The problem is that that with these two cookies I can't authenticate any more.
After "Login" endpoint created a AUTH cookie and client sends some request in Request.User I have empty (unauthorized) Principal. As it wouldn't be a cookie at all. 
I guess Auth module tried to read the cookie for root "/" which was created in other app and fails.

I tried set `options.Cookie.Path = "/survey.netcore.deploy"` with no effect (anyway it isn't an option as it's impossible to detect IIS app name in Startup).

**Comment by Tratcher** [comment]
Can you share a Fiddler trace with all three requests? The two that created the cookies and the third that be authenticated.

**Comment by evil-shrike** [comment]
@Tratcher are HARs from DevTools ok? 

[dotnet-cookieauth-issue-1539.zip](https://github.com/aspnet/Security/files/1478920/dotnet-cookieauth-issue-1539.zip)
* app on localhost:40386/ :
localhost-root-1-login.har - login api 
localhost-root-2-confirm.har - 2nd phase of 2F-auth - actually returns a cookie (for "/" path)
localhost-root-3-api-authenticated.har - successfully accessing an api-controller with the cookie

* app on localhost/survey.netcore.deploy/ :
localhost-iis-1-login.har - login api
localhost-iis-2-confirm.har - 2nd phase of 2F-auth - actually returns a cookie (for "/survey.netcore.deploy" path)
localhost-iis-3-api-unauthenticated.har - accessing an api-controller results 401 (as w/o cookies)

**Comment by Eilon** [comment]
We suspect this might be because the same cookie name(s) are used between the two sites, and ASP.NET Core can't know which of the two cookies to use.

If that's the case, we recommend adjusting the cookie name to be specific for each site.

**Comment by evil-shrike** [comment]
I believe it should use the one which has most relevant path ("/survey.netcore.deploy" in my case) and only then try root's cookie...

**Comment by Tratcher** [comment]
The path information is not present in the request cookie, only the browser maintains that.

**Comment by Eilon** [comment]
Right, the path info is just an instruction to the browser client to know when to send the cookie, and when not to. It's not part of the cookie itself.

**Comment by evil-shrike** [comment]
I see. Could you tell me why cookies from root isn't suitable for path-based app? Is there some unique identification used during encoding cookie value which prevents from reusing cookies from other app instances?

**Comment by Eilon** [comment]
There are two "requirements" to get this to work:
1. Make sure there is only one cookie. ASP.NET Core does not support having two cookies for the same purpose.
2. Make sure that both apps share the same configuration for Data Protection, or otherwise one app won't be able to see/verify data from the other app. You can learn more about this in the docs: https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x#per-application-isolation
