### ISSUE TITLE
Revisit AuthN (switch to AuthenticationScheme/ClaimsPrincipal)

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#154]
Summary of plan:
- AuthenticationType will be renamed AuthenticationScheme which represents a particular authentication middleware.
- Auth Middleware will now produce a ClaimsPrincipal instead of a ClaimsIdentity with authentication type set
- Active/Passive removed from base auth middlware and opt in functionality pushed into a new base class dervied from AuthMiddleware that has an Automatic = true|false, Cookie(true by default)/Bearer(false by default) will opt in.  Concept is removed from all social middlewares (always passive)

**Comment by leastprivilege** [comment]
Why the move to ClaimsPrincipal? What about multiple authN middlewares - e.g. cookies and client certificates?

**Comment by HaoK** [comment]
The behavior is going to be pretty similar as today for multiple authN middlewares, each one generates a ClaimsPrincipal, and at the end, HttpContext.User will be the aggregate of all of the authN principals

The big change is to allow Auth middlewares to produce more than one ClaimsIdentity and leave the authenticationType on the identities untouched, authenticationScheme will be how you refer to a specific auth middleware, instead of authenticationType like before.

cc @blowdart @Tratcher @lodejard

**Comment by leastprivilege** [comment]
So the claims transformation will see a list of ClaimsPrincipal and be able to normalize to one?

sounds good.

**Comment by lodejard** [comment]
Yeah, key difference will be the `identity.AuthenticationType` strings must no longer be used to determine which authn mechanism delivered the identity to the current request. Those AT strings will now be considered arbitrary data, serialized back and forth with the cookie, bearer token, etc. 


A new string named AuthenticationScheme will be used to associate a set of identities with the-way-they-arrived.

So like Hao said, in a nutshell, a cookie or bearer token will be able to contain multiple identities, and the identities' AuthenticationType may be assigned to be any value.

**Comment by PinpointTownes** [comment]
> Concept is removed from all social middlewares (always passive)

So we won't be able to automatically redirect users to an IDP without relying on an explicit `Challenge`? This was particularly useful on applications using a single external provider (now, we'll need a controller or a middleware to trigger the challenge stuff).

> A new string named AuthenticationScheme will be used to associate a set of identities with the-way-they-arrived.

Is it going to be included as a claim?

**Comment by HaoK** [comment]
Merged 775eb5ece452e10a27aa166f52b58a6c0b615d18

**Comment by PinpointTownes** [comment]
The fact social/OIDC/WS-Fed authentication middleware can't now be configured in active mode (or automatic, according to the newest terminology) is a bit annoying and make things more complicated when you only need to support a single external provider, because you now need to add a middleware/controller to handle the challenge part and explicitly call `HttpResponse.Challenge`.

I do think that changing the name of the passive/active concept was a good idea, but I'm not sure that the new `AutomaticAuthenticationHandler` makes things easier.
