### ISSUE TITLE
JwtBearerEvents -> TokenValidated method

### ISSUE THREAD

**Issue by krishnasingh1818** [aspnet/Security#1543]
Hi,

am overriding TokenValidated Method for JwtBearerEvents class to check value of a specific claim and if that value is false i want to return 401 status code with some error message to user "authentication failed"

right now am doing 
context.Response.StatusCode = 401;

but this does not terminate the request and it allows execution to flow till controller methods and results are returned.  

if i add below code then execution terminates and but user gets status code 500 with exception stack trace. 
context.Response.StatusCode = 401;
throw new SecurityTokenValidationException("Authentication failed : Legal disclaimer not accepted.");

I want to abort request processing and return status code 401..  please advise.

**Comment by HaoK** [comment]
Try calling context.Fail("authentication failed") after setting it to 401.

**Comment by krishnasingh1818** [comment]
I don't see fail method on context.. looks like in core 2..  I have core
1.1..  thks

On Nov 16, 2017 3:36 PM, "Hao Kung" <notifications@github.com> wrote:

Try calling context.Fail("authentication failed") after setting it to 401.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aspnet/Security/issues/1543#issuecomment-345070476>,
or mute
the thread

**Comment by HaoK** [comment]
In 1.1, you can call context.HandleResponse()

**Comment by krishnasingh1818** [comment]
context.HandleResponse() allows request to go till controller and returns actual results from api call..  thats why for now i had to throw exception to stop execution ..

**Comment by krishnasingh1818** [comment]
if i do context.SkipToNextMiddleware(); then it worked fine.
but if i do  below. it sends status as 401 and also sends api result (customerList)
context.Response.StatusCode = 401;
context.HandleResponse();

**Comment by Tratcher** [comment]
That's strange.
This might be easier to get working if you separate your authentication from your authorization. The JwtBearer does authentication and produces a user, it's not usually responsible for doing authorization and deciding if that user has access to your site.

Try adding a separate middleware for authorization that calls HttpContext.Authentication.AuthenticateAsync, checks the desired claims, and returns 401 or calls next. Something like this:
```
app.Use(async (context, next) =>
{
  var user = await context.Authentication.AuthenticateAsync(JwtBearerDefaults.AuthenticationScheme);

  if (UserIsAuthorized(user))
  {
    await next();
  }
  else
  {
    context.Response.StatusCode = 401;
  }
});
```
