### ISSUE TITLE
How do I add a custom claim value to be part of cookie ?

### ISSUE THREAD

**Issue by kuseku** [aspnet/Security#1545]
I am using **Microsoft.AspNetCore.Authentication.MicrosoftAccount** and it works great. Question I have is as a part of Cookie values I would like to add some values from the database regarding user. This is to avoid querying DB every-time page loads. In earlier versions I would keep the redirect URL to a Action method and perform this operation. I dint see any examples of how I can do this in ASP.NET 2.0 when using Microsoft Account.

**Comment by Tratcher** [comment]
You can do this in the OnTicketReceived event.
https://github.com/aspnet/Security/blob/34083584a6593b636ed507c1b8e50570197ec2ad/src/Microsoft.AspNetCore.Authentication/Events/RemoteAuthenticationEvents.cs#L13
See this for hooking events:
https://github.com/aspnet/Security/blob/34083584a6593b636ed507c1b8e50570197ec2ad/samples/SocialSample/Startup.cs#L153
