### ISSUE TITLE
[Question] Authentication V2 - How to specify a proxy settings for the BackchannelHttpHandler for development environment only ?

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Security#1547]
I have to specify a proxy settings on the BackchannelHttpHandler, but only on the development environment. 
Is there any way to achieve this? Or should I set a configuration flag like `enableProxy`?

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication("oidc")
                .AddCookie()
                .AddOpenIdConnect("oidc", options =>
                {
                  if (env.IsDevelopment()) // <= Not possible !
                  {
                    var proxy = new WebProxy("http://my-proxy")
                    {
                        Credentials = CredentialCache.DefaultNetworkCredentials
                    };
                    options.BackchannelHttpHandler = new HttpClientHandler() { Proxy = proxy };
                    // Other OIDC configuration...
                  }
                });
        }
```

**Comment by Tratcher** [comment]
That's doable, you can inject IHostingEnvironment into the Startup constructor and store it in a field/property.

**Comment by ycrumeyrolle** [comment]
That's working like a charm. 
I tried to inject the `IHostingEnvironment` into the `ConfigureServices()` method, I did not think about the `Startup` constructor.

**Comment by ycrumeyrolle** [comment]
Any reason for having a `Configure()`  method & `Startup` constructor supporting dynamic IoC and a `ConfigureServices()` method that does not?

**Comment by Tratcher** [comment]
Complexity, and the constructor has access to all of the same services. Configure is different because it needs access to the services added in ConfigureServices.
