### ISSUE TITLE
TestServer and OIDC/MSAL

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1548]
_From @dmcweeney on November 15, 2017 15:39_

Hi,

I've an ASP.Net Core 2 web app/api that is protected using OIDC and MSAL.

For our unit and functional tests, I want to be able to test the routing, model binding, etc 
using the TestServer class. 

Any ideas on the best way to bypass the authentication layer for this kind of testing?

Thanks

Donal

_Copied from original issue: aspnet/Hosting#1271_

**Comment by dallancarr** [comment]
Subclass startup is one solution ive seen out there. At least you can overrride the bits you need. But im not a real advocate of that.

**Comment by Eilon** [comment]
@javiercn I believe you have examples of exactly how to do this. Can you give a pointer?

**Comment by javiercn** [comment]
Subclassing Startup and using that to change the dependencies used for testing is a good start. You can change your auth to use a very simple handler that just looks at the Authorization header and set a principal based on that.

Then you can just put that payload on the HTTP request you make using HTTP Client.

**Comment by brockallen** [comment]
Here's how we do it: https://github.com/IdentityServer/IdentityServer4/blob/dev/test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs#L188

**Comment by dmcweeney** [comment]
Guys thanks for the info and pointer to the sample code. Its a good base to start working off.

Thanks again

Donal
