### ISSUE TITLE
TokenValidated question

### ISSUE THREAD

**Issue by dmcweeney** [aspnet/Security#1551]
Hi,

We have an asp.net core 2 web app/api which uses oidc and msal.

I've implemented a whitelist/blacklist and this checking is done in the TokenValidated event. If the user fails the access checks I throw a SecurityTokenValidationException().
Which results in my forbidden page being rendered to the client.
That is ok but if I hit the endpoint again from the same browser instance there is no login prompt and the user gets redirected back to the forbidden page. I would like that they are presented with a login prompt again. How would I go about doing this? Or is it possible?

Also is throwing a SecurityTokenValidationException in the TokenValidated event the correct way to block out a user? And is there a further level of granularity I can get as regards the forbidden view that is returned to the client.

Thanks

Donal

**Comment by Tratcher** [comment]
You're mixing Authentication and Authorization. @HaoK @blowdart where are the Authorization samples for something like a user filter?

**Comment by blowdart** [comment]
I don't think we have any, and, honestly, hitting an api in browser is *odd*. We're back to, presumably, wanting two methods of auth on an endpoint, jwt and cookie, and that's never a good idea.

@dmcweeney what authentication are you using here?

**Comment by dmcweeney** [comment]
Hi @blowdart, @Tratcher, we are authenticating using the AzureAD V2 endpoint.

I should have clarified the "asp.net core 2 web app/api" as it is a SPA that talks back to its own WebAPI. The idea of putting the whitelist/blacklist check in the TokenValidated event is I don not even want to spool the SPA if user does not pass that authorization check.

The idea of putting the check in TokenValidated event came from Vittorio's book "Modern Authentication with Azure AD for Web Applications", but this space is evolving so fast I thought I'd ask the question.

**Comment by Tratcher** [comment]
You still don't need to mix it in with the Authentication code. A second middleware for authorization would suite you. Something like:
```
app.UseAuthentication();
app.Use(async (context, next) =>
{
  var authResult = await context.AuthenticateAsync();
  if (authResult.Succeeded && UserIsAllowedAccess(authResult))
  {
    await next();
  }
  else
  {
    context.Response.StatusCode = 403;
  }
});
```

**Comment by dmcweeney** [comment]
I do agree with you guys on mixing authentication and authorization code being a bad idea and I will definitely play with this. 
However if I am to understand this correctly this whitelist/blacklist checking middleware will run for every request for users that pass this check?

Thanks

Donal

**Comment by Tratcher** [comment]
Yes this approach will run for every request. If you're using JwtBearer then the validation is always per-request.

**Comment by dmcweeney** [comment]
Ok thanks...
