### ISSUE TITLE
options.ClientId options.ClientSecret Configuration information I want to run in the process of assignment how to achieve?

### ISSUE THREAD

**Issue by qibucloud** [aspnet/Security#1553]
```
services.AddAuthentication()
.AddWeixinAuthentication(options =>
{
options.ClientId = "[you app id]";
options.ClientSecret = "[you app secret]";
});
```
options.ClientId options.ClientSecret    Configuration information I want to run in the process of assignment how to achieve?
I tried a lot of ways does not work, I do not know how to get, can help me think about it?

**Comment by Tratcher** [comment]
Sorry, I don't understand the question. Try rephrasing it.

**Comment by qibucloud** [comment]
I saas application, different site configuration is not the same, I do not know how to configure @Tratcher

**Comment by Tratcher** [comment]
For your SAAS application do you deploy separate instances for each customer? If so then then the customer specific information should be read from Configuration like in this sample:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?tabs=aspnetcore2x#configure-facebook-authentication

If you're running multiple customers in one instance and want to select the configuration per request then it gets more difficult.

**Comment by Eilon** [comment]
@HaoK , I believe you are working on a sample that shows how to do multi-tenancy of auth configuration (that is, different settings used for different requests, based on tenants).

**Comment by HaoK** [comment]
See https://github.com/aspnet/AuthSamples/tree/dev/samples/DynamicSchemes which updates options dynamically, specifically you can look at https://github.com/aspnet/AuthSamples/blob/dev/samples/DynamicSchemes/Controllers/AuthController.cs#L28
