### ISSUE TITLE
Infinite Loopback between asp.net core 2.0 controller and login.microsoft.com inside office addins

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1554]
_From @Petermarcu on November 27, 2017 4:46_

@vskeid opened this here: https://github.com/dotnet/core/issues/1075

hi,
    We have migrated our application to asp.net core 2.0  from 1.1.   Before migration the application used to work in the browser and within word office 365 app task pane.

After asp.net core 2.0 migration the oidc flow and the cookie authentication is working fine in chrome and IE,  but it is failing with infinite loop back between login.microsoft.com and the controller.   Seems that cookie is not being set or being deleted inside office app.

 

                        //Cookies is responsible for two things:
                        //Signing the user in (creating the authentication cookie and returning it to the browser)
                        //Authenticating cookies in requests and creating user principals from them
                  
                        //Open Id Connect is responsible for Responding to challenges from[Authorize] or ChallengeResult returned from controllers.

                       
                        services.AddAuthentication(auth => {

                            auth.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                            auth.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                            auth.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                            auth.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                        })
                       
                             .AddCookie(options =>
                             {
                                 options.Cookie.SameSite = SameSiteMode.Lax;
                                 options.Cookie.HttpOnly = false; //// If True - Javascript will not be able to read cookie.
                                                                  // options.Cookie.SameSite = SameSiteMode.Lax;
                                 options.Cookie.SecurePolicy = CookieSecurePolicy.Always; // Supports only HTTPS
                                 options.SlidingExpiration = config.AzureAD.AllowCookieSlidingExpiration;
                                 options.ExpireTimeSpan =  TimeSpan.FromMinutes(config.AzureAD.CookieExpireTimeSpanInMinutes);

                                 //options.Events = new CDNGCookieAuthenticationEvents();
           
                             })
                            .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, "AAD",options => {
                                options.ClientId = config.AzureAD.ClientId;
                                options.ClientSecret = config.AzureAD.ClientSecret;
                                options.Authority = config.AzureAD.CommonAuthority;
                                options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;

                                options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
                                
                                options.CallbackPath = config.AzureAD.CallBackURL;

                                
                                // GetClaimsFromUserInfoEndpoint = true;
                                options.UseTokenLifetime = false; // if Set to true, id Token expiration will not be used  but auth token (managed by ad) expiration will be used. 
                                                                  // This can create logouts after  one hour since access token is valid only for an hr.
                                                                  // If set to false, cookie expiration will be used using sliding expiration

                                options.TokenValidationParameters = new TokenValidationParameters
                                {
                                    // Instead of using the default validation (validating against
                                    // a single issuer value, as we do in line of business apps), 
                                    // we inject our own multitenant validation logic
                                    ValidateIssuer = true,
                                    ValidateAudience = true,

                                    NameClaimType = "name"
                                };

                                options.SaveTokens = false; // No need to save Access Token in Cookie

                                options.Events = new WebAppOIDCEvents(config);
                                // adding here since scope is read, but scope.add allows set
                                options.Scope.Add(OIDCScope.OpenID);
                                options.Scope.Add(OIDCScope.Profile);
                                options.Scope.Add(OIDCScope.Offline_Access);

Thanks
Suresh

_Copied from original issue: aspnet/Home#2287_

**Comment by Tratcher** [comment]
Can you share a Fiddler trace of the infinite loop?

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.

**Comment by rchowe** [comment]
I've been having the same problem.

I was able to do a Fiddler trace, though it's my first time using Fiddler. Notably, when the user clicks on our O365 login button, triggering AccountController#ExternalLogin (which is close to the same code as the default AccountController) the login works fine, but when they click on something that redirects to a path with an `[Authorize]` attribute, the auto-login kicks them back and forth to the microsoftonline login page and our `/signin-oidc-mycompany` path.

Thanks!

----

[Fiddler_Trace.txt](https://github.com/aspnet/Security/files/1543227/Fiddler_Trace.txt)

I did the following replacements on the Fiddler output:

- I replaced our Office 365 tenant ID with XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
- I replaced our Azure AD client ID with YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY
- I replaced references to our website with example.test or app.example.test.
- I replaced references to our company's name with MyCompany
- I did a few other snips for privacy.

**Comment by Eilon** [comment]
@Tratcher any ideas?

**Comment by Tratcher** [comment]
@rchowe can you also share your startup code? The presence of the Identity.External cookie without a login page is suspicious.

**Comment by Tratcher** [comment]
[Authorize] returns users to the initial page when the base flow is complete, but if you're using Identity then you need to return to a specific endpoint and exchange the External cookie for an App cookie. Your login button likely sets a specific callback path?

**Comment by rchowe** [comment]
Here's the contents of `ConfigureServices`:

```
if ( _useInMemoryDatabase )
{
    var sp = new ServiceCollection().AddEntityFrameworkInMemoryDatabase().BuildServiceProvider();
    services.AddDbContext<ApplicationDbContext>(options =>
        options
            .UseInMemoryDatabase("MyCompany.App")
            .UseInternalServiceProvider(sp));
}
else
{
    // Add Entity Framework services to the services container.
    if ( string.IsNullOrWhiteSpace(Configuration["Data:DefaultConnection:ConnectionString"]) )
        throw new Exception("Data:DefaultConnection:ConnectionString is null.");

    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"],
        builder => builder.CommandTimeout(60)));
}

services.AddMemoryCache();

// Add Identity services to the services container.
services.AddIdentity<ApplicationUser, IdentityRole>()
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders();

// Add authentication services
services.AddAuthentication(options =>
{
    //options.DefaultScheme = "Company Account Office 365";
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = "Company Account Office 365";
})
.AddCookie()
.AddOpenIdConnect("Company Account Office 365", "Company Account", options =>
{
    options.Authority = Configuration["Authentication:Office365:Company:Authority"];
    options.RequireHttpsMetadata = true;
    options.ClientId = Configuration["Authentication:Office365:Company:ClientId"];
    options.ClientSecret = Configuration["Authentication:Office365:Company:ClientSecret"];
    options.CallbackPath = new PathString("/signin-oidc-mycompany");
    options.Scope.Add("openid");
    options.Scope.Add("email");
    options.Scope.Add("api1");
});

services.AddAuthorization(options =>
    options.AddCompanyPolicies()); /* Extension method */

// Add MVC services to the services container.
services.AddMvc();
services.AddSession();

// Register application services.
RegisterAppliationServices(services);

// Amazon S3
services.AddTransient<IFileStorage, AmazonS3FileStorage>(sp =>
    new AmazonS3FileStorage(
        new BasicAWSCredentials(
            Configuration["AWS:S3:AccessKey"],
            Configuration["AWS:S3:SecretKey"]),
        Amazon.RegionEndpoint.USEast1,
        Configuration["AWS:S3:Buckets:DatabaseFileStorage"]));

// Allow forms to process more than 1024 fields.
services.Configure<FormOptions>(options => options.ValueCountLimit = 4096);

// SQL Server Data Protection Cache
services.AddTransient<IXmlRepository, DataProtectionKeyRepository>();
var built = services.BuildServiceProvider();
services.AddDataProtection().AddKeyManagementOptions(options => options.XmlRepository = built.GetService<IXmlRepository>());
```

There are a bunch of `.AddSingleton` and `.AddTransients` in the RegisterApplicationServices method and there are a few other extension methods too.

**Comment by Tratcher** [comment]
AddIdentity and AddAuthentication don't mix like that. Are you using Identity or not? It's setting DefaultSignInScheme which is messing with your flow.

**Comment by rchowe** [comment]
We are using a number of the role-based features of identity.

I don't understand what's different from the [docs](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x) where they have both `AddIdentity` and `AddAuthentication` as well with Facebook login.

**Comment by Tratcher** [comment]
More specifically, you're setting conflicting defaults. AddIdentity sets DefaultScheme, DefaultSignInScheme, and DefaultChallengeScheme. Then you are replacing DefaultScheme and DefaultChallengeScheme. Note that sample you linked to does not override the default schemes when adding Facebook.

The defaults you're using are from the Organizational Auth configuration, they don't work with Identity.

**Comment by rchowe** [comment]
After removing DefaultScheme and DefaultChallengeScheme the user is sent to `/Account/Login` when they go to an action with `[Authorize]`. Thanks!

**Comment by msdkool** [comment]
I have an issue closed to this and it's driving me nuts. I need the AddIdentity in my Startup.cs to automatically inject UserManager and RoleManager for creation of users and roles directly from the Client App. I also need the OpenIdConnect to redirect to the IdentityServer hosted Login page. Right now, I'm caught in an infinite loop. Please help

           services.AddMvc();
            string connectionString = this.Configuration.GetConnectionString("DefaultConnection");
            string authServer = this.Configuration.GetConnectionString("AuthServer");

            var migrationsAssembly = typeof(DbContext).GetTypeInfo().Assembly.GetName().Name;

            services
                 .AddDbContext<DbContext>(options => options
                              .UseSqlServer(connectionString,
                              optionsBuilder => optionsBuilder.MigrationsAssembly(typeof(DbContext).GetTypeInfo().Assembly.GetName().Name)));

            
            services.AddIdentityServer()
            .AddConfigurationStore(options =>
            {
                options.ConfigureDbContext = builder =>
                    builder.UseSqlServer(connectionString,
                        sql => sql.MigrationsAssembly(migrationsAssembly));
            });


            services.AddIdentity<User, IdentityRole>(config =>
            {
                config.Password.RequireDigit = true;
                config.Password.RequireLowercase = true;
                config.Password.RequireNonAlphanumeric = false;
                config.Password.RequireUppercase = true;
                config.Password.RequiredLength = 8;
                config.User.RequireUniqueEmail = true;
                config.SignIn.RequireConfirmedEmail = true;
                config.SignIn.RequireConfirmedPhoneNumber = false;
            })
            .AddEntityFrameworkStores<DbContext>()
            .AddDefaultTokenProviders();


            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
                options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme;

            })
            .AddCookie("Cookies")          
            .AddOpenIdConnect("oidc", options =>
            {                
                options.SignInScheme = "Cookies";
                options.Authority = authServer;
                options.RequireHttpsMetadata = false;

                options.ClientId = this.Configuration["PortalSettings:ClientId"];
                options.ClientSecret = this.Configuration["PortalSettings:ClientSecret"];
                options.ResponseType = "code id_token";

                options.SaveTokens = true;
                options.GetClaimsFromUserInfoEndpoint = true;

                options.Scope.Add("api");
                options.Scope.Add("offline_access");
            });`

**Comment by Tratcher** [comment]
We do not track closed issues, please open a new issue with your details. Also, please include a Fiddler trace showing the loop. I expect your default schemes are misconfigured for this scenario.

**Comment by msdkool** [comment]
Thanks for your quick response, will do that.
