### ISSUE TITLE
Login with External Providers (Microsoft, Facebook, Google, Twitter) in Asp.Net Core (2.x) Web API

### ISSUE THREAD

**Issue by a-patel** [aspnet/Security#1555]
I am using,

Asp.Net Core (2.x) + Web API
Identity User
OpenIddict for Authentication
SPA (Angular) app for Front End.
Created Google and Facebook Application (for App Id/Key and Secrets)
Not using Identity Server (4).

**Comment by a-patel** [comment]
It will be better if someone can give me the,
"Sequence of events which will take place during external login"

**Comment by Tratcher** [comment]
You should refer to OpenIddict samples for this scenario.

**Comment by PinpointTownes** [comment]
You may want to give @asadsahi's project a try. It does exactly what you're looking for: https://github.com/asadsahi/AspNetCoreSpa

**Comment by a-patel** [comment]
Thanks @Tratcher  and @PinpointTownes
