### ISSUE TITLE
Wrong value retrieved from JwtClaimTypes.UpdatedAt claim

### ISSUE THREAD

**Issue by icistrate** [aspnet/Security#1556]
Hi,

I have a strange behavior that the value retrieved from `JwtClaimTypes.UpdatedAt` claim is `\"2017-03-27T13:10:05\" `instead of `2017-03-27T13:10:05 ` (note extra quotes). 

I initially thought is a bug in `IdentityServer4.AccessTokenValidation`, so I posted this issue there [https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/issues/96](https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/issues/96). But the contributors there confirmed I should better post this issue here, since at this level might be a bug.

Thanks!

![ids](https://user-images.githubusercontent.com/17759960/33266885-91229fa0-d377-11e7-9d74-edf1932f9082.png)

**Comment by Tratcher** [comment]
This was with JwtBearer? Can you share an expired JWT token?

@brentschmaltz

**Comment by PinpointTownes** [comment]
I agree it's a bit weird to see these extra quotes but I don't think it's an IM bug,

The OIDC spec explicitly says that the `updated_at` profile claim is a "JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time". Yet your OIDC server seems to return it as a stringified date, which is invalid and non-standard (and proves once again that the OIDC certification tests are way too limited :sweat_smile:)

Could you share a raw JWT to confirm my theory?

**Comment by icistrate** [comment]
@PinpointTownes @Tratcher As already said in the other post, it seems only the API side is affected. In Identity Server and javascript client I see no issue. 

Just for reference, I used dt.ToString("s", InvariantCulture) when creating the claim in IDS; but when reading the value with DateTime.ParseExact(dt, "s", InvariantCulture); this always fails because of extra quotes.

JwtBearer lib version: 1.1.2

Screenshot of a token (no extra quotes):
![x](https://user-images.githubusercontent.com/17759960/33316842-a55d0a3c-d435-11e7-9a03-32ead59e271e.png)

**Comment by PinpointTownes** [comment]
@icistrate IdentityModel doesn't support stringified dates. I opened a new ticket on your behalf to track possible improvements: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/842.

**But as I already said, the real issue is in your own code: with JWT, dates are expected to be number values, not strings.**

**Comment by icistrate** [comment]
@PinpointTownes Oops.. get it now. Don't know why I thought the claims are just some serialized key/value strings. Thank you for your support!

**Comment by icistrate** [comment]
@PinpointTownes Do you mind having a look at below code? Do I set correctly the DateTime inside a Claim? Do I understand correctly that I was missing the `ClaimValueTypes.DateTime`?

```
// BEFORE
//result.Add(new Claim(JwtClaimTypes.UpdatedAt, account.DateLastChange.Value.ToString("s",
System.Globalization.CultureInfo.InvariantCulture)));
// AFTER
result.Add(new Claim(JwtClaimTypes.UpdatedAt, account.DateLastChange.Value.ToString("s",
System.Globalization.CultureInfo.InvariantCulture), ClaimValueTypes.DateTime));
```
When I look at the available API for `System.Security.Claims.Claim` I don't see anywhere a parameter to accept an object, but only strings! Any explanation?
