### ISSUE TITLE
[OIDC] State is lost in hybrid flow

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Security#1557]
Sample here:
https://github.com/ycrumeyrolle/OpenIdConnectSamples

Got the following error message:
```
OpenIdConnectProtocolInvalidStateException: IDX10329: RequireState is 'True' but the OpenIdConnectProtocolValidationContext.State is null. State cannot be validated.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
```

Tried with my own Authorization Server and with https://demo.identityserver.io/.

When receiving the [protocol message](https://github.com/ycrumeyrolle/OpenIdConnectSamples/blob/master/src/OidcWebApp/Startup.cs#L79), the state property is set to the `state` parameter . 
When [validating the token](https://github.com/ycrumeyrolle/OpenIdConnectSamples/blob/master/src/OidcWebApp/Startup.cs#L84) the state property is null.

**Comment by Tratcher** [comment]
The handler validates State itself, RequireState is not required:
https://github.com/aspnet/Security/blob/a9482d1d03fc22f62e42cf31b8adb32c5550835e/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L507-L544

**Comment by ycrumeyrolle** [comment]
The RequireState in the sample is commented out and is used as workaround for the described issue.

**Comment by Tratcher** [comment]
OpenIdConnectOptions sets up its own validator that disables state validation. You are overwriting this default.
https://github.com/aspnet/Security/blob/a9482d1d03fc22f62e42cf31b8adb32c5550835e/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L179-L183

**Comment by ycrumeyrolle** [comment]
I see my mistake. I had overridden the ProtocolValidator because my AS was bogus with the nonce, and it brings a new bug due to the default value of the RequireStateValidation property. 

Is is a desired behavior that RequireStateValidate=true and RequireState=true is not supported and produce an exception ?

**Comment by Tratcher** [comment]
Yes, that's the current design.
