### ISSUE TITLE
SignInManager.SignInAsync and HTTPs

### ISSUE THREAD

**Issue by redowl3** [aspnet/Security#1564]
Not sure if this covered elsewhere but why does SignInManager.SignInAsync now only work with https sites?  I had identity working perfectly fine on a live site but now it's stopped working?  It's not a problem to run SSL locally but how do I get this working when in Azure?

**Comment by DeluxZ** [comment]
First of all, I'm glad the SignInManager.SignInAsync works with HTTPS sites only.

If you want to run your website on a webapp with the default _*.azurewebsites.net_ URI, just use _https://*.azurewebsites.net_. If you want a custom domain to be binded to your webapp see the docs [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-custom-domain)

**Comment by redowl3** [comment]
Thanks for the response, not sure I'm against SignInManager working with HTTPS sites either but surely this is a breaking change isn't it?

**Comment by DeluxZ** [comment]
I don't know if it's a breaking change. The SignInManager is part of the [aspnet/Identity](https://github.com/aspnet/Identity/blob/eb3ff7fc32dbfff65a1ba6dfdca16487e0f6fc41/src/Microsoft.AspNetCore.Identity/SignInManager.cs) repository.

**Comment by redowl3** [comment]
But previous projects (not pointing at https) were working using aspnet/Identity and now they've stopped, but I will leave that for MSFT to answer, thanks again for your help.

**Comment by Eilon** [comment]
There aren't any protocol restrictions that we're aware of. Did you set the cookie policy for your app to be Secure only? If so, the cookies won't transport over HTTPS.

Having said that, we highly recommend using HTTPS for all requests - especially authenticated requests.

**Comment by redowl3** [comment]
Thanks for the response.  I'm confused, I created a ASP.NET MVC Core project using VS2017 a couple of months ago and authorisation was working without needing to use https.  I've since updated my version of  .net core (2.0.3) and authorisation has stopped working unless I use https?  That to me by definition is a breaking change isn't it?

**Comment by redowl3** [comment]
When I publish to Azure, I don't need to use https so I'm assuming that Azure is still using .Net Core 2.0?

**Comment by Eilon** [comment]
HTTPS isn't required, it's just highly recommended.

**Comment by redowl3** [comment]
Seems like it is now.  I've just created a new ASP.NET Core MVC app and it now opens by default in https and as previously mentioned, my app created a few months ago has stopped working?

**Comment by Eilon** [comment]
In ASP.NET Core 2.1 we changed the default templates to all use HTTPS instead of HTTP because it is more secure and more reliable. But, you can certainly disable all the HTTPS features and go back to HTTP.

However, none of this would affect any existing apps, it would affect only new apps created with ASP.NET Core 2.1.

**Comment by redowl3** [comment]
Thanks for the response.  I can assure you it did affect an existing project, the only way I could get authorisation to work was by enabling SSL.

**Comment by Eilon** [comment]
@redowl3 hmm ok that's very surprising.

@Tratcher any idea what could have caused such a change in an existing app?

**Comment by Tratcher** [comment]
No. There were very few patch changes for Identity and Security, and none that touched on the protocol restrictions.

Did you also update VS? What VS version are you using now?

What template are you using? I was not able to reproduce this using ASP.NET Core 2 on .NET Core 2 with MVC and Individual User Accounts. Yes it has https enabled by default for IIS Express, but http works fine with or without disabling https.

What happens for you on HTTP connections? You haven't given any details yet.
