### ISSUE TITLE
Custom AuthorizeAttribute under Asp.net Core

### ISSUE THREAD

**Issue by Edward-Zhou** [aspnet/Security#1565]
I know current Authorize supports elements like below:

`        [Authorize(Roles = "XX", Policy = "XX")]`
I want to add more elements enums like below:

`[Authorize(Roles = "XX", Policy = "XX", Permission="Read")]`
How to implement my own Authorize attribute and add new function for Permission? I have tried to inherit AuthorizeAttribute like below, but I do not know how to invoke Permission validate.

```
public class CustomAuthorizeAttribute : AuthorizeAttribute
{
    public string Groups { get; set; }
}
```
Any help would be appreciated

**Comment by Tratcher** [comment]
The Authorize attribute itself is not extensible. The recommended extensibility is through authorization policies.
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies
