### ISSUE TITLE
JwtBearerHandler will make authentication successful as long as any SecurityTokenValidator passes??

### ISSUE THREAD

**Issue by withinoneyear** [aspnet/Security#1567]
I was expecting this class to execute each SecurityTokenValidators and mark it as failed once any of them fails, but from the source code apparently it's working in the other way. That doesn't sound correct to me. Why is it implemented in this way?

**Comment by blowdart** [comment]
Because that way you can load up multiple issuers and multiple signatures to be checked.

What are you trying to achieve?

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.
