### ISSUE TITLE
CORS Cookies not being sent, even if credentials:"include"

### ISSUE THREAD

**Issue by ghstahl** [aspnet/Security#1569]
I have a CORS enabled asp.net core 2 app [SOURCE](https://github.com/ghstahl/P7.Core-2.0/tree/master/src/ReferenceWebApp.CookieAuthApi) that I am trying to use Cookie Authentication.  

Same-Domain works;
[sign-in](https://p7-referencewebapp-cookieauthapi.azurewebsites.net/api/Identity/sign-in?username=herb&password=1235)  
[check-authentication](https://p7-referencewebapp-cookieauthapi.azurewebsites.net/api/Identity/check-authentication)  
[sign-out](https://p7-referencewebapp-cookieauthapi.azurewebsites.net/api/Identity/sign-out)   

CORS does not;  
I tested it both from [test-cors.org](https://test-cors.org)  and my fetch calls.   
When calling establishAuthenticatedSession, I have to set credentials: 'include' for my AUTHCOOKIE to be dropped.  
Any followup call, like signOut, doesn't send the AUTHCOOKIE.   The cookie samesite set to LAX or Strict doesn't seem to matter.  

I have my CORS App hosted on Azure.  
The thing I have noticed is that Azure drops an ARRAfinity cookie, which DOES get sent...  WHY that and not mine.
![arrafinity on azure](https://user-images.githubusercontent.com/201257/33841747-67c0e60e-de4d-11e7-97ff-7a76afdedb57.png)

The following is a request that sends the ARRAfinity cookie but not my AUTHCOOKIE.
The only difference I see between these cookies is that the domain is slightly different and ARRAfinity is set to NONE, vs "Strict" or "LAX" that my AUTHCOOKIE is set to.   

![authcookie-notsent](https://user-images.githubusercontent.com/201257/33841957-03df25c8-de4e-11e7-9b4e-ac62c874ceb7.png)

At this point I don't know if it is because my AUTHCOOKIE is set up wrong or if I am using fetch wrong.
_BTW: I have the same problem when my app is running at localhost, so it isn't an azure thing._

```
establishAuthenticatedSession(){
    let self = this;
    var model = this.get();
    console.log(model);
    var url = "https://p7-referencewebapp-cookieauthapi.azurewebsites.net/api/Identity/sign-in?username=herb&password=1234";
    fetch(url,
    {
        credentials: 'include',
        headers: { 'Content-Type': 'text/plain' },
        method: 'GET'
    })
    .then(function (res) {
        console.log(res);
        self.set({ establishSession:{ message:"Success" }});
    }).catch(function(error) {
        self.set({ establishSession:{ message:error.message }});
        console.log('There has been a problem with your fetch operation: ' + error.message);
    });
    
},
signOut(){
    
    let self = this;
    var model = this.get();
    console.log(model);
    var url = "https://p7-referencewebapp-cookieauthapi.azurewebsites.net/api/Identity/sign-out";
    fetch(url,
    {
        credentials: 'include',
        headers: { 'Content-Type': 'text/plain' },
        method: 'GET'
    })
    .then(function (res) {
        console.log(res);
        self.set({ signoutResult:{ message:"Success" }});
    }).catch(function(error) {
        self.set({ signoutResult:{ message:error.message }});
        console.log('There has been a problem with your fetch operation: ' + error.message);
    });
    
},
```

**Comment by ghstahl** [comment]
This was a painful 2 days....

So it turns out that the cookie needs to be set as SameSiteMode.None. The hint I got was that that ARRAfinity cookie from azure as set to non and it was being sent where mine was not.

In my app I had to set it as follows;

public class Startup
{
    ...

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        ...           

        services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                // sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            })
            .AddCookie(
                CookieAuthenticationDefaults.AuthenticationScheme,
                options =>
                {
                    options.LoginPath = "/Account/LogIn"; ;
                    options.AccessDeniedPath = new PathString("/account/login");
                    options.Cookie.Name = "AUTHCOOKIE";
                    options.ExpireTimeSpan = new TimeSpan(365, 0, 0, 0);
                    options.Cookie.SecurePolicy = CookieSecurePolicy.SameAsRequest;
                    options.Cookie.SameSite = SameSiteMode.None;

                }
            );
        ...
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        ...
        var cookiePolicyOptions = new CookiePolicyOptions
        {
            Secure = CookieSecurePolicy.SameAsRequest,
            MinimumSameSitePolicy = SameSiteMode.None
        };

        app.UseCookiePolicy(cookiePolicyOptions);
        ...
    }
}

**Comment by amy-dredge-ps** [comment]
Thanks for hitting your head on the wall for me and posting your solution. I ran into the same problem last night for an hour or so, but after some sleep and 13 minutes this morning I googled the right thing, found your post, and it's working now. Just wanted to say thanks.

**Comment by kpietraszko** [comment]
Love you man, I was losing my mind for 2 hours just before deadline.

**Comment by dmichael266** [comment]
Dude, I can't thank you enough for posting this solution.  I spent over 4 hours trying to figure this problem out and your solution worked perfectly.

**Comment by jrt324** [comment]
I spent over one day to this problem , and lucky i found your solution saved my life ,thank you @ghstahl
