### ISSUE TITLE
Resource based auth -- return errors.

### ISSUE THREAD

**Issue by Mardoxx** [aspnet/Security#1570]
I guess this is a bit of a mixed concern between authZ and validation...

How can you return errors from resource based auth without ending up with a spaghetti of if..elif.. statements checking individual policies?

Contrived example: User belongs to several groups. Super user of a group can add users to its group. How can I relay to the user that they don't have access to a particular group?

**Comment by Eilon** [comment]
This is a dup of https://github.com/aspnet/Security/issues/1530, which we plan to handle as part of https://github.com/aspnet/Security/issues/1359.
