### ISSUE TITLE
No remoteError propagated to auth template's ExternalLoginCallback action

### ISSUE THREAD

**Issue by jbagga** [aspnet/Security#1571]
The code path is not hit with a remoteError as an exception gets thrown before it reaches the endpoint

See comment: https://github.com/aspnet/templating/pull/186#issuecomment-351233747

cc @HaoK

**Comment by Eilon** [comment]
This will be handled by https://github.com/aspnet/Security/issues/1165, so closing as dup.

**Comment by jbagga** [comment]
See https://github.com/aspnet/templating/pull/186#issuecomment-351265832
