### ISSUE TITLE
IdentityServer3 based SSO server does not connect with ASP.net Core 2.0 based client

### ISSUE THREAD

**Issue by blowdart** [aspnet/Security#1572]
_From @abhishekchouksey on December 11, 2017 23:26_

IdentityServer3 based SSO server does not work with ASP.net CORE based client, we have been migrating our product from MVC 5 to ASP.net core 2.0 and have noticed that SSO server failed to provide login page.

This is request i have got from MVC 5 based application, which uses OWIN middle ware

```

 app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = configurationSettings.AuthorityUri,
                ClientId = configurationSettings.ClientId,
                RedirectUri = configurationSettings.BaseUri,
                ResponseType = "id_token token",
                Scope = "openid api",
                SignInAsAuthenticationType = "Cookies",
                UseTokenLifetime = false
}
identity/connect/authorize?client_id=XXXX
&redirect_uri=XXXXXXXXXXXXXXXXXXX
&response_mode=form_post&response_type=id_token+token&scope=openid+api&state=OpenIdConnect.AuthenticationProperties%3dwFuNqQIdG7E9axIWsGRaxqn8Aikv4B839r1HfWPm57n9RZ5Ig8BK-r2WuNclpcGZr0Ch2GThSpZ53ShE1zBESfxrSHts_I2iLYfTCvBa0Kd-uRueov-NpXDJOh39yh_f-h8TMcCXRe9S3cvE2eWp64dqJLJZM8EqBsW77b-keS3SvTB2KU0X7NqW-VGdI2StBn0y4kiWg9mZseGS4chgsA&nonce=636483566187911271.OTVmNDY1NGQtZDgxZS00ZjllLThjYzQtYjVkNGYxMGM5ZGZhZGI4MzMyYjctMTBiNi00OGQ3LThmOWItNGExNTc5OGFiYTA4

```

This is request from ASP.net CORE 2.0

```

 services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultAuthenticateScheme = OpenIdConnectDefaults.AuthenticationScheme;
                sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                
            }).AddCookie()
              .AddOpenIdConnect( options =>
            {
                //   options.AutomaticChallenge = true;
                options.Authority = configurationSettings.AuthorityUri;
                options.ClientId =configurationSettings.ClientId;
                options.ResponseType = OpenIdConnectResponseType.IdTokenToken;
                options.Scope.Add("openid api");
                options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.UseTokenLifetime = false;
                options.CallbackPath = new PathString("/");
                options.GetClaimsFromUserInfoEndpoint = true;
      }

identity/connect/authorize?
client_id=XXXXX
&redirect_uri=XXXXXXXXXXXXX &response_type=code
&scope=openid%20api
&response_mode=form_post
&nonce=636483740666280555.NDA3ZGRjZDQtNTdjNS00NjFiLTllOTYtMDc0MjE2NzhkMzQ5NmFiMzU0ZTQtMDIxOS00ODI5LWI4NWEtYTRiMDYzMTFmYjJi&state=CfDJ8AqnlI2Cn3FJtTEVow2y5i5Kt7x-JhPHvqlWGUu6jOxJQQiBB53rtgKV7_nXM4zY0MbzFPQUuONdoyEmX61bexqlAmbTmpEnVC5CHkr41q4b6e3_JtWTBaCOa3vT1_vCNNnIS6lQW3RH4nV-SQ5PUyVr2IzMO3feVRrkS-NLnLAuUXyKSR3gk0LtuzESq_xQ0dtdrjnWr5-dbCyOvG0p3vFhlaQeKyT55q2jZyM4sO0T7B524l6ICz2cKEVLdR6VU2RpjqV_UAlwM7i9Mm7yo_kbCBbtaOOZDWjDVj6XDop0YUmYJhMLGnlXWVBjD87vmg
&x-client-SKU=ID_NET&x-client-ver=2.1.4.0
```

So I wrote the test version of IdentityServer4 based SSO, which works fine with ASP.net CORE.

Is there any defect with ASP.net CORE OpenIDConnect handler?

was there any underlying implementation has been changed to support backward compatibles? 

_Copied from original issue: aspnet/Identity#1527_

**Comment by blowdart** [comment]
@Tratcher the response type is different, could you take a look?

**Comment by abhishekchouksey** [comment]
Just a small correction, it was state which is different
This state from Asp.net core 2.0
`
state=CfDJ8AqnlI2Cn3FJtTEVow2y5i5Kt7x-JhPHvqlWGUu6jOxJQQiBB53rtgKV7_nXM4zY0MbzFPQUuONdoyEmX61bexqlAmbTmpEnVC5CHkr41q4b6e3_JtWTBaCOa3vT1_vCNNnIS6lQW3RH4nV-SQ5PUyVr2IzMO3feVRrkS-NLnLAuUXyKSR3gk0LtuzESq_xQ0dtdrjnWr5-dbCyOvG0p3vFhlaQeKyT55q2jZyM4sO0T7B524l6ICz2cKEVLdR6VU2RpjqV_UAlwM7i9Mm7yo_kbCBbtaOOZDWjDVj6XDop0YUmYJhMLGnlXWVBjD87vmg`

This is from MVC 5 OWIN
`
state=OpenIdConnect.AuthenticationProperties%3dwFuNqQIdG7E9axIWsGRaxqn8Aikv4B839r1HfWPm57n9RZ5Ig8BK-r2WuNclpcGZr0Ch2GThSpZ53ShE1zBESfxrSHts_I2iLYfTCvBa0Kd-uRueov-NpXDJOh39yh_f-h8TMcCXRe9S3cvE2eWp64dqJLJZM8EqBsW77b-keS3SvTB2KU0X7NqW-VGdI2StBn0y4kiWg9mZseGS4chgsA&nonce=636483566187911271.OTVmNDY1NGQtZDgxZS00ZjllLThjYzQtYjVkNGYxMGM5ZGZhZGI4MzMyYjctMTBiNi00OGQ3LThmOWItNGExNTc5OGFiYTA4`

I tried with all possible response types, result was same. 

State it adds  "OpenIdConnect.AuthenticationProperties" text. 

other difference that i see is for response type and scope it adds "+"(plus sign in between), I am not sure that is any issue.

**Comment by Tratcher** [comment]
Scope is a list now, you should be adding to separate values there.

The state differences aren't an issue, state is opaque to the server.

**Comment by abhishekchouksey** [comment]
I have tried that too, there is no difference.  is it possible that encryption method of nonce or state may be different? 
```

        .AddOpenIdConnect( options =>
            {
                options.Scope.Add("openid");
                options.Scope.Add("api");
```

**Comment by Tratcher** [comment]
Any encryption is not relevant as those are all opaque to the server.

**Comment by Eilon** [comment]
@javiercn can you take a look?

**Comment by abhishekchouksey** [comment]
I started looking Source code for OpenIdConnectOptions it is by default adding "profile" and "openId" as scope..  though i am not even adding in my scope it was anyways added. 

So remove "profile" scope  from URL  and resubmitted the form.. request went through successfully. 

modified code as below..  now it works fine.  
                ```
options.Scope.Clear();
                options.Scope.Add("openid");
                options.Scope.Add("api");
```

After all it is underlying implementation change.  could not find any explicit documentation to identify these change, would it possible to have some docs which define all the differences from Katana implementation and asp.net core., or if it is already there.. would you please share.

**Comment by brockallen** [comment]
> So remove "profile" scope from URL and resubmitted the form.. request went through successfully.

Ugggg, more reason to remove "profile" from the defaults.

**Comment by blowdart** [comment]
And when we remove it we get complaints. The defaults are frankly are huge argument no-one can win.

**Comment by brockallen** [comment]
> And when we remove it we get complaints

IMO, only because it was added by default.

**Comment by javiercn** [comment]
@abhishekchouksey Just to make sure I understood it correctly, was your issue that the profile scope was being sent by default and Identity Server v3 having trouble with it?

Nothing else on the issue seems to point to an actual problem. Nonce and state are opaque as @Tratcher mentioned and the constant for TokenIdToken is correct.

Are you able to repro this? (I am not)

> services.AddAuthentication(sharedOptions =>
>             {
>                 sharedOptions.DefaultAuthenticateScheme = OpenIdConnectDefaults.AuthenticationScheme;
>                 sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
>                 sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
>                 
>             }).AddCookie()
>               .AddOpenIdConnect( options =>
>             {
>                 //   options.AutomaticChallenge = true;
>                 options.Authority = configurationSettings.AuthorityUri;
>                 options.ClientId =configurationSettings.ClientId;
>                 options.ResponseType = OpenIdConnectResponseType.IdTokenToken;
>                 options.Scope.Add("openid api");
>                 options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
>                 options.UseTokenLifetime = false;
>                 options.CallbackPath = new PathString("/");
>                 options.GetClaimsFromUserInfoEndpoint = true;
>       }
> 
> identity/connect/authorize?
> client_id=XXXXX
> &redirect_uri=XXXXXXXXXXXXX &response_type=code
> &scope=openid%20api
> &response_mode=form_post
> &nonce=636483740666280555.NDA3ZGRjZDQtNTdjNS00NjFiLTllOTYtMDc0MjE2NzhkMzQ5NmFiMzU0ZTQtMDIxOS00ODI5LWI4NWEtYTRiMDYzMTFmYjJi&state=CfDJ8AqnlI2Cn3FJtTEVow2y5i5Kt7x-JhPHvqlWGUu6jOxJQQiBB53rtgKV7_nXM4zY0MbzFPQUuONdoyEmX61bexqlAmbTmpEnVC5CHkr41q4b6e3_JtWTBaCOa3vT1_vCNNnIS6lQW3RH4nV-SQ5PUyVr2IzMO3feVRrkS-NLnLAuUXyKSR3gk0LtuzESq_xQ0dtdrjnWr5-dbCyOvG0p3vFhlaQeKyT55q2jZyM4sO0T7B524l6ICz2cKEVLdR6VU2RpjqV_UAlwM7i9Mm7yo_kbCBbtaOOZDWjDVj6XDop0YUmYJhMLGnlXWVBjD87vmg
> &x-client-SKU=ID_NET&x-client-ver=2.1.4.0

**Comment by leastprivilege** [comment]
The problem is different expectations ;)

The OIDC spec defines only one mandatory scope and that is `openid` - hence all other scopes are optional in IdentityServer.

The MS handler adds profile by default - which I think is wrong as a default value.

If a client asks for a scope that does not exist in IdentityServer, we error.

**Comment by abhishekchouksey** [comment]
@javiercn I was able to reproduce.. and I think @leastprivilege  is right about MS implementation.

**Comment by javiercn** [comment]
I’m asking specifically for the error where the response type is set to id_token token and the request has response_type=code instead. @abhishekchouksey can you reproduce that behavior? (That would be a bug) if so, can you provide a simple repro project?

As per the defaults I leave that to @blowdart.

**Comment by blowdart** [comment]
@Eilon How do you feel about making a breaking change?

**Comment by Eilon** [comment]
@blowdart that's up to @DamianEdwards . Depends on how "breaky" it is.

**Comment by leastprivilege** [comment]
@davidfowl once told me that if you are fixing a bug, it’s not a breaking change....

**Comment by Tratcher** [comment]
I'd expect the Org Auth template to break.

**Comment by leastprivilege** [comment]
Then add it there explicitly.

The default is the problem. Not the usage.

**Comment by Tratcher** [comment]
Not quite that easy, all prior apps created with that template also break and have to make changes.

**Comment by PinpointTownes** [comment]
> @davidfowl once told me that if you are fixing a bug, it’s not a breaking change....

The fact you don't like a default doesn't mean it's a bug :open_mouth: 

There's a sensible reason for having `profile` added by default in the OIDC handler: all the Katana/ASP.NET Core social providers tend to add some basic data by default (like a display name or a username). Yet, if you don't request the `profile` scope, chances are high you'll only get the `sub`.

If the `profile` scope was removed, it would make the OIDC handler inconsistent with the other providers (and it would be a big breaking change).

**Comment by brockallen** [comment]
> There's a sensible reason for having profile added by default in the OIDC handler

But `profile` isn't always the scope to model those things, and OIDC is less about social and is more about enterprise.

> If the profile scope was removed, it would make the OIDC handler inconsistent with the other providers (and it would be a big breaking change).

Disagree, since all the other providers are custom anyway.

**Comment by javiercn** [comment]
As @tratcher says this would be a massive breaking change for existing apps, so we can’t just change it.

**Comment by brockallen** [comment]
Well, we tried to warn about it prior to 2.0 shipping.

> As @Tratcher says this would be a massive breaking change for existing apps, so we can’t just change it.

And since you use semver, at least it can be done in 3.0.

**Comment by javiercn** [comment]
@blowdart I give this back to triage, I suggest we close this bug and open a new one  to change the default scopes in the future if we choose to do so.

**Comment by Eilon** [comment]
Closing because we are not planning to change this behavior. We still think this is the right default for most apps, but agree it isn't the right default for all apps. Add to that the cost of a breaking change, and we think this isn't a good change to make overall.
