### ISSUE TITLE
Detect if an external authentication provider was used at sign in or not

### ISSUE THREAD

**Issue by blowdart** [aspnet/Security#1574]
_From @gabosistvanpwc on December 12, 2017 14:33_

Hi,

Is there any way to tell after login if the current user was signing in by using the regular authentication flow or an external authentication provider?

Thank you

_Copied from original issue: aspnet/Identity#1530_

**Comment by blowdart** [comment]
_From @grahamehorner on December 12, 2017 14:54_

the claims for the user identity should have the login provider information?

**Comment by blowdart** [comment]
_From @gabosistvanpwc on December 12, 2017 15:12_

Unfortunately it doesn't. 

I'm using the basic ASP.NET Core Web Application project template with the Individual User Accounts authentication option. As the external provider I have configured the WsFederation middleware as follows:

services.AddAuthentication()
.AddWsFederation(options =>
{
options.Wtrealm = "xxxx";
options.MetadataAddress = "xxxx";
})
.AddCookie();

After the request is going through the usual steps 

1. AccountController.ExternalLogin
2. Identity provider login page
3. AccountController.ExternalLoginCallback (and here _signInManager.ExternalLoginSignInAsync method)

and the user is authenticated the claims from the User.Identity have the same "default" entries as if the user was authenticating directly through the application.

I would like to tell at any point when accessing an action /controller which requires authentication if the user was logging in the system through the regular sign in flow or through an external authentication provider.

Probably I'm missing here something....

**Comment by blowdart** [comment]
@Tratcher Does WS-Fed not embed this info like OIDC does? Can we ensure it matches?

**Comment by Tratcher** [comment]
They're dropping all provider specific information at step 3 above. This is more of an identity / template question on how to preserve external claims when transitioning to a local user.

**Comment by gabosistvanpwc** [comment]
Any updates?

**Comment by brockallen** [comment]
Why not just issue an `idp` claim to indicate the provider used.

**Comment by Eilon** [comment]
If using ASP.NET Core Identity the way the default ASP.NET Core templates use it, the system adds a claim to indicate the external provider used.

Here you can find the code where the claim is set:
https://github.com/aspnet/Identity/blob/435ab653dbb7611c0e936e91279f3337d4071622/src/Identity/SignInManager.cs#L192

So you should be able to read it out to get the value.

If your app is not using ASP.NET Core Identity then you will need to update your app to track this data manually.
