### ISSUE TITLE
How can I change MicrosoftAccountOptions/GoogleOptions/FacebookOptions/TwitterOptions in controller

### ISSUE THREAD

**Issue by seven1986** [aspnet/Security#1576]
This's in Startup.cs ConfigureServices how I config the OAuth providers
```chsarp
services.AddAuthentication(options => {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            })
            .AddFacebook(x => {
                x.AppId = "xxx";
                x.AppSecret = "xxx";
            })
            .AddTwitter(x => {
                x.ConsumerKey = "xxx";
                x.ConsumerSecret = "xxx";
            })
            .AddGoogle(x => {
                x.ClientId = "xxx";
                x.ClientSecret = "xxx";
            })
            .AddMicrosoftAccount(x => {
                x.ClientId = "xxx";
                x.ClientSecret = "xxx";
            })
```
Then, for some requirements, I need to update AppId/AppSecret in controller action, How I can do that?

**Comment by Tratcher** [comment]
You can remove and re-register the providers with new options using the IAuthenticationSchemeProvider service.
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Authentication.Abstractions/IAuthenticationSchemeProvider.cs

Note this is not an atomic operation so you'll have a small race condition that may cause active login requests to fail.

**Comment by Eilon** [comment]
We're working on a sample that should cover this as well. You can check out the pull request here: https://github.com/aspnet/AuthSamples/pull/22

**Comment by seven1986** [comment]
@Tratcher There are defferent domains CNAME my application, every domain represent different company.
I according the domain regonization company, then need reset the AuthProvider configurations. 
I wanna know how to achieve this.
 Thanks

**Comment by Tratcher** [comment]
Multi-tenancy.... This system really isn't built for that. You can get a little ways by re-implementing interfaces like IAuthenticationSchemeProvider, but for full multi-tenancy you may be better off using a system like Orchard that builds this for you.

In the short term I suggest registering a unique auth scheme per domain and using IAuthenticationSchemeProvider to select the correct scheme per request.
