### ISSUE TITLE
Basic authentication works on Mac. Does *not* on Windows

### ISSUE THREAD

**Issue by tanyado** [aspnet/Security#1579]
The code can be found here: https://stackoverflow.com/questions/45417337/httpclient-with-networkcredential-returns-401-for-net-core-200-for-net-framewo

We have determined the issue to the linked problem was a combination cookie handling and basic authentication not being part of .Net Core.

However, it seems strange that the same code that works on a Mac OS, does *not* work on a Windows OS. 

----------------------
Additional information:
1. This is a Windows console program built with .NET Core that invokes a webservice with Basic Authentication is not populating the cookie correctly.  (.NET Core 1.0 or 2.0)
2. The same console program built with .NET Core running on a Mac works fine. 
3. The same console program built with .NET Framework works fine.
4. As suggested in the article referenced above, the use of WinHttpHandler seems to get around the problem, but gives up OS independence.

**Comment by Tratcher** [comment]
Note HttpClient bugs go over here: https://github.com/dotnet/corefx

HttpClient uses a different implementation based on the operating system so there are some expected behavioural differences between Mac and Windows.

I'm going to close this as external, and it looks like you've already got an answer on StackOverflow.
