### ISSUE TITLE
Switch to ClaimsPrincipal.WriteTo when available

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#158]

**Comment by PinpointTownes** [comment]
@brentschmaltz I just took a look at the new `ClaimsIdentity.WriteTo` and `ClaimsIdentity.Initialize` methods on Reference Source and I have the weird sensation that serialization and deserialization formats differ: if `WriteTo` supports the `HasLabel`, `Actor` and `UserData`, `Initialize` doesn't seem to have any code to handle them at the deserialization stage. Am I missing something obvious? :scream: 

http://referencesource.microsoft.com/#mscorlib/system/security/claims/ClaimsIdentity.cs,1157
http://referencesource.microsoft.com/#mscorlib/system/security/claims/ClaimsIdentity.cs,1076

**Comment by PinpointTownes** [comment]
Fears confirmed: this new stuff doesn't work AT ALL, even with simple identities that expose no `Actor` and have no `Properties`:

> L'exception System.IO.EndOfStreamException s'est produite
  HResult=-2147024858
  Message=Impossible de lire au-delà de la fin du flux.
  Source=mscorlib
  StackTrace:
       à System.IO.BinaryReader.ReadByte()
       à System.IO.BinaryReader.Read7BitEncodedInt()
       à System.IO.BinaryReader.ReadString()
       à System.Security.Claims.Claim.Initialize(BinaryReader reader, ClaimsIdentity subject)
       à System.Security.Claims.Claim..ctor(BinaryReader reader, ClaimsIdentity subject)
       à System.Security.Claims.ClaimsIdentity.Initialize(BinaryReader reader)
       à System.Security.Claims.ClaimsIdentity..ctor(BinaryReader reader)
       à System.Security.Claims.ClaimsPrincipal.CreateClaimsIdentity(BinaryReader reader)
       à System.Security.Claims.ClaimsPrincipal.Initialize(BinaryReader reader)
       à System.Security.Claims.ClaimsPrincipal..ctor(BinaryReader reader)

@brentschmaltz I'm curious. Have these new APIs been really tested? :smile:

**Comment by Eilon** [comment]
Looks like we already did this another way.

**Comment by brentschmaltz** [comment]
I'll take a peak.

**Comment by MonDeveloper** [comment]
+1 
EndOfStreamException is thrown every time you try to call the ctor with the same data obtained by the WriteTo.
WEIRD !

**Comment by flouk19** [comment]
@MonDeveloper 
I looked into the code provided by @PinpointTownes there is an error in the Initialize method. 
If you compare the initialize method with the WriteTo method you can see that the WriteTo writes one integer more:
https://referencesource.microsoft.com/#mscorlib/system/security/claims/ClaimsIdentity.cs,1238
`writer.Write((Int32)numberOfPropertiesWritten);`
While the initialize does not read this numberOfPropertiesWritten:
https://referencesource.microsoft.com/#mscorlib/system/security/claims/ClaimsIdentity.cs,1104
It starts with reading the mask(an integer) and then loads the values based on the mask(strings) but skips the one integer. 
          
My workaround is to manually "Initialize" the ClaimsIdentity like this:

```
SerializationMask mask = (SerializationMask)reader.ReadInt32();
int numberOfPropertiesWritten = reader.ReadInt32();//var res = reader.ReadString();
string authenticationType = null;
object bootstrapContext = null;
string nameClaimType = null;
string roleType = null;

if ((mask & SerializationMask.AuthenticationType) == SerializationMask.AuthenticationType)
{
    authenticationType = reader.ReadString();
}

if ((mask & SerializationMask.BootstrapConext) == SerializationMask.BootstrapConext)
{
    bootstrapContext = reader.ReadString();
}

if ((mask & SerializationMask.NameClaimType) == SerializationMask.NameClaimType)
{
    nameClaimType = reader.ReadString();
}
else
{
    nameClaimType = ClaimsIdentity.DefaultNameClaimType;
}

if ((mask & SerializationMask.RoleClaimType) == SerializationMask.RoleClaimType)
{
    roleType = reader.ReadString();
}
else
{
    roleType = ClaimsIdentity.DefaultRoleClaimType;
}

identity = new ClaimsIdentity(authenticationType, nameClaimType, roleType);
identity.BootstrapContext = bootstrapContext;

if ((mask & SerializationMask.HasClaims) == SerializationMask.HasClaims)
{
    // 
    int numberOfClaims = reader.ReadInt32();
    for (int index = 0; index < numberOfClaims; ++index)
    {
        Claim claim = new Claim(reader, identity);
        identity.AddClaim(claim);
    }
}
```

**Comment by PinpointTownes** [comment]
This issue was reported almost 3 years ago. Not sure if we should laugh or cry :trollface:

**Comment by brentschmaltz** [comment]
@PinpointTownes @flouk19 @MonDeveloper 
We'll get this fixed.
https://github.com/dotnet/corefx/issues/30774
