### ISSUE TITLE
AddOpenIdConnect and signing key rollover

### ISSUE THREAD

**Issue by VictorioBerra** [aspnet/Security#1580]
I am implementing [signing key rollover in my IdentityServer4](https://identityserver4.readthedocs.io/en/release/topics/crypto.html#signing-key-rollover). The docs state this:

>This requires that clients and APIs use the discovery document, and also have a feature to periodically refresh their configuration.

So my question is when using `AddOpenIdConnect()` does the middleware periodically update their local copy of the discovery document so when I add new signing keys it will now accept both the old and the new key material and also “forget” the old key next time they update their local copy of the discovery document?

Thanks

**Comment by Tratcher** [comment]
Yes, it refreshes once per day.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/af5e5c2b0100e8348c63e2d2bb45612e2080841e/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L49
It may also refresh if it sees unrecognized keys (this is throttled):
https://github.com/aspnet/Security/blob/b3e4bf382c9676e2d912636b7ee0255cad244e11/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L683-L689

**Comment by brockallen** [comment]
>  It may also refresh if it sees unrecognized keys (this is throttled):

Unfortunately only after it fails the request with the unrecognized key.
