### ISSUE TITLE
Set-Cookie shouldn't return secure cookies on http request

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1584]
_From @jchannon on January 2, 2018 17:15_

When using ASP.Net Cookie auth and the `CookieSecure` property is set to `CookieSecurePolicy.Always` and a request is made via http to login the `Set-Cookie` header is returned with a `secure` suffix.  I don't think it should do this if the request is made via `http`, it should only return that header if made via `https`

There is nothing stopping a client taking and using the cookie value to issue a request which leads to the question for maybe https://github.com/aspnet/Security as to whether that should be allowed.

At the moment the onus is on the developer to not allow requests that are made over http when you have `CookieSecurePolicy.Always` set. I would expect the server and/or fwk to step in here.

cc @PinpointTownes

_Copied from original issue: aspnet/KestrelHttpServer#2240_

**Comment by Tratcher** [comment]
This is a misconfiguration. Using CookieSecurePolicy.Always and logging in over HTTP is nonsensical. The guidance is to force your restricted / login endpoints to use HTTPs via the RequireHttps attribute. In the 2.1 templates we're taking this a step further and requiring HTTPs for all requests by default via a new middleware.

**Comment by PinpointTownes** [comment]
Exactly what I said to @jchannon. That said, since it's fundamentally an unsafe operation, the framework/server should at least log a warning indicating that the developer is doing something terribly wrong (there's no point marking a cookie as HTTPS-only if you return it from a HTTP endpoint).

**Comment by PinpointTownes** [comment]
Yep... pretty much the reason why I said @jchannon aspnet/HttpAbstractions was a good place for this ticket :trollface:

**Comment by jchannon** [comment]
Interestingly we had it as SameAsRequest but when behind nginx and the `x-forwarded-proto` header was set it didn't work. I assume Scheme doesnt look for that header to determine if its https?

**Comment by Tratcher** [comment]
Scheme does not look at any headers, we use the forwarded headers middleware to map those headers to Scheme instead.

**Comment by jchannon** [comment]
Have you got a link to that code? 

Can you think why cookies weren't set to `secure` when we had https on nginx and the `X-Forwarded-Proto` header provided

**Comment by Tratcher** [comment]
This middleware is included by default for IIS, but not for nginx. https://github.com/aspnet/BasicMiddleware/blob/8f0cc61808e09d646ba6c32e8785a6cd8f56be29/samples/HttpOverridesSample/Startup.cs#L13

**Comment by jchannon** [comment]
Thanks

![Imgur](https://i.imgur.com/gVWDykg.gif)

**Comment by Eilon** [comment]
I think the most we would consider here is to log that a "secure" cookie is being returned to the client over a non-HTTPS connection.

However, we're not sure how much value there is to this, especially considering that start with ASP.NET Core 2.1, all project templates will be HTTPS by default, which we think is ultimately more important than the logging behavior.
