### ISSUE TITLE
OpenIdConnect authentication handler doesn't support POST to authorize endpoint

### ISSUE THREAD

**Issue by slaneyrw** [aspnet/Security#1586]
As per spec (http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), the Authorize endpoint can support a POST request.

However the OpenIdConnect authN handler only supports a GET redirect when issuing a challenge to the remote identity provider.

Please consider adding a POST implementation.  This will help alleviate issues with very long state parameter that is causing issues with URL length in some older browsers ( like IE9 and mobile variants )

**Comment by Tratcher** [comment]
Is this the setting you're looking for?
https://github.com/aspnet/Security/blob/e13ceb690bfe2a534fa11720d75fd87b4e07d6b0/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L423

**Comment by slaneyrw** [comment]
Yeah, I over looked this one... my bad.  I'm migrating from AspNetIdentity 3 on net 46 and that phrasing has a different meaning
