### ISSUE TITLE
System.ServiceModel.Web

### ISSUE THREAD

**Issue by varcario** [aspnet/Security#1594]
I'm migrating a Web API app from .NET Core RC1 to .NET Core 2.0 and having trouble finding a good replacement for one line of code.  The project is an ASP.NET Web API that calls a SOAP service, the SOAP service requires my app to send request headers 

`System.ServiceModel.Web.WebOperationContext.Current.OutgoingRequest.Headers.Add("key", "value");`

Does anyone know how to perform the above function inside a .NET Core 2.0 app targeting netcoreapp2.0?

**Comment by Tratcher** [comment]
I think you're looking for https://github.com/dotnet/wcf

**Comment by varcario** [comment]
Closed this issue and moved it to wcf project.
https://github.com/dotnet/wcf/issues/2473
