### ISSUE TITLE
Add support for CancellationTokens in AuthorizationHandler

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#1598]
_From @symlynk on January 7, 2018 12:43_

The following methods are missing CancellationToken parameters in Microsoft.AspNetCore.Authorization.AuthorizationHandler:

```
public virtual Task HandleAsync( AuthorizationHandlerContext context );
protected abstract Task HandleRequirementAsync( AuthorizationHandlerContext context, TRequirement requirement );
```
Microsoft.AspNetCore.Authorization Version 2.0.1.0

_Copied from original issue: aspnet/Home#2746_

**Comment by Eilon** [comment]
No plans to add CancellationToken parameters because this would be a breaking change, and we don't think it's worth that cost.

**Comment by twsouthwick** [comment]
@Eilon Could a cancellation token be handed in via the `AuthorizationHandlerContext` similar to how you can access a cancellation token from the `HttpContext`?

**Comment by Eilon** [comment]
A *binary* breaking change could very well be avoided by adding a new property to an existing type, but it would still likely be a *functional* breaking change because all existing components out there would not be checking the new property.

**Comment by twsouthwick** [comment]
It's kind of a chicken and egg problem, then, it seems. If it were added, over time people would add support for it and functionality would light up as it becomes more pervasive. I understand what you're saying, but isn't this the kind of argument that could be made for adding any new features that add more control to a type/framework?

**Comment by Eilon** [comment]
@twsouthwick yeah it is but the question is how much value is there compared to the cost. In this circumstance we felt the value was low compared to the cost.

**Comment by yngndrw-sage** [comment]
@Eilon Sorry to bump this issue, but I'm unsure about this being a functional breaking change.

As it stands right now an `AuthorizationHandler` implementation will not be aware of a cancelled request and therefore will continue processing regardless. With the proposed change of adding the cancellation token to the `AuthorizationHandlerContext`, an implementation which does not check this property will continue to behave in the way that it currently does - The only change in behaviour will be for implementations which do check and use the cancellation token.
