### ISSUE TITLE
How to define the key (symmetric or asymmetric) used for validating the issuer authority (the signer of the token)

### ISSUE THREAD

**Issue by gabosistvanpwc** [aspnet/Security#1599]
In previous versions the following configuration was used to define the token validation sequence and to make sure that signer of a token and the token issuer are as expected.

```
<system.identityModel>
   <issuerNameRegistry type='derived from ValidatingIssuerNameRegistry'>
      <authority name='someFriendlyName'>
         <keys>
            <add thumbprint='caseInsensitiveString'/>
            <add symmetricKey='Base64Encoded bytes' />
         </keys>
         <validIssuers>
            <add name='issuer1'/>
            <add name='issuer2'/>
         </validIssuers>
      </authority>
   </issuerNameRegistry>
</system.identityModel>
```

What properties should be set in the WsFederationOptions object to define the keys (thumbprint and symmetricKey tags) for validating the issuer authority?

Thank you

**Comment by blowdart** [comment]
@Tratcher this is WS-Fed, so you :)

**Comment by Tratcher** [comment]
@brentschmaltz ?

**Comment by gabosistvanpwc** [comment]
Is there any support right now for validating the issuer name registry, similar to https://docs.microsoft.com/en-us/dotnet/framework/security/validating-issuer-name-registry ?

I think this the piece of code from the System.IdentityModel.Tokens.ValidatingIssuerNameRegistry class that is doing this check in .NET Framework 4.5.1 :

```
protected virtual bool IsThumbprintValid(string thumbprint, string issuer)
{
     foreach (IssuingAuthority authority in this.IssuingAuthorities)
     {
         if ((((authority != null) && (authority.Thumbprints != null)) && ((authority.Issuers != null) && authority.Thumbprints.Contains(thumbprint))) && authority.Issuers.Contains(issuer))
        {
            return true;
        }
    }
   return false;
}
```

Thank you

**Comment by Eilon** [comment]
@brentschmaltz can you take a look at this?

**Comment by Eilon** [comment]
This issue was moved to AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#868
