### ISSUE TITLE
Feature Request: RequireUser

### ISSUE THREAD

**Issue by borgdylan** [aspnet/Security#160]
Considering the ```AuthenticationPolicyBuilder```, currently there is a ```RequireRole``` method that uses ```RequireClaim``` to require a ```Role``` claim having any of a set of specific values. For orthogonality purposes, can a ```RequireUser``` method be added that does the same with ```Name``` claims?

**Comment by HaoK** [comment]
Sure sounds reasonable, I'd probably go with RequireUserName to be a little more explicit

**Comment by borgdylan** [comment]
I agree on RequireUserName

**Comment by HaoK** [comment]
Added in 775eb5ece452e10a27aa166f52b58a6c0b615d18
