### ISSUE TITLE
WsFederation - Supported SAML Protocol and Token versions 

### ISSUE THREAD

**Issue by gabosistvanpwc** [aspnet/Security#1603]
Hello,

I'm using the Microsoft.AspNetCore.Authentication.WsFederation 2.0.0-preview2 nuget package and I would like to know what are the current SAML protocol/token versions that are supported?

I'm getting the following exception when receiving a RequestSecurityTokenResponse from the IdP (the first time the POST is done to the "/signin-wsfed" endpoint) :

IDX11112: Exception thrown while reading 'AuthenticationStatement' for SamlSecurityToken. 
Inner exception: 'Microsoft.IdentityModel.Xml.XmlReadException: IDX30107: 'InclusiveNamespaces' is not supported.   

and I was wondering if this might be because of a not supported saml token version. I might be completely wrong on this but I think that the IdP is using the SAML 2.0 protocol and SAML 1.1 tokens. 

Thank you

**Comment by reicher001** [comment]
Here is the part of the SAML token we believe is causing this error.

...
<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                                <InclusiveNamespaces PrefixList="#default saml ds xs xsi" 
                                    xmlns="http://www.w3.org/2001/10/xml-exc-c14n#" />
                            </Transform>
...

We have tested with SAML 1.1 and SAML 2.0 tokens and found they both produce this same error.

**Comment by Tratcher** [comment]
This issue was moved to AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#865
