### ISSUE TITLE
how to catch JWT bearer issuer or audience

### ISSUE THREAD

**Issue by azizkazdal** [aspnet/Security#1604]
I am looking a way to grap the value of Claim Issuer. I want to make 2 way validation of token. First step user will get the token from System API and pass it to Customer API. In customer API token need to be validate with system api token parameter.

if it is validated customer api generate a new token to the user and user will use the new token in next steps.

I am doind this because in the second step I will ad some claim for only that user have to see and use. like connection string, user role for its own database. Or is there any other way to do like this verification ?

```
services.AddAuthentication(options =>
        {
            options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
        })
        .AddJwtBearer(options =>
        {
            if (????)
            {
                // system token validator
            }
            else
            {
                //customer token validator
            }
        });
```

**Comment by Tratcher** [comment]
Start here:
```
        .AddJwtBearer(options =>
        {
            options.Events = new JwtBearerEvents()
            {
                 OnTokenValidated = context =>
                 {
                      ....
                 }
            };
        });
```

**Comment by azizkazdal** [comment]
I need to check token ClaimsIssuer before send it to validation. like in OnMessageReceived. but I could not figure out how to get the issuer from the token that sends for validation.??
Am I on the wrong way?
Just need to check token issuer before validation so I can use a different parameter to validate token for a different issuer.
Users take a token from the first API and send it to another API to validate it and take another token the second API which includes all the user roles and other stuff. So second token will be users general use token to navigate page and do other stuff like CRUD

**Comment by Eilon** [comment]
@Tratcher can you provide additional guidance here?

**Comment by Tratcher** [comment]
What different parameter did you plan on setting? TokenValidationParameters allows setting multiple issuers if that's what you're trying to juggle.

**Comment by azizkazdal** [comment]
As I understand from you I can set two different Claim Issuer parameter and two different IssuerSigningKeys. My Token validaton parameters setting is below
                   ```
 .AddJwtBearer(options =>
                    {
                        var issuers = new List<string>()
                            {
                                Configuration["SystemToken:Issuer"],
                                Configuration["Customer:Issuer"]
                            };
                        SecurityKey SystemKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration["SystemToken:Key"]));
                        SecurityKey CustomerKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration["Customer:Key"]));
                        options.TokenValidationParameters = new TokenValidationParameters()
                        {
                            ValidateIssuer = true,
                            ValidIssuers = issuers,
                            ValidateAudience = false,
                            ValidateIssuerSigningKey = true,
                            IssuerSigningKeys = new List<SecurityKey>() { SystemKey, CustomerKey },
                            ValidateLifetime = true
                        };
                        options.Events = new JwtBearerEvents
                        {
                            OnTokenValidated = ctx =>
                            {
                                //Console.WriteLine($"DateTime : {DateTime.Now.ToString()}  OnTokenValidated from TOKEN_API {ctx.SecurityToken}");
                                return Task.CompletedTask;
                            },
                            OnAuthenticationFailed = ctx =>
                            {
                                //Console.WriteLine("Exception:{0}", ctx.Exception.Message);
                                return Task.CompletedTask;
                            }

                        };
                    });
```

with this code I want to validate two different token. One from customer api generated token one is system api generated token. Is this possible to validate two different token usin this middleware config ?

**Comment by Tratcher** [comment]
That's the idea, did it work?

**Comment by azizkazdal** [comment]
Yeah that looks worked 👍 . I will do some test on it. Thank you so much
