### ISSUE TITLE
How to add more than one identical external providers with different clientid?

### ISSUE THREAD

**Issue by kitirisovgeorgy** [aspnet/Security#1605]
I try to use some like this with different ClientId:
services.AddAuthentication().AddGoogle("schema1", g => ...).AddGoogle("schema2", g => ...)
It work and app start up. 
But when I try to use schema2 I get an exceptuion "Message = "The oauth state was missing or invalid."
How can I use the google authentication with different apps?

**Comment by brockallen** [comment]
Use different callback paths for the two schemes.

**Comment by kitirisovgeorgy** [comment]
Thanks. It work.
