### ISSUE TITLE
OpenID Connect: Simplify saving tokens server side

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#1606]
Per our discussion on twitter.

Storing tokens in cookies is not always practical - and depending on token type you might want different storage strategies (e.g. refresh token vs access token).

It would be nice to have a single event that gets fired when all tokens for a given configuration are available - in this event you have access to all these tokens and can then decide which ones to store in the cookie - and which ones you want to store alternatively.

**Comment by Tratcher** [comment]
Depending on the flow you already have all of the tokens either in TokenResponseReceived or TokenValidated, correct? How would this new event differ?

**Comment by leastprivilege** [comment]
> either

That's my point. 

Why not unify that to a single dedicated event that is only about token persistence. Every application needs to deal with that.

Maybe you want to persist the id_token and access_token in the cookie - but not the refresh_token. In such an event you would get to see all three once available - and could select which one to go to the cookie, which one not.

**Comment by Tratcher** [comment]
Your flow isn't going to vary for a given application, you'd always use one of the two events. A new event might be easier to document and show samples for, but it wouldn't provide new functionality. Or did you have suggestions for additional functionality to include in the event to make alternate persistence easier.

We'd also need to work out how this event relates to the SaveTokens option. I'd expect the even to always run to avoid any confusion over not running user code, but if they turned on SaveTokens they might get redundant behavior. SaveTokens wouldn't be able to tell what you'd done in your event.

What about naming? OnSaveTokens? Sounds too confusing with SaveTokens.

**Comment by leastprivilege** [comment]
How does that sound:

* when SaveTokens = true but this new event is not handled, the behavior is as today
* if you handle the even, you get to choose which tokens go into the cookie, and which ones you persist differently.

wrt to naming - you are the experts for that ;)

**Comment by Eilon** [comment]
Thank you for your feature request. We'll consider this feature during the next release planning period and update the status of this issue accordingly. To help us prioritize this feature correctly, please make sure you provide as much information as possible about the scenarios and their importance.

**Comment by Eilon** [comment]
Closing this because we don't see this as a significant improvement to the current implementation.
