### ISSUE TITLE
Way to add identities to context.User without it getting serialized into cookie

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Security#1607]
Basically there is some very insidious behavior right now that only triggers on refresh or login.

We have extra identities we want to add to the httpcontext ClaimsPrincipal, we do this by pulling them out of a cache on request start and adding them to the ClaimsPrincipal. 

However this goes wrong in the case of a refresh (in our case, as we do work in `ValidatePrincipal`) as the `CookieAuthHandler` references the same instance in the auth ticket as is eventually set on `httpcontext.User` and so will serialize our later additions as well.

Is there any way to stop the `CookieAuthHandler` from doing this? 
(Besides cloning the cookie ClaimsPrincipal, setting that clone as new `httpcontext.User` and then working on just that instance? It feels dirty and the problem feels like an oversight.)

**Comment by blowdart** [comment]
@HaoK @Tratcher 

So is the problem here that changing the identity inside ValidatePrincipal doesn't attach itself to the context until the next request?

**Comment by NinoFloris** [comment]
It doesn't clone the principal it has to write out to the response when ShouldRenew is on, this results in the `httpcontext.User` instance and the `CookieValidationContext` principal instance being the same instance. This means any changes on context.User you'd think are 'request only' are actually sometimes (when ShouldRenew is true) written to cookie. 

I see it like this, `OnValidatePrincipal` should be about creating a principal you want to write to the cookie. Like [SecurityStampValidator](https://github.com/aspnet/Identity/blob/85f8a49aef68bf9763cd9854ce1dd4a26a7c5d3c/src/Identity/SecurityStampValidator.cs) does with delegating that work to `UserClaimsPrincipalFactory`.  

All changes after it ran should be request lifetime and absolutely have no effect on what gets written to cookie. However as it currently shares the instance any changes actually do end up in your cookie when the `Response.OnStarting` action writes it out at the end of the pipeline, way after either event.

**Comment by Eilon** [comment]
@NinoFloris can you share more info about exactly where the request-only changes are made? We think that cloning the principal is the right approach here because that way the cookie serialization won't see the modifications. However, it isn't clear to us at what point the changes are being made.

**Comment by Tratcher** [comment]
No, there's no way to change CookieHandler's behavior here. Your best bet would be to move this functionality from ValidatePrincipal to IClaimsTransformation or a followup middleware and clone the principal before using it.

**Comment by NinoFloris** [comment]
@Eilon currently through cloning and sticking an edited principal in `httpcontext.Items` during ValidatePrincipal, which we then pull out in a followup middleware and set as correct `httpcontext.User`, but ideally our additions would all be in a followup middleware.

@Tratcher We're doing something like your suggestion right now, but we need to be in ValidatePrincipal to do an overall stale check for our user's memberships and claims, if it fails the user should get a new stamp (and some other info) in their cookie as well so we're stuck doing it at that point as those checks all happen in one batch as far as our deeper membership stack is concerned and duplicating these checks is not free.

However I am curious why a clone once the code is on the path of https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L170 wouldn't work? 

Basically the cookie handler is holding on to a reference that will end up in a user-code accessible place (`httpcontext.User`) and then only in the `context.ShouldRenew` case isn't it limited to just sharing that ref but also serializing that into a cookie at, a much later, (response) time. 

Simply put you get 'spooky action at a distance', I change something here and something seemingly unrelated falls over. It feels brittle and very specific behavior only the cookie auth exhibits. 

The problem is exacerbated as Safari (and all of iOS by extension) has a 4KB domain wide cookie limit (not 4KB times 20 cookies or something that's actually RFC compliant) which will instantly brick our app for safari clients if those additions we made do get serialized because of the size. So other users with much less custom code aren't safe either, add some large identities to `httpcontext.User` while the periodic SecurityStampValidator requests a renew and it's done.

**Comment by Eilon** [comment]
Seems like maybe we should consider having the Cookie Auth Handler clone the principal prior to returning it.

**Comment by NinoFloris** [comment]
Happy to hear that, also perf isn't too impacted if the Cookie Auth Handler only clones it when ShouldRenew is true.
