### ISSUE TITLE
How to use AddGoogle in Controller

### ISSUE THREAD

**Issue by kitirisovgeorgy** [aspnet/Security#1608]
What should I do to use AddGoogle in Controller?
I try inject IAuthenticationSchemeProvider, but it doesn't contains AddGoogle.
If I try to use AddScheme with new AuthenticationScheme() I can't use GoogleHandler.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/AuthSamples/pull/22/files#diff-7f0920a23fc4efd604aaf6e208714c59R28
