### ISSUE TITLE
OIDC add support for mapping all user info

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1609]
OIDC in 1.0 mapped all user info into claims by default. 
https://github.com/aspnet/Security/blob/79a60504a824cf8d9d0af33282bd141deb74fa6c/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L735-L763
This could cause a lot of cookie bloat so in 2.0 it was moved to use the new ClaimActions infrastructure to map only a specific set. The same approach is used for all of the OAuth providers.
https://github.com/aspnet/Security/blob/dde7671c06da64e4a7a290c37ed86e9a9bdd0dd7/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L63-L69

There's been some community feedback that this is hard to use for some scenarios:
https://twitter.com/BrockLAllen/status/951222624792834049
https://leastprivilege.com/2017/11/15/missing-claims-in-the-asp-net-core-2-openid-connect-handler/

We can't re-design this until 3.0 and it's not clear what that would look like. In the meantime we can provide some helpers that cover this scenario.

Proposal:
Add `ClaimActions.MapAllClaims()` that emulates the 1.0 behavior. Also `ClaimActions.MapAllClaimsExcept(params string[] exclusions)` that does the same but excludes certain claim types like Roles (Azure can add way too many).
Make sure there's a rational way to handle duplicate claims.

@BrockAllen @leastprivilege

**Comment by leastprivilege** [comment]
sounds good to me.

Not sure it is worth throwing exceptions for duplicate claims - it's an application concern.

We found that e.g. Azure with "Live ID" login emits two name claims which breaks the handler in federation gateway scenarios depending which external provider is used.

**Comment by brockallen** [comment]
My use case for `MapAllClaimsExcept` is not to reduce the claims in the cookie (since there are other approaches for managing cookie size), but to simply filter out the protocol claims coming from the `id_token` When claims are returned from the userinfo endpoint, typically a client app wants all of those claims (since they asked for them in the first place via the `scope`s requested).

**Comment by Tratcher** [comment]
That's a bit trickier. We don't map the id token claims at our layer, that happens in Identity model during the validation. Hence those DeleteClaim actions that retroactively unmap.

**Comment by leastprivilege** [comment]
Assume we always disable the stupid mapping in the JWT handler...and that's what you should do too when using the handler..

**Comment by Eilon** [comment]
@Tratcher can you try prototyping these and we can get a feel for them?

**Comment by Tratcher** [comment]
Here's a basic starting point. I copied the 1.1 code into a ClaimAction:
```
                o.ClaimActions.Clear();
                o.ClaimActions.Add(new MapAllClaimsAction());
...
        private class MapAllClaimsAction : ClaimAction
        {
            public MapAllClaimsAction() : base(string.Empty, string.Empty)
            {
            }

            public override void Run(JObject userData, ClaimsIdentity identity, string issuer)
            {
                foreach (var claim in identity.Claims)
                {
                    // If this claimType is mapped by the JwtSeurityTokenHandler, then this property will be set
                    var shortClaimTypeName = claim.Properties.ContainsKey(JwtSecurityTokenHandler.ShortClaimTypeProperty) ?
                        claim.Properties[JwtSecurityTokenHandler.ShortClaimTypeProperty] : string.Empty;

                    // checking if claim in the identity (generated from id_token) has the same type as a claim retrieved from userinfo endpoint
                    JToken value;
                    var isClaimIncluded = userData.TryGetValue(claim.Type, out value) || userData.TryGetValue(shortClaimTypeName, out value);

                    // if a same claim exists (matching both type and value) both in id_token identity and userinfo response, remove the json entry from the userinfo response
                    if (isClaimIncluded && claim.Value.Equals(value.ToString(), StringComparison.Ordinal))
                    {
                        if (!userData.Remove(claim.Type))
                        {
                            userData.Remove(shortClaimTypeName);
                        }
                    }
                }

                // adding remaining unique claims from userinfo endpoint to the identity
                foreach (var pair in userData)
                {
                    JToken value;
                    var claimValue = userData.TryGetValue(pair.Key, out value) ? value.ToString() : null;
                    identity.AddClaim(new Claim(pair.Key, claimValue, ClaimValueTypes.String, issuer));
                }
            }
        }
```

Now to look at the Except half.

**Comment by Tratcher** [comment]
Filtering out protocol claims really is a distinct action from mapping user-info claims.
```
                o.ClaimActions.Clear();
                // Note some of these protocol claims also show up in the user info
                o.ClaimActions.Add(new DeleteClaimsAction("aud", "iss", "iat", "nbf", "exp", "aio", "c_hash", "uti"));
                o.ClaimActions.Add(new MapAllClaimsAction());
...
        private class DeleteClaimsAction : ClaimAction
        {
            public DeleteClaimsAction(params string[] deletions) : base("Delete", ClaimValueTypes.String)
            {
                Deletions = deletions ?? throw new ArgumentNullException(nameof(deletions));
            }

            public string[] Deletions { get; }

            public override void Run(JObject userData, ClaimsIdentity identity, string issuer)
            {
                // Filter out protocol claims
                foreach (var deletions in Deletions)
                {
                    foreach (var claim in identity.FindAll(deletions).ToList())
                    {
                        identity.TryRemoveClaim(claim);
                    }
                }
            }
        }
```
