### ISSUE TITLE
Prefer the new encoders over Uri.EscapeDataString

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/Security#161]
There are some call sites in this repo that invoke Uri.EscapeDataString. Instead of calling this static API, the caller should make an effort to use the IUrlEncoder that has been configured by the application developer, as it could have more permissive or restrictive logic than that of Uri.EscapeDataString.

If you have access to an IServiceProvider instance, import the `Microsoft.AspNet.WebUtilities.Encoders` namespace (in the `Microsoft.AspNet.Http.Extensions` package) and call the `IServiceProvider.GetUrlEncoder()` extension method

If you do not have access to an IServiceProvider, you can get a default static singleton instance of an `IUrlEncoder` via the `UrlEncoder.Default` static property (namespace `Microsoft.AspNet.WebUtilities.Encoders`, project `Microsoft.AspNet.WebUtilities`).

**Comment by HaoK** [comment]
87c31c5526edee557997f03c7b13d46cb5d1d893
