### ISSUE TITLE
Add[Provider] Extensions Methods

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Security#1610]
Please consider adding extension methods to the providers that accepts a ConfigurationSection simplifying setup and allowing dynamically adding a provider(s) that has a ConfigurationSection.

**Comment by Tratcher** [comment]
Can you provide some samples showing what it would look like to call these new methods?

**Comment by grahamehorner** [comment]
services.AddAuthenticationProviders(configuration).Events(events=>{});
services.AddFacebook(facebookConfiguration);
services.AddGoogle(googleConfiguration);
services.AddMicrosoftAccount(googleConfiguration).Events(events=>{ })
or possibly

services.AddAuthentication<T>(configurationSection) ?

**Comment by HaoK** [comment]
You can do this today just calling `services.Configure<FacebookOptions>("Facebook", o => facebookConfig.Bind(o))`.

**Comment by HaoK** [comment]
When you are dynamically adding a handler, you can just bind the options explicitly rather than going thru DI

**Comment by grahamehorner** [comment]
@HaoK thanks didn't know about that; so how would you suggest I invoke adding the provider dynamically without explicitly doing an AddFacebook ... ie.  having the provider assembly load and attach to the service collection based on the configuration ?

**Comment by HaoK** [comment]
Well you can do that dynamically similar to how the auth samples does it:

https://github.com/aspnet/AuthSamples/blob/dev/samples/DynamicSchemes/Controllers/AuthController.cs#L28

**Comment by grahamehorner** [comment]
@HaoK thanks I wasn't aware of this; wondering should these samples not be moved into this repo?
I'll give that a whirl and see if it's suitable for my use case;  thanks again

**Comment by grahamehorner** [comment]
Q: at what point does IAuthenticationSchemeProvider get registered with DI ?

**Comment by HaoK** [comment]
It gets registered as part of `AddAuthentication` or `AddAuthenticationCore`
