### ISSUE TITLE
Getting "Unprotect ticket failed" error on different web instances

### ISSUE THREAD

**Issue by jesong** [aspnet/Security#1615]
We are getting ""Unprotect ticket failed" error(Authorization failed) after azure webapp restarted or the request is hitting a different instance of azure webapp for authentication cookies. Is this by design behavior?

**Comment by Tratcher** [comment]
A restart shouldn't be a problem, but to share keys across instances requires additional configuration. 
 https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x

**Comment by jesong** [comment]
That's cool. We can persist to azureblob or redius. Thank you! I'll close the issue
