### ISSUE TITLE
Have Microsoft.AspNetCore.Authentication.OpenIdConnect automatically add the v2.0 endpoint as a valid issuer

### ISSUE THREAD

**Issue by zippy1981** [aspnet/Security#1617]
I have a scenario where a website using msal.js, and therefore the version 2.0 endpoints for auth is talking to a service using ADAL.NET, and therefore the version 1 endpoints.

In the .NET Service I make this work by setting ValidAuthorities and ValidIssuers:

        public static void SetTokenValidationParameters(this IAzureAdOptions options,
            TokenValidationParameters validationParameters)
        {
            validationParameters.ValidAudiences = new[] { "website app id" };
            validationParameters.ValidIssuers = new[] { $"https://sts.windows.net/{options.TenantId}/v2.0" };
        }

Setting `ValidAudiences` is a temporary workaround for MSAL's current inability to generate an access token with a different audience, which I've been told will be addressed. However, the issuer thing will exist as long as there are apps using v1 endpoints talking to v2.0 endpoints. To simplify things, can OpenIdOptions and JwtBearerOptions automatically have their TokenValidationParamaters member populated with  the v2.0 endpoint?

**Comment by Eilon** [comment]
@zippy1981 , it looks like this might be more of an issue with msal.js. We recommend logging an issue at https://github.com/AzureAD/microsoft-authentication-library-for-js for further discussion with the people who work on that project.
