### ISSUE TITLE
Windows authentication under IIS via subfolder

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Security#1618]
Previously on netfx asp.net + mvc I had a working solution with the following setup:
* An app hosted under IIS where only anonymous auth is set for the whole app/site:
![image](https://user-images.githubusercontent.com/1203230/35393412-f051ae92-01f5-11e8-8580-2747b42022dd.png)
* there's a subdir in IIS app/site ("auth") with Windows only auth:
![image](https://user-images.githubusercontent.com/1203230/35393298-a9e3532a-01f5-11e8-8e18-4fdbc599c1ae.png)
* app has an endpoint which goes *through* the "auth" folder:
```csharp
			routes.MapRoute(
				name: "Security.Login.Windows",
				template: "auth/login_windows",
				defaults: new
					{
						controller = "Security",
						action = "LoginWindowsAuth",
					}
				);
```
* the endpoint leads to a webapi controller and inside action method I have a WindowsPrincipal of authenticated user
```csharp
        [AllowAnonymous]
        [HttpPost]
        public HttpResponseMessage LoginWindowsAuth(LoginData loginData)
        {
            var windowsPrincipal = User as WindowsPrincipal;
            var xuser = CreateModelUser(windowsPrincipal);
            setAuthCookie(xuser, response, loginData.PersistentCookie);
            return ControllerContext.Request.CreateResponse(HttpStatusCode.OK, xuser);
        }
```
* inside web.config:
```xml
    <authentication mode="Windows">
      <forms timeout="525600" />
    </authentication>
```

This approach allowed me to support cookie-base auth with Windows auth at the same time. User can choose to enter credentials in a form or click "Login under Windows account" button. In all cases server just returns a normal auth-cookie.

Now I'm trying to migrated this setup onto aspnet core and it's not working.

I keep IIS configuration the same: anonymous auth for site, windows only for "auth" subfolder.
The same routing leads to a controller.
But this time inside the controller `User` property contains a not authenticated principal.
So it seems that WindowsIdentity isn't being passed to the aspnet app. 

What I tried:
* adding:
```csharp
  services.AddAuthentication(IISDefaults.AuthenticationScheme);
```
* adding:
```csharp
  services.Configure<IISOptions>(options => { options.AutomaticAuthentication = true; });
```

If I set Windows only auth for the whole site then indeed I get an authenticated `WindowsPrincipal` in `User`. But it's not what I need as it prevents users from using alternative authentication methods.

But even in this case (Windows auth enabled for whole site) while I have a WindowsPrincipal (from User property) if I try to create a cookie via `HttpContext.SignInAsync` method I'll get an `UnauthorizedAccessException`:
```csharp
await HttpContext.SignInAsync("MySchema", principal,
	new AuthenticationProperties { IsPersistent = true });
```
stackTrace:
```
  at System.Security.Principal.WindowsIdentity.get_AuthenticationType()
   at Microsoft.AspNetCore.Authentication.TicketSerializer.WriteIdentity(BinaryWriter writer, ClaimsIdentity identity)
   at Microsoft.AspNetCore.Authentication.TicketSerializer.Write(BinaryWriter writer, AuthenticationTicket ticket)
   at Microsoft.AspNetCore.Authentication.TicketSerializer.Serialize(AuthenticationTicket ticket)
   at Microsoft.AspNetCore.Authentication.SecureDataFormat`1.Protect(TData data, String purpose)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.<SignInAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.<SignInAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Croc.XFW3.Web.Mvc.SecurityControllerBase.<setAuthTicket>d__22.MoveNext() in <my controller>
```

This's probably another issue and can be worked around by creating a new ClaimsPrincipal from WindowsPrincial manually.

So the major question is how to recreate the past approach with authenticating users by going through a subfolder in IIS with windows auth?

**Comment by Tratcher** [comment]
ASP.NET Core requires the use of sub applications, not sub folders, to honor settings like that in IIS. There's a different way though.

Set up the main application to allow both anonymous and windows auth. Leave Cookies as your default authentication scheme for the app.  On your login controller add an Action that calls `ChallengeAsync(IISDefaults.AuthenticationScheme)` if they select Windows. It will return to the same action once authenticated, then you check the user, issue a cookie, and redirect back to the application.

**Comment by evil-shrike** [comment]
@Tratcher thank you! I got it working. It's even simpler and less hacky then before on netfx.

For the record:

* the site has enabled anonymous *and* Windows authentication
* subfolder ("auth) was removed 
* Controller's action for Windows-auth looks like:
```csharp
[HttpPost]
public async Task<IActionResult> LoginWindowsAuth(LoginData loginData)
{
    bool persistentCookie = Config.Security.PersistentCookie;

    if (!User.Identity.IsAuthenticated)
    {
        await HttpContext.ChallengeAsync(IISDefaults.AuthenticationScheme);
        return StatusCode(Response.StatusCode);
    }

    var windowsPrincipal = (WindowsPrincipal)User;
    // now we have fully authenticated WindowsPrincipal and can create a cookie

    var xuser = CreateModelUser(windowsPrincipal);
    return await loginUser(xuser, windowsPrincipal, persistentCookie);
}
```
