### ISSUE TITLE
Microsoft Account Authentication Fails in IE

### ISSUE THREAD

**Issue by danjohnso** [aspnet/Security#1619]
I am using the Microsoft.AspNetCore.Authentication.MicrosoftAccount 2.0.1 package.

When trying to sign up as a new user with a live account, I get an error page with no helpful error description, similar to this issue: #827 

Steps:
1) Click the Sign In with Microsoft button
2) enter email, next
3) enter password, next
4) Error Screen: 
![image](https://user-images.githubusercontent.com/852995/35403736-4cbf46e2-01c6-11e8-93fb-3d49059a280f.png)

This issue only happens in IE 11 (maybe lower version of IE, unsure).  Chrome, FF, and Edge all worked fine and redirected me to the Microsoft constent screen.  My app does use HTTPS, and it is a public url, no local port like 827.  

If I use another browser to get past the consent screen, I can login with my Micrsofot account in IE with no issue.

**Comment by Tratcher** [comment]
I just tested it and it appears to be working fine. Either way this appears to be an issue with their service rather than the ASP.NET components. @brentschmaltz where should service issues like this be reported?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
