### ISSUE TITLE
[AuthN] Revisit/Rename Authentication sub namespaces?

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#163]
Now that we've are renaming Security -> Authentication, do the current sub namespaces still make sense?

*Microsoft.AspNet.Authentication:*
  **.DataHandler -> [Ticket]Serialization?** Since this looks like the serialization interfaces for tickets
  **.Infrastructure -> [Delete]** - Where the AuthenticationHandler/Middleware base classes live, can we just move to the top level and get rid of Infrastructure namespace which doesn't seem to add much clarity
  **.Notifications -> Notifications** - Has the events/contexts, I think this probably is okay.

cc @lodejard @Tratcher @Praburaj @blowdart

**Comment by blowdart** [comment]
Happy for infrastructure to go. Not sure about .Serialization - where are the other ticket pieces?

**Comment by HaoK** [comment]
@blowdart  Everything involving ticket serialization seems to live in the .DataHandler namespace.
This itself has Encoder and Serializer sub namespaces, along with ISecureDatFormat and 3 implementations of that.  The AuthenticationTicket itself lives in the base namespace

https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNet.Security/DataHandler
See

**Comment by HaoK** [comment]
DataHandler looks to be more than just Ticket Serialization, and generally deals with "Data stuff" Encoding/Serialization/Formatting.  

Maybe we just keep the leaf namespaces and drop the DataHandler entirely?
Authentication.Encoder
Authentication.Serializer
Authentication.DataFormat

But there's only one interface and 3 implementations of in each of these namespaces, so another option is we should just take these 16 files and put them in the root Authentication Namespace, since it looks like ICertificateValidator doesn't have its own namespace today.  

This would make the entire assembly flat with no more sub namespaces at all

**Comment by blowdart** [comment]
I'm ok with flattening altogether.

**Comment by HaoK** [comment]
Removed Infrastructure, left the others alone for now

**Comment by Eilon** [comment]
We'll have to do API reviews and take some of this into account.

**Comment by HaoK** [comment]
Smushed 73d4440a25adb1f3ad72d8c0dd43f2dd6e0262c5
