### ISSUE TITLE
Remove unused dependency IDataProtectionProvider from JwtBearerHandler class

### ISSUE THREAD

**Issue by maximpashuk** [aspnet/Security#1631]
Hi.

JwtBearerHandler class constructor has unused dependency from IDataProtectionProvider interface

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L25

Please remove this dependency from constructor.

**Comment by Tratcher** [comment]
Why do you ask?

Changing/Removing API is breaking and can only be done in major versions.

**Comment by Eilon** [comment]
It would be a breaking change to do this, but we will consider it for 3.0.0.
