### ISSUE TITLE
Q: AuthorizationHandler HttpRequest

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Security#1632]
I'm trying to create a custom policy that evaluates a dynamic URL to see if the user has authorisation to the resource; how do I gain access to the HttpRequest associated with the AuthorizationHandler ? do I need to use DI on the constructor ? also is it possible for a AuthorizationHandler to update the claims/cookie of a user ?

**Comment by HaoK** [comment]
If you are in Mvc, the resource passed in is an mvc context that you can use to get access to HttpContext.  You can always take HttpContextAccessor in the ctor as well

**Comment by HaoK** [comment]
Once you have access to HttpContext, you can always directly call SignIn if you want to update things for the next request.  I guess you can do claims transformation on the current request on httpContext.User in the handler as well.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
