### ISSUE TITLE
Q: How to add custom headers when cookie authentication expires?

### ISSUE THREAD

**Issue by zminic** [aspnet/Security#1633]
Hi,

I have the requirement to add custom headers to the response when authentication ticket expires, to be able to handle situation properly at client side. At server side I have configured ExpireTimeSpan but there is no event in CookieAuthenticationEvents that gets called when ticket expires.

What would be the recommended way to do this?

**Comment by Tratcher** [comment]
Cookie expiration is not a singular event. For non-persistent cookies the client doesn't know it's expired and will keep sending it until it's replaced or deleted by the server. This includes concurrent requests while you are replacing it.

How do you plan to treat expired users differently from anonymous users?

When the cookie auth recognizes a cookie as expired it does not take any action, it lets the request be processed as anonymous. For actions that require auth this will trigger your normal login flow. Did you want to customize that challenge? Look at OnRedirectToLogin. If in OnRedirectToLogin you need to distinguish expired users then you can call `HttpContext.AuthenticateAsync("Cookies")` and inspect the result for this Failure: 
https://github.com/aspnet/Security/blob/c1171cd3ff0de71e6ce3e100059fa0115ebb8ee1/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L143

**Comment by zminic** [comment]
Thanks for the info!

You have pointed me in the right direction, it seems that I forgot to add Authorize attribute to the controller. What confused me is that server returned 400 Bad request and I was expecting 401 and I assumed that in expiration case server returns code 400 and that I need to add additional header to distinguish this situation.

After adding Authorize attribute server started returning 401 so no need to change anything.

Thanks also for the failure inspection technique it might come in handy sometimes.
