### ISSUE TITLE
[2.0.x] Merge WsFed into the patch branch

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1634]
WsFed is getting an out of band 2.0 release targeting 2.0.1 dependencies. Once that's done we should merge it into the 2.0 patch branch for long term servicing.

Considerations:
- Do not add it to any store, metapackage, etc.. This is a ship, exclude package that will only be available from nuget.org until 2.1.
- This depends on a higher but compatible version of IdentityModel (5.2.0) than OpenIdConnect (5.1.4). Do we keep the dependency jagged or raise the other packages? Jagged might be OK as these packages won't be used side-by-side much.
- Update the in-repo dependencies from packages to projects.

@muratg @Eilon

**Comment by Eilon** [comment]
We should keep the dependencies as-is because we don't want to raise the minor version dependency on the 2.0.x stuff that already shipped.
