### ISSUE TITLE
Bring back an equivalent of AuthenticationDescription.Items

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#1641]
In 1.x, the per-middleware `Items` bag was extremely useful to store provider-specific data. Unfortunately, with the huge refactoring introduced in 2.0, this property disappeared.

Suggested API:

```csharp
// Existing type:
public class AuthenticationSchemeBuilder
{
    // Add this new member:
    public IDictionary<string, object> Items { get; }
        = new Dictionary<string, object>(StringComparer.Ordinal);

    // Update this method:
    public AuthenticationScheme Build()
        => new AuthenticationScheme(Name, DisplayName, HandlerType, Items);
}
```

```csharp
// Existing type:
public class AuthenticationScheme
{
    // Update the existing constructor:
    public AuthenticationScheme(string name, string displayName, Type handlerType)
        : this(name, displayName, handlerType, items: null)
    {
    }

    // Add a new constructor:
    public AuthenticationScheme(string name, string displayName, Type handlerType, IDictionary<string, object> items)
    {
        if (name == null)
        {
            throw new ArgumentNullException(nameof(name));
        }
        if (handlerType == null)
        {
            throw new ArgumentNullException(nameof(handlerType));
        }
        if (!typeof(IAuthenticationHandler).IsAssignableFrom(handlerType))
        {
            throw new ArgumentException("handlerType must implement IAuthenticationHandler.");
        }

        Name = name;
        HandlerType = handlerType;
        DisplayName = displayName;
        Items = new ReadOnlyDictionary<string, object>(items ?? new Dictionary<string, object>());
    }

    // Add this new member:
    public IReadOnlyDictionary<string, object> Items { get; }
}
```

@Eilon this is a zero-risk change. Could that be part of 2.1?

/cc @Tratcher

**Comment by PinpointTownes** [comment]
Note: it's an important API for me so I'm fine taking care of the PR if the proposed changes are approved.

**Comment by Eilon** [comment]
@PinpointTownes we'll review in this afternoon's bug triage. Should hear back from us later today.

**Comment by PinpointTownes** [comment]
Optionally and to make this new bag easier to access, new extensions for the OIDC/OAuth2/Twitter methods could be added. E.g:

```csharp
public static AuthenticationBuilder AddOpenIdConnect(
    this AuthenticationBuilder builder,
    string authenticationScheme, string displayName,
    IDictionary<string, object> items,
    Action<OpenIdConnectOptions> configureOptions);

**Comment by HaoK** [comment]
We had this concept around in a few iterations, is there any particular reason you want it on the scheme instead of the AuthenticationSchemeOptions instead?  

That feels like a better place for a scheme specific bag of stuff.

**Comment by HaoK** [comment]
The old stand alone description stuff is odd, the options should be the new home for misc data now

**Comment by HaoK** [comment]
Basically something like a new Items property which you can add whatever you want to in today's existing API...

`AddOpenIdConnect(o => o.Items["Whatever"] = "Something)`

**Comment by PinpointTownes** [comment]
> is there any particular reason you want it on the scheme instead of the AuthenticationSchemeOptions instead?

I need to access the bag via `IAuthenticationSchemeProvider`/`HttpContext.GetAuthenticationSchemesAsync()`. Pretty much like the `DisplayName`.

**Comment by HaoK** [comment]
`IOptionsMonitor.Get<Options>("scheme").Items` the only difference is its an implementation details for our security auth handlers stack instead of something in the core authentication abstractions.

**Comment by PinpointTownes** [comment]
> the only difference is its an implementation details for our security auth handlers stack instead of something in the core authentication abstractions.

No, the difference is that you need to know the scheme with the options approach.

In my scenario, I need to iterate the schemes collection, determine whether the item property I want is associated with the scheme and choose it if it's the right one.

**Comment by HaoK** [comment]
You should still be able to iterate over all of the schemes and look for what you want in the Items of each scheme

**Comment by PinpointTownes** [comment]
We use a multi-tenant aware `IOptionsMonitor`. Retrieving all the tenant options associated with all the schemes would be an extremely expensive operation :sweat_smile:

**Comment by PinpointTownes** [comment]
> The old stand alone description stuff is odd, the options should be the new home for misc data now

Why isn't `DisplayName` part of the options, then?

**Comment by HaoK** [comment]
DisplayName didn't really exist for a long time, templates work against core abstractions and rely on the whole display name thing to determine whether to show login buttons etc.  That whole mess we tried to solve and ended up back with display name :/

**Comment by PinpointTownes** [comment]
> DisplayName didn't really exist for a long time

Hum? This property was present in 1.x and used `AuthenticationDescription.Items` internally.
It's inherited from Katana, where it was introduced... in 2013: https://github.com/aspnet/AspNetKatana/blob/dev/src/Microsoft.Owin/Security/AuthenticationDescription.cs#L53-L60.

**Comment by HaoK** [comment]
I mean in 2.0 Displayname was removed completely we only added this back late in 2.0 to enable the ability to filter the login buttons since we didn't have any other mechanism...

**Comment by HaoK** [comment]
The real answer why DisplayName couldn't live in AuthenticationSchemeOptions is because the host auth handlers don't use the security stack, and they also want to not show up as login buttons.

**Comment by HaoK** [comment]
Ideally I think the app should be responsible for filtering the schemes to determine the proper set to show for their purposes (login or what not).  But we ended up bringing back display name since we couldn't come up with any better alternatives in time

**Comment by PinpointTownes** [comment]
I hear your arguments but the alternative you suggested doesn't fit my scenario.

If you don't want to make this thing a first class citizen, that's fine, I have no problem using `AddScheme` and registering the `PostConfigure` things manually instead of using `AddOpenIdConnect()`/`AddWhatever()` sugars.

**Comment by HaoK** [comment]
So to sum up your underlying scenario, you just want a way to be able to select a particular scheme instance out of all the schemes (potentially across tenants/different options monitor instances).  i.e. scheme.Items["Key"] = "somevalue"

**Comment by PinpointTownes** [comment]
Yup, exactly.

**Comment by HaoK** [comment]
I'm assuming you are using the security stack so all of your schemes are AuthenticatinoSchemeOptions and they are using OptionsMonitor?

**Comment by PinpointTownes** [comment]
Yup, but the providers are not of the same type (e.g we have OIDC and tons of OAuth2 providers, so we can't just use `IOptionsMonitor<OpenIdConnectOptions>` as you suggested).

**Comment by HaoK** [comment]
Is this key basically your tenantId?

**Comment by HaoK** [comment]
Like are you trying to implement a custom Tenant specific IAuthenticationSchemeProvider and are looking for a way to get the list of schemes only for this tenant?

**Comment by HaoK** [comment]
I guess what I'm asking is, since it sounds like this is another lookup key for your scheme, if you aren't reusing scheme names, can you just use this as your scheme name or part of the scheme name?

**Comment by HaoK** [comment]
Can you just add a layer of indirection?  A key => scheme service that you use to keep the scheme names stable but do the id to scheme translation?

**Comment by PinpointTownes** [comment]
Certainly. It's just way more convoluted than what we had in Katana and 1.x.

Not sure why we're arguing so hard for a simple "bag" properties, tho. There's really no con for adopting this change.

**Comment by HaoK** [comment]
I'm not arguing against a bag of properties, just as part of AuthenticationSchemeOptions.  The Options are meant to be the metadata for the schema already

**Comment by PinpointTownes** [comment]
There's no reason to do that when you can have strongly types properties in your scheme options.

**Comment by HaoK** [comment]
What I'm getting at, the reason there's no AuthenticationDescription, is because the AuthenticationSchemeOptions are meant to be used for that purpose.  So for the same reason you want to be able to configure a generic bag of stuff for any scheme, is why you would use a new base.Items...

**Comment by HaoK** [comment]
We haven't finished the work to make it easier to extend handlers/options.  So its not easy today to extend GoogleHandler and just customize the options to add new stuff

**Comment by HaoK** [comment]
You'd have to go through the OAuth base classes probably

**Comment by PinpointTownes** [comment]
> So its not easy today to extend GoogleHandler and just customize the options to add new stuff

I don't want/need to custom the handler. What I need is a **very simple way** to flow properties from the moment you register a scheme and the moment you consume it:

Add an item:
```csharp
services.AddAuthentication(options =>
{
    options.AddScheme("scheme", builder =>
    {
        builder.DisplayName = "My handler";
        builder.HandlerType = typeof(OpenIdConnectHandler);
        builder.Items["id"] = "value";
    });
});
```

Filter the schemes:
```csharp
var scheme = (await provider.GetAllSchemesAsync())
    .Where(scheme => scheme.Items.ContainsKey("id"))
    .Where(scheme => (string) scheme.Items["id"] == "abc")
    .FirstOrDefault();
```

**Comment by HaoK** [comment]
That items data seems like it belongs with the rest of configuring the scheme.  Its not quite as pretty but you can still do something like:

```C#
  AddOpenIdConnect(o => o.Items["id"] = "value");

var scheme = (await provider.GetAllSchemesAsync())
    .Where(scheme => scheme.HandlerType.IsDerivedFrom<AuthenticationHandler<>>()
    .Where(scheme => schemeProvider.GetHandler(scheme)?.Options?.Items["id"] == "abc")
    .FirstOrDefault();
```

**Comment by HaoK** [comment]
What I'm trying to avoid is two sets of metadata, this description/items thing, and the options for the scheme.  The options should really be the single source of truth

**Comment by HaoK** [comment]
This also has the benefit of being dynamic, the scheme data is singleton by default and fairly hard to update, while the items would be going through normal options configuration

**Comment by PinpointTownes** [comment]
Having to manually instantiate a handler just to retrieve its associated options looks particularly gross (and exactly the reason why I think all these handler properties shouldn't have been made public)

> What I'm trying to avoid is two sets of metadata, this description/items thing

Why is that a problem for you? The two seem to be separate things: the items bag is used to store immutable data known at registration time while options can be customized by replacing the monitor to support advanced things like lightweight multi-tenancy.

**Comment by HaoK** [comment]
Why do we need two types of metadata?  The options can just contain all of the relevant metadata for the scheme.  Whether you update it or its immutable shouldn't matter really.  You just configure it consistently via.  `AddXyz(o => o.Foo = "whatever")` everywhere.

**Comment by HaoK** [comment]
Ignore display name, but that's basically the intent behind AuthenticationScheme being only the scheme name and the type.

**Comment by PinpointTownes** [comment]
As usual, we're going in circles: I already explained why instantiating options for handlers you don't need wasn't a good idea from a performance perspective in a multi-tenant scenario (specially when the options are dynamically resolved from the DB).

**Comment by HaoK** [comment]
We chatted a bit about this in triage, we decided not to add any generic bag items back to the scehma as it was an intentional decision to eliminate the extra bag.  

Would something like this work for what you are trying to do?
```C#
   services.AddSingleton<ISchemeMapper, SchemeMapper>();
   services.Configure<SchemeMapperOptions>(o => o.Map("<scheme>", "<key>");
   serivces.AddOIDC("<scheme>", o => { }); 

   var scheme = mapper.Find("<key>").FirstOrDefault();
```

**Comment by PinpointTownes** [comment]
> We chatted a bit about this in triage, we decided not to add any generic bag items back to the scehma as it was an intentional decision to eliminate the extra bag.

So surprising... :trollface:
