### ISSUE TITLE
WsFed confusion between Wreply and CallbackPath

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1645]
When WsFed was ported from Katana it was translation with modest updates, most of the original design and options were preserved. Justin noticed in testing that the modified relationship between CallbackPath and Wreply is confusing and may cause infinite login loops for our customers. Wreply sets the address the identity provider returns to. CallbackPath sets the path the middleware listens on for the reply.

In Katana users could opt to set Wreply and CallbackPath would be derived from that. Neither had a default and if it wasn't set then the middleware would read all form-post requests.

In Core CallbackPath defaults to /signin-wsfed like our other handlers and Wreply has no value. Challenges generate a wreply from the CallbackPath. The confusion comes if someone sets wreply without updating or clearing CallbackPath. The server will reply to a path that the handler isn't listening on, likely resulting in an infinite auth loop or 404.

The motivation for making wreply a public option on WsFed rather than generating the redirect like other providers was that WsFed identity servers were known to be extremely strict on matching the value, to the point of requiring exact casing, etc.. Generating the url from user input may not be sufficient for this check. It's unclear how many customers have run into this mismatch vs those that set wreply because they saw it in a sample.

Not sure what the best path forward here is. We'll see how many users run into it.

**Comment by HaoK** [comment]
Do you really need both of these things, should just standardize on CallbackPath ideally and use that as/derive the wreply?

**Comment by Tratcher** [comment]
> The motivation for making wreply a public option on WsFed rather than generating the redirect like other providers was that WsFed identity servers were known to be extremely strict on matching the value, to the point of requiring exact casing, etc.. Generating the url from user input may not be sufficient for this check. It's unclear how many customers have run into this mismatch vs those that set wreply because they saw it in a sample.

**Comment by HaoK** [comment]
If you have two settings that must be consistent, letting them set one and not the other seems like a huge pit of failure.  There should only be one thing they can set, or a single helper method that sets both.

**Comment by HaoK** [comment]
Seems much better to make it easy to do the right thing, and make it 'hard' only for the people that run into issues with exact casing, require them to override something extra instead of just setting another option

**Comment by Tratcher** [comment]
Closing this for now.  We'll revisit it in the future if we get additional feedback.
