### ISSUE TITLE
The redirect URI is not well-formed. The URI is: 'http://грант.рф:5000/connect/authorize ...

### ISSUE THREAD

**Issue by levnikolaevich** [aspnet/Security#1646]
Guys, hello!

When I use OpenIdConnect I have a problem in a OpenIdConnectHandler (394 line)

So, I use a cyrillic domain http://грант-лев.рф and redirect URI in OpenIdConnectHandler looks incorrect.
`The redirect URI is not well-formed. The URI is: 'http://грант-лев.рф:5000/connect/authorize?client_id=RosgrantService&redirect_uri=http%3A%2F%2Fxn----7sbhbm9amwu.xn--p1ai%3A5002%2Fsignin-oidc&`

Seems, punycode like here `redirect_uri=http%3A%2F%2Fxn----7sbhbm9amwu.xn--p1ai` 
would be good, but I dont know where I can handle it.

Moreover, after this warning I catch an exception in kestrel

`System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x0433    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowInvalidHeaderCharacter(Char ch)    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ValidateHeaderCharacters(String headerCharacters)    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ValidateHeaderCharacters(StringValues headerValues)`
....

So, how can I turn my cyrillic domain to punycode to prevent warning and a Kestrel craching in OpenIdConnectHandler?

Thank you for your advice!

**Comment by Tratcher** [comment]
Interesting catch. @brentschmaltz this may be a bug in CreateAuthenticationRequestUrl.

**Comment by Tratcher** [comment]
@levnikolaevich if you look at the metadata document OIDC downloads for configuration, the host value is not encoded in there is it?

**Comment by levnikolaevich** [comment]
@Tratcher 
Do you mean this metadata?
![image](https://user-images.githubusercontent.com/11368076/36124623-caeaf634-1061-11e8-86cd-2f5e6e6e988c.png)

Client configuration looks like this
![image](https://user-images.githubusercontent.com/11368076/36124690-075519ba-1062-11e8-89ed-3d0e3c71ba80.png)

**Comment by Tratcher** [comment]
Yes. One way of addressing this is changing the metadata. Can you do that?

Also, why did you add ConvertToAscii for your Authority? We should be able to handle that one in Unicode.

**Comment by levnikolaevich** [comment]
@Tratcher , I'm using idsrv4. I think, I don't have a direct access to that code. I've asked their support for help.
I'll let you know if we come up with something.

PS ConvertToAscii was just for a experiment =)

**Comment by Tratcher** [comment]
Ok, the other workaround you can try is setting the Options.Configuration property and manually entering the metadata with encoded urls.

**Comment by Eilon** [comment]
Tagging @leastprivilege re: idsrv4. Any ideas on this? This hostname should probably be punycode encoded in the metadata document itself.

**Comment by leastprivilege** [comment]
I have no idea.

**Comment by Eilon** [comment]
@leastprivilege do you suggest that this bug should be tracked by your org? We couldn't think of anything in ASP.NET Core that would be causing this.

**Comment by levnikolaevich** [comment]
@Eilon , hello! 
Actually, I've found a problem here. https://github.com/IdentityServer/IdentityServer4/blob/ecffbb062485b0656461eba4af5648dc9f45a589/src/IdentityServer4/Hosting/BaseUrlMiddleware.cs#L32

request.Host.Value contains the original host name (http://грант-лев.рф), not a punycode

I resolved my issue the following way
http://amilspage.com/set-identityserver4-url-behind-loadbalancer/

it also helped me with https issue.. =)

Seems, you can close this issue

**Comment by levnikolaevich** [comment]
@Tratcher ,  thank you very much for your help!

**Comment by Tratcher** [comment]
https://github.com/IdentityServer/IdentityServer4/blob/ecffbb062485b0656461eba4af5648dc9f45a589/src/IdentityServer4/Hosting/BaseUrlMiddleware.cs#L31 does look like a bug in idsrv4. It should consider the host encoding when generating addresses.

**Comment by brockallen** [comment]
@levnikolaevich there's a `PublicOrigin` setting you can use for this scenario as well: http://docs.identityserver.io/en/release/reference/options.html#identityserver-options

**Comment by brockallen** [comment]
@Tratcher can you elaborate?

**Comment by Tratcher** [comment]
While the OIDC spec doesn't call out the host encoding specifically, it repeatedly sites RFC 3986 URLs which do not allow unicode. That makes sense as several of these urls values are intended for use in redirect Location headers and must be encoded there.

**Comment by brockallen** [comment]
So you're saying the incoming value for the host could be unicode? I guess I'm confused why ASP.NET Core would allow that in in the first place if it's not a valid host value.

**Comment by PinpointTownes** [comment]
> it repeatedly sites RFC 3986 URLs which do not allow unicode

The spec URI spec is not that restrictive:

> When a non-ASCII registered name represents an internationalized domain name intended for resolution via the DNS, the name must be transformed to the IDNA encoding [RFC3490] prior to name lookup. URI producers should provide these registered names in the IDNA encoding, rather than a percent-encoding, if they wish to maximize interoperability with legacy URI resolvers.

`http://грант.рф:5000/` is a perfectly valid URI representation and I don't see why it couldn't be returned without being encoded first by an OIDC server (tho' it's likely not a good idea since many clients won't be able to deal with IDN URIs).

The real issue is that this address is used as-is by the OIDC handler that blindly calls `HttpResponse.Redirect()` without ensuring the URI can be used in a HTTP header (retrospectively, `Redirect` should probably take a `Uri` instance and rely on `Uri.IdnHost` to compute a safe address).

That said, it's absolutely not a new issue. I'm pretty sure even the Katana OIDC middleware had the same issue (which is why I personally went with the safest option. I.e returning punycode-encoded URIs).

**Comment by Tratcher** [comment]
@brockallen HostString.Value returns the decoded from. HostString.ToString() or ToUriComponent gives the encoded form.

**Comment by brockallen** [comment]
I still think there's an issue here -- I just setup a ASP.NET Core client using `AddOpenIdConnect` and set the `Authority` to `http://грант.рф:5000` and the client side app is not very happy:

```
InvalidOperationException: Invalid non-ASCII or control character in header: 0x0433

Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowInvalidHeaderCharacter(char ch)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ValidateHeaderCharacters(string headerCharacters)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ValidateHeaderCharacters(StringValues headerValues)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseHeaders.SetValueFast(string key, StringValues value)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(string key, StringValues value)
Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse.Redirect(string location, bool permanent)
Microsoft.AspNetCore.Http.HttpResponse.Redirect(string location)
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler+<HandleChallengeAsync>d__20.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationHandler+<ChallengeAsync>d__53.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationService+<ChallengeAsync>d__11.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.ChallengeResult+<ExecuteResultAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeResultAsync>d__19.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
```
