### ISSUE TITLE
Where to store auth access/refresh tokens extracted from Google login?

### ISSUE THREAD

**Issue by chrisdunelm** [aspnet/Security#1647]
Hi,

I'm working on allowing users who have logged in using the Google auth provider (ie using `service.AddAuthentication()`[`.UseGoogle(...)`](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Google/GoogleExtensions.cs#L15)), to be able to directly access the acquired Google credential so API calls into Google services can be made.

It's fairly trivial to actually obtain the access_token and refresh_token within the Google auth process, but it's not clear to me where these should be stored within the ASP.NET Core authentication/authorization/identity systems.
The two tokens need to be stored permanently whilst the user remains logged in; then disposed of on logout. The access_token will need to be updated periodically as it expires and is renewed. These tokens should not ever be available client-side.

Is there a "right" place to store these?
By default they appear in the `Properties` collection of an `AuthenticationResult`, also available using `HttpContext.GetTokenAsync(...)`. Is this the right place to leave these tokens, and update the access_token there? Will the persistence behaviour be correct? 
Sorry for my ignorance, but I'm finding it difficult to understand the correct way to do this!

Thanks.

**Comment by Tratcher** [comment]
Properties is fine for storing tokens for the duration of the session, so long as it doesn't get too big. Here's a sample showing the refresh process:
https://github.com/aspnet/Security/blob/5de25bb11cfb2bf60d05ea2be36e80d86b38d18b/samples/SocialSample/Startup.cs#L304-L343

**Comment by chrisdunelm** [comment]
Great. Thanks very much for the clear code example :)
