### ISSUE TITLE
Cookie SlidingExpiration works unexpectedly different then other SlidingExpirations.

### ISSUE THREAD

**Issue by joshbartley** [aspnet/Security#1648]
I have been tracking down a bug in our client-side log out timer while we have SlidingExpiration = true, and our timeout is set to 20 minutes. The Javascript code will start a countdown from 18 minutes on page load, and at minute 18, notify the user they only have so much time remaining. We caught a large amount of 401 errors on a heartbeat call back when they are still logged in from our client side logging. We added a expiration check to the OnValidatePrincipal to log how long their expiration was set to on the cookie. We found that one cookie was set to 13 minutes, and after 18 minutes they were already logged out. Looking into the issue, I found that the cookie is only reset at half of the expiration, in this case, every 10 minutes. The cookie is set to HttpOnly, which won't allow the Javascript to find out the expiration unless I 

MSDN documentation mentions both resetting for each request and also mentions resetting if  only half the expiration has elapsed.
"slidingExpiration | Optional attribute.Specifies whether sliding expiration is enabled. Sliding expiration resets the active authentication time for a cookie to expire upon each request during a single session."
Reference : https://msdn.microsoft.com/en-us/library/1d3t3c61(vs.71).aspx

While this documentation, which links to the above, states this the other way,
"Note If the Web page is accessed before half of the expiration time passes, the ticket expiration time will not be reset. Fore example, if any Web page is accessed again at 5:04 00:00:00 PM, the cookies and ticket timeout period will not be reset."
Reference :https://support.microsoft.com/en-us/help/910443/understanding-the-forms-authentication-ticket-and-cookie

Looking at the semantics of the phrasing as well, the CacheItemPolicy.SlidingExpiration will refresh a cache items expiration time anytime it is accessed.
https://msdn.microsoft.com/en-us/library/system.runtime.caching.cacheitempolicy.slidingexpiration(v=vs.110).aspx

Recommendation
1. Add an additional property to the CookieAuthenticaitonOption called "SlidingExpirationRefresh" that accepts a TimeSpan, if null, default it to half the timespan of the current cookie expiration.
2. Bold the phrase "This can happen on any request where the current cookie expiration period is more than 50% expired." in the documentation to make it stand out more due to the unique way SlidingExpiration works for cookies versus other parts of the framework.

**Comment by Tratcher** [comment]
Those forms auth links refer to a different implementation in System.Web .NET 4.x. Here's the docs for ASP.NET Core: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationoptions.slidingexpiration?view=aspnetcore-2.0

Note that refreshing the cookie is somewhat expensive, heince delaying the renewal.

**Comment by joshbartley** [comment]
@Tratcher can you elaborate more on the expense of refreshing a cookie?

**Comment by Tratcher** [comment]
1. Re-serialize the refreshed identity
2. Disable caching on the response to prevent caching the cookie

If you refreshed your cookie too often then you'd effectively disable caching for your entire site.

**Comment by joshbartley** [comment]
Would a PR to add when the cookie gets refreshed or add an event to ask if a cookie should be refreshed be better. That way each app owner could decide? In most business apps, caching is disabled on controller actions.

**Comment by Tratcher** [comment]
We'll evaluate this in triage later this week.

**Comment by Eilon** [comment]
Hi, we are not planning to add extensibility or options to this scenario. We reviewed the docs again and we felt they had a good balance between length and readability for most users. The docs are already fairly succinct, so we feel that adding highlighting to the doc wouldn't change much about how it stands out.

**Comment by joshbartley** [comment]
I found the ShouldRenew option on the OnValidatePrincipal event, I will just go that route for my needs.

**Comment by syska** [comment]
@joshbartley 

Did this work for you? Is it just renewed with the information or does this actually call 'DefaultChallengeScheme' set ?

@Tratcher 

I'm not sure what the default value is here? ... I would guess it's false by default ... Could this be added to the documentation for the property? Would this just renew the coockie or redirect to the default challenge scheme?

**Comment by joshbartley** [comment]
I decided to set the cookie to expire in one hour, and set my JS code to check for inactivity in 30 minutes. I also have some extra code to do a Heartbeat back to the server for long running SPA like pages. 

ShouldRenew(true) creates a new cookie with a signed claims which gets pushed to the user through Set-Cookie just like if it went past the half way mark.

**Comment by syska** [comment]
@joshbartley 

Thank for the information.

I guess I will need to add more logging to see what going on.

I can see the ShouldRefresh and the usage of it, it actually still looks at the Tickt and sets the expiration from what time is actually left ... unless I looked the wrong place.

This is still better than right now ... since the users gets redirected to the ADFS and then logged in again as it is right now ... protentially loosing data if it expired doing the "Save" ... 

My cookie was "Session" before, now it expires in 8 hours ... I have really no idea if this solves the issue, since the Ticket is valid for 8 hours ... 

Think I really need to look more into this ... I guess it will also benefit me on the long run knowing exactly what is going on ...
