### ISSUE TITLE
Multiple use of Cookies middleware

### ISSUE THREAD

**Issue by rmacfie** [aspnet/Security#165]
I'm trying to use two different cookie configurations in parallel, but I get an exception when signing in as the second one. Bug or by design?

It works in the Owin.Security.Cookies library.

Startup.cs:

    app.UseCookieAuthentication(options =>
    {
        options.AuthenticationType = "type1";
        options.CookieName = "type1";
    });

    app.UseCookieAuthentication(options =>
    {
        options.AuthenticationType = "type2";
        options.CookieName = "type2";
    });

HomeController.cs:

    public IActionResult Index()
    {
        Response.SignIn(new ClaimsIdentity("type1"));
        Response.SignIn(new ClaimsIdentity("type2"));
        return View();
    }

The second SignIn throws "InvalidOperationException: The following authentication types were not accepted: type2" (bubbles up from Microsoft.AspNet.Http.Core.DefaultHttpResponse.SignIn(...)).

**Comment by HaoK** [comment]
You need to name the cookie options using the namedOptions, currently your second option is getting ignored, UseCookieAuth(options => { }, "type2"), UseCookieAuth(options => { }, "type1")
