### ISSUE TITLE
Add Claims to mvc core application 

### ISSUE THREAD

**Issue by WaedSaleh** [aspnet/Security#1650]
Hi All, 
I am new in mvc core and I am trying to secure my application.
I am using windows authentication and using claim based authorization concept. 
I have a list of claims like Edit, Delete, view and I am trying to use policy-based authentication in my application but it not work, can help me on identity these claims to claim principle and use it.

If there any tutorial that has step by step implementation it would be very helpful as I could not find any detailed tutorial for applying policy authorization.

**Comment by Eilon** [comment]
Hi @WaedSaleh , have you read the documentation at https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies ?

Please have a look at it and let us know where you're having a problem.

**Comment by WaedSaleh** [comment]
Hi @Eilon,
I started with this https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims
  
    services.AddAuthorization(options =>
    {
        options.AddPolicy("EmployeeOnly", policy => policy.RequireClaim("EmployeeNumber"));
    });
I would to know  how to define  EmployeeNumber claim

**Comment by WaedSaleh** [comment]
In another word, I want to know how to add claims to the current identity.

**Comment by Eilon** [comment]
@Tratcher / @blowdart - do we have docs on this topic?

**Comment by Eilon** [comment]
Or a sample?

**Comment by blowdart** [comment]
So with Windows Authentication we generally consider AD the source of truth because it's what it's supposed to be. So in that case you'd either use ClaimsTransformation to modify the identity (and that would run on every request), or have your authz rule go off to your source of additional claims when it runs, and query it for membership or properties.

**Comment by WaedSaleh** [comment]
Thank you! I have another question regarding applying a different type of Authincatin in the same application and configure that based on client need without have multiple application for different login, I need to apply windows auth and single sign-on authentication in same application but one client we use windows auth and another will use saml authentication.

**Comment by blowdart** [comment]
When you say another client what do you mean? Are both non-web based? Generally this sort of thing is doomed to failure.

**Comment by WaedSaleh** [comment]
I mean for our business wh have different clients Client A configure his env to use site minder authentication while client B have windows authentication and currently in our web form application we able to support both auth and control that by web config. I would like to know how we can achieve same goal in mvc core

**Comment by blowdart** [comment]
So different instances of the application? Not one application wanting to do multiple auth types at once?

**Comment by WaedSaleh** [comment]
I want one application with multiple auth types and can use one of them in running time

**Comment by WaedSaleh** [comment]
I mean in the end will have one type of Auth but in development will have one application

**Comment by blowdart** [comment]
OK, so switching at runtime would be up to you, put something in config and react to it as you would anything else, but you can't config it just in config you need to write the code :)

**Comment by WaedSaleh** [comment]
Of course, we need to have a code and then chose the one we need to apply. Anyway, can you help me with implement sso by site minder in mvc core 2

**Comment by blowdart** [comment]
@Tratcher is WS-Fed documented yet?

**Comment by blowdart** [comment]
@WaedSaleh So assuming SiteMinder does WS-FED then there you go. I know SiteMinder had their own plugin too, which will not work. Best to ask SiteMinder at this point.

**Comment by WaedSaleh** [comment]
Thank you All
