### ISSUE TITLE
Automatic Redirect on 401

### ISSUE THREAD

**Issue by dealdiane** [aspnet/Security#1651]
At least in DNX RC1 (yes, I know!), the default behavior if a response with status code 401 using cookie authentication was to redirect to the login path. i.e. Simply returning "Unauthorized" from any mvc action resulted in a redirect to the login page.

Now that we finally have upgraded to 2.0, this seems to be no longer the case. Returning "Unauthorized" would simply return a 401. I couldn't find anywhere where this has been documented.  I get it that this change does make it more predictable but is there a quick built-in way to bring the old behavior back?

**Comment by Tratcher** [comment]
Where are you returning from? MVC?

**Comment by dealdiane** [comment]
Yep, from MVC and from a custom middleware both run after the auth middleware. I'm not overly concerned about the middleware at this stage and would like to try find a workaround for the MVC first.

**Comment by Tratcher** [comment]
From MVC it's recommended you return a Challenge result rather than the status code.
https://github.com/aspnet/Mvc/blob/d40c60d15ba3f9e0fd4854a5f23651148161bc36/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs#L2171

**Comment by dealdiane** [comment]
Yeah, I thought I already tried that but returning challenge from a fresh scaffold works so must be something with the way the middlewares are stacked.
