### ISSUE TITLE
Fetch configuration instead of setting

### ISSUE THREAD

**Issue by johnkors** [aspnet/Security#1652]
More of a question than an issue:

In most registrations, you need to set configuration via the Actions. Is it possible to configure the services without using Actions?

For example JwtBearer. I was hoping it was possible to register something like `IConfigureOptions<JwtBearerOptions>, MyBearerJwtConfigurator>` , and have MyBearerJwtConfigurator fetch the JwtBearerOptions config from somewhere else.

**Comment by Eilon** [comment]
@johnkors you can set a lot of configuration from config files, but it ultimately all goes via the same mechanism of "collaborative configuration," where multiple components and pieces of code can each set the options they care about.

So, you can register your config "thingy" as you have shown, but it can only set the options it cares about (or un-set ones it wants to un-set), but it cannot overwrite the entire options object.

There's some more discussion on this topic here: https://github.com/aspnet/Home/issues/2805

**Comment by johnkors** [comment]
Do you have sample showing this? Not getting this to work. By looks of it, shouldn't the configuration be resolved by the JwtBearerConfigurator here?

```
            builder.Services.AddTransient<IConfigureOptions<JwtBearerOptions>, JwtBearerConfigurator>();
            builder.AddJwtBearer().
```

**Comment by HaoK** [comment]
`services.Configure<JwtBearerOptions>("Bearer", o => config.Bind(o))` is probably what you want.  Auth uses named options where the name == the scheme.

**Comment by johnkors** [comment]
Hmm, no - not really. I'd like to use the `JwtBearerConfigurator` since it has dependencies.

**Comment by HaoK** [comment]
That's fine, your JwtBearerConfigurator just has to implement IConfigureNamedOptions.  You want to register as you are doing as an IConfigureOptions, but it has to implement named options to get picked up by auth.

**Comment by johnkors** [comment]
Ah, wow - that was the missing piece. A bit of a gotcha that you'd need to register it as IConfigureOptions, but implement IConfigureNamedOptions :) 

Neat. Thanks a bunch.

End story:
```
public class JwtBearerConfigurator : IConfigureNamedOptions<JwtBearerOptions>{
    ...
   public JwtBearerConfigurator(IOptions<MyOtherOptions> options)
   {
       _options = options.Value;
   }

   public void Configure(string name, JwtBearerOptions o)
   {
         var authority = new Uri(new Uri(_options.Authority), "oauth2");
         var audience = new Uri(authority, "resources").ToString();
         o.Authority = authority.ToString();
         o.Audience = audience;
   }
...
```
&
```
services.AddTransient<IConfigureOptions<JwtBearerOptions>, JwtBearerConfigurator>();
```
