### ISSUE TITLE
Asp.net Core 2.0 Window Authentication Cors HttP Post method Issues

### ISSUE THREAD

**Issue by bharathpbk** [aspnet/Security#1653]
Hi team,

when i am working with asp.net core 2.0 My HttpPost method not working  with windows authentication.It is Stopping Prelift Calls

**Comment by Eilon** [comment]
@bharathpbk can you share more information about what you are doing? If you can share your app on GitHub that would be great.

**Comment by Eilon** [comment]
Hi, we are planning to work on a sample of how to do CORS + WIndows Auth, which you can track here: https://github.com/aspnet/AuthSamples/issues/15

Unfortunately we don't have any specific guidance on this at this time. Consider asking on another site such as StackOverflow to get further assistance on this sooner.
