### ISSUE TITLE
Where is my Session Data in OpenIdConnectEvents.OnMessageReceived

### ISSUE THREAD

**Issue by ghstahl** [aspnet/Security#1656]
I am working with OpenIdConnectEvents.
First off, HttpContext.Session.SetString and GetString work in my app.
1. **OnRedirectToIdentityProvider**  
```
OnRedirectToIdentityProvider = (context) =>
{
     context.HttpContext.Session.SetString("x-test", "hi there");
// Looking at context.HttpContext.Session.Keys lists a lot of keys...
     return Task.FromResult(0);
}
```

2. **OnMessageReceived**
```
OnMessageReceived = (context) =>
{
    var test = context.HttpContext.Session.GetString("x-test");
   // Looking at context.HttpContext.Session.Keys results in "Enumeration yielded no results"
    return Task.FromResult(0);
}
```

x-test doesn't exist.  Actually nothing is in the Session.
"Enumeration yielded no results"
I think it is reasonable to expect that the context is on par on all On{Whatever} callbacks in the OpenIdConnectEvents object.

**Comment by Tratcher** [comment]
Check Fiddler to see if the session cookie is being sent. This may be an issue with the SameSite setting on your session cookie.

**Comment by ghstahl** [comment]
My Session Cookie is not being sent when I look at the /sigin-google handler.  
/signin-google doesn't have my session cookie, but a following redirect to my app has it.

Can you point me to what Cookie setup I am supposed to have here for making sure that I see my session data at the /signin-google handler?

I have tried the following

```
            //enable session before MVC
            //=========================  
            var sessionOptions = new SessionOptions
            {
                CookieSecure = CookieSecurePolicy.None
// Tried all the combinations that this had as well.
            };
            var deploymentOptions = app.GetService<IOptions<DeploymentOptions>>();
            app.UseSession(sessionOptions);
            // tried this too.   app.UseSession();
            app.UseAuthentication();

            app.UseMvc();
```

**Comment by Tratcher** [comment]
SessionOptions.Cookie.SameSite = SameSiteMode.None (?)

**Comment by ghstahl** [comment]
Nope!

```
            //enable session before MVC
            //=========================  
            var sessionOptions = new SessionOptions
            {
                CookieSecure = CookieSecurePolicy.None
            };
            sessionOptions.Cookie.SameSite = SameSiteMode.None;
            app.UseSession(sessionOptions);

            app.UseAuthentication();

            app.UseMvc();
```
BTW: I solve my real problem another way, which was dropping a cookie in OnRedirectToIdentityProvider and reading it in OnMessageReceived.

However, this session thing has me needing to solve what is going on there.  How the browser deals with cookies when redirecting between different domains knowledge needs focusing up! 

I noticed that the OIDC Handler drops a bunch of cookies before redirecting to the OIDC provider, and are only present when the OIDC Provider(google) redirects back to /signin-in.  When that handler finally does a redirect to some route in my app, those OIDC Handler cookies are not being sent.

**Comment by Tratcher** [comment]
OIDC deletes it's cookies when it's done so that's why you don't see them later.
