### ISSUE TITLE
Example of authentication using SAML by ping federate open token in mvc core 

### ISSUE THREAD

**Issue by WaedSaleh** [aspnet/Security#1657]
Hi All, 
Is there any sample of using SAML 2 by ping federate open token in mvc core

**Comment by brockallen** [comment]
Yes, here: https://github.com/Sustainsys/Saml2/tree/master/Sustainsys.Saml2.AspNetCore2

**Comment by WaedSaleh** [comment]
Thank you @brockallen. Is there example that use open token agent

**Comment by Eilon** [comment]
We don't have plans to add a sample for this. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core` and other tags.
