### ISSUE TITLE
Failed login tracking

### ISSUE THREAD

**Issue by dmcweeney** [aspnet/Security#1659]
Hi,

We have a multi-tenant asp.net core 2 webapp/webapi which is secured with OpenIdConnect/Azure AD and we hit the organizations/v2.0 endpoint for authentication - we only want work accounts.

One thing I would like to do is keep some telemetry data on failed login attempts. For example people that may try and login with Google or MSAs, and what those email addresses are.

I don't see a way to get these email addresses back in the OpenIdConnectEvents events.
Is this possible?

Thanks

Donal

**Comment by Eilon** [comment]
@Tratcher / @brentschmaltz - any ideas on this?

**Comment by Tratcher** [comment]
That restriction is in AAD, correct? For a failed login you would never get any user information sent back to your app. You may not even get an error back, the flow may end on the AAD login page with an error. You'd have to check if AAD provided this kind of telemetry for you.

**Comment by dmcweeney** [comment]
@Tratcher - it does appear that that restriction is in AAD and the flow does end in the AAD login page. I was wondering if I was missing something on if it was possible to get failed login attempts back to the app. I'll follow up with AAD on this... 
Thanks for your help.
