### ISSUE TITLE
how to use pingfederate (OpenToken -agent) for MVC core

### ISSUE THREAD

**Issue by WaedSaleh** [aspnet/Security#1660]
Hi All, 
I used ping federate (OpenToken -agent ) for web form and I want to  use it for MVC core. I want to know how to do that

**Comment by blowdart** [comment]
That would be a question for PingIdentity - Open Token isn't a standard,

PingFederate Server does support OIDC, OAuth and WS-FED/SAML, all of which we have authentication handlers for, which would be a matter of figuring out how to figure that on their servers, and then point the handler configuration to the server, but again, that's a question for PingIdentity.
