### ISSUE TITLE
google authorization failed after  login . in asp.net core 1.1 web api

### ISSUE THREAD

**Issue by arshu1919** [aspnet/Security#1663]
```
{"message":"Specified method is not supported.",
"detail":"   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleSignInAsync(SignInContext context)\r\n
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<SignInAsync>d__66.MoveNext()\r\n
--- End of stack trace from previous location where exception was thrown ---\r\n
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<SignInAsync>d__66.MoveNext()\r\n
--- End of stack trace from previous location where exception was thrown ---\r\n
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n
   at ****
```

---
Edited for formatting by @Eilon

**Comment by Eilon** [comment]
@arshu1919 do you have more info on how you ran into this problem? Can you show what configuration you have in Startup.cs, and any other relevant details?

**Comment by HaoK** [comment]
It looks like you are trying to call SignIn on JwtBearer which isn't supported, you can only SignIn to cookie authentication.

**Comment by arshu1919** [comment]
@Eilon , this is my startup config       // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            #region Identity

            services.AddDbContext<BildarbDbContext>(options =>
            {
                // Configure the context to use Microsoft SQL Server.
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
               
                // Register the entity sets needed by OpenIddict.
                // Note: use the generic overload if you need
                // to replace the default OpenIddict entities.
                // options.UseOpenIddict();
            });

            services.AddIdentity<BildarbUser, BildarbRole>()
                .AddEntityFrameworkStores<BildarbDbContext, int>()
                .AddDefaultTokenProviders();

            services.Configure<IdentityOptions>(config =>
            {
                config.User.RequireUniqueEmail = true;
                config.Password.RequiredLength = 8;
                config.Password.RequireUppercase = false;
                config.Password.RequireDigit = false;
                config.Password.RequireNonAlphanumeric = false;
                 
            });

            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap.Clear();

             
            services.AddAuthentication(options =>
            {
                //options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.SignInScheme = JwtBearerDefaults.AuthenticationScheme;
                //options.SignInScheme = GoogleDefaults.AuthenticationScheme;
                
            });

            // Get options from app settings
            var jwtAppSettingOptions = Configuration.GetSection(nameof(JwtIssuerOptions));

            //// Configure JwtIssuerOptions
            services.Configure<JwtIssuerOptions>(options =>
            {
                options.Issuer = jwtAppSettingOptions[nameof(JwtIssuerOptions.Issuer)];
                options.Audience = jwtAppSettingOptions[nameof(JwtIssuerOptions.Audience)];
                options.SigningCredentials = new SigningCredentials(_signingKey, SecurityAlgorithms.HmacSha256);
            });

 
            #endregion Identity

            
             the rest is mvc config
             
 
           
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
             
              var jwtAppSettingOptions = Configuration.GetSection(nameof(JwtIssuerOptions));
            var tokenValidationParameters = new TokenValidationParameters
            {
                NameClaimType = "name" ,
                RoleClaimType = "role",
                ValidateIssuer = true,
                ValidIssuer = jwtAppSettingOptions[nameof(JwtIssuerOptions.Issuer)],

                ValidateAudience = true,
                ValidAudience = jwtAppSettingOptions[nameof(JwtIssuerOptions.Audience)],

                ValidateIssuerSigningKey = true,
                IssuerSigningKey = _signingKey,

                RequireExpirationTime = true,
                ValidateLifetime = false,

                ClockSkew = TimeSpan.Zero
            };
            app.UseJwtBearerAuthentication(new JwtBearerOptions
            {
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                RequireHttpsMetadata = true,
                SaveToken = true,
                TokenValidationParameters = tokenValidationParameters,
                
                Events = new JwtBearerEvents
                {
                    OnAuthenticationFailed = context =>
                    {
                        if (context.Request.Path.StartsWithSegments("/api")  && context.Response.StatusCode == 404)
                        {
                            context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                        }

                        return Task.CompletedTask;
                    }
                }
            });
            
			 app.UseGoogleAuthentication(new GoogleOptions()
            {
                DisplayName = "Goolge Authentication",
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                AuthenticationScheme = GoogleDefaults.AuthenticationScheme,
                AuthorizationEndpoint = GoogleDefaults.AuthorizationEndpoint,
                TokenEndpoint = GoogleDefaults.TokenEndpoint,
                ClientId = Configuration["Authentication:Google:ClientId"],
                ClientSecret = Configuration["Authentication:Google:ClientSecret"],
                CallbackPath = new PathString("/api/signin-google"),
                Scope = { "openid", "profile", "email" },
                Events = new OAuthEvents()
                {
                    OnRemoteFailure = ctx =>
                    {
                        ctx.Response.Redirect("/api/account/errors/FailureMessage=" + System.Text.Encodings.Web.UrlEncoder.Default.Encode(ctx.Failure.Message));
                        ctx.HandleResponse();
                        return Task.FromResult(0);
                    }
                }

            });

            app.UseFacebookAuthentication(new FacebookOptions()
            {
                DisplayName = "facebook authentication",
                AutomaticChallenge = true,
                AutomaticAuthenticate = true,
                AppId = Configuration["Authentication:Facebook:AppId"],
                AppSecret = Configuration["Authentication:Facebook:AppSecret"],
                CallbackPath = new PathString("/api/signin-facebook"),
                Scope = { "email", "public_profile" }
            });
			
            app.UseIdentity();
            app.UseSession();
            app.UseMvcWithDefaultRoute();
             
        }

**Comment by arshu1919** [comment]
@HaoK   i tried with cookies but ,  
var info = await _signInManager.GetExternalLoginInfoAsync();
info is alway null

**Comment by Tratcher** [comment]
Let me adjust that a bit:
```
        public void ConfigureServices(IServiceCollection services)
        {
            #region Identity

            services.AddDbContext<BildarbDbContext>(options =>
            {
                // Configure the context to use Microsoft SQL Server.
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
               
                // Register the entity sets needed by OpenIddict.
                // Note: use the generic overload if you need
                // to replace the default OpenIddict entities.
                // options.UseOpenIddict();
            });

            services.AddIdentity<BildarbUser, BildarbRole>()
                .AddEntityFrameworkStores<BildarbDbContext, int>()
                .AddDefaultTokenProviders();

            services.Configure<IdentityOptions>(config =>
            {
                config.User.RequireUniqueEmail = true;
                config.Password.RequiredLength = 8;
                config.Password.RequireUppercase = false;
                config.Password.RequireDigit = false;
                config.Password.RequireNonAlphanumeric = false;
                 
            });

            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap.Clear();

            // Get options from app settings
            var jwtAppSettingOptions = Configuration.GetSection(nameof(JwtIssuerOptions));

            //// Configure JwtIssuerOptions
            services.Configure<JwtIssuerOptions>(options =>
            {
                options.Issuer = jwtAppSettingOptions[nameof(JwtIssuerOptions.Issuer)];
                options.Audience = jwtAppSettingOptions[nameof(JwtIssuerOptions.Audience)];
                options.SigningCredentials = new SigningCredentials(_signingKey, SecurityAlgorithms.HmacSha256);
            });

 
            #endregion Identity

            
             the rest is mvc config
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
             
              var jwtAppSettingOptions = Configuration.GetSection(nameof(JwtIssuerOptions));
            var tokenValidationParameters = new TokenValidationParameters
            {
                NameClaimType = "name" ,
                RoleClaimType = "role",
                ValidateIssuer = true,
                ValidIssuer = jwtAppSettingOptions[nameof(JwtIssuerOptions.Issuer)],

                ValidateAudience = true,
                ValidAudience = jwtAppSettingOptions[nameof(JwtIssuerOptions.Audience)],

                ValidateIssuerSigningKey = true,
                IssuerSigningKey = _signingKey,

                RequireExpirationTime = true,
                ValidateLifetime = false,

                ClockSkew = TimeSpan.Zero
            };
            app.UseJwtBearerAuthentication(new JwtBearerOptions
            {
                AutomaticAuthenticate = true,
                AutomaticChallenge = false,
                RequireHttpsMetadata = true,
                SaveToken = true,
                TokenValidationParameters = tokenValidationParameters,
                
                Events = new JwtBearerEvents
                {
                    OnAuthenticationFailed = context =>
                    {
                        if (context.Request.Path.StartsWithSegments("/api")  && context.Response.StatusCode == 404)
                        {
                            context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                        }

                        return Task.CompletedTask;
                    }
                }
            });
            
			 app.UseGoogleAuthentication(new GoogleOptions()
            {
                DisplayName = "Goolge Authentication",
                ClientId = Configuration["Authentication:Google:ClientId"],
                ClientSecret = Configuration["Authentication:Google:ClientSecret"],
                CallbackPath = new PathString("/api/signin-google"),
                Scope = { "openid", "profile", "email" },
                Events = new OAuthEvents()
                {
                    OnRemoteFailure = ctx =>
                    {
                        ctx.Response.Redirect("/api/account/errors/FailureMessage=" + System.Text.Encodings.Web.UrlEncoder.Default.Encode(ctx.Failure.Message));
                        ctx.HandleResponse();
                        return Task.FromResult(0);
                    }
                }

            });

            app.UseFacebookAuthentication(new FacebookOptions()
            {
                DisplayName = "facebook authentication",
                AppId = Configuration["Authentication:Facebook:AppId"],
                AppSecret = Configuration["Authentication:Facebook:AppSecret"],
                CallbackPath = new PathString("/api/signin-facebook"),
                Scope = { "email", "public_profile" }
            });
			
            app.UseIdentity();
            app.UseSession();
            app.UseMvcWithDefaultRoute();
             
        }
```

Side note: Why are your callback paths set to '/api/signin-facebook`?
