### ISSUE TITLE
Problem with AddJwtBearer with two AzureB2C applications

### ISSUE THREAD

**Issue by FredericThibaultOlympus** [aspnet/Security#1664]
We try to migrate from v1 to v2.

We have two Azure subscription. One subscription with some kind of users and the other for other kind of users. We created an application in each subscriptions and use it successfully with .net core 1 by using UseJwtBearerAuthentication twice.

.net core 1 
app.UseJwtBearerAuthentication with options from subscription 1 app

app.UseJwtBearerAuthentication with options from subscription 2 app

Now with .net core 2 I can't find a way to make the same concept works by using AddJwtBearer twice. If I use AddJwtBearer one at a time it works just fine but not if I add both. I tried to specify different scheme name and it's not working.

.net core 2

 services
                .AddAuthentication("Bearer")
                .AddJwtBearer(options => options from subscription 1 app
                .AddJwtBearer(options => options from subscription 2 app

in configure app.UseAuthentication(); -> throw an exception Scheme already exists: Bearer

If I specify Specifing and use two different scheme name, the bearer one is working but not the other...

Thanks,

**Comment by HaoK** [comment]
Yeah so in v2, you can only pick one of the schemes to be the HttpContext.User, you can get the second identity explicitly via HttpContext.AuthenticateAsync("OtherBearerScheme").

**Comment by mkeymolen** [comment]
@HaoK can you please give an example? i have the same issue. In my webapi i need to be able to validate a jwt coming from two different authorities. one from Azure AD and one coming from Azure AD b2c. I use the authorize attribute on my controllers. Do you mean we should work with a policy and validate via HttpContext.AuthenticateAsync("OtherBearerScheme")

**Comment by FredericThibaultOlympus** [comment]
If I understand the answer from HaoK, it's by design that this functionnality doesn't works anymore... it was working in .net std and .net core 1 and not anymore in .net core 2!!! 

I dont understand the HttpContext.AuthenticateAsync("OtherBearerScheme") and how to configure the second application if we can't use AddJwtBearer twice.

**Comment by mkeymolen** [comment]
@FredericThibaultOlympus i think i found out how but not sure. I will test it this weekend and let you know. i think you should do it this way:
```
 // Add JwtBearerAuthentication via Azure AD
services.AddAuthentication(options =>
{
           options.DefaultAuthenticateScheme = JwtCustomBearerSchemes.AZURE_AD_AUTHENTICATION_SCHEME;
}).AddJwtBearer(options =>
            {
                options.Authority = $"https://{azureAdClassicSettings.Issuer}/";
                options.Audience = azureAdClassicSettings.ClientId;
});

// Add JwtBearerAuthentication via Azure AD B2C
services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtCustomBearerSchemes.AZURE_AD_B2_C_AUTHENTICATION_SCHEME;
}).AddJwtBearer(options =>
            {
                options.Authority = $"https://{azureAdB2CSettings.Issuer}/";
                options.Audience = azureAdClassicSettings.ClientId;
            });
```

**Comment by HaoK** [comment]
So @mkeymolen setting default authenticate scheme twice is likely not what you want as last one wins, the first one will be overridden.

Its not clear to me what authorization logic you are looking for, you want to allow access if they have either bearer token?  If that's the case, you can just configure the default policy to challenge both schemes...

```
   services.AddAuthorization(o => o.DefaultPolicy = new AuthorizationBuilder(JwtCustomBearerSchemes.AZURE_AD_AUTHENTICATION_SCHEME, JwtCustomBearerSchemes.AZURE_AD_B2_C_AUTHENTICATION_SCHEME).RequireAuthenticatedUser().Build();
```

This will make `[Authorize]` challenge both schemes and allow access if either token is provided.

cc @scottaddie it might be worth adding this scenario to one of the authorization docs for 2.0 as its the opposite of limiting identity by schemes: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?tabs=aspnetcore2x

Its allowing access with either scheme instead.

**Comment by scottaddie** [comment]
@HaoK I've logged an issue for this. Is this topic big enough to be its own doc?

**Comment by HaoK** [comment]
@scottaddie I don't think it needs its own doc, maybe just a small section/example in something relevant seems good enough.  Generalize the scheme selection topic?  That probably will grow over time especially once 2.1 and the policy scheme feature hits.

**Comment by HaoK** [comment]
I think once we have https://github.com/aspnet/Docs/issues/4055 done, we can maybe find more logical homes for topics.

**Comment by mkeymolen** [comment]
@HaoK thank you first for your excellent help.
what i need is the following:
As Azure AD B2C can't handle client credentials flow yet and i need custom logins for my api as well, i need to accept either **Azure AD classic** tokens as **Azure AD B2C** tokens. Both tokens are coming from a different authority and the Client id (audience) is different as well as you need to register the app in both Azure AD classic and Azure AD B2C

So in short: My api should accept a bearer token coming from a registered app in Azure B2C and also accept a bearer token coming from an app registered in Azure AD classic.  I think that's also what @FredericThibaultOlympus wants to do, but with a difference that he has two different Azure B2C directories. In the Authorization attribute you should be able to specify a role (which is included in the claims)

So on top of what you suggested, how can i specify those to authorities and audiences?
twice with
`.AddJwtBearer(options =>`  ?

**Comment by HaoK** [comment]
Call `AddJwtBearer` twice, use the overload that takes the scheme name as first argument.

**Comment by mkeymolen** [comment]
@HaoK This is what i implemented so far:
```
var customPolicyBuilder = new AuthorizationPolicyBuilder(JwtCustomBearerSchemes.AZURE_AD_B2_C_AUTHENTICATION_SCHEME, JwtCustomBearerSchemes.AZURE_AD_AUTHENTICATION_SCHEME);
// TODO don't forget to check for correct issuer in customPolicy
customPolicyBuilder.AddRequirements(new CustomPolicyRequirement());
var customPolicy = customPolicyBuilder.RequireAuthenticatedUser().Build();
services.AddAuthorization(o =>
{
       o.DefaultPolicy = customPolicy;
});

// Add JwtBearerAuthentication via Azure AD
services.AddAuthentication(options =>
{
                options.DefaultAuthenticateScheme = JwtCustomBearerSchemes.AZURE_AD_AUTHENTICATION_SCHEME;
})
// add Azure AD B2C settings
.AddJwtBearer(JwtCustomBearerSchemes.AZURE_AD_AUTHENTICATION_SCHEME, options =>
{
                options.Authority = authenticationSettings.AzureAdB2C.Authority;
                options.Audience = authenticationSettings.AzureAdB2C.ClientId;
// add Azure AD Classic settings
}).AddJwtBearer(JwtCustomBearerSchemes.AZURE_AD_B2_C_AUTHENTICATION_SCHEME, options =>
{
                options.Authority = $"https://{authenticationSettings.AzureAdClassic.Issuer}/";
                options.Audience = authenticationSettings.AzureAdClassic.ClientId;
});
```
If i add a breakpoint in my custompolicy requirement, i get my User identity filled in and he is authenticated. Is there now a way to reuse the Authorize attribute with a parameter i can check in my custompolicy requirement without using the policy overload. Because that would mean i need to add all the values i fill in as a parameter in my attribute (e.g Authorize("read:companies")) as a different policy?

**Comment by FredericThibaultOlympus** [comment]
Hi and thanks to everyone invove in this thread. I tries @HaoK code and unfortunatly I can't make it  works. Whan the first bearer is called Bearer the it goes to the OnTokenValidated but I receive a 403 in response from the controller with a plain [Authorize] attribute. When I test the bearer1 nothing works, I receive a 500.

`
services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtCustomBearerSchemes.AZURE_AD_AUTHENTICATION_SCHEME; // Bearer
})

.AddJwtBearer(JwtCustomBearerSchemes.AZURE_AD_AUTHENTICATION_SCHEME, options =>
{
    options.Authority = string.Format(
                                this.configuration[Constants.Configuration.AUTHENTICATION_AZURE_AD_AADINSTANCE],
                                this.configuration[Constants.Configuration.AUTHENTICATION_AZURE_AD_TENANT],
                                this.configuration[Constants.Configuration.AUTHENTICATION_AZURE_AD_POLICY]);

    options.Audience = this.configuration[Constants.Configuration.AUTHENTICATION_AZURE_AD_CLIENTID];

    options.Events = new JwtBearerEvents()
    {
        OnTokenValidated = async (context) =>
        {
            // Do something 
        }
    };

})
            
.AddJwtBearer(JwtCustomBearerSchemes.AZURE_AD_B2_C_AUTHENTICATION_SCHEME, options =>  // Bearer1
{
    options.Authority = string.Format(
                            this.configuration[Constants.Configuration.AUTHENTICATION_AZURE_AD_B2_C_AADINSTANCE],
                            this.configuration[Constants.Configuration.AUTHENTICATION_AZURE_AD_B2_C_TENANT],
                            this.configuration[Constants.Configuration.AUTHENTICATION_AZURE_AD_B2_C_POLICY]);

    options.Audience = this.configuration[Constants.Configuration.AUTHENTICATION_AZURE_AD_B2_C_CLIENTID];

    options.Events = new JwtBearerEvents()
    {
        OnTokenValidated = async (context) =>
        {
            // Do something 
        }
    };
});
`

**Comment by mkeymolen** [comment]
@FredericThibaultOlympus You forgot to change the default policy to take the two schemes into account.

```csharp 
var customPolicyBuilder = new AuthorizationPolicyBuilder(JwtCustomBearerSchemes.AZURE_AD_B2C_AUTHENTICATION_SCHEME, JwtCustomBearerSchemes.AZURE_AD_CLASSIC_AUTHENTICATION_SCHEME);
var defaultPolicy = customPolicyBuilder.RequireAuthenticatedUser().Build();
```

And what are the values of your authorities? For b2c and AD classic they are different.
for AD classic it should be in the form: https://login.microsoftonline.com/{tenantid}
for AD B2C : https://login.microsoftonline.com/tfp/{tenantid}/{DefaultPolicy}/v2.0

**Comment by Tratcher** [comment]
Remove DefaultAuthenticateScheme, you don't need that when you have the AuthorizationPolicyBuilder that specifies both schemes.

**Comment by torhovland** [comment]
In case this helps anybody, I am successfully supporting two different JwtBearer providers in my app. I set them up like this:

```
.AddJwtBearer("IdSrv2Bearer", options =>
   ...

.AddJwtBearer("IdSrv1Bearer", options =>
   ...
```

Then my controllers have this attribute on them:

```
[Authorize(AuthenticationSchemes = "IdSrv2Bearer,IdSrv1Bearer")]
```
