### ISSUE TITLE
Using Google Authentication with other Google services

### ISSUE THREAD

**Issue by strich** [aspnet/Security#1667]
I'm writing a small webapp in .NET Core 2 focused around displaying custom reports out of a users Google Analytics account. I have added `Microsoft.AspNetCore.Authentication.Google` as the primary way to register and log into the website.

I'd now like to use the `Google.Apis.AnalyticsReporting.v4` package to pull in data from that users connected Analytics accounts.

Is this possible?

**Comment by strich** [comment]
In additional to this I've been trying to simply access the tokens required to do a straight REST/POST call maybe:
```
// In Startup
services.AddAuthentication().AddGoogle(googleOptions =>
            {
                googleOptions.ClientId = Configuration["Authentication:Google:ClientId"];
                googleOptions.ClientSecret = Configuration["Authentication:Google:ClientSecret"];
                googleOptions.SaveTokens = true;
                googleOptions.Scope.Add("https://www.googleapis.com/auth/analytics");
            });

//Elsewhere:
var accessToken = await HttpContext.GetTokenAsync("Google", "access_token");
var refreshToken = await HttpContext.GetTokenAsync("Google", "refresh_token");
```

These aren't returning anything either. Am I doing something wrong?

**Comment by Eilon** [comment]
Hi, please check out this sample that shows how to store the access tokens so that you can later call APIs with that token: https://github.com/aspnet/AuthSamples/tree/dev/samples/Identity.ExternalClaims

**Comment by strich** [comment]
What does `googleOptions.SaveTokens = true;` do, if anything? Seems to me it doesn't do anything at all?

**Comment by Eilon** [comment]
The claims are being retrieved from the wrong identity. The code you show above is trying to get Google's claims (and tokens) from the local ASP.NET identity. Please review the sample we linked to in order to see some of the differences.

cc @Tratcher @HaoK

**Comment by strich** [comment]
I downloaded a setup the ExternalClaims sample project and can see the access_token being displayed. However I don't see the refresh_token after setting accessType to "offline" in the auth options. Are there additional steps required?

**Comment by Eilon** [comment]
@Tratcher / @HaoK / @javiercn - any idea on the refresh token?

**Comment by HaoK** [comment]
Did you set the prompt?
```
o.AuthorizationEndpoint += "?prompt=consent"; // Hack so we always get a refresh token, it only comes on the first authorization response 
```

**Comment by strich** [comment]
That just forces the consent every time they login? I'm trying this against new users so shouldn't be relevant right?

**Comment by javiercn** [comment]
@strich Yeah, that forces consent, if the underlying protocol is Open ID Connect, explicit consent might be required for the server to send you back a refresh token. See http://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

**Comment by strich** [comment]
Hrm okay. But we're talking about first party auth here - Google, etc.
