### ISSUE TITLE
Google Authentication service does not provide access & refresh tokens

### ISSUE THREAD

**Issue by strich** [aspnet/Security#1668]
In relation to my usecase in issue #1667, I need to be able to use the access and refresh tokens available to users who have already logged in with Google auth on my website. However it does not work as expected - All the various methods I am aware of to get the `access_token` and `refresh_token` return an empty string.

Startup.cs code:
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

    services.AddIdentity<ApplicationUser, IdentityRole>(o =>
    {
        // configure identity options
        o.Password.RequireDigit = false;
        o.Password.RequireLowercase = false;
        o.Password.RequireUppercase = false;
        o.Password.RequireNonAlphanumeric = false;
        o.Password.RequiredLength = 6;
    })
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders();

    services.AddAuthentication()
    .AddGoogle(googleOptions =>
    {
        googleOptions.ClientId = Configuration["Authentication:Google:ClientId"];
        googleOptions.ClientSecret = Configuration["Authentication:Google:ClientSecret"];
        googleOptions.SaveTokens = true;
        googleOptions.AccessType = "offline"; // Gets a refresh token
        googleOptions.Scope.Add("https://www.googleapis.com/auth/analytics");
    });

    services.AddMvc(o =>
    {
        o.Filters.Add(new BaseLayoutActionFilter());
    });

    // Add application services.
    services.AddTransient<ApplicationUserManager>();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.AddConsole(Configuration.GetSection("Logging"));
    loggerFactory.AddDebug();

    if (env.IsDevelopment())
    {
        app.UseBrowserLink();
        app.UseDeveloperExceptionPage();
        app.UseDatabaseErrorPage();
    }
    else
    {
        app.UseExceptionHandler("/Home/Error");
    }

    app.UseStaticFiles();

    app.UseAuthentication();

    app.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "default",
            template: "{controller=Home}/{action=Index}/{id?}");
    });
}
```

On the home page of webapp I try to grab and display the tokens via:
```c#
var accessToken = await HttpContext.GetTokenAsync("Google", "access_token");
var refreshToken = await HttpContext.GetTokenAsync("Google", "refresh_token");
```

**Comment by strich** [comment]
I have found that if I login an account for the first time I will get an `access_token`. But if I logout and log back in, I get nothing.

I am finding that `var info = await _signInManager.GetExternalLoginInfoAsync();` returns null after the first login too. Is there something I am missing?

**Comment by HaoK** [comment]
Take a look at https://github.com/aspnet/AuthSamples/tree/dev/samples/Identity.ExternalClaims which does something similar, basically identity is doing the main authentication and google is only used temporarily to associate the appropriate identity user, you will need to deal with the google tokens in a way like the sample does to access them.

**Comment by strich** [comment]
Thanks for the assistance @HaoK - I'll take a look at these samples tonight to tweak to fit. As a followup question: The intention is that I will be running google actions on behalf of the user when they aren't active on the website at the time. With the access and refresh tokens can I retain access to their account permanently (Assuming they don't do anything to block it later)?

**Comment by Tratcher** [comment]
Yes, that's what they're for. You'd need to store those tokens in the user database so you have access to them when the user isn't around.

**Comment by strich** [comment]
Two things I'm struggling with right now: 
1. Using the same StartUp config as @HaoK provided example I am finding that the `info.AuthenticationTokens` doesn't provide a `refresh_token`. I can see the `access_token` though.
2. I'm not sure where to actually capture and record them to my db? I had thought `ExternalLoginCallback`, but it is an anonymous function that has no access to the logged in User. Where should I be recording them to the db in a webapp very similar to the examples provided?

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Security/blob/21acbf06e88a5f649e90b4a458b4341355791ac4/samples/SocialSample/Startup.cs#L99

**Comment by strich** [comment]
Worked a charm, thanks @Tratcher! Would you be able to point me in the right direction for point 2 at all?

**Comment by strich** [comment]
Okay nevermind I sorted it out. Turns out it is actually saved to db automatically. I could retrieve with:

```
var userFromManager = await _userManager.GetUserAsync(User);
            var externalAccessToken = await _userManager.GetAuthenticationTokenAsync(userFromManager, "Google", "access_token");
            var externalRefreshToken = await _userManager.GetAuthenticationTokenAsync(userFromManager, "Google", "refresh_token");
```

**Comment by strich** [comment]
@Tratcher althought that `AuthorizationEndpoint ` 'hack' works really well, it does also prompt the user for access to the requested scopes every time they login. Is there a nicer way to refresh the `refresh_token` only when the existing one is null or invalid?

**Comment by Tratcher** [comment]
That prompt hack you only need for new users. You could use the OnRedirectToAuthorizationEndpoint event to add it selectively. E.g. ask users to re-login through a special page if you don't have a valid refresh token for them.

**Comment by strich** [comment]
I'm not really sure how to access things like db and user properties in those event contexts though. I assume you mean something like this?

```c#
googleOptions.Events.OnRedirectToAuthorizationEndpoint = ctx =>
{
    // Get user -- ? _userManager.GetUserAsync(ctx.HttpContext.User)?
    // Get database context
    // Check if user exists OR user has no refresh token ( _userManager.GetAuthenticationTokenAsync(user, "Google", "access_token");)                    

    // If we need a refresh token:
    ctx.Response.Redirect(ctx.RedirectUri + "?prompt=consent");
    // Else
    // ?

    return Task.CompletedTask;
};
```
Are you able to help me fill in the gaps?

**Comment by Tratcher** [comment]
The user isn't usually logged in when OnRedirectToAuthorizationEndpoint is executed. I meant that if in your application you try to perform an action that requires a access/refresh token and you don't have one, then you can request that the user log out and log back in through a specific page that adds the prompt parameter. You can flow information from your account controller down into the events either by putting into HttpContext.Items or in the AuthenticationProperties collection passed to Challenge.

**Comment by strich** [comment]
@Tratcher thanks. I've had a go but I'm not sure I'm using the right calls. Could you mock up how to add something to `AuthenticationProperties` and then pass it to a challenge/redirect?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
