### ISSUE TITLE
Would it possible to run web project that is targeting 4.6(mvc core)  while business layer projects targeting 4.5 ? 

### ISSUE THREAD

**Issue by WaedSaleh** [aspnet/Security#1669]

**Comment by Eilon** [comment]
@WaedSaleh yes in general that should work just fine. Well, the web app might need to target a slightly newer .NET Framework, such as .NET Framework 4.6.1, because ASP.NET Core 2 requires .NET Standard 2.

Please let us know if you're having a specific problem, and we can re-open this question.

**Comment by WaedSaleh** [comment]
@Eilon Actually I am using 4.6.1 for mvc core, but my business layer class library was built using 4.5 and I need to read info from app settings in MVC core from the business layer which uses 4.5, would this be possible

**Comment by Eilon** [comment]
@WaedSaleh that should work just fine. If you try it and run into problems please let us know details and we can investigate.

**Comment by WaedSaleh** [comment]
Hi @Eilon, yes it works but for example, if I have web project as Mvc core targeting 4.6.2 and in-class library 4.5 I have this logic WebConfigurationManager.GetSection("Stage.DataAccess"), the value that return is null, so how I can read app setting in web project from the class library.

FYI, that class library is not called directly from the web application.

**Comment by Eilon** [comment]
@WaedSaleh generally the app has to pass in some context info into the library. There isn't a general way for a library to read config from the app because there's no static way to get to it in .NET Core.

**Comment by Eilon** [comment]
@WaedSaleh for ASP.NET Core, there's no difference for this between .NET Core and .NET Framework.
