### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by zulander1** [aspnet/Security#1670]
Hello,

i am having a redirect loop, the problem is that the i am redirecting the user if user has no roles...
it is going to a page with [Authorize()] attribute, the problem is that the ClaimPricipal is empty, hence, it is trying to Authenticate. How do i pass the ClaimPricipal  a long ?

```c#
            public void Configure(string name, OpenIdConnectOptions options)
            {
				//other stuff
                options.Events = new OpenIdConnectEvents
                {
                    OnTokenValidated = otv =>
                  {
						
                   //Some role validation logic...
						
                      if (accounts.RoleId == (int)RolesEnum.None)
                      {
                          otv.Response.Redirect("/Home/NoRoles");
                          otv.HandleResponse();
                      }

                      return Task.CompletedTask;
                  }
                };
            }
```

**Comment by blowdart** [comment]
What is your authentication mechanism? Where are you creating your ClaimsPrincipal? How are you attaching it to the request? How is it persisted?

**Comment by zulander1** [comment]
There you go:

What is your authentication mechanism: SSO with Auzure, the default functions generated by visual studio for Azure Authentication.

Where are you creating your ClaimsPrincipal: I am not creating the ClaimsPrincipal, I am just addng a role using ClaimTypes.Role inside the created class (AzureAdAuthenticationBuilderExtensions)

How are you attaching it to the request: I am not, because i am not creating it ! 

How is it persisted: I don't understand what you mean.

of couse removing redirect work as expected !

**Comment by blowdart** [comment]
OK, so what you're seeing isn't unexpected. You need to do some serious work to get Azure AD to send roles, so you're redirecting to something that probably needs authorization, and back into the loop you go.

**Comment by zulander1** [comment]
Yes, i understand it's not expected. We are not using Azure roles, we are using local from the DB. The user gets authenticated, which is ok. The only problem is when redirect using Response.Redirect("/Home/NoRoles"); and .HandleResponse(); The ClaimsPrincipals is empty should the ClaimsPrincipals be passed ?

**Comment by blowdart** [comment]
I believe you're abandoning the flow at that point, so you're bypassing the pieces that actually setup the ClaimsPrincipal see https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L551

**Comment by zulander1** [comment]
Ahh yes i see! Thank you so much ! changed event handling to OnTicketReceived

**Comment by zulander1** [comment]
I spoke too fast! I see, how do i get the flow to complete and then redirect, do i need to write a middleware or i can use an event from OpenIdConnect ?

**Comment by zulander1** [comment]
Fixed it by using AccessDeniedPath insted !
