### ISSUE TITLE
WsFederation endless loop when logging in

### ISSUE THREAD

**Issue by mshindal** [aspnet/Security#1671]
I posted my Startup.cs [here](https://gist.github.com/mshindal/02e4bde492b3f14996a801220214b249).

If you need the Fiddler log, let me know of an email address I can send it to privately.

**Comment by Tratcher** [comment]
`options.Wreply = "https://localhost:44363/foobar";` what is /foobar? Your site application path? I suggest not setting Wreply, CallbackPath is better and it defaults to /signin-wsfed and that's what you should register with your identity provider. 

See https://github.com/aspnet/Security/issues/1645

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
