### ISSUE TITLE
[AllowAnonymous] vs [Authorize] vs inheritance

### ISSUE THREAD

**Issue by suszig** [aspnet/Security#1672]
Maybe this is not an issue, maybe it is by design

sample "code" (just the idea):
```
[Authorize]
public class MyControllerBase : Controller
```
```
[Route("test")]
public class MyController : MyControllerBase 
{
 [AllowAnonymous]
 [HttpPost]
 public IActionResult Action()
 { return Ok(); }
}
```
Current behavior - 401 Unauthorized when calling the Action()
Expected behavior - Method is marked as anonymous an available to call

**Comment by Eilon** [comment]
@HaoK / @rynowak - seems related to the issue about authorization composition - what's the story here?

**Comment by rynowak** [comment]
I agree with the expectations from @suszig - `[Authorize]` should be inherited but ignored. `[AllowAnonymous]` doesn't compose - if it's present at any scope it **always** wins.

**Comment by javiercn** [comment]
Allow anonymous should always bypass as @rynowak said.
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Authorization/AuthorizeFilter.cs#L192

@HaoK Are you taking a look at this?

**Comment by HaoK** [comment]
Sure I can take a look

**Comment by HaoK** [comment]
@suszig do you have a repro for the behavior you describe?  Are you perhaps mixing bearer + cookies?

 I tried this on a new template project and was able to hit the action:
```
    [Authorize]
    public class MyControllerBase : Controller { }

    public class HomeController : MyControllerBase
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
```

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
