### ISSUE TITLE
Improve the Error Msg When Forgetting to Register IAuthorizationHandler

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Security#1676]
I forgot to register my `IAuthorizationHandler` and that caused this error message:

> AuthenticationScheme: Bearer was forbidden 

Can this be **improved** to say something like this: "Hey, there are **no handler(s)** for your policy"

---

Custom policy-based authorization documentation -> [Handler Registration](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies#handler-registration)

```c#
services.AddSingleton<IAuthorizationHandler, YourHandlerClass>();
```
Reference: [#769](https://github.com/aspnet/Security/issues/769#issuecomment-349717842)

**Comment by HaoK** [comment]
There's no requirement that every requirement has to have a handler, its perfectly valid to have a single handler that is responsible for all requirements.

**Comment by spottedmahn** [comment]
Hi @HaoK - right, but if I **forget** to **register** that single handler I don't get a useful error/exception.

**Comment by HaoK** [comment]
While we could add an exception for when no handlers are registered at all, that wouldn't be that useful since Authorization registers handlers by default for some of the built in requirements...

**Comment by Eilon** [comment]
@HaoK can you dup this against our bug that is tracking providing better experiences for failures? We should check, for example, that we have ample logging stating what we found or tried.

**Comment by HaoK** [comment]
We are tracking improving the general error experience when authorization fails as part of  https://github.com/aspnet/Security/issues/1359 so once that work is done, the experience when you forget to register a handle should be better.  There will most likely be an msg logged somewhere saying something to the effect that "Requirement Xyz was not met, so authorization failed."

**Comment by spottedmahn** [comment]
I monkeyed around w/ `Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync` to get requirements for this auth call, that don't have handlers registered.

```csharp
public async Task<AuthorizationResult> AuthorizeAsync(ClaimsPrincipal user, object resource, IEnumerable<IAuthorizationRequirement> requirements)
{
	...
	
	var authContext = _contextFactory.CreateContext(requirements, user, resource);
	var handlers = await _handlers.GetHandlersAsync(authContext);

	var requirementsForRegisteredHandlers = new List<Type>();

	foreach (var handler in handlers)
	{
		var type = handler.GetType();
		var baseType = type.BaseType;
		if (baseType.GenericTypeArguments.Length > 0)
		{
			var genericType = baseType.GenericTypeArguments[0];
			requirementsForRegisteredHandlers.Add(genericType);
		}
	}

	var requirementTypes = requirements.Select(h => h.GetType()).ToList();

	var requirementTypesWithoutRegisteredHandlers = requirementTypes.Except(requirementsForRegisteredHandlers).ToList();
	
        //if requirementTypesWithoutRegisteredHandlers has any entries that is a problem!
	...
}
```
[Source link](https://github.com/spottedmahn/Security/blob/9a58b352fac5a664d449c254de217637779829aa/src/Microsoft.AspNetCore.Authorization/DefaultAuthorizationService.cs#L107)

```csharp
[Fact]
public async Task CustomReqWithHandlerSucceeds()
{
	// Arrange
	var authorizationService = BuildAuthorizationService(services =>
	{
		//services.AddTransient<IAuthorizationHandler, CustomHandler>();
		services.AddAuthorization(options =>
		{
			options.AddPolicy("Custom", policy => policy.Requirements.Add(new CustomRequirement()));
		});
	});
	var user = new ClaimsPrincipal();

	// Act
	var allowed = await authorizationService.AuthorizeAsync(user, null, "Custom");

	// Assert
	Assert.True(allowed.Succeeded);
}
```
[Source link](https://github.com/spottedmahn/Security/blob/9a58b352fac5a664d449c254de217637779829aa/test/Microsoft.AspNetCore.Authorization.Test/DefaultAuthorizationServiceTests.cs#L697)

`requirementTypesWithoutRegisteredHandlers` will have `Microsoft.AspNetCore.Authorization.Test.DefaultAuthorizationServiceTests+CustomRequirement` in it.

**Comment by HaoK** [comment]
Its not an error to not have handlers for a requirement.  IAuthorzationHandler is not generic, its only the default implementation we provide that makes it easy to target a single requirement.  Its generally not a rule that every requirement has to have a `AuthenticationHandler<TReq>`

**Comment by spottedmahn** [comment]
Interesting, thanks @HaoK!

Hopefully, you guys can figure out an elegant way to provide us quick feedback when we forget to register a handler!

**Comment by HaoK** [comment]
That's not likely to ever happen, the best we'll be able to do is to give you which requirement wasn't met.  Which should be a reasonable hint to what's going on

**Comment by spottedmahn** [comment]
Hi @HaoK - copy that.  Hopefully, this plants the seed and a brilliant ⚡ idea 💡 is realized w/ time ⌚.

The more our software can tell us where the problems lies, the better!

Thanks for all your input/feedback! 🔥
