### ISSUE TITLE
OpenIdConnectHandler returns "Message contains error: <invalid_request>"

### ISSUE THREAD

**Issue by joaco-espinosa** [aspnet/Security#1677]
Hello,

I'm experiencing an issue hosting my Identity server behind load balancer.
I have one instance (planning on adding more) and I always get an error message on the client even though the login is successful and the token is correctly generated on the server.

Could you please help me narrow down the problem? I'm not sure if this is a client side problem or a server side one.

Client message:
```Message contains error: 'invalid_request', error_description: 'error_description is null', error_uri: 'error_uri is null'.```

Logs from server:
```"Token Issued Success" (2000) Detailed Event Information: "{ RemoteIpAddress: XXXX, ClientId: IdProviderWebClient, ClientName: Test Web Client - Authorization Code Flow, RedirectUri: http://localhost:5002/signin-oidc, Endpoint: Authorize, SubjectId: <GUID>, GrantType: authorization_code, Tokens: [ { TokenType: code, TokenValue: ****8b07 }]}"```

Stack trace:
```
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<RedeemAuthorizationCodeAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRemoteAuthenticateAsync>d__21.MoveNext()
```

Client startup:
```
public void ConfigureServices(IServiceCollection services)
{
	JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

	services.AddAuthentication(o =>
	{
		o.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
		o.DefaultChallengeScheme = "oidc";
	})
	.AddCookie(CookieAuthenticationDefaults.AuthenticationScheme)
	.AddOpenIdConnect("oidc", o =>
	{
		o.Authority = Configuration["Authority"];
		o.ClientId = Configuration["OpenIdConnectOptions:ClientId"];
		o.ClientSecret = Configuration["OpenIdConnectOptions:ClientSecret"];
		o.GetClaimsFromUserInfoEndpoint = Convert.ToBoolean(Configuration["OpenIdConnectOptions:GetClaimsFromUserInfoEndpoint"]);
		o.RequireHttpsMetadata = Convert.ToBoolean(Configuration["OpenIdConnectOptions:RequireHttpsMetadata"]);
		o.ResponseType = Configuration["OpenIdConnectOptions:ResponseType"];
		o.SaveTokens = Convert.ToBoolean(Configuration["OpenIdConnectOptions:SaveTokens"]);

		foreach (var item in Configuration.GetSection("OpenIdConnectOptions:Scope").GetChildren())
		{
			o.Scope.Add(item.Value);
		}
		o.SignInScheme = Configuration["OpenIdConnectOptions:SignInScheme"];
	});

	services.AddMvc();
}
```

**Comment by javiercn** [comment]
Seems like you are having issues exchanging the authorization code in the token endpoint. What your log suggests is that your server is able to produce a code and that the app receives it, but that the server sends an error when that code gets exchanged on the server.

* What Identity provider are you using?
* I would look at what token request your app is sending and figure out what is missing.

**Comment by joaco-espinosa** [comment]
Hi Javier, thanks for the response.

- We are using IdentityServer4, I can provide additional information related to its configuration if desired.
- I don't think there's something wrong with the actual request. This stems from the fact that everything works correctly until we place the server behind a load balancer. Put differently, the request being made by the client is the same in both cases.

I'm having a hard time determining why the exception is being thrown if the content of the post being made is exactly the same. **Is there a way I can obtain more information than just _invalid_request_?**

**Comment by javiercn** [comment]
@joaco-espinosa Can you see what the network request and response for the token exchange? Maybe from the logs?

Seems to me that the server is answering with an error on the token endpoint, so unless we can see the message the server receives and the response we get, it will be impossible to diagnose the situation.

To gather more information you could add a delegating handler to the OpenIdConnectOptions.BackChannelHandler that does more loging. Seeing the response status code from the server and the request from the client will be the most helpful.

**Comment by Eilon** [comment]
Closing this because we don't have enough info. This might also be an issue with https://github.com/IdentityServer.
