### ISSUE TITLE
How do I suppress exceptions in OnAuthenticationFailed?

### ISSUE THREAD

**Issue by torhovland** [aspnet/Security#1680]
Hi, I'm using ASP.NET Core 2.0.5, and I have successfully been able to support two different OIDC providers in my app like this:

```
.AddJwtBearer("IdSrv2Bearer", options =>
{
    options.Authority = "https://id-v2...";
    options.Audience = "audience-v2-string";
})
.AddJwtBearer("IdSrv1Bearer", options =>
{
    options.Authority = "https://id-v1...";
    options.Audience = "audience-v1-string";
})
```

The only issue is that when the first JWT validation fails, it logs an exception that I don't want. According to the `OnAuthenticationFailed` docs, I should be able to suppress an exception, but I can't see how. In .NET Core 1, there was a `SkipToNextMiddleware` method, but I don't see that now. Instead, it seems I have the following 3 options:

```
    options.Events = new JwtBearerEvents
    {
        OnAuthenticationFailed = context =>
        {
            var invalidAudienceException = context.Exception as SecurityTokenInvalidAudienceException;

            if (invalidAudienceException?.InvalidAudience == "audience-v1-string")
            {
                // Option 1
                context.Success();

                // Option 2
                context.Fail("IdSrv2Bearer couldn't validate this token, but IdSrv1Bearer probably can.");

                // Option 3
                context.NoResult();
            }

            return Task.CompletedTask;
        }
    };
```

However, neither of these seem to suppress the exception. Well, maybe `Success` does, but that's going to be wrong anyway, and I have to fill out a user Principal in order for it to work.

So how do I actually suppress the validation exception?

**Comment by HaoK** [comment]
`NoResult` results in no exception being thrown, and you end up with an Empty AuthenticateResult which sounds like what you want?

https://github.com/aspnet/HttpAbstractions/blob/321639b0eb2098a6fe3b0d763f48ac3ed025a688/src/Microsoft.AspNetCore.Authentication.Abstractions/AuthenticateResult.cs#L44

**Comment by torhovland** [comment]
Thank you for responding. Actually, I cannot get `NoResult` to suppress the exception. This is what I have at the moment (this should suppress all exceptions, I'll be more selective when I know it works):

```
options.Events = new JwtBearerEvents
{
    OnAuthenticationFailed = context =>
    {
        Log.Debug("IdSrv2Bearer authentication failed. Suppressing it.");
        context.NoResult();
        return Task.CompletedTask;
    }
};
```

However, in Application Insights I get this:

```
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: '<audience-v1-string>'. Did not match: validationParameters.ValidAudience: '<audience-v2-string>' or validationParameters.ValidAudiences: 'null'.
    at  Microsoft.IdentityModel.Tokens.Validators.ValidateAudience (Microsoft.IdentityModel.Tokens, Version=5.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
    at  System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateAudience (System.IdentityModel.Tokens.Jwt, Version=5.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
    at  System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload (System.IdentityModel.Tokens.Jwt, Version=5.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
    at  System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken (System.IdentityModel.Tokens.Jwt, Version=5.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
    at  Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler+<HandleAuthenticateAsync>d__6.MoveNext (Microsoft.AspNetCore.Authentication.JwtBearer, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
```

Immediately followed by:

```
IdSrv2Bearer authentication failed. Suppressing it.
```

**Comment by Tratcher** [comment]
Validation failures are always logged, even if you suppress the exception.
https://github.com/aspnet/Security/blob/a0b704efbdf924099de908c57087de49c9d12d17/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L113

**Comment by torhovland** [comment]
All right, I see. I will suppress the logging in an Application Insights Telemetry Processor, then.
