### ISSUE TITLE
Error when building - "Expected the dependencies to exist at...."

### ISSUE THREAD

**Issue by salzersoftware** [aspnet/Security#1681]
After cloning the repository, I built the solution using the _build.cmd_ script. Everything seemed okay, but my console window disappeared after the build seemingly ended, so I assumed all was good.

I then went to "Rebuild" the solution in source control, only to still receive the following error message across projects: 

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | KRB1001 | Package references have not been pinned. Run './build.cmd /t:Pin'.        Also, you can run './build.cmd /t:Restore' which will pin *and* restore packages. 'build.cmd' can be found in 'C:\Work\AspNetSecurity\'. | Microsoft.AspNetCore.CookiePolicy | C:\Work\AspNetSecurity\Directory.Build.targets | 12 |  

Still being unable to build the solution, I went to run the build.cmd script again. I now receive error messages regarding missing dependencies. Here's the full output:

> 'C:\Users\{username}\.dotnet\x64\dotnet.exe'.
> WARNING: Adding 'C:\Users\{username}\.dotnet\x64' to system PATH permanently may be required for applications like
> Visual Studio or VS Code to work correctly.
> Adding C:\Users\{username}\.dotnet\x64 to PATH
> .NET Core runtime 2.0.5 is already installed. Skipping installation.
> .NET Core SDK 2.1.300-preview2-008251 is already installed. Skipping installation.
> >>> dotnet.exe msbuild @C:\Work\AspNetSecurity\artifacts\logs\msbuild.rsp @C:\Work\AspNetSecurity\artifacts\logs\msbuild.logger.rsp
> C:\Users\{username}\.dotnet\buildtools\korebuild\2.1.0-preview2-15726\modules\KoreBuild.Tasks\module.targets(82,5): error KRB4003: Expected the dependencies file to exist at C:\Work\AspNetSecurity/build\dependencies.props [C:\Users\{username}\.dotnet\buildtools\korebuild\2.1.0-preview2-15726\KoreBuild.proj]
> 
> Build FAILED.
> 
> C:\Users\{username}\.dotnet\buildtools\korebuild\2.1.0-preview2-15726\modules\KoreBuild.Tasks\module.targets(82,5): error KRB4003: Expected the dependencies file to exist at C:\Work\AspNetSecurity/build\dependencies.props [C:\Users\{username}\.dotnet\buildtools\korebuild\2.1.0-preview2-15726\KoreBuild.proj]
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:00.27
> dotnet.exe failed with exit code: 1
> At C:\Users\{username}\.dotnet\buildtools\korebuild\2.1.0-preview2-15726\scripts\common.psm1:11 char:9
> +         throw "$cmdName failed with exit code: $exitCode"
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (dotnet.exe failed with exit code: 1:String) [], RuntimeException
>     + FullyQualifiedErrorId : dotnet.exe failed with exit code: 1
> 

Please advise how to proceed, in order to be able to build the solution. Thank You.

**Comment by Eilon** [comment]
@salzersoftware can you have a look through https://github.com/aspnet/Home/wiki/Building-from-source to see if you've followed all the steps there?

**Comment by salzersoftware** [comment]
Thanks @Eilon - I originally followed the instructions you referenced. I believe the issue was that the default branch for my clone was something other than _dev_ or one of the release versions - which I didn't notice at first. I purged my local copy, re-fetched it with the release v2.0 branch, and things worked. I haven't tried this using the dev branch yet, but I assume it'll work fine as well.

**Comment by Eilon** [comment]
Sounds great!
