### ISSUE TITLE
Setting CookieAuthenticationOptions.ReturnUrlParameter to null or empty does not produce expected results

### ISSUE THREAD

**Issue by ctorx** [aspnet/Security#1682]
When setting CookieAuthenticationOptions.ReturnUrlParameter to null or whitespace, unexpected behavior is observed.

**When null:**
Throws an exception when calling `QueryString.Create()` from within `CookieAuthenticationHandler.cs`

**When empty:**
Produces a mostly un-usable query string parameter (e.g. ?=%2F)

**Suggested Fix:**
If the CookieAuthenticationOptions.ReturnUrlParameter is set to null or empty, rather than throwing an exception (in the null case) or redirecting with an empty query string key, it should instead redirect to the  appropriate path WITHOUT the query string appened.

**For Example:**
If the CookieAuthenticationOptions.ReturnUrlParameter is set to null or empty and the root url is accessed in an unauthenticated manner, the redirect path should simply be the CookieAuthenticationOptions.AccessDeniedPath without any query string.

**Comment by Tratcher** [comment]
As a rule we don't support nulling out various cookie auth options to disable various features. In most cases you can override the events to customize the behavior.

**Comment by ctorx** [comment]
Looking at the code, it does not appear that there currently is a way to
disable the ReturnUrlParameter getting appended to the Url.

Can this be added as a feature in the form of another property on
CookieAuthenticationOptions such as "AppendReturnUrlParameter" that
defaults to true ?

I'm developing many asp.net core apps that don't rely on the Url parameter
and I'd prefer not to pollute the URL with un-necessary information that
can lead to user confusion.

**Comment by blowdart** [comment]
What about the URL do you believe would confuse your users?

**Comment by ctorx** [comment]
Users may become confused or concerned when strange characters that have no
obvious meaning getting added to a URL where they are entering sensitive
information.

This is not such a big problem when the URL is already long and largely
illegible, but when it's something short like "/sign-in", the extra
characters are much more obvious.

When left as the default, *ReturnUrl*, it has a fairly obvious meaning.  If
I set the parameter to empty, the URL now has *?=%2F* added to it, which
has no meaning and may lead to user confusion.

I'm not looking to get into a philosophical debate about this, however, I
do think that if I can set it to empty, I should be able to disable it
altogether.

**Comment by blowdart** [comment]
So as you're the only person to ask for this right now it's unlikely to happen. We're confused how blanking the return URL would work in practice too, and adding more options to what is essentially a security API widens the scope that people may misconfigure things and end up in a state where things are going to go wrong.

**Comment by ctorx** [comment]
Fair enough on the demand.

Here's my use case, if you are interested.

I'm building an ASP.NET Core web application that is composed of multiple
front end single page applications that are powered by Vue.js.  I'm using
Identity with Cookies for authentication on the server.  Authentication
happens via a front end component that utilizes a WebApi to communicate
with Identity.  The WebApi sets the auth cookie upon successful
authentication and responds to the client. The client then handles which
screen is shown next, which has nothing to do with http redirection.

No need to beat this to death, but if I understand it correctly, the
ReturnUrl is never automatically redirected to.  The developer has to
explicitly grab the value and redirect from within their controller.  It
seems reasonable to make it configurable since it is never automatically
redirected to by the framework.

Thanks for taking the time to respond.  Cheers.

**Comment by blowdart** [comment]
Ah that's rather out of scope for our templates :) The parameter is used for "normal" usage in the templates, and others use is for forbidden handling as well.

**Comment by JeroenVogelpoel** [comment]
Mind you, I support having the ability to clean up the ReturnUrl query string or even completely disabling it.

It might interfere with caching systems both local and remote; some might be configured to treat the query string part of the URL as a key in their internal store. For example:

- /Login?ReturnUrl=%2FHome%2FIndex
- /Login?ReturnUrl=%2Resources%2Hello%20World
- /Login?ReturnUrl=%2Resources%2Foo
- /Login?Example=%2FHome%2FIndex

... might be treated as different resources to be cached while effectively being a single resource to be cached. Using dummy query strings is actually used as a way to 'trick' caches (both local and remote) into pulling a fresh resource from the URL.

Also; it honestly just looks plain ugly to pass around dummy URLs in the query string.

**Comment by ctorx** [comment]
Are you open to a pull request on this if someone else does this?  It looks
pretty trivial.

**Comment by JeroenVogelpoel** [comment]
Even if the users don't look at your URLs at all, the OWASP black box testers usually do look at your inputs.

Though the software underneath doesn't redirect at all, the testers still have a valid point that a URL parameter can be used for potentially insecure redirects. And while it's completely valid and possible to simply not use the 'returnUrl' parameter from the QS, this is hard (impossible?) to verify that this parameter is unused in a proper black box external audit.

In combination with the potential caching issues, I feel we might have a good reason to simply disable the QS parameter altogether.

Also see: https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet

**Comment by blowdart** [comment]
If your testers are flagging things based on potential rather than reality then my opinion is your testers aren't very good.

**Comment by RickBlouch** [comment]
I've wondered in the past why the default isn't for the return url to be omitted and for devs to have to opt in if their application actually uses it.  I would turn it off if I could.

**Comment by JeroenVogelpoel** [comment]
Such is the reality we have to work with; black box security testers with a healthy-perhaps-unhealthy dose of paranoia, I suppose.

What are the chances that we might one day expect the ability to completely remove the return URL from the query string?

**Comment by blowdart** [comment]
It's not something we're considering adding. A PR might be considered in our next release.

**Comment by ctorx** [comment]
Thanks for the feedback.  When is the next release scheduled?

**Comment by blowdart** [comment]
Unknown. It won't be in 2.1 though, it'd be 2.2 at the earliest.

**Comment by Eilon** [comment]
After further discussion, we have concluded that this suggestion does not align with what we want to do for cookie auth, so we're closing this issue.
