### ISSUE TITLE
WSFederation Support with Windows Identity

### ISSUE THREAD

**Issue by joetherod** [aspnet/Security#1683]
Is there support for WFFederation SSO authentication with WIF?
Currenyly using the following namespaces in .NET 4.6

using System.IdentityModel;
using System.IdentityModel.Services;
using System.IdentityModel.Services.Configuration;
using System.IdentityModel.Tokens;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Permissions;

DeflateCookieTransform
RsaEncryptionCookieTransform
RsaSignatureCookieTransform

Is there any information on how to do this in ASPNET Core MVC?

Thanks

**Comment by blowdart** [comment]
Yes. https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.WsFederation/

https://github.com/aspnet/Security/issues/1473 has the discussion from Preview 1 to Release.

**Comment by laj0206** [comment]
Hi @blowdart, thanks for the information. 
In .NET 4.6, we used to use SessionSecurityTokenHandler including RsaEncryptionCookieTransform to parse token since token is been encrypted by certificate. Is there a way to do the same thing in net core? I am not able to find a way based on the current nuget package. 
Could you please kindly advise? Thanks

**Comment by Tratcher** [comment]
@brentschmaltz

**Comment by joetherod** [comment]
@brentschmaltz any update on WSFederation supporting SessionSecurityTokenHandler including RsaEncryptionCookieTransform.
Or is there a sample implementation that can do the same thing for authentication via WSFederation for SSO?

**Comment by joetherod** [comment]
No update? @brentschmaltz Very unfortunate that this prerelease is unusable at this point.

**Comment by Tratcher** [comment]
This issue was moved to AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#887
