### ISSUE TITLE
SaveTokens & AccessType do nothing

### ISSUE THREAD

**Issue by strich** [aspnet/Security#1685]
Use case: For the past 2 weeks I've been trying to make the most simple application that uses Google auth and Identity. I need to use the access and refresh tokens once a user has signed up to do things on their behalf. 

I have been getting sporadic assistance in tickets #1667 and #1668, though there still seems to be no real consensus on how to achieve this task. [There is an issue to add an example project here](https://github.com/aspnet/AuthSamples/issues/29), and hopefully that will happen soon.

This issue is to specifically raise the fact that applying the options `SaveTokens = true` and `AccessType = "Offline"` appear to do nothing, or don't do what they purport to do. That is to say, `SaveTokens` doesn't save the access and refresh tokens to the db and `AccessType` doesn't appear to force a refresh token to be returned if there isn't one.

It could be they still do something, but require a lot of other backing code to work elsewhere? If so, it should be setup as such in the default auth templates.

**Comment by Eilon** [comment]
@strich sorry you're still running into issues. Can you show in this issue the relevant configuration/startup logic of your app so that we can dig into this?

**Comment by strich** [comment]
I use the the .NET Core v2.1 ASPNET Template and add a standard google auth setup to Startup. I can make a demo app if you like, but I don't stray far from the template.

**Comment by Eilon** [comment]
@strich it would be great if you can just copy/paste the configuration lines of code into this issue so we can make sure we're all looking at the same scenario.

**Comment by strich** [comment]
Sure:

```c#
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("DefaultConnection")));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.AddAuthentication().AddGoogle(o =>
            {
                o.ClientId = Configuration["Authentication:Google:ClientId"];
                o.ClientSecret = Configuration["Authentication:Google:ClientSecret"];
                o.Scope.Add("https://www.googleapis.com/auth/plus.me");
                o.Scope.Add("https://www.googleapis.com/auth/analytics");
                o.AccessType = "offline";
                o.SaveTokens = true;
            });

            services.AddMvc()
                .AddRazorPagesOptions(options =>
                {
                    options.Conventions.AuthorizeFolder("/Account/Manage");
                    options.Conventions.AuthorizePage("/Account/Logout");
                    options.Conventions.AuthorizePage("/MyClaims");
                });

            services.AddSingleton<IEmailSender, EmailSender>();
        }
```

**Comment by HaoK** [comment]
So the main issue here is that identity is really controlling your login in the templates.  The google login is only really used to exchange for an identity cookie.  So turning on things like SaveTokens and Access type were mostly intended for scenarios where you were using Google and its associated cookie directly.  

https://github.com/aspnet/AuthSamples/tree/dev/samples/Identity.ExternalClaims does some of what you want, with coping over the access tokens during login

**Comment by strich** [comment]
Thanks @HaoK. However I have a couple of issues with this:

1. It is absolutely not clear that those options suddenly don't work. Surely this is a fairly common scenario and the default auth templates should be able to cope with this by including the functionality presented in the ExternalClaims demo.
2. I have downloaded the ExternalClaims demo and have got it working. However refresh tokens still do not work.

**Comment by strich** [comment]
@HaoK @Eilon I would love it if I could get an update on this - I don't know how to continue with my project without a refresh token. Would it be possible if one of you could update the ExternalClaims example with a concrete implementation of this? I've spent quite a few days on this now and I suspect one of you could bash out a solution very quickly, no?

Thanks!

**Comment by Eilon** [comment]
@strich we're going to consider this in the 2.2.0 release, as we can't fit this into the 2.1.0 release.

@HaoK - can you please break this down into targeted issues in appropriate repos?

**Comment by strich** [comment]
@Eilon can you provide an estimated timeframe for v2.2?

**Comment by HaoK** [comment]
https://github.com/aspnet/Identity/issues/628 will track the all up work in making this easier

**Comment by Eilon** [comment]
@strich we're focused right now on getting 2.1.0 done. We're hoping that 2.2 is a fairly quick release after that, but it's late this year at the earliest I would guess.

**Comment by strich** [comment]
Is there any chance I could get the External Claims demo updated with refresh tokens at least? I can make my own way after that until there is official support.

**Comment by Eilon** [comment]
@strich sorry I'm not sure we can guarantee that. It's a matter of juggling many different priorities so it's hard to say exactly when we will get to that.
