### ISSUE TITLE
web api in core api 1.1.

### ISSUE THREAD

**Issue by arshu1919** [aspnet/Security#1687]
![screenshot-localhost-5341-2018 03 11-12-04-14](https://user-images.githubusercontent.com/36697174/37251603-5be2c49c-2524-11e8-923d-812a9f27988d.png)
if authorization is failed , it is giving me 404. instead of 401. with mvc route

```c#
app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "api",
                    template: "api/{controller=Account}/{action=Login}/{id?}");
            });
```

i am using  services.AddAuthentication(options =>

```c#
            {
                options.SignInScheme = JwtBearerDefaults.AuthenticationScheme;
            });
```

i am not using cookie authentication.
and  app.UseIdentity() has beed used also.

```c#
 Events = new JwtBearerEvents
 {
    OnChallenge = ctx =>
       {
                        if (ctx.Request.Path.StartsWithSegments("/api") && ctx.Response.StatusCode == (int)HttpStatusCode.OK)
                        {
                            ctx.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                            ctx.HandleResponse();
                            
                            return Task.CompletedTask;
                        }
 

     }
}
```

always it goes to Request starting HTTP/1.1 GET http://localhost:23355/Account/Login?ReturnUrl=%2Fapi%2Freservation , i dont have get method.

any solution to fix the 404 to 401

**Comment by Tratcher** [comment]
Identity is doing this, it adds cookie auth and overrides your defaults. You need to specify JwtBearerDefaults.AuthenticationScheme in your Authorize attribute on your WebApi controllers.

Also, JWT is not a valid SignInScheme.

**Comment by arshu1919** [comment]
@Tratcher ,  which will be best method to give hybrid user token , so that they will not signin every time.
please give me any suggestion and methods.

**Comment by Tratcher** [comment]
hybrid user token? It's not clear what you're trying to build in your app.

**Comment by arshu1919** [comment]
@Tratcher , i am building web api which support  mobile device , web ,desktop . i am trying to implement  signin  with jwt token.

**Comment by Tratcher** [comment]
The only provider that implements SignIn is CookieAuth. For JWT you need a token server to issue the JWT to the client app.
