### ISSUE TITLE
[Question] Two "virtual" applications Google OAuth2

### ISSUE THREAD

**Issue by joacar** [aspnet/Security#1688]
Hi,

Is it possible to have to "virtual" applications using Google OAuth2? What I'm trying to achieve is `AddGoogle("youtube", "YouTube", options => { ... })` and then `AddGoogle("blog", "Google Analytucs", options => { ... })` but when I initiate the "blog" authorization flows (it works because it only displays the scope for Google Analytics and not those for YouTube) and authorize it redirects back with error **The OAuth state is missing or invalid**. The "YouTube" flow works (it is defined prior to "blog").

I'm using `Microsoft.AspNetCore.Authentication.Google 2.0.1`.

Thanks

**Comment by Tratcher** [comment]
You need to give them unique CallbackPaths.

**Comment by joacar** [comment]
@Tratcher Thanks!
