### ISSUE TITLE
[AuthZ] Revisit Authorize default RequireAuthenticatedUser behavior

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#169]
Currently its looking for User.Identity.IsAuthenticated, this probably needs to be changed to look for ANY Identity in the ClaimsPrincipal where IsAuthenitcated is true.

cc @blowdart @lodejard

**Comment by blowdart** [comment]
Yup. Worth considering is what we do for claims checks. Do we limit to authenticated identities or not? That's probably what people expect.

**Comment by HaoK** [comment]
I still need to revist (and reimplement) what ActiveAuthenticationTypes means on a policy, when set, we still further filter the user's identities?  We certainly can't have Schemes at this point unless we are going to rebuild the user entirely using only the principals from the policy
