### ISSUE TITLE
OpenIdConnectOptions adding multiple audience in TokenValidationParameters

### ISSUE THREAD

**Issue by JiwanMS** [aspnet/Security#1690]
I am using azure AD B2C in aspnet core web app and i am setting the OpenIdConnectOptions.TokenValidationParameters with multiple audience. But after the user is authenticated with AD i still see the error 

`SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'xxxx'. Did not match: validationParameters.ValidAudience: 'xxxx' or validationParameters.ValidAudiences: 'null'.`

How do i set the validationParameters.ValidAudiences in this case? currently it only validates against OpenIdConnectOptions.ClientId.

**Comment by Tratcher** [comment]
@javiercn

**Comment by javiercn** [comment]
Are you using the jwt bearer middleware or the open id connect middleware? I don't think audience matters in the open id connect case in the sense that it always have to match the client ID as you are login in a user based on it.

**Comment by JiwanMS** [comment]
I am using open id connect middleware with Azure AD B2C. The request is redirected to the AD and after user logs in the token is validated against the clientId configured in open ID connect options as audience. In my case there can be multiple audiences since multiple applications have access to the site. I am trying to add the list of audience using OpenIdConnectOptions.TokenValidationParameters.ValidAudiences but in the error i can still see ValidAudiences as null.

**Comment by JiwanMS** [comment]
Adding more info. Below is the code and stack trace.

```
options.ClientId = this.authenticationConfig.CompanyA.ClientId; // This is acting as audience
options.TokenValidationParameters = new TokenValidationParameters
{
       ValidAudiences = new List<string>
        {
                    this.authenticationConfig.CompanyA.ClientId,
                    this.authenticationConfig.CompanyB.ClientId
        }
};

//// Other configurations below
```

```
SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'ca68a1ae-414e-4013-a22a-9f3b30d4ef03'. Did not match: validationParameters.ValidAudience: '2a0c7741-d699-4a67-a1bd-2b8b5902a503' or validationParameters.ValidAudiences: 'null'.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Session.SessionMiddleware+<Invoke>d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Session.SessionMiddleware+<Invoke>d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
```

**Comment by javiercn** [comment]
I don't think the OpenIDConnect handler supports multiple audiences, what you need to do instead is have an open id connect handler per audience you want to support and have them all sign in with the same cookie.

**Comment by JiwanMS** [comment]
Yes that worked. Thanks!
