### ISSUE TITLE
WS-Federation without Core Identity crashes when initialized before UseMvc()

### ISSUE THREAD

**Issue by remware** [aspnet/Security#1694]
I have this in Startup.cs ( NetCore 2.0.0 + WsFederation 2.0.0, also tested 2.0.5)
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
      env.ConfigureNLog("nlog.config");
      loggerFactory.AddNLog();
      app.AddNLogWeb();
       try
		{
			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
			}
			else
			{
				app.UseExceptionHandler();
			}

		    app.UseAuthentication();
                    app.UseMvc();				
		}
			catch (Exception e)
			{ ... }
}
```
When using Authentication before MVC the app starts but authentication does not work properly.
If reverting the orders the app crashes without error log:
Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler:Information: Error from RemoteAuthentication: No message

**Comment by Tratcher** [comment]
Stack trace?

**Comment by remware** [comment]
System.Exception: No message.

   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by Tratcher** [comment]
And what do you have in ConfigureServices?

**Comment by Tratcher** [comment]
For reference that error message comes from here: https://github.com/aspnet/Security/blob/d95109c96d6b92d04178dea004583796824072da/src/Microsoft.AspNetCore.Authentication.WsFederation/WsFederationHandler.cs#L164

**Comment by remware** [comment]
Configure services looks like:
 ....
                services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

		    // Add auth
		    services.AddAuthentication(sharedOptions =>
		        {
		            sharedOptions.DefaultScheme = AuthScheme;
		            sharedOptions.DefaultSignInScheme = AuthScheme;
		            sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;
		        })
		        .AddCookie(AuthScheme, options =>
		        {
		            options.DataProtectionProvider = DataProtectionProvider.Create(new DirectoryInfo(Configuration.GetSection("Auth:KeyStorage").Value));
		            options.Cookie.Name = Configuration.GetSection("Auth:CookieName").Value;
		            options.Cookie.Domain = Configuration.GetSection("Auth:CookieDomain").Value;
		            options.Cookie.Path = "/";
		        })
		        .AddWsFederation(options =>
		        {
		            options.MetadataAddress = Configuration.GetSection("AccountController:Adfs").Value;

		            // Wtrealm is the app's identifier in AD or relying party's identifier in ADFS ( WS-Federation Passive protocol URL)
		            options.Wtrealm = Configuration.GetSection("AccountController:AppId").Value;

		            options.CallbackPath = ""AccountController:LoginPath";

		        });

            // Add MVC
            services.AddMvc(options =>
			{
				options.Filters.Add(typeof(LoggingExceptionFilter));
			});

			// Add logging
			services.AddLogging();
			
			// Custom Settings
			services.AddOptions();
			   services.Configure<AccountControllerSettings>Configuration.GetSection("AccountController"));          

...

**Comment by Tratcher** [comment]
Side note: data protection should be configured for the whole app, not just one cookie.

Your CallbackPath is wrong, it should not refer to an mvc controller, it should be to a path unique to the middleware.

Also, put auth back in front of mvc.

**Comment by remware** [comment]
I removed the CallbackPath but results are similar, authentication does not happen. I wonder if my login logic is wrong as follows:

1. Check if user is authenticated with default scheme, otherwise continue with current auth user
2. If not call auth then challenge auth with WsFed and redirect to home
3. Check in next round if user is authenticated with other scheme than default

Is there something I am missing?

**Comment by Tratcher** [comment]
Where are you doing that? Want to show the code?

**Comment by remware** [comment]
In HomeController

using Alehdet.Hours.Seller.Identity.Components;
using Alehdet.Hours.Seller.Identity.Options;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Principal;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.WsFederation;


namespace Alehdet.Hours.Seller.Identity.Controllers
{
    public class HomeController : Controller
	{
		private readonly ILogger _logger;

		private readonly IAppUrlProvider _appUrlProvider;

		private readonly AccountControllerSettings _options;

		private const string CookieAuthType = "CookieAuth";


        public HomeController(
			ILoggerFactory loggerFactory,
			IAppUrlProvider appUrlProvider,
			IOptions<AccountControllerSettings> optionsAccessor)
		{
			_logger = loggerFactory.CreateLogger<HomeController>();
			_appUrlProvider = appUrlProvider;
			_options = optionsAccessor.Value;
		}

		
		[Route("")]
		public IActionResult Index()
		{
			var c = new StringBuilder();		
			foreach (var u in _appUrlProvider.GeAllAppUrls())
			{
				c.AppendLine(u);
			}

			return Ok(c.ToString());
		}

		[Route("login/{appName}")]
		public async Task<IActionResult> Login([FromRoute] string appName)
		{
			var logEventId = new EventId(1);

			if (string.IsNullOrWhiteSpace(appName))
			{
				return NotFound();
			}

	
            var authenticateResult = await HttpContext.AuthenticateAsync(Startup.AuthScheme).ConfigureAwait(false);
			var principal = authenticateResult?.Principal;


		    if (principal?.Identities != null && principal.Identities.Any(i => i.IsAuthenticated))             
		    {
		        if (principal.Identities.Any(i => i.AuthenticationType == CookieAuthType))
		        {
		            _logger.LogWarning(logEventId, $"Authenticated user '{principal.Identity.Name}' is back.");		            
		        }
		        else
		        {
		            _logger.LogWarning(logEventId, $"Authenticated  {authenticateResult.Succeeded}, Ticket  {authenticateResult.Ticket}, Failure  {authenticateResult.Failure}, Prin  {authenticateResult.Principal}  ");
		            await SignInCookie(principal.Identity.Name, new[] { "OnAdfs" }, null).ConfigureAwait(false);
                }		        
               
			    // already auth
		        return Redirect(_appUrlProvider.GetAppUrl(appName, Request.Query));

            }
		       
		    // not auth, challenge adfs
			await HttpContext.ChallengeAsync(WsFederationDefaults.AuthenticationScheme);
            
			return RedirectToAction("Index"); // or Unauthorized
			
			
		}

	    private Task SignInCookie(string username, string[] roles, string salesRepid)
		{
			var claims = new List<Claim>
			{
				new Claim(ClaimTypes.Name, username)
			};

			if (roles != null)
			{
				foreach (var role in roles)
				{
					claims.Add(new Claim(ClaimTypes.Role, role));
				}
			}

			var claimsPrincipal = new ClaimsPrincipal(new ClaimsIdentity(claims, CookieAuthType, ClaimTypes.Name, ClaimTypes.Role));

			return HttpContext.SignInAsync(Startup.AuthScheme, claimsPrincipal);
		}
	}
}

**Comment by Tratcher** [comment]
It's odd to use the same cookie for the external and local logins, every call site would have to distinguish between them. You'd be better off registering two cookies and transitioning from one to the other. The Identity templates do something like this. That however is unlikely related to your issue.

My only other suggestions at this point are to collect a Fiddler trace of the traffic and to collect application logs with the level set to Debug.

**Comment by remware** [comment]
Thanks for the suggestion. Now after updating NetCore 2.0.6 + WsFederation 2.0.3, there is no crash in the app but smoothly respond. Also tried with new  VS2017 code generation for core web api project based on  authentication against Azure AD and it seems to authenticate well.

**Comment by remware** [comment]
BTW  The use of CallbackPath is not clear, while testing against Azure AD I noticed that you need to match CallbackPath with Reply url in Azure AD, plus the path should exists. Not clear what is the purpose of that and not sure what you mean by unique in the middleware. I will try to put some code in github to get further comments.

**Comment by Tratcher** [comment]
Can you clarify this?
> the path should exists

See the doc comments:
https://github.com/aspnet/Security/blob/bee77ebf911d477faed36a12bcc7369bf0005e1a/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationOptions.cs#L87-L88

Or put another way, the middleware handles all requests to this path so it must have a unique path to avoid conflicts with other components.

**Comment by remware** [comment]
Hi,
I think I manage to reproduce this again when you make a GETcall to CallbackPath. It does not matter if you use the default "siginin-wsfed" or other you configure in your middleware. The CallbackPath is configured to be used as POST route. Now my question is why this throw an exception instead of ignoring the call?
As developer my point of view is that we have no control over this path but still a "user" might try to use this route "accidentally". How can I prevent this flow or catch the exception ?

**Comment by Tratcher** [comment]
The routing is not Method specific, the middleware handles all requests to a given route. The only case I've seen users end up on this path accidentally is through use of the browser Back button. Have you had users hit this any other way?

You can get more control of these behaviors through the various Events, specifically the OnRemoteFailure event. https://github.com/aspnet/Security/blob/d24d4fa99f46822a3b9b87702507e0dc914a0126/samples/SocialSample/Startup.cs#L70-L73
https://github.com/aspnet/Security/blob/d24d4fa99f46822a3b9b87702507e0dc914a0126/src/Microsoft.AspNetCore.Authentication.WsFederation/Events/WsFederationEvents.cs#L12

**Comment by remware** [comment]
Thanks for the hint. The auth now works smoothly locally if configured against Azure Ad, but when deploying to ISS host and configured with the network domain ADFS,  I get following error:
 Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler | ERROR | Exception occurred while processing message. Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'https://my.domain.com'. Did not match: validationParameters.ValidAudience: 'https://my.domain.com/' or validationParameters.ValidAudiences: 'null'.
at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateConditions(SamlSecurityToken securityToken, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.Tokens.Saml.SamlSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler.<HandleRemoteAuthenticateAsync>d__9.MoveNext() | POST https://my.domain.com/signin-wsfed

Which for me the only visible difference is ending "/" in uri, could you point me to the code generating this error?

**Comment by Tratcher** [comment]
That's coming from here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/d771b5c3ef22b7ff065e8fad1a63d6a2937b7d7f/src/Microsoft.IdentityModel.Tokens/Validators.cs#L109
You can open a new issue there for better matching.
