### ISSUE TITLE
System.threading.thread.currentprincipal.identity.name is returning null .Net Core

### ISSUE THREAD

**Issue by WaedSaleh** [aspnet/Security#1696]

**Comment by Eilon** [comment]
`Thread.CurrentPrincipal` is not used in ASP.NET Core. You have to pass around the identity/principal as a parameter to other methods based on what you get in `HttpContext.User` after authentication has taken place.

**Comment by WaedSaleh** [comment]
@Eilon, But why it works for 4.6.2 and it does not work for ,Net Core

**Comment by Eilon** [comment]
It works on ASP.NET 4.6 apps, but does not work in ASP.NET Core. This was a design decision for the reasons mentioned above.

**Comment by WaedSaleh** [comment]
Hi Elion,  What I meant when using   ASP.NET Core targeting 4.6 it works but when you have it on ASP.NET Core targeting.Net Core it does not work

**Comment by blowdart** [comment]
It's luck it works for your targetting 4.6. We make no promises it will work, because it ends up using HttpContext.Current and this just doesn't work well for multi-threading or async. Don't use it.
