### ISSUE TITLE
Allow developers to customize the OIDC parameters when calling Challenge

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1698]
Related: https://github.com/aspnet/Security/issues/990
https://github.com/aspnet/Security/pull/1401#issuecomment-372072396
https://github.com/aspnet/Security/pull/1691

Developers can already do this the long way by hooking into the RedirectToIdentityProvider event and customizing the protocol message. For well known properties consider allowing developers to specify them in the AuthProperties from Challenge provide a built in mapping.

**Comment by Eilon** [comment]
@Tratcher I'm putting this on your plate to track the PR.

**Comment by muratg** [comment]
Are we taking the PR?  @Tratcher you seem to have approved it, will you be taking it in, or should this be reassigned?

**Comment by Tratcher** [comment]
I approved the initial version but then it snowballed. There's ongoing debate over an expanded design.

**Comment by Eilon** [comment]
We discussed at standup this morning. I think we either get it into Preview2 or it has to wait until 2.2.
