### ISSUE TITLE
WSFederation - No token validator was found for the given token.

### ISSUE THREAD

**Issue by StevanoHallo** [aspnet/Security#1700]
The exception I'm getting when attempting to use WSFederation in my .NET Core App:

SecurityTokenException: No token validator was found for the given token.

`Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()`

This is my 'ConfigureServices':

> services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;
            })
            .AddWsFederation(options =>
            {
                options.Wtrealm = "https://localhost:1234";
                options.MetadataAddress = "https://adfs.company.co.uk/federationmetadata/2007-06/federationmetadata.xml";
            })
            .AddCookie();

I also have 'app.UseAuthentication();' at the top of 'Configure' as well.

I've tried using the MetaData and also building the options manually without it. Both result in the same exception. Looking at Fiddler as well, it seems to be authenticating with ADFS and I'm getting a 200 back. We use the same ADFS server for our .NET 4.6 Apps and that works fine. 

But I'm not sure if I'm missing something or there is an issue with the library?

**Comment by Tratcher** [comment]
We would need an example token to investigate.

**Comment by StevanoHallo** [comment]
@Tratcher Here's an example token pulled from a response. Thanks.

[Token.txt](https://github.com/aspnet/Security/files/1829678/Token.txt)

**Comment by Tratcher** [comment]
This issue was moved to AzureAD/azure-activedirectory-library-for-dotnet#1018
