### ISSUE TITLE
iconfigurationsection does not contain a definition for get 

### ISSUE THREAD

**Issue by WaedSaleh** [aspnet/Security#1704]
I  passed Configuration object to the class library and when I use  it to get a configuration  like 
 Configuration.GetSection("Settings").Get<Settings>(); I get the error iconfigurationsection does not contain a definition for get. 

PS : In Startup class, it works fine but in the class library not.

**Comment by blowdart** [comment]
This issue was moved to aspnet/Home#2988

**Comment by blowdart** [comment]
This issue was moved to aspnet/Home#2990
