### ISSUE TITLE
Allow overriding protocol redirect_uri in OpenIdIdentityProvider from external providers

### ISSUE THREAD

**Issue by sergiomcalzada** [aspnet/Security#1705]
When generating redirect url in the AuthenticationHandler the uri is composed from the current request protocol. When you are behind a proxy (like in a lot of Kubernetes deployments) protocol is incorrect.

You could override it in OnRedirectToIdentityProvider now, but it should be more easy to do it when configuring the options.

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/Security/issues/1702
