### ISSUE TITLE
WsFederation SaveTokens does not work

### ISSUE THREAD

**Issue by dsmailys** [aspnet/Security#1716]
Hello,

Tried using `WsFederationOptions.SaveTokens = true`, but the token is not being set in the AuthenticationProperties.

I have tried hooking into `Events.OnSecurityTokenValidated`
and saving token into authentication properties myself by
`properties.StoreTokens (new [] { new AuthenticationToken { Name = tokenClaimName, Value = token } });`
but with no luck. I get
```
This site can’t be reached
The webpage at https://localhost:44301/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SPDY_PROTOCOL_ERROR
```
Am I missing something here?

**Comment by dsmailys** [comment]
If I disable the SaveTokens implementation - the rest of the site is working as intended.
I have a wrapper class that wraps around `WsFederationHandler` and adds some code for authentication from authorization header, but this might be out of scope.
I hook into the events like this:
```
public async Task InitializeAsyncWrapper (AuthenticationScheme scheme, HttpContext context)
            {
            await base.InitializeAsync (scheme, context); 
            Events.OnSecurityTokenValidated = OnSecurityTokenValidated;
            }

private Task OnSecurityTokenValidated (SecurityTokenValidatedContext securityTokenValidatedContext)
            {
            var token = securityTokenValidatedContext.ProtocolMessage.GetToken ();
            var claimsIdenity = securityTokenValidatedContext.Principal.Identity as ClaimsIdentity;
            claimsIdenity.AddClaim (new Claim ("TokenType", token));
            return Task.CompletedTask;
            }
```
If I add non base64 encoded token to the claims, I get
```
Bad Request - Request Too Long
HTTP Error 400. The size of the request headers is too long.
```

If I encode the token to base64 before storing it into the claims:
```
private Task OnSecurityTokenValidated (SecurityTokenValidatedContext securityTokenValidatedContext)
            {
            var token = securityTokenValidatedContext.ProtocolMessage.GetToken ();
            var encoded = System.Convert.ToBase64String (System.Text.Encoding.UTF8.GetBytes (token));
            var claimsIdenity = securityTokenValidatedContext.Principal.Identity as ClaimsIdentity;
            claimsIdenity.AddClaim (new Claim ("TokenType", encoded));
            return Task.CompletedTask;
            }
```
I get
```
The webpage at https://localhost:44301/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SPDY_PROTOCOL_ERROR
```
Note that I clear the cookies (and not using the authorization header implementation) before the requests to get the code triggered.

Tried saving the token to the AuthenticationProperties:
```
private Task OnSecurityTokenValidated (SecurityTokenValidatedContext securityTokenValidatedContext)
            {
            var token = securityTokenValidatedContext.ProtocolMessage.GetToken ();
            securityTokenValidatedContext.Properties.StoreTokens (
                new[] {new AuthenticationToken {Name = "TokenName", Value = token}});
            return Task.CompletedTask;
            }
```
And I get:
```
Bad Request - Request Too Long
HTTP Error 400. The size of the request headers is too long.
```

Tried encoding the token:
```
private Task OnSecurityTokenValidated (SecurityTokenValidatedContext securityTokenValidatedContext)
            {
            var token = securityTokenValidatedContext.ProtocolMessage.GetToken ();
            var encoded = System.Convert.ToBase64String (System.Text.Encoding.UTF8.GetBytes (token));
            securityTokenValidatedContext.Properties.StoreTokens (
                new[] {new AuthenticationToken {Name = "TokenName", Value = encoded } });
            return Task.CompletedTask;
            }
```
And I get:
```
This site can’t be reached
The webpage at https://localhost:44301/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SPDY_PROTOCOL_ERROR
```

If I am not messing with the claims and authenticationProperties, I get a working application.
Is it related to some cookie checks for integrity or something?

**Comment by Tratcher** [comment]
Wrapping the handler is a strange way to set OnSecurityTokenValidated, you could have set that in Startup.

How big is the token? It sounds huge. A Fiddler trace would show how big the cookie gets when you do this.

I don't have a good explanation for the protocol error, it sounds like a catastrophic failure on the server. Is there anything showing up in the server logs?

**Comment by dsmailys** [comment]
Yes, I could, but this is not the main purpose of the wrapper. The main purpose is to enable authentication through authorization header on an api call with a token in the authorization header.

**1st scenario:**
When I am not saving the token and getting a redirect from IdentityProvider to my application:
Status code: 302, localhost:44301/, Body size: 0.
Request sending 82 bytes of Cookie data: .AspNetCore.Correlation.WsFederation
Response: 1) 142 bytes of Cookie data: .AspNetCore.Correlation.WsFederation
                 2) 68 bytes of Cookie data: .AspNetCore.Cookies=chunks-2
                 3) 4049 bytes of Cookie data: .AspNetCore.CookiesC1
                 4) 881 bytes of Cookie data: .AspNetCore.CookiesC2
Status code: 200, localhost:44301/, Body size: 30 (just simple data from the app)
Request sending 4882 bytes of Cookie data: 
                  1) .AspNetCore.Cookies=chunks-2
                  2) .AspNetCore.CookiesC1
                  3) .AspNetCore.CookiesC2

**2nd scenario:**
When I am saving the token (as is) to the authentication properties with StoreTokens method and getting a redirect from IdentityProvider to my application:
Status code: 302, localhost:44301/, Body size: 0.
Request sending 82 bytes of Cookie data: .AspNetCore.Correlation.WsFederation
Response: 1) 142 bytes of Cookie data: .AspNetCore.Correlation.WsFederation
                 2) 68 bytes of Cookie data: .AspNetCore.Cookies=chunks-5
                 3) 4049 bytes of Cookie data: .AspNetCore.CookiesC1
                 4) 4049 bytes of Cookie data: .AspNetCore.CookiesC2
                 5) 4049 bytes of Cookie data: .AspNetCore.CookiesC3
                 6) 4049 bytes of Cookie data: .AspNetCore.CookiesC4
                 7) 354 bytes of Cookie data: .AspNetCore.CookiesC5
Status code: 400, localhost:44301/, Body size: 346
Request sending 16388 bytes of Cookie data. (sending same 5 chunks)

**3rd scenario:**
When I am saving the token (base64 encoded) to the authentication properties with StoreTokens method and getting a redirect from IdentityProvider to my application:

I did notice a very strange behaviour. Once I open Fiddler to capture traffic, I get Bad Request - Request Too Long screen, but once Fiddler is closed, I receive the ERR_SPDY_PROTOCOL_ERROR. I did reproduce this multiple times in a row.

Status code: 302, localhost:44301/, Body size: 0.
Request sending 82 bytes of Cookie data: .AspNetCore.Correlation.WsFederation
Response: 1) 142 bytes of Cookie data: .AspNetCore.Correlation.WsFederation
                 2) 68 bytes of Cookie data: .AspNetCore.Cookies=chunks-6
                 3) 4049 bytes of Cookie data: .AspNetCore.CookiesC1
                 4) 4049 bytes of Cookie data: .AspNetCore.CookiesC2
                 5) 4049 bytes of Cookie data: .AspNetCore.CookiesC3
                 6) 4049 bytes of Cookie data: .AspNetCore.CookiesC4
                 7) 4049 bytes of Cookie data: .AspNetCore.CookiesC5
                 8) 165 bytes of Cookie data: .AspNetCore.CookiesC6
Request sending 20210 bytes of Cookie data. (sending same 6 chunks)

The token itself is 8542 bytes long (non encoded).

I could not see anything abnormal in the logs.
I can attach full trace log if there is a need for it.

**Comment by Eilon** [comment]
@dsmailys we don't recommend storing this data in any persistence because it is security-sensitive information (akin to a username/password). Can you provide more info on the scenario you're trying to achieve?

**Comment by dsmailys** [comment]
This is mainly used when a service wants to call another service that requires authentication.

On full framework we had an option of BootStrapTokenClaimName where we could specify a claim name and store the token.
Do you think we could tackle this in different manner @Eilon ?
Is there some sort of a workaround to pass the token to the controller action until the enhancement is implemented? @Tratcher

**Comment by Tratcher** [comment]
ClaimsIdentity has a BootstrapContext, not sure what's in it for WsFed though. @brentschmaltz

**Comment by Eilon** [comment]
@brentschmaltz - can you share your thoughts on this?

**Comment by dsmailys** [comment]
Tried saving the token to the BootstrapContext in OnSecurityTokenValidated event. 
```
private Task SecurityTokenValidated (SecurityTokenValidatedContext context)
    {
    TrySaveTokenToBootstrapContext (context.ProtocolMessage.GetToken(), context.Principal.Identity as ClaimsIdentity);
    }

private void TrySaveTokenToBootstrapContext (string token, ClaimsIdentity claimsIdentity)
            {
            if (Options.SaveTokens && claimsIdentity != null)
                {
                claimsIdentity.BootstrapContext = new BootstrapContextToken (token);
                }
            }
```

But when I get to the authorized Controller action, BootstrapContext is null. Is it being overwritten somehow? Maybe I am not using the BootstrapContext correctly?
@Tratcher

**Comment by jeff-bacon** [comment]
I'm trying to fetch the access token after login and somehow instantiate a WindowsIdentity from it for the purpose of impersonation.  I can't figure out how to get the access token though.  Tried the bootstrap context and savetokens = true with no luck.

**Comment by dsmailys** [comment]
@Tratcher I've got some additional information.
Our team found out that if we host the application on Kestrel web server with configured https and self signed certificate, we are able to add token to the user claims and receive the modified claimsPrincipal in the action with no additional modifications.

Beforehand I tested the application by hosting it on local IIS. Might it be related to the IIS configuration and maybe we can workaround it?

**Comment by Tratcher** [comment]
That's odd. The only feature of IIS that would conflict with this is if you had Windows Auth turned on. The only other difference is the application pool identity.

**Comment by dsmailys** [comment]
@Tratcher @Eilon 
Could you please elaborate on the security concerns about implementing SaveTokens?
This is mainly used when a service wants to call another service that requires authentication from an authorization header. Is there something wrong with our approach and this scenario could be handled with another solution?

**Comment by dsmailys** [comment]
Adding some additional information.
This issue is happening when cookie size exceeds 16kb. 16kb is the default value of http system registry setting. More information about this here: https://support.microsoft.com/en-us/help/820129/http-sys-registry-settings-for-windows
Both MaxFieldLength and MaxRequestBytes by default are 16kb.

One of the solutions would be to open regedit and go to: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HTTP\Parameters
Add MaxFieldLength and MaxRequestBytes with increased values and restart http service, but keep in mind this warning message from microsoft:
Changing these registry keys should be considered to be extremely dangerous. 
These keys allow larger HTTP packets to be sent to IIS. 
This, in turn, may cause Http.sys to use more memory. 
Therefore, such changes can increase the computer's vulnerability to malicious attacks.

Another solution would be use Cookie SessionStore.
https://github.com/aspnet/Security/tree/dev/samples/CookieSessionSample
This suggests adding 
.AddCookie(o => o.SessionStore = new MemoryCacheTicketStore());
to handle identity storage across sessions.
This way only session identifier is being sent to the client.
More information could be found here:
https://hajekj.net/2017/03/20/cookie-size-and-cookie-authentication-in-asp-net-core/
And
https://github.com/aspnet/Identity/issues/447

This kind of looses the stateless call principle, but if you have multiple services, you could implement your own ITicketStore for Reddis cache by following the MemoryCacheTicketStore example, it's quite easy to do.

Conclusion. As it turns out, my SaveTokens implementation works with smaller tokens, could I make a PR for it? Or you would keep this functionality out of the repository?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
