### ISSUE TITLE
Resource-based authorization with separate authentication scheme and a different default policy

### ISSUE THREAD

**Issue by poke** [aspnet/Security#1721]
I have a maybe weird auth configuration, let me explain it first:

I have cookie authentication as the default authentication handler, and a default authorization policy that performs some checks but is pretty restrictive. In my controllers, I then use the `[Authorize]` attribute to require (cookie) authentication and that the user fulfills the requirements of the default authorization policy. So far so good.

Now, I have a separate authentication scheme, basically a simplified bearer authentication. The authentication handler just looks for a token in the request headers, and if it’s there, it will authenticate the user with a single claim for that token.

For the authorization I have a simple resource-based requirement:

```c#
public class TokenRequirement : AuthorizationHandler<TokenRequirement, MyObject>, IAuthorizationRequirement
{
    protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, TokenRequirement requirement, MyObject resource)
    {
        var token = context.User.FindFirstValue(TokenAuthenticationHandler.TokenClaimType);
        if (token != null && token == resource.Token)
            context.Succeed(requirement);

        return Task.CompletedTask;
    }
}
```

So this basically just gets the token from the claim, and compares it to the token stored in the resource.

Finally, I have a policy set up:

```c#
options.AddPolicy(TokenPolicy, new AuthorizationPolicyBuilder(TokenScheme)
    .RequireAuthenticatedUser()
    .AddRequirements(new TokenRequirement())
    .Build());
```

---

Now, in my controller, I want to authorize the user against the resource, using something like this:

```
var result = await _authorizationService.AuthorizeAsync(User, obj, TokenPolicy);
```

I expected this to work but I had to learn that calling `AuthorizeAsync` will not actually authenticate the user against the schemes specified in the policy. So this would always fail since the user is simply not authenticated and as such the claim is missing.

So I thought about adding an explicit `[Authorize(Policy = TokenPolicy)]` to the controller. This does work in that it will correctly authenticate the user. However, since with the authorize attribute there is no resource passed, the authorization handler will not run and as such the requirement will never be fulfilled. So ultimately, authorization will fail.

I then thought that I could use the authorize attribute with the scheme instead, i.e. `[Authorize(AuthenticationSchemes = TokenScheme)]`. This *also* does authenticate the user correctly but then the *default* policy runs which will obviously fail since it checks something completely different.

So I see two options now:

-  Use no authorize attributes but explicitly call `HttpContext.AuthenticateAsync(TokenScheme)` in the controller code *before* calling the resource-based `AuthorizeAsync`.
- Create a separate policy *just for authentication* so that I can use `[Authorize(Policy = TokenAuthenticationPolicy)]`. The existing policy will then only do the resource-based authorization check.

Both of these work fine but it does not feel correct to me that I have to do this extra stuff. Having a separate authorization policy which is just there to trigger the correct authentication feels weird. Calling `AuthenticateAsync` explicitly feels cleaner to me but has the drawback that this delays the authentication to when the controller code is already executing.

---

I have a hard time to accept that there appears to be no proper way to solve this situation, especially given that the auth stack is so flexibly designed. Am I missing something? What would be the best way to perform the *authentication* step for a resource-based authorization policy?

**Comment by HaoK** [comment]
So let me try to restart your requirements to make sure I understand the scenario properly.

The authorized case is when:
- The user has the cookie which passes the default [Authorize] logic
- And there's token in the request headers which you use to check against a resource based on the controller action being hit

So in this case since your token scheme is pretty simple you can probably get this to work like this as well.
1. You should be able to add TokenScheme to the default policy as well as the cookie, which should result in authenticate getting called on both, and the resulting ClaimsPrincipals should be [merged](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authorization.Policy/PolicyEvaluator.cs#L43)
```
   services.Configure<AuthorizationOptions>(o => o.DefaultPolicy = new AuthorizationPolicyBuilder("Cookies", "Token").RequireAuthenticatedUser().Build();
```

2. You can implement the additional claim as a [IClaimsTransformation](https://github.com/aspnet/AuthSamples/tree/dev/samples/ClaimsTransformation) which will run after every authenticate, so you could use IHttpContextAccessor in your transformation to look at the header and add it to the user generated by the default cookie authentication scheme.  This gets you out of the business of having multiple authentication schemes.

3. You can also do this by explicitly adding a new authentication scheme that combines the cookie and token (this is basically what the new 2.1 "policy scheme" feature is targetting), you would implement IAuthenticationHandler for a "CookiesToken" scheme that would do something like:

```C#
   AuthenticateResult AuthenticateAsync() {
       var result = await Context.AuthenticateAsync("Cookies");
       if (result.Succeeded) {
             if (FindToken(Context)) {
                   AddTokenClaim(result.Principal, Context);
             }
       }
   }

   Task ChallengeAsync(AuthenticationProperties properties) => Context.Challenge("Cookies");
```

In 2.1 you could use the new PolicySchemeHandler base class which is basically the same but lets you forward the challenge via an option:
```C#
   services.AddAuthentication("CookiesToken")
         .AddScheme<PolicySchemeOptions, CookiesTokenHandler >(o => o.ForwardChallenge = "Cookies")
         .AddCookies("Cookies");

   public class CookiesTokenHandler : PolicySchemeHandler {

   // Same as before
   Task<AuthenticateResult> HandleAuthenticateAsync() {
       var result = await Context.AuthenticateAsync("Cookies");
       if (result.Succeeded) {
             if (FindToken(Context)) {
                   AddTokenClaim(result.Principal, Context);
             }
       }
   }
}
```

**Comment by poke** [comment]
Thanks for the detailed response! Unfortunately, you did not get my scenario correct.. Guess I did not explain that well enough, sorry about that!

There are basically two different ways to interact with my application:

The default case is a standard MVC setup with multiple controllers. This uses cookie authentication (and OIDC) to authenticate the user. The protected routes use a default authorization policy which does normal claim based authorization (those claims are provided by the underlying OIDC scheme). There are also a few unprotected MVC routes that simply don’t require authentication. 

Then, there is a single API controller that uses this special authentication handler that reads the token from the request header. This API is not protected by the cookie authentication but should be exclusively accessed by users that include the token in the header.

So the cookie scheme and the token authentication scheme are completely separate and responsible for different parts of the application. Summed up, there are basically three different kinds of users:

- Anonymous users: Can access controller/routes A
- Authenticated (and authorized) users (via cookie): Can access controller/routes A, B, C
- Token user (via token scheme): Can access API controller *if* the passed token matches the token inside the resource.

---

I originally wanted to do the resource-based authorization on an unauthenticated user and just retrieve the token value from the header directly in the AuthorizationHandler instead of getting it from a claim. But there’s actually no way to access the HttpContext from within the AuthorizationHandler – unless I inject the accessor there of course. That’s why I also addded the authentication handler to actually authenticate the “user” (with that one claim).

Of course, a very simple solution would be to just retrieve the token within the controller and perform the check there directly. But I wanted to use the auth stack for this, and my situation appeared to be perfect for resource-based authorization (since that’s literally what I want to do ^^).

**Comment by HaoK** [comment]
Does this work for you then?

- Routes A: should be [AllowAnonymous] or not protected with [Authorize]
- Routes B/C: [Authorize("Cookies")] or [Authorize] if you use cookies as your default scheme
- API controller [Authorize("Token")] should result in context.User = Authenticate("Token") and then you can use that to do resource based authZ.

**Comment by HaoK** [comment]
Basically if you aren't trying to mix and match routes/endpoints between cookies and bearer users this should work fine.  The big trouble is when you want the same route to be accessible via either Cookies OR token

**Comment by poke** [comment]
Yes, that’s what I’m doing, having two separate policies for the token stuff: One for authentication and one for resource-based authorization. But I’m wondering if there’s a better way, or if there *should* be a better way. Some way to do this properly without creating an *authorization* policy just for *authentication* purposes.

Why are resource-based authorization requirements even considered for authorization through the authorize attribute? Those will never succeed since the resource is missing.

**Comment by HaoK** [comment]
I'm not sure what you mean, aren't you doing actually doing authorization via the token.  Letting only API requests succeed with the appropriate token seems more like authorization than authentication (which would only be get me the token).  Arbitrary, resource based authorization isn't currently supported via the authorize attribute at all.  Its only something you can do imperatively.  If you go through an `[Authorize]` attribute, the resource passed into the authorization handlers are always the MVC specific authorization filter context, but this lets you get to the request and basically anything else that you want.

**Comment by poke** [comment]
> aren't you actually doing authorization via the token?

Yes, but before you can do authorization, you need some sort of authentication, no? I want to use authentication to get the token, and authorization to validate the token then.

>  Arbitrary, resource based authorization [is] only something you can do imperatively.

Yeah, I know and I’m totally fine with that. My point is that using a authorization policy that includes such arbitrary resource-based requirements cannot be used for *authentication*. And that feels a bit wrong because it means we always have to have explicit separate policies for authentication.

Anyway, I think we’re going in circles a bit. I am aware of how I can solve my situation, it’s just that the way the auth stack does this does not feel right to me.

**Comment by brockallen** [comment]
All sounds very complicated. Why not split this into 2 different hosts, each with its own security configuration? Cookies vs tokens are two fundamentally different schemes and require different security protections.

**Comment by poke** [comment]
@brockallen Because in this case the API controller actually just contains a single endpoint which is used by an external application to push data to the web application. The whole thing is very self-contained and splitting it up into separate hosts would be overengineered and simply not appropriate for the use case.

In general though: ASP.NET Core supports multiple authentication methods, and multiple authorization setups. So yeah, there are different schemes and different protections but that scenario is generally well supported by the auth stack.

**Comment by brockallen** [comment]
I'm just saying those are two distinct security models and concerns. Beware XSRF for when you allow cookies.

**Comment by HaoK** [comment]
@poke if you could imagine an API for your scenario how would you want to express what you describe?

**Comment by poke** [comment]
Hmm, I think what confused me most was that I configured an authorization policy with an explicit authentication scheme and calling `AuthorizeAsync` with that policy completely ignored that. I think I expected this call to also look at the authentication schemes of the policy, requiring one those as well. – But I understand why this is not the case, after all I’m passing a claims principal to the call which should be the basis for the authorization.

The other thing is that I can use the authorize attribute with a policy that contains a resource requirement which—by design—could never succeed through the authorize filter.

Since I’d rather want authentication outside of a controller action (so that `HttpContext.User` is properly set), I don’t think doing something about the authorization service would be good. What I could image though, is a way to tell the authorize attribute or the policy directly to ignore resource-based requirements. Since those will have to be evaluated explicitly in code anyway, ignoring them should make this a bit nicer.

To not break compatibility, maybe it would be an additional flag, e.g. `[Authorize(Policy = "my-policy", SkipResourceRequirements = true)]`. Or maybe even set a flag as part of the policy builder, e.g.

```c#
options.AddPolicy(TokenPolicy, new AuthorizationPolicyBuilder(TokenScheme)
    .RequireAuthenticatedUser()
    .AddRequirements(new TokenRequirement(), skipAuthorizeFilter: true)
    .Build());
```
Or a `.SkipResourceRequirementsInAuthorizeFilter()` or whatever.

**Comment by HaoK** [comment]
AuthorizationPolicies were basically a mechanism to attach names to a pair of metadata: authentication schemes and authorization requirements for use in attributes.  The only real authorization inputs are the the ClaimsPrincipal + resource + list of requirements

**Comment by poke** [comment]
> I'm not sure I understand why you need a mechanism to skip these policies in code

Basically I just wanted to avoid having to create separate policies with and without those resources requirements.

> You can also just skip the entire policy thing and use the the other AuthorizeAsync method:
>
> ```
> authService.AuthorizeAsync(context.User, resource, new TokenRequirement());
> ```

Yeah, I think that’ll be the best thing to do after all.

It’s a shame though since I think policies are a great way to move the responsibility to set up the authorization rules to a single location; but at the same time I don’t like having to duplicate the requirements just for separate authentication and authorization..

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
