### ISSUE TITLE
Issues with authenticating

### ISSUE THREAD

**Issue by MichaelBTR** [aspnet/Security#1722]
We have an application that we are migrating from ASP .NET Core 1.1 to 2.0. There's an auth endpoint that allows JWT tokens that can be validated using known RSA keys, or those obtained once a user has signed in with an AAD account from a specific tenant (the sign in process is done via a separate website). This auth endpoint would then return an API token that can be used on other endpoints. Upon trying to migrate, a couple of issues have occurred

1. we're not sure how to enable such a workflow given the changes to the how authentication works now
2. we've tried to reduce the code to just accept AAD tokens to debug what's going on, such that the code looks as follows

```c#
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(jwtOptions =>
                    {
                        jwtOptions.Authority = aadSettings.AADInstance + aadSettings.TenantId;
                        jwtOptions.Audience = aadSettings.Audience;
                        jwtOptions.Events = new JwtBearerEvents
                        {
                            OnAuthenticationFailed = AuthenticationFailed
                        };
                    });
```

however, the code in the auth endpoint (action) is never invoked although Fiddler shows a 200 response although there's no response body. The code does work upon removing the Authorize attribute.

Any ideas on how to solve the above issues?

**Comment by Tratcher** [comment]
What's in AuthenticationFailed?

**Comment by MichaelBTR** [comment]
It's empty and isn't fired. Looking at the output logs and handling the OnTokenValidated event shows that the token was successfully validated

**Comment by MichaelBTR** [comment]
Spent more time investigating and it looked like the differences between the lifetime of our authorisation handlers and db context had messed up the behaviour of the middleware. Will look into trying to implementing the auth workflow as I described but would appreciate if anyone could provide some pointers

**Comment by MichaelBTR** [comment]
Managed to figure it out now by creating multiple authentication schemes, setting the default one and using the authorize attribute to change the ones that should be used when required. Closing the issue but if there's a better way of doing then please do let me know :)
