### ISSUE TITLE
Configurable SessionIdClaim when using cookie claim storage

### ISSUE THREAD

**Issue by chrisowhite** [aspnet/Security#1724]
When using cookie authentication with an implementation of `ITicketStore` a constant in `CookieAuthenticationHandler` is used when creating the identity for the auth ticket. This is fine when sharing the cookie between Core apps, but is a problem when trying to share the cookie between a core app and another app using the Katana middleware.

I think adding a property to `ITicketStore` would do the trick. If that property is null from the implementation, use the constant instead.

Thoughts? This would be a breaking change for anyone that currently is using the `SessionStore` option as they would have to add the property to their implementation.

**Comment by Tratcher** [comment]
API breaking changes are not an option for 2.1. Adding something to CookieAuthOptions would be more feasible.

**Comment by chrisowhite** [comment]
Derp, yeah clearly a better option. I can submit a PR.

**Comment by Tratcher** [comment]
Sure, give it a try and we'll see how it looks.

**Comment by chrisowhite** [comment]
Any suggestion on where in that object graph it seems most at home?

**Comment by Tratcher** [comment]
Top level on CookieAuthOptions.

**Comment by chrisowhite** [comment]
I know it's a different repo, but thoughts on making this change in Katana? I'll probably be forking there for the time being so I can keep moving along.

**Comment by Eilon** [comment]
Closing because we are not planning to implement this.
