### ISSUE TITLE
Using Microsoft.AspNetCore.Authentication.JwtBearer in Azure

### ISSUE THREAD

**Issue by haydenhancock** [aspnet/Security#1727]
I seem to be having issues when using Microsoft.AspNetCore.Authentication.JwtBearer with a .NET Core 2.0 web API published (using Web Deploy in Visual Studio) to Azure. Everything works locally; however, when I publish my application to Azure, I receive '500' errors. I've attempted to collect information from Kudu but everything appears to be normal. There are no errors in the build output when publishing to Azure either. If I remove the Jwt implementation, and re-publish, I have no issues with calling my web API in Azure. Has anyone else experienced this issue?

**Comment by Tratcher** [comment]
Try these:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/troubleshoot?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-azure

**Comment by haydenhancock** [comment]
Well, after reviewing my application settings, I realized there was a mistake. I resolved this in my appsettings.json file and re-published and it's working as expected.

Thanks,
