### ISSUE TITLE
Map causes wrong ReturnUrl parameter for Cookies

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1730]
```
            app.UseAuthentication();

            app.Map("/hello", map =>
            {
                map.Run(async context =>
                {
                    if (!context.User.Identities.Any(identity => identity.IsAuthenticated))
                    {
                        await context.ChallengeAsync();
                        return;
                    }

                    context.Response.ContentType = "text/plain";
                    await context.Response.WriteAsync("Hello old timer");
                });
            });
```

If UseAuthentication is outside of the Map, and ChallengeAsync is called inside the Map, then CookieAuth generates the wrong ReturnUrl parameter. 
https://github.com/aspnet/Security/blob/2e3a1071a884de19d33daa00bbdc2b7614d73646/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L436

In the example `http://localhost:12345/hello/world?query`, it uses the OriginalPathBase (empty) but the current request Path "/world" and redirects to "/world?query". It should use the OriginalPathBase "" and the OriginalPath "/hello/world" rather than the current Path.

**Comment by muratg** [comment]
Workaround:
```c#
                    await context.ChallengeAsync(new AuthenticationProperties()
                    {
                        // https://github.com/aspnet/Security/issues/1730
                        // Return here after authenticating
                        RedirectUri = context.Request.PathBase + context.Request.Path + context.Request.QueryString
                    });
```

**Comment by Eilon** [comment]
Won't Fix because there is not enough demand for this.
