### ISSUE TITLE
[2.0] After successfully SignIn "IsAuthenticated" (IIdentity) property is always false even all claims are set.

### ISSUE THREAD

**Issue by MarcinSzyszka** [aspnet/Security#1731]
Hi.

My code in ConfigureServices method in Startup.cs

`            services.AddAuthentication()
                .AddCookie(c =>
                {
                    c.LoginPath = new PathString("/User/SignIn");
                    c.ExpireTimeSpan = TimeSpan.FromDays(1);
                    c.SlidingExpiration = true;
                    c.Cookie.Name = "RodoApiAuthCookie";
                    c.AccessDeniedPath = "/User/AccessDenied";
                })
                .AddJwtBearer(opt =>
                {
                    opt.Audience = Configuration["Auth:Audience"];
                    opt.ClaimsIssuer = Configuration["Auth:Issuer"];
                    opt.SaveToken = true;
                    opt.TokenValidationParameters = new TokenValidationParameters
                    {
                        RequireExpirationTime = true,
                        RequireSignedTokens = true,
                        ValidateIssuerSigningKey = true,
                        IssuerSigningKey = signingKey,
                        ValidateIssuer = true,
                        ValidIssuer = Configuration["Auth:Issuer"],
                        ValidateAudience = true,
                        ValidAudience = Configuration["Auth:Audience"],
                        ValidateLifetime = true,
                        ClockSkew = TimeSpan.Zero
                    };
                });`

After succesfully SignIn I can't use ` [Authorize(AuthenticationSchemes = [SLECETED_SCHEMES])]` becasue "IsAuthenticate" property is set to false but all claims created during the SignIn are set:

![image](https://user-images.githubusercontent.com/14890675/38920764-55599680-42f4-11e8-9f2f-34aeb1a8ccfe.png)

How can I use [Authorize] attribute without getting acces denied?

Best regards.

**Comment by HaoK** [comment]
You need to specify an AuthenticationType in the claims identity as that's what IsAuthenticated is testing

**Comment by MarcinSzyszka** [comment]
@HaoK big up for you. Thanks. Issue can be closed.
