### ISSUE TITLE
.AspNetCore.Correlation. state property not found

### ISSUE THREAD

**Issue by davdev82** [aspnet/Security#1732]
I am having errors. ".AspNetCore.Correlation. state property not found" within OIDC Handler. It does not happen all the time, but when it does none of our customers can login and the page is stuck at "/signin-oidc". The only way out is to recycle app pool. We do not have multiple OIDC handlers configured.

I have noticed that the version of the OIDC middleware has been upgraded to 2.0.3, so it might be worth trying that approach to see if it fixes the intermittent errors. But can anyone point out what has been released as part of 2.0.3

**Comment by Tratcher** [comment]
Don't expect any changes here between 2.0 and 2.0.3. It's very suspicious that everybody would get the error at the same time. It might be a data protection error, possibly a bad key rollover. Does anything show up in the application logs?

**Comment by Tratcher** [comment]
That's odd. Have you customized the OIDC settings at all?

**Comment by davdev82** [comment]
I have followed what the documentation says, and the fact is it works. But when it does not it throws the ASP.Net Core State Property not found error. There have been other users facing the same issue

https://github.com/IdentityServer/IdentityServer4/issues/2115

**Comment by davdev82** [comment]
I have posted my query there as well just to see if anyone has an answer

**Comment by davdev82** [comment]
services.AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                })
                .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
                {
                    options.SlidingExpiration = false;
                    options.ExpireTimeSpan = TimeSpan.FromHours(2);
                })
                .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
                {
                    options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.Authority = _configuration.GetValue<string>("auth:oidc:authority");
                    options.ClientId = _configuration.GetValue<string>("auth:oidc:clientId");
                    options.ClientSecret = _configuration.GetValue<string>("auth:oidc:clientSecret");
                    options.AuthenticationMethod = OpenIdConnectRedirectBehavior.RedirectGet;
                    options.ResponseType = OpenIdConnectResponseType.Code;
                    options.SaveTokens = true;
                    options.GetClaimsFromUserInfoEndpoint = true;
                    options.Scope.Clear();
                    options.Scope.Add("openid");
                    options.Scope.Add("info");
                    options.RequireHttpsMetadata = !_environment.IsDevelopment();
                    options.UseTokenLifetime = true;
                    options.Events = new OpenIdConnectEvents
                    {
                        OnRedirectToIdentityProvider = context =>
                        {
                            if (context.ProtocolMessage.RequestType == OpenIdConnectRequestType.Authentication)
                            {
                                if (context.HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                                {
                                    context.Response.StatusCode = (int) HttpStatusCode.Unauthorized;
                                    context.HandleResponse();
                                    return Task.FromResult(0);
                                }
                            }

                            return Task.FromResult(0);
                        }
                    };
                });

**Comment by Tratcher** [comment]
Ok, no interesting customizations there. I don't have any other ideas at the moment except to hook into the events and add extra logging around the suspect values.
https://github.com/aspnet/Security/blob/48dceba628d4d4f15dd70b71dcdd55c4d7dad7e0/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L345
https://github.com/aspnet/Security/blob/48dceba628d4d4f15dd70b71dcdd55c4d7dad7e0/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L470
That or contacting support next time you have a repro and trying to do some live debugging.

**Comment by davdev82** [comment]
Well adding the logging to RedirectToIdentityProvider will not help as the culprit here is the **"State"**, but that is not passed in when the event is raised, The state is calculated and protected after the Redirect event is raised. So logging a before and after state cannot be done

**Comment by frankyvij** [comment]
Hey, did you manage to solve the issue? I have the same problem. The authentication with Microsoft OpenId was working fine, but all of a sudden, it stopped working. I did not update any library (using the same version 2.0.3).

Following is the error I get:
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: .AspNetCore.Correlation. state property not found.

**Comment by sathiathirumal** [comment]
Are you all running behind a reverse proxy perhaps? I have been hitting "Correlation failed" exception during OIDC auth challenge as well BUT only when running behind Azure Application Gateway. One more sign is when running in Incognito browser mode AND azure app gateway - its a 100% repro in that case.

**Comment by gianibob82** [comment]
I'm using AWS Cognito as OpenId and I'm having the same problem. It works fine when debugging using IIS Express but when I deploy to AWS API Gateway I get the error. Probably @sathiathirumal  is on the right track but I can't find any solution for now...

**Comment by gianibob82** [comment]
Thanks @KevinDockx ! That's exactly the problem. In my case I'm storing the keys in S3

**Comment by sathiathirumal** [comment]
Also see https://github.com/aspnet/Security/issues/1755#issuecomment-392803709. Related to what @KevinDockx says.

**Comment by bdparrish** [comment]
@KevinDockx - I am seeing this with NGINX, but I only have a single server.  Any ideas what this would be coming from since the session is not being shared across multiple servers?

**Comment by Tratcher** [comment]
@bdparrish can you share a Fiddler trace of the login flow? Also your Nginx config?

**Comment by bdparrish** [comment]
@Tratcher - disregard, seemed to be a phantom error.  I couldn't recreate it after restarting the cluster of services.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
