### ISSUE TITLE
Incorrect request format when exchanging authorization_code for tokens

### ISSUE THREAD

**Issue by jdmichel** [aspnet/Security#1737]
Per OIDC spec 2.1.6.1 the Client Id and Secret must be encoded into the Authorization header.
http://openid.net/specs/openid-connect-basic-1_0.html#TokenRequest

I have a PR that might fix the bug, but I can't get the source to build. (version '2.1.0-preview3-26413-05' was not found.) Too much hassle to get this built. Installed VS 15.7 and latest available 2.1 preview and still errors. 

I also have a much more tedious workaround for our actual application that involves implementing my own RedeemAuthorizationCodeAsync at the app level.

**Comment by PinpointTownes** [comment]
FYI, this was already discussed here: https://github.com/aspnet/Security/issues/1032.

**Comment by muratg** [comment]
Yup, this is dup of #1032. Closing.
