### ISSUE TITLE
CurrentUri in AuthenticationHandler is headache under load balancers

### ISSUE THREAD

**Issue by ZOXEXIVO** [aspnet/Security#1739]
For services under load balancers, code like this

`return Request.Scheme + "://" + Request.Host + OriginalPathBase + targetPath;`

in AuthenticationHandler is really terrible. 
We can't override it and projects must be using X-Forward-Proto headers and other things.

Why you can't take this control to client-side if needed ?

**Comment by Tratcher** [comment]
Duplicate x100
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1

**Comment by ZOXEXIVO** [comment]
We know about this configuration, but why we need do this, if we can take control for building url in our hands?

**Comment by Tratcher** [comment]
Because you'd have to do the same thing in a dozen other places too. Lots of components in the stack work from the request fields and depend on them being accurate.
