### ISSUE TITLE
Jwt - IDX10500: Signature validation failed. No security keys were provided to validate the signature.

### ISSUE THREAD

**Issue by makcakaya** [aspnet/Security#1741]
v 2.0.1

I am trying to get Controller.User set by using JWT authentication but I don't want to validate anything (because I do it in another app already).

I am getting following exception:

```
Failed to validate the token eyJhbGciOiJSU...
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.
```

```
// Inside ConfigureServices()
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidateActor = false,
                        ValidateAudience = false,
                        ValidateIssuer = false,
                        ValidateIssuerSigningKey = false,
                        ValidateLifetime = false
                    };
                    options.Validate();
                });

// Inside Configure()

 app.UseAuthentication();
```

What might be the problem? As I said I don't want any validation but the library throws a validation exception.

**Comment by HaoK** [comment]
You need to configure the appropriately named JwtBearer that you specified in AddAuthentication()

```
.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
```

**Comment by Tratcher** [comment]
There are some validations that can't be turned off. @brentschmaltz

**Comment by makcakaya** [comment]
@Tratcher The other validation code is completely seperate, it is in another application (AWS Gateweay Authorizer), and yes it will run first.

**Comment by makcakaya** [comment]
This middleware seems to do the job for me. I am sharing it here in case anyone else needs it.

```
  public sealed class JwtMiddleware
    {
        private static readonly string Bearer = "bearer";
        private readonly JwtSecurityTokenHandler _handler = new JwtSecurityTokenHandler();
        private readonly RequestDelegate _next;

        public JwtMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task Invoke(HttpContext context)
        {
            var token = context.Request.Headers[HeaderNames.Authorization].ToString();
            if (!token.ToLower().StartsWith(Bearer))
            {
                throw new InvalidOperationException("Expected {0} at the start of the token.");
            }

            var jwt = _handler.ReadJwtToken(token.Substring(Bearer.Length).TrimStart());
            context.User = new ClaimsPrincipal(new ClaimsIdentity(jwt.Claims));

            await _next(context);
        }
    }
```

Then in your `Startup.cs`:
```
app.UseMiddleware<JwtMiddleware>();
```

Now, in your controller you can get the User as usual:
```
var userId = User.Claims.First(c => c.Type == JwtRegisteredClaimNames.Sub);
```

**Comment by brentschmaltz** [comment]
@Tratcher @makcakaya you set the delegate TokenValidationParameters.SignatureValidator to just return a JwtSecurityToken.

Why don't  you want to validate the token in the pipeline?

**Comment by makcakaya** [comment]
@brentschmaltz Thanks for the info. 

Just to make my case clear, the validation of JWT is done in another application (call it application A) (AWS Custom Authorization). If only the validation succeeds, then that application (A) passes/redirects the original request to my application (application B). So there is no request from B to A for authorization.
