### ISSUE TITLE
dynamically changeable authentication based on host name

### ISSUE THREAD

**Issue by martindrlik** [aspnet/Security#1743]
It is possible to have multiple authentications (and options) and choose relevant one let say based on host name? For instance assume several companies hosted by application and each has their own AppId and AppSecret for Facebook authentication, or event different authentication e.g. Google.
```
company1.example.com // has facebook with own appId and secret
company2.example.com // has facebook with own appId and secret
company3.example.com // has facebook, google or other enabled
```
Note that AppId and AppSecret or what authentication can be used is unknown in the time when `ConfigureServices` method in the *Startup.cs* file is called.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/AuthSamples/pull/44

**Comment by blowdart** [comment]
I'm going to assume the thumbs up means you got your answer and the issue can be closed. If this isn't the case feel free to reopen it.
