### ISSUE TITLE
The oauth state was missing or invalid

### ISSUE THREAD

**Issue by justinhelgerson** [aspnet/Security#1744]
I can't seem to get past this exception when using the Salesforce OAuth package from [aspnet-contrib](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers).

> Exception: The oauth state was missing or invalid.
> 
>     Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>     Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

My `Startup.cs` class is fairly generic:

```
public class Startup {
        public Startup(IConfiguration configuration) {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services) {
            services.AddMvc();

            services.AddAuthentication(options => {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            })
            .AddCookie(options => {
                options.LoginPath = "/signin";
                options.LogoutPath = "/signout";
            })
            .AddSalesforce(salesforceOptions => {
                salesforceOptions.ClientId = "real-client-id-is-here";
                salesforceOptions.ClientSecret = "real-secret-is-here";
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env) {
            if (env.IsDevelopment()) {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            } else {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();
            app.UseAuthentication();
            app.UseMvc(routes => {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
```

I've been starting to dig into the source code for the OAuth handler, but I'm not sure why it's not able to read the state (or why it considers it invalid).  Salesforce is in fact returning a state parameter in the callback:

> https://localhost:44384/signin-salesforce?code=aPrxzp43SUYOZpHHFKio3l3Y3YUl6JV8a78QcATZYv14ygc5Jr5f4iHEPk1lCnMjiZW65_1BOw==&state=CfDJ8DJf4Bm-ZqJErpelQNxzmFbtI601Cob4p5K6XXuHoT0kXQhA4x7H8ql2cQs0kW78zatwipZ3ROgmd87f-k7GiITu39ugRTFAprQJgEiGkvDe_qRR40re1e3vabvJ5DzHOdTqygfi3Xi1jupZxk9wm350caczN2sjuXk2znqdEUmPXGRlIGDzmVA91xhVVDXATdKJn1_gqHY5kJYTlsFk1ybqf8RLGcn3nuulFJ1A3COW

Any suggestions would be appreciated.

ref: aspnet-contrib/AspNet.Security.OAuth.Providers/issues/236

**Comment by Tratcher** [comment]
Can you share a Fiddler trace of the login flow?

The state parameter would have to be corrupted, or you've have to be having issues with data protection trying to decrypt it. Are you debugging this with a single instance of the app? Or do you have multiple instances running?

**Comment by justinhelgerson** [comment]
Thanks for the reply @Tratcher.  This is a single instance.

I haven't used Fiddler in ages, and it doesn't seem to play well with IIS Express / localhost.  I'll see if I can get it working; in the meantime, I've attached an HTTP Archive of only the relevant requests:
[OAuth-HAR.txt](https://github.com/aspnet/Security/files/1967687/OAuth-HAR.txt)

**Comment by Tratcher** [comment]
That's weird. Your request to https://localhost:44384/signin-salesforce has all of the right parameters, successfully authenticates, but then it redirects back to itself at https://localhost:44384/signin-salesforce, which fails because it's missing the required parameters. Why would it return to itself? It's supposed to return to the url that initiated the challenge unless you overwrote that when calling challenge?

**Comment by justinhelgerson** [comment]
I was able to get this straightened out.  Your comment

> overwrote that when calling challenge

triggered a thought.

I assumed I had to handle the OAuth response, but the handler takes care of processing that response for you.  I was overriding the redirect, but that action had an incorrect `Route` attribute using the same route as the OAuth callback.  The OAuthHandler then takes over that request and tries to process it, but of course the OAuth parameters are missing.  This was a routing mistake on my part (essentially having a route with the same path as the callback path).

Thanks for your quick response.  And FWIW, your responses to the community have been very helpful while researching ASP.NET Core issues, features, etc.  I come across your posts a lot.

**Comment by mananchoksi007** [comment]
@justinhelgerson I have the same issue. Can you please share the fix that you have made to your code?

**Comment by justinhelgerson** [comment]
@mananchoksi007 You could get this error in a few different ways depending on your configuration.  My issue is that I had an action in my controller trying to handle the callback.  This isn't necessary; the middleware will take care of it for you.

If you need more help you'd have to share more info like your configuration and HTTP flow.

**Comment by mananchoksi007** [comment]
I am using pivotal cloud foundry service to authenticate the application. Here is my configuration. 


   public void ConfigureServices(IServiceCollection services)
        {
            services.AddOptions();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddSingleton<IConfiguration>(Configuration);


                services.AddAuthentication(options =>
                {
                    options.DefaultChallengeScheme = CloudFoundryDefaults.AuthenticationScheme;
                })
                    .AddCookie((options) =>
                    {
                        options.AccessDeniedPath = new PathString("/AccessDenied");
                    })
                    .AddOAuth<CloudFoundryOAuthOptions, CloudFoundryOAuthHandler>(CloudFoundryDefaults.AuthenticationScheme, CloudFoundryDefaults.DisplayName, (options) =>
                    {
                        var securitySection = Configuration.GetSection(CloudFoundryDefaults.SECURITY_CLIENT_SECTION_PREFIX);
                        securitySection.Bind(options);

                        SsoServiceInfo si = Configuration.GetSingletonServiceInfo<SsoServiceInfo>();

                        options.Scope.Add("openid");
                        options.Scope.Add("roles");
                        options.Scope.Add("user_attributes");
                        options.Scope.Add("uaa.user");
                        options.Scope.Add("profile");

                        if (options == null)
                        {
                            return;
                        }

                        if (si != null)
                        {
                            options.ClientId = si.ClientId;
                            options.ClientSecret = si.ClientSecret;
                            options.AuthorizationEndpoint = si.AuthDomain + CloudFoundryDefaults.AuthorizationUri;
                            options.TokenEndpoint = si.AuthDomain + CloudFoundryDefaults.AccessTokenUri;
                            options.UserInformationEndpoint = si.AuthDomain + CloudFoundryDefaults.UserInfoUri;
                            options.TokenInfoUrl = si.AuthDomain + CloudFoundryDefaults.CheckTokenUri;
                        }

                        //options.Events = new OAuthEvents
                        //{
                        //    OnCreatingTicket = async ctx =>
                        //    {
                        //     var user = ctx.Identity.Name;

                        //        if (user != null)
                        //        {
                        //            Console.WriteLine(user);

                        //        }
                        //    }
                        //};

                        options.SaveTokens = true;

                        options.BackchannelHttpHandler = CloudFoundryHelper.GetBackChannelHandler(options.ValidateCertificates);
                    });

                services.AddMvc(o =>
                {
                    var policy = new AuthorizationPolicyBuilder()
                                .RequireAuthenticatedUser()
                                .Build();
                    o.Filters.Add(new AuthorizeFilter(policy));
                });


                //services.AddAuthorization(options => options.AddPolicy(Constants.DLP_Role, policy => policy.RequireClaim(ClaimTypes.Role, Constants.DLP_Role)));
              services.Configure<RequestLocalizationOptions>(
              options =>
              {
                  var supportedCultures = new List<CultureInfo>
                      {
                            new CultureInfo("en-US"),
                            new CultureInfo("de-CH"),
                            new CultureInfo("fr-CA"),
                            new CultureInfo("it-CH")
                      };

                  options.DefaultRequestCulture = new RequestCulture(culture: "en-US", uiCulture: "en-US");
                  options.SupportedCultures = supportedCultures;
                  options.SupportedUICultures = supportedCultures;

                     // You can change which providers are configured to determine the culture for requests, or even add a custom
                     // provider with your own logic. The providers will be asked in order to provide a culture for each request,
                     // and the first to provide a non-null result that is in the configured supported cultures list will be used.
                     // By default, the following built-in providers are configured:
                     // - QueryStringRequestCultureProvider, sets culture via "culture" and "ui-culture" query string values, useful for testing
                     // - CookieRequestCultureProvider, sets culture via "ASPNET_CULTURE" cookie
                     // - AcceptLanguageHeaderRequestCultureProvider, sets culture via the "Accept-Language" request header
                     options.RequestCultureProviders.Insert(0, new QueryStringRequestCultureProvider());
              });

            services.AddSession(options =>
            {
                options.IdleTimeout = TimeSpan.FromHours(2);
            });
            services.Configure<FormOptions>(options =>
            {
                options.ValueCountLimit = int.MaxValue;
            });

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseSession();

            if (env.IsDevelopment() || Env.EnvironmentName.Equals("Local"))
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
            }

            app.UseAuthentication();

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }

**Comment by justinhelgerson** [comment]
What endpoint in your application is handling the callback?  Is it receiving a state parameter?

**Comment by mananchoksi007** [comment]
"authorizationEndpoint": "https://vspdev2.vsp.pp.gm.com/oauth/authorize",
        "tokenEndpoint": "https://vspdev2.vsp.pp.gm.com/oauth/token",
        "userInformationEndpoint": "https://vspdev2.vsp.pp.gm.com/userinfo",
        "tokenInfoUrl": "https://vspdev2.vsp.pp.gm.com/check_token",

**Comment by mananchoksi007** [comment]
not sure about state parameter
