### ISSUE TITLE
Role string mapping in Role based authorization?

### ISSUE THREAD

**Issue by sonichanxiao** [aspnet/Security#1745]
I am thinking using RequireRoles() method to filter AD group user at application global level(if user's account is not in the AD group, access will be denied).

So I added this within ConfigureServices in Startup.cs:
```
services.AddMvc(config =>
{
	var policy = new AuthorizationPolicyBuilder()
					 .RequireAuthenticatedUser()
					 .RequireRole("[domain name]\dev group")
					 .Build();
	config.Filters.Add(new AuthorizeFilter(policy));
});
```

Not sure if this is the way to specify AD group name?

**Comment by blowdart** [comment]
You shouldn't need the domain name, at least not if you're using Integrated Auth,.

**Comment by sonichanxiao** [comment]
So you are saying, as the application runs on internal network within a domain. it should be able to identify the "dev group" (AD group) by just doing this?
```
services.AddMvc(config =>
{
	var policy = new AuthorizationPolicyBuilder()
					 .RequireAuthenticatedUser()
					 .RequireRole("dev group")
					 .Build();
	config.Filters.Add(new AuthorizeFilter(policy));
});
```

Do I need to connect to AD or something?

**Comment by blowdart** [comment]
You need to configure [windows authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.1&tabs=aspnetcore2x).

**Comment by sonichanxiao** [comment]
Yes, I have set windowsAuthentication to be true in launchSettings.json file
```
"iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": false,
```

**Comment by blowdart** [comment]
If you're behind IIS did you also configure IIS?

**Comment by sonichanxiao** [comment]
I am currently running the application on my local dev machine. should I also configure it under launchSettings.json->profiles->IIS Express?

**Comment by blowdart** [comment]
No there's an option in the VS project property dialog you can tick

![snip_20180504111947](https://user-images.githubusercontent.com/796298/39645683-ff7c455e-4f8d-11e8-927d-10624954f2e0.png)

**Comment by blowdart** [comment]
Uncheck Enable Anonymous and check Enable Windows Authentication.

Then in your view just output User.Identity.Name and see what you get

**Comment by sonichanxiao** [comment]
Yes, I have done that.
And it shows the current user's domain name [domain]\[username]

**Comment by blowdart** [comment]
OK cool, so you're logged in

Now try User.IsInRole("Users") and User.IsInRole("Administrators"), then User.IsInRole("Domain\Users") and User.IsInRole("Domain\Administrators"). Do they match? (Replacing domain with, well, your domain).

I believe this varies according to config. But Domain\ should always talk to the domain.

And then you can see what groups you're in via the command prompt

net user /domain <your username>

You don't get spaces, you end up with _s as an FYI

**Comment by sonichanxiao** [comment]
User.IsInRole("Users") returns true
User.IsInRole("Administrators") returns false
User.IsInRole(@"[domain]\Users") returns false
User.IsInRole(@"[domain]\Administrators") returns false

I even tried:
User.IsInRole(@"[domain]\[group alias name]") 
and it still returns false

**Comment by blowdart** [comment]
So in this because, I *think* (because Windows auth belongs to Windows and it's hard to remember the rules), because your PC is in the domain you don't need to specify the domain.

@User.IsInRole("DEVDIV_ORG_FTE_REDMOND")
@User.IsInRole("REDMOND\\DEVDIV_ORG_FTE_REDMOND")

Both return true for me.

**Comment by sonichanxiao** [comment]
I tried User.IsInRole("[group alias name]"), it still return false;

**Comment by blowdart** [comment]
Are you testing with yourself, or with someone else? And your local machine you're testing on is domain joined?

**Comment by sonichanxiao** [comment]
I am testing myself, on my local dev box.

Some updates, I tried using this command gpresult /r in command, tried a few random groups showing there, it works. But in AD explorer, under a specific account's memberOf field, some groups showing in AD are not in the group list generated from command.

**Comment by blowdart** [comment]
Remember there are two types of groups in AD, security groups and distribution groups.  You can only acl on security groups.

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
