### ISSUE TITLE
Add API Key authentication to this library

### ISSUE THREAD

**Issue by jamesharling** [aspnet/Security#1746]
Hi

I've just finished porting my Owin API key authentication project to .NET Core, and it can be found here: https://github.com/jamesharling/Microsoft.AspNetCore.Authentication.ApiKey. I wanted to upload this package to NuGet but you have a prefix reservation active, meaning I am unable to do so. The Owin version has proved popular and I've had requests to port it to .NET Core, so I wondered if we could discuss one of these options:

- Delegate the prefix reservation so this package can be maintained separately by me
- Incorporate the code in this repository (via fork and PR perhaps), and have the ASP.NET team manage the packaging etc.

I'd be keen to hear your thoughts!

Thanks

**Comment by Tratcher** [comment]
We recommend taking projects like this over to https://github.com/aspnet-contrib and/or dropping the Microsoft naming prefix.

**Comment by jamesharling** [comment]
Thanks for the feedback. @Tratcher do you know how to get a repository under `aspnet-contrib`? All members are hidden in that org.

**Comment by Tratcher** [comment]
@PinpointTownes ?

**Comment by PinpointTownes** [comment]
@jamesharling not sure why the members are not public. Thanks for pointing that out, I'll take a look.

@Tratcher unfortunately, I can't accept new projects ATM (I already maintain 60 packages as part of the contrib initiative and without help, it's hard to keep up). If you guys offered to help with reviewing PRs/managing issues/fixing things, I'd certainly reconsider that (I don't mention financial support 'cause it's certainly out of the question :sweat_smile:).

**Comment by Tratcher** [comment]
@PinpointTownes understood. You've done a good job to juggle that many.

@jamesharling AspNet.Security.ApiKey or AspNetCore.Authentication.ApiKey sound good.

**Comment by jamesharling** [comment]
FYI this library is now uploaded as [AspNet.Security.ApiKey.Providers](https://github.com/jamesharling/AspNet.Security.ApiKey.Providers).
