### ISSUE TITLE
AuthorizeAsync with ConfigureAwait(false)

### ISSUE THREAD

**Issue by Tobias-Gr** [aspnet/Security#1749]
Hi,

is it safe/recommended to use AuthorizeAsync with ConfigureAwait(false) in an ASP.NET Core WebAPI-project? E. g.:

if ((await authorizationService.AuthorizeAsync(User, userLogin, Operations.Read).ConfigureAwait(false)).Succeeded)
{...}

Thanks!
Tobias

**Comment by blowdart** [comment]
Why do you think you need it? There's no SynchronizationContext in Core.

**Comment by Tobias-Gr** [comment]
We thought that using ConfigureAwait(false) might have performance benefits (like it does in other contexts). But I'm not well versed in the details of ASP.NET Core. So this idea might be wrong.

**Comment by blowdart** [comment]
Paging @davidfowl, performance question ...

Although honestly, I wouldn't use performance as a reason to do odd things with anything security related.

**Comment by davidfowl** [comment]
There's no need to use ConfigureAwait in ASP.NET Core as there's no SynchronizationContext, it is a no-op.  Closing this issue
