### ISSUE TITLE
UserManager.IsLockedOutAsync is always returning false

### ISSUE THREAD

**Issue by frankyvij** [aspnet/Security#1750]
Hi,

I am trying to retrieve user locked out status and it seems that IsLockedOutAsync method always returns false, even if the user is locked out.

Also, please note that "summary" of the method is incorrect. It should read as: "Returns a flag indicating whether the specified user ~~his~~ **is** locked out, as an asynchronous operation."

Similarly, "summary" is incorrect for GetLockoutEnabledAsync: "Retrieves a flag indicating whether user lockout can **be** enabled for the specified user."

Also, "summary" is incorrect for GetLockoutEndDateAsync: "Gets the last DateTimeOffset a user's last lockout expired, if any. Any time in the past should ~~be indicates~~ **indicate that** a user is not locked out."

Please help to resolve IsLockedOutAsync issue.

**Comment by frankyvij** [comment]
LockoutEnabled is set to 1 and LockoutEnd is set to date: 2018-05-10 06:09:04.571204.

I just locked the user out by entering incorrect password, so the date above is current. Also, I am using MySQL database, does it have anything to do with how this date is treated?

**Comment by HaoK** [comment]
Yeah the expectation is that the date is in UTC I believe, is there any issues with MySql and dates?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
