### ISSUE TITLE
Why would /signin-wsfed return a 404?

### ISSUE THREAD

**Issue by davidgouge** [aspnet/Security#1751]
Hi,

We have an asp.net core web app using the Microsoft.AspNetCore.Authentication.WsFederation package.  When the auth has been performed by the authority and they POST to /signin-wsfed, a 404 is being returned.

What would be the reasons for this?  This app works just fine when running from my machine and Authenticating against a test authority, so I know there is probably a difference somewhere.  But so I'm in a position of knowledge, what would cause /signin-wsfed to return a 404 (given the package is installed and working).

Thanks

Dave

**Comment by Tratcher** [comment]
That's odd. Have you compared Fiddler traces for the working and failing scenarios? Want to share them?

**Comment by davidgouge** [comment]
Odd is right! :)

Not fiddler, but Chrome dev tools network monitor and the requests and responses look ok.   I'm in the process of adding logging to all of the .AddWsFederation options.Events to see if that shows anything.

I'll dig out the traces shortly.

**Comment by Tratcher** [comment]
Xposted at https://stackoverflow.com/questions/50270654/asp-net-core-signin-wsfed-returning-404

**Comment by davidgouge** [comment]
This is the request and response for the working environment:

`
POST /signin-wsfed HTTP/1.1
Host: pp-**********.*******.********.gov.uk
Connection: keep-alive
Content-Length: 7940
Cache-Control: max-age=0
Origin: https://adfs.preprod.**********.******.gov.uk
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
DNT: 1
Referer: https://adfs.preprod.**********.******.gov.uk/adfs/ls/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cookie: .AspNetCore.Correlation.WsFederation.BpHfyBOpGB_OoKUTwxRAdyFGxFXY-nlNbTZe8QMFc8I=N; BNES_.AspNetCore.Correlation.WsFederation.BpHfyBOpGB_OoKUTwxRAdyFGxFXY-nlNbTZe8QMFc8I=hXlQ2/KUI3eaBnY2PlQO2fDisEseNDVhD7u+2bP1OyAoQGJk3aq3+AKiomVhncX8Ala2ic1Ll10PNO+n/aj7jLZ1vHy2VLFOFw8D15rPoXCT/XvpD/MH6b38BQMauhq+UtmsZ53vxfpACfOVtn2o0Grx4nJyTbwu; seen_cookie_message=yes; BNES_seen_cookie_message=EEE2yidGKTwIs/Qp7OPHAU0702rNNY5d+wiGLBd/1iM0cm1eBGoMZqPAnMj4wuEZR+4SEDQeXQl9/ei7OyC1+g==
wa: wsignin1.0
wresult: <t:RequestSecurityTokenResponse xmlns:t="http://schemas.xmlsoap.org/ws/2005/02/trust"><t:Lifetime><wsu:Created xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2018-05-10T11:41:34.834Z</wsu:Created><wsu:Expires xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2018-05-10T12:41:34.834Z</wsu:Expires></t:Lifetime><wsp:AppliesTo xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"><wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing"><wsa:Address>https://pp-**********.*******.********.gov.uk</wsa:Address></wsa:EndpointReference></wsp:AppliesTo><t:RequestedSecurityToken><saml:Assertion MajorVersion="1" MinorVersion="1" AssertionID="_231af94b-3f00-4672-ad9b-9dabfcb0bc67" Issuer="http://adfs.preprod.**********.******.gov.uk/adfs/services/trust" IssueInstant="2018-05-10T11:41:34.834Z" xmlns:saml="urn:oasis:names:tc:SAML:1.0:assertion"><saml:Conditions NotBefore="2018-05-10T11:41:34.834Z" NotOnOrAfter="2018-05-10T12:41:34.834Z"><saml:AudienceRestrictionCondition><saml:Audience>https://pp-**********.*******.********.gov.uk</saml:Audience></saml:AudienceRestrictionCondition></saml:Conditions><saml:AttributeStatement><saml:Subject><saml:SubjectConfirmation><saml:ConfirmationMethod>urn:oasis:names:tc:SAML:1.0:cm:bearer</saml:ConfirmationMethod></saml:SubjectConfirmation></saml:Subject><saml:Attribute AttributeName="upn" AttributeNamespace="http://schemas.xmlsoap.org/ws/2005/05/identity/claims" a:OriginalIssuer="https://pp**********.******.org.uk/Login/samlIdp" xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"><saml:AttributeValue>********</saml:AttributeValue></saml:Attribute><saml:Attribute AttributeName="ukprn" AttributeNamespace="http://schemas.portal.com" a:OriginalIssuer="https://pp**********.******.org.uk/Login/samlIdp" xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"><saml:AttributeValue>********</saml:AttributeValue></saml:Attribute><saml:Attribute AttributeName="service" AttributeNamespace="http://schemas.portal.com" a:OriginalIssuer="https://pp**********.******.org.uk/Login/samlIdp" xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"><saml:AttributeValue>EPA</saml:AttributeValue></saml:Attribute><saml:Attribute AttributeName="displayname" AttributeNamespace="http://schemas.portal.com" a:OriginalIssuer="https://pp**********.******.org.uk/Login/samlIdp" xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"><saml:AttributeValue>**************</saml:AttributeValue></saml:Attribute><saml:Attribute AttributeName="name" AttributeNamespace="http://schemas.xmlsoap.org/ws/2005/05/identity/claims" a:OriginalIssuer="https://pp**********.******.org.uk/Login/samlIdp" xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"><saml:AttributeValue>************</saml:AttributeValue></saml:Attribute><saml:Attribute AttributeName="mail" AttributeNamespace="http://schemas.portal.com" a:OriginalIssuer="https://pp**********.******.org.uk/Login/samlIdp" xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"><saml:AttributeValue>**************</saml:AttributeValue></saml:Attribute></saml:AttributeStatement><saml:AuthenticationStatement AuthenticationMethod="urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport" AuthenticationInstant="2018-05-10T11:41:29.568Z"><saml:Subject><saml:SubjectConfirmation><saml:ConfirmationMethod>urn:oasis:names:tc:SAML:1.0:cm:bearer</saml:ConfirmationMethod></saml:SubjectConfirmation></saml:Subject></saml:AuthenticationStatement><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" /><ds:Reference URI="#_231af94b-3f00-4672-ad9b-9dabfcb0bc67"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" /><ds:DigestValue>apOGiLg+HG7unfpwQIWNRH9uqoC/lk2Y56UfOEbdgik=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>############################</ds:SignatureValue><KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#"><X509Data><X509Certificate>############</X509Certificate></X509Data></KeyInfo></ds:Signature></saml:Assertion></t:RequestedSecurityToken><t:TokenType>urn:oasis:names:tc:SAML:1.0:assertion</t:TokenType><t:RequestType>http://schemas.xmlsoap.org/ws/2005/02/trust/Issue</t:RequestType><t:KeyType>http://schemas.xmlsoap.org/ws/2005/05/identity/NoProofKey</t:KeyType></t:RequestSecurityTokenResponse>
wctx: CfDJ8HUA7y9jTWlHtpWfmLwtc7_OVAet7P9zpY_ijVIy1XIpcHE0mgHoYj3wF_e-9fmzg2sm69KZgikMQoO6_FYYTP3iSka_xXwEvZEnX9guURA-c9aP9yK_J72xpR5D8Jw5MyKuqCgHvNLzqa46utwo6L5gF1ElLPBAFJI9wMhe6ElZgNEc6cxJkIX1r7T7iX7pRSwWVb04b1UzlI3FlOwmWm6L0BLyFtawFMLNvirwt66x

HTTP/1.1 302 Found
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Location: /Account/PostSignIn
Date: Thu, 10 May 2018 11:41:34 GMT
Content-Length: 0
Set-Cookie: .AspNetCore.Correlation.WsFederation.BpHfyBOpGB_OoKUTwxRAdyFGxFXY-nlNbTZe8QMFc8I=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/signin-wsfed; Secure
Set-Cookie: BNES_.AspNetCore.Correlation.WsFederation.BpHfyBOpGB_OoKUTwxRAdyFGxFXY-nlNbTZe8QMFc8I=cfMsV1SkFV0Hhk3bJNnAz4BSU1AXfRGA4p+rXsm7ufPbMkMQtEF11zuhoPjeBj63jNn43oyp7yIzfyc2tPlw/JqqPhWHeRspPOeFrNfCbeNg1Cf0QmwWrWvd3DB5Wn2anVzbZVYn8HIagyBoUGahc6jbcoJ0+VAC; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/signin-wsfed; Secure
Set-Cookie: samesite=lax; Secure
Set-Cookie: BNES_samesite=ihFR+VS36Ro6rT4/ZS3CFsgerT1MCdkPp27/qPiZM+GWzyzxNXnQeyGiddf59q6I; Secure
Set-Cookie: .Assessors.Cookies=CfDJ8HUA7y9jTWlHtpWfmLwtc7-Z0W9z-qoMXMfSZq_z9GhHg3cSPcu2-WhTtqDyNlyWtlxF0eLb9dgDeG76T4P5pNdfmWz6Aw_qWHnbPvwh1vgLjdKt-zUfK5nnCu1cHqLFIFpd313ve-fMqlZat9pjimtnqZqJrm_nyj_rhFqtZA8O_5QJtBu2_MOWZ9uEVAYLnQg8u0pTjteB_XRJYjyY8TvqSsjMwnsookh-jeD4iL10Dsoi2n9ZqN931WO6O6vOU4FkY3LRGjwBeRaxLj-0uuGhMzS1JgezhtDop3sRj0PbEZGyyRQ7VxhBburaSdYV5br-RFrvclIPTp25rNzSEMKvgYEAYc6O2kUwlfijcpzVsPJpESodXhTVWeW2zVbn1k4slL9hSY9iUYw9EemTIQfaRTdnT8OpE-pgqK4MbV34KUFiZEQQRkJkSpnwnuEO2H3fiNz1_2USbYwd_SLb_cbFFBQJ6VsWhNteMknFSbAiRhi-OxEFoi4EEqrBTrvtG1VqMarjMzjkB4VCqKwcF2RvG8lEqa74s_u0UivaA_jtcIHbKCxg5RopJccufmaHnxUuSAguSayyO6Ng8cxWbYM1UqMnSebRZkgmUTRcgW-lPVI9JDyUMPvtUE1CJxACcFg6gQxOtgic_-pZ0L2QwM2XAMnMRB3Pf0LzrEXHQy9AKtVNRGqFKWCl8FYwUBpRrY_LXnLCF7-trrtGh_sicBu1tIGfRcgEFd0-rHV_-mQlWoJHCXhuivGIuQyCxx_MbFMhM_Nw5vBayLnUBtwX-R2LJsK5miYVuPLGoziJ5So2mEJ5RtqZ7oGTnMnoyJwzzmqTpWp2fUlSrG24oHbM09SDVgHWFwjLd3t2wgQOiRKL624JAvbJ8oL1NALyve_aI6pE2Wp1NKCpgyFUiBMvmfmfX26IYmsXU2ZRfnvbWbkdszbpt2LVrhAY5KCPlabEj5iPXuHulEL1HjPP3zBT3EliuffZqqdcK1yDarhP35xypf2dA9dMfcWBemUMnDbcLJ_K6pJnBNkKs1MDXZCGe5IZ4uT-4snACCzJE0Hte3rqWHvhi7SneOrYo0uG1qSxBJvtcgDX5MTNuH5zKAaopJ1hZnMUQhx75qbiBgjdEIvLzACH0mh3Fbfc4HbFcav0PZguUVNdmUYnH9c_cksVfhs7uJbd0A41duTiod4XNQ9BXuWIuIq1qEQ97Izxw43e7xHsMtAtSvd9ThRkNSZT7pnHF4s5vsVMGFVIj3JlNI4riLnRr3l-nUukrLMLkDZrbANQs3w-42fBZDD3Y19N3WJNe26d9L6U_SEw2FWhI_iAYtTZcD_xgfkRqr6j6jt4B7hI2oPFwyxh7GD0gK3loyV7xRW-FVbDtuSIItyottRDKD1_rbwtl6hOQW8OKeMk_WX8Y2GeTq7vbXIkByQHMeF3MZF-1QfeA0GpI-mWV_kMxNBei-EQTdIRmk9izpHsduU_7DaKrYWiC45RkNXO_j5gv4Dh4Z3uXl9CQtD1KhoO_ltbRyGo6IcHwFZBi8oww9V9m9DsPVVOkdMa1N6UBKfFJQIuaQDbNZUrmu7yQUQUkyTPX5CaqVf7CLNcQbuNiJTyi3qAgXcn5V8Kc9PBOdYvpfFp3GbBN_eh2Xlh_GLLyUmW90IQG7d0uj26pNuHJ_2V0A0M2KCsa24DT8a83v3huM91DDiwsOb494Y7syPdfo6SL7tG7emSm8M0mst1HQAYEeTaNRzX0yBUjUW667y5nbPArWXL8KXUkciAefSx7y744gBQH9HCK7tQpJQusmE1MIGzm5cw6O5DHha5c_WPDZ2A6ZMPg1F4Uu96eciBTMfHERnZ_pD0ERV7QRJYnUzK02v00vJHZTdcG5wwTubpKqf8Rgv4VHlJuf-3FsWtT7W4aO4uifGe8iX33hX2d4m9QHBqIhMJDVH07nI_IJItb5W1oEd1ITPjnjXheXcD4E2l9QSG5ZMGsOeFvGC8nQws-TlrFZvjyn6qaZhOnwcDMVKld-WF0lugTPcJZWx6LTSEUzv57tCU8XQJ_sRLnA6JjNU-jg85gJOKUAda2xNCcsRHDCe9bYpUX-NWigwL_GDxzvTVE0IZ8pN9D19_xEMd5P43MrWkYzQ03qHhTxEEqCysOjPNPrAbSOqb76anqYS8LLSZTDXydNZYsVXw0ReShow more`

**Comment by davidgouge** [comment]
And this is the Request and Response for the none working one:
`POST /signin-wsfed HTTP/1.1
Host: **********.*******.********.gov.uk
Connection: keep-alive
Content-Length: 7899
Cache-Control: max-age=0
Origin: https://adfs.**********.******.gov.uk
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
DNT: 1
Referer: https://adfs.**********.******.gov.uk/adfs/ls/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cookie: .AspNetCore.Correlation.WsFederation.CH8UOWzGoqZ_hhRSfLD6pUNZgPqa61nsvH7d2k9ZniQ=N; BNES_.AspNetCore.Correlation.WsFederation.CH8UOWzGoqZ_hhRSfLD6pUNZgPqa61nsvH7d2k9ZniQ=XK0w7ExhW1QIzA3+yCJcLTbTkYXzI+5YK12pKPYl7q+oVMJ9gbIyOYBYAGpaGR+dmNE9gsYmM2bTF7kGU1vVZG6Dfk5fqVGktXWYekz0mzx/VtnZHXLtG/l7xtDZzxqWoD90GxzYohknsbzancwHuLdmQ9Owgrf5YZDOrAv59Bs=; seen_cookie_message=yes; BNES_seen_cookie_message=xOl+A+U9+KU/v1HWZw9j/v4a9bxovuBhXTCji8CinThiNB/29aA4IRXRUKS+yNF28BmtIgleQyhRYb8F8FyRgcmsY/uOSL3o
wa: wsignin1.0
wresult: <t:RequestSecurityTokenResponse xmlns:t="http://schemas.xmlsoap.org/ws/2005/02/trust"><t:Lifetime><wsu:Created xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2018-05-10T11:43:41.819Z</wsu:Created><wsu:Expires xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2018-05-10T12:43:41.819Z</wsu:Expires></t:Lifetime><wsp:AppliesTo xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"><wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing"><wsa:Address>https://**********.*******.********.gov.uk</wsa:Address></wsa:EndpointReference></wsp:AppliesTo><t:RequestedSecurityToken><saml:Assertion MajorVersion="1" MinorVersion="1" AssertionID="_4e913af8-e25f-4934-8184-c441416a2b11" Issuer="http://adfs.**********.******.gov.uk/adfs/services/trust" IssueInstant="2018-05-10T11:43:41.821Z" xmlns:saml="urn:oasis:names:tc:SAML:1.0:assertion"><saml:Conditions NotBefore="2018-05-10T11:43:41.819Z" NotOnOrAfter="2018-05-10T12:43:41.819Z"><saml:AudienceRestrictionCondition><saml:Audience>https://**********.*******.********.gov.uk</saml:Audience></saml:AudienceRestrictionCondition></saml:Conditions><saml:AttributeStatement><saml:Subject><saml:SubjectConfirmation><saml:ConfirmationMethod>urn:oasis:names:tc:SAML:1.0:cm:bearer</saml:ConfirmationMethod></saml:SubjectConfirmation></saml:Subject><saml:Attribute AttributeName="name" AttributeNamespace="http://schemas.xmlsoap.org/ws/2005/05/identity/claims" a:OriginalIssuer="https://logon.fasst.org.uk/Login/samlIdp" xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"><saml:AttributeValue>*******</saml:AttributeValue></saml:Attribute><saml:Attribute AttributeName="upn" AttributeNamespace="http://schemas.xmlsoap.org/ws/2005/05/identity/claims" a:OriginalIssuer="https://logon.fasst.org.uk/Login/samlIdp" xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"><saml:AttributeValue>***********</saml:AttributeValue></saml:Attribute><saml:Attribute AttributeName="ukprn" AttributeNamespace="http://schemas.portal.com" a:OriginalIssuer="https://logon.fasst.org.uk/Login/samlIdp" xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"><saml:AttributeValue>**********</saml:AttributeValue></saml:Attribute><saml:Attribute AttributeName="service" AttributeNamespace="http://schemas.portal.com" a:OriginalIssuer="https://logon.fasst.org.uk/Login/samlIdp" xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"><saml:AttributeValue>EPA</saml:AttributeValue></saml:Attribute><saml:Attribute AttributeName="displayname" AttributeNamespace="http://schemas.portal.com" a:OriginalIssuer="https://logon.fasst.org.uk/Login/samlIdp" xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"><saml:AttributeValue>********</saml:AttributeValue></saml:Attribute><saml:Attribute AttributeName="mail" AttributeNamespace="http://schemas.portal.com" a:OriginalIssuer="https://logon.fasst.org.uk/Login/samlIdp" xmlns:a="http://schemas.xmlsoap.org/ws/2009/09/identity/claims"><saml:AttributeValue>****************</saml:AttributeValue></saml:Attribute></saml:AttributeStatement><saml:AuthenticationStatement AuthenticationMethod="urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport" AuthenticationInstant="2018-05-10T11:43:37.692Z"><saml:Subject><saml:SubjectConfirmation><saml:ConfirmationMethod>urn:oasis:names:tc:SAML:1.0:cm:bearer</saml:ConfirmationMethod></saml:SubjectConfirmation></saml:Subject></saml:AuthenticationStatement><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" /><ds:Reference URI="#_4e913af8-e25f-4934-8184-c441416a2b11"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" /><ds:DigestValue>brqyBkdCBoERkg0dQYO0uTnhQJCOjczrMbkQ98Vu8Dg=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>################</ds:SignatureValue><KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#"><X509Data><X509Certificate>########</X509Certificate></X509Data></KeyInfo></ds:Signature></saml:Assertion></t:RequestedSecurityToken><t:TokenType>urn:oasis:names:tc:SAML:1.0:assertion</t:TokenType><t:RequestType>http://schemas.xmlsoap.org/ws/2005/02/trust/Issue</t:RequestType><t:KeyType>http://schemas.xmlsoap.org/ws/2005/05/identity/NoProofKey</t:KeyType></t:RequestSecurityTokenResponse>
wctx: CfDJ8JzgJEq8QJdKvd2f9jd3h_MsDALtbiy4R1EfvY0y7hsnO2fpgt4PGfdXYInyi-wI2Q4c9lr0DB2HGB_cROnndLwqkEcwvPM6nwRf4PUratctwtf9BY_IQCPVnaby69Foahen71NHtb6rdipy9rQ8nj1RHx7pBh1_klJEAQINGNr28g-Z45tEKsoFW7GbOhjP6_opHyrWlaN1AjAQaU143N8DZRwHWwT_mEFa4pdXxmjO

HTTP/1.1 404 Not Found
Connection: Close
Content-Type: text/html`

**Comment by davidgouge** [comment]
Nothing jumps out as different to me apart from urls etc.

**Comment by davidgouge** [comment]
And the startup config: 

` services.AddAuthentication(sharedOptions =>
                {
                    sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;
                    sharedOptions.DefaultSignOutScheme = WsFederationDefaults.AuthenticationScheme;
                })
                .AddWsFederation(options =>
                {
                    options.Wtrealm = configuration.Authentication.WtRealm;
                    options.MetadataAddress = configuration.Authentication.MetadataAddress;
                    options.Events = new WsFederationEvents()
                    {
                        OnMessageReceived = context =>
                        {
                           logger.LogInformation($"WSFED MessageReceived: {context.ProtocolMessage.Wresult}");
                            return Task.FromResult(0);
                        },
                        OnRedirectToIdentityProvider = context =>
                        {
                            logger.LogInformation($"WSFED RedirectToIdentityProvider: {context.ProtocolMessage.ToString()}");

                            return Task.FromResult(0);
                        },
                        OnSecurityTokenReceived = context =>
                        {
                            logger.LogInformation($"WSFED SecurityTokenReceived: {context.ProtocolMessage.ToString()}");
                            return Task.FromResult(0);
                        },
                        OnSecurityTokenValidated = context =>
                        {
                            logger.LogInformation($"WSFED SecurityTokenValidated: {context.ProtocolMessage.ToString()}");
                            return Task.FromResult(0);
                        },
                        OnAuthenticationFailed = context =>
                        {
                            logger.LogInformation($"WSFED AuthenticationFailed: {context.ProtocolMessage.ToString()}");
                            return Task.FromResult(0);
                        },
                        OnRemoteSignOut = context =>
                        {
                            logger.LogInformation($"WSFED RemoteSignOut: {context.ProtocolMessage.ToString()}");
                            return Task.FromResult(0);
                        }, 
                        OnRemoteFailure = context =>
                        {
                            logger.LogInformation($"WSFED RemoteFailure: {context.Failure.Message}");
                            return Task.FromResult(0);
                        }
                    };
                })
                .AddCookie(options =>
                {
                    options.Cookie = new CookieBuilder() {Name = ".*******.Cookies", HttpOnly = true};
                });`

**Comment by davidgouge** [comment]
Startup.Configure: 

`public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            MappingStartup.AddMappings();
            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles()
                .UseSession(new SessionOptions() { Cookie = new CookieBuilder() { Name = ".******.Session", HttpOnly = true } })
                .UseAuthentication()
                .UseRequestLocalization()
                .UseMvc(routes =>
                {
                    routes.MapRoute(
                        name: "default",
                        template: "{controller=Home}/{action=Index}/{id?}");
                });
        }`

**Comment by davidgouge** [comment]
Ok, thank you so much for looking at this @Tratcher, but I've just been informed that the WAF on the failing environment is probably the cause as they have blocked notifications for the signin-wsfed url. 🤕 

Thanks again! 👍

**Comment by fesioche** [comment]
I had the same problem and i solved including in Startup.cs

 public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
           //Omited for clarity

			app.UseAuthentication();

			app.UseStaticFiles();

           //Omited for clarity
        }
