### ISSUE TITLE
Why is implicit mode the default one for OpenID Connect?

### ISSUE THREAD

**Issue by skyflyer** [aspnet/Security#1753]
While testing AD FS integration with OIDC middleware I (unexpectedly) found out that implicit flow is the default one. I then checked the sources and it seems that way too:

```c#
public string ResponseType { get; set; } = OpenIdConnectResponseType.IdToken;
```

I noticed (older) discussions in #744 that the hybrid one should be the default, though I'm not sure I understand exactly why the "authorization code flow" is not the default? I suppose the `state` and `nonce` are checked (haven't verified it myself) in all flows (where appropriate).

Perhaps I'm being naive, but I suppose that if the `state` is checked, and the app uses back-channel (authorization code flow) to obtain an `id_token`, that prevents the "copy/paste" attack (as well as MITM between browser and app) and is the most secure option to use?

Thanks!

**Comment by brockallen** [comment]
Implicit is for when your client app only needs user authentication. Hybrid is when your client app needs user authentication and to invoke an API on behalf of the user.

**Comment by dallancarr** [comment]
Browser initiated is a little different though and can actually do both.

**Comment by blowdart** [comment]
Yes, but by default we're only doing user authentication, so why would we want extra privileges. Least privilege is a good principle.

**Comment by skyflyer** [comment]
I'm sorry for a late reply. Please correct me if I'm wrong in understanding, but I thought "Implicit" flow was designed for clients, which can not keep a secret (i.e. Javascript SPA, Mobile apps, etc). So it is not directly related to "authentication" per se.

From the [spec](http://openid.net/specs/openid-connect-core-1_0.html#ImplicitFlowAuth):
> The Implicit Flow is mainly used by Clients implemented in a browser using a scripting language. The Access Token and ID Token are returned directly to the Client, which may expose them to the End-User and applications that have access to the End-User's User Agent. The Authorization Server does not perform Client Authentication.

With implicit flow, all I need is a correct `redirect_url` and a `client_id` and I can successfully authenticate a client.

With "authorization code" flow, the server (ASP.NET Core MVC application) would call the IdP directly to obtain the authentication information based on the code that was passed in, that is, IMHO, more secure.

We all agree that both flows can be used to achieve the same thing. And we're on the same page, that we're talking about authentication.

> Yes, but by default we're only doing user authentication, so why would we want extra privileges. Least privilege is a good principle.

I'm not talking about different ("extra") privileges here -- it is still just authentication. I'm just wondering why is the "implicit" flow the default one for OpenID Connect provider?

**Comment by dallancarr** [comment]
I  think it is the lowest common denominator. Generally developers only want authentication and the need to not have to manage a client secret is imo hassle free.

**Comment by skyflyer** [comment]
That's an OK explanation. Do you think it would make sense to explicitly state that in the documentation?

Like [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/index?view=aspnetcore-2.1) and [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.openidconnectoptions?view=aspnetcore-1.1)?

Most of the documentation mentions client id and secret management, but if the default configuration uses implicit flow, then the secret is not needed? For instance, I was *expecting* that the authorization code flow was the default one. I see that the OAuth handler uses `code` by default and Google provider as well.

I would personally vote for changing the default to "code" and documenting how to change it to implicit flow if necessary or desired. We are talking about a server-side component after all.

**Comment by brockallen** [comment]
code flow by itself it subject to the code copy & paste attack. Adding an id_token in the front-channel (either by hybrid or implicit) response gives you a signed protocol response that's verifiable on the first leg of the response.

**Comment by dallancarr** [comment]
Agreed. But @skyflyer is right to call out the docs here. `client_secret` is related to code flow and shouldn't be confused with other grant types.

**Comment by PinpointTownes** [comment]
> code flow by itself it subject to the code copy & paste attack.

Hem... the same attack works against implicit and hybrid. If you manage to steal an authorization code, chances are extremely high you can also steal an identity token. The fact the identity token is directly validated by the RP instead of the IDP (unlike the code) doesn't change anything to the feasibility of this attack.

**Comment by brockallen** [comment]
Perhaps, but as you know an injected code is subject to other... mixups if not done properly (code flow by itself, for example doesn't require nonce). I'm speaking about pure protocol, but there are other things in this implementation that help mitigate various bad situations -- for example, the nonce enabled by default, the additional correlation (for the OAuth2 only providers), and using the scheme name in the state data protector (although this might be a concern with the recent suggestions for dynamic per-request options config to support connecting to different OPs).

Anyway, my point is that a validatable protocol response on the first leg is better than not.
