### ISSUE TITLE
OAuthHandler issue with Docker

### ISSUE THREAD

**Issue by aceven24** [aspnet/Security#1754]
So I spent a good portion of the day looking at this issue.  I'm running .NET Core 2.0 with OAuth + Facebook 2.0.4 packages.  My application is configured correctly at Facebook but here is the issue.

I terminate SSL at my load balancer and then the request gets routed to Kestrel (no, I'm not using nginx, but maybe I should have)

My first issue was that when the redirect to Facebook occured the callback/redirect back uri was going to:

http://www.acmecorp.com/signin-facebook opposed to https://www.acmecorep.com/signin-facebook.

That caused Facebook to reject the request.

My solution to that problem was to modify HttpContext.Request.Scheme and set that to https.

Things looked good, except when the callback gets to this line in OAuthHandler

var tokens = await ExchangeCodeAsync(code, BuildRedirectUri(Options.CallbackPath));

It rebuilds the BuildRedirectUri and I have no shot at adjusting the HttpContext.Request.Scheme back to https.

Am I missing something or do I need to go ahead and get a reverse proxy setup and get Kestrel living in https land?

**Comment by Tratcher** [comment]
Duplicate. https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1
