### ISSUE TITLE
Correlation failed. at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler during OIDC authentication

### ISSUE THREAD

**Issue by sathiathirumal** [aspnet/Security#1755]
I am hitting this with the following combination:
1) Browser incognito mode (Chrome)
2) Application is behind Azure application gateway (no repro if it isnt). Cookie based affinity is turned OFF (default); if turned ON, seems to make repro happen more often.

Code is rather plain vanilla OIDC authN + cookies.

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            })
            .AddAzureAd(options => {
                Configuration.Bind("AzureAd", options);
            })
            .AddCookie(p => p.SlidingExpiration = true);

(I have tried converting cookies to persistent instead of session; no impact)

I am forwarding the X-Forwarded-Proto header to the auth middleware as recommended so the redirect_uri uses the correct protocol scheme.

**HANDLING IN CODE**

I tried to handle the **OnRemoteFailure()** event, and redirect to "/Home/AuthRedirect" which is an anon page that waits for 20 secs, and then redirects to the "/" (home page). It seems to work sometimes, but not always. I am out of ideas.

**WORKAROUND**

1) Users can go to the homepage again and hit F5 until this works. It seems that each F5 gets them moving a step ahead and once the OpenID cookies are populated, everything else (I have more auth after openid finishes, via adal.js for AJAX use).
2) Bypass the application gateway and use the direct service fabric cluster DNS name (not acceptable as it is http).

**DETAILS**

System.Exception: Correlation failed.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

![image](https://user-images.githubusercontent.com/9466367/39440060-907a5506-4c5e-11e8-8208-3cfa7dc9847c.png)

**Comment by Tratcher** [comment]
A few things that would help debug this:
a) Your whole Startup.cs
b) A Fiddler trace of the login flow (not just the last request)
c) Logs of the request as received by Kestrel. https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1#troubleshoot or https://github.com/aspnet/KestrelHttpServer/blob/b040e33b1bbcc9719dc8e71c707a7e3fe1ff99ca/samples/SampleApp/Startup.cs#L87

**Comment by Tratcher** [comment]
@Hobray see https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1#when-it-isnt-possible-to-add-forwarded-headers-and-all-requests-are-secure

**Comment by Hobray** [comment]
@Tratcher Thanks for that solution. That feels a lot less hacky.

**Comment by heavenwing** [comment]
@sathiathirumal I am hitting same problem.  Do you solve this issue?

My environment is:
- 4 nodes Service Fabric Cluster ( IP is :192.168.100.16-192.168.100.19)
- 2 nodes NLB+ARR as Load Balance, I have Virtual IP is 192.168.100.60, NLB1 IP is 192.168.100.13, NLB2 IP is 192.168.100.14
- STS web stateless service run on 4 SF nodes
- Client(a management console web) also run on 4 SF nodes

My problem is :
- When I open mc web in Chrome with 192.168.100.60 (with NLB+ARR), then login with sts, I get error "Correlation failed".
- When I open mc web in Chrome with 192.168.100.13 (only with ARR), then login with sts, I also get same error.
- When I open mc web in Chrome with 192.168.100.16 (access SF node directly), then login with sts, it is working.
STS always run on 4 SF nodes with NLB+ARR in above 3 situations.

**Comment by heavenwing** [comment]
@Tratcher I have already added ForwardedHeadersOptions configuration , problem is still with me :(

**Comment by sathiathirumal** [comment]
@heavenwing, no I have not resolved this yet. I increased the cookie expiration time to 30 days and so I hit this problem a bit less now, but I still do hit it. When i hit it, I execute a logout and then sleep 10 secs and then redirect to an authenticated page (which is just the homepage for me). It works 50% of the time on first such retry, and 30% on 2nd retry (20secs sleep), and 20% needs a 3rd retry (30secs sleep). Needless to say, it presents a poor user experience. And additionally, since I manually redirect to the homepage, if the user was originally on a deeper URL on the site, that information is lost and post-login they are landed on the homepage *always*. 

I added code to dump all the HTTP headers when this code is hit as @Tratcher  requested and didnt see anything weird there. 

@Tratcher - I will send you the details u requested directly (via corpmail) so I dont need to sanitize anything.

**Comment by sathiathirumal** [comment]
Hmmm, here's something weird I am noticing. During the POST to /signin-oidc, the **X-Original-Proto : http** - why is this? I am https everywhere upto the Application Gateway where I terminate SSL. I also don't see the X-Forwarded-Proto in this case even though I do specify the middleware explicitly to inject this header (see far below on my startup code for that).

POST https://MY.SITE.com/signin-oidc

Cache-Control : max-age=0
Connection : Keep-Alive
Content-Type : application/x-www-form-urlencoded
Accept : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding : gzip, deflate, br
Accept-Language : en-US,en;q=0.9,ta;q=0.8
Cookie : <redacted> [length: 3316]
Host : MY.SITE.com
Max-Forwards : 10
Referer : https://login.microsoftonline.com/TENANTID/oauth2/authorize?client_id=CLIENTID&redirect_uri=https%3A%2F%2FMY.SITE.com%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=636633215778893767.MWJkYTg3MTYtMGFmNCxxxxxxxxxxxxsz8ukV2-HgglqiXZ0uITnQV6wNrMANPKqe1NLBZa24_7Hv5MRqEcAf5Or2aTTRjHF2xxxx0MU5UCuoIKyQMFNZgcnd7gco3A&x-client-SKU=ID_NET&x-client-ver=2.1.4.0
User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Origin : https://login.microsoftonline.com
Content-Length : 2397
Upgrade-Insecure-Requests : 1
DNT : 1
X-FORWARDED-PORT : 443
X-ORIGINAL-HOST : MY.SITE.com
SEC-WEBSOCKET-EXTENSIONS : 
X-Original-URL : /signin-oidc
**X-Original-Proto : http**
X-ARR-SSL : 2048|256|C=US, S=STATE, L=CITY, O=COMPANYNAME Corporation, OU=COMPANYNAME IT, CN=COMPANYNAME IT TLS CA 5|CN=MY.SITE.com
X-ARR-LOG-ID : 84b6289e-cc21-48e0-84f0-6a045f060ff1
X-Original-For : NN.NNN.35.NNN:1985

The code I use to inject X-Forwarded-Proto is; this code used to be very simple and only forward X-Forwarded-Proto but then I was experimenting and added the other ones (and the clearing knownnetworks/proxies as a hack/suggestion from another similar thread); may be I should revert this.

            var forwardedHeaderOptions = new ForwardedHeadersOptions
            {
                ForwardedHeaders =
                    ForwardedHeaders.XForwardedHost |
                    ForwardedHeaders.XForwardedFor |
                    ForwardedHeaders.XForwardedProto
            };
            SenseiLogger.Current.LogInformational(1, "KnownNetworks = " + String.Join<string>(", ", forwardedHeaderOptions.KnownNetworks.Select<IPNetwork, string>(ipnet => ipnet.ToString())));
            SenseiLogger.Current.LogInformational(1, "KnownProxies = " + String.Join<IPAddress>(", ", forwardedHeaderOptions.KnownProxies));

            // required for XForwardedHost/For to take effect; also seems to interfere with
            // XForwardedProto and caused redirect_uri to use http: instead of https:
            forwardedHeaderOptions.KnownProxies.Clear();
            forwardedHeaderOptions.KnownNetworks.Clear();

            app.UseForwardedHeaders(forwardedHeaderOptions);

**Comment by sathiathirumal** [comment]
OK, so @Tratcher said that X-Original-Proto: http is ok - it just means that X-Forwarded-Proto did appear and it was processed. I also verified this by 1) dumping all request headers BEFORE and AFTER the .UseForwardedHeaders() call and 2) dumping the HttpContext.Request.Scheme value BEFORE and AFTER the .UseForwardedHeaders() call [it is http before and then flips to https after]. So all seems fine there.

Not sure what to try anymore. I see a 90% chance of repro in incognito mode (Chrome) which is almost always. But 10% of the time it works on first try (also in incognito mode). **So this isn’t deterministic…** perhaps it is related to some timing issue in the login path? Is there any other timeout in this codepath that I can try tweaking?

For completeness sake - _outside_ of incognito mode, it really only occurs if I leave a logged in browser session open for a long time and then hit F5 after say a day (even if my cookies expiration time is 30 days).

**Comment by sathiathirumal** [comment]
OK, figured out what was going on here with @Tratcher 's help. 

Basically I was missing a DataProtection middleware; because of that, each of my cluster nodes uses a different encryption/decryption key for the cookies. Normally if your AG has cookie affinity enabled, the issue is masked (as all session traffic goes to the same node). However, during the OpenIdConnect login dance, the AG affinity cookie doesnt exist; and IF the GET call to login.microsoftonline.com ends up on a node that is DIFFERENT from the node that receives the POST /signin-oidc, then the correlation cookie decryption will fail causing the "Correlation Failed" error (of course, if by luck, the GET and POST ends up on the same node, then it will succeed; this explains the non-deterministic behavior I saw. Incognito mode just means there are no AG affinity cookies, and the OpenId dance happens _always_ which increases the chance of hitting this issue)

The fix is to add a DataProtection middleware so the OpenId middleware can make use of it to share the keys across nodes. Here's the code I added to:

            // create a blob storage container to use as the central, cross-node DataProtection key holder
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(AppStorageAccountConnectionString);
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer blobContainer = blobClient.GetContainerReference("my-portal-dataprotection");
            blobContainer.CreateIfNotExistsAsync().GetAwaiter().GetResult();

            // TODO: keys in keys.xml are not encrypted at rest, by default
            // we need to add an encryption cert here so they will be, via .ProtectKeysWithCertificate("certthumbprint")
            services.AddDataProtection(options =>
            {
                options.ApplicationDiscriminator = "My-Portal";
            })
            .PersistKeysToAzureBlobStorage(blobContainer, "keys.xml");

Once I added this, I am no longer able to reproduce the issue.

**Comment by sathiathirumal** [comment]
@Tratcher Can we get this troubleshooting information added to the https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1#troubleshoot article? It makes sense there because proxy-load-balancer is practically used only in multi-node farm situations where this issue is impactful. It would've saved me countless hours if only the word "DataProtection" was even mentioned once in that article. Thanks!

**Comment by Tratcher** [comment]
We're getting a dedicated doc written for the multi-node scenario: https://github.com/aspnet/Docs/issues/3255.

**Comment by ydekova** [comment]
In our case, this was the reason https://github.com/aspnet/Security/issues/1510 It results in the same behavior.

**Comment by Dev123213** [comment]
A note to anyone tearing their hair out... I got this error because the secret I was sending was the encrypted secret, not the decrypted. I didn't anything in the logs on Identity Server saying there was a problem, and just got a correlation error on the client application (hybrid).

**Comment by leastprivilege** [comment]
I am pretty sure you would see a failed client authentication log entry - and hopefully a log entry as well from the Microsoft handler in the client app.

**Comment by Dev123213** [comment]
[log_report_IS.txt](https://github.com/aspnet/Security/files/2084497/log_report_IS.txt)

**Comment by Dev123213** [comment]
Log config:

 Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .MinimumLevel.Override("Microsoft.AspNetCore.Authentication", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .Enrich.WithThreadId()
                .Enrich.WithProperty("Application", "XXXXXXXXX")
                .WriteTo.RollingFile(Path.Combine(environment.ContentRootPath, "Logs/log-{Date}.txt"))
                .CreateLogger();

**Comment by shatl** [comment]
Enabling sticky sessions fixed this error for us

**Comment by Tratcher** [comment]
@shatl which means your Data Protection is not correctly configured across your nodes.

**Comment by ZOXEXIVO** [comment]
@Tratcher We use DataProtection with long-expiring keys
For 1500 clients we catch 1-3 Correlation failed errors every day and we very tired to solve it

**Comment by Tratcher** [comment]
The best way to figure it out is to capture the request headers from the failed request via a Fiddler trace or a log. It also helps if you can capture the original challenge response headers.

**Comment by jjkesinger** [comment]
I'm having the same issue and tried these fixes but no luck. The problem I see is the correlation cookie is not being set (tried in IE, Edge, Chrome, Firefox) even though the forward response to the oauth provider does have the set-cookie header. I've set the DataProtection to a static location so the same key is used, tried, the cookie policy, https redirection, but nothing seems to set the cookie. I believe it has to do with the local computer settings as I can clone this repo (https://github.com/jjkesinger/charts) on another computer and it works fine. Does anyone have any ideas why the correlation cookie isn't being set? Here's my SO question with a little more details: https://stackoverflow.com/questions/53352945/aspnetcore-authentication-correlation-failed

**Comment by DwaynesWorld** [comment]
@jjkesinger, could it be related to the samesitemode of the cookies. I see the same site mode is set to strict.

**Comment by jjkesinger** [comment]
@DwaynesWorld that was it. Thanks.
