### ISSUE TITLE
OpenIdConnectOptions Support for Absolute URIs

### ISSUE THREAD

**Issue by Hobray** [aspnet/Security#1757]
While I can appreciate the desire to simplify and abstract the OIDC configuration as much as possible, I've run into a handful of scenarios where the inability to define absolute URIs for the IDP Authorization Endpoint URI and the CallbackPath (Redirect) URI has been limiting and frankly feels a little dirty to step around.

One scenario required that my application (the relying party) point to an intermediate/proxy location as my "IDP" authorization endpoint in order for domain specific user claims to be appended to the authorization request query string parameters before redirecting to the actual IDP authorization endpoint. All other OIDC transactions would then happen between my application and the IDP. As of now there is no was to explicitly set/override the authorization endpoint or other values that typically come from the well known endpoint metadata. In working through SSO setup with various SaaS providers, I've learned that this kind of configuration flexibility is well supported outside of .NET.

Another scenario that I believe to be less of a fringe case than the previous deals with CallbackPath generation. In our organization, SSL is applied at the load balancer, not at the application server level. Because the OpenIdConnectOptions expect a relative path when specifying the "CallbackPath", this creates the problem of the "redirectUri" parameter being "http" and not "https" because the library auto generates the base URL and scheme. The result is that when the IDP attempts to send the auth code back to my application, I get a "Correlation Error" because the hop from "http" to "https" results in a remote failure. I've seen some feedback on this item related to enabling forwarding headers in Identity Server etc. but we don't use Identity Server and don't have the latitude to go that route.

This is how I've worked around this scenario:

```csharp
.AddOpenIdConnect("oidc", oidcConnectionOptions =>
{
    oidcConnectionOptions .Events = new OpenIdConnectEvents
    {
        OnRedirectToIdentityProvider = redirectContext=>
        {
            if (!_env.IsEnvironment("Debug"))
            {
                //Force scheme of redirect URI
                redirectContext.ProtocolMessage.RedirectUri = redirectContext.ProtocolMessage.RedirectUri.Replace("http://", "https://", StringComparison.OrdinalIgnoreCase);
            }
            return Task.FromResult(0);
        }
    };

    //Set relative CallbackPath (Redirect URI)
    oidcConnectionOptions.CallbackPath = "/access/authenticate";

    //Set other options here....
)};
```

This would be my preference:
```csharp
.AddOpenIdConnect("oidc", oidcConnectionOptions =>
{
    var baseAddress = new Uri("https://myhostname.com");
    var callbackPath = new Uri("/access/authenticate");
    oidcConnectionOptions.AbsoluteCallbackPath = new Uri(baseAddress, callbackPath);

    //Maybe something like this for metadata endpoint overrides
    var proxyBaseAddress = new Uri("https://idpproxy.com");
    var proxyAuthPath = new Uri("/sss/oauth2/authorize");
    oidcConnectionOptions.AuthorizationEndpointOverride = new Uri(proxyBaseAddress, proxyAuthPath);

    //Set other options here....
)};
```

**Comment by Tratcher** [comment]
Previously discussed. There are many other things broken if your request fields are not correct, this one is just more obvious. The recomended solution is https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1#when-it-isnt-possible-to-add-forwarded-headers-and-all-requests-are-secure
