### ISSUE TITLE
Exception: Correlation failed.

### ISSUE THREAD

**Issue by hnviradiya** [aspnet/Security#1761]
I have seen this error at many places, at some places issue is closed. at some places issue is open. Don't know if this is similar. But I get following.

```
An unhandled exception occurred while processing the request.
Exception: Correlation failed.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()

Stack Query Cookies Headers
Exception: Correlation failed.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
```

Cookies are as following.

![screenshot 13](https://user-images.githubusercontent.com/12680915/40254574-a0e646fa-5b01-11e8-9296-25527c569955.png)

Headers are as following.

![screenshot 14](https://user-images.githubusercontent.com/12680915/40254648-e8f20790-5b01-11e8-9ebf-b6432b6a28f5.png)

My URL is like this.

**signin-oidc#error=login_required&state=a02009f03c924afc9398ee437c903af9**

My OIDC client:

```
var mgr = new UserManager({
            authority: "http://localhost:5000",
            client_id: "js",
            redirect_uri: "http://localhost:50144/signin-oidc",
            silent_redirect_uri: "http://localhost:50144/signin-oidc",
            response_type: "id_token token",
            post_logout_redirect_uri: "http://localhost:50144/signout-callback-oidc",
            loadUserInfo: true,
            scope: "openid profile email"
        });

        mgr.signinSilent().then(function (user) {
});
```

My Identityserver's allowed client details.

```
new Client
                {
                    ClientId = "js",
                    ClientName = "js",
                    ClientUri = "http://localhost:50144",
                    //LogoUri = "https://pbs.twimg.com/profile_images/1612989113/Ki-hanja_400x400.png",

                    AllowedGrantTypes = GrantTypes.Implicit,
                    AllowAccessTokensViaBrowser = true,
                    RequireClientSecret = false,
                    AccessTokenType = AccessTokenType.Jwt,

                    RedirectUris = 
                    {
                        "http://localhost:50144/signin-oidc",
                    },

                    PostLogoutRedirectUris = { "http://localhost:50144/signout-callback-oidc" },
                    AllowedCorsOrigins = { "http://localhost:50144" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                        //"api1", "api2.read_only", "api2.full_access"
                    }
                },
```

**Comment by Tratcher** [comment]
`error=login_required` looks like one problem, but that shouldn't have failed with a `Correlation failed`.

My other suggestion is to share a Fiddler trace of the whole login flow.

**Comment by hnviradiya** [comment]
[Oidc-AND-MVC-Login-Flow-Identityserver.zip](https://github.com/aspnet/Security/files/2019138/Oidc-AND-MVC-Login-Flow-Identityserver.zip)

**Comment by hnviradiya** [comment]
I am going to close this. as it is an issue with not logged in as u said. It is different that shouldn't have failed with a Correlation failed. but I don't have issue with that as I have got reason for that. i'll follow following issue.

https://github.com/aspnet/JavaScriptServices/issues/1645

**Comment by hnviradiya** [comment]
I am getting issue after successful login. So opening issue again. Might be related to following article (Which is not solving issue for me as I don't have another CallbackPath).

https://blog.headforcloud.com/2017/11/05/asp-net-core-identity-with-multiple-oidc-providers/

Following is my new fiddler log.

[Oidc-Signin.zip](https://github.com/aspnet/Security/files/2020145/Oidc-Signin.zip)

FYI: I have two clients. First authenticates properly and redirects to my client1. This Issue is created on second client2's auth. It shows login screen. Authenticates. And when tries redirects to client2 (Callback path is same as that of client1), this error occurs.

**Comment by Tratcher** [comment]
Something's fishy with the prior request to `GET /connect/authorize?client_id=js&redirect_uri=http%3A%2F%2Flocalhost%3A50144%2Fsignin-oidc...`. That wasn't generated by a challenge from the auth middleware. You're trying to use this with a JS Client? That's not what this OIDC component is for. You should be using JwtBearer for that.

**Comment by hnviradiya** [comment]
There are 2 auths taking place. one is my server side (like [this](https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Clients/src/MvcImplicit/Controllers/HomeController.cs))  which redirects to Login page with authorize attribute. Second authorization is from JS Client once server side code is authorized (like [this](https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Clients/src/JsOidc/wwwroot/app.js)). At client side authorization this issue occurs.

**Comment by hnviradiya** [comment]
But this js client woks if I use it separately. This creates issue only when i have both of them together. Server side (which is protected with Authorize attribute) as well as js client.

**Comment by hnviradiya** [comment]
I am closing this issue as due to below thread now I don't want to use both auth at a time. so. But may be other might have similar issue.
https://github.com/aspnet/JavaScriptServices/issues/1645
