### ISSUE TITLE
Infinite loop with .NetCore AddIdentity and AddOpenIdConnect

### ISSUE THREAD

**Issue by msdkool** [aspnet/Security#1763]
I have an issue closed to this and it's driving me nuts. I need the AddIdentity in my Startup.cs to automatically inject UserManager and RoleManager for creation of users and roles directly from the Client App. I also need the OpenIdConnect to redirect to the IdentityServer hosted Login page. Right now, I'm caught in an infinite loop. Please help. Below is the content of my ConfigureServices

services.AddMvc();
        string connectionString = this.Configuration.GetConnectionString("DefaultConnection");
        string authServer = this.Configuration.GetConnectionString("AuthServer");

        var migrationsAssembly = typeof(DbContext).GetTypeInfo().Assembly.GetName().Name;

        services
             .AddDbContext<DbContext>(options => options
                          .UseSqlServer(connectionString,
                          optionsBuilder => optionsBuilder.MigrationsAssembly(typeof(DbContext).GetTypeInfo().Assembly.GetName().Name)));

        
        services.AddIdentityServer()
        .AddConfigurationStore(options =>
        {
            options.ConfigureDbContext = builder =>
                builder.UseSqlServer(connectionString,
                    sql => sql.MigrationsAssembly(migrationsAssembly));
        });

        services.AddIdentity<User, IdentityRole>(config =>
        {
            config.Password.RequireDigit = true;
            config.Password.RequireLowercase = true;
            config.Password.RequireNonAlphanumeric = false;
            config.Password.RequireUppercase = true;
            config.Password.RequiredLength = 8;
            config.User.RequireUniqueEmail = true;
            config.SignIn.RequireConfirmedEmail = true;
            config.SignIn.RequireConfirmedPhoneNumber = false;
        })
        .AddEntityFrameworkStores<DbContext>()
        .AddDefaultTokenProviders();

        JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
        services.AddAuthentication(options =>
        {
            options.DefaultScheme = "Cookies";
            options.DefaultChallengeScheme = "oidc";
            options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme;

        })
        .AddCookie("Cookies")          
        .AddOpenIdConnect("oidc", options =>
        {                
            options.SignInScheme = "Cookies";
            options.Authority = authServer;
            options.RequireHttpsMetadata = false;

            options.ClientId = this.Configuration["PortalSettings:ClientId"];
            options.ClientSecret = this.Configuration["PortalSettings:ClientSecret"];
            options.ResponseType = "code id_token";

            options.SaveTokens = true;
            options.GetClaimsFromUserInfoEndpoint = true;

            options.Scope.Add("api");
            options.Scope.Add("offline_access");
        });
[FiddlerTrace_Loop_Full.txt](https://github.com/aspnet/Security/files/2024262/FiddlerTrace_Loop_Full.txt)

**Comment by Tratcher** [comment]
Can you show us your home controller for http://gpmerchantportal.azurewebsites.net/?

**Comment by msdkool** [comment]
[Authorize]
    public class HomeController : Controller
    {
        public ITransactionService _transactionService;
        private IConfiguration _configuration;

        public HomeController(ITransactionService transactionService, IConfiguration configuration)
        {
            _transactionService = transactionService;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            string id = "ALL";

            Dashboard dashboard = _transactionService.GetDashboardTransactions(id);

            return View(dashboard);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
        public IActionResult Secure()
        {
            ViewData["Message"] = "Secure page.";

            return View();
        }

        public async Task<IActionResult> CallApiUsingUserAccessToken()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");

            var client = new HttpClient();
            client.SetBearerToken(accessToken);
            var content = await client.GetStringAsync("http://localhost:5001/api/resource-with-policy");

            return View("Json", content);
        }

        public async Task<IActionResult> CallApiUsingClientCredentials()
        {
            var tokenClient = new TokenClient("http://globalpayauthserver.azurewebsites.net/connect/token", _configuration["PortalSettings:ClientId"], _configuration["PortalSettings:ClientSecret"]);
            var tokenResponse = await tokenClient.RequestClientCredentialsAsync("globalpay.api");

            //var client = new HttpClient();
            //client.SetBearerToken(tokenResponse.AccessToken);
            //var content = await client.GetStringAsync("http://localhost:5001/api/resource-without-policy");
            var content = "{ 'Token':tokenResponse.AccessToken}";

            return View("Json", content);
        }

        public async Task Logout()
        {
            await HttpContext.SignOutAsync("Cookies");
            await HttpContext.SignOutAsync("oidc");
        }

    }`

**Comment by Tratcher** [comment]
Yeah, that makes sense. You Signin with "Cookies", but you Authenticate with IdentityConstants.ApplicationScheme. You need some intermediate step that either exchanges Cookies for IdentityConstants.ApplicationScheme, or replace IdentityConstants.ApplicationScheme with Cookies everywhere.

**Comment by msdkool** [comment]
So, it should change to this
         `
        options.DefaultScheme = "Cookies";
        options.DefaultChallengeScheme = "oidc";
        options.DefaultAuthenticateScheme = "Cookies"; 
`

**Comment by msdkool** [comment]
@Tratcher You are the best, it worked. Thank you so much. I've been on this for hours.
