### ISSUE TITLE
HttpContext.GetTokenAsync fails after Upgrade to 2.1.0

### ISSUE THREAD

**Issue by TimHess** [aspnet/Security#1765]
Hello,
I have some code that's calling `await HttpContext.GetTokenAsync("access_token")`. When using `Microsoft.AspNetCore.Authentication.JwtBearer` version 2.0.4 it works, but upgrading to 2.1.0-preview1-final or newer results in null being returned.

I believe this is because on line 73 in [Microsoft.AspNetCore.Authentication.Core/AuthenticationService.cs](https://github.com/aspnet/HttpAbstractions/blob/bcb7bcbb7a6461204f4cefd9848e2a782ebb0a6b/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationService.cs#L73)
`return AuthenticateResult.Success(new AuthenticationTicket(transformed, result.Properties, result.Ticket.AuthenticationScheme));` result.Properties is null.

When using JwtBearer auth, result.Properties is never set - however, the properties that are expected to be there are present on result.Ticket. Changing line 73 to `return AuthenticateResult.Success(new AuthenticationTicket(transformed, result.Ticket.Properties, result.Ticket.AuthenticationScheme));` appears to fix the issue for me, is there any reason not to do so?
Thanks

**Comment by Tratcher** [comment]
JwtBearer Succeeds:
https://github.com/aspnet/Security/blob/e031eff146c8aad43e63cd8d32e8fe382a0c8d66/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L152-L153
Creates a ticket and HandleRequestResult:
https://github.com/aspnet/Security/blob/e031eff146c8aad43e63cd8d32e8fe382a0c8d66/src/Microsoft.AspNetCore.Authentication/Events/ResultContext.cs#L46
Stores the ticket:
https://github.com/aspnet/Security/blob/e031eff146c8aad43e63cd8d32e8fe382a0c8d66/src/Microsoft.AspNetCore.Authentication/HandleRequestResult.cs#L36
Which doesn't set Properties like the base class does:
https://github.com/aspnet/HttpAbstractions/blob/bcb7bcbb7a6461204f4cefd9848e2a782ebb0a6b/src/Microsoft.AspNetCore.Authentication.Abstractions/AuthenticateResult.cs#L57

**Comment by HaoK** [comment]
Yeah looks like a bug

**Comment by TimHess** [comment]
@Tratcher Thanks for accepting the PR - is it possible to have this included in 2.1.0-RTM?

**Comment by ajcvickers** [comment]
@Tratcher @HaoK Is there a workaround?

**Comment by HaoK** [comment]
The information is still there via result.Ticket.Properties, so the workaround would be to use the underlying apis instead of the top level sugar...

instead of 'context.GetToken("access_token")' something like:
```
 context.AuthenticateAsync(JwtBearer.Defaults).Ticket.Properties.GetToken("access_token");
```

**Comment by ajcvickers** [comment]
Thanks @HaoK. So the workaround is easy. How common do we think it will be for people to hit this?

**Comment by Tratcher** [comment]
That workaround doesn't work, all of the Properties collections are empty. You'd have to go a step further and hook into an event and store the token yourself in HttpContext.Items.

**Comment by Tratcher** [comment]
Actually, isn't that token the same as the incoming Auth header value?

**Comment by HaoK** [comment]
I was just going by the description in the bug above: "When using JwtBearer auth, result.Properties is never set - however, the properties that are expected to be there are present on result.Ticket"

**Comment by HaoK** [comment]
Assuming that statement is correct, its there just in the wrong place

**Comment by HaoK** [comment]
RE how common this is @ajcvickers this bug has been there since 2.0, its not new in 2.1, so this is the first we've seen it, so its pretty uncommon I guess

**Comment by Tratcher** [comment]
No, I debugged it. Part of the trouble is that the ticket gets re-created and loses the Properties from the first ticket.

**Comment by HaoK** [comment]
Actually rereading the OP, this behavior is new to 2.1, let me see what changed in 2.1

**Comment by HaoK** [comment]
Can you try debugging this on 2.0.4 @Tratcher the code path looks the same to me in https://github.com/aspnet/Security/blob/2.0.4/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationResult.cs doesn't look like we changed anything other than rename the file and you tweaked the exception/error methods to include the properties

**Comment by TimHess** [comment]
For what this background is worth, this is the application I'm working on right now: https://github.com/SteeltoeOSS/Samples/tree/dev/FreddysBBQ

It uses [Steeltoe Security](https://github.com/SteeltoeOSS/Security/tree/dev/src/Steeltoe.Security.Authentication.CloudFoundryCore) for doing JWT on Cloud Foundry, via `Microsoft.AspNetCore.Authentication.JwtBearer`

I'm in the process of making sure that Steeltoe works with [asp]netcore 2.1, so the changes I'm making are almost exclusively TargetFramework and NuGet dependencies.

The code that's breaking is in GetClientAsync() inside this file https://github.com/SteeltoeOSS/Samples/blob/dev/FreddysBBQ/src/Common/Services/AbstractService.cs

The scenario is that of multiple microservices, where the user's credentials are passed down the chain (in this case a customer site calls an order service which then calls a menu service)

**Comment by Tratcher** [comment]
Yes this worked in 2.0. Here's what broke it:
https://github.com/aspnet/HttpAbstractions/commit/321639b0eb2098a6fe3b0d763f48ac3ed025a688#diff-7e92f7940da0e821fc452fc9950db334
AuthentiateResult.Properties change from a pass through to a local field.

**Comment by HaoK** [comment]
Ah cool, I actually looked at the PR...just in the wrong repo doh...I looked at the security half forgot there was a matching one in Http doh

**Comment by TimHess** [comment]
I was able to confirm that pulling the token out of the auth header from the incoming request works fine in my case, so I'm a lot less worried about the extension not working in 2.1.0. We don't depend on GetTokenAsync for anything other than this one sample, so we should be fine.

Thanks again!

**Comment by avaisane** [comment]
If AuthenticationProperties are not saved in cookie (e.g access_token) and/or able to get those after authentication/challenge flow, then it is just a deal breaker for me. You should at least give some example how to store this to enable access it on coming requests.

**Comment by Tratcher** [comment]
@avaisane JwtBearer never did store the token in a cookie. The Auth header is sent on every request and GetTokenAsync is only a shortcut for reading the header. You can read the auth header directly.

**Comment by Tratcher** [comment]
Ah, have you reproduce this with OIDC? This regression happened a year ago and I've definitely used that code path in OIDC since then...

**Comment by Tratcher** [comment]
Hmm, GetTokens works fine in the 2.1 branch in the OIDC sample. https://github.com/aspnet/Security/blob/dev/samples/OpenIdConnectSample/Startup.cs

**Comment by avaisane** [comment]
@tratcher. Thats correct, oidc is having similar phenomenon. After updating
to .net core 2.1.300 functionality break up.

ma 4. kesäk. 2018 klo 20.45 Chris Ross <notifications@github.com> kirjoitti:

**Comment by Tratcher** [comment]
How are you using it? The sample linked above is working fine.

**Comment by avaisane** [comment]
@Tratcher Goosh, we did broke our own code. We implemented the header trick mentioned above into our shared accesstokenfetcher componed, which was used by APIs and Web App. Thus it bypassed previous  httpContextAccessor.httpContext.GetTokenAsync() 80) Thanks anyway for you assistance!

**Comment by profet23** [comment]
This is just caused me to waste a day trying to figure out why our token authentication was failing...  any chance at a hot fix release of 2.1 with this fix?

**Comment by Tratcher** [comment]
@muratg ?
+This is a regression from 2.0.
-The workaround is trivial.

**Comment by muratg** [comment]
@Tratcher Could you file a bug for the patch candidate? Thanks.

**Comment by Tratcher** [comment]
Filed https://github.com/aspnet/Security/issues/1809

**Comment by plazav** [comment]
@Tratcher, even after updating to 2.2.0-preview2-35157 I still can reproduce this issue.
