### ISSUE TITLE
JwtBearerOptions.SaveToken tests

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#1768]
SaveToken does not have any tests and it regressed in 2.1. See https://github.com/aspnet/Security/pull/1767

@HaoK

**Comment by HaoK** [comment]
Are we sure this regressed in 2.1 as opposed to never working in 2.0? (given that we never had tests :)

**Comment by HaoK** [comment]
I didn't even realize save tokens was a thing for JwtBearer, I thought it was an OAuth only feature

**Comment by Tratcher** [comment]
FYI: GoogleTests covers this for the interactive OAuth flow. JwtBearer and OIDC are lacking test coverage though.

**Comment by Eilon** [comment]
We feel this is a low churn area, so no strong need to add tests for this.
