### ISSUE TITLE
Generating RequestTelemetry for the signin API call for OpenId

### ISSUE THREAD

**Issue by zippy1981** [aspnet/Security#1774]
I have an ASP.NET core using application insights and all the traces I put in in the callbacks get logged, but calls to /signin-oidc don't get logged.
 I added a call to `var telemetry = context.HttpContext.Features.Get<RequestTelemetry>();` in OpenIdConnectEvents.OnMessageRecieved and saw that I am getting a blank Request object unlike if I did that in a controller or in middleware were I'd have the request telemetry object that I could enrich.

I don't see calls to RequestTelemetry in this repository. Can you please add one? For now, is there a "last hook" that always fires so than I could send the telemetry myself if I enrich it throughout my callbacks?

**Comment by Tratcher** [comment]
It may just be an ordering issue. Where in startup do you add AI? Is it before or after Auth?

**Comment by zippy1981** [comment]
@Tratcher I added it right at the top:

        public void ConfigureServices(IServiceCollection services)
        {
            var connectionString = Configuration.GetConnectionString("Default");
            services.AddApplicationInsightsTelemetry();

And then I have a third party logging tool called serilog that is logging ILogger<T> to application insights traces

Also, in Program.cs I have this:

            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseApplicationInsights()
                .UseSerilog()
                .Build();

            host.Run();

Do you recommend another configuration option?

**Also note!** I did some more digging (and I'm probably opening up an issue in the ApplicationInsight repo):

TelemetryClient.Active.InstrumentationKey is not set until `Startup.Configure`, not during `Startup.ConfigureServices()`.  This is suspicious, but since telemetry is generally working, including most requests, probably a red herring.

And I went digging through the ApplicationInsights source code and saw that AddApplicationInsights only does anything if `ApplicationInsightsDebugLogger` is added to the DI container:

* https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/6e602f85b1d39d9e779f001297def36b1e935899/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L134
* https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/6e602f85b1d39d9e779f001297def36b1e935899/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L360

No matter what I comment out,  if I place`var appInsIsConfigured = services.Any(service => service.ServiceType == typeof(ApplicationInsightsDebugLogger));` as the first line in `ConfigureServices()`, then `appInsIsConfigured` always is true. So I am not sure what is happening there.

**Comment by Tratcher** [comment]
Please move this issue to the AI repo you linked to.

**Comment by Eilon** [comment]
Closing because this issue seems to be external to this project. Please log a new issue in the appropriate repo. Thanks!
