### ISSUE TITLE
WsFederation Token Encryption (Certificate)

### ISSUE THREAD

**Issue by qubicaamf** [aspnet/Security#1785]
Hi,
As you can read from [WsFederation authentication doc](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.1):

> [Microsoft.AspNetCore.Authentication.WsFederation](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.WsFederation) lacks support for token encryption, so don't configure a token encryption certificate...

We need this feature because of Signle-Sing-On auth system, that we want to implement in ours **public web apps** ([Azure App Services](https://azure.microsoft.com/en-us/services/app-service/) working as relying party-trust in our scenario) and other internal (web based) products.

Do you have any plan to add this feature?

**Comment by Tratcher** [comment]
This issue was moved to AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#966

**Comment by qubicaamf** [comment]
@Tratcher, we need to use it as an external login provider and [without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.1#use-ws-federation-without-aspnet-core-identity).
For this reason, i don't know if Azure AD Identity model ext is  the right repo.

Everything is working good following the doc, but we need to use the token encryption certificate to improve security on relying party-trust side (external web apps on azure app services).

**Comment by Tratcher** [comment]
They implement the low level protocol for us, encryption would be dealt with at that layer.
