### ISSUE TITLE
Facebook Api version exists/duplicated in code base

### ISSUE THREAD

**Issue by ry8806** [aspnet/Security#1786]
just looking at the commit to bump the facebook api version to 2.12 = #1306 
and this commit: https://github.com/aspnet/Security/commit/cc8acdff57a200966b6b695c7846dfde073cfe68
and there are multiple places where the version number exists, to me this feels a little dangerous/wasteful - having it defined in more than one place. This would also make sure the upgrade process is even easier 😺 

I could improve it, so that it only references the version in one place (in FacebookDefaults) and we could reference the version through the rest of the project??

Just wondering if this is something that may be considered?  I'm happy to knock out the very small amount of work pretty quickly

I have originally thought about doing something like:

```
public static readonly string FacebookVersion = "v2.12";
public static readonly string TokenEndpoint = $"https://graph.facebook.com/{FacebookVersion}/oauth/access_token";
```

**Comment by Tratcher** [comment]
That's a bit overstated, half of these are tests.

Feel free to send a PR, and to check on the other providers while you're at it.

**Comment by Eilon** [comment]
We wrote the code this way deliberately, so we are not planning to change this.
