### ISSUE TITLE
Jwt Authentication not work on Linux and Mac

### ISSUE THREAD

**Issue by PilgrimViis** [aspnet/Security#1787]
Looks like there is a compatibility issue with Jwt Authentication on Asp Net Core 2.1. On Windows my code works as expected, but under *nix system (Debian 9 and High Sierra) it throws exception while token validation.
I've configured it with the code provided below:

        private const string _privateKey = "<RSAKeyValue><Modulus>wCnmTiH/rFym9g2SSEn6f2pV6YQqFiV5ls3VqxUC3yeyk7UXFuEH/Kttbl2h4eOmXy7NCutmkyF+Mul5DeIs3X1jF6ZxTs3tIzBovV7lpIyQp9DUideSOy3jyu2pznP+l+XwkPwS5f4G43uFOTxU7KvXjJ8MLCNQ0TeY1wWVEkTX8JGEjv68dXEp8xOfMEDXkRYppEHy2g/FsDcqL+S33e/O5TQf2VSZpTH+COAz0nYwNs4RPuR6dpzOqeRhVMTVuOaAYYbzff15/bh1ytjXuZcuHsBUEe5zQnjV5iqIhzwtSw2p7jbIhOFq8DNUbOHKnLR1iI6tNXdz0NwMbTpLtw==</Modulus><Exponent>AQAB</Exponent><P>/23p95aUkenEzmgcH8+EIrkzotFVV15eRg7jtnY4rGbzZhY0mFMgnu1WGd0URFdY+D0QQEDI0+K68IlCYFMnZXPTX/4uD7cJtSfLKtTVc5kt1V6eE6r0nuGee1NImlVdokwtb1L/BMfco9wAm22NFCSm2f7RHWb8M2iNfxj/lbM=</P><Q>wJfNdK5AlVqCiFo1/iMhXiRrfry9Ri4WBg+G9kdelJh5rFYnFv4SGTeo/327pzaLSA59/idOTFG1wJjo9nnQZKfhVz3qPaq+OaThCU2d2YdMt1Kyl8VK4kziYf+9auem3J9WD5xiPPq4usDhuvhVKAJkjU6UkvTddrVUkvef9+0=</Q><DP>6vyvdjttyx8JE+rrlMhQg7FmM6/pl0sV59Xi4AW69cBww8ZB9LDlHdCymXCuKIFDNHzY6oOvPl8kJA3ipsNZRxhbqcApmAOIRsSpQGo1RPfzFozJWMa57UEbj9F6xaErVxhF5FiyjC9iaM0JMfSDCbj+Vyb6MtZ/xru1EOxqlck=</DP><DQ>NNoz3t5nCNWi1spy4MBBSvWRrmEbTCQflSAzuGhTk1HYqiumZI/q5ZK5xQt7MOMuC+M2PkYJHbaauzT7UZCSWN0dYPSz0KKHu4f83bG4LNcNfY2rRy00ZLAWvDATij/yMb9kPbp71yIzCcUe7VFzBRzK/WBgM4gRMp+GiyJ7eu0=</DQ><InverseQ>zDYpl2+9M4huyFY0L/WvZd7MYnYqEFMKIiRqTF2fUzT0mzCcLQcIb+a8LNkOIbIe199Zc64mdcjztMA0y2OW8Gsw2Twg6R2s1a3QNL7Fxsv9GE3JckLODcjJI8XprXwNxXu8HxFC/e6iG/urCvBAFAGlhGAlJ8qp3y3p9/oCDR8=</InverseQ><D>RSVOh8LYGw9jzJnpjzV/e6WpsFMsSbfGXqtGPT9cPywrp9a7rjHfC94rjFEI1R1zWkCe61T1HfApVuyH8KT3++MIaxQrJW4X7FeY+LtS6rjhvGD6eXcmWUET/Is0VOOMMuA8hg8ORc/4bpadw5CgBmF3OFRqrt8uT3ov9v89OssFqi48G0OHOZ+RLLQUazSgKAem00TI7xoIzpvEcALLyRlF9D39kB6Q4+5sNu4I8xOIPyBCH6TY24LARXwh++eeTDwD4wJDp1bk9Qsx/QQ8sQeKVrSc+0DWPrU1rsyuqWAL0LkI65Wt3fA7Zyd3oNEIU/I2+rau9Sc/0rT8j6Hm0Q==</D></RSAKeyValue>";
        private const string _publicKey = "<RSAKeyValue><Modulus>wCnmTiH/rFym9g2SSEn6f2pV6YQqFiV5ls3VqxUC3yeyk7UXFuEH/Kttbl2h4eOmXy7NCutmkyF+Mul5DeIs3X1jF6ZxTs3tIzBovV7lpIyQp9DUideSOy3jyu2pznP+l+XwkPwS5f4G43uFOTxU7KvXjJ8MLCNQ0TeY1wWVEkTX8JGEjv68dXEp8xOfMEDXkRYppEHy2g/FsDcqL+S33e/O5TQf2VSZpTH+COAz0nYwNs4RPuR6dpzOqeRhVMTVuOaAYYbzff15/bh1ytjXuZcuHsBUEe5zQnjV5iqIhzwtSw2p7jbIhOFq8DNUbOHKnLR1iI6tNXdz0NwMbTpLtw==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>";

        public void ConfigureServices(IServiceCollection services)
        {
            RsaSecurityKey publicKey;
            using (var rsa = RSA.Create())
            {
                rsa.FromXML(_publicKey); // rsa.FromXML do the same as FromXMLString from Net Framework 
                                                          // because FromXMLString not supported on Net Core platform. 
                publicKey = new RsaSecurityKey(rsa);
            }
            var tokenValidationParameters = new TokenValidationParameters()
            {
                RequireSignedTokens = true,
                RequireExpirationTime = true,
                IssuerSigningKey = publicKey,
                ValidateAudience = false,
                ValidIssuer = "CompanyName"
            };

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            }).AddJwtBearer(configureOptions =>
            {
                configureOptions.TokenValidationParameters = tokenValidationParameters;
                configureOptions.SaveToken = true;
            });
            // ...
        }

 And later in code I use Authorize attribute like this

        [Authorize(AuthenticationSchemes = "Bearer")]
        [HttpGet]
        public async Task<IActionResult> GetAllClientAppsAsync() 
        // ...

On Windows it works as expected. Returning 401 when I tampering with token and execute action code when token is valid. On Mac and Linux I got this exception

_Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: '[PII is hidden]'.
Exceptions caught:
 '[PII is hidden]'.
token: '[PII is hidden]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()_

**Comment by Tratcher** [comment]
This issue was moved to AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#968
