### ISSUE TITLE
ASP.NET Core 2 Jwt Auth with Azure B2C // IDX10500: Signature validation failed. Unable to match keys: 'egE8-_RcPdNjT_XFT6M9gNvrSoz9v7Nr6Br4wkbL1mg', 

### ISSUE THREAD

**Issue by mingderekwang** [aspnet/Security#1791]
Hi, as a reference from https://github.com/aspnet/Security/issues/1466# 

I got issue when I manually set the jwtMetedataAddress, there is code 

```c#
services.AddAuthentication(option =>
{
    option.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(jwtOptions =>
{
    jwtOptions.MetadataAddress = $"https://login.microsoftonline.com/{Configuration["AzureAdB2C:TenantId"]}/v2.0/.well-known/openid-configuration";  //ADD this will have an issue. If I remove this, it works fine. 
    jwtOptions.Authority = $"https://login.microsoftonline.com/tfp/{Configuration["AzureAdB2C:TenantId"]}/{Configuration["AzureAdB2C:Policy"]}/v2.0/";
    jwtOptions.Audience = Configuration["AzureAdB2C:ClientId"];
    jwtOptions.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
    {
        ValidIssuer = $"https://login.microsoftonline.com/tfp/{Configuration["AzureAdB2C:TenantId"]}/v2.0/",
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateTokenReplay = true,
        ValidateIssuer = true,
        ValidateIssuerSigningKey = true
    };
    jwtOptions.Events = new JwtBearerEvents
    {
        OnAuthenticationFailed = AuthenticationFailed
    };
});
```

**Comment by mingderekwang** [comment]
I had not tried this sample, I had tried the sample https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapi and upgrade the project to core 2.1, it has the same issue. If I am not input MetadataAddress it is fine, so if you think it is not a common issue, maybe just leave it there.

**Comment by blowdart** [comment]
@Tratcher any ideas?

**Comment by Tratcher** [comment]
The Authority is used to create the MetadataAddress if you don't provide one.
https://github.com/aspnet/Security/blob/d8821d7eb120744f5439bcf85ad39c72537e85d3/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerPostConfigureOptions.cs#L39-L45

If that works then the format of MetadataAddress you're providing is wrong. Why provide one if it works without it?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
