### ISSUE TITLE
SaveTokens Not working .net core 2.1.301

### ISSUE THREAD

**Issue by BruceHunter** [aspnet/Security#1793]
To get access_token via 2.1.301 - I had to add this code because SaveTokens = true doesn't work.

```c#
      .AddOpenIdConnect("oidc", options =>
            {
                options.Events.OnTokenValidated = context =>
                {
                    var accessToken = context.SecurityToken as JwtSecurityToken;

                    if (accessToken != null)
                    {
                        var identity = context.Principal.Identity as ClaimsIdentity;
                        if (identity != null)
                        {
                            identity.AddClaim(new Claim("access_token", accessToken.RawData));
                        }
                    }

                    return Task.FromResult(0);
                };
```

It's my understanding that SaveTokens = true is to add Claims that you can have access to in your Client apps (MVC etc).

**Comment by Eilon** [comment]
Closing as a dup of https://github.com/aspnet/Security/issues/1765, which is fixed by https://github.com/aspnet/Security/pull/1767, and will be in the 2.2 release.

**Comment by Tratcher** [comment]
FYI: This is not a direct duplicate, OIDC was not affected by #1765. This issue appears to be a mis-understanding of SaveTokens. The tokens are not saved as Claims, they're saved in the AuthenticationProperties collection returned along with the ClaimsPrincipal (See HttpContext.AuthenticateAsync). You can retrieve them via HttpContext.GetTokenAsync.

**Comment by estet** [comment]
But still closed...
