### ISSUE TITLE
Configuration has to be fixed in AddOpenIdConnect method call, before IOptions available

### ISSUE THREAD

**Issue by davidgouldtracsis** [aspnet/Security#1798]
The following method:

`public static AuthenticationBuilder AddOpenIdConnect(this AuthenticationBuilder builder, string authenticationScheme, Action<OpenIdConnectOptions> configureOptions)`

Requires that I know all of the values for OpenIdConnectOptions whilst configuring services; however some of these will be unavailable as I need to have progressed to be able to receive an IOptions<> class from the ServiceProvider.

For example, the exact URL to the OpenIDConnect service is a configuration option for the app as we can switch between UAT and Production environments, and we need to be able to alter this.

**Comment by blowdart** [comment]
@Tratcher what was your magic options thing?

**Comment by Tratcher** [comment]
@haok has a sample for PostConfigureOptions.

**Comment by davidgouldtracsis** [comment]
My understanding is that this should solve the problem, following much digging yesterday:

`
            IEnumerable<ServiceDescriptor> serviceConfigurators = new List<ServiceDescriptor>
            {
                ServiceDescriptor.Singleton<IPostConfigureOptions<OpenIdConnectOptions>, [LocallyDefinedClass : IPostConfigureOptions<OpenIdConnectOptions>]>(),
                ServiceDescriptor.Singleton<IPostConfigureOptions<OpenIdConnectOptions>, OpenIdConnectPostConfigureOptions>()
            };

            services.TryAddEnumerable(serviceConfigurators);
`

I would appreciate some advice as to whether this would cause any race conditions, or whether this is safe!

Thanks!

**Comment by Tratcher** [comment]
Using IPostConfigureOptions is correct, but you shouldn't need TryAddEnumerable? Why not call AddSingleton directly?

**Comment by davidgouldtracsis** [comment]
Thanks for all of your help guys!  Much appreciated.
