### ISSUE TITLE
Issue with set-cookie: .AspNetCore.xx in OpenId Authentication Flow

### ISSUE THREAD

**Issue by xrkolovos** [aspnet/Security#1799]
I use all the 2.1.1 nuget packages.
I am trying to implement authentication with "Microsoft.AspNetCore.Authentication.OpenIdConnect" and Identity Server.

When i am getting redirected back from Identity server (Hybrid flow) I get this error
> Error from RemoteAuthentication: Correlation failed.

I used fiddler to track this down and i found out that in the 302 Redirect there are some Set-Cookie headers that are not being respected.
My Request
```
HTTP/1.1 302 Found
Date: Thu, 05 Jul 2018 11:38:45 GMT
Server: Kestrel
Content-Length: 0
Location: https://auth.server.com/connect/authorize?client_id=.....
Set-Cookie: .AspNetCore.OpenIdConnect.Nonce.CfDJ8IT6M6oMPllOrMHpkZo8YAE02ndDQQ8-DoDodQjr-zQK0nw8Ato0lBv9OKdP3hvpPVHBvfIazX1TlmkwTnk8h0hMfy9tuyQzriRjlZA3UeCgVDUmk6WI-R7HZhaEr5QyQ8weT4DpsITQW2yY-Yc319zglOVWioD3s2b5-ojrnrUtwtAFolFQZP2DeazxLX7fXxqVErz2XHUHcHkq5BYOrUBSchaCYsGqAOzVI9eb7kksYJIVo92owx9ADj51d0s5NS8UFDD0gPDo8umhlp56QR0=N; expires=Thu, 05 Jul 2018 11:53:46 GMT; path=/signin-oidc; secure; samesite=lax; httponly
Set-Cookie: .AspNetCore.Correlation.OpenIdConnect.fcsmJq7buai120Obk_mm7rg-xQirBpqzROC0NJFeSd0=N; expires=Thu, 05 Jul 2018 11:53:46 GMT; path=/signin-oidc; secure; samesite=lax; httponly
```

But when i come back with this request cookies are missing
```
POST https://myapp.com/signin-oidc HTTP/1.1
Host: myapp.com
Connection: keep-alive
Content-Length: 1596
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: null
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: el,en-US;q=0.9,en;q=0.8

code=........
```

I use chrome.

**Comment by Tratcher** [comment]
Looks like a problem with `samesite=lax;` in the cookies. We set that to None:
https://github.com/aspnet/Security/blob/d0d72782745edc41c79c501ff2210058a4eadb46/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L75
But CookieSecurePolicy may upgrade it. Are you using CookieSecurePolicy? We override that minimum in the templates:
https://github.com/aspnet/Templating/blob/4ca00f6b1b16f0461e91cc7ba5028898b25f1b33/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Startup.cs#L59

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
