### ISSUE TITLE
The oauth state was missing or invalid.

### ISSUE THREAD

**Issue by jamierytlewski** [aspnet/Security#1800]
I know there's been some other questions on this, but I'm trying to use an OAuth2 client that uses a slightly older version of OAuth2 and I was wondering if there's a way to disable state and still be able to use OAuth2 middleware or am I going to have to make the calls on my own.

The other question is this seems also an older version as stated above and after I made the initial call to the /authorize it immediately returns the refresh_token in a POST. Which seems to be the Implicit Flow, which I know is not as secure, but I don't have many other options. 

What is the best way to use the middleware with Implicit Flow and ignoring the state? 

Thanks,

Jamie

**Comment by Eilon** [comment]
The state is required in ASP.NET Core's auth system to help prevent certain types of attacks. Closing this issue because we have no plans to change this behavior.
