### ISSUE TITLE
CookieAuthenticationHandler.RequestRefresh does not safeguard against ArgumentOutOfRangeException for DateTimeOffset.Add

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Security#1801]
https://github.com/aspnet/Security/blob/d0d72782745edc41c79c501ff2210058a4eadb46/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L88-L102

If the value of `expiresUtc` is very high (realistically, `DateTimeOffset.MaxValue`) then subtracting the value of `issuedUtc` to get the `timeSpan` results in `timeSpan` not being valid as an argument to `Add`: `The added or subtracted value results in an un-representable DateTime.` This prevents a developer from being to able to, say, set `context.ShouldRenew = true` from within `OnValidatePrincipal` and obtain the expected result of having the cookie renewed/refresh.

**Comment by Eilon** [comment]
Closing because we don't feel this is important enough to fix. Hopefully the error gives a hint that some unusually large date is being used. If you feel this happened in some reasonably common case, we can take another look.

**Comment by tuespetre** [comment]
@Eilon this is the case when the cookie is set to ‘not expire’ — the framework uses `MaxValue` — but there are times where we would like to cause a renewal.

**Comment by Eilon** [comment]
@tuespetre can you show more about what your app code would look like such that you would run into this? We took a look and everything we thought of we felt wouldn't be common.

**Comment by tuespetre** [comment]
I was wrong; we *are* setting the `ExpiresUtc` to `DateTimeOffset.MaxValue` (in the call to `SignInAsync`.)

`MaxValue` *seems* like the right way to say "This cookie should be considered non-perishable", but I suppose we could use `DateTimeOffset.UtcNow.AddYears(500)` to the same effect.

**Comment by Eilon** [comment]
@tuespetre yeah that's what we were thinking too. I doubt any web browser that exists today will exist in 500 years 😄
