### ISSUE TITLE
Can I use facebook or google oauth2 login without cookie?

### ISSUE THREAD

**Issue by HangJiang** [aspnet/Security#1802]
Can I use facebook or google oauth2 login without cookie to protect my restful api?
such as put the accesstoken into the autorization header？

**Comment by dallancarr** [comment]
It should be possible to craft a jwt to exchange for an access token. But it is very much dependent on what grant types these auth providers support.  I think Google only supports code grant but there is a service account option. 

https://developers.google.com/identity/protocols/OAuth2ServiceAccount

**Comment by Tratcher** [comment]
Not the ones we provide, they're designed for an interactive browser flow. What you want is a client SDK from facebook or google that gets you the JWT token, put it in the auth header, and then use the JwtBearer auth handler on the server turn that into a ClaimsPrincipal.
