### ISSUE TITLE
[bug].net core 2.1,Identity will throw exception while implement IdentityUser. But .net core 2.0 is Ok.

### ISSUE THREAD

**Issue by Caizhenyu** [aspnet/Security#1804]
I am using asp net core Identity Framework on core 2.1, and I implement my  `ApplicationUser : IdentityUser` .Then there will throw Exception like the screenshot .
But I found that, the same code is Ok on core 2.0, or I just user IdentityUser not my own ApplicationUser is also ok while `services.AddIdentity<TUser, TRole>`.

Is it's a core 2.1 bug?
![tim 20180707194836](https://user-images.githubusercontent.com/19528235/42410678-1fcd9ff0-8220-11e8-9bf7-27d4c34b266a.png)

**Comment by blowdart** [comment]
This issue was moved to aspnet/Identity#1872
