### ISSUE TITLE
v2.1 Identity authentication middleware

### ISSUE THREAD

**Issue by radupopConnatix** [aspnet/Security#1819]
As I understood there is new way for authorization in .netCore 2.1. As I created a new fresh project with the following dotnet cli command:
`dotnet new mvc -au individual`

It sets me to use identity, which I wanted, now I want to intercept the authentication so I can insert a bit more middle ware logic in there. As I need to port the info .net framework, I need to be able to do additional things to authentication.

I have tried to add something like this:
`services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            });`

and with this after a login the cookie is present in browser but the browser doesn't show any user info, looks like the user did not login.

From the above I my feeling is that there is a default authentication. How can I intercept that?

**Comment by blowdart** [comment]
What sort of things are you wanting to do? There might be a better way than middleware, for example events

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
