### ISSUE TITLE
How to add runtime openId configuration in .net core

### ISSUE THREAD

**Issue by EddieGahan** [aspnet/Security#1828]
After a research, I got to know that we can use SchemeProvider to use AddScheme at runtime from below links.

https://github.com/aspnet/AuthSamples/tree/master/samples/DynamicSchemes

My concern is how to add OpenIdConnectOptions at run time where all values of OpenIdConnectOptions will come from database in .net core

**Comment by Eilon** [comment]
There is no direct support for this at this time. We are tracking this feature request at https://github.com/aspnet/Security/issues/1826.
