### ISSUE TITLE
Shared cookie between applications with different sheme authentication

### ISSUE THREAD

**Issue by SchroterQuentin** [aspnet/Security#1833]
I have follow the documentation about shared cookie between application but i think the problem is my use case.

I have one application which use wsfederation to authenticate my user. And an other applications which run on the same URL, so which can read the cookie. Now I need to know if the user is authenticated and access to some claim. But the second application doesn't read the cookie and return a not authenticated user.

The cookie is only readable by WsFederation middleware? I can't understand why it's not working and I can't debug this part and I don't have log to said that the cookie is wrong or some stuff like that.

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.1&tabs=aspnetcore2x

**Comment by SchroterQuentin** [comment]
I finally find the code and understand how it works but did not succeed to understand where was my mistake. But if I'm right :

- Each Authentification Middleware must create a cookie which is encrypted by a data protector which is instantiated with this specific combination

**CookieAuthenticationMiddleware:40**
```cs
var dataProtector = provider.CreateProtector(typeof(CookieAuthenticationMiddleware).FullName, Options.AuthenticationScheme, "v2");
Options.TicketDataFormat = new TicketDataFormat(dataProtector);
```

So I think that my mistake is that the AuthenticationSheme is not the same in the two apps but I didn't manage to understand which params I have to change.

I did the test to finally give the protector provider and the ticketDataFormat on both of the application and it works as expected. It's ugly so if you have a nice solution I'm listening

So here is how it works for now :

**App 1**
```cs
services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo(Configuration["KeyStorageLocation"]))
                .SetApplicationName("SharedCookieApp");

var provider = ActivatorUtilities.GetServiceOrCreateInstance<IDataProtectionProvider>(services.BuildServiceProvider());
var dataProtector = provider.CreateProtector("toto");

services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.Name = ".AspNet.SharedCookie";
                options.DataProtectionProvider = provider;
                options.TicketDataFormat = new TicketDataFormat(dataProtector);
            });

services.AddAuthentication("CustomAuthentification")
                .AddWsFederation(options =>
                {
                    // MetadataAddress represents the Active Directory instance used to authenticate users.
                    options.MetadataAddress = "https://adfs01.gpi.pri/FederationMetadata/2007-06/FederationMetadata.xml";

                    // Wtrealm is the app's identifier in the Active Directory instance.
                    // For ADFS, use the relying party's identifier, its WS-Federation Passive protocol URL:
                    options.Wtrealm = Environment.GetEnvironmentVariable("EXTERNAL_URL");
                });
```

**App 2**

```cs
services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo(Configuration["KeyStorageLocation"]))
                .SetApplicationName("SharedCookieApp");

var provider = ActivatorUtilities.GetServiceOrCreateInstance<IDataProtectionProvider>(services.BuildServiceProvider());
var dataProtector = provider.CreateProtector("toto");

services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie(options =>
                {
                    options.Cookie.Name = ".AspNet.SharedCookie";
                    options.DataProtectionProvider = provider;
                    options.TicketDataFormat = new TicketDataFormat(dataProtector);
                }); 
```

**Comment by Eilon** [comment]
The answer to this question:

> Each Authentification Middleware must create a cookie which is encrypted by a data protector which is instantiated with this specific combination

Is yes.

We're closing this issue because it appears all the issues have been resolved.
