### ISSUE TITLE
multiple handlers for a requirement (AuthorizationHandler) HasSucceeded

### ISSUE THREAD

**Issue by shqu3** [aspnet/Security#1835]
Trying to follow this tutorial for creating multiple handlers.
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.1#why-would-i-want-multiple-handlers-for-a-requirement

For AuthorizationHandlerContext
when there are multiple Requirements 
**HasSucceeded** will be false if both requirements do not call **Succeed()**
since the only way to remove a **pendingRequirement** is to call **Succeed()**
and **HasSucceeded** checks if there are any **pendingRequirements** left
`!_failCalled && _succeedCalled && !PendingRequirements.Any();`

Expect **HasSucceeded** to return true if at least one policy succeeds per documentation.

> If either handler succeeds when a policy evaluates the BuildingEntryRequirement, the policy evaluation succeeds.

[AuthorizationHandlerContext.cs](https://github.com/aspnet/Security/blob/beaa2b443d46ef8adaf5c2a89eb475e1893037c2/src/Microsoft.AspNetCore.Authorization/AuthorizationHandlerContext.cs#L74)

As a workaround, removing the **requirement** from the **PendingRequirements**
```
protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, FooRequirement requirement)
{
    if (context.User.HasClaim(c => c.Type == "Foo"))
    {
        context.Succeed(requirement);
    }
    var pr = context.PendingRequirements as HashSet<IAuthorizationRequirement>;
    pr.Remove(requirement);
    return Task.CompletedTask;
}
```

**Comment by blowdart** [comment]
I think you're mixing up handlers, requirements and policies here. 

_Expect HasSucceeded to return true if at least one policy succeeds per documentation._

This isn't right, you can see the documentation is talking about handlers, not policies. A requirement will succeed if any of it's handlers succeeds, but if you have multiple requirements, or multiple policies, if any of them don't succeed then the overall evaluation is going to be "Nope"

**Comment by shqu3** [comment]
Yea I was. Thank you.
