### ISSUE TITLE
all the samples are in .net framework 4.6.1

### ISSUE THREAD

**Issue by ccm1st** [aspnet/Security#1836]
all the samples are in .net framework 4.6.1, can we upgrade it to dotnet core versions so that it will work for mac

**Comment by Tratcher** [comment]
? They're net461 AND netcoreapp2.2
https://github.com/aspnet/Security/blob/47c9141527b417ae41543534852aced5db1d9f58/samples/OpenIdConnectSample/OpenIdConnectSample.csproj#L4
