### ISSUE TITLE
Share cookies & tokens between asp.net core and legacy .net framework application.

### ISSUE THREAD

**Issue by WayneCBarker** [aspnet/Security#1838]
I have a custom identity provider (IP-STS) and several (RP) applications written in .net framework 4.6.2 implementing WS-Federation. We make use of reference mode for our token to reduce the size of our cookies and as such have a shared token cache in Redis.

We recently implemented an asp.net core website which need to participate in SSO to allow the user to have a seamless experience when navigating from the one site to the other.

1. What exactly needs to be done to allow SSO between .net framework sites and .net core?

2. I read that the cookie format and encryption is different in .net core. Will the .net core site be able to read the cookie coming from the IP-STS?

**Comment by Eilon** [comment]
@blowdart can you follow up on this with any guidance?

**Comment by blowdart** [comment]
Just my sample https://github.com/blowdart/idunno.CookieSharing
