### ISSUE TITLE
Microsoft.AspNetCore.Authentication.Core code?

### ISSUE THREAD

**Issue by dazinator** [aspnet/Security#1840]
Hello.
I am trying to diagnose an issue in my asp.net core 2.0 application, and I noticed that `services.AddAuthenticationCore()` is called which lives in a `Microsoft.AspNetCore.Authentication.Core` assembly - however I can't find the source code for this.. Could someone point me in the right direction?

Cheers

**Comment by HaoK** [comment]
https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationCoreServiceCollectionExtensions.cs#L20
