### ISSUE TITLE
Wreply url in WS-Federation starts with http instead of https

### ISSUE THREAD

**Issue by ccm1st** [aspnet/Security#1842]
Hi, 

I am using WS-Federation Url and for some reason, when I test the code with Kestral server, the wreply url is fine and the reply url starts with HTTPS. However, when I tested in IIS, the url starts with http instead of https, which request looks like following: 

GET https://xxx.com/example HTTP/1.1
Host: xxx.com
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,zh;q=0.8,zh-TW;q=0.7,zh-CN;q=0.6
Cookie: _ga=GA1.2.15284;
.AspNetCore.Antiforgery.5Z-vndGlgZs=CfDJ8NRqffxBK

Response Looks like this, as you can see the wreply is now http. (note some sensitive data are been replaced with xxx)

HTTP/1.1 302 Found
Date: Mon, 20 Aug 2018 08:41:38 GMT
Content-Length: 0
Connection: keep-alive
Location: https://adfs.xxx.com/adfs/ls/?wtrealm=https%3A%2F%2Fxxxx.com&wa=wsignin1.0&wreply=http%3A%2F%2Fxxx.com%2Fsignin-wsfed&wctx=CfDJ8XXXX
Set-Cookie: .AspNetCore.Correlation.WsFederation.bYfSySAj_E5VQMNfXgoUtHj9rTRTtGpAyH2tzHwMZj4=N; expires=Mon, 20 Aug 2018 08:56:38 GMT; path=/signin-wsfed; httponly

Any thoughts???

**Comment by blowdart** [comment]
What version of ASP.NET core are you using? What does your program.cs and startup.cs look like? (Please remove any secrets in either of these files)

**Comment by ccm1st** [comment]
@blowdart  thanks for the reply. I figured out it wasn't the problem of the framework. It was actually the load balancer forwarding request to port 80 of the instance that app seats on. 

This means app will always seeing traffic coming from an http request. The request schema in WS-Federation is used to generate the reply URL, which in this case it will always be http. Is there anyway to override the reply url so that I can manually replace the http with https?

**Comment by blowdart** [comment]
There's [middleware](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1) that understands load balancers, and WS-FED should pick that up if it's in play. If that's in the pipeline and configured correctly then we have a bug.

**Comment by ccm1st** [comment]
Looks great will give that a try. Thanks for the help @blowdart !
