### ISSUE TITLE
OpenId: private_key_jwt authentication method support

### ISSUE THREAD

**Issue by mathiasbl** [aspnet/Security#1846]
Are there plans to support the 'private_key_jwt' authentication method for OpenId?

**Comment by Eilon** [comment]
@brentschmaltz is this something in here or something in your area?

**Comment by mathiasbl** [comment]
I started implementing this and I am having issues to create the client assertions.
I have publics keys in json format and when trying to create a jwt token I get ''IDX10638: Cannot create the SignatureProvider, 'key.HasPrivateKey' is false, cannot create signatures. Key: Microsoft.IdentityModel.Tokens.RsaSecurityKey.''

```cs

            var handler = new JwtSecurityTokenHandler();

            var jwkset = JsonWebKeySet.Create(json);

            var signingCredentials = new SigningCredentials(jwkset.GetSigningKeys().First(), SecurityAlgorithms.RsaSha256);
            var header = new JwtHeader(signingCredentials);
            var payload = new JwtPayload
             {          
                 { "iss", "ClientId"},
                 { "sub", "ClientId"},
                 { "aud", "MyAudience"},
                 { "jti", Guid.NewGuid().ToString("N")},
                 { "exp", (int)(DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalSeconds + 5 * 60}
             };

            var securityToken = new JwtSecurityToken(header, payload);
            var clientAssertion = handler.WriteToken(securityToken);
```

Any idea what I'm missing? According to OpenID Connect you should sign it with your public key
[https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication)

The public keys look like this:
```json
{
  "keys": [
    {
      "kty": "RSA",
      "e": "AQAB",
      "use": "sig",
      "kid": "s1",
      "alg": "RS256",
      "n": "xxxx"
    },
    {
      "kty": "RSA",
      "e": "AQAB",
      "use": "enc",
      "kid": "e1",
      "alg": "RS256",
      "n": "xxxx"
    }
  ]
}

```

**Comment by blowdart** [comment]
We rely on libraries provided by AAD for our JWT support, you might want to ask them - https://github.com/AzureAD/azure-activedirectory-library-for-dotnet

**Comment by blowdart** [comment]
This issue was moved to AzureAD/azure-activedirectory-library-for-dotnet#1223
