### ISSUE TITLE
JwtBearerHandler And keys rollover management. How to do it properly.

### ISSUE THREAD

**Issue by Someguyatwork** [aspnet/Security#1848]
I'm trying to understand what is happening and what to do when the jwt signing keys must be updated.

Let's say we have a simple jwt server. And we also have several api configured with the MetadataAdress of JwtBearer pointing to a JWK endpoint (All this in .net core 2.1)

JwtBearerHandler (https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs) is calling Options.ConfigurationManager.RequestRefresh() in case of failure but :
- RequestRefresh only refresh the sync time (and only if there is a minimum time interval since the last refresh - 30 seconds by default, can be modified down to 1 second)
- The actual reloading of the configuration is done by manually calling ConfigurationManager.GetConfigurationAsync.
- It seem there is a periodical refresh as the configuration manager have a AutomaticRefreshInterval defaulted to 1 day (can be modified down to 5 minutes) but it does not seems to work at all :
I tried changing AutomaticRefreshInterval to 5 minutes and no refresh was ever triggered.

Conclusion : 
In case of failure a refresh will be asked but :
We need to add a OnAuthenticationFailed/JwtBearerEvent to manually trigger ConfigurationManager.GetConfigurationAsync, otherwise nothing will happen.
Even if we do that all the first api calls after a key rollover will fail.

To avoid this we can add a queue system : 
When a key update will happen the jwk end point will warn everybody by sending a message on a queue. 
All the api are listening to it and will try to trigger a resfresh when receiving the message. To work smoothly this imply that :
- We have at that time access to the JwtBearerOptions used at startup (or at least the ConfigurationManager created via the MetadataAdress). 
  I could not find any nice way to do this. I end up initializing an ugly static variable at startup :
  
  services.AddJwtBearer(o => { 
	... all the configuration stuff ...;
	StaticJwtOptions.Current = o;
  }
  
- We reduce the ConfigurationManager RefreshInterval to a few seconds.

So our code when receiving a refresh message on the queue will be like this : 

CancellationTokenSource cts = new CancellationTokenSource();
// Set the refresh interval to a few seconds to make sure the refresh is done
(StaticJwtOptions.Current.ConfigurationManager as ConfigurationManager<OpenIdConnectConfiguration>).RefreshInterval = TimeSpan.FromSeconds(5);

// trigger the refresh
StaticJwtOptions.Current.ConfigurationManager.RequestRefresh();
await StaticJwtOptions.Current.ConfigurationManager.GetConfigurationAsync(cts.Token);

This is actually working but :
- I still have the feeling that I fail to understand some point (especially the mystery of the non working periodical refresh)
- Am I over thinking this ? I'm not sure of the state of the art way to do all this ... 

Thanx for listening to my rambling ...

**Comment by Tratcher** [comment]
This issue was moved to AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1010

**Comment by Tratcher** [comment]
This issue was moved to AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1011
