### ISSUE TITLE
Microsoft.Extensions.Http.Polly.dll is code signed but Polly.Extensions.Http.dll and Polly.dll

### ISSUE THREAD

**Issue by abatishchev** [aspnet/Security#1849]
My Service Fabric + ASP.NET Core (API) application refers package Microsoft.Extensions.Http.Polly which contains Microsoft.Extensions.Http.Polly.dll which is code signed by Microsoft.

It refers two more packages: Polly.Extensions.Http -> Polly. Which respective dlls are not anyhow code signed. What raises an alerts when my application binaries are reaching our Test (PPE) environment.

How should I handle this? Code sign it myself, alongside with my own binaries? Would it be appropriate?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/HttpClientFactory#170
