### ISSUE TITLE
ASP.NET core 2.0 using wsfederation authentication application is in endless loop when logging in

### ISSUE THREAD

**Issue by AbhiShetti** [aspnet/Security#1850]
Hi , i have implemented the wsfederation auth with pingfederate identity , but after loggin my application is   
in endless loop. I am stuck at this point . can anyone please help me out from this.
I am attaching the startup.cs 
[Startup.txt](https://github.com/aspnet/Security/files/2347384/Startup.txt)
Also the wsfederation extenstion
[AddWsFedAuthenticationExtensions.txt](https://github.com/aspnet/Security/files/2347390/AddWsFedAuthenticationExtensions.txt)

**Comment by Tratcher** [comment]
The code samples are incomplete, please share a full project on GitHub that demonstrates the issue.

A Fiddler trace and application logs are useful for debugging loops like this.
