### ISSUE TITLE
Add a DelegatedAuthenticationHandler abstract class

### ISSUE THREAD

**Issue by huysentruitw** [aspnet/Security#1851]
I'm currently creating a custom authentication scheme based on `System.DirectoryServices` (Active Directory) for authenticating a user, so I essentially need a scheme that looks up a user identity in the Challenge method and than Signs in to f.e. Cookie middleware (determined by SignInScheme options).

A large part of the code I need for this is already in [`RemoteAuthenticationHandler`](https://github.com/aspnet/Security/blob/e2a07fbddcc5b1d9fb45ed94159f88fda87cbe0c/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs#L13), but I don't need the redirection logic.

So my question is, if it would be a good idea to create an additional abstract class `DelegatedAuthenticationHandler` that only does the SignInScheme-delegation, which can then be used as base class for the `RemoteAuthenticationHandler` ?

This abstract base-class would look a little bit like this:

```Csharp
public abstract class DelegatedAuthenticationHandler<TOptions> : AuthenticationHandler<TOptions>
    where TOptions : DelegatedAuthenticationOptions, new()
{
    private const string AuthSchemeKey = ".AuthScheme";

    protected string SignInScheme => Options.SignInScheme;
    
    protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        var result = await Context.AuthenticateAsync(SignInScheme);
        if (result != null)
        {
            if (result.Failure != null)
            {
                return result;
            }

            // The SignInScheme may be shared with multiple providers, make sure this provider issued the identity.
            string authenticatedScheme;
            var ticket = result.Ticket;
            if (ticket != null && ticket.Principal != null && ticket.Properties != null
                && ticket.Properties.Items.TryGetValue(AuthSchemeKey, out authenticatedScheme)
                && string.Equals(Scheme.Name, authenticatedScheme, StringComparison.Ordinal))
            {
                return AuthenticateResult.Success(new AuthenticationTicket(ticket.Principal,
                    ticket.Properties, Scheme.Name));
            }

            return AuthenticateResult.Fail("Not authenticated");
        }

        return AuthenticateResult.Fail("Remote authentication does not directly support AuthenticateAsync");
    }
}
```

Where `HandleAuthenticateAsync` is a 1-to-1 copy of the code in the `RemoteAuthenticationHandler`.

**Comment by Tratcher** [comment]
Since this is the first custom use case we've seen like this we are unlikely to factor out a special base class for it. RemoteAuthenticationHandler is the base class for dozens of providers.

It's a little odd for Challenge to directly call sign-in, Challenge is expected to produce an http response that the client needs to act on to sign in. This sounds more appropriate as an MVC controller that Cookie Auth redirects to.

**Comment by huysentruitw** [comment]
Yeah, having a controller action that creates a `ClaimsPrincipal` and passes it to `SignIn` directed to the Cookie scheme also works of course, and that's where we've started. However, the code looks cleaner now I've refactored it to an `AuthenticationHandler`. But I agree, it's a very special use-case 🙂
