### ISSUE TITLE
OpenIdConnect authentication doesn't use PathBase

### ISSUE THREAD

**Issue by drauch** [aspnet/Security#1854]
Hi!

We migrated from ASP.NET Core 1.1.x to 2.1.x and run into problems with our OpenIdConnect middleware.

Before we hosted our application at `https://server/WebApp/`, which is no longer possible in ASP.NET Core 2.1.x. We must host it at `https://server/` now and use `UsePathBase("/WebApp")`. Unfortunately, OpenIdConnect now changed the return URL parameter from `https://server/WebApp/signin-oidc` to `https://server/signin-oidc` which doesn't work.

How to tell OpenIdConnect to use the correct return URL?

**Comment by drauch** [comment]
UsePathBase() is the very first entry in the pipeline

**Comment by Tratcher** [comment]
Can you share Startup.Configure?

What component requires authentication? MVC? Then the order should be:
UsePathBase
UseAuthentication
UseMvc

**Comment by drauch** [comment]
I cannot share my `Startup` as it is proprietary code and moreover it is distributed amongst multiple files. But I can definitely confirm that the order is UsePathBase/UseAuthentication/UseMvc

**Comment by Tratcher** [comment]
I just re-verified this is working in our tests and samples. There's not much else we can do for you without an app that can reproduce your issue.

**Comment by Tratcher** [comment]
UseUrls behaved the same with prior versions of Kestrel, it did not reject requests based on path.

Consider using the Map example in the linked issue as an exclusive alternative.
