### ISSUE TITLE
JwtBearerHandler does not correctly use Scheme used when adding JwtAuthentication

### ISSUE THREAD

**Issue by quintonn** [aspnet/Security#1855]
When adding JwtAuthentication inside Startup.cs class like this:
`services.AddAuthentication().AddJwtBearer("NewBearer", options =>`
The class **JwtBearerHandler** does not correctly use the provided scheme to find the token when authenticating an access token.

The code seems to have hard-coded "Bearer". 
See line 73 of [JwtBearerHandler.cs](https://github.com/aspnet/Security/blob/beaa2b443d46ef8adaf5c2a89eb475e1893037c2/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs)

`if (authorization.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
                    {
                        token = authorization.Substring("Bearer ".Length).Trim();
}`

I think "Bearer" should be replaced by **Scheme**

**Comment by Tratcher** [comment]
No, this behavior is intentional. The "NewBearer" is uses as an internal identifier of the authentication handler, this is independent of the header value. You can use JwtBearerEvents.OnMessageReceived and OnChallenge to override the header value.

**Comment by quintonn** [comment]
Ok, it seems somewhat confusing.
What i was trying to achieve when i discovered this was to have 2 separate token endpoints on the same web server instance which use different signing keys. But only the first one is registered and used.
Is there a way to achieve something like this?
