### ISSUE TITLE
How to implement the option - "Login as another user" with windows authentication using .NET Core

### ISSUE THREAD

**Issue by Jenan** [aspnet/Security#1856]
I have tried to implement the option like "Login as another user" with Windows authentication - I have used the code snippet from SO - (https://stackoverflow.com/questions/17871816/login-as-another-user-mvc-4-windows-authentication/25672345#25672345):

```cs
public ActionResult LogOut()
{
    HttpCookie cookie = Request.Cookies["TSWA-Last-User"];

    if(User.Identity.IsAuthenticated == false || cookie == null || StringComparer.OrdinalIgnoreCase.Equals(User.Identity.Name, cookie.Value))
    {
        string name = string.Empty;

        if(Request.IsAuthenticated)
        {
            name = User.Identity.Name;
        }

        cookie = new HttpCookie("TSWA-Last-User", name);
        Response.Cookies.Set(cookie);

        Response.AppendHeader("Connection", "close");
        Response.StatusCode = 401; // Unauthorized;
        Response.Clear();
        //should probably do a redirect here to the unauthorized/failed login page
        //if you know how to do this, please tap it on the comments below
        Response.Write("Unauthorized. Reload the page to try again...");
        Response.End();

        return RedirectToAction("Index");
    }

    cookie = new HttpCookie("TSWA-Last-User", string.Empty)
    {
        Expires = DateTime.Now.AddYears(-5)
    };

    Response.Cookies.Set(cookie);

    return RedirectToAction("Index");

}
```

Is it possible to use following code snippet with .NET Core? I have tried to rewrite this snippet with methods in .NET Core but there are missing things like - Response.End etc.

How can I do it something similar in .NET Core?

Thx.

**Comment by Tratcher** [comment]
What a weird example. The only part that looks related to windows auth is the 401 status code and maybe the connection close.

**Comment by Jenan** [comment]
OK, I think it is inspired from the SharePoint - there is a feature - "Sign in as a Different User", I need achieve same thing in my intranet ASP.NET Core app.
Any ideas how to implement it? - We have the users with more accounts and I'd like to solve it.
Thx.

**Comment by rasitha1** [comment]
Here's how you can do that with ADFS + OIDC:

1. Trigger SignOut with a redirect uri pointing to an anon endpoint in your AccountController
2. In that SignOutCallback method, set a flag using AuthenticationProperties and trigger Challenge()
```csharp
            var props = new AuthenticationProperties
            {
                RedirectUri = url, 
            };
            props.Items.Add("login-prompt", "true");
            return Challenge(props);
```
3. In your OIDC config setup events and adjust the protocol message to set Prompt="login";
```csharp
                    options.SaveTokens = true;

                    options.Events.OnRedirectToIdentityProvider = ctx =>
                        {
                            switch (ctx.ProtocolMessage.RequestType)
                            {
                                case OpenIdConnectRequestType.Authentication:
                                    if (ctx.Properties.Items.ContainsKey("login-prompt"))
                                    {
                                        ctx.ProtocolMessage.Prompt = "login";
                                    }
                                    break;
                                case OpenIdConnectRequestType.Logout:
                                    var cp = ctx.HttpContext?.User?.Identity as ClaimsIdentity;
                                    if (cp?.BootstrapContext != null)
                                    {
                                        ctx.ProtocolMessage.IdToken = cp.BootstrapContext as string;
                                    }
                                    break;
                            }

                            return Task.FromResult(0);
                        };
```

**Comment by blowdart** [comment]
Yea, sharepoint if it shows this option is not using Integrated Authentication, it's using OIDC.

**Comment by rasitha1** [comment]
Our legacy intranet apps (before ADFS) had this requirement and the way we handled this was by having a `<location>` tag in the web.config and just for that location enabled windows auth. Rest was anonymous. So when a request came in, the application (auth filters) would see if user can do WIA and then redirect to that special endpoint. That endpoint would then use the windows identity and create a session cookie. When the user cannot do WIA, a login page was displayed to do forms auth. That was also used when a user explicitly signed out (so you can login as a different user). 

Just curious if something like that can be done in asp.net core? Can we have only some endpoints do Windows Auth?

**Comment by rasitha1** [comment]
> Just curious if something like that can be done in asp.net core? Can we have only some endpoints do Windows Auth?

Found the answer [here ](https://stackoverflow.com/questions/46084851/windows-and-anonymous-authentication-in-net-core-2-0)which points to an example [here](https://github.com/aspnet/ServerTests/blob/e155b814349f8ff9dd563480d784c38837b0b59f/test/ServerComparison.TestSites/StartupNtlmAuthentication.cs#L34-L59)

**Comment by Eilon** [comment]
Closing because there doesn't appear to be any action remaining in the Security repo.
