### ISSUE TITLE
HTTP Basic Auth via IIS

### ISSUE THREAD

**Issue by shorbachuk** [aspnet/Security#1860]
I understand the security problems around HTTP basic authentication.

From the README notes:

"ASP.NET Security will not include Basic Authentication middleware due to its potential insecurity and performance problems. If you host under IIS you can enable it via IIS configuration."

What does this mean? I enabled HTTP Basic in IIS and provided a Realm.  IIS is authenticating the requests and sending them to Kestrel, but Kestrel returns a 401. What needs to be done on the .NET Core side to make this work?

I have an Intranet app using Windows Authentication which I am trying to migrate to .NET Core 2.1
95% of my traffic is intranet users, however I have a few automated processes using (linux) clients that do not support Windows Authentication. I would like to use Basic to accommodate this. As I said this is intranet only and using SSL/TLS.

**Comment by Tratcher** [comment]
Do you already have the site working with [Windows Auth](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.1#iis-configuration)? The instructions for IIS Basic Auth aren't any different, it's only a matter of checking the Basic Auth [checkboxes](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/authentication/basicauthentication) when installing and configuring it.

**Comment by shorbachuk** [comment]
Yes, Windows Auth is working. 

I couldn't find any documentation that says IIS Basic Auth uses the same instructions. Are you saying that IIS passes the MS-ASPNETCORE-WINAUTHTOKEN header to Kestrel even when using IIS basic auth?

**Comment by Tratcher** [comment]
Correct, IIS processes the Basic credentials, converts it to a windows identity, and passes that to ASP.NET via MS-ASPNETCORE-WINAUTHTOKEN. Digest auth works the same way.

**Comment by shorbachuk** [comment]
Thank you, that is good info. Is there a way to debug to see if this is working?

Here are some of the relevant bits:

`services.AddAuthentication(IISDefaults.AuthenticationScheme);
services.AddMvc(options =>
	{
		options.Filters.Add(new ResponseCacheAttribute { NoStore = true, Location = ResponseCacheLocation.None });
	})
	.AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver())
	.SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

services.AddAuthorization(options =>
	{
	options.AddPolicy("Authenticated", policyBuilder => policyBuilder.RequireAuthenticatedUser());
	});`

On my controller I have:
`[ApiController, Authorize(Policy = "Authenticated")]`

Works with Windows Auth but not with IIS basic.

**Comment by shorbachuk** [comment]
I created some middleware to log the headers on the request coming from IIS. 
MS-ASPNETCORE-WINAUTHTOKEN is not present on a request coming from IIS authenticated with basic auth. 
`Connection:Keep-Alive
Content-Type:application/json
Authorization:Basic <REDACTED>
Host:redacted.com
User-Agent:Mozilla/5.0 (Windows NT; Windows NT 6.1; en-US) WindowsPowerShell/5.0.10586.117
MS-ASPNETCORE-TOKEN:a9b04e04-fc85-480e-9134-723d16689f5d
X-Original-Proto:http
X-Original-For:127.0.0.1:58064`

With Windows Auth, the header MS-ASPNETCORE-WINAUTHTOKEN and everything works fine.

**Comment by shorbachuk** [comment]
I think this tracks back to this line: 
https://github.com/aspnet/IISIntegration/blob/b6c311c14d3c3cf89b1b28d52efa0088a580213e/src/AspNetCoreModuleV2/OutOfProcessRequestHandler/forwardinghandler.cpp#L895

**Comment by Tratcher** [comment]
@pakrym can you confirm this for V1 and V2? I thought this worked for Basic as well. Does it work for in-proc?

**Comment by Eilon** [comment]
Assigning to @pakrym pending an answer to the above question.

**Comment by pakrym** [comment]
I don't know the answer from the top of my head, we would need to verify.

Filed: https://github.com/aspnet/IISIntegration/issues/1429

**Comment by Eilon** [comment]
Closing this issue here because as long as a lower level component such as AspNetCoreModule flows the token, the components in this repo should automatically light up.
