### ISSUE TITLE
DataProtection with ProtectKeysWithCertificate for Cookie Authentication shared by multi-apps.

### ISSUE THREAD

**Issue by kevinlo** [aspnet/Security#1879]
I have App1 and App2 that need to shared cookie authentication.   App1 is the first access application that will create the cookie to be shared by App2.   I put the following codes in both apps and it works fine.  I can see the key.xml with the encryptedSecret tag.

```
            services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo(myDataProtectionPath))
                .SetApplicationName("MyApp")
                .ProtectKeysWithCertificate(myCertificate);
                
            services.AddAuthentication()
                .AddCookie(CookieScheme, options =>
            {
                options.Cookie = new CookieBuilder()
                {
                    HttpOnly = true,
                    Name = "MyCookie",
                };
            };
```
            
Then , I remove the ProtectKeysWithCertificate(myCertificate) call in App2 like this

```
            services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo(myDataProtectionPath))
                .SetApplicationName("MyApp");
```

I expect the App2 cannot decrypt the cookie and the authentication will fail.  But instead, the cookie authentication pass and I see a new protection key file with unencrypted master key is created.

Is it a bug or I am missing something?   Could someone explain how it works?

**Comment by Tratcher** [comment]
That's expected. When App2 can't read any keys it will create its own. Is the concern that it wiped out the first one?

**Comment by kevinlo** [comment]
@Tratcher Could you explain how it works in this case?   App2 read the encrypted key file, it cannot decrypt it so it creates its own unencrypted one.   Is that key same as the one used by the App1 so it can use it to decrypt the cookie?    

In that case, why does it need to ProtectKeysWithCertificate, any app that knows the DataProtectionPath and ApplicationName can create the same key to decrypt the protected data?

**Comment by Tratcher** [comment]
@natemcmaster to confirm.

**Comment by kevinlo** [comment]
@natemcmaster 

> Yes, DataProtection will attempt to read all keys in your storage location (in your case, "myDataProtectionPath"). If it can decrypt a key, it will load and use it.

App2 does not have the myCertificate.  Why can it decrypt the key?   That is the main question I have why the App2 can decrypt the cookie even it does not have the myCertificate.  Does it read the certificate from the store?

**Comment by natemcmaster** [comment]
Yes, DataProtection will use certificates installed in the cert store, even if you did not programmatically call `.ProtectKeysWithCertificate` or `.UnprotectKeysWithAnyCertificate`.

Can you clarify the exact behavior you are seeing, and what you're expecting? I'm not sure what the problem is. Is App2 using the exact same key as App1 and shouldn't? Is the certificate used to encrypt the key for App1 installed in the machine running App2 but shouldn't be used? Something else?

**Comment by kevinlo** [comment]
Ok.  I just test it more.   I create the myCertificate in my testing server.   It does add the certificate to the Personal store.  After I delete that certificate in the store and now App2 has 

```
20181015 13:38:12,462 ERROR [XmlKeyManager] An exception occurred while processing the key element '<key id="9a207536-9af2-4dc6-bbff-9cb07e9b3bd1" version="1" />'. [(null) (null):3  ] 
System.Security.Cryptography.CryptographicException: Unable to retrieve the decryption key.
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.EncryptedXmlDecryptor.Decrypt(XElement encryptedElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)

```
After I add ProtectKeysWithCertificate back to App2 using the same myCertificate, the exception is gone.

That is what I expect.

@natemcmaster  I think you have answered my question 

> DataProtection will use certificates installed in the cert store, even if you did not programmatically call .ProtectKeysWithCertificate 

Could you please point me to the class and function that read the certificate in the store?  I would like to read how it works.  Does it try every certificate in the store?

**Comment by natemcmaster** [comment]
The class which decrypts the key is here: https://github.com/aspnet/DataProtection/blob/2.1.0/src/Microsoft.AspNetCore.DataProtection/XmlEncryption/EncryptedXmlDecryptor.cs. It uses [System.Security.Cryptography.Xml.EncryptedXml](https://github.com/dotnet/corefx/blob/v2.1.0/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/EncryptedXml.cs) which finds certs in the CurrentUser\My store.

**Comment by kevinlo** [comment]
Got it.  The Utils.BuildBagOfCerts in System.Security.Cryptography.Xml read the certificates from the LocalMachine and CurrentUser store.

Thanks all answering my questions.   I''ll close this issue.

**Comment by hem-sharma** [comment]
Using services.AddDataProtection().PersistKeysToAzureBlobStorage(Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(connectionString), keyPersistentPath) doesn't resolves private key, results "Keyset not exists" error, can anyone shed some light on it?
