### ISSUE TITLE
Question: Is it possible to update OpenIdConnectOptions at runtime?

### ISSUE THREAD

**Issue by AdamRiddick** [aspnet/Security#1889]
Hi,

We have a situation where the values passed into OpenIdConnectOptions are user configurable, as we have multiple providers.

This works great when configuring the options on startup with AddOpenIdConnect(), but we have the situation where the configuration has been changed and requires updating, or a new configuration needs adding.

Is it possible to add new providers, or update an existing provider, at runtime? I haven't been able to find any documentation on this.

Thanks.

**Comment by Tratcher** [comment]
Yes, see the sample at https://github.com/aspnet/AuthSamples/tree/master/samples/DynamicSchemes for adding and removing schemes.

**Comment by AdamRiddick** [comment]
Perfect - Thank you.
