### ISSUE TITLE
Add IAuthorizeAttribute  as a marker for AuthorizeAttribute.

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Security#193]

**Comment by HaoK** [comment]
@harshgMSFT Is this what you needed?

https://github.com/aspnet/Security/blob/haok/5-19authz/src/Microsoft.AspNet.Authorization/IAuthorizeData.cs

**Comment by harshgMSFT** [comment]
Yes. I think if you are okay with the name it can be closed. (IMO `IAuthorizeAttribute` is better than `IAuthorizeData`)

**Comment by muratg** [comment]
@HaoK should this be renamed, or his this one good to close?

**Comment by HaoK** [comment]
I called it IAuthorizeData for now
