### ISSUE TITLE
Regression: Cookie Auth Principal Validation routine not being called

### ISSUE THREAD

**Issue by borgdylan** [aspnet/Security#196]
I am giving a delegate when I configure cookie authentication so that the incoming principal gets validated. Using the latest nightly bits, this delegate is not getting invoked. Also ASP.NET is ignoring auth cookies that have been freshly made.

**Comment by HaoK** [comment]
The change made recently is that cookie auth middleware is not automatically authenticating anymore, AutomaticAuthentication = false by default, can you try setting the option to true and seeing if that restores the old behavior

**Comment by borgdylan** [comment]
Is the options in the CookieAuthOptions?

**Comment by HaoK** [comment]
Its in the base AuthenticationOptions so yes

**Comment by borgdylan** [comment]
Yes, using the following settings made it work for me:
```
method private void ConfigureCookieAuth(var cookieAuthOpts as CookieAuthenticationOptions)
    	cookieAuthOpts::set_CookiePath("/")
    	cookieAuthOpts::set_CookieName("mypimAuth")
		cookieAuthOpts::set_SlidingExpiration(true)
		cookieAuthOpts::set_AutomaticAuthentication(true)
		cookieAuthOpts::set_Notifications(new CookieAuthenticationNotifications() {set_OnValidatePrincipal(new Func<of CookieValidatePrincipalContext, Task>(ValidateCookie))})
    end method
```

**Comment by HaoK** [comment]
Cool this behavior is by design
