### ISSUE TITLE
[Design] Next authN iteration discussion

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#204]
Lets discuss what potential changes we might want for the next iteration of Auth.

1. Revisit/rename the sugar/packaging around the current set of Authentication data: (need new names)
```
    public class AuthenticationResult
        /// Contains the claims that were authenticated by the given AuthenticationScheme
        public ClaimsPrincipal Principal { get; private set; }

        /// Contains extra values that were provided with the original SignIn call.
        public AuthenticationProperties Properties { get; private set; }

        /// Contains description properties for the middleware authentication type in general. Does not
        /// vary per request.
        public AuthenticationDescription Description { get; private set; }
```

2. Consider storing the original AuthenticationResult for use as part of ClaimsTransformation (need to introduce a Context for claims transformation potentially?)

3. Consider renaming AuthenticaitonScheme to something that conveys its intent as an AuthHandler instance/name 

4. Review AuthenticationHandler base classes and patterns and modernize (less instances, more DI/Options)

cc @lodejard @davidfowl @Tratcher @blowdart @brentschmaltz @Eilon @tushargupta51 @Praburaj

**Comment by HaoK** [comment]
Would be good to address this issue as part of this work: https://github.com/aspnet/Identity/issues/185

**Comment by brentschmaltz** [comment]
I am trying to understand why signing is two parts. An AuthenticatationHandler (WSFed, OIDC), recognizes a signin message, processes it, returns a ticket, then it is called again to SignIn. 
What are we designing for by requiring the return trip.

**Comment by brentschmaltz** [comment]
To further that thought, the oidc handler creates a ticket only when it recognizes a signin response that it knows its instance sent (by validiating nonce, state). Validating the response and creating a ticket is signing in. WsFed, Samlp, OAuth signin work the same way.

**Comment by Eilon** [comment]
@HaoK please double check that we have an issue specifically about the claims transformation preservation.

**Comment by HaoK** [comment]
https://github.com/aspnet/Security/issues/284
