### ISSUE TITLE
OAuthBearerAuthenticationHandler does not call SecurityTokenValidated

### ISSUE THREAD

**Issue by mdekrey** [aspnet/Security#207]
It looks like `OAuthBearerAuthenticationHandler` doesn't call the `SecurityTokenValidated` handler in the `Options.Notifications`.

In addition, logic goes on to use `securityTokenReceivedNotification` - `securityTokenValidatedNotification` is not checked after being instantiated, but is used once, hiding it from any Treat Warnings as Errors flags.

Starting with line 133:

```csharp
var securityTokenValidatedNotification = new SecurityTokenValidatedNotification<HttpContext, OAuthBearerAuthenticationOptions>(Context, Options)
{
    ProtocolMessage = Context,
    AuthenticationTicket = ticket
};

// The following line is missing from source
await Options.Notifications.SecurityTokenValidated(securityTokenValidatedNotification);
if (securityTokenReceivedNotification.HandledResponse)
{
    return securityTokenValidatedNotification.AuthenticationTicket;
}
```

**Comment by PinpointTownes** [comment]
Duplicate of https://github.com/aspnet/Security/issues/140

I already submitted a PR to fix it: https://github.com/aspnet/Security/pull/168

/cc @brentschmaltz @HaoK @Praburaj @Tratcher

**Comment by mdekrey** [comment]
@PinpointTownes Somehow didn't find your issue when searching for it. Thanks for pointing it out!
