### ISSUE TITLE
How to use OpenIdConnect with ASP.NET Identity?

### ISSUE THREAD

**Issue by ninety7** [aspnet/Security#211]
I am writing a new MVC 6 app and cannot find a way to use ASP.NET Identity along with OpenIdConnect as an external provider (same way as Google or Twitter examples). Does anybody know if this is even possible? I want to be able to create a local account for each user and store his settings but provide a way for them to sign on using OpenId Connect.

**Comment by blowdart** [comment]
That's not what we're currently targeting OpenID connect at. As we we get closer to release we could examine treating it like any other social auth, but the templates and documentation, such as they are, are focusing on using it for authenticating to Azure Active Directory.

**Comment by ninety7** [comment]
Thanks for the super-fast response. Will using OAuth authentication work as a social authentication?

**Comment by blowdart** [comment]
It should do yes, I just can't point you at a sample for it :)

**Comment by HaoK** [comment]
Oath sample is here https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L51

**Comment by ninety7** [comment]
@blowdart I hope you consider treating openID connect as social auth in the future. For now, you can close the issue.
