### ISSUE TITLE
[Design] OpenIdConnect needs a definition for agumenting the 'state' parameter on request.

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#214]
If a users wants to add to the 'state' parameter when sending a request, there is no easy way to do this.

**Comment by PinpointTownes** [comment]
Adding custom properties to `AuthenticationProperties` when calling `HttpResponse.Challenge` sounds rather easy for me. Do you have something particular in mind?

**Comment by brentschmaltz** [comment]
That works fine with Challenge(...). I am thinking about a user that is hooking the RedirectToIdentityProviderNotification. The runtime sets OpenIdConnectMessage.State with protected AuthenticationProperties before the call. How would a user add to the state. I am thinking that it maybe we may want to pass the AuthenticationProperties to the notification and protect afterwards.

**Comment by Eilon** [comment]
This should be done as part of the recent PR that was merged.
