### ISSUE TITLE
OpenIdConnect: OpenIdConnectMessage.RequestType shouldn't be needed.

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#215]
A user needs to know the purpose of the RedirectToIdentityProviderNotification is it: SignIn or SignOut?
A property was added to OIDCMessage for this purpose. It seems a better place would be on the notification since this is not related to the OIDC message.

**Comment by Eilon** [comment]
@brentschmaltz is this cleanup that can be moved to beta7?

**Comment by tushargupta51** [comment]
@Eilon @brentschmaltz moved this to beta7

**Comment by Eilon** [comment]
Will be covered by https://github.com/aspnet/Security/issues/340.
