### ISSUE TITLE
OIDC - should allow 'code' only response_types

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#218]
OIDC middleware requires code as part of id_token + code.
Code should be processed by itself so that sign-in can occur using the UserInfo endpoint.
Code -> AccessToken -> UserInfo -> ClaimsPrincipal.

**Comment by PinpointTownes** [comment]
I think that userinfo is orthogonal here: it's useful, but not necessary - and not sufficient, as it doesn't help mitigating token substitution attacks - to correctly/safely authenticate the user. On the other hand, given that an `id_token` is always returned when you exchange the authorization code, it would be easier and safer to use it and apply the existing `id_token` validation process.

**Comment by brentschmaltz** [comment]
Perhaps I left out too many details.:
The flow is:
1. id_token + code
2. code - > accessToken (where accessToken gives access to UserInfo endpoint)
3. accessToken presented to UserInfo endpoint -> id_token

The id_token returned when obtaining an accessToken may or may not contain a comprehensive set of information.

**Comment by PinpointTownes** [comment]
Not sure to understand:

> The flow is:
1. id_token + code __-> how can you get an id_token here if you only ask for a code?__
2. code - > accessToken (where accessToken gives access to UserInfo endpoint)
3. accessToken presented to UserInfo endpoint -> id_token __-> hum, IIRC, you can't get an id_token via the userinfo endpoint: of course, similar parameters are returned (like `sub`), but others are not mandatory (like `iss` or `aud`)__

**Comment by brockallen** [comment]
As a side note, it might be worthwhile setting up and testing with IdentityServer to ensure the new OIDC middleware is working well with the protocol (beyond just azure's implementation).

**Comment by brentschmaltz** [comment]
Yes I agree.  With Katana we interop'd with Ping and Salesforce.  Which led to a couple of fixes. 
We also found issues with http://wso2.com/products/identity-server/ ( https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/100 ).

We don't have a formalized interop program which admittedly takes a lot of energy along with commitment.

**Comment by brockallen** [comment]
Okies -- that's all refreshing to hear. Thanks.

**Comment by brentschmaltz** [comment]
I'll close for now, since the middleware will allow 'code' response_type. We can open separate issues as needed.
