### ISSUE TITLE
Add property to RedirectToIdentityProviderNotification to indicate purpose of redirect

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#220]
RedirectToIdentityProviderNotification can be called for signin or signout. OpenIdConnectMessage.RequestType is currently being used to define the purpose. This pattern requires each additional protocol message to have this property.

**Comment by PinpointTownes** [comment]
Duplicate of https://github.com/aspnet/Security/issues/215?

**Comment by brentschmaltz** [comment]
it is a dup
