### ISSUE TITLE
AuthenticationHandler.SignIn sets SignoutContext to null, SignOut sets SignInContext to null

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#226]
This looks like an unexpected side effect and may surprise users. If it is by design, why is it necessary?

**Comment by Tratcher** [comment]
Yes this is by design. The most common scenario we see at the moment is that cookies get periodically renewed via sign-in, but the user may request to sign-out on the same request as the renewal. The sign-out should win in that case.

**Comment by brentschmaltz** [comment]
This seems non-deterministic for the user, essentially a race condition.

**Comment by Tratcher** [comment]
It has worked well in practice. Have you seen something break due to this?

That sounds like a whole new flow we'll have to investigate. I recommend tracking it separately.

**Comment by brentschmaltz** [comment]
I am designing SignOut and am studying solutions and noticed this issue.

**Comment by Eilon** [comment]
The behavior of SignIn/SignOut itself is by design in that the last one wins, so it's deterministic.

If there's another flow we need to consider, please do log an issue with that particular scenario.
