### ISSUE TITLE
AuthenticationHandler.SignInContext property should be ISignInContext

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#227]
ChallengeContext, SignOutContext both are interfaces. Should all three properties be interfaces?

**Comment by Tratcher** [comment]
I'm actually about to remove the interfaces. See https://github.com/aspnet/HttpAbstractions/pull/282

**Comment by brentschmaltz** [comment]
Good I personally prefer Abstract Base classes.

**Comment by brentschmaltz** [comment]
https://github.com/aspnet/HttpAbstractions/pull/282
Was merged
