### ISSUE TITLE
public class SignContext is defined in Microsoft.AspNet.Authentication and Microsoft.AspNet.Http.Authentication

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#229]
Is this by design? 
SignOutContext and ChallengeContext are only in Microsoft.AspNet.Http.Authentication.

**Comment by Tratcher** [comment]
This has already been addressed in the following PR:
https://github.com/aspnet/HttpAbstractions/pull/282

**Comment by brentschmaltz** [comment]
Nice, when that is merged I will close this.

**Comment by PinpointTownes** [comment]
@brentschmaltz done: https://github.com/aspnet/Security/commit/63fc18b945bb30b217de20d2aec7c042f70a68ae#diff-e87cbbc77b6641c451cf43aeb823bcb0L1 :dancer:
