### ISSUE TITLE
DefaultHttpResponse.SignOut has different guard logic than SignIn or Challenge

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#230]
SignOut:

```
if (!string.IsNullOrWhiteSpace(authenticationScheme) && !signOutContext.Accepted)
            {
                throw new InvalidOperationException("The following authentication scheme was not accepted: " + authenticationScheme);
            }
```

SignIn, Challenge:

```
if (!signInContext.Accepted), 
if (!challengeContext.Accepted)
```

Is the check for NullOrWhiteSpace significant for just SignOut?

Sorry, I should have put this in HttpAbstractions.

**Comment by HaoK** [comment]
I'll take a look

**Comment by muratg** [comment]
Does this need to change in Beta 6?

**Comment by HaoK** [comment]
It shouldn't be an issue after my changes go in
>

**Comment by muratg** [comment]
:+1: feel free to close this one after. :)

**Comment by HaoK** [comment]
Fixed as part of https://github.com/aspnet/Security/pull/283

ShouldHandle consolidates all the checks
