### ISSUE TITLE
Add sugar to make Authorize model parameter optional

### ISSUE THREAD

**Issue by blowdart** [aspnet/Security#238]
As it's not needed for in view checks.

**Comment by HaoK** [comment]
Unfortunately this causes issues with the params...

        Task<bool> AuthorizeAsync(ClaimsPrincipal user, object resource, params IAuthorizationRequirement[] requirements);

So we can't really do this easily since resource is untyped...

**Comment by HaoK** [comment]
Replacing params with IEnumerable so we can add sugarz

**Comment by HaoK** [comment]
17deab142da56b656bb2cd84dce294ca15135397
