### ISSUE TITLE
Hardcoded claim types for role and name

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#245]
You are using hard coded values for roles (ClaimTypes.Role) and Name (ClaimTypes.Name)

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authorization/AuthorizationPolicyBuilder.cs#L81-91

The ClaimsIdentity ctor allows mapping those claims to different types. I don't want to use 90ies style XML namespaces - and the external IdPs that send you those claims don't want to either.

ClaimsIdentity.Name and ClaimsIdentity.IsInRole would honour this mapping.

**Comment by HaoK** [comment]
This is really just meant to be sugar for the common case.  If apps are using different claim types for role/name.  They can simply use the Requires overload directly for their authZ policies.  @blowdart thoughts?  We haven't spent a lot of time looking at this area yet, so we can certainly discuss this more

**Comment by brockallen** [comment]
"Common" is relative, no? It's common in all the apps I work on that the ClaimsTypes class is never used.

**Comment by blowdart** [comment]
Well you could use claims transformation to map :) But, yea, Dominick is right here we should be using the Identity property rather than the claim name,

**Comment by HaoK** [comment]
Fair enough, just needs two new specialized requirements for this I guess, I can add this today

**Comment by blowdart** [comment]
Not really, we just need to map that claim requirement to not an actual claim name, but to a property.

So, for example, 

RequireClaim("urn:mstidentity.super.hao.name", userName);

And then when we encounter that, instead of looking for that actual claim, check the identity's Name property to discover the valid claim name for Name.

OK, that's given me a headache to type.

**Comment by blowdart** [comment]
Or, hmm, yea, specialized might be better, heh, now I think on how bad that was to explain.

**Comment by HaoK** [comment]
Yep, I took one look at the current requirement, and there was no way we were going to shoehorn that logic into it :)

**Comment by HaoK** [comment]
Fixed 434d158c7620fd75492ea5d03b6885246745b26c
