### ISSUE TITLE
Don't use the 'Windows' brand in the name of any APIs or packages

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#25]
When we port over the security middleware from Katana, rename WindowsAzureActiveDirectoryBearerAuthenticationOptions/Extensions to not use 'Windows'.
Ported from: https://katanaproject.codeplex.com/workitem/284

**Comment by Eilon** [comment]
@Tratcher I don't see any mentions of "Windows" in the codebase anymore. Is this good to close? Or do we need to hold on to this to protect some future work?

**Comment by Tratcher** [comment]
This was tracking future ports, but it doesn't look like we're going to do any of those.
