### ISSUE TITLE
Samples don't run in VS 2015 RC

### ISSUE THREAD

**Issue by StenPetrov** [aspnet/Security#251]
I downloaded this sample and ran it in VS 2015 RC. When the browser opens up there's an error message there:

Server Error in '/' Application.

No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +303

[HttpException (0x80004005): No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9940016
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261

**Comment by Tratcher** [comment]
It sounds like your version of dnx is out of sync with your version of Microsoft.AspNet.Server.IIS. Verify that everything is beta4 without any build numbers attached. Check your project.json and also run `dnvm list` from the command line.

**Comment by Tratcher** [comment]
@suhasj

**Comment by suhasj** [comment]
@StenPetrov I have updated the master branch. Can you clone the repo again and try ?

**Comment by StenPetrov** [comment]
I tried again with latest code, still the same error.

dnvm list returns

Active Version     Runtime Architecture Location                    Alias
------ -------     ------- ------------ --------                    -----
       1.0.0-beta4 clr     x64          C:\Users\Sten\.dnx\runtimes
       1.0.0-beta4 clr     x86          C:\Users\Sten\.dnx\runtimes default
       1.0.0-beta4 coreclr x64          C:\Users\Sten\.dnx\runtimes
       1.0.0-beta4 coreclr x86          C:\Users\Sten\.dnx\runtimes

**Comment by suhasj** [comment]
I am a still stumped since I was able to run all the four samples in this repo. My steps
- Clone latest master branch
- Open in VS 2015 RC
- Press F5

I was able to run them successfully. What branch are you cloning ? Can do a clean clone and try ?

**Comment by StenPetrov** [comment]
I'm downloading the zip from github, running it in vs2015 rc

**Comment by egorpavlikhin** [comment]
I get the same exception just after installing VS 2015 RC, upgrade dnvm and creating a new empty ASP .Net 5 MVC project.

**Comment by suhasj** [comment]
@egorpavlikhin is `dnvm upgrade` installing beta5 dnx and the projects still reference beta4 packages ? In that case this error is expected. You can use beta5 packages for the project and it should work fine

**Comment by suhasj** [comment]
@StenPetrov : Downloading the zip and running it worked for me. One question, when you do `dnvm list`, is there an asterisk (*) next to 1.0.0-beta4 ?

**Comment by sakopov** [comment]
I am also having the same issue running solution downloaded as zip. `dnvm list` looks like that of @StenPetrov.

**Comment by egorpavlikhin** [comment]
@suhasj steps 1-6 here do the trick https://github.com/aspnet/dnx/issues/1912#issue-78482547

**Comment by janna173** [comment]
I cannot run the samples either, running SKD beta4.
But `<dnvm upgrade>` is not working. Seems to be the same issue as [aspnet/dnvm/issues/190] (https://github.com/aspnet/dnvm/issues/190) although this is marked as closed.

**Comment by Eilon** [comment]
Hi everyone, we're still unable to reproduce this. Please make sure you're matching the right dnx with the build/branch you're using.
