### ISSUE TITLE
API authentication not available in templates

### ISSUE THREAD

**Issue by jraadt** [aspnet/Security#253]
When I go to create a Web API project in VS 2015 RC I'm unable to choose an authentication method and the template created has no authentication.  I couldn't find anything in the samples either.  What's the recommended method of security for Web APIs in MVC 6?

**Comment by Eilon** [comment]
@rustd can you track this as part of the templates work? I think then we can close this.

**Comment by rustd** [comment]
This is already tracked as template work. Closing this out.
