### ISSUE TITLE
Have an UseCookieAuthentication overload that takes in instance of DataProtectionProvider

### ISSUE THREAD

**Issue by suhasj** [aspnet/Security#259]
Based on the discussions to make the cookie compatibility between v4.5 and v5.0 apps, we need to have `UseCookieAuthentication` method take an instance of DataProtectionProvider which is shared among the apps.

**Comment by Tratcher** [comment]
Or put it on the options.

**Comment by HaoK** [comment]
+1 to options, I can do this together with the identity changes

**Comment by PinpointTownes** [comment]
IMHO, the best option would be to provide an extension method around `CookieAuthenticationOptions`, that would internally set the ticket data format using a given data protector.

```
app.UseCookieAuthentication(options => {
    options.UseDataProtector(protector);
});
```

**Comment by HaoK** [comment]
Well, today looks like there's the TicketDataFormat which takes the DataProtector in its ctor.  

So if we leave cookies alone as is, identity could simply configure things via

`options.TicketDataFormat = new TicketDataFormat(dataprotector);`

This doesn't look unreasonable, maybe we should just leave things be?

**Comment by Tratcher** [comment]
We have a token binding feature coming that may require us to work directly with the DataProtection classes on a per request basis. In that case I think we'd want it on the options.

**Comment by Eilon** [comment]
Related to https://github.com/aspnet/DataProtection/issues/85

**Comment by HaoK** [comment]
As discussed in https://github.com/aspnet/Security/issues/363, what we have today with overriding the TicketDataFormat is enough for cookie sharing
