### ISSUE TITLE
Microsoft.Owin.Security.OAuth should provide an extension point for exception handling/rethrowing

### ISSUE THREAD

**Issue by levicui** [aspnet/Security#261]
Hi there,

Our team is currently working on the error handling feature in the Owin OAuth MiddleWare, specifically we are calling the WindowsAzureActiveDirectoryBearerAuthenticationExtensions and JwtBearerAuthenticationExtensions to feed in the oauth related BearerAuthenticationOptions into the Owin authentication middleware for the authentication.

The authentication and logging logic works as expected. However, we also have a requirement to get the details of the exceptions happened during the authentication (i.e. audience/issuer, token, identity validation failures etc.) - not only have them logged properly, but also need to throw an exception and circuit back to the upper caller.

For example, we use the customized functions ValidateAudiences/Issuer in Token validation params:

            app.UseWindowsAzureActiveDirectoryBearerAuthentication(new WindowsAzureActiveDirectoryBearerAuthenticationOptions
                {
                    TokenValidationParameters = new TokenValidationParameters() { 
                        ValidAudience = true,
                        ValidateIssuer = true,
                        ValidateIssuerSigningKey = true,
                        AudienceValidator = this.ValidateAudiences,
                        IssuerValidator = this.ValidateIssuer}
                });

And I our implementation, there are various specific exceptions being thrown from these two functions, and it would be great if the underlying OAuthBearerAuthenticationMiddleware could be able to notify/rethrow these exceptions to the upper middleware layer, BUT 1) there seemed no exception related extension points for that purpose; 2) The method in OAuthBearerAuthenticationHandler.AuthenticateCoreAsync() is doing try catch with return null that suppresses all the exceptions being thrown:

            ....
            catch (Exception ex)
            {
                _logger.WriteError("Authentication failed", ex);
                return null;
            }

It would make our life much easier if we could expose an extension points for exception handling delegate or the ability to rethrow those exception to upper layer for capturing them.

And thus, the upper layer could have control to decide whether to terminate the further middleware processing in the pipeline or not, if an exception is thrown.

Thanks!

**Comment by brentschmaltz** [comment]
@levicui can you have a look at the OpenIdConnectMW model and see if that fits?

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Security/issues/55

**Comment by brentschmaltz** [comment]
@Tratcher @PinpointTownes I put a comment in #55 wondering about throwing in general from a handler.  thoughts?

**Comment by levicui** [comment]
@brentschmaltz @Tratcher Thanks for commenting. I go over that thread, and I was thinking because our scenario is designed to use "UseWindowsAzureActiveDirectoryBearerAuthentication" and JwtBearerAuthentication MWs, which don't have an extension for notification handling, is there anyway to customize those two MWs to handle the notification similarly as OpenIdConnectMW?

**Comment by Eilon** [comment]
Let's track the error handling improvements in https://github.com/aspnet/Security/issues/55.
