### ISSUE TITLE
AuthorizeAttribute with Groups for Group-Based Permissions

### ISSUE THREAD

**Issue by mojtabakaviani** [aspnet/Security#262]
Next version of Asp.Net Identity will be Implementing ['Group Based' Permissions Management](https://github.com/aspnet/Identity/issues/184) for large numbers of users please add groups named parameters to AuthorizeAttribute that easy authorize groups every where.

**Comment by hishamco** [comment]
@mojtabakaviani  You asking for something like ```[Authorize(Roles = "Administrators")]``` this is already implemented have a look https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authorization/AuthorizeAttribute.cs#L21

**Comment by blowdart** [comment]
Groups are an ease of administration concept. 

Group = collection of users.

You authorize on permissions.

Roles = collection of permissions.

Groups are not suitable for authorization.

**Comment by mojtabakaviani** [comment]
Right, but if can add groups to Authorization mechanism so 
```[Authorize(Groups = "Administrators")]```

**Comment by blowdart** [comment]
It won't happen. Groups are not meant for, nor designed for authorization.

**Comment by HaoK** [comment]
@blowdart can we just close this since you won't fixed?

**Comment by blowdart** [comment]
Closed, by design.
