### ISSUE TITLE
[AuthZ] Consider new sugar for adding auth handler

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#265]
@divega suggested something like this to make it easy to register a handler/requirement all at once without implementing a new class/interface (the sugar only would exist for the sync scenario):

[Need a new name other than Magic...]

```
        policy.AddRequirement(new MagicRequirement(context, req => { context.Fail() }));

        // Add this come up name
        public class MagicRequirement : AuthorizationHandler<MagicRequirement>, IAuthorizationRequirement
        {
            public Action<AuthorizationContext, MagicRequirement> Handler { get;  }

            public MagicRequirement(Action<AuthorizationContext, MagicRequirement> handleMe)
            { Handler = handleMe; }

            protected override void Handle(AuthorizationContext context, MagicRequirement requirement) 
            { Handler.Invoke(context, requirement); }
```

**Comment by HaoK** [comment]
cc @blowdart thoughts?

**Comment by blowdart** [comment]
They'd have to be very simple requirements then if you wanted to specify them like that, but, meh, I have no objections, as long as the existing methods still work for more "grown up" requirements

**Comment by HaoK** [comment]
https://github.com/aspnet/Security/pull/283
