### ISSUE TITLE
[AuthZ] Consider short circuiting when a handler fails?

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#268]
@blowdart @divega @lodejard 

For our default authorization service implementation, should we short circuiting running any more handlers if any handler fails the context?  Do we care about any side effects of the handlers running?  They won't be able to undo the failure, so Authorize will definitely fail even if they run.

**Comment by blowdart** [comment]
I had suggested this before, I can't remember why there were objections.

**Comment by Eilon** [comment]
@lodejard do you have thoughts on whether it's ok to short-circuit authZ providers after one already rejected the person?

**Comment by lodejard** [comment]
I'd suggest letting them run. We don't know what the user might be trying to do in them, like log denials, or even something simple like setting a breakpoint in their code. It would seem like the their condition wasn't being tripped based on the order the rules were being evaluated.

**Comment by HaoK** [comment]
Ok leaving this behavior unchanged for now
