### ISSUE TITLE
Revisit Cookie's custom AJAX redirect

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#27]
The cookies middleware has custom redirect logic for AJAX requests, where it sends a 200 and embeds the real status code and location header inside a custom response header.  Everybody I've asked says this was done to support the first version of templates, but I can't find any reference to it there. The templates have since been modified. Do we still need this strange custom behavior?
RE: https://katanaproject.codeplex.com/workitem/264

**Comment by Eilon** [comment]
Remove this behavior in Cookies.DefaultBehavior.

**Comment by HaoK** [comment]
cd237445ec49f7def7978db5a6e1a44e691450da
