### ISSUE TITLE
Cookie MW null reference exception

### ISSUE THREAD

**Issue by dolly22** [aspnet/Security#270]
I'm getting null reference exception from cookie authentication middleware when protecting authentication ticket. This happens when the following conditions occur on request:

1. Sliding expiration is enabled and enough time passed so middleware tries to refresh authentication ticket (setting `_shouldRenew = true`)
2. Principal is rejected in `Options.Notifications.ValidatePrincipal` notification (setting `Context.Principal = null`)
3. `_shouldRenew` path is hit inside `ApplyResponseGrantAsync()` and null reference is thrown from `Options.TicketDataFormat.Protect(model);` because `Principal` was set to null.

Also `Security/src/Microsoft.AspNet.Authentication.Cookies/Notifications/CookieValidateIdentityContext.cs` should be probably renamed to `CookieValidatePrincipalContext.cs`

**Comment by muratg** [comment]
@HaoK Could you have a look?  We can move it out of Beta 6 based on your workload.

**Comment by HaoK** [comment]
d7ce42dacc226c74056a6c0883f9b3e2be7828d7
