### ISSUE TITLE
Consider factories / interfaces within OAuthAuthenticationHandler to support additional access token properties

### ISSUE THREAD

**Issue by amattie** [aspnet/Security#271]
[1.0.0-beta4]

Currently in [OAuthAuthenticationHandler](https://github.com/aspnet/Security/blob/1.0.0-beta4/src/Microsoft.AspNet.Authentication.OAuth/OAuthAuthenticationHandler.cs), [TokenResponse](https://github.com/aspnet/Security/blob/1.0.0-beta4/src/Microsoft.AspNet.Authentication.OAuth/TokenResponse.cs) and [OAuthGetUserInformationContext](https://github.com/aspnet/Security/blob/1.0.0-beta4/src/Microsoft.AspNet.Authentication.OAuth/Notifications/OAuthGetUserInformationContext.cs) expect an OAuth token with only a limited number of fields. The [OAuth RFC in 4.2.2](https://tools.ietf.org/html/rfc6749#section-4.2.2) says that "client MUST ignore unrecognized response parameters", indicating that unrecognized parameters can exist. It'd be nice to be able parse and grab extra parameters by providing my own factory for creating an ITokenResponse that'll eventually pass those parameters to the OAuthGetUserInformationContext so that they can be available to be put into claims.

My current use case is for [Salesforce's OAuth flow](https://help.salesforce.com/HTViewHelpDoc?id=remoteaccess_oauth_refresh_token_flow.htm&language=en_US), which provides an ```instance_url``` and ```id``` property in the token that's needed to interact with the service. Without added functionality to override the token parsing, I'm forced to reimplement most of OAuthAuthenticationHandler.

Furthermore, but separately, it doesn't seem that the current TokenResponse or OAuthGetUserInformationContext supports the error notifications allowed in the token in [section 4.2.2.1](https://tools.ietf.org/html/rfc6749#section-4.2.2.1).

**Comment by PinpointTownes** [comment]
Duplicate of https://github.com/aspnet/Security/issues/101

I'll fix it as part of this PR: https://github.com/aspnet/Security/pull/257

**Comment by PinpointTownes** [comment]
FYI: having a Salesforce-specific provider is on our radar for aspnet-contrib: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/14

Feel free to participate if you want to :smile:

**Comment by Eilon** [comment]
Yup, basically a dup of https://github.com/aspnet/Security/issues/101.
