### ISSUE TITLE
[AuthN] Clean up 401-403 AuthenticateCalled

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#273]
Currently for 401-403 to work, the AuthenticateCalled flag must be set.  This is a pretty obscure thing for subclasses to be required to do and is very easy to miss.  Cookie was missing this and as a result broke 401-403.  We should revisit this and see if there's anyway to make this more seamless...

@blowdart

**Comment by HaoK** [comment]
# Summary of plan:

## HttpAbstractions:
```
public enum ChallengeBehavior { Automatic, Unauthorized, Forbidden }

Add ChallengeBehavior property to ChallengeContext

new methods on AuthenticationManager:

// calls Challenge with Forbidden behavior
public void Forbidden(string authenticationScheme, AuthenticationProperties properties)

// Existing challenge uses Automatic behavior (where the middleware decides challenge behavior
```

## AuthenticationHandler changes:

- AuthenticationScheme is required for SIgnIn/SignOut, no more overloads that sign in/sign out all automaticAuthentication middlewares (this setting now only affects ApplyResponseChallenge automatically getting called on the way out, and Authenticate getting called on the way in)

- Immediately change status codes/set headers/cookies for SignIn/SignOut/Challenge instead of deferring the changes until ApplyResponse
- ApplyResponseChallenge will still need to check for the AutomaticAuthentication chase which will then call handler's Challenge method explicitly (the non chained version)

- There will be a helper method in AuthenticationHandler which uses new ChallengeBehavior property:
```
        public virtual void Challenge(ChallengeContext context)
        {
            if (ShouldHandleScheme(context.AuthenticationScheme))
            {
                HandleChallenge(context)
                context.Accept();
            }

            if (PriorHandler != null)
            {
                PriorHandler.Challenge(context);
            }
        }

// If this returns true, challenge method should stop and just return 
protected virtual void HandleChallenge(ChallengeContext context) {
   switch (behavior) {
     case Automatic:
        if (Response.StatusCode != 401) return false;
        var ticket = Authenticate(options.AuthenticationScheme);
        var foundPrincipal = ticket.Principal != null;
        if (!foundPrincipal) {
           HandleForbidden();
         }
         HandleUnauthorized();
         return;
     case Forbidden:
         HandleForbidden()
         return;
     case Unauthorized:
         HandleUnauthorized();
         return;
   }
}

// Cookie Middleware would override this to 302 to AccessDenied if options set
public virtual void HandleForbidden() {
    Response.StatusCode = 403;
}

// Cookie Middleware would override this to 302 to LoginPage if options set
public virtual void HandleUnauthorized() {
    Response.StatusCode = 401;
}

```

@lodejard is this what you had in mind?

cc @blowdart @davidfowl @Tratcher

**Comment by PinpointTownes** [comment]
Kewl, another totally insane design for 403 handling :smile: 

I'll probably repeat myself, but authentication middleware are __NOT__ the right place for that. The weirdest thing with this new approach is that you (= the ASP.NET team) don't seem to realize that it is semantically aberrant: a "challenge" operation (or whatever you call it) cannot result in a 403 response (like your snippets suggest): a challenge is ALWAYS the consequence of a 401 response: http://tools.ietf.org/html/rfc2617

> AuthenticationScheme is required for SIgnIn/SignOut, no more overloads that sign in/sign out all automaticAuthentication middlewares (this setting now only affects ApplyResponseChallenge automatically getting called on the way out, and Authenticate getting called on the way in)

> Immediately change status codes/set headers/cookies for SignIn/SignOut/Challenge instead of deferring the changes until ApplyResponse

Interesting. What's the reason behind these changes?

**Comment by PinpointTownes** [comment]
@HaoK FYI, I'm prototyping a new authorization middleware that reuses the (excellent) CORS approach and offers a far better way (at least, IMO) to handle authorization: https://github.com/PinpointTownes/Security/commit/7ac1a2515015a98dc6f4919f28baa9db33beb50a#diff-7bf20fd130932f29f2028b7126281f84R58

(it doesn't build as I haven't updated the tests but you should get the idea)

**Comment by HaoK** [comment]
https://github.com/aspnet/Security/pull/283
