### ISSUE TITLE
Problem with Token FormatVersion(TicketSerializer) from Owin .net 4.5 and new aspnet .net 4.6|5

### ISSUE THREAD

**Issue by jkljajic** [aspnet/Security#280]
Really do not know if here is good to ask question like this or write notice of my problem but i will try.

Looking how to implement security for current application that we do not want to change to much on old application. i have notice that some protection will be different. But after some time i make some 
custom IDataProtector and IDataProtectorProvider that works on old apps and new beta .net.
i have notice than i have big issue in TicketSerializer that those new and old format are totally different old is *FormatVersion = 3*(use also gzipcommpression) and new is *FormatVersion = 2*(don't use gzipcompression) and if you make AuthenticationTicket protected and serialized in old cant be used in new .net 5.
My question is this is planed to be like this or this is bug or will be backward compatibility manged much latter when product go in RC or final state.

Do we, if we plane to use old format from .net 4.5 need to create new custom TicketSerializer and custom IDataProtector that can work in new .net 5.

**Comment by Tratcher** [comment]
@HaoK Where is that compat shim and docs you were working on for this?

**Comment by blowdart** [comment]
http://docs.asp.net/en/latest/security/data-protection/compatibility/cookie-sharing.html

Note that this needs you to switch data protectors in the asp.net 4.0 app. It's not just a matter of compression, it's also a matter of keys.

**Comment by jkljajic** [comment]
Tanks
I have found that link (and it help me to much) but like you see in that docs you need to install BETA apps (Microsoft.AspNet.DataProtection) that is not possible in my case.
About compression i have solve that part. make my own IDataProtectionProvider.

But my is question it is plane to left like that (2 different version old one and new one ) and use some third party software or we just need to wait release, or we need to start make our own solution for that.

thank you in advance

**Comment by blowdart** [comment]
We're currently exploring compatibility options. Is your beta concern you have to install beta libraries in a release 4.5 app to support a beta 5.0 app?

**Comment by Eilon** [comment]
Closing this because we'll track the product work in https://github.com/aspnet/Identity/issues/457.
