### ISSUE TITLE
[AuthN] API Review - Changing Authenticate signature

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#282]
- Signature on AuthenticationManager becomes, with AuthenticationResult absorbed by the context
```
   public void Authenticate(AuthenticationContext context);
   public Task AuthenticateAsync(AuthenticationContext context);
```

New sugar extension method to directly return the ClaimsPrincipal (accessing AuthenticationProperties means no sugar[not common, identity would use this])
```
   public static ClaimsPrincipal Authenticate(this IAuthenticationManager manager, string authenticationScheme)
   public static Task<ClaimsPrincipal> AuthenticateAsync(this IAuthenticationManager manager, string authenticationScheme)
```

cc @lodejard @davidfowl @blowdart @Tratcher @divega

**Comment by PinpointTownes** [comment]
Out of curiosity, why not keep the current API and simply providing an extension method directly returning `ClaimsPrincipal`?

Personally, I'm not a huge fan of exposing `AuthenticateContext` for the reasons pointed out by Darrel on the PR.

**Comment by HaoK** [comment]
AuthenticateContext was actually already exposed in http features. Since we can only have one authenticate method that takes a single authentication scheme, it seems reasonable to have that method be the most commonly used one.

**Comment by PinpointTownes** [comment]
You mean that *Microsoft.AspNet.Http.Abstractions* will now depend on *Microsoft.AspNet.Http.Features*? It seems a bit odd, no?

I'm not sure changing this API will be really useful anyway: you have no reason to use *Authenticate* with authentication middleware configured in active mode, except to retrieve the *AuthenticationProperties*, as it's far easier to use *HttpContext.User* to get the principal. Why making this API harder to use for advanced developers, who are obviously the only ones using this more complicated passive mode?

**Comment by HaoK** [comment]
So I get where you are coming from. This is indeed harder for people who are writing auth middleware (so you and I suffer a bit). But the vast majority of people when calling authenticate are only looking for the claims. 

It's really ONLY auth middleware authors who don't want to pollute the claims identity with extra internal data that use the properties. And I think this extra burden isn't too bad for the advanced developers who are working with the auth middleware (I think you would agree it's not exactly the most straightforward thing to implement correctly already haha). The benefit of removing the description and properties off the primary authenticate Apis is worth it.

**Comment by PinpointTownes** [comment]
> So I get where you are coming from. This is indeed harder for people who are writing auth middleware (so you and I suffer a bit). But the vast majority of people when calling authenticate are only looking for the claims.

Actually, I have never used this API in an authentication middleware (I don't even see why I'd use it), so my opinion is not that biased :smile: 

I just think that this unnatural (and anti?) pattern - that consists in...
* creating a "context" object yourself...
* flowing it to a method that may alter it... 
* and getting the result from the "context" object...

... shouldn't be used for a public API like the authentication manager. Ideally, it should be used nowhere.

A similar pattern is used by the security middleware for their notifications (or by MVC and its multiple binding/action contexts) and it's not always easy to determine what you're supposed to do exactly in these "methods" that return nothing (I don't blame you, I also use it massively in my own stuff). But with the pattern you're suggesting, it's far less intuitive as you initialize yourself the "context" object.

IMHO, keeping the existing `Authenticate` signature and adding a `GetPrincipal` (or `Identify`?) extension method would be easier and cleaner.

Just my 2 cents :smile:

**Comment by HaoK** [comment]
https://github.com/aspnet/Security/pull/283
