### ISSUE TITLE
[AuthZ] ClaimsTransformation can run multiple times

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#284]
Looks like today we sometimes run claims transformation more than once (i.e. once via Authenticate), and then again when it hits the ClaimsTransformationMiddleware (AutomaticAuthentication = true with Cookies scenario).

This doesn't seem ideal...

cc @blowdart

**Comment by blowdart** [comment]
Yea, kinda weird. Not sure where it should be ran, probably after all potential auth middlewares have ran.

**Comment by leastprivilege** [comment]
That's what you get for inventing passive authentication middleware ;)

**Comment by muratg** [comment]
@HaoK is there a big impact? Backlog OK?

**Comment by HaoK** [comment]
It's probably ok as backlog yes

**Comment by HaoK** [comment]
Suggestion was to remember if claims transformation has been run for a particular auth scheme and only do it once (i.e. HashSet("scheme")

**Comment by Eilon** [comment]
Moving to backlog.

**Comment by jcob-ross** [comment]
I'm bumping this issue as I just ran into it. That's it.

**Comment by Eilon** [comment]
Clearing milestone so we can revisit.

@jcob-ross can you provide more info on what your scenario is and how this is a problem? That will help us decide on the appropriate priority for the issue. Thanks!

**Comment by jcob-ross** [comment]
@Eilon Yes. Sorry for the late reply.
In my case I was using claims transformation middleware
and at the same time Jwt Bearer Middleware with custom OnTokenValidated event.

Log showed that claims transformation was hit right before and after token validation.

1st transformation - before identity was validated, then OnTokenValidated event
and then 2nd transformation - right after OnTokenValidated finished.

As a result I had some claims duplicated.
Thankfully google led me here.


(From source in my repo with this issue)
[link to TransformAsync](https://github.com/jcob-ross/dotnet-core-auth0/blob/e15224ffeeda67e22b29c077217ec67e1c500b8d/src/dotnet-core-auth0.Backend/Infrastructure/AuthClaimsTransformer.cs#L22)
[link to OnTokenValidated](https://github.com/jcob-ross/dotnet-core-auth0/blob/e15224ffeeda67e22b29c077217ec67e1c500b8d/src/dotnet-core-auth0.Backend/Infrastructure/Authentication/AuthenticationExtensions.cs#L65)
[link to Startup / UseClaimsTransformation](https://github.com/jcob-ross/dotnet-core-auth0/blob/e15224ffeeda67e22b29c077217ec67e1c500b8d/src/dotnet-core-auth0.Backend/Startup.cs#L94)

**Comment by HaoK** [comment]
@blowdart what is a rationale behavior we want for claims transformation.

Today we basically apply it blindly in a few situations:
1. Its applied to HttpContext.User by the middleware in the pipeline.
2. As part of the middleware hookup, it also intercepts any 'passive' Authenticate calls that occur, and invokes claims transformation in those cases as well. (this can happen multiple times, once per each call to Authenticate, and will happen again if its stuffed into HttpContext.User

Maybe we can do something like prevent our default claims transformer from applying itself to the same instance of a ClaimsPrincipal?  That might help in some cases...

**Comment by blowdart** [comment]
For me the main fix would be to make it injectable so folks can run off to their databases

I am not sure I care about it running twice, you'd hope that people would check if claims exist and replace them if so, however sure, if you can do it without adding a claim to the principal to track it, then running it once per identity would be better.

**Comment by HaoK** [comment]
There's only one situation where claims authentication is run more than once, that's when AutomaticAuthentication = true, the claims transformation middleware will also run on context.User.

@blowdart this makes things a bit tricky to fix since context.User is mutable, so unless we take a general stance where if any AutomaticAuthentication = true triggered claims transformation, we will skip the middleware transformation step.  Thoughts?

**Comment by HaoK** [comment]
Given that we don't have an obvious way to distinguish between the automatic authentication and a passive call to Authenticate, maybe we should just leave the behavior alone, and update the documentation to say that this may be called more than once (cookies, automatic = true by default)

**Comment by blowdart** [comment]
Ugh. That kinda sucks, what was wrong with recording which middleware triggered it already?

**Comment by HaoK** [comment]
That doesn't help, the first transformation is cookie applying it as part of its automatic authentication.  The second application is by the direct claims transformation middleware, the two aren't related in any way today, so we'd have to event logic to stop both of them running

**Comment by blowdart** [comment]
Darn it. OK caveats it is then.

**Comment by HaoK** [comment]
Actually maybe there's one other thing I can try, we can put something into the metadata that lives with the authentication ticket, that should be a safe place for a run once marker.

**Comment by HaoK** [comment]
Nope, doesn't work with the same issue, unless we put something visible into the ClaimsPrincipal, we have no way to mark the context.User as transformed unless we jam things into HttpContext.Items or something which doesn't seem worth it?...  caveats it is I guess

**Comment by HaoK** [comment]
I think this is fine since they always have an workaround to make claims transformation only run once by adding a marker claim themselves.

**Comment by HaoK** [comment]
@blowdart before I close this bug, do we want to update any docs to point this potential issue out?  It does affect how we setup cookies by default so its going to be fairly common (even if the impact is relatively small duplicate claims probably don't really matter)

**Comment by blowdart** [comment]
Yea, we do want to update the docs. In fact creating a doc on claims transformation might be a good idea :D

**Comment by HaoK** [comment]
Created https://github.com/aspnet/Docs/issues/2097, which we can use to track the doc updates
