### ISSUE TITLE
the `Identity.IsAuthenticated` is still `false` after `SignIn`  in Cookie Sample

### ISSUE THREAD

**Issue by RickyLin** [aspnet/Security#285]
Run the cookie example and check the `IsAuthenticated` of Identity, it is still `false`.
![screen shot 2015-06-09 at 5 06 02 pm](https://cloud.githubusercontent.com/assets/1393989/8054306/3a9af020-0eca-11e5-9a04-404c6b31064a.png)

**Comment by leastprivilege** [comment]
Because AuthenticationType is not set.

**Comment by RickyLin** [comment]
@leastprivilege yes, you are right. Thank you.
It would be great if cookie example could has a comment to clarify this.

**Comment by PinpointTownes** [comment]
@RickyLin it's definitely a bug in the sample, that doesn't set `authenticationType` when initializing the identity.

You can fix it easily: 

```
var user = new ClaimsPrincipal(new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, "bob") }, CookieAuthenticationDefaults.AuthenticationScheme));
```

Note that you can replace `CookieAuthenticationDefaults.AuthenticationScheme` with any other value if you want to.
