### ISSUE TITLE
The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator' threw an exception

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Security#288]
In `OnAuthorizationCodeReceived`, getting a context for Graph API this way ...
```c#
string userObjectId = notification.AuthenticationTicket.Principal.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;
ClientCredential credential = new ClientCredential(ClientId, AppKey);
AuthenticationContext authContext = new AuthenticationContext(Authority);
AuthenticationResult result = await authContext.AcquireTokenByAuthorizationCodeAsync(notification.Code, new Uri(BaseAddress), credential, "https://graph.windows.net");
```
works with dnx451 1.0.0-beta4 clr x86 but fails for dnxcore50 1.0.0-beta6-* coreclr x64 with
```
The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator' threw an exception.
```
Values for ClientId, AppKey, Authority, notification.Code, and BaseAddres should be ok ... they weren't changed between the two runtimes. Dependencies are ...
```c#
    "Microsoft.IdentityModel.Protocol.Extensions": "2.0.0-*",
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-*",
    "Microsoft.AspNet.Server.IIS": "1.0.0-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-*",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-*",
    "Microsoft.IdentityModel.Clients.ActiveDirectory": "3.1.203031538-alpha",
    "Microsoft.Framework.ConfigurationModel": "1.0.0-*",
    "Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-*",
    "Microsoft.AspNet.Identity": "3.0.0-*",
    "Microsoft.AspNet.Http": "1.0.0-*"
```

**Comment by PinpointTownes** [comment]
`Microsoft.IdentityModel.Clients.ActiveDirectory` is not part of ASP.NET 5 so I doubt you'll get an answer here. Instead, you should have a look at the repository managed by the Azure AD team: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/

That said, I'm pretty sure this issue is related to this other one: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/202 so maybe the Azure AD team is already working on a fix.

**Comment by GuardRex** [comment]
Thanks ... I'll take it up elsewhere then.
