### ISSUE TITLE
Customize AuthorizeAttribute

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Security#290]
I want to customize the AuthorizeAttribute a bit to add another property that is checked. I am using Identity. In MVC5 I would just inherit the `AuthorizeAttribute` and override `AuthorizeCore` returning `true`/`false` after checking the property. Example:

    public class AuthorizeUserAttribute : AuthorizeAttribute
    {
        public bool Foo { get; set; }

        protected override bool AuthorizeCore( HttpContextBase httpContext )
        {
            if( !base.AuthorizeCore( httpContext ) || !Foo )
            {
                return false;
            }

            return true;
        }
    }

Then

    [AuthorizeUser( Roles = "Admin", Foo = false )]
    public ActionResult MyAction()
    {
        return View( );
    }

Looking here, I only see the following for `AuthorizeAttribute`: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authorization/AuthorizeAttribute.cs

It appears to be doing nothing? I know I'm missing something. How do I inherit the `AuthorizeAttribute` and tweak the actual authorization check?

**Comment by HaoK** [comment]
Authorization is now policy based, so you would register a policy and tweak that to do the appropriate auth checks that you want...

https://github.com/aspnet/Security/blob/dev/test/Microsoft.AspNet.Authorization.Test/DefaultAuthorizationServiceTests.cs#L63

**Comment by kspearrin** [comment]
Got it. Thanks.
