### ISSUE TITLE
AuthorizeAttribute return 404 Not Found instead of 401 Unauthorized

### ISSUE THREAD

**Issue by YZahringer** [aspnet/Security#292]
Hello,

When anonymous request on action with AuthorizeAttribute, it's return 404 Not Found.

It should return 401 Unauthorized? How to change the current behavior to return 401?

Best regards,
Yann

**Comment by Eilon** [comment]
@YZahringer can you send some more info on this? One common case is that after authorization fails that the redirect then point to a page that doesn't exist, and that returns a 404. Can you check the `LoginPath` property of the cookie options?

**Comment by YZahringer** [comment]
Hello,

Thank you, LoginPath of cookie options contains "/Account/Login" by default. When set PathString.Empty, it returns 401 unauthorized.

Best regards,
Yann

**Comment by weitzhandler** [comment]
I'm unable to find `LoginPath` in ASP.NET Core 2.0.
Any ideas?

**Comment by weitzhandler** [comment]
@Tratcher that did the trick.

**Comment by TobiasBaumgarten** [comment]
I run in the same issue. I added the second options line and that solved the problem.
I think this is a better solution than the [Authorize("Bearer"] approach.
```c#
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
```

**Comment by Sigvaard** [comment]
but why `services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)` doesn't work like above? is this a bug?

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.

And yes @Sigvaard, your example should work the same as the one given by @TobiasBaumgarten.

**Comment by Sigvaard** [comment]
@Tratcher I've just realized `AddIdentity` calls `AddAuthentication`

https://github.com/aspnet/Identity/blob/329eed9e8d14243d0b36385bb1adc9fc85df0e41/src/Identity/IdentityServiceCollectionExtensions.cs#L38

And I call it before `AddAuthentication` so that was causing the problem.
