### ISSUE TITLE
Remove AuthenticationTokenProvider and AuthenticationToken*Context

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#294]
`IAuthenticationTokenProvider`, `AuthenticationTokenProvider`, `AuthenticationTokenCreateContext` and `AuthenticationTokenReceiveContext` are not used in ASP.NET 5 since @brentschmaltz removed `AccessTokenProvider` from the OAuth2 bearer middleware.

I personally stopped using this stuff in `AspNet.Security.OpenIdConnect.Server` when @brentschmaltz removed `DeserializeTicket` from `AuthenticationTokenReceiveContext`, as deserializing a token using the data protection system had become painful: https://github.com/aspnet/Security/pull/112/files#diff-cbc39b24fe94127489e33bc8b7b393e4L29 :smile: 

We should strongly consider removing this dead code.

@Eilon I'm your man if you want me to submit a PR :boy: 

/cc @brentschmaltz @Eilon @Tratcher

**Comment by Eilon** [comment]
If these types are truly unused, please go ahead and send us a PR. Thanks!

**Comment by HaoK** [comment]
I went ahead and deleted the 4 files rather than wait for a PR, since its a trivial change, and @PinpointTownes will be busy rebasing all of his prs anyways...

**Comment by HaoK** [comment]
6ae37717e819b047b10421e997e9704601d9fbd9

**Comment by PinpointTownes** [comment]
@HaoK ah ah, thanks :smile:
