### ISSUE TITLE
Support POST OpenID Connect authentication requests

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#295]
Supporting POST authentication/authorization requests is not mandatory for clients, but would be a nice addition to support heavy OIDC payloads. 

> Authorization Servers MUST support the use of the HTTP GET and POST methods defined in RFC 2616 [RFC2616] at the Authorization Endpoint. Clients MAY use the HTTP GET or POST methods to send the Authorization Request to the Authorization Server. If using the HTTP GET method, the request parameters are serialized using URI Query String Serialization, per Section 13.1. If using the HTTP POST method, the request parameters are serialized using Form Serialization, per Section 13.2.

http://openid.net/specs/openid-connect-core-1_0.html

Implementing this thing will require much carefulness to make sure we don't create deadlocks on critical async/sync paths (@Tratcher already knows everything about this issue, but you can take a look at this comment for more information: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.cs#L365-L377)

/cc @brentschmaltz @Eilon @Tratcher

**Comment by Tratcher** [comment]
Right now we use redirects to send the client over to the auth server (as a GET). What would we send to the client that would result in them doing a POST?

**Comment by PinpointTownes** [comment]
An auto-post HTML form pointing to the authorization endpoint, similar to the one an OIDC server returns for a **response_mode=form_post** response.

**Comment by Tratcher** [comment]
Ah, yes that's a challenge.  This might be easier with @HaoK's new prototypes where Challenge takes effect immediately rather than during OnResponseStarted, it could write the body directly. This would definitely have to be opt-in though.

**Comment by Eilon** [comment]
Marking as up-for-grabs in case anyone wants to do it.

**Comment by PinpointTownes** [comment]
@Eilon I'm rather busy these days, but I'm your man if nobody wants to do it :smile: 
That said, I'll probably need @brentschmaltz's help to add the appropriate tests (the logging testing is a bit cryptic for me).

@brentschmaltz out of curiosity, does AAD support POST authorization requests?

**Comment by Eilon** [comment]
@PinpointTownes I'm out of town all next week but maybe we could sync up the week after that to see how this could be arranged.

**Comment by PinpointTownes** [comment]
@Eilon I guess you've found nobody to implement it? :cry:

**Comment by Eilon** [comment]
@PinpointTownes can you email me (you already have my email) and we can figure this out with @Tratcher ?
