### ISSUE TITLE
[AuthZ] Middle ground between Requirement and Resource Handler

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#297]
I like the resource handler. well done.

I am not much of a fan of the plain requirements since it encourages you to source the authZ data solely from the claims (CanUpdateTableB and other "funny" stuff). 

Requirements would be much more useful if they would support DI - so we could inject our IPermissionRepository into it.

@blowdart  liked the idea and told me to open an issue.

**Comment by HaoK** [comment]
@leastprivilege Can you elaborate a bit more about what you wanted?  We aren't quite clear what you had in mind for the IPermissionRepository?

Can you outline the usage?

**Comment by leastprivilege** [comment]
So in a nutshell - it would be great if policies could go into DI. 

The current design injects the user's claims as the only data source - which encourages people to treat claims as permission/authorization data (which they are not). Being able to inject other dependencies like a repository over a permission system would improve that situation.

Right now you have to new up the policies explicitly (and thus pass in dependencies explicitly)

does that make sense?

**Comment by HaoK** [comment]
Are you just asking for something like this where you can plug in your own PolicyManager which maps names to requirements in way that doesn't necessarily involve the mechanical PolicyBuilder calls?

```
class AuthZPolicy {
 IEnumerable<IAuthZRequirement> Requirements { get; }
 IEnumerable<string> AuthenticationSchemes { get; }
}

interface IPolicyManager
 AuthZPolicy GetPolicy(string policyName)
```

The default AuthZ service would use the IPolicyManager to resolve policies instead of directly via the AuthZOptions.  Although, our default PolicyManager would continue to do this

**Comment by HaoK** [comment]
Blocked until @leastprivilege is back from holiday

**Comment by HaoK** [comment]
Working idea is enabling something like this which would activate the requirement using services from DI and pass in any additional arguments to the ctor

```
    AddAuthorization(options => options.AddPolicy("eighteen", policy => policy.AddRequirement<AgeRequirement>(18, new FileInfo("file.json"), ...)
```

**Comment by leastprivilege** [comment]
looks good!

**Comment by HaoK** [comment]
@leastprivilege After playing around with this some, I actually think this is no longer the right thing to do.  The intent of the current design is for the requirements to be basically data and simple.  The handlers are the consumers of the requirements and already live in DI and can depend on services.  So if you need a service to process a particular policy/requirements.  You can do that today already since you need to manually put your handler into DI.

For example:
```
    public class FooRequirement : IAuthorizationRequirement { }
    public class FooHandler : AuthorizationHandler<FooRequirement> {
       public FooHandler(DbContextAuth db) { }
       
       void Handle(AuthorizationContext context, FooRequirement requirement) {
          if (db.IsAuthorized(context.User)) context.Succeed(requirement);
       }
    }
```

cc @blowdart @divega @lodejard

**Comment by robianmcd** [comment]
@HaoK do you know of any working examples that demonstrate this? I'm trying to follow the example you gave in your last comment but my Handler never gets instantiated. All the examples I can find use the same class to inherit from `IAuthorizationRequirement` and `AuthorizationHandler` so I can't use DI

**Comment by Jargon64** [comment]
@robianmcd Did you find out how to do this? I'm in exactly the same situation. My handler is never instantiated and I can't find a working example anywhere. @HaoK Are you able to clarify on how to do this?

**Comment by robianmcd** [comment]
@Jargon64 no I never figured it out. I just gave up on using requirements :(

**Comment by Jargon64** [comment]
@robianmcd I've actually got a little further as I found this: https://docs.asp.net/en/latest/security/authorization/dependencyinjection.html

I can see that my handler is being instantiated now but the `Handle` method is never called. Beginning to think this is a bug so may open a ticket about it.

**Comment by robianmcd** [comment]
@Jargon64 I ran into the same problem. This solved it for me http://stackoverflow.com/a/37288885/373655 .

**Comment by Jargon64** [comment]
@robianmcd This looks interesting. I'm working on a different task at the moment but will definitely try this soon.

My concern with this solution is that I'm only using a custom authorization handler for a specific endpoint of my API. The rest is handled by the Identity system so I'm wondering if there's a way to have the workaround authenticated identity created for a user requesting a specific endpoint only?

At least I know why it's not calling the `Handle` method now and points me in the right direction. Thanks :)
