### ISSUE TITLE
[AuthN] Revisit base AuthHandler behavior

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#299]
Should SignIn/SignOut/HandleForbidden/Unauthorized all throw  NotSupportedException by default or be pure abstract instead of no-op?

Facebook/OAuth/Bearer will typically never support SignOut/Forbidden etc.

**Comment by Tratcher** [comment]
Provider | Authenticate | Unauthorized | Forbidden | SignOut | SignIn
---------- | ---------------- | ----------------- | ------------- | ---------- | -------- 
Cookie | x | x | x | x | x 
Bearer | x | x | x |  |  
Windows | x | x | x |  |  
ODIC | (callback only) | x |  | x |  
OAuth | (callback only) | x |  |  |

**Comment by HaoK** [comment]
This is mostly just cleanup tidying up the base implementation, not urgent, bumping to beta 7

**Comment by HaoK** [comment]
RemoteAuthHandler takes care of this now 409b50269a9d85618a31f84a3ffc2868abb3eeea
