### ISSUE TITLE
[AuthZ] Review authorize filter behavior again

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#300]
So with the new PR going in, there's no way for AuthorizeFilter to end up with a 403 unless it either asks for an scheme explicitly, or relies on an automatic one being populated (i.e. cookie).

Perhaps this ok, but we should review just to be certain @blowdart

**Comment by blowdart** [comment]
We came to the conclusion that the filter must demand an identity, and wasn't suitable for non-identity based decisions.

So if there's no identity then 401 is suitable.

If there is one (either automatic, or we've asked for, say, bearer), and it fails then it's 403. So this feels ok, but we should probably sit down and go through all the routes in and out.

**Comment by HaoK** [comment]
Yep that's how its implemented today.  The issue is for the a policy that doesn't demand any particular schemes, it relies on the HttpContext.User.  If there was no automatic cookie middleware, you never get a 403, you just get a 401 always...

**Comment by HaoK** [comment]
But if you think this behavior makes sense, I can just close this bug out...  and I guess add a test to verify the current wonkiness we have :)

**Comment by blowdart** [comment]
Which makes sense, as there's no identity on the thread to evaluate, so 401 go away and come back with an identity.

@PinpointTownes / @leastprivilege / @lodejard for opinions :)

**Comment by HaoK** [comment]
I think I'm just failing to articulate the wonkiness well if you think this makes sense :)

**Comment by HaoK** [comment]
Basically if policy.ActiveAuthenticationScheme is not set, we rely on there being an automatic authentication setup to ever get a 403.  Its basically impossible for it to ever return a 403 otherwise

**Comment by blowdart** [comment]
Yea, you seem hesitant here :) Shall we sit down in person tomorrow?

**Comment by HaoK** [comment]
The normal case with a cookie middleware in automatic mode works great...  As soon as you remove that, things get weird...

**Comment by blowdart** [comment]
Well don't do that then :)

More seriously, you think if someone wired up multiple auths, but none automatic a 401 would be hard to debug?

**Comment by HaoK** [comment]
Well, so the test that is weird is you have a policy that fails because a claim is missing, you don't get a 403 saying you don't have permission, you get a 401.  There's a user, with claims set, just not the one requested...and you get a 401

**Comment by blowdart** [comment]
Oh I didn't get that from the initial issue wording at all. Ok, that's definitely wrong IMO

**Comment by HaoK** [comment]
Again, this is only if there's no automatic authentication setup(like cookies), because that handler is the guy who will kick the 403 on the naked Challenge()...

**Comment by HaoK** [comment]
So there's an edge case where you fall into the pit of doom

**Comment by PinpointTownes** [comment]
Ahahahahaha, that's what you get for mixing authorization and authentication :smile:

**Comment by Eilon** [comment]
Moving to backlog as we don't think this is a major issue in the most common scenarios.

**Comment by HaoK** [comment]
Covered as part of https://github.com/aspnet/Security/issues/1061
