### ISSUE TITLE
[OAuth] Move GenerateCorrelationId and ValidateCorrelationId from base class

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#302]
GenerateCorrelationId and ValidateCorrelationId were put in the AuthenticationHandler base class back when Facebook, Google, etc directly derived from it. Then we created the OAuthAuthenticationHandler base class for all the providers to derive from. The OAuth base class is now the only caller of these methods.

Proposal: Move these methods from AuthenticationHandler to OAuthAuthenticationHandler.

**Comment by HaoK** [comment]
I can do this as part of my current PR if you want

**Comment by Tratcher** [comment]
No, it's a trap

**Comment by HaoK** [comment]
19d026268b80ad7a2299c4366fbc717e6b7bd9eb
