### ISSUE TITLE
Add support for HTTP Strict Transport Security

### ISSUE THREAD

**Issue by sblackler** [aspnet/Security#31]
*Continuing discussion from https://github.com/aspnet/Mvc/issues/744#issuecomment-49768062*

I would like to propose adding an HTTP Strict Transport Security (HSTS) attribute into the core of ASP.NET. According to [OWASP](https://www.owasp.org/index.php/HTTP_Strict_Transport_Security), HTTP Strict Transport Security (HSTS) protects users from a number of threats, in particular man-in-the-middle attacks by not only forcing encrypted sessions, but also stopping attackers who use invalid digital certificates.

Although developers can write middleware themselves, I believe a fully test implementation would be a benefit and prevent inconsistencies within developer code (for example, developers may overlook the ability to add the sub domains suffix).

Following the advice of the previously mentioned thread, I have created a NuGet package with a test implementation [here](https://www.nuget.org/packages/Owin.HSTS/), with the project site be located [here](https://github.com/sblackler/Owin.Hsts).

If you think that this feature would add value, I will happily submit the code via a PR.

cc/ @yishaigalatzer

**Comment by Eilon** [comment]
@blowdart

**Comment by blowdart** [comment]
Given multiple implementations, including nwebsec from @klings I don't feel providing a more limited middleware is that useful.

**Comment by sblackler** [comment]
@blowdart thanks for the info about nwebsec. Didn't realise that existed (don't know if it did a year a go when I started this). I think it would be good to raise awareness for stuff like this, maybe through a blog post or something? :)

**Comment by blowdart** [comment]
That would be a good idea. I'll find someone that blogs and poke them with a stick.

**Comment by StefanOssendorf** [comment]
Or https://github.com/StefanOssendorf/SecurityHeadersMiddleware/ ;-)
