### ISSUE TITLE
[OIDC] Investigate Music store failure with SignOut

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#313]
Something regressed with OIDC sign out, we are seeing a redirect to "/" instead of the session end from the music store test

**Comment by GuardRex** [comment]
Might be related: https://github.com/aspnet/Security/issues/356

At some point, there was a breaking change, right? ... The method went from `Context.Response.SignOut()` to `Context.Authentication.SignOutAsync`. I'm also getting a redirect to "/" ... but not so much "instead of session end" as instead of the normal AAD IDP logout redirect that used to occur with `.SignOut()`. The user remains signed in with the IDP now, but that's a regression, right? ... or I haven't implemented something properly.

**Comment by HaoK** [comment]
I will take a look

**Comment by GuardRex** [comment]
@HaoK Cool - Thanks.

The behavior can be seen in my test apps:

dnx451 version that uses the old `SignOut()` method: https://www.console.guardrex.com:8003/
Use login: bjones@guardrex.onmicrosoft.com
Password: passWord1!

You'll notice the redirect to AAD on `SignOut()` that then redirects back to the app. On the next Log In, the redirect to ADD **does** require fresh credentials.

dnxcore50 version that uses the new `SignOutAsync()` method: https://www.console.guardrex.com:8000/
Use login: jsmith@guardrex.onmicrosoft.com
Password: passWord1!

You'll notice that `SignOutAsync()` clears the cookie/claims but there is no redirect to AAD. When you sign in again, the redirect to AAD only redirects back to the app (no credentials required) ... the user was never signed out at AAD.

Let me know if you want a repo of the app.

**Comment by HaoK** [comment]
Yeah let me see the repo for the controller action that calls sign out.

**Comment by GuardRex** [comment]
I can put the full app up, but if you just wanted to see the controller, it just goes like this. I think I copied the format from the ADAL for .NET 5 sample project:
```c#
// GET: /Account/LogOut
[HttpGet]
public IActionResult LogOut(){
    if (Context.User.Identity.IsAuthenticated) {
        Context.Authentication.SignOutAsync(OpenIdConnectAuthenticationDefaults.AuthenticationScheme);
        Context.Authentication.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
    }
    return RedirectToAction("Index", "Home");
}
```
I also tried a version that went like this, but I had the same outcome:
```c#
// GET: /Account/LogOut
[HttpGet]
public async Task<ActionResult> LogOut(){
    if (Context.User.Identity.IsAuthenticated) {
        await Context.Authentication.SignOutAsync(OpenIdConnectAuthenticationDefaults.AuthenticationScheme);
        await Context.Authentication.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
    }
    return RedirectToAction("Index", "Home");
}
```

**Comment by HaoK** [comment]
Yeah so try retuning empty result instead. That is the issue I think. You are overwriting the sign out



On Jul 11, 2015, at 4:00 PM, Luke Latham <notifications@github.com<mailto:notifications@github.com>> wrote:


I can put the full app up, but if you just wanted to see the controller, it just goes like this. I think I copied the format from the ADAL for .NET 5 sample project:

// GET: /Account/LogOut
[HttpGet]
public IActionResult LogOut(){
    if (Context.User.Identity.IsAuthenticated) {
        Context.Authentication.SignOutAsync(OpenIdConnectAuthenticationDefaults.AuthenticationScheme);
        Context.Authentication.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
    }
    return RedirectToAction("Index", "Home");
}

I also tried a version that went like this, but I had the same outcome:

// GET: /Account/LogOut
[HttpGet]
public async Task<ActionResult> LogOut(){
    if (Context.User.Identity.IsAuthenticated) {
        await Context.Authentication.SignOutAsync(OpenIdConnectAuthenticationDefaults.AuthenticationScheme);
        await Context.Authentication.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
    }
    return RedirectToAction("Index", "Home");
}

-

**Comment by HaoK** [comment]
The new behavior is sign out redirects immediately rather than later so before the sign out would win. Now the redirect to home wins which is why you need to return empty result.

**Comment by GuardRex** [comment]
Ok ... I'll give that a shot ... testing now ... brb

**Comment by GuardRex** [comment]
Got IT! Thanks ... that did the trick. I'll put the answer over on the issue I opened at https://github.com/aspnet/Security/issues/356 and close that out.

Have a great weekend! ... and I'll raise a Beck's to you tonight! :beer:

**Comment by GuardRex** [comment]
@PinpointTownes recommends in [#356 (comment)](https://github.com/aspnet/Security/issues/356#issuecomment-120887762) to go with an `await` version, like this:
```c#
// GET: /Account/LogOut
[HttpGet]
public async Task LogOut(){
    await Context.Authentication.SignOutAsync(OpenIdConnectAuthenticationDefaults.AuthenticationScheme);
    await Context.Authentication.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
}
```

**Comment by HaoK** [comment]
Moving to beta 7 as this is just a test update

**Comment by HaoK** [comment]
Opened issue in music store to track this, there doesn't appear to be any regression on the functional side.

https://github.com/aspnet/MusicStore/issues/511
