### ISSUE TITLE
AuthenticationOptions.AuthenticationScheme and SigninScheme

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#314]
What is the correct way to think about these two properties?
Why would I use one over the other?

**Comment by Tratcher** [comment]
AuthenticationScheme is the identifier of the current auth middleware. SigninScheme matches the AuthenticationScheme of a down-stream middleware. When the current middleware produces an identity, it calls SignInAsync(claimsPrincipal, SignInScheme).

In all current examples SignInScheme is set to match the AuthenticationScheme of the cookie auth middleware.

**Comment by brentschmaltz** [comment]
That describes the mechanics, thanks.
Why is the design as such? Is there a different middleware that will preform the signin?

**Comment by Tratcher** [comment]
Other middleware could implement signin, but so far only the cookie auth middleware has.

**Comment by brentschmaltz** [comment]
So the act of creating an authenticationticket is only a hint that the ticket should be used to be signed in.
What is the criteria / flow required for a successful signin (User.Authenticate == true) once an AuthenticationHandler has produced an AuthenticationTicket?

**Comment by Tratcher** [comment]
It's up to the middleware to decide if it should call SignIn. Most look like this: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationHandler.cs#L605

**Comment by brentschmaltz** [comment]
Ok, so it's possible for an AuthenticationMiddleware to create a ticket, but not signin. What happens with the ticket?

**Comment by Tratcher** [comment]
Bearer doesn't call SignIn. The resulting ticket is available from context.Authentication.AuthenticateAsync().
