### ISSUE TITLE
OIDC expiration time when adding nonce may not accuratly reflect the validity of the nonce

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#318]
The following code seems to assume the message.Nonce should be equal to NonceLifetime.
This may not always be true.
1. The nonce may not have a prefix of a time
2. The NonceLifetime while usually is the same as the nonce prefix, is not guaranteed.

await Options.NonceCache.SetAsync(message.Nonce, new byte[0], new DistributedCacheEntryOptions
 {
     AbsoluteExpirationRelativeToNow = Options.ProtocolValidator.NonceLifetime
  });

**Comment by PinpointTownes** [comment]
/cc @Tratcher, as he suggested to use ``Options.ProtocolValidator.NonceLifetime`: https://github.com/aspnet/Security/pull/293#discussion_r33092864

That said, I'm not sure to understand why a nonce should live longer than its expiration date.

**Comment by brentschmaltz** [comment]
ProtocolValidator.NonceLifetime is not guaranteed to == epoch time on the nonce.
Also, the nonce need not have a prefix that is a Epoch time.

That said I grappled with this concept over ReplayTokenCache and came to the conclusion that unless a token had an expiration there was no way we could guarantee detecting replays unless we were able to hang onto all tokens.

**Comment by Tratcher** [comment]
Well we clearly can't hold onto all the tokens. Is NonceLifetime a reasonable default timeout even for nonce's that don't have an embedded expiration?

**Comment by brentschmaltz** [comment]
I debated this for long periods with many people and came to the conclusion that if a user want to have a 'replay' type cache, the items in the cache need to have an expiration associated with them.
This led to the runtime behavior with .Net: If you specify "Detect Token Replay" and a token arrives without a expiration time, .Net faults.

Otherwise, you are making a false promise.

**Comment by Eilon** [comment]
The current plan is to use a consistent expiration time for everything, which is 15min.

See also: https://github.com/aspnet/Security/issues/390
