### ISSUE TITLE
INonceCache has been replace but the file still exists.

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#319]
The file should be removed.

**Comment by PinpointTownes** [comment]
@brentschmaltz erf, that's my fault ; nice catch! :smile: 

@HaoK do you want me to send a PR to fix that or is this something you can remove in a commit?

**Comment by HaoK** [comment]
Don't worry about it, I can nuke it in one of my check ins, not a big deal

**Comment by PinpointTownes** [comment]
@HaoK thanks! 

https://github.com/aspnet/Security/commit/6e67b1c9b1354a565afe55a52ddb99bffdd99b0d
