### ISSUE TITLE
Nonce caching should not require two properties on OpenIdConnectAuthenticationOptions: CacheNonces and NonceCache

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#321]
By default NonceCache is null.
It seems reasonable to me if the user set it that should be an indication to use it.

**Comment by Tratcher** [comment]
The CacheNonces bool is also used in the constructor to request the cache from DI:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectAuthenticationMiddleware.cs#L132

**Comment by brentschmaltz** [comment]
This is different than the pattern for IDataFormatter.  Could we have a default NonceCache that uses cookies, have users override as they do with the formatter.

**Comment by Tratcher** [comment]
IDataFormatter? Do you mean ISecureDataFormat?

**Comment by brentschmaltz** [comment]
Yes, ISecureDataFormat.

**Comment by Eilon** [comment]
This is behaving as designed.
