### ISSUE TITLE
CookieMiddleware serialization of the ClaimsPrincipal is lossy.

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#324]
The AuthenticationTicket serialization is lossy. Not all of the ClaimsIdentities and Claims properties are serialized.

**Comment by PinpointTownes** [comment]
> The AuthenticationTicket serialization is lossy. Not all of the ClaimsIdentities and Claims properties are serialized.

This issue is not specific to cookies and affects everything using `TicketSerializer`.
+1 for `Claim.Properties`, I had to create my own serializer to fix that.

Anyway, these issues will likely disappear when migrating to your new `WriteTo` gem: https://github.com/aspnet/Security/issues/158
That said, I guess this change will have to wait until .NET 4.6 is supported by dnx.

**Comment by brentschmaltz** [comment]
A possible solution is for the runtime could flow the AuthenticationTicket in it's entirety,  rather than chop it up and flow parts then rehydrate them. The claimstransformation point could take action on all of the tickets that are available.

**Comment by leastprivilege** [comment]
Why would you want to serialize the properties? The claims classes are already way to complicated and should be really onyl name/value pairs

**Comment by PinpointTownes** [comment]
I could find 10 examples to legitimate serializing `Claim.Properties` but I can't find a reason not to do that.

**Comment by leastprivilege** [comment]
That makes it clearer.

**Comment by PinpointTownes** [comment]
You want a concrete example? Okay, here's one: In `AspNet.Security.OpenIdConnect.Server`, I use `Claim.Properties` to store a marker indicating whether a claim should be included in the identity token, in the access token or in both.

**Comment by PinpointTownes** [comment]
And BTW, the same remarks applies to `ClaimsIdentity.Actor`, which is currently not serialized.

**Comment by leastprivilege** [comment]
Fair enough - If someone (sensible) would re-create the Claims / CI / CP classes today most of these things would probably not exist. They were included back then to accommodate some of the WS*/SAML features they needed. 

I am not saying the none of them are useful - but the classes are bloated and I am not sure that full fidelity in round-tripping them makes sense. 

Same goes for custom principals - but I guess that is a separate discussion.

**Comment by PinpointTownes** [comment]
> Fair enough - If someone (sensible) would re-create the Claims / CI / CP classes today most of these things would probably not exist.

Are you saying that the guys who introduced claims support in .NET were/are not sensible? :smile: 
I don't always agree with @brentschmaltz but I'm convinced that this claims stuff is the right mix between easiness, completeness and extensibility. There are definitely things that don't make sense as claims and are good candidates for `Claim.Properties`.

Even the `ClaimTypes` class you hate (and I guess it's an euphemism :smile:) exists for a reason: decoupling your app from the protocols/tokens formats you may use to authenticate your users. Of course, we could still argue these WS-*-styled URLs were not really appropriate, but heh, are JWT's short names really better? :smile: 

> Same goes for custom principals - but I guess that is a separate discussion.

@brentschmaltz opened a ticket for custom principals: https://github.com/aspnet/Security/issues/323

**Comment by leastprivilege** [comment]
I am not opposed to serializing claims properties - I was mainly curious why you want to do it. I would be opposed to guarantee full fidelity round tripping of the CLR types. As I said they are already bloated.

btw - I don't hate the ClaimTypes class - just the fact the libraries think everything should be mapped to it by default. ;)

**Comment by brentschmaltz** [comment]
@leastprivilege @PinpointTownes There is some truth to the statement: "They were included back then to accommodate some of the WS*/SAML features they needed." At that time all of this was new. Brock Allen and others convinced us to remove mapping to long ClaimTypes in Wilson (S.IM.Tokens.Jwt, renamed to M.IM.Tokens.Jwt) by default.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/95

Most of the bloat was a result of storing CLR typing in the serialization. I tried to address with the new API ClaimsPrincpal.WriteTo. Which, if a runtime exposes a factory, will allow for the users to hydrate the exact CP they created. I haven't opened that issue yet as I haven't thought it through.

As @PinpointTownes points out, some items properties are missing in the serialization. We should close on what the serialization contract. What I am arguing is that the serialization of the Identity was never really thought through since it's inception in Katana and needs to be revisited. 

@PinpointTownes If we agreed all the time, we would probably both be wrong all the time :-)

**Comment by leastprivilege** [comment]
As per our other thread (custom principals) - I advise against doing that. Serializing a DTO that represents a claims principal is fine. serializing a custom principal implementation has not benefit IMO and adds unneeded complexity.

**Comment by PinpointTownes** [comment]
> @PinpointTownes If we agreed all the time, we would probably both be wrong all the time :-)

@brentschmaltz ahah, true :smile: 

> As per our other thread (custom principals) - I advise against doing that. Serializing a DTO that represents a claims principal is fine. serializing a custom principal implementation has not benefit IMO and adds unneeded complexity.

@leastprivilege I'm not sure this ticket is about serializing custom principals.

@brentschmaltz except `ClaimsIdentity.Actor` and `Claim.Properties`, do you see any other property that is not currently serialized?

**Comment by davidfowl** [comment]
> I would be opposed to guarantee full fidelity round tripping of the CLR types

@leastprivilege +1 to that.

**Comment by PinpointTownes** [comment]
There's a difference between guaranteeing `full fidelity round tripping of the CLR types` and `loosing critical properties during serialization/deserialization`, which is currently the case.

**Comment by brentschmaltz** [comment]
Round tripping of CLR types is possible but not necessary by default. Will require custom coding.
Full fidelity of the contents of a ClaimsIdentity should be the default.

**Comment by Eilon** [comment]
The more reliable serializers for this are not available until future versions of .NET 4.6, so we cannot consume these from ASP.NET 5. When those become available, we can reconsider this.

**Comment by PinpointTownes** [comment]
@Eilon luckily, we don't need to wait for >.NET 4.6 since we can easily extend the existing serializer to support both `ClaimsIdentity.Properties` and `ClaimsIdentity.Actor` (AspNet.Security.OpenIdConnect.Server has one that replaces the default one).

**Comment by PinpointTownes** [comment]
@Eilon is this ticket open to external contributions? I'm tired of having to embed by own serializer because the official one lacks `ClaimsIdentity.Actor` and `Claim.Properties` support.

**Comment by Eilon** [comment]
@Tratcher thoughts on this? I have no particular problem but if we think it's not a good fit for v1 we should wait.

**Comment by Tratcher** [comment]
@PinpointTownes can you share a link to your custom serializer?

**Comment by PinpointTownes** [comment]
Minor a few changes needed to make the serializer work with `ClaimsIdentity.Actor`/`Claim.Properties`, it's the same as the one used in aspnet/Security, but it doesn't include the recent changes (since BootstrapContext support was not needed):

```csharp
// Remove when the built-in ticket serializer supports Claim.Properties.
// See https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/71
private sealed class EnhancedTicketDataFormat : SecureDataFormat<AuthenticationTicket> {
    private static readonly EnhancedTicketSerializer Serializer = new EnhancedTicketSerializer();

    public EnhancedTicketDataFormat(IDataProtector protector)
        : base(Serializer, protector, TextEncodings.Base64Url) {
    }

    private sealed class EnhancedTicketSerializer : IDataSerializer<AuthenticationTicket> {
        private const int FormatVersion = 3;

        public byte[] Serialize(AuthenticationTicket model) {
            using (var memory = new MemoryStream())
            using (var writer = new BinaryWriter(memory)) {
                writer.Write(FormatVersion);

                writer.Write(model.AuthenticationScheme);
                writer.Write(model.Principal.Identities.Count());

                foreach (var identity in model.Principal.Identities) {
                    WriteIdentity(writer, identity);
                }

                PropertiesSerializer.Write(writer, model.Properties);

                return memory.ToArray();
            }
        }

        public AuthenticationTicket Deserialize(byte[] data) {
            using (var memory = new MemoryStream(data))
            using (var reader = new BinaryReader(memory)) {
                if (reader.ReadInt32() != FormatVersion) {
                    return null;
                }

                var scheme = reader.ReadString();

                var identities = new ClaimsIdentity[reader.ReadInt32()];
                for (int index = 0; index != identities.Length; ++index) {
                    identities[index] = ReadIdentity(reader);
                }
            
                var properties = PropertiesSerializer.Read(reader);

                return new AuthenticationTicket(new ClaimsPrincipal(identities), properties, scheme);
            }
        }

        private static void WriteIdentity(BinaryWriter writer, ClaimsIdentity identity) {
            var authenticationType = identity.AuthenticationType ?? string.Empty;

            writer.Write(authenticationType);
            WriteWithDefault(writer, identity.NameClaimType, DefaultValues.NameClaimType);
            WriteWithDefault(writer, identity.RoleClaimType, DefaultValues.RoleClaimType);
            writer.Write(identity.Claims.Count());

            foreach (var claim in identity.Claims) {
                WriteWithDefault(writer, claim.Type, identity.NameClaimType);
                writer.Write(claim.Value);
                WriteWithDefault(writer, claim.ValueType, DefaultValues.StringValueType);
                WriteWithDefault(writer, claim.Issuer, DefaultValues.LocalAuthority);
                WriteWithDefault(writer, claim.OriginalIssuer, claim.Issuer);

                writer.Write(claim.Properties.Count);

                foreach (var property in claim.Properties) {
                    writer.Write(property.Key);
                    writer.Write(property.Value);
                }
            }

            if (identity.Actor != null) {
                writer.Write(true);
                WriteIdentity(writer, identity.Actor);
            }

            else {
                writer.Write(false);
            }
        }

        private static ClaimsIdentity ReadIdentity(BinaryReader reader) {
            var authenticationType = reader.ReadString();
            var nameClaimType = ReadWithDefault(reader, DefaultValues.NameClaimType);
            var roleClaimType = ReadWithDefault(reader, DefaultValues.RoleClaimType);
            int count = reader.ReadInt32();
            var claims = new Claim[count];

            for (int index = 0; index != count; ++index) {
                string type = ReadWithDefault(reader, nameClaimType);
                string value = reader.ReadString();
                string valueType = ReadWithDefault(reader, DefaultValues.StringValueType);
                string issuer = ReadWithDefault(reader, DefaultValues.LocalAuthority);
                string originalIssuer = ReadWithDefault(reader, issuer);

                claims[index] = new Claim(type, value, valueType, issuer, originalIssuer);

                var x = reader.ReadInt32();

                for (int j = 0; j != x; ++j) {
                    claims[index].Properties.Add(key: reader.ReadString(), value: reader.ReadString());
                }
            }

            var identity = new ClaimsIdentity(claims, authenticationType, nameClaimType, roleClaimType);

            if (reader.ReadBoolean()) {
                identity.Actor = ReadIdentity(reader);
            }

            return identity;
        }

        private static void WriteWithDefault(BinaryWriter writer, string value, string defaultValue) {
            if (string.Equals(value, defaultValue, StringComparison.Ordinal)) {
                writer.Write(DefaultValues.DefaultStringPlaceholder);
            }
            else {
                writer.Write(value);
            }
        }

        private static string ReadWithDefault(BinaryReader reader, string defaultValue) {
            string value = reader.ReadString();
            if (string.Equals(value, DefaultValues.DefaultStringPlaceholder, StringComparison.Ordinal)) {
                return defaultValue;
            }
            return value;
        }

        private static class DefaultValues {
            public const string DefaultStringPlaceholder = "\0";
            public const string NameClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name";
            public const string RoleClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role";
            public const string LocalAuthority = "LOCAL AUTHORITY";
            public const string StringValueType = "http://www.w3.org/2001/XMLSchema#string";
        }
    }
}
```

**Comment by Tratcher** [comment]
Seems reasonable, go ahead and send a PR.
