### ISSUE TITLE
[Cookies] Reject/throw null principal authentication tickets

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#325]
Also make serializer throw if principal is null instead

**Comment by brentschmaltz** [comment]
Can you be more specific on what you are proposing?
Thanks.

**Comment by HaoK** [comment]
Rather than the serializer handling nulls as it does today, it will throw instead, and cookie middleware will reject/not support storing tickets with no principal.

**Comment by HaoK** [comment]
ab4ba794e546074a573fbf76d9150ffcf9752c89
