### ISSUE TITLE
Add additional Notification: AuthenticationComplete

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#327]
This would be fired just before returning from AuthenticateAsync and would be symmetric to OnMessageReceived. It would take the AuthenticationTicket that was produced.

**Comment by Tratcher** [comment]
Something like this?
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Twitter/TwitterAuthenticationHandler.cs#L172

**Comment by brentschmaltz** [comment]
@Tratcher It is not clear what you are suggesting.
Line 172 is: var model = await AuthenticateAsync();
