### ISSUE TITLE
Why does AuthenticationHandler.ChallengeAsync call AuthenticateAsync()?

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#328]
I noticed that if I make the code: 
await context.Authentication.ChallengeAsync(OpenIdConnectAuthenticationDefaults.AuthenticationScheme, new AuthenticationProperties { RedirectUri = "/" })
AuthenticationHandler.AuthenticateAsync() is called if context.Behavior ==ChallengeBehavior.Automatic.
If a ticket is returned, then the runtime calls  HandleForbiddenAsync().

How should I be thinking about this? Can you help me understand what HandleForbiddenAsync()  is for?

**Comment by HaoK** [comment]
See https://github.com/aspnet/Security/issues/273

**Comment by brentschmaltz** [comment]
I looked at 273 and still do not understand why AuthenticateAsync needs to be called.
Authenticate looks for a message to process.
What am I missing?

**Comment by PinpointTownes** [comment]
@brentschmaltz https://github.com/aspnet/Security/issues/336#issuecomment-119336570
