### ISSUE TITLE
CookieMiddleware serialization of AuthenticationTicket should be Version neutral

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#330]
The current design for deserializing an AuthenticationTicket is fixed for a particular version.
This will impact users when updating servers.

Servers updates are sometimes performed in stages resulting in heterogeneous environments. Some servers will now start to fail to handle the tickets.

Users that have a valid application session will experience some type of failure (depends on the app). For VisualStudio online, this was a ship blocker and we had to produce a solution.
Different solutions exist, depending on if the OM was designed originally with version neutrally in mind or not.

ClaimsPrincipal.WriteTo from .Net 4.6 is in the first category.
WindowsPrincipal.GetObjectData between .Net 4.0 <-> 4.5 is in the second category.

**Comment by Eilon** [comment]
The approach we recommend for this is to enable compatibility by replacing the serializers in either the "old" app to support the "new" format, or to replace them in the "new" app to support the "old" format.
