### ISSUE TITLE
Integrated logs for aspnet and wilson

### ISSUE THREAD

**Issue by tushargupta51** [aspnet/Security#331]
`Microsoft.Aspnet.Authentication.OpenIdConnect` uses `ILogger` to log events whereas Wilson uses `EventSource` based logging. Currently, there is no easy way for a user using OIDC to get an integrated log from both aspnet and wilson (OIDC takes a hard dependency on Wilson). They have to configure both the loggers separately and it is very difficult to debug using the separated logs.

**Comment by leastprivilege** [comment]
Oh really - why is that? Must be an artifact from the Katana version.

**Comment by PinpointTownes** [comment]
@leastprivilege `ILogger` is part of the new logging block and has nothing to do with Katana: https://github.com/aspnet/Logging :smile:

**Comment by leastprivilege** [comment]
Oh really? ;) So who is using EventSource then - and why?

**Comment by PinpointTownes** [comment]
`EventSource` is used by Wilson for its internal logging.

Why? I dunno: https://github.com/aspnet/Security/pull/258#discussion_r30331835

**Comment by brentschmaltz** [comment]
Because ILogger is not available for some of the customers of Wilson.

**Comment by PinpointTownes** [comment]
Then it might be a good idea to list those targets and add them to aspnet/Logger.

/cc @Eilon

**Comment by tushargupta51** [comment]
Aligning the logging experience of Wilson with ADAL is one reason. ADAL uses EventSource.

**Comment by Eilon** [comment]
Both ASP.NET 5 components and Wilson can (or will be able to) write to EventSource, and that is the best way to get unified logs.
