### ISSUE TITLE
Authority in OAuthBearer-Middleware

### ISSUE THREAD

**Issue by manfredsteyer** [aspnet/Security#332]
Hi,

I really like the fact, that the OAuthBearer-Middleware can read the OpenId-Connect-Metadata following the Link in the Property Authority.

Are there plans to port this behavior back to 4.x ?

Wishes,
Manfred

**Comment by PinpointTownes** [comment]
> Are there plans to port this behavior back to 4.x ?

You mean Katana 3? :laughing: 
It's really unlikely to happen, as it's not developed anymore (http://katanaproject.codeplex.com/SourceControl/list/changesets).

You should maybe have a look at the extension package developed by @leastprivilege: it's specifically designed for IdSrv but I don't see why it wouldn't work with another OpenID Connect server: 

https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation

**Comment by Eilon** [comment]
There are no current plans to port this to Katana 3.x.
