### ISSUE TITLE
Would like a description of "AuthN and AuthZ API changes (Async, Challenge)"

### ISSUE THREAD

**Issue by aggieben** [aspnet/Security#333]
I have authored an OAuth1 middleware, and when I pulled a recent package everything was broken.  I can kind of see what's happening in the code (3a8ea672eae590785a78d74777abb76bb9664130), but it would be helpful if someone could go through the design choices involved as well as their motivations.  "Async and challenge" kinda-sorta tell me where to look, but there was already support for async in the parts that seemed to need it the most, and I have no idea why challenge would have needed changing.

I don't need a book, just a short clue-in ;-)

**Comment by HaoK** [comment]
Sure, I'll give short brief overview, feel free to ask for more details:

1. Why Async?  Prior to making all of auth Async, there was a separate callstack for both Sync/Async, with parallel methods and virtual methods in the auth handlers.  This was both cumbersome and error prone so we decided to just eliminate the sync path for simplicity.

2. ChallengeBehavior: this was basically where we landed as a result of the 401/403 thrashing https://github.com/aspnet/Security/issues/273: which explains the motivations/changes a bit

3. As a result of all these changes, we made auth handler more opinionated with less virtuals and only a few extensibility endpoints as its now intended do more stuff i.e. Challenge and auth handlers should only need to override the appropriate HandleXyz when they actually need to change the behavior.
