### ISSUE TITLE
You can't set querystrings on Login/AccessDenied/LogoutPaths

### ISSUE THREAD

**Issue by blowdart** [aspnet/Security#334]
I'd have expected

    options.LoginPath = new PathString("/Home/PickIdentity/").Add(new QueryString("?unauthorized=true"));
    options.AccessDeniedPath = new PathString("/Home/PickIdentity/").Add(new QueryString("?forbidden=true"));

to work; but you end up with a URL like

http://localhost:12612/Home/PickIdentity/%3Funauthorized%3Dtrue?ReturnUrl=%2FProtected%2FAdministratorsOnly

You can see the QueryString is getting treated as a PathString and a new querystring created for the ReturnUrl.

**Comment by PinpointTownes** [comment]
That's because `new PathString("/Home/PickIdentity/").Add(new QueryString("?unauthorized=true"))` actually returns a `string`, which is implicitly converted back to a new `PathString` when you assign it to `LoginPath`:

And because `/Home/PickIdentity/?forbidden=true` is considered as a path string, the whole string is encoded by `ToUriComponent` when you use `PathString.Value`... and boom, fail.

It's definitely not an aspnet/Security issue. You should probably open a ticket on aspnet/HttpAbstractions (where `PathString` and `QueryString` live) if you really want to fix it.

**Comment by HaoK** [comment]
Which is a nice way of saying, user error: @blowdart

**Comment by PinpointTownes** [comment]
Yeah, @blowdart is a noob! :smile:

**Comment by blowdart** [comment]
I'll bet I won't be the only person who wants to do this, noob or not. So it should be addressed somehow :p

**Comment by PinpointTownes** [comment]
Well, these primitives are not really different compared to their Katana equivalent... and I never heard someone trying such a crazy thing, so... :smile:

**Comment by brentschmaltz** [comment]
@PinpointTownes I am with @blowdart on this one. He was confused, I was also confused.
Not sure why .Add returns a string and not a PathString.

**Comment by PinpointTownes** [comment]
@brentschmaltz `PathString.Add(QueryString)` cannot return a `PathString` simply because you can't have a query string in a path string (it's named `PathString`, not `PathAndQueryString` :smile:)

**Comment by HaoK** [comment]
Pinpoint wins

**Comment by blowdart** [comment]
Or you stop using a limited path string. Its an unwelcome surprise for users.
________________________________

**Comment by HaoK** [comment]
And seriously no matter how confusing this may or may not be. This isn't a security issue. Feel free to file an issue in http

**Comment by PinpointTownes** [comment]
> Pinpoint wins

Semantic wins :smile: 

@blowdart @brentschmaltz if you really find this behavior confusing, the best option would probably be to remove the implicit `string` operators introduced in April: https://github.com/aspnet/HttpAbstractions/pull/283/files#diff-0f73e24b2a5cfe9e8842fd60242fe26bR240

This way, `options.LoginPath = new PathString("/Home/PickIdentity/").Add(new QueryString("?unauthorized=true"));` couldn't be considered by the compiler as a valid code.

**Comment by blowdart** [comment]
If it's a problem with path string then stop using PathString and simply use string.

**Comment by PinpointTownes** [comment]
Using a string would have different implications (should we tolerate absolute URIs? Even for a different domain? How should we treat duplicate query string parameters? How to combine that with `PathBase`?)

**Comment by blowdart** [comment]
Oh indeed, but all redirects should be relative etc. You wouldn't fix query strings either, you'd append to, and so on.

**Comment by Tratcher** [comment]
FYI: You can customize the redirects today using the redirect notification.

I also have not heard any requests yet for query strings in these properties.

**Comment by blowdart** [comment]
Why would I want to hook into something outside of the security settings to do this?

And consider this a request for query strings.

**Comment by brentschmaltz** [comment]
Just paraphrasing what @blowdart is seems to be saying, if it doesn't seem natural OR requires some tweak (hack) in an un-related area: there is room for improvement (there I said it nicely).

**Comment by Eilon** [comment]
Discussed in triage and this is by-design. We recommend using URL path segments to indicate this type of information.
