### ISSUE TITLE
AuthenticationHandler.BaseInitializeAsync calls ShouldHandleScheme with string.Empty

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#338]
The comment says: // Automatic authentication is the empty scheme
This does not match the logic in ShouldHandleScheme

```c#
 return string.Equals(BaseOptions.AuthenticationScheme, authenticationScheme, StringComparison.Ordinal) ||
                (BaseOptions.AutomaticAuthentication && string.IsNullOrWhiteSpace(authenticationScheme));
```

1. What is the purpose of BaseOptions.AutomaticAuthentication if the comment is true?
2. The comment says string.IsEmpty, but null, and any whitespace will be true.

**Comment by HaoK** [comment]
Fixed in https://github.com/aspnet/Security/pull/343
