### ISSUE TITLE
Create an Authorization.Abstractions package for frameworks to reference

### ISSUE THREAD

**Issue by rynowak** [aspnet/Security#339]
API review feedback. MVC is taking a reference on Authorization+Authentication just to use the attribute to call into the authorization service.

Basically the hope is that the code in the MVC `AuthorizeFilter` would only need this dependency.

We want to create a slim package with minimal surface area.
- AuthorizeAttribute
- IAuthorizationService

**Comment by HaoK** [comment]
Splitting securityhelper into shared sources so MVC can remove dependency on Auth

https://github.com/aspnet/Mvc/pull/2792

**Comment by HaoK** [comment]
@rynowak @davidfowl AuthZ doesn't bring in much so with AuthN dependency broken is this sufficient?

**Comment by rynowak** [comment]
The extra reference that we're getting here is `Microsoft.AspNet.Http.Features`

**Comment by Tratcher** [comment]
@rynowak It's expected that middleware reference Microsoft.AspNet.Http.Features. Microsoft.AspNet.Http.Abstractions depends on Features anyways.
