### ISSUE TITLE
Need to rename the protected AuthenticationTicket AuthenticateAsync to not clash

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#341]
public async Task AuthenticateAsync(AuthenticateContext context)
protected abstract Task<AuthenticationTicket> AuthenticateAsync();

Just a little confusing...

**Comment by HaoK** [comment]
Leaning towards CreateTicketAsync (which happens to be the same name @PinpointTownes used for the OAuth stuff, which is good)

**Comment by PinpointTownes** [comment]
> which happens to be the same name @PinpointTownes used for the OAuth stuff, which is good

And I'll also use it for the future OpenID 2.0 generic middleware: https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/pull/2/files#diff-5cf36d7a3098ef19627e2a76097ca8b6R255 :smile: 

That said, I'm not sure that renaming `AuthenticateAsync` to `CreateTicketAsync` is actually a good idea:

1. It would clash with the `CreateTicketAsync` method we use in the OAuth2 base handler (the two `CreateTicketAsync` methods would only differ by their arguments) :laughing: 

2. `CreateTicketAsync` doesn't seem 'generic' enough to describe what could happen during the authentication process. For instance, `AuthenticateAsync` is also the place where the cookie middleware determines whether the cookie should be renewed. `CreateTicketAsync` would finally be much more than a simple method creating a ticket.

Why not simply renaming the protected abstract `AuthenticateAsync` to `AuthenticateCoreAsync`? (well, like in Katana 3, actually) :smile:

**Comment by HaoK** [comment]
Well Authenticate and AuthenticateCore might as well both be Authenticate in my book.  I was trying to tease apart what the base method does (which is deal with the Http IAuthenticationHandler stuff), and name the abstract "Core" something else, I guess to follow my own naming scheme, this could just be:

`public Task<AuthenticationTicket> HandleAuthenticateAsync()'

**Comment by HaoK** [comment]
Fixed in https://github.com/aspnet/Security/pull/343

**Comment by PinpointTownes** [comment]
:+1: `HandleAuthenticateAsync` seems a good option (though `HandleAuthenticationAsync` seems more natural).

**Comment by HaoK** [comment]
Yeah the naming pattern I used was simply adding a Handle prefix in front of the non virtual public method name (as opposed to the old Core suffix which I strongly disliked :)

**Comment by HaoK** [comment]
ab4ba794e546074a573fbf76d9150ffcf9752c89
