### ISSUE TITLE
Override default ClaimsPrincipal.PrimaryIdentitySelector

### ISSUE THREAD

**Issue by blowdart** [aspnet/Security#345]
In the case of multiple identities on a principal Principal.Identity returns the first one added (with no guarantee of this. Bad back compat decision, but what can you do?). I

If an unauthenicated identity is added first, followed by an authenticated one then User.Identity.IsAuthenticated will be false, which is probably not what people expect.

We should either override the identityselector to ensure ordering where authenticated identities are returned first, or remove all references to User.Identity.IsAuthenticated and replace them with a statement that looks in the Identities collection for any authenticated identity.

**Comment by brentschmaltz** [comment]
Good idea, we could then leave the Identities in the order that the Authentication Middleware placed them

**Comment by blowdart** [comment]
There are disadvantages

1) It's global over all principals. Which could be crappy if users create principals outside of the identity flow.
2) This would have performance issues, if it's called multiple times on a single identity. We should look at what's quicker in normal flow.

Alternatively an extension method on principal of `IsAuthenticated()` might be clearer, and would steer people away from using the hideous assumption filled back compat produced nightmare that is the `Identity` property.

**Comment by leastprivilege** [comment]
oh it is global? really? ;P

**Comment by brentschmaltz** [comment]
global, yes. This one could should been instance.
Would the extension method be global?

**Comment by blowdart** [comment]
How do you mean global? Extension methods are added to the type, but act upon an instance of that type.

**Comment by brentschmaltz** [comment]
Right, I was thinking all users would get the same experience, but only if they make the IsAuthenticate() call.
This seems better that overloading the PrimaryIdentitySelector which would affect all users.

**Comment by Eilon** [comment]
Not planning on doing this. Apps can work around this if needed.

We also believe that there is no correct way to solve this out-of-the-box, so we'd rather err on the side of doing nothing.
