### ISSUE TITLE
OpenIdConnectHandler.AuthenticateAsync should not throw SecurityTokenException

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#351]
If message.Error is ! null, the OIDC handler throws SecurityTokenException, it should throw OpenIdConnectProtocolException. Other SecurityTokenExceptions should be considered as well.

**Comment by Tratcher** [comment]
This was already fixed by https://github.com/aspnet/Security/issues/55 where we changed many of these exceptions to AuthenticationResult.Failed.
