### ISSUE TITLE
AuthenticationManager.SignOutAsync is not signing out with the IDP (AAD in my case)

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Security#356]
When `.SignOut` was in use, the behavior (which I think is correct) is that the app redirects to the IDP (AAD in my case), where the user is signed out, then they are returned back to the app ... and the cookie/claims are dropped in the process. If a challenge is issued again, the user is redirected to AAD and must provide valid credentials in order to log back in to the app.

I just upgraded an app's runtime (`dnx-coreclr-win-x64.1.0.0-beta6-12189`) and dependencies, and at some point recently `.SignOut` method went to `.SignOutAsync`. I updated the method, but the behavior is different now. The cookie/claims are dropped, but the app doesn't redirect to AAD ... the user is left signed in at AAD. Therefore, if a new login is attempted, it briefly goes to AAD but you don't supply credentials ... the user is still logged in there, so AAD just shoots them back to the app as a logged in user.

Isn't the prior behavior with previous `.SignOut` method the correct process ... shouldn't the user be logged out with the IDP? I don't see an obvious `AuthenticationProperties` setting for the `.SignOutAsync` method that I should be providing to give me the prior behavior.

**Comment by GuardRex** [comment]
@HaoK provided the answer to this in https://github.com/aspnet/Security/issues/313#issuecomment-120668602.

I was using this controller for the sign out, which I think I obtained from the ADAL sample for .NET 5 (back when the method was `.SignOut(...)`:
```c#
// GET: /Account/LogOut
[HttpGet]
public IActionResult LogOut(){
    if (Context.User.Identity.IsAuthenticated) {
        Context.Authentication.SignOutAsync(OpenIdConnectAuthenticationDefaults.AuthenticationScheme);
        Context.Authentication.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
    }
    return RedirectToAction("Index", "Home");
}
```
@HaoK explains:
> The new behavior is sign out redirects immediately rather than later so before the sign out would win. Now the redirect to home wins which is why you need to return empty result.

Therefore, this is what I needed:
```c#
// GET: /Account/LogOut
[HttpGet]
public void LogOut(){
    if (Context.User.Identity.IsAuthenticated) {
        Context.Authentication.SignOutAsync(OpenIdConnectAuthenticationDefaults.AuthenticationScheme);
        Context.Authentication.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
    }
}
```
Three cheers to @HaoK ... this was the last thing I needed for a full story on ADAL AAD for `dnxcore50`! :beers: all around!

**Comment by PinpointTownes** [comment]
@GuardRex glad you sorted it out :smile: 

IMHO, you should `await` `Task`-returning methods to avoid race conditions.

```
// GET: /Account/LogOut
[HttpGet]
public async Task LogOut(){
    await Context.Authentication.SignOutAsync(OpenIdConnectAuthenticationDefaults.AuthenticationScheme);
    await Context.Authentication.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
}
```

(related comment: https://github.com/aspnet/Security/pull/257#discussion_r33391477)

**Comment by GuardRex** [comment]
@PinpointTownes Will do. I was wondering about that, but I had it in the format without `await` because I thought that those `SignOutAsync()` methods were returning void ... such that I thought that they might be executed in an asynchronous way regardless of adding `await` here. Anyway ... yes, I changed the code as you suggested. Thanks.
