### ISSUE TITLE
AuthorizeAttribute with OpenIdConnect don't redirect to external login page

### ISSUE THREAD

**Issue by heavenwing** [aspnet/Security#357]
I've added [Authorize] to the controller action and app.UseCookieAuthentication();app.UseOpenIdConnectAuthentication(); to Startup.cs.When I hit the controller action marked with [Authorized] attribute error 401 occurs but no redirection.

**Comment by mikeandersun** [comment]
I have the same issue.

**Comment by PinpointTownes** [comment]
Make sure you're using the `automatic authentication mode`:

```csharp
app.UseOpenIdConnectAuthentication(options => {
    options.AutomaticAuthentication = true;
});
```

http://stackoverflow.com/a/31322496/542757

**Comment by muratg** [comment]
Thanks @PinpointTownes! @heavenwing if this doesn't solve your issue, please re-open.

**Comment by cc-john** [comment]
Try setting options.ClientSecret to an appropriate guid value. The VS2015 template leaves this out.
