### ISSUE TITLE
Authorization : AddAuthorization() method do not use the configureOptions parameter

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Security#364]
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authorization/ServiceCollectionExtensions.cs#L22

**Comment by PinpointTownes** [comment]
This overload shouldn't even exist, actually :smile:

**Comment by HaoK** [comment]
Why shouldn't this overload exist?  Its just sugar to add/configure in one line (assuming it was implemented :)

**Comment by PinpointTownes** [comment]
Because it's actually the only **Add** method in aspnet/Security that accepts a delegate to configure the options :smile: 

This pattern is fine, but it should be used everywhere or nowhere, for consistency :smile:

**Comment by HaoK** [comment]
If you are talking about AddAuthentication(), that's because its fake, and is only adding other things like DataProtection.  All of the other AddXyz follow this pattern.  The difference its there is no master AuthenticationOptions to configure.

I'm probably going to prototype nuking using IOptions from all of the auth middlewares soon, and having them go back to taking concrete instances in UseGoogle etc...

**Comment by PinpointTownes** [comment]
I guess it could/should be updated to configure SharedAuthenticationOptions, which must currently be configured with the hardly-discoverable generic services.Configure<SharedAuthenticationOptions>() :smile: 

There are a few places where Add doesn't take a delegate: https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNet.Session/SessionServiceCollectionExtensions.cs

https://github.com/aspnet/Antiforgery/blob/dev/src/Microsoft.AspNet.Antiforgery/ServiceCollectionExtensions.cs

https://github.com/aspnet/CORS/blob/dev/src/Microsoft.AspNet.Cors.Core/CorsServiceCollectionExtensions.cs

**Comment by PinpointTownes** [comment]
> 
I'm probably going to prototype nuking using IOptions from all of the auth middlewares soon, and having them go back to taking concrete instances in UseGoogle etc...

Does that mean we won't be able to use Configure*Authentication anymore?

**Comment by HaoK** [comment]
Yeah those are probably bugs in those repos, I made a pass through to fix these once

Yeah AuthOptions will basically no longer go in DI, and only can be configured via UseXyz.

**Comment by PinpointTownes** [comment]
I protest then, because it's a great way to configure per-environment options: https://gist.github.com/PinpointTownes/c2096cd2cbf812f8d500

**Comment by HaoK** [comment]
I don't think that argument holds much water, since you can just switch to using the ConfigureXyz methods instead and still have something similar

**Comment by HaoK** [comment]
Both ConfigureXyzServices and ConfigureXyz can be per environment today

**Comment by ycrumeyrolle** [comment]
@HaoK I asked the question around the differents ways to "configure" the Options on stackoverflow:
http://stackoverflow.com/questions/31485311/configure-a-component-in-asp-net-5
If you have the answer of what should be done and what should not, it would be great!

**Comment by PinpointTownes** [comment]
> Both ConfigureXyzServices and ConfigureXyz can be per environment today

Using `IHostingEnvironment.EnvironmentName`? It seems less handy than the Configure*Services approach.

> I'm probably going to prototype nuking using IOptions from all of the auth middlewares soon, and having them go back to taking concrete instances in UseGoogle etc...

You would remove it from the security middleware, but not from the other ones?

**Comment by HaoK** [comment]
Yes, the motivation is mostly around nuking named options.  Security middleware (unlike frameworks) doesn't lend itself to the singleton style of options that frameworks use.  Many of the other middlewares today aren't actually using IOptions for their options anyways, so this would make everything consistent, and clean up options as well by nuking the whole named complexity that I had to create just to get Security/Identity/Cookies all playing well together...

**Comment by PinpointTownes** [comment]
Understood :smile: 

Related question: do you have plans for multi-tenant scenarios? (https://github.com/aspnet/Security/issues/35). `IOptions<>` seemed to be a nice first step in that direction.

**Comment by HaoK** [comment]
For once I'll reply with a @blowdart -ism:  no plans

**Comment by csunali** [comment]
@HaoK, that is sad.

**Comment by HaoK** [comment]
3294de14f43108f11af682b4d30090a131be0d71
