### ISSUE TITLE
Remove usage of IOptions from Auth middlewares

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#367]
Named options are being removed.  Middleware should use instances of Options instead of IOptions

**Comment by leastprivilege** [comment]
Just curious- why?

**Comment by HaoK** [comment]
We found that it didn't work perfectly and it was fairly hard to discover/understand compared to the more straight forward old way of each middlewares getting their own separate instance of options to work with.  

Singleton `IOptions` works great for frameworks but it didn't ever really feel like a great fit with middlewares.  I tried to papered over it with as much sugar as I could via extension methods, but it still felt pretty clunky.  Most middleware don't even need this anyway, as only identity and the auth middlewares were using named options.

So at the end of the day, the Startup.cs usage of auth will look the same, except you won't be able to configure auth options in ConfigureServices anymore, only be configurable via the app builder:

`app.UseXyz(options => options.AppId = "abc")`

**Comment by leastprivilege** [comment]
I think you are right!

This is more or less the outcome of our discussion three months ago ;)

**Comment by HaoK** [comment]
Small change in plans, instead of removing usage of IOptions, the new pattern for options is simply to make each options instance implement IOptions of itself, so they can be directly passed in, which will bypass whatever shared options were in DI.  Still working through the details of exactly how the new UseXyzAuth methods will be most likely:

```
UseXyzAuth(options => options.Foo = "whatever") // same as today, action tweaks options from DI
UseXyzAuth(new XyzOptions() { options.Foo = "whatever" }) // will use only this instance, ignores DI options
```

**Comment by PinpointTownes** [comment]
Really glad to see you changed your mind concerning `IOptions`, removing it from authentication middleware would have been a real mistake :smile:

**Comment by HaoK** [comment]
Well this just means I have another battle to fight now which is changing all middlewares to use IOptions consistently...

**Comment by PinpointTownes** [comment]
Don't worry, Captain HaoK, I'll cover you :smile:
