### ISSUE TITLE
[OIDC ]Transforming AuthenticationTicket in SecurityTokenValidated notification - and nonce checking bypass bug?!

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#372]
Looking at beta5 but seems to be also the case for dev branch - 

In Katana I was able to transform the contents of the authN ticket in the SecurityTokenValidated event - especially the claims. Typically I want to strip things like iss, nonce, exp, nbf etc - because I don't want these claims in my cookie.

In the current bits - I can only do that if I call HandledResponse() in the notification - otherwise the original authN ticket will be returned. 

But if HandledResponse = true - the nonce checking is not being performed. 

Is that intentional? Is there another way I should transform the claims before they are handed off to cookie middleware.

Letting the user (unintentionally) bypass nonce checking seems like a bug to me.

**Comment by brentschmaltz** [comment]
@leastprivilege we defined setting HandledResponse as telling the runtime to step aside and the ticket has been created, just use it.

Here are some options
JwtSecurityTokenHandler has a static (yes we have a work item to have instance and a static default), InboundClaimFilter. It is currently empty, any values in that set will be filtered if they match claim.Type.

OIDCAOptions.SecurityTokenValidators allows you to plug a derived JwtSecurityTokenHandler which could override CreateClaimsIdentity (sorry no delegate here).

**Comment by leastprivilege** [comment]
Yea - I don't like any of these options. 

I want to be able to replace the authN ticket in SecurityTokenValidated - but after the token is actually *fully* validated (and the nonce cached is cleaned up).

Simply move the nonce handling before firing the notification and everything is fine.

**Comment by brentschmaltz** [comment]
Ok, well then we might have a bug.  If you set the ticket in the SecurityTokenValidated notification we should continue on using that ticket unless you call Handled or Skipped.

**Comment by leastprivilege** [comment]
Yes - that's one part to it.

The other part is that i don't get why there is an event called SecurityTokenValidated - when the token is not validated yet. And exiting there leaves protocol artifacts that cannot be easily cleaned up manually.

**Comment by brentschmaltz** [comment]
The design behind exiting after notifications such as SecurityTokenReceived / Validated was to give users the ability to take over validation. It gives one a place to take complete control.
Having just reviewed HandleUnauthorizedAsync, it looks like we write the cookie nonce before calling RedirectToIdentityProvider, that needs to be adjusted for this to be symmetric and address artifacts lying around.

STV is about giving you the opportunity to modify claims, I agree until the 'OIDC Message' has been validated STV notification should not be fired.

Do you think there is value in changing the name of the notification?

https://github.com/aspnet/Security/issues/278 - notes the need for work here. We can address this issue with 278.

**Comment by Eilon** [comment]
This should probably go through claims transformation, but there might be some limitations there in the current code.

@Tratcher might have some thoughts on how this is already improved a bit, but perhaps not yet entirely. The last few commits in this repo help address this.

**Comment by leastprivilege** [comment]
Well - claims transformation is for changing the claims for the current request. The notification is for changing the claims before the get persisted into the cookie...

**Comment by Tratcher** [comment]
This should help with some of the validation concerns:
https://github.com/aspnet/Security/commit/86962ab12cee49209e9b9c1a87687ad11b6f9628

As for the claims transformation, I think the claims transformation middleware should hook into the SignIn code path to modify the principal before the cookie is generated.

**Comment by leastprivilege** [comment]
And how do you want to distinguish between the "initial" transformation and per-request?

**Comment by Tratcher** [comment]
I was thinking CT would have two different events, sign-in and authenticate. However, thinking about it more I realize there may be an ordering issue. For CT to intercept sign-ins and authenticates, your ordering would have too look like this:
CookieAuth
Bearer
ClaimsTransformation
OIDC
OAuth (FB, MS, Goog, Twit)

This could probably work, but I bet a lot of people would get it wrong.

**Comment by leastprivilege** [comment]
so beta7 has still the same bug?

**Comment by Tratcher** [comment]
? https://github.com/aspnet/Security/commit/86962ab12cee49209e9b9c1a87687ad11b6f9628 is in beta7.

**Comment by leastprivilege** [comment]
OK - but i still need to call HandleResponse - otherwise the new authentication ticket is discarded. Is that by design now?

**Comment by Tratcher** [comment]
The flow is somewhat ambiguous there. We should change it to flow the value you set.
