### ISSUE TITLE
Removal of AuthorizeCore may be too restrictive

### ISSUE THREAD

**Issue by taori** [aspnet/Security#374]
http://stackoverflow.com/questions/31464359/custom-authorizeattribute-in-asp-net-5-mvc-6

When researching how some things are done in MVC 6 i ran into this question, which i had the same issue with and ran into 2 issues regarding the new authorization.

Issue 1:

Seeing how this question got plenty of attention (9 days, 1040 views) the question asker and me are obviously not in a minority. While the person answering the question certainly made clear why it was changed the way it is now and how it works this concept is too restrictive.

It requires you read up on quite a bunch of concepts and setting up a structure to store identities+claims etc and using certain classes in order to get things done, which is a tremendous amount of work (including being forced to change your entire to be built around claims etc) if you are transitioning a project from 5x to mvc 6.

While i do think the new concept seems nice and flexibile, i think it's important to provide a simple alternative to have a swift and easy way to do the whole authorization manually.

"We don't want you writing custom authorize attributes. If you need to do that we've done something wrong. Instead you should be writing authorization requirements."

While i don't think the new concept is wrong in general, i do think it is still too restrictive. In the past there have been mutliple authorization methods in the asp stack, which all seemed fine, but were frowned upon because of being forced to do things the way MS wants you to do them. The most amazing part about MVC was that it made replacing key parts a breeze - This change however is putting shackles upon developers once again.

Issue 2:

"@blowdart Is the way to handle authorize without a value for policy "options.AddPolicy(string.Empty, policy => policy.AddRequirements(new Test()));" ? I'm in the process of trying it out but right now i get an empty page + debugging does not work"

I presume others will run into this issue too.

Please revisit the way "AuthorizationApplicationModelProvider.cs" deals with the authorize attribute and provide a way of injecting a class to do manual authorization in order to mitigate upgrade issues to mvc 6. 

Yes, working with identities sounds fine in concept - but not everyone wants to do his authorization the way you are trying to force them to.

**Comment by blowdart** [comment]
As the person who pushed for the new system I'm rather biased, but no-one has ever given me a concrete example of something they cannot express in code as an authorization policy. The only mix-ups I've seen is when folks combine authentication and authorization, which we are now more strict about keeping apart. 

There's no need at all to use the identity system as the basis for authorization, and the authorization stack and middleware concept isn't new to this version, but was present after the move to the Katana architecture. 

When you say "I want a simple alternative to do authorization manually" I would love some code to illustrate what you mean. Your idea of simple may be different to others and I can't just assume what you mean. You may think you need to drop out the entire stack in MVC, but I honestly don't believe you do as now the built in attributes will call through to your policies with no work on your behalf beyond writing a requirement and writing it up, which should take a lot less code than implementing another authorization stack and authentication middleware.

As for why you want a policy with no name you still haven't told me what you're trying to achieve here. What are you assuming an unnamed policy is? Are you trying to replace the default behaviour of the authorize attribute? Again this hasn't changed, it's exactly as it's always been, even in ASP.NET v1.

I need you to tell me details of what you want before I can tell you if you can do it, or if we need to look at ways to support your requirements, or if we simply won't do it at all.

**Comment by taori** [comment]
You seem like a reasonable person to me, so i doubt you'd struggle putting bias aside. That being said i will point out a common case i've (ab)used overloading this method in the old attribute:

Check if Identity is present -> 
Ajax call? -> Execute javascript
Normal call ? -> Redirect to login page.

While this certainly does not strictly have to do with authorization itself it is a perfect hook to make sure that in any case you will redirect your user to the login page or execute custom js to prompt the user with a login dialog.

That's really the reason i attempted to use an empty policy name. In every case of an authorization process i want to previously run some custom code, even if a sub action does use a policy.

I don't mind the new architecture at all - in fact i really enjoy seperation of concerns, because it turns looking for certain code a lot easier.

But with this change i am unaware of how to hook myself right before every authorization to do my custom Request redirect / Js Code injection.

My guess is that there is another middleware for that now? Originally i've found the solution to "session expired, redirect to login" etc on stackoverflow using that described method (e.g. http://stackoverflow.com/questions/25423464/redirect-to-specific-page-after-session-expires-mvc4). So i think a method of doing this should at least be documented.

Sorry for the waiting time. Been working.

I hope i explained it well enough, where my confusion is comming from.

**Comment by blowdart** [comment]
So how are you triggering the JS to run? With a specific value returned?

Cookie auth has redirection, as does OpenID. Other types don't because it doesn't make sense. For example a bearer token middleware would just return status codes.

**Comment by taori** [comment]
Until now i do it like this:

public class Sample : AuthorizeAttribute
	{
		public override void OnAuthorization(AuthorizationContext filterContext)
		{
			filterContext.RequestContext.HttpContext.Response.Write("<script type='text/javascript'>alert('do something');</script>");
			filterContext.RequestContext.HttpContext.Response.End();
			base.OnAuthorization(filterContext);
		}
	}


MVC 5 cookie snippet
			app.UseCookieAuthentication(new CookieAuthenticationOptions()
			{
				AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
				LoginPath = new PathString("/Account/Login"),
				LogoutPath = new PathString("/Account/Logout"),
				AuthenticationMode = AuthenticationMode.Active,
				Provider = new CookieAuthenticationProvider()
				{
					OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<ApplicationUserManager, ApplicationUser, long>(
						validateInterval: TimeSpan.FromMinutes(30),
						regenerateIdentityCallback: (manager, user) => manager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie),
						getUserIdCallback: identity => identity.GetUserId<long>())
				}
			});

Yeah, i assume you can just insert the ajax request switch inside the login action. which feels kind of clean still, but it's limited to executing code during one form of authentication then. 

I guess i could live with that. But inserting that kind of logic in the controller does feel a little weird (someone else changes view name - my login redirect does not work anymore. nice?; Yes, i use constants/comments for that, but not everyone does.). Doing it in the authorization attribute felt like the better place for it.

What's your recommended solution for solving it without the attribute? Because the old way sure was a convenient and refactor safe way to make sure you're running your code.

**Comment by blowdart** [comment]
That makes me shudder a little. 

I've opened issue #376. What we've tried to do, and it still isn't easy enough, is allow you to filter identities. So if you had a webapi endpoint you could limit it to bearer middleware and ignore cookieauth. This would then enable spa/bearer auth as it should be, and close a bunch of CSRF loop  holes.

However right now everything still goes haywire if you have an automatic middleware, so replacing the default policy with one you could configure might go some way to alleviating the pain of implementing this (right now you'd have to apply a policy which requires cookie sourced identities everywhere except the webapi).

But still, writing out a response, rather than a status in auth middleware seems wrong to me

**Comment by taori** [comment]
#376 Looks exactly like something one can (ab)use for that yes. 

"But still, writing out a response, rather than a status in auth middleware seems wrong to me".

From an architect point of view - i absolutely agree - yes, certainly not quite the right place

From a "i need to stop my colleagues from copy pasting redirects/javascripts everywhere" point of view - i am just looking for a convenient way to make sure they can't break my code, which does not confuse them and stops them from writing lots of unnecessary code.

Not everyone works at companies where people are interested in refining their skills, sadly. Anyway - thats OT.

#376 Potentially resolves #374 since it provides an easy hook. This issue could be considered solved, once adding an empty policy name throws an exception (when i tried it did not, then again no break points are attaching during startup in 2015 RTM right now), since you pointed out that case is something which surprised you someone would even try.

**Comment by Eilon** [comment]
We are not planning to change this design.
