### ISSUE TITLE
Enable default policy for MVC authorize attribute

### ISSUE THREAD

**Issue by blowdart** [aspnet/Security#376]
This would make the multiple identities scenarios easier, as a dev could set the default behaviour to use Cookie auth, which in turn would mean you wouldn't have to set cookie auth to be automatic, and filtering would work as expected when you limit to bearer.

**Comment by HaoK** [comment]
Looks like this behavior actually comes from Policy.Combine, where we add RequireAuthenticatedUser by default.  

How about we just add a default policy to the options which we use for this instead?  The default behavior would be the same, just requiring any authenticated user.

You could replace it via

```services.ConfigureAuthorization(options => options.DefaultPolicy = new PolicyBuilder().AddWhatever().Build())```

**Comment by blowdart** [comment]
Might work - can you give it a shot?

**Comment by HaoK** [comment]
3294de14f43108f11af682b4d30090a131be0d71
