### ISSUE TITLE
Announcement Discussion: AuthenticationHandler<T> is now only async, AuthenticateCore() renamed to HandleAuthenticateAsync()

### ISSUE THREAD

**Issue by blowdart** [aspnet/Security#379]
Authentication handlers have now dropped their synchronous methods and are fully async

In addition to this there has been method renames;

1)

    protected override AuthenticationTicket AuthenticateCore()

has now become 

    protected override async Task<AuthenticationTicket> HandleAuthenticateAsync()

2)

    protected override void ApplyResponseChallenge()

has been split and now becomes

    protected override async Task<bool> HandleUnauthorizedAsync(ChallengeContext context)
    protected override async Task<bool> HandleForbiddenAsync(ChallengeContext context)

**Comment by kspearrin** [comment]
You might want to point out that `ApplyResponseChallenge` was also dropped in favor of methods like `HandleUnauthorizedAsync` and `HandleForbiddenAsync`.

**Comment by PinpointTownes** [comment]
@blowdart you should try to make shorter announcements :smile: 

The fact authentication handlers are now `async` is clearly not the most important change. The most important thing to note is that `ChallengeAsync`/`SignInAsync`/`SignOutAsync` are now immediate and not deferred like they used to be in Katana 3, which has different implications in everyday's code: https://github.com/aspnet/Security/pull/257#discussion_r33391477 and https://github.com/aspnet/Security/issues/313#issuecomment-120668602.

You **should** really write some serious documentation about this important change.

**Comment by blowdart** [comment]
SignInAsync is not a middleware issue, it's a separate announcement.

**Comment by PinpointTownes** [comment]
True, but it has a **direct** impact on how `AuthenticationHandler`'s methods are invoked.

**Comment by PinpointTownes** [comment]
BTW, there's an awful typo in the title... `aynsc` -> `async` :smile:

**Comment by jods4** [comment]
Just saying: the naming of `HandleUnauthorizedAsync` and `HandleForbiddenAsync` is not great. To me `Unauthorized` is pretty much a synonym of `Forbidden` so I'm clueless as to what the difference between the two might be (I guess I'll have to read the documentation -- then the issue becomes remembering which is which).

**Comment by blowdart** [comment]
We're using the same names as HTTP uses, and the wording are the generally accepted industry terms.

Unauthorized = There is no identity
Forbidden = There is an identity already, but it doesn't meet the requirements of the system.

The wording is unlikely to change.

**Comment by artganify** [comment]
@blowdart +1

There is a clear difference between 'Unauthorized' and 'Forbidden' though I agree that the names can be confusing - but that's the fault of the HTTP standard. ASP / any other http-related platform have always made that distinction so thank you for providing both seperatetly.

**Comment by HaoK** [comment]
Closing really old auth discussion
