### ISSUE TITLE
Configure Redirect to Login View

### ISSUE THREAD

**Issue by Fosol** [aspnet/Security#380]
How do we configure what the default login view will be in MVC 6?  I've looked high and low and can't find anyone talking about it.  I am not using the out-of-the-box solution.

Any help is appreciated.

**Comment by Tratcher** [comment]
I think you're looking for this:
https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L45

MVC just does Authorization. When it rejects a request the cookie authentication middleware can pick it up and redirect it to a login page.

**Comment by Fosol** [comment]
First of all thanks for your response!

However I can't figure out how the sample as the following method; ChallengeAsync and SignOutAsync.

I'm sure they're probably extension methods, but they don't show up.

This new model is overly complex in comparison to adding the default login page.  I'm a big fan of middleware and extensibility, however I'm getting lost in the details.  Is there any documentation on this?

**Comment by Fosol** [comment]
I found the Async methods.  they're in the new beta7.  So that leads to the next question/problem.  So far I haven't had much luck mixing beta version of the various nugget packages.

What's the general rule about mixing versions?  The user/developer experience so far with the new nugget package versioning is horrible.  It's only great when you don't do anything outside the default...

**Comment by Fosol** [comment]
As soon as you mix versions you get 500 errors where it can't even resolve system objects...

**Comment by Fosol** [comment]
I've attempted to update as many nuget packages to the latest builds.  I get the following error;

Method 'Start' in type 'Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication' from assembly 'Microsoft.AspNet.Loader.IIS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by Fosol** [comment]
So you can't trust the NuGet Package Manager or the intellisense within the project.json file.

If you manually search at Nuget.org you can find that Microsoft.AspNet.SErver.IIS has a new beta6.

Now I simply get a 403 status.  It should have redirected to the login view I choose...

**Comment by Fosol** [comment]
With the latest Microsoft.AspNet.Server.IIS it doesn't even get to my Startup class.  It just throws a 403...

**Comment by Fosol** [comment]
In an attempt to ensure all my assemblies and DNX are the latest I now get a runtime error.  I upgrade to DNX beta6.

Could not load file or assembly 'Microsoft.Dnx.Host.Clr' or one of its dependencies. The system cannot find the file specified.

**Comment by Tratcher** [comment]
It sounds like you're using beta7 dnx with beta6 packages. Use dnvm to go back to beta6 dnx.

**Comment by Fosol** [comment]
I could only get my hello world app up and running with the following;
dnx "1.0.0-beta5"
      "Microsoft.AspNet.Identity": "3.0.0-beta5",
      "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta5",
      "Microsoft.AspNet.DataProtection": "1.0.0-beta5",
      "Microsoft.AspNet.Mvc": "6.0.0-beta5",
      "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta5",
      "Microsoft.AspNet.Server.IIS": "1.0.0-beta5",
      "Microsoft.AspNet.Server.WebListener": "1.0.0-beta5",
      "Microsoft.AspNet.StaticFiles": "1.0.0-beta5",
      "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta5",
      "Microsoft.Framework.Configuration.Abstractions": "1.0.0-beta5",
      "Microsoft.Framework.Configuration.Json": "1.0.0-beta5",
      "Microsoft.Framework.Configuration.UserSecrets": "1.0.0-beta5",
      "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta5"

Any other configuration just fails for all different reasons.

I get the impression from the example Startup you linked that the following should redirect to the login page.
            app.UseCookieAuthentication(options =>
            {
                options.AutomaticAuthentication = true;
                options.LoginPath = new PathString("/authorize/login");
                options.LogoutPath = new PathString("/authorize/logoff");
            });

This of course doesn't work.

**Comment by Fosol** [comment]
Essentially all I want is to be able to control the redirect when I place an Authorize attribute on an MVC controller.  The example you provided has no MVC and thus I think I don't even get down that far in the pipeline.

**Comment by Fosol** [comment]
Cheer!

I moved the order of things in my Startup.Configure(...) method.

Put this at the top;
            app.UseCookieAuthentication(options =>
            {
                options.AutomaticAuthentication = true;
                options.LoginPath = new PathString("/authorize/login");
                options.LogoutPath = new PathString("/authorize/logoff");
            });

Looks like I need to learn how the pipeline works.
