### ISSUE TITLE
Bearer token authentication no longer returns 401 on unauthorized request

### ISSUE THREAD

**Issue by jraadt** [aspnet/Security#382]
I have an API that authenticates with an IdentityServer.  My API controller has an [Authorize] attribute.  In beta 5 if I didn't pass up a bearer token it would return a 401.  In beta 6 it returns a 200 blank response.  Also, in beta 5 I noticed it has a WWW-authenticate header, while beta 6 does not.  How do I get it to return a 401 in beta 6?  Here's part of my sample Startup.cs:

        public void Configure(IApplicationBuilder app)
        {
            app.Map("/api", api =>
            {
                var options = new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = "http://localhost:55555/oauth",
                    RequiredScopes = new[] { "api" }
                };
                api.UseAppBuilder(builder => { builder.UseIdentityServerBearerTokenAuthentication(options); }, "SampleApi");

                api.UseMvc();
            });
        }

**Comment by jraadt** [comment]
After some experimenting, I got it to return a 401 by adding this block of code before the api.UseMvc(); line.  Is this the right way to do it?  Seems like something like this should just work without me having to manually check if the user is authenticated for returning a 401.

                api.Use(async (context, next) =>
                {
                    if (context.User == null || context.User.Identity == null || !context.User.Identity.IsAuthenticated)
                    {
                        context.Response.StatusCode = 401;
                        return;
                    }

                    await next();
                });

**Comment by Tratcher** [comment]
[Authorize] calls HttpContext.Authentication.ChallengeAsync() . This used to set the status code to 401 and then invoke the registered auth handlers. Now it relies on the auth handlers to set the appropriate status code when invoked. Unfortunately the old OWIN components do not set the status code.
@HaoK

**Comment by HaoK** [comment]
Doh, I knew that change was scary...  I'll take a look at this next week

**Comment by HaoK** [comment]
ping @lodejard for his thoughts

**Comment by jraadt** [comment]
@HaoK - thanks for looking into it.

I spent some more time trying all sorts of things and I actually got it to work with the following code in Startup.cs.  I basically had to include cookie authentication, which seems strange because I don't do anything with cookies.  But for some reason it triggered the right parts of the security to work.  Hopefully this helps you guys figure it out.

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication();

            services.Configure<ExternalAuthenticationOptions>(options =>
            {
                options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            });

            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseCookieAuthentication(options =>
            {
                options.AutomaticAuthentication = true;
            });

            app.Map("/api", api =>
            {
                var options = new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = "http://localhost:5555/core",
                    RequiredScopes = new[] { "api" }
                };

                api.UseAppBuilder(builder => { builder.UseIdentityServerBearerTokenAuthentication(options); }, "SampleApi");

                api.UseMvc();
            });
        }

**Comment by Tratcher** [comment]
@HaoK Shouldn't ChallengeAsync("") have thrown !Accepted when called from [Authorize]?

**Comment by HaoK** [comment]
Cookie picks it up since its automatic

**Comment by HaoK** [comment]
Oh, and we never throw for the empty/null scheme since that's meant for the automatic middlewares to pickup...

**Comment by HaoK** [comment]
Double checking the code again since its been a while just to make sure though :)

**Comment by HaoK** [comment]
Yah, we explicitly never throw for empty or null in DefaultAuthenticationManager:

```
            // The default Challenge with no scheme is always accepted
            if (!challengeContext.Accepted && !string.IsNullOrEmpty(authenticationScheme))
```

**Comment by Tratcher** [comment]
Hmm, that may be considered a bug now. Auto middleware should Accept and set the status code.

**Comment by HaoK** [comment]
So basically its a misconfigured app if they don't have any automatic and have authorize with nothing setup to listen to it?  That sounds reasonable @blowdart thoughts?

**Comment by blowdart** [comment]
If by nothing set up to listen you mean there's no automatic middleware they're not specifying a scheme that does feel like a misconfiguration.

**Comment by gruntster** [comment]
I think I have the same issue since updating to beta 6.

I'm using a custom middleware class to authenticate the user and assign appropriate claims, etc.

```	
app.UseMiddleware<HttpAuthenticationMiddleware>()
```
I've also registered an authorization policy with an authorization requirement.

```        
mvcBuilder.AddAuthorization(options => options.AddPolicy(
            "UserPolicy",
            builder => builder.AddRequirements(new AuthorizationPolicyRequirement())));
```
Beta 6 is now returning a status code of 200 instead of 401 when authorisation fails.  However if I enable cookie authentication with AutomaticAuthentication as noted by @jraadt, things work the way they used to.

Do I now need to use a custom AuthenticationHandler with a scheme for authorisation to work correctly?

**Comment by HaoK** [comment]
So to summarize the current thinking.  It sounds like we are leaning towards changing the behavior to throw instead of return a 200.  

Basically if you have an [Authorize] and no authentication handler is configured in automatic mode, this will throw instead of 200 today.  The workaround with cookies works because it does this.

@Tratcher Do we need to do anything to support the old owin components issue that you mentioned as well?

**Comment by jraadt** [comment]
I'm unsure how to resolve this in my original situation with IdentityServer.  I believe they are using the old owin components you are referring to.

        public static IApplicationBuilder UseAppBuilder(this IApplicationBuilder app, Action<IAppBuilder> configure, string owinHostAppName)
        {
            app.UseOwin(addToPipeline =>
            {
                addToPipeline(next =>
                {
                    var builder = new Microsoft.Owin.Builder.AppBuilder();
                    builder.Properties["builder.DefaultApp"] = next;
                    builder.Properties["host.AppName"] = owinHostAppName;
                    configure(builder);

                    var appFunc = builder.Build(typeof(Func<IDictionary<string, object>, Task>)) as Func<IDictionary<string, object>, Task>;
                    return appFunc;
                });
            });
            return app;
        }

Where would we enable automatic mode?

**Comment by Tratcher** [comment]
@jraadt  The OWIN security components/patterns are not directly supported by the UseOwin adapter (they were never part of the OWIN spec, just something Katana cobbled together). The only reason this used to work was that Challenge would set the status code to 401 and the OWIN middleware would see that on the way out and react. To preserve this behavior you now need something to react to the Challenge and set the status code. Something like this:
```c#
app.UseOwin(addToPipeline =>
        {
            addToPipeline(next =>
            {
                // ...
            });
        });
// ...
            app.Use((context, next) =>
            {
                var authFeature = context.GetFeature<IHttpAuthenticationFeature>();
                if (authFeature == null)
                {
                    authFeature = new HttpAuthenticationFeature();
                    context.SetFeature(authFeature);
                }
                authFeature.Handler = new InterceptingHandler(context);
                return next();
            });
// ...

        private class InterceptingHandler : IAuthenticationHandler
        {
            private readonly HttpContext _httpContext;

            public InterceptingHandler(HttpContext httpContext)
            {
                _httpContext = httpContext;
            }

            public Task ChallengeAsync(ChallengeContext context)
            {
                _httpContext.Response.StatusCode = 401;
                context.Accept();
                return Task.FromResult(0);
            }

            public Task AuthenticateAsync(AuthenticateContext context)
            {
                return Task.FromResult(0);
            }

            public void GetDescriptions(DescribeSchemesContext context)
            {
            }

            public Task SignInAsync(SignInContext context)
            {
                return Task.FromResult(0);
            }

            public Task SignOutAsync(SignOutContext context)
            {
                return Task.FromResult(0);
            }
        }
```
