### ISSUE TITLE
How to access DBContext from CookieAuthenticationNotifications

### ISSUE THREAD

**Issue by danroth27** [aspnet/Security#383]
Originally posted as https://github.com/aspnet/Mvc/issues/2892 by @ponsaravanan

I am trying to access db context from  CookieAuthenticationNotifications.OnValidatePrincipal for populating some properties from db. But couldn't access it. 

Searched for online documents on how to do the same. But no luck so far. 

MVC6, Beta5. I am using.

Any inputs to guide me will be greatly appreciated.

**Comment by danroth27** [comment]
@HaoK Could you please help out here?

**Comment by ponsaravanan** [comment]
Ok it was me who overlooked the OnConfiguring with the parameter DbContextOptions in beta5 and couldnt use the DbContext. later after searching the internet came to know that it is changed to EntityOptionsBuilder and again changed back to DbContextOptions  beta6, 

Unfortunately I was using beta5 and no samples on internet highlights much about the changes in the parameter.After on configuring work with connection string. It started working. I am closing the issues in SO and here also. 

Thank you
