### ISSUE TITLE
Where is Microsoft.IdentityModel.Protocols.OpenIdConnect ?

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Security#386]
After update to  Microsoft.AspNet.Authentication.OpenIdConnect version1.0.0-beta7-12747  I get the following error in project compilation!!!!
The dependency Microsoft.IdentityModel.Protocols.OpenIdConnect >= 2.0.0-beta7-207310921 could not be resolved.
 Thanks to any helps

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/blob/dev/NuGet.Config#L6

**Comment by Eilon** [comment]
Please use the feed specified in the file that @Tratcher linked to.

**Comment by Eilon** [comment]
These packages will eventually be on NuGet.org, but not the daily builds.
