### ISSUE TITLE
AuthorizationContext.Resource in an AuthorizationRequirement

### ISSUE THREAD

**Issue by alandevos** [aspnet/Security#388]
When trying to work with the AuthorizationContext.Resource object in an AuthorizationRequirement, the object is surprisingly missing all members at compile time.

Won't compile:
```cs
context.Resource.RouteData.Values["id"];
```

However, the expected members do exist at runtime.

Will compile and allow access to members:
```cs
dynamic resource = context.Resource;
var id = resource.RouteData.Values["id"];
```

Bug?  Is there another preferred way to access HttpContext/RouteData within a requirement?

**Comment by HaoK** [comment]
Can you include a more detailed repro and I'll take a look?  Perhaps just the entire controller action method and the relevant authZ policy/requirement classes?

**Comment by alandevos** [comment]
Thanks!

[](https://github.com/alandevos/AuthRequirementExample)

**Comment by HaoK** [comment]
Resource is typed as object, so you have to cast it to what you expect it to be.
