### ISSUE TITLE
Cookies should not Accept a Challenge (or anything else) unless it does something

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#389]
Right now the CookieAuthHandler will Accept a Challenge (Unauthorized or Forbidden) even if it doesn't have the associated LoginPath or AccessDeniedPath configured. This appears to be a configuration error and should throw.

**Comment by HaoK** [comment]
We decided to always do something (redirect) b883920befce4afaac89ec031d30d868a48df666
