### ISSUE TITLE
Port the OAuth middleware from Katana

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#39]
Do not port the OAuth authorization server, @blowdart says we should use the Thinktexture server instead.

**Comment by Xacron** [comment]
For anyone still looking for the original OAuth Authorization Server in ASP.NET 5, I have ported the code and the original sample here:
https://github.com/XacronDevelopment/oauth-aspnet

The port includes backwards compatibility to allow ASP.NET 4.x resource servers to read the access tokens created by the authorization server.

The nuget packages are here:
https://www.nuget.org/packages/OAuth.AspNet.AuthServer
https://www.nuget.org/packages/OAuth.AspNet.Tokens
https://www.nuget.org/packages/OAuth.Owin.Tokens
