### ISSUE TITLE
React to System.Security.Cryptography.* changes in CoreFX

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#396]
https://github.com/dotnet/corefx/commit/ce0506baea623efdb74707aee0e4aa169d6f468c

![image](https://cloud.githubusercontent.com/assets/6998306/9151283/543630a0-3dfd-11e5-9d66-d5b3e0d73dbd.png)

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Facebook/project.json#L17

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Twitter/project.json#L22

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication/project.json#L22 (for this one, see my previous remark: https://github.com/aspnet/Security/commit/19d026268b80ad7a2299c4366fbc717e6b7bd9eb#commitcomment-11885651)

Related to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/212

/cc @Eilon @HaoK @Tratcher

**Comment by Tratcher** [comment]
Yes, we're expecting the AzureAD changes today.

**Comment by PinpointTownes** [comment]
Wilson was just updated by @tushargupta51 with the packages changes I mentioned: 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/213

Has someone been assigned to add the required changes in the different ASP.NET repositories?

**Comment by Eilon** [comment]
@Tratcher can you own this?
