### ISSUE TITLE
Consider changing AuthorizationHandler.Handle from void to return a result

### ISSUE THREAD

**Issue by lfoust** [aspnet/Security#398]
The current signature of ```AuthorizationHandler```.Handle is:

```C#
public void Handle(AuthorizationContext context)
```

and to implement this method, you are expected to call either ```context.Succeed``` or ```context.Fail``` to indicate the result of the ```AuthorizationHandler```. This feels like a very awkward API and allows for people to implement Handle without ever signaling a result.

A much clearer approach would be to make the Handle method return a result either as a boolean:

```C#
public bool Handle(AuthorizationContext context)
```

or as a result object:

```C#
public AuthorizationResult Handle(AuthorizationContext context)
```

This would allow for developers who are implementing their own requirements to fall into the pit of success when signaling authorization results.

For reference, the change (by @HaoK) where this was added is:
SHA: 775eb5ec

**Comment by HaoK** [comment]
This was considered and the reasoning was basically that we wanted to allow handlers that did nothing potentially.  The current design gives full control to the handlers as they are called with every requirement, and they don't necessarily handle every requirement.  But they are always given the option.
