### ISSUE TITLE
Port the JWT & AAD middleware from Katana

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#40]
Depends on https://github.com/aspnet/Security/issues/39 (OAuth) and System.IdentityModel.Tokens.Jwt.

We'll need to re-work the IIssuerSecurityTokenProvider to use the new ConfigurationManager for retrieving metadata (See WsFederation).

For AAD, also fix https://github.com/aspnet/Security/issues/25

**Comment by PinpointTownes** [comment]
@brentschmaltz started working on a (lightweight) `aspnetcore50` port of `System.IdentityModel`: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/K

The nightly builds are available on the Azure AD team MyGet repository: https://www.myget.org/gallery/azureadwebstacknightly

The weird thing is that this package also provides an implementation for `aspnet50`, that replaces the one provided in the full .NET Framework 4.5 (both are incompatible). I'm not sure it's a great idea (you can't use a project built with .NET 4.5 and using types from `System.IdentityModel` with the new NuGet package).

@brentschmaltz I already miss the `GetAsymmetricAlgorithm` method on `AsymmetricSecurityKey` (and its counterpart on `SymmetricSecurityKey`). Is this something you could add?

That would be great if we could chat a few minutes on JabbR :smile:

**Comment by Tratcher** [comment]
Done. See https://github.com/aspnet/Security/commit/49e66f03110b486f8dd9959dd2cee802d676c28f
Note this was merged with the OAuth Bearer middleware.
