### ISSUE TITLE
AuthorizationHandler - Current HttpContext + Route Information?

### ISSUE THREAD

**Issue by Fosol** [aspnet/Security#400]
Is it possible to get the current HttpContext and Route information within the AuthorizationHandler?

I need to be able to have dynamic policies which check the current request (route) to determine whether the user has authorization.

**Comment by blowdart** [comment]
Nope, all you get is the authorization context. You could, I suppose, do it imperatively by using resource based authorization and mapping the route information to a resource class.

**Comment by Fosol** [comment]
I don't follow your suggestion.

Do you mean a configuration that contains resources and mapping the route information to an entry within the configuration?  If so, that is what I'd like to do.

I however don't know how to capture the current route information within the Authorization framework.  The AuthorizationHandler & AuthorizeAttribute don't pass any information about the current route request.  Am I missing something?  Shouldn't the request information be sent to the authorization code?

**Comment by blowdart** [comment]
We took a deliberate decision not to send route information to attribute based authorization, because by applying the attribute at the controller method you have the route, unless you're doing something strange like mapping multiple routes to the same controller.

Instead we have resource/operation based auth. Normally this would be aimed at something like "I have this document, a resource, and I want to see if the current user can edit it, an operation".

So you could have a resource class which contains everything you wanted from the context, and auth against that with a single operation of Visit or View.

I'd like to figure out why you want the actual context and route data though. Those are MVC specific and we've been trying to move away from locking policies into MVC only, in the hope that you can write common policies that would work cross platform should, for example, Nancy pick it up.

**Comment by Fosol** [comment]
The use case I'm commonly dealing with is as such;

1) I have endpoints (MVC Controller Action).
2) A request is made (from a 3rd party or user).  Authentication occurs as per normal.
3) I have a dynamically configured role base system which roles can be created and then granted access to specific endpoints (operation).  I can't go [Authorize(Roles = "somerole")] because the roles are dynamically created, and or changed.  There can be multiple roles allowed to perform the operation.

What I want to do is create a configuration that I can update that maps endpoints (operations) to roles.  Then when a request is made to an endpoint it reviews that configuration to determine if the request is authorized.

I used to be able to do this by overriding the AuthorizeAttribute.  Essentially I could have it go out and verify based on configuration.

The new framework however doesn't support this behaviour.  Instead it's a push to apply policies and authorization requirements.  Which sounds great, but it has no dynamic mapping to the actual request.  Thus I can't determine within the handler whether the current request is authorized since I can't map it to the configuration.  The only way I think I can do it with the current framework is to create a separate policy for every endpoint (operation) I have.  Then each one would know because it's hardcoded where it is relevant.

What am I missing?

**Comment by blowdart** [comment]
Can you give me a concrete example? What out of the request or route information are you wanted to make decisions about?

You could, perhaps, user claims transformation to add the information from the current request as claims to the current authenticated identity. Authorization is aimed at identities and resources, not request properties.

**Comment by Fosol** [comment]
I'm dealing with hundreds of endpoints that the client has control over what their users are able to perform.

Basic Structure
Operation (Endpoint) -> Role(s)/Claim(s)

Reality
Endpoint -> I don't know what role will be assigned access

I have a few options.
1) I can create claims for every endpoint/operation and apply them to the user.  Lots of claims.  Then I need to create policies for every endpoint/operation that check if the user has the appropriate claim.
- This however means I need to create a policy every time I create an endpoint.  It adds work.
- I don't know if having hundreds of claims is an issue?

2) I want to map the endpoint/operation dynamically to a configured role based system.  Which means at the point of request it needs to know which endpoint/operation is being requested so that it can go look up the configuration for the current user.

I believe the authorization framework you are implementing forces me to do (1).  I'm hoping someone will give me a third option.  One that follows your best practices (framework) but also doesn't require such an ugly implementation.

**Comment by blowdart** [comment]
Are you wed to doing this as an attribute, as opposed to an if Authorize() in code?

**Comment by Fosol** [comment]
I don't have a preference.  An attribute would allow me to pass the current route id (something that can be mapped to a configuration).  But that attribute would need to be known by the authorization implementation so that it could then do the check with the current user.

**Comment by Fosol** [comment]
I have to I'll add a method to every single endpoint.  Boilerplate code I guess.

**Comment by Fosol** [comment]
But this would mean the AuthorizeAttribute is mostly useless.

**Comment by blowdart** [comment]
For your purposes yes it is because you want a single policy over every route. That's not what this is designed for. You're at the CMS/multitenancy point and that's where people start rolling their own custom pieces because everyone's requirements vary. You'd also wanting MVC specific information in a policy system that is meant to apply to more than just MVC.

What you could do is approach it with resource based auth, which is what you seem to be indication you want. 

Take a look at https://onedrive.live.com/view.aspx?resid=600FD0DBAAE1E40F!283770&ithint=file%2cpptx&app=PowerPoint&authkey=!AHropH0wGXJdtIQ slides 40-42. You'd define your resource as a class containing the bits of route data and context you want, then in each controller method you'd construct it, and check it

    var myResource = new Resource(context, routeData, etc)

    if (authorizationService.Authorize(User, myResource, Operations.View))
    {
        return View();
    } 

Really though this is aimed at the actual resource behind the request, NOT the endpoint, the document, the invoice, the medical record, and not the request itself, because documents, invoices, etc. will have their own acls within them, or within a system.

**Comment by HaoK** [comment]
I haven't read this thread in its entirety since its quite long, but basically what Barry said is what I suggest as well.  The Resource parameter is meant for you to flow whatever specific info is necessary for your authorization logic.  If you need the Route data, that is where you would flow it in...

**Comment by Fosol** [comment]
Essentially I was hoping to have that logic in the AuthorizationHandler.  It looked like it would be so nice and clean that way.  Then my developers could write [CustomAuthorize(nameof(route))] and it would do it all for them.

Looks like I'll have to apply your suggestion of boilerplate code to authorize the operation.  I like your suggestion, I just wish I could have moved it up the chain.

**Comment by Fosol** [comment]
What would be nice is AuthorizeAttribute could automatically insert Resource information into the AuthenticationService.Authorize() method.  Then I could set what the Resource would be as an attribute value.

**Comment by blowdart** [comment]
But the attribute doesn't/can't know what the resource is, you need to load it first, from your service/database/whatever, hence it being imperative only.

**Comment by Fosol** [comment]
Technically I'm treating the resource as the operation/endpoint.  I have additional security/authorization that needs to be applied to what is actually done once they're allowed to use the endpoint/operation.

**Comment by Fosol** [comment]
Security Model
1) Can this user use the system?
2) Can this user use this endpoint?
3) What data/resource can this user perform an action on?

**Comment by Fosol** [comment]
Your framework is separating the connection between endpoint/operation and authorization.  You've essentially made authorization on the endpoint/operation static, or in other words the developer knows who can perform that operation.  Thus the develop can apply a static policy to the endpoint/operation that looks for a static claim definition.

I'm living in a dynamic world where I can't control those things.  The user does through administration/configuration.

**Comment by blowdart** [comment]
Taking a concrete example then, a health care invoicing system

1) Can a user use the system? Plain old auth
2) Can a user use this endpoint (i.e. access inovices)? Does the user have any value for the InvoiceAccess claim - at the controller level.
Optional 3 - Can a user perform that action? Then yes, you'd have a policy for each endpoint/action. Still only a single claim though.
4) Can the user perform the action against the resource behind their request? (i.e. can they update invoice number 73 to say it's paid) imperative resource/operation based.

**Comment by Fosol** [comment]
Your #2 goes back to my earlier comment.  I would have to create a policy and claim pair for every endpoint/operation.

I'm not against that solution.  I was looking for input and confirmation that I understand the framework.

I just worry about how many policies I'm going to have.  Which means a user would have tons of claims so that they would have configurable access for all the endpoints.

**Comment by blowdart** [comment]
Why would you have to have tons of claims? Endpoints go to a resource and an operation? So you'd have a single "Invoice" claim, with a value detailing their access, for example "CRUD". Now you have a single claim that applies to all resources of that type.

**Comment by Fosol** [comment]
Does a policy apply an OR or and AND to the required claims?

[Authorize(Policy = "InvoiceAccess")]
public IActionResult InvoiceAccess() {
}

The InvoiceAccess policy checks to see if the user has an InvoiceAccess claim.

One policy definition, one claim definition per endpoint.

I think you're saying a claim would be applied to the whole controller rather than the specific endpoint.  And then the endpoint would only check to see if they had a claim value detailing their access level.

**Comment by blowdart** [comment]
Multiple policies would be ANDed together.

**Comment by Fosol** [comment]
I really appreciate your feedback.  I think I have a working plan to go forward with Policies and Claims.

I still would have preferred for a more flexible AuthorizeAttribute.  If only to be able to pass additional information to it for authorization logic.  I realize you want that logic to be placed in policies and authorization handlers.  Pity they aren't self aware of what operation/endpoint called them.

**Comment by blowdart** [comment]
Just to follow up with this @Fosol. It was pointed out in another issue you can get to the route data and more in the Handle() if it's called from MVC (I apologise for not realising this)

      var controllerContext = context.Resource as Microsoft.AspNet.Mvc.AuthorizationContext;

The MVC AuthorizationContext contains RouteData and more.

**Comment by xavierjohn** [comment]
What if I want to authorize based on a ClientCertificate? I need the HTTP Request to get the ClientCert.
