### ISSUE TITLE
redirect_uri param is incorrect when SSL termination happens upstream of server running service

### ISSUE THREAD

**Issue by amattie** [aspnet/Security#401]
When putting servers behind a device that handles SSL termination and makes requests to the server via HTTP, the context's Request.Scheme is "http". Request.Scheme is used in [BuildRedirectUrl in AuthenticationHandler.cs](https://github.com/aspnet/Security/blob/ab4ba794e546074a573fbf76d9150ffcf9752c89/src/Microsoft.AspNet.Authentication/AuthenticationHandler.cs#L88). It's also used in [CurrentUri](https://github.com/aspnet/Security/blob/ab4ba794e546074a573fbf76d9150ffcf9752c89/src/Microsoft.AspNet.Authentication/AuthenticationHandler.cs#L58), and maybe other places.

The problem is that BuildRedirectUrl is used to build various URLs, like the challenge URLs, and so they get set to http instead of https. This cause issues when the redirect_uri gets set to an http URL when an https URL is registered with the service. Furthermore, it appears that Request.Scheme can't be easily overridable via custom middleware as a NotSupportedException is thrown, and so there's no easy workaround.

Can an option be added that'll override that URL to be overridden, or at least the scheme or scheme + host?

**Comment by Tratcher** [comment]
Overriding Request.Scheme is the recommended approach and should be fully supported as of beta6. There's even a middleware built to do this for you if your front end sets standard headers: https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNet.HttpOverrides/OverrideHeaderMiddleware.cs

**Comment by amattie** [comment]
Ah, that's cool. We were using beta5, so I guess that's why it wasn't working.
