### ISSUE TITLE
Authorize attribute/filter should return 401 when called from JavaScript

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Security#402]
In prior versions of MVC, the Authorize attribute would return a 401 if the header "X-Requested-With: XMLHttpRequest" was included. Either I don't know how to make this magic happen in MVC6 or it's poorly documented. It looks like there is no checking for that in the ChallengeResponse class. 

Please close if this can be addressed with a policy (which i'm happy to do if someone can point me in the right direction). 

For example, a controller might look like this:

```
  [Authorize]
  [Route("api/trips")]
  public class TripController : Controller
  {
    private ILogger<TripController> _logger;
    private IWorldRepository _repository;

    public TripController(IWorldRepository repository, ILogger<TripController> logger)
    {
      _logger = logger;
      _repository = repository;
    }

    [HttpGet("")]
    public JsonResult Get()
    {
      try
      {
        var trips = _repository.GetTripsByUsername(User.Identity.Name);

        return Json(AutoMapper.Mapper.Map<IEnumerable<TripViewModel>>(trips));
      }
      catch (Exception ex)
      {
        _logger.LogError("Failed to get the Trips", ex);

        Response.StatusCode = (int)HttpStatusCode.BadRequest;
        return Json("Failed");
      }

    }
}
```

When /api/trips is called without having logged in, it returns the body of the /auth/login page as the successful call to an AJAX call (e.g. from JavaScript). Do I need to specify something to get this behavior?

**Comment by HaoK** [comment]
Can you try adding a policy that lists your scheme in ActiveAuthenticationSchemes to see if that fixes things?

**Comment by PinpointTownes** [comment]
@shawnwildermuth which middleware are you using for authentication? The cookies middleware?
Katana used to return 200 responses (instead of 302) for unauthenticated AJAX calls, but this behavior was removed from ASP.NET 5.

https://github.com/aspnet/Security/issues/27

http://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Security.Cookies/Provider/DefaultBehavior.cs

**Comment by shawnwildermuth** [comment]
@HaoK,

Can you elaborate what you mean?

**Comment by HaoK** [comment]
What does your startup.cs look like, in terms of Auth?  Specifically Cookies/Bearer configuration is important along with any AuthZ configuration

**Comment by shawnwildermuth** [comment]
My Startup.cs looks like this currently:

https://gist.github.com/shawnwildermuth/87cbf15772ec511e4985

Of note, is that I'm trying to use MapWhen to configure Cookie Auth differently for Api and non Api

**Comment by shawnwildermuth** [comment]
Ok, I think I figured out how to make this work. If so, I'm happy with this workaround and we can close the issue as 'not fixing'. Any reason why I shouldn't recommend this:

      services.Configure<CookieAuthenticationOptions>(opt =>
      {
        opt.LoginPath = PathString.FromUriComponent("/Auth/Login");
        opt.Notifications = new CookieAuthenticationNotifications()
        {
          OnApplyRedirect = ctx =>
          {
            if (ctx.Request.Path.StartsWithSegments("/api"))
            {
              ctx.Response.StatusCode = 401;
            }
            else
            {
              ctx.Response.Redirect(ctx.RedirectUri);
            }
          }
        };
      });

**Comment by Tratcher** [comment]
Be careful that there are no calls to Map after this middleware, they will update Path and PathBase. Also note that OnApplyRedirect is called for different kinds of redirects (sign-in, sign-out, unauthorized, forbidden, etc.), so you may want to check where you're going before you send a 401.
