### ISSUE TITLE
Flow 'state' independently of the OIDC message for validation

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#404]
To fully validate an incoming OIDC message we need to make sure the 'state' parameter matches the one we sent. Can this be flown similar to the nonce (which already has issues)?

RE:
#278 
#390

**Comment by brentschmaltz** [comment]
Additionally, http://tools.ietf.org/html/rfc6819#section-5.3.5 specifies that the 'state' should be tied to the user-agent session.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/issues/278#issuecomment-132656395

**Comment by Tratcher** [comment]
Design: Use the same flow as the OAuth middleware's correlation ID, plus OIDC's unique cookie name.
