### ISSUE TITLE
Consider modifying OpenIdConnectAuthenticationOptions to use a single ISecurityTokenValidator

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#410]
Currently OpenIdConnectAuthenticationOptions.SecurityTokenValidators is a collection of validators, given that the specification requires a JWT, a collection here is not necessary.

Suggest change from ICollection<ISecurityTokenValidator> -> ISecurityTokenValidator.

**Comment by PinpointTownes** [comment]
Covered by https://github.com/aspnet/Security/pull/276#issuecomment-134710037

**Comment by Eilon** [comment]
Close when the PR goes in.
