### ISSUE TITLE
Revisit the OIDC/OAuth2 bearer middleware to stop re-throwing exceptions for invalid tokens

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#411]
By default, both the OIDC and the OAuth2 bearer middleware throw a bunch of security exceptions when a token is invalid. These exceptions are caught but the catch handler always re-throw them if you don't override the `AuthenticationFailed` notification and explicitly call `HandleResponse()` or `SkipToNextMiddleware()`, which is - obviously - a very bad thing, as you don't want to get a 500 response - or worse, an error page - for an invalid token.

In this case, 401 is the only response you want: https://tools.ietf.org/html/rfc6750#section-3.1

**Comment by Tratcher** [comment]
RE: https://github.com/aspnet/Security/issues/55

**Comment by PinpointTownes** [comment]
Alzheimer... :scream: 

Let's close this one then :smile:

**Comment by PinpointTownes** [comment]
Reopening this issue, since the bearer middleware still needs to be reworked to avoid throwing exceptions for invalid tokens, despite https://github.com/aspnet/Security/issues/55 being merged.

/cc @HaoK

**Comment by PinpointTownes** [comment]
Any chance we could prioritize this item?

**Comment by Tratcher** [comment]
I'd rather get a TryValidateToken from IdentityModel. @brentschmaltz?

**Comment by muratg** [comment]
@brentschmaltz can we stop throwing and return false?

**Comment by HaoK** [comment]
Please file an issue

**Comment by blowdart** [comment]
I'm actually OK with SecureDataFormat swallowing exceptions.

**Comment by Tratcher** [comment]
Yes, but I suppose it could also use a Try pattern as failures are expected.

**Comment by louislewis2** [comment]
Guys, having an issue like this one present for RC seems terrible. We are in preview with customers and due to this error, we are receiving a lot of flack. Can we please prioritise this fix?
