### ISSUE TITLE
WinHttpHandler is being used which is not cross-plat friendly

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Security#415]
MusicStore uses a lot of the Auth methods and when hosting on Linux or Mac trying to sign-in with one of these causes the server to crash because it is trying to use a windows dll.

See below for an example
https://github.com/aspnet/Security/blob/f3e03fbf2605da7d41bea2f346d9a33d608a3f8a/src/Microsoft.AspNet.Authentication.Twitter/project.json#L21

**Comment by Tratcher** [comment]
@blowdart Can we remove the BackchannelCertificateValidator's since they won't be supported on CoreCLR? Or just leave them ifdef'd for desktop?

**Comment by blowdart** [comment]
I'd prefer the ifdef. Just in case someone wants to do the right thing.

**Comment by Tratcher** [comment]
I've updated the code to use the generic HttpClientHandler, but we still need packages that actually contain the linux binaries. @davidfowl?
