### ISSUE TITLE
Microsoft.AspNet.Authentication.Facebook 1.0.0-Beta6 and Web.Api

### ISSUE THREAD

**Issue by kennyrulez** [aspnet/Security#416]
Hello everyone!

I Created a project using Asp.net 5 web.api template.
In order to mimic the authentication process via web.api, I adapted the methods I took from another MVC6 project.
When I raise the method **ExternalLogin** (via angularjs, httpost) to login with Facebook, after the ChallengeResult call the browser (chrome or firefox equally) return this error 
`XMLHttpRequest cannot load https://www.facebook.com/v2.2/dialog[...]. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:65167' is therefore not allowed access.`
If I try to complete the process manually, by coping the url the error says and pasting to the browsers, the operation completes and the **ExternalLoginCallback** is raised correctly and retrieve the correct information I need.

To be sure, I created a dummy project (the full application, the one that come with visual studio under ASP.NET 5 Preview Templates) in which I configured the same parameters for Facebook login: everything works perfectly.

So I think is related to how web.api handles http requests. 
Can anyone help me?

Is it possible to send the Access-Control-Allow-Origin by configuring Microsoft.AspNet.Authentication.Facebook 1.0.0-Beta6 in some way?

**Comment by Eilon** [comment]
The Facebook authentication package (and indeed all other auth packages, except for Bearer) are designed for interactive browser applications, rather than APIs.

We recommend using a Facebook JavaScript SDK to acquire a token for the client interactively and then use validation code from Facebook to validate the token in the API.
