### ISSUE TITLE
Reissue/refresh claims

### ISSUE THREAD

**Issue by henninga** [aspnet/Security#419]
Hi

When updating the user details, the clients does not automatically get the updated claims. How can I tell the idserver that I want to refresh the claims?

Using Cookie auth along with OpenId Connect.
Using version 3.0.1.0 of both client libraries.

Currently I'm attempting a dirty hack using AutenticationManager.AuthenticateAsync and AuthenticationManager.SignIn.

**Comment by Eilon** [comment]
The only way to do this is to log out and log back in. There is no general notification from auth servers to get updated claims.

**Comment by henninga** [comment]
It seems to work using the SignIn method. Probably not what it was supposed to do, but it reissues a new token and cookie.
