### ISSUE TITLE
Cookies now always redirects to Login/AccessDenied Paths

### ISSUE THREAD

**Issue by BreeeZe** [aspnet/Security#426]
This commit broke a pretty nice feature : https://github.com/aspnet/Security/commit/b883920befce4afaac89ec031d30d868a48df666?_pjax=%23js-repo-pjax-container , why was this changed?

I created an angular app which calls my mvc api and if it was not authenticated the cookie authentication automatically returned a 401 and my angular app recognised this so it displayed a login dialog. Now the api call receives a 302 and is redirected to a non existent api call resulting in a 404 and no login dialog :(

This feature was not broken, why was it 'fixed' ?

**Comment by Tratcher** [comment]
Yeah, it was broken. That 401 was being sent without a www-authenticate challenge which is invalid.

That said, Cookies shouldn't be used with WebApi anyways. You should be using Bearer or some other non-interactive login.

**Comment by BreeeZe** [comment]
That's too bad..

Why do you state "cookies should not be used in a webapi anyways"?
I agree that they should not be used for anything that involves retaining state on your api by means of a session or anything, but I am using claimbased authentication which uses cookies to communicate the claims to the server : https://msdn.microsoft.com/en-us/library/ff423674.aspx?f=255&MSPPError=-2147217396 , all microsoft tech, and also designed to be used with api's.

It used to work transparent and out of the box, but this change breaks it.

**Comment by leastprivilege** [comment]
because of XSRF

**Comment by BreeeZe** [comment]
Got a point there... :)

Well, I guess I have some work to do then, thanks for your time.
