### ISSUE TITLE
Consider dropping Authentication from all of the classes

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#428]
Since all of the Auth stuff lives under the Microsoft.AspNet.Authentication namespace already.  Why do we use Authentication in the class name everywhere?  It seems extra verbose and redundant.  Can we strip them across the board on the class names and only leave them on the Use/Add methods?

**Comment by blowdart** [comment]
Hurrah a grand renaming which breaks the world. 

Actually not a bad idea.

**Comment by Tratcher** [comment]
Like this?
TwitterOptions
TwitterMiddleware
TwitterHandler
TwitterDefaults
ITwitterEvents
TwitterEvents
UseTwitterAuthentication

How about the base classes? I think we'd have to leave those or else we'd end up with:
Handler
Middleware
Options
etc..

**Comment by HaoK** [comment]
Yeah so basically I think the general rule should be to only add Authentication when its needed to be clear, as opposed to just always tacking it on everywhere.

For the base classes I agree that those make sense to have the prefix as the names would be meaningless without it :)

**Comment by HaoK** [comment]
I'm willing to be the sacrificial lamb for this work if your plate is full, since this has always been a pet peeve of mine :)

**Comment by Tratcher** [comment]
We'll take it up with Triage.

**Comment by HaoK** [comment]
Note to self, need to rename ConfigureJwtBearer => AddJwtBearer to match the new naming pattern

**Comment by HaoK** [comment]
e8090a3176de5e6fc84be829be3a98f1e5ee8a5d
