### ISSUE TITLE
Consider making all the authentication events asynchronous

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#429]
There are multiple events that are still synchronous in the current code base.
Since we're no longer blocked by synchronous OSH callbacks, there's no reason not to make everything async.

**Comment by HaoK** [comment]
The async virus continues to spread :)

**Comment by PinpointTownes** [comment]
![ASYNC ALL THE THINGS!](http://cdn.meme.am/instances/500x/63126868.jpg)

**Comment by HaoK** [comment]
e8090a3176de5e6fc84be829be3a98f1e5ee8a5d
