### ISSUE TITLE
Authentication middleware collision when registering multiple instances

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#431]
Sometimes, I wonder if you really take my remarks into consideration: https://github.com/aspnet/Security/pull/377#issuecomment-129647531 :smile: 

As expected, removing the named options without introducing an appropriate workaround resulted in a total mess, that you can easily reproduce with the `SocialSample`:

![image](https://cloud.githubusercontent.com/assets/6998306/9672994/fb687eda-529f-11e5-9ded-204518d8285d.png)

**Comment by HaoK** [comment]
Oh I hear you, it was just buried in the avalanche of things that were broken.  The fix for this will probably be similar to Cookies and requires a new overload to be used when registering them multiinstance that takes an an instance of the options.  Thanks for bringing this up though :)  sounds like we have a sample for the generic OAuth but no real test coverage or usage!

**Comment by PinpointTownes** [comment]
> The fix for this will probably be similar to Cookies and requires a new overload to be used when registering them multiinstance that takes an an instance of the options.

This fix is too fragile, IMHO. Having an overload taking no parameter (and retrieving the options exclusively via DI) and a second one taking a delegate (that wouldn't extract the options from DI) would be far less surprising.

**Comment by HaoK** [comment]
I went with a single UseOAuth that requires an options instance to make things simpler.  Do you feel strongly that we need the DI default overload?

**Comment by HaoK** [comment]
We are going to fix this once and for all by standardizing on UseXyz(XyzOptions options) with middlewares not taking IOptions for now.

**Comment by brockallen** [comment]
So does this mean that middleware config in general will be moving away from ConfigureServices? I think this is a good idea (and hopefully MVC does the same).

**Comment by davidfowl** [comment]
@brockallen definitely not. First, MVC isn't even a middleware :smile: . Secondly it has a ton of services that need to be added to the container.

**Comment by brockallen** [comment]
Why is MVC not middleware?

**Comment by HaoK** [comment]
Routing is the middleware that UseMvc actually is registering in the pipeline

**Comment by HaoK** [comment]
This is similar to how UseIdentity actually is registering several instances of Cookies middleware, but there's no identity middleware either

**Comment by HaoK** [comment]
081577e4f4996082a4fc28ef77c84f54c7d04183
