### ISSUE TITLE
Port SaveTokensAsClaims to the OpenID Connect middleware

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#433]
In one of my recent PRs, I added a new `SaveTokensAsClaims` option for the OAuth2 generic middleware: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OAuth/OAuthAuthenticationOptions.cs#L111-L117.

Having a similar option for the OIDC client middleware would be great! :smile:

**Comment by Eilon** [comment]
@PinpointTownes do you want to send a PR for this?

**Comment by PinpointTownes** [comment]
Yep, you can count on me. I'll start working on it when @Tratcher is done with his PR.

**Comment by Eilon** [comment]
Awesome, thanks!

**Comment by Eilon** [comment]
@PinpointTownes let us know if you are getting close to submitting this - we have 1 week until the end of this release.

**Comment by PinpointTownes** [comment]
@Eilon nope, I haven't started working on it, but in my defense, @Tratcher merged his PR yesterday :smile: 

Unless you want to assign it to someone else, I'll try to submit a first prototype tomorrow.

**Comment by Eilon** [comment]
Oh no hurry at all. Just wanted to let you know our schedule!
