### ISSUE TITLE
Unable to generate JSON web tokens using a symmetric key

### ISSUE THREAD

**Issue by videege** [aspnet/Security#439]
Sorry if this is the wrong repo for reporting this issue, but I couldn't find any other repo that seemed more suited. 

I am encountering an issue when trying to write a JWT to a string using a `JwtSecurityToken` and `JwtSecurityTokenHandler` when utilizing a `SymmetricSecurityKey`.  When writing the token, an error occurs that says `IDX10640: Algorithm is not supported: 'http://www.w3.org/2001/04/xmldsig-more#hmac-sha256'`.  This SO question has a more complete example of the problem: http://stackoverflow.com/questions/32438878/dnx-core-5-0-jwtsecuritytokenhandler-idx10640-algorithm-is-not-supported-htt

I am using beta7 which ends up including the System.IdentityModel.Tokens.Jwt library, version 5.0.0-beta7-208241120.  

So far my best guess is that SymmetricSecurityKey (which as far as I can tell is closed source?) is still meant to be abstract, but in beta7 it does not appear to have any child classes - in previous versions it looks like there was an `InMemorySymmetricSecurityKey` but this is no longer present.

**Comment by Tratcher** [comment]
You want https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

**Comment by sandorfr** [comment]
Thanks for link @Tratcher. If you still have that need @videege I can share my workaround with you.

**Comment by videege** [comment]
@sandorfr That would be great - I could use a workaround.

**Comment by sandorfr** [comment]
@videege https://gist.github.com/sandorfr/4039d540b6b552154522
