### ISSUE TITLE
Certificate verification tests do not work on Mono

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#443]
All of the custom certificate verification code fails on Mono.
https://travis-ci.org/aspnet/Security/builds/79531362
CertificateSubjectKeyIdentifierValidator
CertificateSubjectPublicKeyInfoValidator - uses PInvokes
CertificateThumbprintValidator

The public key validator won't ever work because it PInvokes. The other two might work if we had appropriate certs to test with.

Consider removing these. Only Twitter uses them and removing them will allow us to remove the associated BackchannelCertificateValidator and related complexity on all the middleware. https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Twitter/TwitterAuthenticationOptions.cs#L66
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Twitter/TwitterAuthenticationMiddleware.cs#L101-L110

@blowdart @muratg

**Comment by blowdart** [comment]
This makes me sad, but I won't stand in its way.

**Comment by davidfowl** [comment]
@blowdart wrote this code right?

**Comment by blowdart** [comment]
Yes I did. It's horribly windows centric, and I doubt there's a way to make it cross platform as neither mono or core will expose wrappers for the cert structures I need without us producing X509Certificate3.

**Comment by davidfowl** [comment]
Let's nuke it then.
