### ISSUE TITLE
SecurityTokenValidator Error when deploying to Azure/IIS 10

### ISSUE THREAD

**Issue by Sharpiro** [aspnet/Security#448]
I created an ASP.net 5 application that uses bearer authentication through "OpenIdConnectServer".

I have a working example where the application will work when debugging on a local instance through VS.  But once I deploy to either Azure or IIS, I receive 500 errors upon response, "No SecurityTokenValidator available for token:" despite being 100% sure that the token is valid.

I also talked to the author of the author of "OpenIdConnectServer" and he pointed me to this line in your code and said an exception may be being thrown somewhere in the Identity Model stack.

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerAuthenticationHandler.cs#L134

**Comment by Sharpiro** [comment]
Figured out it was a different issue.

**Comment by vincez** [comment]
Sharpiro, what was the issue? I'm hitting the same error.

**Comment by Sharpiro** [comment]
i think i just had an issue where i wasn't updating my token authority URL when deploying to Azure.  So it was still trying to use the localhost address.
