### ISSUE TITLE
When an external login (e.g. Google) is denied, how do I recognize this?

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#451]
I was toying around with your library on ASP.NET 5 (beta 8-ish on nightlies) with little experience there so far, however the sample server project seems to works fine in general. I stripped out the Entity Framework part, as I'm planning to use a different data store later on.

Maybe I'm missing something obvious, but when I try to login with Google by doing a little

    http://localhost:51497/signin?returnUrl=http://localhost:51497/api/message

dance, I'll get to the consent page on Google, as expected. When I _deny_ the login there, I'm being redirected to 

    http://localhost:54540/signin-google?error=access_denied&state=CfDJ8M_e...foobar....Rdh5iyg#

and find the message

    Microsoft.AspNet.Authentication.Google.GoogleMiddleware: Warning: Invalid return state, unable to redirect.

in the debug output, along with a `500 Internal Server Error`.

Can you guide me on what's going on here and how I would react to that?

__________________________________________

Moved from https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/131

**Comment by PinpointTownes** [comment]
@HaoK @Tratcher I was sure we have a ticket tracking new hooks for the OAuth2 generic middleware but I can't find it. I guess we'd need an `OnAuthenticationFailed` equivalent here.

**Comment by Tratcher** [comment]
Yeah, the failure path for these is terrible.

**Comment by Tratcher** [comment]
RE: https://github.com/aspnet/Security/issues/55

**Comment by Anderman** [comment]
I have looked to the code and I think there are two problems. If the state is invalid you will get a 404 error. The case of the google URL could be resolved by changing some lines but there is no way to return to the callbackurl if the state variable is invalid

**Comment by HaoK** [comment]
We added a new OnRemoteError event:

Here's an example using the redirects putting the error message in the query string.
```
                options.Events = new OAuthEvents()
                {
                    OnRemoteError = ctx =>

                    {
                        ctx.Response.Redirect("/error?ErrorMessage=" + UrlEncoder.Default.UrlEncode(ctx.Error.Message));
                        ctx.HandleResponse();
                        return Task.FromResult(0);
                    }
                };
```

**Comment by Anderman** [comment]
Thanks. That's was missing!.

 I didn't have time to test your lastest build. But I did a quick scan a few days ago and I was missing this solution.
