### ISSUE TITLE
Enable dnxcore50 in Microsoft.AspNet.Authentication.Test

### ISSUE THREAD

**Issue by jmloeffler** [aspnet/Security#454]
In #420 I identified a number of items that are incompatible with `dnxcore50`.  We should address these so that the project supports coreclr.

* remaining Moq reference in OpenIdConnectMiddlewareTest
* XmlTextWriter reference in CookieMiddlewareTest
* Uri.GetLeftPart(...) in FacebookMiddlewareTest, GoogleMiddlewareTest, and MicrosoftAccountMiddlewareTest
* UriPartial in FacebookMiddlewareTest, GoogleMiddlewareTest, and MicrosoftAccountMiddlewareTest

**Comment by Eilon** [comment]
@jmloeffler I'm asking @Tratcher to follow up on anything remaining in this PR. Sorry for the delay in getting back to you!

**Comment by jmloeffler** [comment]
No problem.  I think people were waiting on me anyway.  There was some concern over one of the test changes I made and I got a bit discouraged about the whole thing when I saw this commit af14c99b465ef79bea85edd38421f7d08f7d371e.  But I'm happy to put more time into this one if having dnxcore support in the test projects is still desired.

**Comment by Eilon** [comment]
Yes, we definitely want the tests to run on `dnxcore50`!

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/commit/42cba79e01872a69165ffc957ddcb7d79adf63da
