### ISSUE TITLE
Make CookieAuthenticationDefaults and FacebookDefaults fields static readonly

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#457]
Many of them are currently `const`, which seems wrong.

**Comment by PinpointTownes** [comment]
The cookie middleware and the FB provider are not the only ones using constants: Google, JWT/Bearer, MSFT, OIDC, Twitter also all use constants.

I'm not saying constants are more appropriate, but they have at least one merit for the default schemes: you can use them with `AuthorizeAttribute`:

```csharp
[Authorize(ActiveAuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
```

**Comment by Eilon** [comment]
Is the attribute scenario a common one?

The problem with these consts is that they are logically *not* constant, so that bugs me :smile:

**Comment by Eilon** [comment]
Ah, we can keep the schemes `const` for this scenario. We should change just about everything else, though.

**Comment by brentschmaltz** [comment]
@Eilon @PinpointTownes const => will not change over time, readonly => fixed for this instance. Is this the reason to change to readonly?

**Comment by HaoK** [comment]
835903892771b9e833985c43bc3b967f66f31892
