### ISSUE TITLE
Rationalize notification context patterns

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#46]
The original batch of social auth middleware (Facebook, Twitter, etc.) all used notification contexts derived from `BaseContext`. The second round (WsFed, ODIC) tried to provide more direct shared context objects (`AuthenticationFailedNotification`). These should be rationalized.

**Comment by HaoK** [comment]
Don't think we'll have time to finish the full rationalization/cleanup, pinpoints PR needs to go in first which should happen this week.  Bumping to beta7

**Comment by Eilon** [comment]
Will be covered by https://github.com/aspnet/Security/issues/47.
