### ISSUE TITLE
Change all the XyzOptions.SystemClock properties to be EditorBrowsable(Never)

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#460]
And update all their doc comments to clearly say the are "For testing purposes only." (Some already make similar comments but aren't as clear.)

**Comment by Eilon** [comment]
Also need to check if `JwtBearerOptions.SystemClock` is even needed.

**Comment by brentschmaltz** [comment]
@Eilon the comment suggest this is just used for testing.

**Comment by HaoK** [comment]
835903892771b9e833985c43bc3b967f66f31892
