### ISSUE TITLE
Invalid/missing configuration shouldn't allow starting a new authorization request

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#467]
If the authentication server is offline, when I start the **client** sample on Windows or using a `1.0.0-beta8-15618` docker image (e.g. `sunside/aspnet:1.0.0-beta8-15618` from today), the client application renders the home page, but fails as soon as the `sign in` button is clicked.

This does a `GET /signin` which results in a `500 Internal Server Error`. On Kestrel, no exception output is given. On Windows (both HTTP Listener and IIS Express), an exception is printed stating that the authentication server's `.../.well-known/openid-configuration` cannot be reached.

If I try that again within a short time (or simply go to `/signin` manually), on both Windows and Linux Chrome detects an infinite redirect and terminates the request.

Fiddler states that the response is a `302 Found` with the Location

```http
Location: ?client_id=myClient&redirect_uri=http%3A%2F%2Fclient-dev.wundercart.de%3A53507%2Foidc&resource=http%3A%2F%2Fresource-dev.wundercart.de%3A54540%2F&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=6357820672...QxZTNh&state=CfDJ8BR0J...KPygjHp62icn0JQ
```

The console is then spammed with

```
client_1 | warning : [Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware] OIDCH_0036: Uri.IsWellFormedUriString(redirectUri, UriKind.Absolute) returned 'false', redirectUri is: '?client_id=myClient&redirect_uri=http%3A%2F%2Fclient%3A53507%2Foidc&resource=http%3A%2F%2Fresource%3A54540%2F&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=635782067223014590...MjMtZmUxMjgwODhkMzY2&state=CfDJ8BR0JH1siad...PGKXve4TivaWEs_XwBKydF3HY'.
client_1 | warning : [Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware] OIDCH_0036: Uri.IsWellFormedUriString(redirectUri, UriKind.Absolute) returned 'false', redirectUri is: '?client_id=myClient&redirect_uri=http%3A%2F%2Fclient%3A53507%2Foidc&resource=http%3A%2F%2Fresource%3A54540%2F&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=635782067223118170....YzAtMDM5ZDBjMDdkY2My&state=CfDJ8BR0JH1siad...WFEmnNDv9xfV3wWCi1bA6t9a8'.
client_1 | warning : [Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware] OIDCH_0036: Uri.IsWellFormedUriString(redirectUri, UriKind.Absolute) returned 'false', redirectUri is: '?client_id=myClient&redirect_uri=http%3A%2F%2Fclient%3A53507%2Foidc&resource=http%3A%2F%2Fresource%3A54540%2F&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=635782067223231680...iNWUtYjMyOWZlNzcxY2Fi&state=CfDJ8BR0JH1siad5J...NhLwk4HBXaGWHLJNOIFZ3sE'.
client_1 | warning : [Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware] OIDCH_0036: Uri.IsWellFormedUriString(redirectUri, UriKind.Absolute) returned 'false', redirectUri is: '?client_id=myClient&redirect_uri=http%3A%2F%2Fclient%3A53507%2Foidc&resource=http%3A%2F%2Fresource%3A54540%2F&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=635782067223231680...iNWUtYjMyOWZlNzcxY2Fi&state=CfDJ8BR0JH1siadL..._NhLwk4HBXaGWHLJNOIFZ3sE'.
```

In `Startup.cs` the middleware is configured with

```csharp
app.UseOpenIdConnectAuthentication(options => {
    options.AuthenticationScheme = OpenIdConnectDefaults.AuthenticationScheme;

    options.ClientId = "myClient";
    options.ClientSecret = "secret_secret_secret";
    options.RedirectUri = "http://client:53507/oidc";
    options.PostLogoutRedirectUri = "http://client:53507/";

    options.Authority = "http://server:54540/";
    options.Resource = "http://resource:54540/";

    // ...
```

This generally works at least on Windows when both servers are on.

_______________

Moved from https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/136.

**Comment by PinpointTownes** [comment]
@Tratcher the `Location` header (`Location: ?client_id=myClient...`) missing the issuer address seems to indicate the OIDC configuration was not correctly retrieved (as expected if the server is offline)... but surprisingly, this doesn't prevent the OIDC middleware from trying to create a new authorization request on subsequent calls.

Has something changed in Wilson that could allow a null configuration instead of throwing an exception?

/cc @brentschmaltz @Tratcher @sunsided

**Comment by Tratcher** [comment]
@tushargupta51?

**Comment by tushargupta51** [comment]
@PinpointTownes @Tratcher I ran a quick test on ConfigurationManager trying to retrieve configuration from https://login.windows.net/throw.onmicrosoft.com/.well-known/openid-configuration (which does not exist), it threw the expected error: IDX10803: Unable to obtain configuration....

**Comment by PinpointTownes** [comment]
Make sure you call the configuration manager a second time since it only appears on subsequent calls.

I just tried the built-in OIDC sample and the bug is exactly where I thought:

![image](https://cloud.githubusercontent.com/assets/6998306/10062281/37e7ed84-6261-11e5-904e-51ff8403d4d3.png)

**Comment by PinpointTownes** [comment]
@Eilon this bug is critical. Can we prioritize it for beta8?

**Comment by Eilon** [comment]
@PinpointTownes yeah we have a bug triage meeting tomorrow afternoon and we'll discuss this one as well.

**Comment by tushargupta51** [comment]
@PinpointTownes I was able to reproduce the issue when calling twice, it was because of the configuration manager trying to return stale configuration (which was null). I fixed it, it will make it in beta8. The fix is in beta8fixes2 branch.

**Comment by Tratcher** [comment]
Closing as external.

**Comment by PinpointTownes** [comment]
The root cause is indeed external, but I'm convinced we should add new checks in the middleware itself to avoid redirecting to a null/invalid issuer address.
