### ISSUE TITLE
Fix package descriptions with proper casing

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#468]
For this project: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.JwtBearer/project.json

Change from:
> ASP.NET 5 middleware that enables an application to receive a Jwt bearer token.

To:
> ASP.NET 5 middleware that enables an application to receive an OpenID Connect bearer token.

And for this project: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OpenIdConnect/project.json
Change from:
> ASP.NET 5 middleware that enables an application to support OpenIdConnect authentication workflow.

To:
> ASP.NET 5 middleware that enables an application to support the OpenID Connect authentication workflow.

**Comment by muratg** [comment]
@Tratcher feel free to move to RC1 if you're not touching said projects for other bugs.

**Comment by Eilon** [comment]
I think @HaoK is fixing one of these in his current PR. Feel free to poach this issue.

**Comment by Eilon** [comment]
Fixed in 3c925fc4bf4ae831ee85093dd738adf172b9e704.
