### ISSUE TITLE
Rename OpenIdConnect JWT bearer events

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#474]
* `ApplyChallenge` --> `SetAuthenticationHeader`
* `MessageReceived` --> `ReceivingToken`
* `SecurityTokenReceived` --> `ReceivedToken`
* `SecurityTokenValidated` --> `ValidatedToken`

Also need to rename methods/contexts/etc.

**Comment by HaoK** [comment]
852f44a3691c02c379b586fe7ef3dc0cb4cea6ab
