### ISSUE TITLE
Rename OAuthEvents and ITwitterEvents

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#476]
* `ApplyRedirect` --> `RedirectToAuthorizationEndpoint`
* `Authenticated` --> `CreatingTicket`
* `ReturnEndpoint` --> `SigningIn`

Also need to change the properties/method names, and the context types they use.

Related:
* https://github.com/aspnet/Security/issues/474
* https://github.com/aspnet/Security/issues/459

**Comment by HaoK** [comment]
https://github.com/aspnet/Security/pull/482
