### ISSUE TITLE
Authorization API cleanup

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#480]
* Rename `AuthorizeAttribute.ActiveAuthenticationSchemes` to `AuthorizeAttribute.AuthenticationSchemes`
* Move all Requirements types to a `.Infrastructure` namespace
* Move all `PassThroughAuthorizationHandler` to a `.Infrastructure` namespace

**Comment by HaoK** [comment]
0eaec216b10981fc4b55b5539cf9768526826043
