### ISSUE TITLE
Add a RequireHttps property when migrating to Wilson beta8

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#485]
In a recent change in Wilson, `HttpDocumentRetriever` was updated to reject non-HTTPS metadata addresses. Overriding the default configuration manager to allow HTTP for testing scenarios is possible but a real PITA from a usability perspective: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/samples/Mvc/Mvc.Server/Startup.cs#L50-L57

I suggest adding a new `RequireHttps` (or `AllowInsecureHttp`) property to both the OIDC and the bearer middleware to control whether the instantiated configuration manager should support HTTP or not.

This property could also be used to reject non-HTTPS addresses earlier in the middleware itself, specially since there's a bug in Wilson that hides the exception thrown when you try to use a HTTP endpoint and makes this new requirement really hard to discover: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/253.

@Eilon is migrating to Wilson beta8 planed for ASP.NET 5 beta8?

**Comment by leastprivilege** [comment]
I really don't understand why this HTTPs by default requirement was added - there are some valid scenarios where HTTP is OK - and it is up to the developer to set the right URL.

lol for `AllowInsecureHttp` ;)

Please don't start to do the same for redirect_uri or authority.

**Comment by leastprivilege** [comment]
but anyways - please make that at least easily configurable.

**Comment by Eilon** [comment]
Yes, ASP.NET beta8 will use Wilson beta8. If this is what I think it is, I recall seeing some spec verbiage around the requirement of HTTPS.

@brentschmaltz @Tratcher @blowdart do any of you recall what this was about?

**Comment by blowdart** [comment]
Pinpoint pretty much explains it. The OIDC spec requires HTTPS return points. That's a PITA for dev. So add a "DisableHttpsRequirement" property. This would then be checked when the URLs are configured, and an exception thrown as appropriate to the settings.

**Comment by Eilon** [comment]
@Tratcher can you take a look at this?

**Comment by stephenstroud** [comment]
+1

**Comment by brentschmaltz** [comment]
@PinpointTownes @leastprivilege @blowdart This is a 'secure by default' change. Unlike, fed metadata which can be signed, normally OIDC metadata is not signed. Hence, https required by default. I agree we need to make it easier to turn off.
