### ISSUE TITLE
TwitterAuthenticationOptions.BackchannelCertificateValidator unavailable on core 5.0

### ISSUE THREAD

**Issue by Banashek** [aspnet/Security#487]
Apologies in advanced if this is filed in the wrong project. If it is, let me know where it should go and I'll close it here and open it in the appropriate location.

I'm on windows 10 with vs2015 community with beta-7 currently.

Was attempting to set up twitter login and ran into the following issue:
http://stackoverflow.com/questions/25011890/owin-twitter-login-the-remote-certificate-is-invalid-according-to-the-validati

I attempted to implement the fix, but the BackchannelCertificateValidator option shows as unavailable in dnxcore50. After removing the dnxcore50 context from project.json, the program builds and runs fine.

I'm not sure if there is a better way to go about fixing the issue other than manually setting the certificate (seems unstable), or if this is the appropriate way for a production app to handle this kind of issue.

At the moment, I had to remove dnxcore50 as one of my targets (I'd like to be able to target it in the future). 

Is there a way that either I can fix the issue without manually setting the BackchannelCertificateValidator or without removing the dnxcore50 reference?

**Comment by Tratcher** [comment]
Cert pinning was never enabled for CoreCLR, so you can just `#if !DNXCORE50` around that code.

In beta8 we removed the default cert pinning and BackchannelCertificateValidator. If you want to still do cert pinning then you would set BackchannelHttpHandler directly with the required config.

**Comment by Banashek** [comment]
Ah perfect.

I had assumed that the issue was present in both frameworks, and therefore needed to be handled in both.

Thanks for the prompt and helpful response!
