### ISSUE TITLE
Add Logging to Authn and Authz

### ISSUE THREAD

**Issue by rynowak** [aspnet/Security#491]
From offline logging discussion:

- Add Verbose logging where it can be useful for debugging
- Time box to 2 dev-days maximum
- Use EventIds at each logging statement
- Update any existing logging to include an EventId

Relevant logging points we want to include for sure:
```
    Authn:
        -Identity Authenticated - Information
        -SignIn/SighOut - Information
        -Challenge - Information
        -Access Denied - Information

    Authz:
        - Granted/Denied - Information
```

**Comment by muratg** [comment]
FYI @rynowak

**Comment by muratg** [comment]
FYI @Tratcher

**Comment by muratg** [comment]
@HaoK Will you be able to tackle this early in RC?

**Comment by HaoK** [comment]
Yep

**Comment by Eilon** [comment]
We have security repo triage this afternoon.

**Comment by HaoK** [comment]
e0464c950853909aa3491c65b519db47bb22679f
