### ISSUE TITLE
resource-based AuthorizationHandler is invoked for other resource types.

### ISSUE THREAD

**Issue by MikeWasson** [aspnet/Security#494]
I have two authZ handlers that derive from `AuthorizationHandler<TRequirement, TResource>` with different resource types:
 
    services.AddInstance<IAuthorizationHandler>(new FooAuthorizationHandler());
    services.AddInstance<IAuthorizationHandler>(new BarAuthorizationHandler());
 
The AuthorizationService runs both handlers, passing in null when the resource type does not match. Is this the intended behavior? If so, I need to check for null resource and exit.

**Comment by HaoK** [comment]
defc9faac06958b89ad3bf8fa28a135265cef46f
