### ISSUE TITLE
Returning 403 does not redirect to AccessDeniedPath

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aspnet/Security#499]
Returning `new HttpStatusCodeResult(StatusCodes.Status403Forbidden)` from an action does not redirect to a "forbidden" url. I am using cookie authentication in beta7.

**Comment by Eilon** [comment]
@HaoK can you log a bug in MVC to create a forbidden result that sends a forbid response + 403?

**Comment by HaoK** [comment]
https://github.com/aspnet/Mvc/issues/3242

**Comment by herecydev** [comment]
Is this still an issue for RC1 @HaoK ?

Given the following middleware configuration:

```c#
app.UseCookieAuthentication(options =>
{
	options.AutomaticAuthenticate = true;
	options.AutomaticChallenge = true;
});
app.UseOpenIdConnectAuthentication(options =>
{
	options.Authority = Configuration.Get<string>("AzureAd:Authority");
	options.ClientId = Configuration.Get<string>("AzureAd:ClientId");
	options.AutomaticAuthenticate = true;
	options.AutomaticChallenge = true;
	options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
});

//MVC
```

When the MVC returns a 403 this is "caught" and made into a 302 redirect to the login page (causing endless redirects). My assumption was it would use the default `AccessDeniedPath` but it seems to ignore it.

**Comment by Eilon** [comment]
@Tratcher any idea on this?

**Comment by Tratcher** [comment]
That's odd, we don't intercept 403s, only 401s.
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L150

**Comment by herecydev** [comment]
I've made the [most simple gist]()https://gist.github.com/herecydev/b729403448943f3df5229767e4981c12 I could to demonstrate this.

Given an end user that does not have the claim there, I'm seeing endless redirects.

**Comment by Tratcher** [comment]
Oh, MVC isn't setting a 403 anywhere in your gist. It's failing to authorize which triggers another login flow. I think you're hitting this issue: https://github.com/aspnet/Security/issues/667

**Comment by herecydev** [comment]
Ah okay, perhaps I made some assumptions about this, so sorry about that. How exactly does the Authorize attribute work if it doesn't return a 403?

**Comment by Tratcher** [comment]
It invokes HttpContext.Authentication.Challenge. For authenticated but not authorized Cookies or Bearer this can produce a 403, but for most of the other auth middleware this causes an infinite loop.

**Comment by herecydev** [comment]
Thanks, I'll keep tabs on the related issue. Hoping this will go into RC2!

**Comment by Tratcher** [comment]
No, it's scheduled for post RC2. We're out of time for RC2 features.
