### ISSUE TITLE
401 and 403 Behavior in CookieAuthenticationHandler

### ISSUE THREAD

**Issue by easyt** [aspnet/Security#502]
The CookieAuthenticationHandler class always redirects a user on unauthorized and forbidden. It doesn't seem like there is a way to tell it to use the base implementation of sending back a 401 and 403. Is there a way to get that behavior (without a hack) or is there another auth implementation we should be using?

**Comment by Tratcher** [comment]
I assume this is for a WebApi or similar? You should be using Bearer, Windows Auth, Basic, etc.. Cookie auth is for user-interactive flows.

**Comment by MaximBalaganskiy** [comment]
It would be a waste of a good cookie :) to use tokens just for that.  This achieves the goal.

````
services
                .Configure<CookieAuthenticationOptions>(o =>
                {
                    o.Notifications = new CookieAuthenticationNotifications()
                    {
                        OnApplyRedirect = c =>
                        {
                            if (c.Request.IsAjaxCall() && c.Response.StatusCode == 200)
                                c.Response.StatusCode = 401;
                            else
                                c.Response.Redirect(c.RedirectUri);
                        }
                    };
                });
````

**Comment by easyt** [comment]
Thanks, guys. I'm going to go with @MaximBalaganskiy on this one.

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Security/issues/508.
