### ISSUE TITLE
AuthZ Namespace

### ISSUE THREAD

**Issue by glatzert** [aspnet/Security#504]
Perhaps I do not see "the big picture" or my understanding of the naming is not that good, but looking into ASP.NET and especially Logging and DependencyInjection makes me assume that features, which are not "Web-only" get a namespace like Microsoft.Framework.Logging.
Now I am wondering about Microsoft.AspNet.Security.Authorization: since I'd assume that authorization is something which is probably used throughout multiple application layers, I would expect that in Microsoft.Framework.Security.AuthZ or something similar.
Am I missing something? Or are we supposed to stick to PrincipalPermissions in non-web layers?

**Comment by Eilon** [comment]
The authorization types are indeed intended for ASP.NET scenarios only.
