### ISSUE TITLE
Cannot set null LoginPath in CookieAuthenticationOptions to prevent redirect.

### ISSUE THREAD

**Issue by michaelbudnik** [aspnet/Security#505]
Hi.

There is no way of setting the `LoginPath` to null or empty to get the 401 response code rather then redirect.

The null value gets ovverriden in the `CookieAuthenticationMiddleware` constructor [here](https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationMiddleware.cs#L42) with the default one taken from `CookieAuthenticationDefaults`.

What's the point on checking for null value in `CookieAuthenticationHandler` [here](https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationHandler.cs#L292) when there is no way to assign a null or empty string to this field?

**Comment by dvdcrr77** [comment]
https://github.com/aspnet/Security/issues/502

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Security/issues/508.
