### ISSUE TITLE
Update the call to OpenIdConnectProtocolValidator.ValidateUserInfoEndpointResponse

### ISSUE THREAD

**Issue by tushargupta51** [aspnet/Security#506]
There will a small OM change in wilson: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/263. Update the API to react to that.

**Comment by brentschmaltz** [comment]
Change is in: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/2b2969149fb73f0cdde07a2064eaa2f8744fd312

**Comment by Eilon** [comment]
Need to update Wilson dependencies to RC1.
