### ISSUE TITLE
Cookies: HTTP 401 always turns into 302

### ISSUE THREAD

**Issue by kpocza** [aspnet/Security#508]
When using cookie authentication the HTTP 401 response always turns into HTTP 302 Redirect to Accounts/Login.
I setup the authentication this way:

```c#
            app.UseCookieAuthentication(options => 
            {
                options.CookieHttpOnly = false;
                options.ExpireTimeSpan = System.TimeSpan.FromMinutes(60);
                options.SlidingExpiration = true;
                options.CookieName = "ThriotMgmtAuth";
                options.AutomaticAuthentication = true;
            });
```

I've tried to set the LoginPath to empty, since the engine redirects only when there is a valid login url. However it's already empty.

As I see the CookieAuthenticationMiddleware class updates the LoginPath with the default value when it's empty.

I think this is not the right behavior in every situations. In my case I have a cookie-protected API and call it from AngularJS from a browser besides other places.

Further details:
https://github.com/kpocza/thriot/tree/master/Service/Management/Thriot.Management.WebApi

**Comment by PinpointTownes** [comment]
(duplicate of https://github.com/aspnet/Security/issues/505)

+1. I completely understand it's a way to deter us from using cookies authentication for Web API endpoints, but not being able to disable these redirects is evil.

/cc @HaoK

**Comment by kpocza** [comment]
I've created a workaround for beta7.

New middleware based on the built-in cookieauth middleware:
+++
    public class WorkaroundCookieAuthenticationMiddleware : CookieAuthenticationMiddleware
    {
        public WorkaroundCookieAuthenticationMiddleware(RequestDelegate next, IDataProtectionProvider dataProtectionProvider, ILoggerFactory loggerFactory, IUrlEncoder urlEncoder, IOptions<CookieAuthenticationOptions> options, ConfigureOptions<CookieAuthenticationOptions> configureOptions) : 
            base(next, dataProtectionProvider, loggerFactory, urlEncoder, options, configureOptions)
        {
            ((CookieAuthenticationNotifications) Options.Notifications).OnApplyRedirect = context =>
            {
                context.Response.StatusCode = 401;
            };
        }
    }
+++

Registration:
+++ 
app.UseMiddleware<Thriot.Management.WebApi.Auth.WorkaroundCookieAuthenticationMiddleware>(
                new ConfigureOptions<CookieAuthenticationOptions>(options =>
                {
                    options.CookieHttpOnly = false;
                    options.ExpireTimeSpan = System.TimeSpan.FromMinutes(60);
                    options.SlidingExpiration = true;
                    options.CookieName = "ThriotMgmtAuth";
                    options.AutomaticAuthentication = true;
                }) {Name = ""});
+++

It works seamlessly for me.

**Comment by Tratcher** [comment]
@kpocza Your new middleware is redundant, you could have set Options.Notifications.OnApplyRedirect from app.UseCookieAuthentication like this in OAuth: https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L131

**Comment by blowdart** [comment]
So hopefully we're are aware of why using cookie authentication for webapis is a bad idea, right? It's obvious however that making a leap to a non-automatic auth like bearer tokens is too much to bear (no pun intended) for some situations.

I propose the following compromise.

We won't go back to the very weird Katana behaviour, instead if we detect a local ajax request, i.e. something with an X-Requested-With header value of XMLHttpRequest and you have cookie auth wired up and it has run for the request (either via it being automatic, or requested as part of the Authorize types) then we will not do a redirect. We will return raw 401 or 403 and you must handle appropriately. 

This will happen even if you have a LoginPath set.

I'm open to arguments saying we should put this behind a config switch so folks could get the redirect if they wanted (UseReallyBadAuthSchemeForAjaxAndRedirect = true would work :satisfied:)

**Comment by kpocza** [comment]
I'd definitely suggest introducing some config switch. Most of the times it's true that for AJAX request 401 may be better than 302. But it's not even obvious that 302 is the best way for other resource requests in every case.
I could imagine to have a flags enum for 401 with values like: None, Ajax, NonAjax, All. With default None. There might be cases when the situation cannot be decided based on some standard headers (X-Requested-With) so I could image an optional lambda expression that gets the request parameters and decides the status code based on these.

**Comment by davidfowl** [comment]
We used to have this in the cookie middleware in katana. What happened to it?

**Comment by HaoK** [comment]
We decided to remove this functionality during design review a while ago

**Comment by Tratcher** [comment]
@davidfowl Not quite, Katana returned 200.
http://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Security.Cookies/Provider/DefaultBehavior.cs

**Comment by PinpointTownes** [comment]
IMHO, removing these checks would be enough since you'd just have to set `LoginPath` to `PathString.Empty` to disable the 401 -> 302 conversion:

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Cookies/CookieAuthenticationMiddleware.cs#L64-L75

**Comment by blowdart** [comment]
Here's the other problem; what scheme do you expect in the 401? To match the HTML spec it needs one. Cookie in this case isn't actually valid.

**Comment by PinpointTownes** [comment]
I suggest `Interactive` (though the actual value doesn't really matter) :smile:

**Comment by Eilon** [comment]
In the default implementation of the Challenge event handler it should detect an AJAX request and return the original status code. Detecting an AJAX request involves checking the `X-Requested-With` header value to see if it is `XMLHttpRequest`.

The response for AJAX calls should not modify the body, but should have a header indicating the login page in case a client wishes to do a browser redirect. E.g. could use the `Location` header for this, or perhaps a custom header if the RFC semantic of the `Location` header don't match what we want.

**Comment by MaximBalaganskiy** [comment]
@blowdart Consider a scenario when web api is only consumed from a dynamic web page which was served under cookie authorization. Why is it bad, could you please be more specific? Everything just works in this case except that redirect which is fixable in 10 lines of code. I definitely don't want to write tons of code (since, surprise, we don't have token server anymore). And then there is a problem of synchronisation between cookies and those tokens. I don't even want to think about all the aspects of this problem.

Calling web api from other clients like mobile or SPAs definitely needs tokens though.

**Comment by blowdart** [comment]
@MaximBalaganskiy it's bad because you are wide open to Cross Site Request forgery calls. There's nothing to stop an attacker doing a simple form submit to your webapi, unless you're writing tons of code to pull the csrf token out of a form, put it into a header, then check it in the controller.

Your dynamic web page is a SPA, it's just one with lots of pages.

**Comment by MaximBalaganskiy** [comment]
@blowdart That is exactly what I am doing. And it's not a lot of code actually - all ajax requests come through a class which is pulling a verification token from a page. Some frameworks - Telerik for one - even do the same for you.

**Comment by blowdart** [comment]
And then how are you verifying it? It's ugly manual labour which you end up having to write, and people don't *know* to write it, which is why we recommend bearer, it's *safe* by default. We like safe by default, even if it is more work.

**Comment by MaximBalaganskiy** [comment]
MVC verifies it when I put ValidateAntiForgeryToken on an api action

**Comment by blowdart** [comment]
MVC won't pick it out of a header though, which should be where it ends up in an ajax call. For forms, sure, that attribute works. Bearer protects against CSRF because it is explicit.

**Comment by MaximBalaganskiy** [comment]
I just checked. It does look for the verification token and returns "The required antiforgery form field \"__RequestVerificationToken\" is not present.". Why wouldn't it? These actions are same as view actions.

**Comment by blowdart** [comment]
Ah sorry, I meant it won't succeed! Which means you need to remove the check for ajax calls, and lo, CSRF :)

**Comment by MaximBalaganskiy** [comment]
Sure, if an action is going to be called from browser AND mobile then it's not that simple.

**Comment by blowdart** [comment]
Indeed. Or from the browser via ajax. Which is why we tend to say use bearer, because it's safer.

**Comment by geertendoornenbal** [comment]
It would be nice if the documentation on security could be extended on how to include Bearer tokens and use that for authorization. I want to change the current cookie authentication for our WebApi, but I can't find any proper explanation on how to do it easily in ASP.NET 5.

**Comment by muratg** [comment]
POR: Detect if AJAX for all redirects, and if it is, we'll leave it the status code appropriate code(401/403) and the appropriate location header.

**Comment by HaoK** [comment]
1d2c6ba1223748df02a879622e8deb6ac23db5b7

**Comment by michaelbudnik** [comment]
@HaoK How does this solve #505 ?

I think there should be an option to completely disable redirects regardless of AJAX or not.

**Comment by PinpointTownes** [comment]
Can't agree more :+1: : https://github.com/aspnet/Security/pull/543#issuecomment-150376689

**Comment by cda-1** [comment]
For OP's scenario, you can do the following, which I learned from [the awesome Pluralsight course "Building a Web App with ASP.NET 5, MVC 6, EF7 and AngularJS"](https://app.pluralsight.com/library/courses/aspdotnet-5-ef7-bootstrap-angular-web-app/table-of-contents).

```C#
    services.AddIdentity<User, Role>(config =>
    {
        config.Cookies.ApplicationCookie.Events = new CookieAuthenticationEvents
        {
            OnRedirectToLogin = ctx =>
            {
                if (ctx.Request.Path.StartsWithSegments("/api") &&
                    ctx.Response.StatusCode == (int) HttpStatusCode.OK)
                {
                    ctx.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                }
                else
                {
                    ctx.Response.Redirect(ctx.RedirectUri);
                }
                return Task.FromResult(0);
            }
        };
    })
    .AddEntityFrameworkStores<ApplicationDbContext, int>()
    .AddDefaultTokenProviders();
