### ISSUE TITLE
Authorization based on action parameters

### ISSUE THREAD

**Issue by djanosik** [aspnet/Security#509]
I like the new `AuthorizeAttribute`, authorization policies and requirements. But there is one thing I find impossible to implement. Consider the following action method:
```c#
[Authorize("SomePolicy")]
public IActionResult AttachValue(long accountId) 
{
    ...
}
```
It serves to attach values to an account with the given ID. I want to create a requirement where I can check whether the authenticated user has access to this account. But I can't find a way to access action method parameters from within the requirement.

Is there any solution?

**Comment by DAllanCarr** [comment]
This was posted in another issue by @XplMarcel
https://github.com/aspnet/Security/issues/500

  var controllerContext = context.Resource as Microsoft.AspNet.Mvc.AuthorizationContext;
  return controllerContext?.RouteData?.Values["paramValue"]?.ToString();

**Comment by djanosik** [comment]
Well, it's an ugly solution and is not really helpful. What I mean is to have access to argument values after model binders do their job.

**Comment by DAllanCarr** [comment]
@djanosik  I agree that was not really helpful.

**Comment by Eilon** [comment]
@blowdart

**Comment by Eilon** [comment]
@blowdart

**Comment by Eilon** [comment]
@blowdart

**Comment by blowdart** [comment]
Binding doesn't happen till long after authorization, and parameters don't exist when authorization happens, they are only available inside the actual controller method. So declarative authorization simply will not work for you. 

For this sort of situation we have resource based authorization. The scenario here is you're getting a model sent to you, or a reference to a resource, which you then load. For example in your controller you'd end up loading the account entity that accountId refers to, then acting upon it.

First off you define the imperative operations you might need, for example

```c#
    public static class Operations
    {
        public static OperationAuthorizationRequirement Create = 
            new OperationAuthorizationRequirement { Name = "Create" };
        public static OperationAuthorizationRequirement Read = new 
            OperationAuthorizationRequirement   { Name = "Read" };
        public static OperationAuthorizationRequirement Update = new 
            OperationAuthorizationRequirement { Name = "Update" };
        public static OperationAuthorizationRequirement Delete = new 
            OperationAuthorizationRequirement { Name = "Delete" };
    }
```

Then you write a resource based handler;

```c#
    public class AccountAuthorizationHandler : 
        AuthorizationHandler<OperationAuthorizationRequirement, Account>
    {
        protected override void Handle(AuthorizationContext context, 
            OperationAuthorizationRequirement requirement, Account resource)
        {
            // User is in context.User
            // Make decisions based on the resource, the user and the operation
            
            // If the operation should succeed call
            context.Succeed(requirement);

           // otherwise
           context.Fail();
        }
    }
```

Inside ConfigureServices() you'd register it

```c#
    services.AddInstance<IAuthorizationHandler>(
        new Authorization.AccountAuthorizationHandler());
```

Then in your controller actions you can call

```c#
    var account = accountDb.Load(accountId);
    if (await authorizationService.AuthorizeAsync(User, account, Operations.Update))
    {
        return View();
    }
    else
    {
        return new HttpStatusCodeResult(403);
    }
```

The return value will be simplified after beta 8
