### ISSUE TITLE
Consider splitting AutomaticAuthentication

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#513]
AuthenticationOptions.AutomaticAuthentication actually covers two concepts, authenticate (set the user) and challenge (handle 401s).
```c#
/// If true the authentication middleware alter the request user coming in and
/// alter 401 Unauthorized responses going out. If false the authentication middleware will only provide
/// identity and alter responses when explicitly indicated by the AuthenticationScheme.
```
Cookie, Bearer, etc. support both, but facebook, OIDC, etc. only support automatic challenges.

Note that if we did separate the flags it would mean you could auto-authenticate (which is non-invasive) without auto-challenging, possibly alleviating some of the complaints against the cookie middleware.

**Comment by HaoK** [comment]
Done as part of 409b50269a9d85618a31f84a3ffc2868abb3eeea
