### ISSUE TITLE
[Authorization] Evaluating a non-existent policy returns "false"

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#514]
When doing this:

```
if (await _authz.AuthorizeAsync(User, "does_not_exist"))
```

I get back false. 

Doing the same in an Authorize attribute - it throws an exception.

**Comment by blowdart** [comment]
@HaoK can you slip this into beta8? I'd agree with throwing the exception in imperative checks too

**Comment by Tratcher** [comment]
No @blowdart, beta8 is 'done'.

**Comment by muratg** [comment]
Moving to RC1 per internal discussion.

**Comment by HaoK** [comment]
0eaec216b10981fc4b55b5539cf9768526826043
