### ISSUE TITLE
Multiple resource-based authorization handlers in ASP.NET MVC 6

### ISSUE THREAD

**Issue by BadriL** [aspnet/Security#515]
I want to have two resource-based authorization handlers like so.

    public class FooAuthorizationHandler : 
               AuthorizationHandler<OperationAuthorizationRequirement, Foo>	
    {	
       protected override void	Handle(AuthorizationContext context, 
                      OperationAuthorizationRequirement requirement, Foo foo)
       {
           // Do something here using context.User and foo
       }	
    }
    
    public class BarAuthorizationHandler : 
               AuthorizationHandler<OperationAuthorizationRequirement, Bar>	
    {	
       protected override void	Handle(AuthorizationContext context, 
                      OperationAuthorizationRequirement requirement, Bar bar)
       {
           // Do something here using context.User and bar
       }	
    }

I added the following lines in the `ConfigureServices` method of `StartUp`.

    services.AddInstance<IAuthorizationHandler>(new FooAuthorizationHandler());
    services.AddInstance<IAuthorizationHandler>(new BarAuthorizationHandler());

In my controller, I have the `IAuthorizationService` dependency like so and I call the `AuthorizeAsync`method.

    public class FooController
    {
       IAuthorizationService authorizationService;
        
       public ValuesController(IAuthorizationService authorizationService)
       {
          this.authorizationService = authorizationService;
       }
        
       [ActionContext]
       public ActionContext ActionContext { get; set; }
            
       public async Task<string> SomeAction()
    	{
    	    var foo = new Foo();
    	    bool result = await authorizationService.AuthorizeAsync(
                                    ActionContext.HttpContext.User,
                                    foo,
                                    new OperationAuthorizationRequirement {
                                                       Name = "FooCheck" });
    	    
    	    return "hello";
        }
    }

With the `AuthorizeAsync` call, both the handlers run. I want to make sure only the `FooHandler` runs when I call `AuthorizeAsync` from `FooController` and `BarHandler` to run when I do the same from `BarController`. Basically I want to have more than one resource-based authorization handler. What is the right approach to accomplish what I want to? What am I doing wrong here?

**Comment by leastprivilege** [comment]
I can re-produce that as well - I have to handlers (one for customer, one for product) - and the authorize call for product also triggers the Handle method of the customer handler.

My rep(r)o is here:
https://github.com/leastprivilege/AspNet5AuthorizationPlayground

**Comment by leastprivilege** [comment]
This makes it pretty much un-usable. Any comment?

**Comment by Eilon** [comment]
@HaoK we think this is a dup, can you find it and close this against that one?

**Comment by Eilon** [comment]
Found it: Dup of https://github.com/aspnet/Security/issues/494
