### ISSUE TITLE
SaveTokensAsClaims defaults

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#526]
Storing the expires_in is not very useful. I'd rather store an expires_at claim and add the seconds to the current time.

I am also not sure if the SaveTokensAsClaims should default to true.

**Comment by brentschmaltz** [comment]
Since expires_in is a relative term, it is difficult to determine when the item has expired. expires_at is easier to work with.

**Comment by Eilon** [comment]
Is this about changing the default value of `SaveTokensAsClaims` to `false` only for the OIDC provider? But perhaps leaving it `true` for the other providers (e.g. OAuth)?

As an aside, we also need to promote this property into `RemoteAuthenticationOptions` because all the current sub-classes of that type independently add the property.

**Comment by Eilon** [comment]
We're going to change the default back to `false` because having it on by default causes too many problems. In reality, many common scenarios also need to use something like claims transformation to limit the tokens that get saved anyway, so a one-stop action often won't work anyway.

**Comment by PinpointTownes** [comment]
> We're going to change the default back to false because having it on by default causes too many problems.

Interesting. Do you have a concrete example in mind?

Personally, I'm fine changing the default value to `false` for both the OIDC middleware and the OAuth2 base middleware (all the social providers already use `false` by default: https://github.com/aspnet/Security/pull/257#discussion_r30621030), as long as `SaveTokensAsClaims` remains a first-class citizen :+1:

**Comment by brockallen** [comment]
Perhaps some of the problems are the bloat from the protocol claims (nonce, etc). Those, most likely, can be always filtered from the claims.

**Comment by Eilon** [comment]
The bloat was the main problem. Serializing the full set of claims from OIDC can be huge, and most often breaks Safari. Having different defaults amongst different providers could also be a bit confusing. We talked about filtering out certain claims but I have a feeling that might also be confusing.

**Comment by HaoK** [comment]
f24c35f1a93ed0d6de3cda2b4ab15906f5f6d56b

**Comment by brentschmaltz** [comment]
@Eilon @PinpointTownes @HaoK Happy to see the default off. Was there any thought about using the BootStrapContext? I have seen multiple instances where the addition of a single claim has caused issues. The IDP never issued these claims.

**Comment by leastprivilege** [comment]
So will someone also change expires_in to expires_at ??

**Comment by brentschmaltz** [comment]
+1 on expires_at, as noted above, expires_in is a relative time.

**Comment by PinpointTownes** [comment]
@leastprivilege you know you can send a PR? :smile: 

If nobody wants to send a PR, I'll submit one to fix all the `SaveTokensAsClaims` issues.

**Comment by Tratcher** [comment]
Go for it

**Comment by leastprivilege** [comment]
@PinpointTownes Last time I checked, there are also paid developers at Microsoft to take care of that ;)

**Comment by HaoK** [comment]
Unassigning for retriage

**Comment by Tratcher** [comment]
So I went to change expires_in to expires_at
