### ISSUE TITLE
Organizational account authentication broken in beta8? Forces relogin on every request.

### ISSUE THREAD

**Issue by unt1tled** [aspnet/Security#544]
I'm able to File-New-Project a new Web Application with Organizational Account authentication and successfully login. But ever since beta8, I'm unable to navigate to any page other than Home/Index. It seems as though each [Authorize]d request redirects to the OpenId login page, which in turn redirects me back to the Index Page.

**Comment by unt1tled** [comment]
I tried creating a simple workaround by setting a session variable when I log in, then accessing that in a custom AuthorizeAttribute. I see that the pipeline gets to my attribute, grabs the username from my session and doesn't raise the unauthorized result, but afterwards it has the same behavior: redirecting me to the openid page.

In Startup.css:
    
    app.UseOpenIdConnectAuthentication(options =>
    {
                options.Events = new OpenIdConnectEvents
                {
                    OnAuthorizationCodeReceived = async (oContext) =>
                    {
                        var code = oContext.Code;
                        var authContext = new AuthenticationContext("https://login.microsoftonline.com/common");

                        // Get the token. 
                        var authResult = await authContext.AcquireTokenByAuthorizationCodeAsync(
                            code,  new Uri(options.PostLogoutRedirectUri), new ClientCredential(options.ClientId, options.ClientSecret),  "https://graph.microsoft.com/");

                        // Save the token in the session. 
                        oContext.HttpContext.Session.SetString("O365Token", authResult.AccessToken);
                        oContext.HttpContext.Session.SetString("loggedInUserName", authResult.UserInfo.DisplayableId);
                        oContext.HttpContext.Session.SetString("loggedInUserId", authResult.UserInfo.UniqueId);
                    }
                };

            });

Authorize**d** attribute
    
    public class Authorized : AuthorizeAttribute
    {
        public void OnAuthorization(Microsoft.AspNet.Mvc.Filters.AuthorizationContext context)
        {
            if (string.IsNullOrEmpty(context.HttpContext.Session.GetString("loggedInUserName")))
                context.Result = new HttpUnauthorizedResult();
        }
        
    }

**Comment by unt1tled** [comment]
Turns out that the generated template code was incorrect. You must explicitly set AutomaticAuthentication = true in the Configure function for your UseCookieAuthentication, but the default template has this set in the ConfigureServices function. My issue was resolved after moving it.

    
    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        ....
        app.UseCookieAuthentication(options =>
        {
              options.AutomaticAuthentication = true;
        });
        ....

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Templates#255
