### ISSUE TITLE
AuthenticationProperties is not available from OpenIdConnectAuthenticationNotifications.RedirectToIdentityProvider

### ISSUE THREAD

**Issue by MikeWasson** [aspnet/Security#546]
For OpenID Connect, we want to pass some information to the `RedirectToIdentityProvider` notification.

The `ChallengeResult` constructor takes an `AuthenticationProperties`, which includes an “Items” dictionary. But in the `RedirectToIdentityProvider` notification, there’s no way to get back the `AuthenticationProperties`.

**Comment by HaoK** [comment]
3257a82367e946a351cc1eaa02a9bb5dae2a432b
