### ISSUE TITLE
OpenIDConnect Scope became read-only

### ISSUE THREAD

**Issue by jgsousa** [aspnet/Security#548]
I'm trying to use OpenID on ASP.Net Beta8 but the scope option is read-only unlike it was previously. On startup.cs, Configure: 

            app.UseOpenIdConnectAuthentication(options =>
            {
                options.Authority = "XXX";
                options.ClientId = "XXX";
                options.ResponseType = "id_token token";
                //options.Scope = "openid email profile apiroles";
                options.RedirectUri = "XXX";

                options.SignInScheme = "Cookies";
                options.AutomaticAuthentication = true;
            });

I can't set the Scope anymore.

**Comment by rsantosdev** [comment]
+1

**Comment by MikeWasson** [comment]
@rsantosdev Scope is now a list. The property itself is read-only but you can add/remove scopes from the list.

    options.Scope.Add("phone");
    options.Scope.Add("address");

**Comment by jgsousa** [comment]
Sorry for not putting the answer, but yes it became a List. I found just after opening the issue.
