### ISSUE TITLE
CookieAuthenticationNotifications replacement

### ISSUE THREAD

**Issue by kennyrulez** [aspnet/Security#549]
Hello Everyone!
in order to superseed the identity redirect for my web.api project, in beta7 I used
```
services.ConfigureIdentityApplicationCookie(options =>
{
    options.LoginPath = PathString.Empty;
    options.Notifications = new CookieAuthenticationNotifications { OnApplyRedirect = context => { context.Response.StatusCode = 401; } };
});
```

Now in Beta8 ConfigureIdentityApplicationCookie does not exists anymore.

I struggle to find a replacement for this. I tried
```
services.Configure<CookieAuthenticationEvents>(options => {
    options.OnRedirect = (ctx) => { 
        return new Task(() => { ctx.Response.StatusCode = 401; });
    };
});
```
How I can restore this behavior?

Thanks in advance!
Valerio

**Comment by Tratcher** [comment]
@HaoK?

**Comment by HaoK** [comment]
```
 services.Configure<IdentityOptions>(options => options.Cookies.ApplicationCookie // gets you to the cookie options
```

**Comment by kennyrulez** [comment]
@HaoK thanks for your response.
I digged in your suggestion and I discovered:
ApplicationCookie contains CookieAuthenticationEvents in ApplicationCookie.Events

I think that OnRedirectToLogin will be suitable for me.
Could you please provide a snippet on how I can use it, because the code in
https://github.com/aspnet/Security/blob/204ab0b860d0c97f77373310becdff5f1c95103b/src/Microsoft.AspNet.Authentication.Cookies/Events/CookieAuthenticationEvents.cs 
(from line 40) is exactly what I want and what I tried to reproduce, and seems to be already present. Why I cannot use this behavior on my web.api project?

**Comment by HaoK** [comment]
Well these changes are pretty new, its possible that these aren't in the bits you are consuming yet?

**Comment by kennyrulez** [comment]
I'm using 1.0.0-beta8 received via embedded package manager in visual studio 2015, using project.json file. I haven't specified any revision number.
If these changes aren't already available as nuget package, what can I do? Can i mimic the behavior with the package I have or it's better to rollback to beta7?

Thanks!

**Comment by HaoK** [comment]
Yeah the code you are looking at is in rc1 builds.  You probably should just mimic the behavior with existing code for now, unless you like playing with fire and upgrading to rc1 bits :)

**Comment by kennyrulez** [comment]
I'll mimic :+1:
