### ISSUE TITLE
Rationalize error handling

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#55]
The original batch of social auth middleware (Facebook, Twitter, etc.) all swallowed exceptions. The second round (WsFed, ODIC) notified you (AuthenticationFailedNotification) and threw them. These should be rationalized.

Also, consider getting rid of EnsureSuccessStatusCode and offering a more useful error reporting by trying to build an exception using the JSON error payload when content type=app/json.

**Comment by brentschmaltz** [comment]
If a handler throws, will the next handler be called?  I think not. Given that we need sites to handle multiple providers for the same protocol, throwing may not be the right thing say if the signature fails, since the next handler using different signing key would succeed.

**Comment by Tratcher** [comment]
Related: http://katanaproject.codeplex.com/workitem/419

**Comment by Eilon** [comment]
@lodejard @Tratcher @HaoK some notes to consider:

1. Look at all the places we have a try/catch and either remove them entirely, or "tighten them up" to be more constrained, log the error (maybe), and then rethrow.
2. Consider scenarios such a login failure loops and how an app developer can fall into the pit of success (i.e. don't have infinite loops by default).

**Comment by Tratcher** [comment]
Design recommendation:
- Remove catch-all exception handling from all the middleware. Let the ExceptionHandler middleware catch and deal with the exceptions.
- Handle known errors as granular as possible. (e.g. g+ login not enabled.)
- For OAuth/OIDC/Twitter protocol errors (e.g. we get back an "error" response when the use hits cancel), add a new ProtocolError event, where the default behavior is to redirect to an auth failed path with query parameters describing the error.

**Comment by blowdart** [comment]
Depending on the error detail we may need to squash the error into something more generic, e.g. crypto errors. Can someone draw up a list of the errors thrown for review?

**Comment by Tratcher** [comment]
The ProtocolError redirect would only be for error messages the 3rd party sent to us, e.g. the user pressed cancel. These were already sent to us via a client side redirect, so the client had the chance to see them. Crypto errors would be exceptions handled by the ExceptionHandler middleware.

**Comment by blowdart** [comment]
I mean in reference to the the remove catch-all exception handling comment, and the as granular as possible recommendation

**Comment by HaoK** [comment]
I'll send out the PR for this today, but got sucked into a config rename :/

**Comment by HaoK** [comment]
Closing this since we have the main changes/design in.  Will use the other bugs to track resolving specific flows for each error condition.  409b50269a9d85618a31f84a3ffc2868abb3eeea
