### ISSUE TITLE
LoginPath override doesn't work for CookieAuthentication

### ISSUE THREAD

**Issue by diolive** [aspnet/Security#550]
I have a MVC 6 beta 8 web application based on default MVC template. I have renamed default `AccountController.cs` to `Auth.cs` and then I've tried to replace login path to `/Auth/Login`, but unsuccessfully. I've tried two different cases: override `CookieAuthenticationOptions.LoginPath` in `ConfigureServices` or in `Configure`, but there's no effect: `[Authorize]` attribute redirects me to /Account/Logic and I've received 404 error page.

Code example 1:
```
services.Configure<CookieAuthenticationOptions>(options =>
{
    options.LoginPath = new PathString("/Auth/Login");
});
```

Code example 2:
```
app.UseCookieAuthentication(options =>
{
    options.LoginPath = new PathString("/Auth/Login");
});
```

**Comment by HaoK** [comment]
If you are using the default templates, the application cookie is using the options configured via Identity, you can access these via `IdentityOptions.Cookies.ApplicationCookie`
