### ISSUE TITLE
Update project.json to pull in the latest build of OpenIdConnect packages

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Security#552]
To workaround an issue with gating, we're using a fixed version of OpenIdConnect packages:

* https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OpenIdConnect/project.json#L13
* https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.JwtBearer/project.json#L13

These need to be floated again. In addition, if OpenIdConnect packages target dotnet* generations, we could update these packages to also target generations as opposed to dnx*

**Comment by Tratcher** [comment]
Continue to use a hardcoded version in release, just update it.

Also, when we update this we should try to switch to the generations dependency model. They should be ready for this later this afternoon.
