### ISSUE TITLE
OpenIdConnectOptions.RedirectUri guidance

### ISSUE THREAD

**Issue by lszomoru** [aspnet/Security#553]
Please feel free to redirect me in case this is not the correct repo for this issue.

I have created a new WebApplication (beta8) that uses Azure AD for authentication and it looks like out of the box after the Azure AD auth dance, the request is always redirected to "/". Is that expected behavior? I would have expected that by default, if RedirectUri is not specified, after the auth dance I would redirected back to the original page that I tried to access.

To illustrate the issue I have changed the launch URL of the site from https://localhost:44300 to https://localhost:44300/Home/Contact and when I launch the site, I get redirected to https://localhost:44300 instead of https://localhost:44300/Home/Contact.

**Comment by PinpointTownes** [comment]
To change the final location of the user agent (the "return URL", not the OAuth2/OIDC `redirect_uri`), you can use `AuthenticationProperties.RedirectUri` when calling `ChallengeAsync`: https://github.com/aspnet/Security/blob/dev/samples/OpenIdConnectSample/Startup.cs#L44

```csharp
await context.Authentication.ChallengeAsync(OpenIdConnectDefaults.AuthenticationScheme, new AuthenticationProperties { RedirectUri = "/Home/Contact" });
```

**Comment by lszomoru** [comment]
Thanks for your response. The issue is that I do not want to hard code the RedirectUri to a particular Uri but I want it to be dynamic depending on the page that the user tried to access when the authentication challenge has happened. I was hoping that not explicitly specifying a RedirectUri will do the trick but that does not seem to be the case.

**Comment by PinpointTownes** [comment]
Nothing prevents you from determining the return URL dynamically (for instance, via a specific `returnUrl` parameter in the query string: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/samples/Mvc/Mvc.Server/Controllers/AuthenticationController.cs#L42) :smile:

**Comment by PinpointTownes** [comment]
BTW, the OIDC middleware should automatically use the current URL when `AuthenticationProperties.RedirectUri` is null as the final destination. That said, I remember the Azure AD guys were doing crazy things in their code samples. Could you please post the sample URL?

**Comment by lszomoru** [comment]
Thanks for your help and for the link to your code. To make things more interesting in my case the auth challenge is happening due to the AuthorizeAttribute that I have on a controller and not through an action (ex: SignIn) on a particular controller (ex: AccountController).

As you say, I was also hoping that by not specifying the RedirectUri, I will get the default behavior for free and that is why I have posted my question here to check whether this is expected or possibly a bug in the middleware. BTW, what is the sample URL that you want me to post?

**Comment by PinpointTownes** [comment]
Sorry, I thought you were using one of the Azure AD samples :smile: 

Then, could you please share your Startup.cs?

**Comment by Tratcher** [comment]
This was probably caused by Options.DefaultToCurrentUriOnRedirect defaulting to false in beta8. https://github.com/aspnet/Security/blob/1.0.0-beta8/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L124

We've removed this property in rc1 so you should get this behavior by default now.

**Comment by PinpointTownes** [comment]
Doh, I had not realized this property was `false` by default :scream:

**Comment by lszomoru** [comment]
Yep, setting Options.DefaultToCurrentUriOnRedirect to **true** did the trick!!!
Glad to hear that this will be removed in rc1. Thank you both for your help!

**Comment by farshid3003** [comment]
now there is no return_uri but you did not think to this case
when you code works behind an proxy server like nginx with http protocol and from out you have https (ssl) now when you go to authority server your client redirect_uri is not valid as it will post with http not https.

**Comment by Tratcher** [comment]
@farshid3003 the recomendation for reverse proxies is to use x-forwarded-proto headers and the ForwardedHeaders middleware to apply them to the request fields. Then the redirects can be built correctly.

**Comment by farshid3003** [comment]
I did it actually  the problem is that when you go to ids with http//* and ids is wating for https.
in the app middle ware set the return_url automatically and set it to http
now I solve it by using events

` Events = new OpenIdConnectEvents
                {
                    OnRedirectToIdentityProvider = OnRedirectToIdentityProvider
                },

and in the method
arg.Properties.RedirectUri = idsConfig.ReturnUri;`

but I think it should let me to set return_url. if I didnot set it It can set it automatically
