### ISSUE TITLE
Breakpoint in Controller.OnAuthentication() results in catastrophic failure of OpenIDConnect

### ISSUE THREAD

**Issue by dapug** [aspnet/Security#554]
**Evil Problem:**
If you override **OnAuthentication** in your MVC controller, AND you happen to simply set a **breakpoint** in that method, your OpenIDConnect notifications will NOT fire!  **Authentication fails** despite the server returning the code and tokens.  Remove the breakpoint, and suddenly OpenIDConnect works again.

**Set up:**
 - Create a simple hello-world MVC client with "hybrid" flow connecting to an OpenID authority
 - Configure OpenIdConnectAuthenticationNotifications as usual, with methods such as  **MessageReceived** and **AuthorizationCodeReceived**

```
            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "client",
                Authority = "https://localhost:44302/core", // Thinktecture IdeneityServer3
                RedirectUri = "https://localhost:44300",
                PostLogoutRedirectUri = "https://localhost:44300",
                ResponseType = "code id_token token",
                Scope = "openid profile read write offline_access",
      
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    MessageReceived = n =>
                    {
                        //var foo = n.ProtocolMessage;

                        return Task.FromResult(0);
                    },
                    AuthorizationCodeReceived = async n =>
                    { ...
```
 - Create an auth Url in your controller with an HTML Link on the view (you will click this to initiate an auth request)
```
        public async Task<ActionResult> Index()
        {
            ViewBag.AuthUrl = "http://localhost:44302/service/connect/authorize?client_id=client&response_type=code+id_token+token&scope=openid+profile+read+write+offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A2003%2Fcallback&nonce=blah";
            return View();
        }

        [Authorize]
        public async Task<ActionResult> Callback()
        {
            return View();
        }
```
 - Now put this override method in you Controller

```
        protected override void OnAuthentication(System.Web.Mvc.Filters.AuthenticationContext filterContext)
        {
            base.OnAuthentication(filterContext);
        }
```

OK, now, normally what happens when you navigate to a page requiring authorization, the middleware intercepts and sends you off to to authenticate, upon return, it signs you in (and if you have a breakpoint in AuthorizationCodeReceived, you will see this happen).

However, you might also want to **create your own request**, as seen here in **Index()**.  When you CLICK that link, it takes you to authenticate, and upon return, you are actually returning to a page requiring authorization - in this example, **Callback()**.  By requesting this secure page, OpenIDConnect knows to apply the code/token it got from the authentication server.

**Repro:**
 - Make sure you pointed to a valid OpenID authority, configured client as **hybrid**, with **redirects**, etc.
 - Put a **breakpoint** in **AuthorizationCodeReceived** and the **Callback()** action 
 - Run the project and click the link and sign in.  you should see it hit both breakpoints upon your return, (user is authenticated or Callback would not be called)
 - Navigate to Index again, **clear cookies** (sign out)
 - Now add a **breakpoint** in your **OnAuthentication()** method.
 - Click the link and sign in again
 - Notice that NO breakpoints are hit!  **OpenIDConnect is skipped**, and user is not authorized to hit Callback()

**Simply adding or removing the breakpoint in OnAuthentication() results in catastrophic failure of OpenIDConnect.**

**Why?**  

Maybe it seems like no big deal, but how in the world is the debugger affecting critical execution of OpenIDConnect, and how am I to feel confident about this in production? What else might affect execution here?

**Comment by Tratcher** [comment]
It would help if you pushed your repro project to a github repo.

**Comment by HaoK** [comment]
Please reopen if you can reproduce this.
