### ISSUE TITLE
How to I can do what does DefaultToCurrentUriOnRedirect=true with IdentityServer3 ?

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Security#559]
It seems DefaultToCurrentUriOnRedirect property has been removed from OpenIdConnectOptions.
How to I can return to a secure route different than what id set for CallbackPath?
IdentityServer3 return request to the CallbackPath only.
Needs to handle it in the callbackPath route?

**Comment by PinpointTownes** [comment]
`DefaultToCurrentUriOnRedirect` has been removed but the default behavior is based on what `DefaultToCurrentUriOnRedirect=true` used to do, so no change should be required.

**Comment by mikeandersun** [comment]
I visit `/securedroute` redirect to IdentityServer and return to `/` ! 
What what is my mistake?
rc1-16048 breaks me :)

**Comment by PinpointTownes** [comment]
Without seeing any code, it's hard to help you. At least, share your Startup class :smile:

**Comment by mikeandersun** [comment]
https://github.com/aspnet/Security/issues/560
