### ISSUE TITLE
Specified method is not supported when return from IdnSrv to the callbackPath.

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Security#560]
An unhandled exception occurred while processing the request.
NotSupportedException: Specified method is not supported.
Microsoft.AspNet.Authentication.RemoteAuthenticationHandler`1.HandleSignInAsync(SignInContext context)

**Comment by mikeandersun** [comment]
[Here](https://github.com/mikeandersun/experimental/tree/master/source/OpenIdExperinces) is my experimental repo.

**Comment by Tratcher** [comment]
Issue 1, OIDC's Options.AuthenticationScheme should not match the one specified in Cookies. Auth middleware instances need to be identified using unique authentication schemes.
https://github.com/mikeandersun/experimental/blob/master/source/OpenIdExperinces/Startup.cs#L69

**Comment by billboga** [comment]
@mikeandersun: see if this helps: https://github.com/IdentityServer/IdentityServer3/issues/2112#issuecomment-172692273.
