### ISSUE TITLE
Consider making AutomaticAuthenticate true by default for Cookies

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#569]
Now that we split the automatic flags, cookies can probably default to true in most cases, as its almost always the desired behavior when using only a single application cookie.

**Comment by Tratcher** [comment]
Is Identity the odd one out where it uses multiples? Or is this safe even with multiples?

**Comment by HaoK** [comment]
Yeah, identity and templates use multiples for TFA and external login cookies.  Even there, nothing stops working even if all of the cookies got mushed into the claims principal.  But it just bloats the cookie, so we would still turn it off there.  I think we are okay flipping back now with challenge split.  @davidfowl had some concerns that we made this too complicated with the additional flag, so I'm hoping just making the defaults work more generally, at least very few people will have to set these flags...

**Comment by PinpointTownes** [comment]
Personally, the biggest concern I have with that is the risk of seeing a subtle XSRF attack in apps mixing both "Web API" and "MVC" controllers, since a Web API controller would accept both cookies and bearer authentication.

**Comment by HaoK** [comment]
de107ffe61d15c7074fc56fa1da6428e3c0e7de1

**Comment by blowdart** [comment]
This needs to tie into MVC work around not binding form POST to webapi controllers. @rynowak

**Comment by HaoK** [comment]
So just to be clear, identity was already turning this to true today.  So this doesn't really have much practical effect except for changing the default when directly using cookie middleware
