### ISSUE TITLE
beta 7 > beta 8  - JWT SecurityTokenValidators

### ISSUE THREAD

**Issue by dynamiclynk** [aspnet/Security#572]
So prior to Beta 8 in Beta 7 I had the below code in my StartUp.ConfigureServices method, but since the Bearer configuration was moved to the Configure method, the **ValidateToken** in my Custom JwtTokenValidator no longer fires.

**This is what I had prior to beta 8**
     

        public static void ConfigureTokenValidation(IServiceCollection services, string appName)
        {
            services.ConfigureOAuthBearerAuthentication(config =>
            {
                config.TokenValidationParameters.ValidateAudience = true;
                config.TokenValidationParameters.ValidateIssuer = true;
                config.TokenValidationParameters.RequireExpirationTime = true;
                config.TokenValidationParameters.ValidateLifetime = true;
                config.TokenValidationParameters.RequireSignedTokens = true;
                config.TokenValidationParameters.ValidateIssuerSigningKey = true;
                config.TokenValidationParameters.ValidateSignature = true;
                config.SecurityTokenValidators = new List<ISecurityTokenValidator>
                {
                    new CustomSecurityTokenValidator(appName)
                };
            });
        }

**Now (ValidateToken not firing)**
    

        public static void UseJwtBearerValidation(IApplicationBuilder app, string appName)
        {
            app.UseJwtBearerAuthentication(config =>
            {
                config.AutomaticAuthentication = true;
                config.TokenValidationParameters.ValidateAudience = true;
                config.TokenValidationParameters.ValidateIssuer = true;
                config.TokenValidationParameters.RequireExpirationTime = true;
                config.TokenValidationParameters.ValidateLifetime = true;
                config.TokenValidationParameters.RequireSignedTokens = true;
                config.TokenValidationParameters.ValidateIssuerSigningKey = true;
                config.TokenValidationParameters.ValidateSignature = true;
               
                //now a readonly list prop
                config.SecurityTokenValidators.Add(new CustomSecurityTokenValidator(appName));
            });
        }

CustomSecurityTokenValidator is a custom class that handles all of JWT issuer, key, expiration, etc. Inherits from JwtSecurityTokenHandler in System.IdentityModel.Tokens.Jwt.

**Comment by Tratcher** [comment]
Have you tried calling `config.SecurityTokenValidators.Clear()` first to remove the default validator. https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.JwtBearer/JwtBearerOptions.cs#L103

**Comment by dynamiclynk** [comment]
@Tratcher You are my hero :) Yep all good now. closed.
