### ISSUE TITLE
Consider adding a sample using the JWT authentication

### ISSUE THREAD

**Issue by janpieterz** [aspnet/Security#574]
I've been trying to implement this and am currently basing the implementation on some loose issues that show code of people implementing this. It would be very helpful if either the docs or this repository had a valid way of handling JWT tokens.

I realize it's probably an extensive topic, but a minimal implementation could be linking to a couple of good explanatory articles and then pointing towards one sample project that has this working.

**Comment by brentschmaltz** [comment]
@janpieterz  https://github.com/AzureADSamples have many samples showing how to validate a JWT.
