### ISSUE TITLE
[Authorization] Consider base class to make building custom policies/requirements easier

### ISSUE THREAD

**Issue by brockallen** [aspnet/Security#575]
The authorization system is quite nice, but complex given the type checking for authorization handlers and authorization requirements. When building custom authorization handler/requirement logic, it's a tad complex/confusing to be required to build a class such as this:

```
public class ClaimsAuthorizationRequirement : 
   AuthorizationHandler<ClaimsAuthorizationRequirement>, IAuthorizationRequirement
```

I'd like to see a easy base class to encapsulate this policy based approach in some way (with the assumption this class can fully implement the authorization logic based upon the incoming user's claims without needing to look at something external and this doesn't need anything from DI). Something like:

```
abstract public class AuthorizationRequirement
{
    abstract public void Handle(AuthorizationContext context);

    // not sure if these helpers would be needed -- looking for
    // a way to not have to pass the IAuthorizationRequirement instance to Succeeded
    protected void Succeed(){} 
    protected void Failed(){} 
}
```

And then perhaps an implementation:
```
public class SeniorSalesRequirement : AuthorizationRequirement
    {
        protected override void Handle(Microsoft.AspNet.Authorization.AuthorizationContext context) 
        {
             if (context.User.HasClaim("role", "Exec") ||
                 context.User.HasClaim("role", "SeniorSales"))
             {
                  base.Succeed(context);
              }
        }
    }
```

Perhaps this approach would need another pre-registered authorization handler (like the PassThroughAuthorizationHandler) that knows how to handle the AuthorizationRequirement-dervied requirements.

Just throwing out ideas to try to simplify and polish the API for doing policy based authorization.

**Comment by HaoK** [comment]
That sounds reasonable to me, we started without the requirement/handler split initially, and I agree that it simpler in many situations and worth a little additional sugar...  I'll take a look

cc @blowdart @lodejard @divega

**Comment by HaoK** [comment]
@brockallen Take a look at this PR: https://github.com/aspnet/Security/pull/655

Does something like this work for you?  Basically you would just have to do something like this:

```
policy.RequireAssertion(c => c.User.HasClaim("role", "e1") || c.User.HasClaim("role", "s1")));
```

**Comment by HaoK** [comment]
2e1a8b31cd0c520ffd69ba7818313ae9a9f688a4

**Comment by brockallen** [comment]
Nice, thanks.
