### ISSUE TITLE
The dependency Microsoft.AspNet.Authentication.OpenIdConnect 1.0.0-rc2-16009 does not support framework .NETPlatform,Version=v5.4

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Security#576]
I add this dependency to my project and get this error:
Error NU1002	The dependency Microsoft.AspNet.Authentication.OpenIdConnect 1.0.0-rc2-16009 in project xyz does not support framework .NETPlatform,Version=v5.4.

**Comment by Tratcher** [comment]
Are you using an RC2 DNX?

**Comment by mikeandersun** [comment]
Yes

**Comment by Eilon** [comment]
@pranavkm looks like we missed updating the TFMs in this repo. Can you update this repo and also check if we missed any other repos? Basically scan all the NuGet packages we ship and see if `dnxcore50` show up in them.
