### ISSUE TITLE
Port serialization for BootstrapContext. Make sure to increment TicketSerializer.FormatVersion.

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#58]
Recent changes made in Katana to support `BootstrapContext` have not been ported yet to vNext. When porting them, make sure to increment `TicketSerializer.FormatVersion` to avoid this kind of issue: https://katanaproject.codeplex.com/workitem/347

> Associated topic: https://katanaproject.codeplex.com/discussions/566815

> __Symptoms__: tickets (and by extension, cookies) created by __Katana 2.1__ are not correctly deserialized under __Katana 3__ and lack the `AuthenticationProperties` element. This causes critical properties like `IssuedUtc` or `ExpiresUtc` to be absent from the final ticket. As a result, non-persistent cookies never expire.

> __Root cause__: when __Brent Schmaltz__ added `BootstrapContext` support in `TicketSerializer` (https://katanaproject.codeplex.com/SourceControl/changeset/87f2be297e5b24cbbc2627cc5cac2ded41ddf822), he forgot to increment the version number to make sure tickets serialized before this change were ignored. 

> __Explanation__: when `TicketSerializer` tries to read old tickets, the new `reader.ReadInt32()` call inserted in `TicketSerializer.Read` makes the binary serializer going further than expected by trying to read an element that was not present in the serialized payload. Next line, when `PropertiesSerializer.Read` is called to deserialize the `AuthenticationProperties`, `BinaryReader` fails to read the correct version number associated with `PropertiesSerializer`, which causes the ticket to be returned without its `AuthenticationProperties` companion.

> __Solution__: increment `TicketSerializer.FormatVersion` to make sure `TicketSerializer` won't try to deserialize incompatible tickets. This change will make every existing ticket/cookie unreadable. As a consequence, users would have to re-authenticate. In the meantime, end devs can implement their own `TicketSerializer` and fix this issue by incrementing the version number.

**Comment by Eilon** [comment]
We think the type is now available on Core CLR, so we should be able to do this now.

**Comment by Eilon** [comment]
@Tratcher can you check if the APIs we need are there? If not, we'll have to ping some folks.

**Comment by Tratcher** [comment]
@brentschmaltz What package is the BootstrapContext type available in for CoreCLR?

**Comment by PinpointTownes** [comment]
`BootstrapContext` no longer exists.

`JwtSecurityTokenHandler` sets `ClaimsIdentity.BootstrapContext` with the serialized token (as a string).
