### ISSUE TITLE
Documentation / Tutorial Request

### ISSUE THREAD

**Issue by Fosol** [aspnet/Security#580]
I'm working on a project where I need to authenticate and authorize users so that they have access to numerous MVC applications and APIs.

I was planning to use Oauth, however I'm running into a wall trying to figure out how to implement it.  The solution is internal and can not use 3rd party Oauth providers.

I need to create a simple Oauth Server that validates user credentials using Microsoft.AspNet.Identity.  I've already implemented Identity successfully within the context of a single MVC application (it needs to be ported to the Authentication Server).

Each MVC Application will redirect to the Authentication Server for login.  I have this 'working', although I have no idea if I'm doing it correct.

However the response from a valid login never does what I need.  It needs to return the appropriate response so that the MVC Application can now make requests to the API on behalf of the user with their specific access token.

Please point me in the direction of documentation or samples?

Thanks!

**Comment by PinpointTownes** [comment]
> I need to create a simple Oauth Server that validates user credentials using Microsoft.AspNet.Identity. I've already implemented Identity successfully within the context of a single MVC application (it needs to be ported to the Authentication Server).

Unlike OWIN/Katana, ASP.NET 5 offers no native authorization server (you can take a look at http://stackoverflow.com/questions/29055477/oauth-authorization-service-in-asp-net-mvc-6/29144031#29144031 for more information).

You basically have 2 ways to achieve what you're looking for:
* You can roll your own authorization server. Of course, it's not the recommended approach, but some people like this option: https://github.com/aspnet/Security/issues/359#issuecomment-124450989.

* You can use a third-party authorization server. There are a few servers for ASP.NET:
    * The most popular one is probably IdentityServer3 (https://github.com/IdentityServer/IdentityServer3). It's not based on ASP.NET 5 but there's an adapter you can use to add it to your ASP.NET 5 app (it won't work on CoreCLR, though). It's the server you need if you're looking for a turnkey solution.

    * Another one is ASOS (https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server). It has been specifically designed for ASP.NET 5 and works on both DNX451 and DNXCORE50. Unlike IdentityServer, it offers a low-level/protocol-first approach. Go with ASOS if you need full flexibility (e.g custom authorization pages). Since I'm the main developer behind ASOS, you can ping me for more information :smile: 

    * The most recent one is OpenIddict (https://github.com/openiddict/core): it's an experimental zero-friction server that uses ASOS and ASP.NET Identity 3 internally and is supposed to provide the easiest way to add token support to your application.

**Comment by Fosol** [comment]
Does ASOS allow me to plug in my implementation of Microsoft.AspNet.Identity?

**Comment by PinpointTownes** [comment]
Sure, it's absolutely not tied to any membership implementation (it's even up to you to implement that part :smile:)

**Comment by Fosol** [comment]
In your sample project Mvc.Server it appears all AuthenticationController endpoints use a 3rd party provider?  Is there an example of in-house signin validation?

**Comment by PinpointTownes** [comment]
Since you're using Identity, I'd suggest using the (horrible :smile:) `AccountController` that comes with the default template. it will handle local/external authentication for you (this is exactly how the Mvc.Server sample in OpenIddict works: https://github.com/openiddict/core/tree/dev/samples/Mvc.Server).

**Comment by Fosol** [comment]
1) User makes request to MVC App
2) MVC App redirects to Oauth Server /login
3) Oauth Server returns /login View
4) Oauth Server validates POST
5) Oauth Server creates token
6) ??  This is where I get lost.  I can't get the Oauth Server to correctly respond to the original MVC App.  I can redirect back to it, but it has no authentication information.

**Comment by PinpointTownes** [comment]
Well, the flow is a bit more complicated:

1. The client app initiates the OAuth2/OIDC request and redirects the user agent to the authorization server.

2. The authorization endpoint (`AuthorizationController.Authorize` in the default sample) detects you're not logged in and returns a 401 response, which is caught and replaced by a 302 redirect to the login controller (`AccountController` in your case).

3. Once the user is fully authenticated, he/she's redirected back to the authorization endpoint (`AuthorizationController.Authorize`), with the OIDC parameters of the original request.

4. Depending on how your authorization page is implemented, the user might have to accept the authorization request. When the request is accepted, the authorization controller calls ASP.NET 5's native `SignInAsync` method, which triggers the token creation and causes a 302 redirect (or a 200 response with an auto-post form) that redirects the user agent to the client app.

5. The client application validates the tokens and can use the access token to query the API.

**Comment by Fosol** [comment]
@PinpointTownes I was hoping you could help me out.

I've create a example solution and posted it on GitHub - https://github.com/Fosol/Example.OauthServer

This of course doesn't work yet.  Essentially I want to have a MVC client application redirect logins to the MVC server application which will use our custom Identity implementation to login and provide tokens.

My experience with Oauth is on the side of client software.  I understand the general process but I'm used to manually handling all the requests and responses within a literal client application (not a web MVC client).

I don't understand how to respond to the client after successfully signing in.  I don't understand how the MVC Client application will continue to remember the users authentication token so that all subsequent requests contain it (thus giving access to Resource applications).

Any feedback is appreciated.

**Comment by PinpointTownes** [comment]
@Fosol I took a look at your solution and TBH, I can't understand what you're trying to do.
If you don't feel comfortable with the protocol, why rolling your own OAuth2 server instead of using a ready-to-use solution?

**Comment by Fosol** [comment]
Good question.  Sometimes it's not so much about comfort and more about requirements.  

There is a lot of configuration in the Startup that I can't find any documentation or tutorials on to fully understand.  I'm spending a lot of time stepping through the code (which is fine, but time consuming).

I was reviewing some of the examples you have provided.  I found the code useful but I didn't see how they would work in my situation.  I'm probably just not understanding them well enough.

I need the web browser to make a request to the MVC Client application which will send them to login into the MVC Oauth Server application.  It will then allow the MVC Client application to make requests to the Resource applications (really just common oauth implementation).

Can you confirm that your framework (https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server) does this?  If so, great!  I'll probably have more specific questions as I dig deeper into it.

**Comment by PinpointTownes** [comment]
> I need the web browser to make a request to the MVC Client application which will send them to login into the MVC Oauth Server application. It will then allow the MVC Client application to make requests to the Resource applications (really just common oauth implementation).

> Can you confirm that your framework (https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server) does this? If so, great! I'll probably have more specific questions as I dig deeper into it.

Yes. Btw, that's exactly how the default Mvc.Server/Mvc.Client samples work. Don't hesitate to give them a try to see how they work :smile:

**Comment by Fosol** [comment]
@PinpointTownes When I open up the example solution it displays tons of errors.  I think they're all to do with DNX Core 5.0.  

1) Is there a way to disable DNX Core 5.0 temporarily?
2) Is there a way to possibly resolve all the errors VS is displaying?

Lots of errors are saying they don't support Core 5.0.

**Comment by Fosol** [comment]
@PinpointTownes Will your example solution work in beta8?

**Comment by PinpointTownes** [comment]
> @PinpointTownes When I open up the example solution it displays tons of errors. I think they're all to do with DNX Core 5.0.

@Fosol you need the latest DNX runtime to open ASOS (RC2). Which version are you currently using?

> @PinpointTownes Will your example solution work in beta8?

The samples coming with the main project require the latest runtime/packages. They won't work with beta8. That said, you can clone the samples and use the official release for beta8: https://www.nuget.org/packages/AspNet.Security.OpenIdConnect.Server/1.0.0-beta3. It will probably need some tweaking to fix the breaking changes between beta8 and RC2.

FYI, future samples will be posted to https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples and will probably use fixed versions (likely ASP.NET 5 RC1). @DovydasNavickas is currently working on a SignalR sample :smile:

**Comment by Fosol** [comment]
@PinpointTownes Regrettable all I get is a lot of red underlining in your code.  Not sure if there is a quick bit of advice that might help me actually step through your code.

**Comment by Fosol** [comment]
@PinpointTownes Regrettably I can only get red lines under nearly every file.

I've installed DNVM 1.0.0-rc1-final.

**Comment by PinpointTownes** [comment]
You need the **latest DNX RC2 nightly build** (from https://www.myget.org/gallery/aspnetvnext) :smile: 
Just run `dnvm upgrade -u -r clr` and it will install that for you.

**Comment by Fosol** [comment]
@PinpointTownes I hate to be a constant bother, but dependency issues with the new DNX structure have been a constant nagging problem over here.  I'm sure lots of these issues are the direct result of a unreleased product that is constantly change.  I however haven't figured out how to resolve many of them consistently.

I've installed DNVM 1.0.0-rc2-16177 clr x86.
I've run dnu restore.
I get a lot of warnings - (i.e. "Warning: FindPackageById: Microsoft.Extensions.Primitives Response status code does not indicate success: 404 (Not Found)).
I get a lot of errors - (i.e. "Error: FindPackagesById: Microsoft.AspNet.Hosting.Abstractions Response status code does not indicate success: 404 (Not Found)).

All I'm sure of is that the issues are the result of dependencies since there are over 800 errors.  This is a common headache.

**Comment by PinpointTownes** [comment]
These errors are often transient. Have you tried running dnu restore again?

**Comment by Fosol** [comment]
@PinpointTownes I was finally able to get everything up and running.

Is there an example of how to turn on NTML?

**Comment by PinpointTownes** [comment]
@Fosol nope, sorry.

That said, it shouldn't be really different from adding any other external provider. I'm sure @Tratcher has a sample demonstrating how to use Windows authentication :smile:

**Comment by Fosol** [comment]
If I turn on "Enable Windows Authentication" on the project property wizard page the program crashes.  When I leave it off the program runs.

**Comment by PinpointTownes** [comment]
@Tratcher is definitely the right person to ask :smile: 

I guess you're using the RC1 tooling?

**Comment by Fosol** [comment]
@PinpointTownes I've posted a new Github repository with a running version of AspNet.Security.OpenIdConnect.Server.

GitHub - https://github.com/Fosol/Example.Oauth

In the AuthenticationController I've added a way to Login using the default implementation of Microsoft.AspNet.Identity.

What I don't understand is how ASP.NET 5 is expecting to submit the appropriate oauth token and return it to the original client requests.  Any information would be helpful.

I'm think it needs to do something with a ChallengeResult, but I'm not certain in this particular use case.

**Comment by PinpointTownes** [comment]
> What I don't understand is how ASP.NET 5 is expecting to submit the appropriate oauth token and return it to the original client requests. Any information would be helpful.

The authorization response (with the access token) is applied when calling `SignInAsync`: https://github.com/Fosol/Example.Oauth/blob/master/src/Example.Oauth.Server/Controllers/AuthorizationController.cs#L172-L174

FYI, cloning the repository and using it as-is is strongly discouraged. Instead, you should reference the official beta4 release (for ASP.NET 5 RC1): https://www.nuget.org/packages/AspNet.Security.OpenIdConnect.Server/1.0.0-beta4

**Comment by Fosol** [comment]
I'm trying to step through the code to understand it all, that's the reason I've copied the code into the project.  I also needed it to run in RC1, all I had reference to was your earlier post on GitHub which was using the most recent nightly builds.

**Comment by Fosol** [comment]
@PinpointTownes Is there any documentation on the following;
1) How ChallengeResult works?
2) How to implement custom login form?

I'm having a hard time understanding the technical flow within ASP.NET 5.

**Comment by Fosol** [comment]
```
var request = HttpContext.GetOpenIdConnectRequest();
```
The request after a custom login form always null since all the original request information containing client_id and other details is no longer in scope.  I'm not sure how to ensure this gets reattached after the post with the users credentials.

**Comment by PinpointTownes** [comment]
> @PinpointTownes Is there any documentation on the following;
1) How ChallengeResult works?
2) How to implement custom login form?

I'm not sure the documentation for these 2 things is ready yet. (/cc @Rick-Anderson)

> The request after a custom login form always null since all the original request information containing client_id and other details is no longer in scope. I'm not sure how to ensure this gets reattached after the post with the users credentials.

The best approach is to flow the OIDC request parameters directly in the request form. If your authentication process is too complex for that, consider using `unique_id` to retrieve the OIDC request from the distributed cache: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/134

**Comment by Fosol** [comment]
@PinpointTownes Any example on how to use retrieve the OIDC request parameters with the unique_id?

In your sample it's at this point that I lose the OIDC since it redirects to my custom login page: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/samples/Mvc/Mvc.Server/Controllers/AuthorizationController.cs#L53

My custom login controller now needs to get the OIDC requests parameters but I haven't figured out how to get the information.
```

        [HttpGet, Route("~/account/login")]
        public ActionResult Login(string returnUrl = null)
        {
            var request = HttpContext.GetOpenIdConnectRequest();
            ...
        }
```

**Comment by Fosol** [comment]
@PinpointTownes I've been able to get an example working, which is great.  Thanks to all the work in your example.

Question - How do I support a resource server on a different domain?

**Comment by PinpointTownes** [comment]
> @PinpointTownes Any example on how to use retrieve the OIDC request parameters with the unique_id?

It's transparent: simply call `GetOpenIdConnectRequest()` and it will return the request from the cache (assuming the current request path corresponds to the authorization endpoint, of course).

> @PinpointTownes I've been able to get an example working, which is great. Thanks to all the work in your example.

Fantastic. Glad you sorted it out! :clap: 

> Question - How do I support a resource server on a different domain?

In the current version, simply create a new app and add the JWT bearer middleware to your pipeline. In the next version, we'll stop using JWT access tokens and go back to opaque tokens: you'll thus be encouraged to use the new introspection middleware for this scenario: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/185

**Comment by Fosol** [comment]
@PinpointTownes I've attempted to pull down the NuGet package you referenced here (https://www.nuget.org/packages/AspNet.Security.OpenIdConnect.Server/1.0.0-beta4) into a project I want to now test with.  There however appears to be an extension method missing "AddOpenIdConnectServer".

Is it no longer needed?

**Comment by PinpointTownes** [comment]
Hum, not sure where you've seen this extension, as it has never existed :smile: 

Just ensure that both the authentication and the caching services (`services.AddAuthentication()` + `services.AddCaching()`) are added and it should work.

**Comment by Fosol** [comment]
Thanks!

**Comment by Fosol** [comment]
@PinpointTownes I'm not sure what I changed to break the resource request, but now it only returns a 500 when I attempt to get /api/message.  Is there a way to debug the issue on the server side?  I can't seem to find a spot to place a breakpoint.

**Comment by Fosol** [comment]
It's related to the AuthorizeAttribute because if I remove it the endpoint can be hit successfully.

**Comment by PinpointTownes** [comment]
Try enabling logging to determine the exception causing the 500 response.

**Comment by Fosol** [comment]
@PinpointTownes I'm having difficulty signing off after I introduced my custom Identity implementation.  I was wondering if you could point me in the right direction.  I suspect it has something to cookie or authentication schema names.

Using Fiddler to watch the traffic I get the following;
1) After successful login form
Response Cookies
> Set-Cookie: LIS.Cookie...

2) Redirects back to Client Application
Response Cookies
> Set-Cookie: .AspNet.OpenIdConnect.Nonce...
- - -
> Set-Cookie: .AspNet.OpenIdConnect.State...
- - -
> Set-Cookie: Cookies=chunks:2; path=/; httponly
- - -
> Set-Cookie: CookiesC1...
- - -
> Set-Cookie: CookiesC2...

3) After logout on Client Application
Response Cookies
> Set-Cookie: Cookies=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/
- - -
> Set-Cookie: CookiesC1=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/
- - - 
> Set-Cookie: CookiesC2=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/

4) Then it redirects to the OAuth Server and includes a cookie
Request Cookies
> LIS.Cookie...

5) The OAuth Server then automatically signs me back in.

**Comment by Fosol** [comment]
@PinpointTownes Another question for you regarding tokens and claims.

After I login through the Oauth server I can confirm that my Identity implementation has added the appropriate claims to the user.  However once it gets back to the client it no longer contains the claims associated with my Identity implementation.

I've tried to include my Identity library in both the client and the server application to no avail.  It only appears to work on the server.

Is there something that needs to be configured so that the oauth server returns the identity claims?

**Comment by PinpointTownes** [comment]
Are you specifying a destination for your claims?

See http://stackoverflow.com/a/32299781/542757 for more information.

**Comment by Fosol** [comment]
@PinpointTownes does this mean I need to edit the AuthorizationController.Accept method to include the claims with the new identity?

**Comment by PinpointTownes** [comment]
Yes. You can see the MVC server sample for an example.

**Comment by Fosol** [comment]
I noticed the claims from my Identity implementation are issued by "LOCAL AUTHORITY".  Where is this value set?  I've scanned the source code and can't find that value anywhere.

**Comment by PinpointTownes** [comment]
It's ClaimsIdentity's default issuer when you don't set it. But it's not really important as the issuer is not used by the OIDC server.
