### ISSUE TITLE
beta8 -> rc1-final jwt signature validation fails

### ISSUE THREAD

**Issue by dynamiclynk** [aspnet/Security#582]
I have been utilizing this same jwt signature validation code since beta6 and it has worked without issues. 

Once I upgraded to rc1-final. Signature validation fails, because the payload is different on the consumer end and I can not determine why, before I start posting the Generation and Consumer code were their any rc1-final changes that could have potentially cause this issue I am encountering?

I have verified the secret used in the generation is the same as being used to validate the signature, like I said this code is the same as from dnx beta 6.

**Generation Key:**

    var hmac = new HMACSHA256(Convert.FromBase64String(client.Secret));
    var key = new InMemorySymmetricSecurityKey(hmac.Key);
    var signingCredentials = new SigningCredentials(key, SecurityAlgorithms.HmacSha256Signature, SecurityAlgorithms.Sha256Digest);

*Ticket generated payloads:*

**jwt.EncodedHeader**
    
    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9

**jwt.EncodedPayload**

 
     eyJ1bmlxdWVfbmFtZSI6ImNvcmV5aEBoZWFydGxlZ2FjeS5jb20iLCJlbWFpbCI6ImNvcmV5aEBoZWFydGxlZ2FjeS5jb20iLCJzdWIiOiJjb3JleWhAaGVhcnRsZWdhY3kuY29tIiwiaXNzIjoiYXV0aC5oZWFydGxlZ2FjeWRldi5jb20iLCJhdWQiOiJQb3N0TWFuIiwiZXhwIjoxNDQ3OTU0NTUxLCJuYmYiOjE0NDc5NTQ1NTB9

*diff: Q1NTB9*

*Incoming Bearer Payload:*

**jwt.EncodedHeader**

    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

**jwt.EncodedPayload**
            
    eyJ1bmlxdWVfbmFtZSI6ImNvcmV5aEBoZWFydGxlZ2FjeS5jb20iLCJlbWFpbCI6ImNvcmV5aEBoZWFydGxlZ2FjeS5jb20iLCJzdWIiOiJjb3JleWhAaGVhcnRsZWdhY3kuY29tIiwiaXNzIjoiYXV0aC5oZWFydGxlZ2FjeWRldi5jb20iLCJhdWQiOiJQb3N0TWFuIiwiZXhwIjoxNDQ3OTU0NzQ0LCJuYmYiOjE0NDc5NTQ3NDN9

*diff: Q3NDN9*

**StartUp**

    app.UseJwtBearerAuthentication(config =>
            {
                config.AutomaticAuthenticate = true;
                config.TokenValidationParameters.ValidateAudience = true;
                config.TokenValidationParameters.ValidateIssuer = true;
                config.TokenValidationParameters.RequireExpirationTime = true;
                config.TokenValidationParameters.ValidateLifetime = true;
                config.TokenValidationParameters.RequireSignedTokens = true;
                config.TokenValidationParameters.ValidateIssuerSigningKey = true;
                config.TokenValidationParameters.ValidateSignature = true;
               
                config.SecurityTokenValidators.Clear();
                config.SecurityTokenValidators.Add(new CustomSecurityTokenValidator(appName)); // <-- signature validation happens here
            });

So inside of CustomSecurityTokenValidator I have this 

    var jwt = new JwtSecurityToken(securityToken);

I am curious if the JwtSecurityToken class is somehow modifying the jwt payload and if that was recently modified in rc1-final?

    public override ClaimsPrincipal ValidateToken(string securityToken,
            TokenValidationParameters validationParameters, out SecurityToken validatedToken)
        {
            var jwt = new JwtSecurityToken(securityToken);

**Comment by Tratcher** [comment]
@tushargupta51 I think this belongs in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

**Comment by dynamiclynk** [comment]
I was able to resolve the issue using following code. I will validate this works using the JwtSecurityToken ctor, and if so I will close this.

 private static SecurityToken SignatureValidator(string token, TokenValidationParameters validationParameters)
       

    {

            var authRepo = new AuthModelRepository();
            var authClient = authRepo.GetAuthClientByOAuthClientID(validationParameters.ValidAudience);

            var tokenParts = token.Split('.');
            var header = tokenParts?[0];
            var tokenHdr = JwtHeader.Base64UrlDeserialize(header);

            var payload = tokenParts?[1];
            var tokenPld = JwtPayload.Base64UrlDeserialize(payload);

            var signedData = $"{header}.{payload}";

            var signature = tokenParts?[2];

            var secretBytes = Convert.FromBase64String(authClient.Secret);

            var hmac = new HMACSHA256(secretBytes);
            var hmacKey = hmac.Key;

            var computedSignature = CryptoHashHelper.CalculateHMAC256Hash(signedData, hmacKey);

            if(signature!=computedSignature)
                throw new NullReferenceException("Invalid token signature specified.");

            var secToken = new JwtSecurityToken(token);
            return secToken;
        }

     public static string CalculateHMAC256Hash(string input, byte[] key)
        {
            var hmac256 = new HMACSHA256(key);
            byte[] byteArray = Encoding.UTF8.GetBytes(input);
            using (MemoryStream stream = new MemoryStream(byteArray))
            {
                byte[] hashValue = hmac256.ComputeHash(stream);
                return EncodingHelper.Base64Url.Encode(hashValue);
            }

        }

**Comment by Eilon** [comment]
@tushargupta51 have you had a chance to take a look at this? Does this issue belong in the AzureAD repo?

**Comment by tushargupta51** [comment]
@Eilon sorry I was out for last couple of weeks, didnt get a chance to look at this. This seems to belong  to azuread repo. @dynamiclynk can you move this issue here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet? Also, can you share the token generation and validation code?

**Comment by tushargupta51** [comment]
@dynamiclynk I moved this issue here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/326

**Comment by dynamiclynk** [comment]
@tushargupta51 thanks.
