### ISSUE TITLE
Question about Claims Transformation and CookieAuthentication

### ISSUE THREAD

**Issue by airomero** [aspnet/Security#583]
Hi, until MVC5 i used to get and refresh the user's claims like this:

             app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                SlidingExpiration = false,
                CookieName = "xxxx",
                ExpireTimeSpan = TimeSpan.FromHours(2),
                Provider = new CookieAuthenticationProvider
                {
                    OnResponseSignIn = ctx =>
                    {
                        ctx.Identity = TransformClaims(ctx); //My custom Claims Transformation
                    }
                }
            });

            app.UseWsFederationAuthentication(
                new WsFederationAuthenticationOptions
                {
                    MetadataAddress = ConfigurationManager.AppSettings.Get("WsFederationMetadataAddress"),
                    Wtrealm = ConfigurationManager.AppSettings.Get("WsFederationRealm"),
                    UseTokenLifetime = false,
                    SignOutWreply = ConfigurationManager.AppSettings.Get("WsFederationRealm"),
                }
            );

This allowed me to get the claims when the user signed in or when the cookie refreshes at a certain interval of time that i define. This was great because i didn't have to do it on every request. In aspnet5 i tried:

            app.UseCookieAuthentication(options =>
            {
                options.Events = new CookieAuthenticationEvents
                {
                    OnSignedIn = ctx =>
                    {
                        ctx.HttpContext.User = TransformPrincipal(ctx); //my custom claims transformation
                        return Task.FromResult<object>(null);
                    }
                };
                options.AutomaticAuthenticate = true;
                options.SlidingExpiration = false;
                options.CookieName = "xxxx";
                options.ExpireTimeSpan = TimeSpan.FromMinutes(5);
                
            });

            app.UseOpenIdConnectAuthentication(options =>
            {
                options.AutomaticChallenge = true;
                options.ClientId = "xxxx";
                options.Authority = "xxxxx";
                options.PostLogoutRedirectUri = "https://localhost:44328/";
                options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.UseTokenLifetime = false;
                
            });

But the user principal can't be modified. When i get to the controller, the user identity is not the one i modified inside CookieAuthentication, is the one that Azure AD (in this case) returns after login. I've also tried the new ClaimsTransformation Middleware "UseClaimsTransformation":

             app.UseClaimsTransformation(o => o.Transformer = new MyClaimsTransformer());

             public virtual Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
            {
                if (principal.Identity.IsAuthenticated)
                {
                    (principal.Identity as ClaimsIdentity).AddClaim(new Claim("Nationality", "AnyCountry"));
                    (principal.Identity as ClaimsIdentity).AddClaim(new Claim(ClaimTypes.Name, "NameFromDB"));
                }
                return Task.FromResult(principal);
            }

This works as expected, but it runs on every request and it'd be nice to set it an expire interval like you do on a cookie so you don´t have to hit the database on every request (in this case). I'm i missing something??

Thanks!!
(sorry for my english)

**Comment by Tratcher** [comment]
There are two events, OnSigningIn and OnSignedIn. Try using OnSigningIn instead.

**Comment by Eilon** [comment]
Closing for now. Please let us know if you still have any issues.

**Comment by airomero** [comment]
Thanks! It worked. So now i will use OnSigningIn instead of OnSignedIn to modify the principal claims. Thanks again.
