### ISSUE TITLE
Request email from Facebook auth

### ISSUE THREAD

**Issue by adrianhara** [aspnet/Security#586]
Hi,

I noticed that the Facebook call in CreateTicketAsync doesn't return the user's email. The code in CreateTicketAsync does try to get the email from the payload, but it's not there. 

I think the problem could be solved by specifying the "fields=email,..." in the query to the UserInformationEndpoint. I'd be happy to submit a PR for this, but before I try I wanted to ask if maybe I'm missing something and it actually should work as is.

Thanks!

**Comment by Tratcher** [comment]
This was just fixed: https://github.com/aspnet/Security/issues/565
