### ISSUE TITLE
JwtBearer projects targets dnx451 and dnxcore50

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Security#590]
I believe it should target net451 and dotnet5.4.

**Comment by Eilon** [comment]
@pranavkm any chance you can do a scan of all `src/**/project.json` files in the org and see if others need fixing?

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Security/commit/0db9a16c915ba5e686f6e001af82853edca63e09
