### ISSUE TITLE
Default Login Route Issue

### ISSUE THREAD

**Issue by Fosol** [aspnet/Security#603]
I've set the LoginPath and it's ignored.  It continues to use the default "/account/login".
```
            app.UseCookieAuthentication(options =>
            {
                options.LoginPath = new PathString("/authenticate/login");
            });

            app.UseIdentity();
            app.UseMvc();
```
Did something change in 1.0.0-rc1-final?

**Comment by Eilon** [comment]
@HaoK can you respond to this?

**Comment by HaoK** [comment]
Yeah cookies no longer share their options.  So the application cookie configuration actually live inside of IdentityOptions.Cookies.ApplicationCookie...

```
   services.AddIdentity(options => options.Cookies.ApplicationCokie.LoginPath = "");
```

**Comment by Fosol** [comment]
Is there a way to use services.Configure<MyConfigClass>(this.Configuration)?

I'd like to have these settings in an environment specific configuration file?

Is there a way to get the results of a services.Configure<MyConfigClass>(this.Configuration) immediately?

**Comment by HaoK** [comment]
yes you can configure directly against IdentityOptions using the overload the binds to configuration

**Comment by Fosol** [comment]
@Haok I'm not following how to get the immediate results of the configuration.
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<LIS.Mvc.Configuration.CookieConfiguration>(this.AuthenticationSection.GetSection("Cookie"));

          /// I want the results of that configuration immediately if possible.
           var cookie_config = ?
        }
```
You mention configure directly against IdentityOptions using the overload.  Do mean something like this?
```
        public void ConfigureServices(IServiceCollection services)
        {
            var identity_options = new IdentityOptions();
            services.AddInstance<IdentityOptions>(identity_options);
        }
```

**Comment by HaoK** [comment]
Why do you need the immediate results of the configuration?  That's not possible, as you are just setting up the DI container here,  you can get it out in the Configure method after services are built.  Or you can directly access config and read whatever you want at this point too.

**Comment by Fosol** [comment]
There are a number of things that need to be configured for DI.  Configuration often requires configuration files.

I suspect you want the middleware to use DI to get the configuration rather than get setup during the ConfigureServices method.  However I noticed that some of the middleware requires configuration in ConfigureServices and others requires in Configure.
