### ISSUE TITLE
RC1 regression for DNX5

### ISSUE THREAD

**Issue by danielcrenna** [aspnet/Security#606]
Hello,

Beta8 worked with moniker `DNXCORE5` but under the new moniker `DOTNET5_4` the RC1 bits are no longer compatible. The error is:

Severity	Code	Description	Project	File	Line
Error	NU1002	The dependency Microsoft.AspNet.Authentication.JwtBearer 1.0.0-rc1-final in project MyProject.Auth does not support framework .NETPlatform,Version=v5.4.	middleware.auth	C:\src\MyProject\project.json	26

**Comment by davidfowl** [comment]
@danielcrenna What do you mean? Can you show the project? Are you referencing the newer versions of the packages?

**Comment by Tratcher** [comment]
Duplicate https://github.com/aspnet/Security/issues/590

**Comment by danielcrenna** [comment]
@Tratcher Respecting that this is fixed, how can we get it? The regression means JWT in RC1 is unusable. I checked the nightly feeds and didn't see this.

**Comment by Tratcher** [comment]
The RC1 packages still work if your project continues to target dnxcore50. If you want to try the RC2 packages you need Microsoft.AspNet.Authentication.JwtBearer-1.0.0-rc2-16081 or later from the nightly feed.
