### ISSUE TITLE
[RC1] Cookie Authentication returns 401 and does not redirect to LoginPath

### ISSUE THREAD

**Issue by ddotlic** [aspnet/Security#607]
I'm seeing the regression in rc1 - instead of being redirected to the `LoginPath`, cookie auth simply returns 401 and my web app "sits" there doing nothing.

This worked in beta 7 and 8.

To repro, you need to install rc1, make a new project, add `[Authorize]` attribute to the `HomeController`, then simply add `app.UseCookieAuthentication(options => options.LoginPath = "/Account/Login");` (assuming you've added `AccountController` with `Login` action, but any controller and action - which exist, this is checked while executing - will work).

Opening the home page returns 401 and then... crickets.

This is annoying to say the least. I've seen several issues that are exact **opposite** of this one where people claim the middleware always redirects, but I can't get even one redirect right :disappointed: 

My environment is latest Windows 10 x64, Visual Studio 2015 Update 1 and ASP.NET 5 RC1 (Update 1, however confusing this is :smile: )

**Comment by ddotlic** [comment]
Forgot to say but of course one needs to add `Microsoft.AspNet.Authentication` and `Microsoft.AspNet.Authentication.Cookies` as dependencies to `project.json` (both version `1.0.0-rc1-final`).

I also tried switching to version `1.0.0-*` but this results in _HTTP 500 Internal Server Error_ and I can't even debug this :disappointed:

**Comment by PinpointTownes** [comment]
Try setting `AutomaticAuthenticate` and `AutomaticChallenge` to `true`:

```csharp
app.UseCookieAuthentication(options => {
    options.AutomaticAuthenticate = true;
    options.AutomaticChallenge = true;
    options.LoginPath = "/Account/Login";
});
```

**Comment by Tratcher** [comment]
This should only happen for AJAX requests. Unless you have some other auth middleware in the pipeline?

**Comment by ddotlic** [comment]
We actually had `AutomaticAuthenticate` in our project, I noted it was default and did not put it in the repro project, but the thing which does the trick is actually `AutomaticChallenge` - thanks!
FYI, there was no need to put in `AutomaticAuthenticate`, nor is it necessary to set `LoginPath` (as long as `/Account/Login` is what you have), I just tried.

Weird, I did not find this (`AutomaticChallenge`) in the `Annoucements` repo, or I just did not look hard enough?

**Comment by ddotlic** [comment]
> This should only happen for AJAX requests. Unless you have some other auth middleware in the pipeline?

Since I reproduced in an empty ASP.NET project, it is safe to assume that there is no other middleware in the pipeline.

Unless the default template added it, which I checked it did not :smiley: 

I'll just chalk this one up to the maturity (or lack of) of the framework at this point in time.
