### ISSUE TITLE
Split Microsoft.Owin.Security.Cookies.Interop into 2 packages

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#611]
We'd like to use the ticket serializer and the data protector adapter in the OWIN/Katana version of ASOS, but having a dependency on the cookies middleware is something we'd like to avoid. Separating the cookies extension from the rest of the package would be ideal.

https://github.com/aspnet/Security/pull/408#discussion_r38157266

https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/188#issuecomment-163291304

If you agreed with the general idea, I (or @MonkeyJamboree) would be happy to submit a PR. I guess simply creating a new `Microsoft.Owin.Security.Interop` package containing the ticket serializer and the data protector would be the best way to go.

/cc @Eilon @HaoK @Tratcher

**Comment by Eilon** [comment]
We are not planning on doing this; we recommend just copying the code as needed.

**Comment by PinpointTownes** [comment]
TBH, this doesn't seem like a good idea, as the ticket serializer adapter must exactly match the one used by ASP.NET 5, which is an easy task when using an official package but rather fragile when rolling your own version.

**Comment by PinpointTownes** [comment]
@Eilon if you don't like the idea of having a new package, maybe we could simply make the new `Microsoft.Owin.Security.Interop` I guess a sources package?

**Comment by MonkeyJamboree** [comment]
@Eilon out of curiosity, why is copying the code recommended over actually separating out `Microsoft.Owin.Security.Interop` into its own package? It seems to me since the namespace and code is assumed to be for interoperability, it should be consumable by others easily. If not, is there a package that's explicitly for this purpose instead? Creating unneeded dependencies in code or duplicating code are usually are not good things.

**Comment by Tratcher** [comment]
This package was built specifically for interop with Microsoft.Owin.Security.Cookies. 

One way to pull the  src is via git submodule.

**Comment by PinpointTownes** [comment]
> This package was built specifically for interop with Microsoft.Owin.Security.Cookies.

True, but the ticket serializer and the data protector shim are not specific to the cookies middleware. Sounds like a bad layering IMHO.

**Comment by blowdart** [comment]
The ticket serializer was for Forms auth. Which became cookie auth, Arguably it is for the cookie middleware.

Data Protection has a 4.5.2 implementation which you can bring in as a normal nuget package.

**Comment by PinpointTownes** [comment]
> The ticket serializer was for Forms auth. Which became cookie auth, Arguably it is for the cookie middleware.

That would be a valid argument if the ticket serializer was not HEAVILY used by Katana's OAuth2 middleware...

**Comment by blowdart** [comment]
It's not any more though is it? And the interop package itself wasn't for OAuth either. It was designed for forms authentication, nothing more.

**Comment by PinpointTownes** [comment]
> It's not any more though is it? 

Of course, since there's no OAuth2 middleware in vNext :trollface: 
But people (like me) might want to use the new ticket serialization format and the new data protection stack with Katana's authorization server. 

There's absolutely no difference between cookies and access tokens as they use the same exact serialization format (which explains why the OAuth2 authorization server/bearer middleware and the cookies middleware share the same TicketDataFormat). You're just introducing an artificial distinction.

**Comment by PinpointTownes** [comment]
So, wouldn't a new `Microsoft.Owin.Security.Interop` sources package be a good compromise?

**Comment by ryanwischkaemper** [comment]
+1

**Comment by DovydasNavickas** [comment]
+1
Yeah, that'd be great. And I really don't see any logical arguments why not... I understand you don't want to support multiple packages, but essentially it's splitting same code that you have. Not much of a difference for you, a whole lot benefits for us.

**Comment by PinpointTownes** [comment]
No Christmas gift for us? :smile:

**Comment by Eilon** [comment]
Re-opening, moving to Backlog, and marking as up-for-grabs. If someone wants to take a crack at this then we can publish the package with the code.

However, be warned: source packages have very few guarantees around them: stuff can change at any time. This is a use-at-your-own-risk type of scenario.

**Comment by PinpointTownes** [comment]
Ahhhhhhhhhh, thanks! :gift: :dancers: 

> Re-opening, moving to Backlog, and marking as up-for-grabs. If someone wants to take a crack at this then we can publish the package with the code.

I'll prepare a PR and send it ASAP :smile: 

> However, be warned: source packages have very few guarantees around them: stuff can change at any time. This is a use-at-your-own-risk type of scenario.

Would you prefer a standard package, with just the ticket serializer and the data protector?

**Comment by Eilon** [comment]
I think the audience for this package is super tiny, so I'd rather do something very un-fancy, if possible :smile:

**Comment by PinpointTownes** [comment]
As long as this package is managed by the ASP.NET team and published on NuGet, I'm fine :smile: 

Question: the Interop package doesn't have its own `PropertiesSerializer` and relies on the properties serializer developed for Katana, Currently, it's not really a big deal as Katana's `PropertiesSerializer` and vNext's `PropertiesSerializer` are identical, but it might cause weird issues if vNext's `PropertiesSerializer` had to be updated in the future. Is this something you plan to fix? /cc @HaoK

**Comment by Eilon** [comment]
Would need @HaoK and/or @Tratcher to answer that. They might both be on vacation, though.

**Comment by Tratcher** [comment]
We don't have any plans to fix it yet because it's not broken :-). If at some point it needs a similar interop approach then we could use a similar solution.
