### ISSUE TITLE
[OIDC] In OnMessageReceived, calling SkipToNextMiddleware causes error

### ISSUE THREAD

**Issue by brockallen** [aspnet/Security#616]
Perhaps there's something new in RC2 due to the comments here: https://github.com/aspnet/Security/issues/555

But as of RC1, this code:

```
options.Events = new OpenIdConnectEvents()
{
        OnMessageReceived = ctx =>
        {
            if (ctx.ProtocolMessage.Error != null)
            {
                ctx.SkipToNextMiddleware();
                ctx.Response.Redirect("~/Home/Error");
            }
            return Task.FromResult(0);
        }
};
```

Always causes this exception/stack trace:

```
ArgumentNullException: Value cannot be null.
Parameter name: ticket
Microsoft.AspNet.Authentication.AuthenticateResult.Success(AuthenticationTicket ticket)
```

Perhaps I'm handling errors incorrectly. But in any event, it seems I should be able to do what I'm trying do to (even if it's not the best way).

**Comment by Tratcher** [comment]
Yes this was regressed in rc1. It was fixed by https://github.com/aspnet/Security/pull/610 in rc2.

**Comment by brockallen** [comment]
Ok, thanks. Sorry I didn't find that while searching (I missed looking in PRs).
