### ISSUE TITLE
Share ASP.NET MVC 5 Forms authentication?

### ISSUE THREAD

**Issue by yuezhongxin** [aspnet/Security#617]
My question: There are two projects, one project is old (ASP.NET MVC 5), it is a login site, write code like `FormsAuthentication.SetAuthCookie("xishuai", false);`, another project ASP.NET 5 is rewritten, the site needs to obtain verification of the identity of another site, such as this code: `var name = User.Identity.Name;`, but I can not get found, here is my test.

### ASP.NET MVC 5

Web.config:

```xml
<system.web>
  <compilation debug="true" targetFramework="4.6" />
  <authentication mode="Forms">
    <forms name=".AppCookie" loginUrl="/Home/About" />
  </authentication>
  <httpRuntime targetFramework="4.6" />
</system.web>
```

HomeController:

```cs
public class HomeController: Controller
{
    [Authorize]
    public ActionResult Index()
    {
        var name = User.Identity.Name; // get 'xishuai' value
        return View();
    }

    public ActionResult About()
    {
        FormsAuthentication.SetAuthCookie("xishuai", false);

        ViewBag.Message = "Your application description page.";

        return View();
    }
}
```

I first tested under the two projects are ASP.NET MVC 5, such as `http://localhost: 24255/` `http://localhost: 24256/`, `User.Identity.Name` value which can be obtained to.

### ASP.NET 5

Startup.cs

```cs
app.UseCookieAuthentication((cookieOptions) =>
{
    cookieOptions.AutomaticAuthenticate = true;
    cookieOptions.AutomaticChallenge = true;
    cookieOptions.CookieName = ".AppCookie";
});
```

`"Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final"`

HomeController:

```cs
public class HomeController: Controller
{
    public ActionResult Index()
    {
        var name = User.Identity.Name; // get null
        return View();
    }
}
```

How do I solve this problem?

**Comment by blowdart** [comment]
The cookie format and the encryption pieces changed between MVC 6 and ASP.NET 5

Right now there's an unsupported compatibility package - it will become more official in the RC2 timeline. 

There is documentation at https://docs.asp.net/en/latest/security/data-protection/compatibility/cookie-sharing.html

**Comment by Tratcher** [comment]
That compat package only helps if you were using Katana v3. It doesn't go all the way back to Asp.Net 4 forms auth.

**Comment by yuezhongxin** [comment]
The above test is not no solution?

My real problem is that there are a lot of old projects (WebForms, MVC 3/4/5, etc.), and now we want incremental improvements to ASP.NET 5, so the process of transformation on the emergence of the above problems.

I read this blog: [Sharing authentication cookies between ASP.NET 4.x and ASP.NET 5 applications.] (Https://docs.asp.net/en/latest/security/data-protection/compatibility/cookie -sharing.html # sharing-authentication-cookies-between-asp-net-4-x-and-asp-net-5-applications), is not to achieve this effect you need to rewrite ASP.NET 4.x applications, such as using `app.UseCookieAuthentication(new CookieAuthenticationOptions {} ); GenerateUserIdentity...`, instead of using` FormsAuthentication.SetAuthCookie("xishuai", false);...`?

**Comment by yuezhongxin** [comment]
@blowdart I understand what you mean, about how long it can be compatible? and about RC2 timeline I can see it?

**Comment by yuezhongxin** [comment]
@Tratcher 😭

**Comment by yuezhongxin** [comment]
In ASP.NET 5, and I am trying to rewrite `FormsAuthentication.Decrypt(cookieValue)` [code](http://referencesource.microsoft.com/#System.Web/Security/FormsAuthentication.cs,21ad8e6b6f1681a2), using ` web.config-machineKey-validationKey` decryption, I just want to get `FormsAuthenticationTicket.Name`, but it feels more difficult.

**Comment by blowdart** [comment]
There is not FormsAuthentication.Decrypt(). The cookie format and the encryption methods got greatly improved. What you want to do simply won't work. We provide a back compat package, but as Chris says it's only going back one version.

**Comment by yuezhongxin** [comment]
@blowdart Ok, what this version is?

**Comment by blowdart** [comment]
I'm afraid I don't understand your question.

If your project was a new project from vs2013 the shim package will work.

If you upgraded a previous project to the katana platform which came with 2013 it should work.

**Comment by yuezhongxin** [comment]
@blowdart Sorry, my English is very bad.

Once again, I describe my problem, I have a lot of old sites (such as using WebForms), now I need to rewrite these sites to ASP.NET 5, but the login site has not been rewritten (using the Forms Authentication), now I rewrote a project to ASP.NET 5, need to verify the identity of a user (such as using User.Identity.Name), it is the beginning of what I do that test.

You mentioned: "It's only going back one version", I want to know what this version is? thanks.

**Comment by blowdart** [comment]
The version would be Katana v3. So you need to upgrade your existing sites to that first. Katana shipped with VS2013.

**Comment by yuezhongxin** [comment]
@blowdart Ok, but now I use VS2015 Update1, and some packages using rc2 version, if to solve the above problem, I can not use ASP.NET 5 is not it?

**Comment by blowdart** [comment]
I'm sorry, I'm not sure what you're asking again?

So, let's imagine you start a new project in .NET 4.5.2 from scratch. In VS2015. That ends up using Katana 3. That will accept the forward compat packages. There's more about Katana at http://www.asp.net/aspnet/overview/owin-and-katana/an-overview-of-project-katana

FormsAuthentication.SetAuthCookie() isn't part of Katana. You must bring your login system, and of course everything that depends upon it up to Katana first. Then you need to switch everything to use the compat shim. Then and only then will ASP.NET v5 understand the cookies

**Comment by yuezhongxin** [comment]
@blowdart 😂

I think I know what you mean, I need to first upgrade login system to Katana v3, and other systems using ASP.NET 4.x or ASP.NET 5 is possible, is not it?

**Comment by blowdart** [comment]
It should be possible yes, but it may be a lot of work for you. In all honesty you might want to look at some sort of OAuth system, using Identity Server https://identityserver.github.io/Documentation/

This means rather than drag everything up you would use whatever OAuth code is appropriate for each version of .NET, MVC, WebForms or whatever that you're using.

**Comment by yuezhongxin** [comment]
@blowdart Ok, I understand.

Now log into the system is not good upgrade, because it involves other systems, if a start using OAuth, this problem may not occur, and I really appreciate your patience, thank you very much.

However, if the ASP.NET 5 is compatible with Forms Authentication just fine.👻

**Comment by blowdart** [comment]
Forms Authentication comes in many versions.

To be precise we are only compatible with Katana 3.0's cookie middleware, which is used by forms authentication

**Comment by yuezhongxin** [comment]
@blowdart Ok, Thanks again.

**Comment by yuezhongxin** [comment]
@blowdart Now, I can not rewrite the login system code(Forms Authentication), but other systems rewritten ASP.NET 5, my idea is to decrypt Cookie in the new system code, I saw this project [DataProtection](https://github.com/aspnet/DataProtection) and relevant [documents](https://docs.asp.net/en/latest/security/data-protection/index.html), but I do not really understand, you think you can achieve?

**Comment by davidfowl** [comment]
As @blowdart says, that will be very hard to do but if you can't possibly change the other application then you'd need to write a separate middleware and component that understands the older cookie format. Basically porting FormsAuthentication.Decrypt https://github.com/Microsoft/referencesource/blob/master/System.Web/Security/FormsAuthentication.cs#L128 (which is a beast :smile:). And a bunch of logic from the old FormsAuthenticationModule https://github.com/Microsoft/referencesource/blob/master/System.Web/Security/FormsAuthenticationModule.cs#L327.

Some caveats:

- This code won't work on .NET Core (which means it won't work cross platform). At least not as is.
- It requires reading of the machine key section. Calling this method from an ASP.NET 5 application probably won't work the way you expect it to (if you just try to call FormsAuthentication.Decrypt), as there is no config hierarchy etc.

**Comment by yuezhongxin** [comment]
@davidfowl Yes, you say I fully understood, some time ago, I rewrote the code about `FormsAuthentication.Decrypt` in ASP.NET 5, the same as you say it is very difficult (😭😭😭), in addition to some of the caveats you said, there is involved a lot of other code, I'll try the next.

In addition to this way, do you think there are other solution?

**Comment by davidfowl** [comment]
> In addition to this way, do you think there are other solution?

Not that I'm aware of. Just try calling `FormsAuthentication.Decrypt` and see what breaks.

**Comment by yuezhongxin** [comment]
@davidfowl Ok, thank you very much, if there is a breakthrough, then please tell me.

**Comment by yuezhongxin** [comment]
@davidfowl Now what progress?

**Comment by davidfowl** [comment]
Nobody is working on this. Did you try one of the suggestions?

**Comment by yuezhongxin** [comment]
@davidfowl Sorry, now I do not try to do this, but in my plan, some time ago I tried the next, but the implementation is very difficult, because the code involved is very large, Chinese called "牵一发而动全身", later if there is progress, I'll get back to you Thank you. :)

In addition, about this, do you have any plans? The future will provide a compatible version?

**Comment by yuezhongxin** [comment]
* [MVC6 Decrypting a forms authentication cookie from another website](http://stackoverflow.com/questions/34265117/mvc6-decrypting-a-forms-authentication-cookie-from-another-website)
* [FormsAuthenticationTicketHelper.cs](https://gist.github.com/dazinator/0cdb8e1fbf81d3ed5d44#file-formsauthenticationtickethelper-cs)

**Comment by yuezhongxin** [comment]
I tried again, but still failed, I was ready to give up temporarily.

**Comment by blowdart** [comment]
As you appear to have gotten this working I'm going to close the issue.

There will not be any back compat package for anything other than Katana based sites.

**Comment by yuezhongxin** [comment]
I changed the ways to solve this problem, blog record: http://www.cnblogs.com/xishuai/p/aspnet-5-or-core1--identity-part-two.html

**Comment by johnhamm** [comment]
Incase anyone comes across this thread in the future, this may be helpful:
https://github.com/dazinator/AspNetCore.LegacyAuthCookieCompat
