### ISSUE TITLE
Correct usage of AntiForgery token in ASP.NET 5 in SPA application?

### ISSUE THREAD

**Issue by artemgrygor** [aspnet/Security#618]
In previous version of ASP.NET during SPA application the idea of AntiForgey token was following:

* add `@Html.AntiForgeryToken();` on the page
* add `__RequestVerificationToken` to the request
* override AuthorizeAttribute as ValidateJsonAntiForgeryTokenAttribute.

I don't really understand the authorization requirements (is there some good information source?) in ASP.NET 5 but looks like new behavior should be like this:
* add `asp-anti-forgerytaghelper`
* add `__RequestVerificationToken` to the request
* here should be the new requirement.

The question is: how to write this new authorization requirement and remove standard one? 
Could someone give some advice or point me on some example? Thanks

**Comment by artemgrygor** [comment]
Looks like I need to create custome middleware and check if it's json to use my way or use standard ` await _antiforgery.ValidateRequestAsync(context);`
But still not sure about it.

**Comment by blowdart** [comment]
The idea would not use cookie authentication in your SPA app - it's only persistent authentication mechanisms such as cookie or basic auth that create CSRF problems.

This question doesn't belong here though, there's an AntiForgery repo. https://github.com/aspnet/AntiForgery - you should open a discussion there.

**Comment by artemgrygor** [comment]
@blowdart thanks, will move to the AntiForgery repo.
