### ISSUE TITLE
External Providers negotiation eg Facebook Login via proxy server

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Security#619]
It doesn't appear that I can set a client proxy server via web.config anymore in the System.Net section.
I wanted to allow my app to access the external authentication providers without drilling out through my firewall.

Is this possible?
I know I could create an HttpClient and set the proxy on that but I don't have access to that object for the Facebook middleware. I thought I could use the BackHandler to set the proxy but proxy is not allowed to be set after HttpClient has already been created.

**Comment by blowdart** [comment]
@Tratcher - worth investigating, although global might be painful.

**Comment by PinpointTownes** [comment]
:+1: for directly exposing the `HttpClient` instead of a `HttpMessageHandler` :clap:

**Comment by Tratcher** [comment]
You should be able to set it like this:
```
            app.UseFacebookAuthentication(new FacebookOptions()
            {
                AppId = Configuration["facebook:appid"],
                AppSecret = Configuration["facebook:appsecret"],
                BackchannelHttpHandler = new HttpClientHandler()
                {
                   Proxy = new WebProxy("http://myproxy:9090/")
                }
            });
```

**Comment by mikes-gh** [comment]
Great
Just confirmed it works .

Looking at the object hierarchy and hadn't appreciated that an HttpClientHandler is actually an HttpMessageHandler.

I also tried it with a class that inherits form HttpClientHandler for my own custom handler and that works aswell

Thanks for your help
