### ISSUE TITLE
Dynamic cookie authentication LoginPath

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Security#626]
Is there a way to make cookie authentication `LoginPath` dynamic? Because I'm always losing all the routing data from which unauthenticated request was called. E.x., given `LoginPath = "accounts/login"`:
`http://localhost:8547/private-section/b/items/1` redirects to `http://localhost:8547/accounts/login`
I would like to get `http://localhost:8547/private-section/b/accounts/login`
or
`http://localhost:8547/public-section/promotion` redirects to `http://localhost:8547/accounts/login`
I would like to get `http://localhost:8547/public-section/accounts/login`

**Comment by Tratcher** [comment]
You can use options.Events.OnRedirectToLogin to customize the login path on a per request basis.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Cookies/Events/CookieAuthenticationEvents.cs#L40

**Comment by Muchiachio** [comment]
Hmm, but it's not available from `ICookieAuthenticationEvents`, should I extend `CookieAuthenticationEvents` and set it to options?

```C#
app.UseCookieAuthentication(options =>
{
    options.Events = new CustomEvents()
});
```

**Comment by Tratcher** [comment]
```
app.UseCookieAuthentication(options =>
{
    options.Events = new CookieAuthenticationEvents()
    {
        OnRedirectToLogin = context => {...};
    };
});
```
