### ISSUE TITLE
The values of Roles property in AuthorizeAttribute aren't trimmed

### ISSUE THREAD

**Issue by phenixdotnet** [aspnet/Security#627]
Hi.

Actually in the asp.net 5 (1.0.0-rc1-final) the values of the Roles property in Authorize attribute aren't trimmed before using it.
This lead to the situation where if for any reason you have this code:
```csharp

[Authorize(Roles="user, admin")]
public class MyController : Controller
{
}

```
Users with the admin role will never be authorized because the role name will be evaluated to " admin" and not "admin".

I can work on a patch and submit it if you want.

Regards

**Comment by HaoK** [comment]
Sure, if you want to submit a PR to fix this, that would be great :)

**Comment by phenixdotnet** [comment]
Hi.

PR submitted (#634)

Regards

**Comment by HaoK** [comment]
a8ef4df32a6ce8f47da882d34685768dafbe7c8e
