### ISSUE TITLE
TwitterHandler doesnt save all tokens as claims when SaveTokensAsClaims is true

### ISSUE THREAD

**Issue by SHAGGAR** [aspnet/Security#632]
TwitterHandler only adds the AccessToken to the list of claims and does not add the AccessTokenSecret.
Current:
```
if (Options.SaveTokensAsClaims)
{
	identity.AddClaim(new Claim("access_token", accessToken.Token, ClaimValueTypes.String, Options.ClaimsIssuer));
}
```

Should this not be
```
if (Options.SaveTokensAsClaims)
{
	identity.AddClaim(new Claim("access_token", accessToken.Token, ClaimValueTypes.String, Options.ClaimsIssuer));
	identity.AddClaim(new Claim("access_token_secret", accessToken.TokenSecret, ClaimValueTypes.String, Options.ClaimsIssuer));
}
```
Instead?

A workaround for this is to use the OnCreatingTicket event to add the claims yourself after authentication, but it would be way more convenient if all the claims were there when SaveTokensAsClaims is true.  

Also would it be worthwhile to add some constants for the token ClaimTypes ?

**Comment by Tratcher** [comment]
https://dev.twitter.com/web/sign-in/implementing
"The token and token secret should be stored and used for future authenticated requests to the Twitter API."
Yes, it sounds like we need both of them.
