### ISSUE TITLE
Changing roles (claims) for a user during a session doesn't update the claim.

### ISSUE THREAD

**Issue by theonlylawislove** [aspnet/Security#633]
If I implement the identity interfaces ```IUserRoleStore<User>``` and return a valid set a roles for a user, they get added to the user's ```ClaimsPrincipal``` for authentication.

If I update this user's role "live", the ```ClaimsPrincipal``` doesn't get reflected for the user until he/she logs out and back in.

User roles change dynamically in my application from background services. Is there a way I can force this to refresh?

**Comment by HaoK** [comment]
SignOut/SignIn is the recommended way to clear the cookie/refresh the claims, this behavior is intentional, as by default you don't want to hit the database on every request.
