### ISSUE TITLE
OpenIdConnectOptions Event Handler Question

### ISSUE THREAD

**Issue by jimnorth55** [aspnet/Security#637]
Is there an example anywhere in this repository that shows how to wire up a custom OpenIdConnect authentication event handler.  In particular, I want to add a AuthorizationCodeReceived handler for the purpose of implementing the hybrid flow.

I see that there is an open issue (#456) regarding out-of-the-box hybrid flow support--looks like in RC2.  However, I was hoping to get something working sooner.

Thanks

**Comment by Tratcher** [comment]
Not currently, but it should look a lot like this other sample:
https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L102-L117

**Comment by jimnorth55** [comment]
Thanks Chris.  I just wasn't getting the correct syntax.  The example you
referenced did the trick.
