### ISSUE TITLE
BuildRedirectUri does not work easily when under proxy

### ISSUE THREAD

**Issue by timmydo** [aspnet/Security#638]
#540 
@Tratcher 

Here is my situation: I have a pre-rc2 web app that runs on kestrel under azure web app (IIS) using HttpPlatformHandler. I think this means basically IIS is proxying all requests to my webserver, which is listening on a random internal port (using http).

So basically, when under a proxy, BuildRedirectUri()'s Request.Scheme is not the same as what the user is seeing. So my google oauth doesn't work because the redirect URI has http (what the server is listening with) rather than https (what I'm using to browse the site).

Since this is fairly out-of-the-box, there should be an easy way to fix/override this?

**Comment by davidfowl** [comment]
Are you using the platform handler middleware? (Assuming you're on RC1)

**Comment by timmydo** [comment]
Yes as far as I can tell, startup code here (currently using pre rc2 referencing Microsoft.AspNet.IISPlatformHandler/1.0.0-rc2-16069 though):

https://github.com/timmydo/gearup/blob/sf/GearUp/Startup.cs#L98

**Comment by davidfowl** [comment]
If you use bleeding edge bits then you have to keep up with the announcements https://github.com/aspnet/Announcements/issues/123. Also that middleware should be further up the stac

**Comment by timmydo** [comment]
Thanks. Got it working. Knowing what I did last week, that announcement wouldn't have made sense to me. Makes sense now though!

Note to self, this code doesn't throw any errors but also doesn't do anything:

```
app.UseOverrideHeaders(h => new OverrideHeaderOptions() { ForwardedOptions = ForwardedHeaders.All });
```

for people finding this thread online, this is the correct version (put it at the top of the Configure method) :

```
app.UseOverrideHeaders(config => config.ForwardedOptions = ForwardedHeaders.All);
```
