### ISSUE TITLE
SaveTokenAsClaim for JwtBearer

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#639]
For consistency - the JwtBearer MW should also have a `SaveTokenAsClaim` setting - this would make it easier to get to the token e.g. for contacting user info in claims transformation - or "delegation"

**Comment by leastprivilege** [comment]
it probably should go on `AuthenticationOptions` and not `RemoteAuthenticationOptions`

**Comment by Tratcher** [comment]
It wouldn't belong on the base AuthenticationOptions because it wouldn't apply to things like Cookies, Basic, etc.. If we do this I'd just duplicate the property for JWT rather than moving it up to AuthOptions.

**Comment by Eilon** [comment]
We're considering putting the data into the `AuthenticationProperties` instead of as claims. Would that make sense here?

**Comment by leastprivilege** [comment]
I thought this was meant to be a convenient way to get to the access token without having to implement an event. The token should be available as a property (or on the protocol message in OIDC) anyways.

**Comment by Tratcher** [comment]
The auth properties flow with the ClaimsPrincipal all the way back to the app, and through the cookie.

**Comment by PinpointTownes** [comment]
@Eilon @Tratcher when adding `SaveTokensAsClaims` to the OIDC middleware, I had considered using `AuthenticationProperties`, as it was the best candidate for that. Sadly, retrieving authentication properties is much harder than retrieving a simple claim (not to mention that it requires using a very strange syntax).

```csharp
var token = context.User.FindFirst("access_token")?.Value;
```

```csharp
var context = new AuthenticateContext("[authentication scheme]");
await context.Authentication.AuthenticateAsync(context);

if (context.Principal == null || context.Properties == null) {
    throw new InvalidOperationException("The request is not authenticated.");
}

string token;
context.Properties.TryGetValue("access_token", out token);
```

**Comment by Eilon** [comment]
Putting on Backlog for now. We will revisit the popular suggestion at a later time. (Popular == not the one I made :smile: )

**Comment by Tratcher** [comment]
@vibronet recommends cutting SaveTokensAsClaims outright on the grounds that the ClaimsPrincipal (and the auth properties) go into the session cookie and that's the wrong place to save this kind of information. Moreover the lifetimes of the access and refresh tokens can be fundamentally different from the login session. Finally if there are additional tokens acquired later they would have to be handled separately. The recommended way to handle the tokens is to get them via the events and store them independently.

**Comment by PinpointTownes** [comment]
I disagree.

`SaveTokensAsClaims` is far from being perfect, but it's an extremely convenient option to make API requests after an authentication/authorization flow (IIRC, @Eilon used it in one of his projects :smile:).

Removing this option would also make retrieving the access/identity/refresh tokens from an `AccountController` much harder (extracting the access/refresh tokens from `ExternalLoginInfo` to store them in a database became a quite popular pattern).

**Comment by brockallen** [comment]
> I disagree.

+1

**Comment by vibronet** [comment]
It might be convenient, but it is fundamentally broken. The identity token is retrievable from a controller via SaveSignInToken if you need it. The access and refresh token don't belong to a session, as they have completely different lifetimes and uses. Why should an expired access token linger in the ClaimsPrincipal after it is long expired? Why should a refresh token be buried in something tied to a web session when in fact it represents a consent that should be available regardless of how one access the app (think granting consent for a web app to access an API, then accessing the app through a mobile client - I should not have to get a brand new refresh token). Why should a developer have the access and refresh token acquired at sign in time handled differently than the ones acquired after sign in via normal OAuth2 code flow?
The middlewares as they exist today handle sign in/identity verificatin. Access token and refresh token acquisition at the same time as sign in are an optimization to save roundrips, not fundamental changes in the nature of a sign in. I 100% agree that we need a good mechanism to make those tokens available to the app, because that's where they are needed - but per the above treating the claims collection as a property bag is not the cleanest design IMO. Can we come out with some other place we could save those tokens, so that they are available to the app without introducing asymmetries and special cases?

**Comment by leastprivilege** [comment]
I think this is all a bit mixed up here - 

this issue is about the JwtBearer middleware - 

my point was mainly that there needs to be an easy way to get to the access token from within the API. You might need it in claims transformation (e.g. for the userinfo endpoint) or for delegation.
Since this token can potentially come from different source (authZ header, query string etc) - the Jwt middleware should make it available somehow.

Now if this is a claim - or some other well defined (and consistent) place  that is easy to reach - I don't care.

Now for APIs that is easy since there is no session involved.

Generally speaking I agree with Kevin - SavenTokensAsClaims is not perfect but is exactly what most people end up doing anyways - tuck away the tokens in the cookie so they can get to it for calling an API, renewing and logout hints.

It doesn't necessarily need to be the claims collection - but not sure we have the time to invent another abstraction.

**Comment by vibronet** [comment]
I would rather take a bit more time and get it right than put it in the wrong place and pay for this for years to come. I understand this is convenient, but the claims collection is not a generic property bag. If we need a generic property bag, or something specific for this functionality, we can introduce it. Besides, I thought we did have something to that effect in the AuthProperties... but I do agree with @PinpointTownes that the current accessor code is too complicated. Maybe we can work on simplifying that.

**Comment by PinpointTownes** [comment]
> It might be convenient, but it is fundamentally broken. The identity token is retrievable from a controller via SaveSignInToken if you need it.

AFAIK, the raw identity token is rarely needed as-is, specially from user code. The only place where it's frequently used is in the OIDC events, to add `id_token_hint` to the logout message before redirecting the user to the end session endpoint (and it's something the OIDC handler now automatically does).

And... hem, `ClaimsIdentity.BootstrapContext` is not really the most user-friendly API we've seen :smile: 

```csharp
var identity = (ClaimsIdentity) User.Identity;
var token = (string) identity.BootstrapContext;
```

```csharp
var token = User.FindFirst("id_token")?.Value;
```

> The access and refresh token don't belong to a session, as they have completely different lifetimes and uses. Why should an expired access token linger in the ClaimsPrincipal after it is long expired? Why should a developer have the access and refresh token acquired at sign in time handled differently than the ones acquired after sign in via normal OAuth2 code flow?

Those are definitely valid points, but to address them we'd need to introduce a new persistence layer to store and bind the tokens with their corresponding sessions directly in the OAuth2/OIDC middleware (similarly to what ADAL does, I guess). IMHO, it's not something the security middleware should be responsible of (but it might be a good exercise for ASP.NET Identity).

> Why should a refresh token be buried in something tied to a web session when in fact it represents a consent that should be available regardless of how one access the app (think granting consent for a web app to access an API, then accessing the app through a mobile client - I should not have to get a brand new refresh token).

I disagree: a refresh token doesn't necessarily represent a consent. The actual meaning totally depends on the authorization server implementation: one could allow revoking a particular refresh token (and optionally, the entire chain of access tokens issued using it) without ever revoking the consent.

Binding it with a web session is no different than binding the identity token with the `ClaimsIdentity` or keeping protocol specific claims/properties like `nonce`/`iat`/`nbf`/`exp`/`at_hash` in the final authentication cookie (which is useless and makes it bigger, we should definitely fix that before RTM).

> The claims collection is not a generic property bag.

Totally agree, though it's sadly no longer true these days (JWT treats everything as claims, even non-user attributes).

> Besides, I thought we did have something to that effect in the AuthProperties... but I do agree with @PinpointTownes that the current accessor code is too complicated. Maybe we can work on simplifying that.

:+1:

**Comment by leastprivilege** [comment]
Before we "dream up" something in a rush (only run past by the people on this thread) - I would opt for removing the feature altogether and continue writing code in the notification (sorry - events) to transfer whatever data we need to the "session".

After looking at the past customer projects I did - while "SaveTokensAsClaims" might be convenient for demos - I haven't come across a single solution where NO claims transformation has taken place (typically in SecurityTokenValidated) to remove/amend the claim set. Since this has to be done anyways - you can also decide if you want to transfer tokens to to the claims (or store them somewhere else).

**Comment by Tratcher** [comment]
We're going to look at a few different approaches next week. Fell free to share any suggestions you have.  If we don't come up with something readily then we'll probably remove the existing code until we can.

**Comment by Tratcher** [comment]
@leastprivilege I've been looking into this feature as a whole and I don't see how it applies to JwtBearer. In general we're talking about storing things like OAuth access tokens that are used to make API calls later.  However, a JWT shouldn't contain those kinds of tokens. It sounds like you were asking to store the original JWT, but how is that useful to you later? It seems strange that the same JWT would be accepted as an access token at a user-info-endpoint.

**Comment by PinpointTownes** [comment]
> It sounds like you were asking to store the original JWT, but how is that useful to you later?

Keeping the original access token is extremely useful for delegation scenarios, where the API that receives the access token can query a second (distinct) API on behalf of the original caller. 

FWIW, I've been asked to implement a similar feature in aspnet-contrib's validation and introspection middleware.

**Comment by Tratcher** [comment]
OK. How is that different from just copying the request authentication header?

The original JWT is also stored in the ClaimsIdentity.BootstrapContext.

**Comment by PinpointTownes** [comment]
Actually, it's not different, but don't forget that one can use the JWT events to retrieve the access token from somewhere else: query string or request form (which is fully spec-compliant). Not having to retrieve the token manually from the headers just help make the separation of concerns better for the application code. 

:+1: for BC, even if it's not enabled by default and is not really user-friendly.

**Comment by leastprivilege** [comment]
what @PinpointTownes said ;)

**Comment by HaoK** [comment]
ace166fa31af61a6c9924873e6bdcb45e7785d5d
