### ISSUE TITLE
Rewrite JwtBearer TokenValidation Test

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Security#640]
Currently the test is using a token generated on AAD which means that the token will expire every 60 days (or some set interval). For this unit test, we should use a statically generated token that does not expire and not depend on an external authentication authority.

https://github.com/aspnet/Security/blob/bbff105e4dd5105722159fe792c17b2b39baaea3/test/Microsoft.AspNetCore.Authentication.Test/JwtBearerTests.cs#L435-L450

**Comment by Eilon** [comment]
Ideally we would mock away this logic and rewrite the test to avoid these stricter checks.
