### ISSUE TITLE
GetClaimsFromUserInfoEndpoint option available for all Flows with response_type token

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#644]
OIDC spec says in "5.4.  Requesting Claims using Scope Values"

"The Claims requested by the profile, email, address, and phone scope values are returned from the UserInfo Endpoint, as described in Section 5.3.2, when a response_type value is used that results in an Access Token being issued. However, when no Access Token is issued (which is the case for the response_type value id_token), the resulting Claims are returned in the ID Token."

IOW - the `GetClaimsFromUserInfoEndpoint` option should be available for all flows that result in an access token.

Right now it seems the options is only checked if code flow is used (from `HandleCodeOnlyFlow`).

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/Security/issues/456
