### ISSUE TITLE
Claim Authentication (windows authentication)

### ISSUE THREAD

**Issue by vinny-Jo** [aspnet/Security#649]
I am trying to build a webapi service using windows authentication with a custom role provider using Claim authentication. Unfortunately I am not able to find a way to use ClaimTransformationAppBuilderExtension since it is only exposed has part of Microsoft.Aspnet.Http.Abstractions. How can we reference or use from Microsoft.AspNet.Builder.Internal.ApplicationBuilder the Microsoft.AspNet.Builder.ClaimsTransformationAppBuilderExtensions.UseClaimsTransformation?

example: app.UseClaimsTransformation(o => o.Transformer = new MyClaimsTransformer());

**Comment by Tratcher** [comment]
I don't quite understand the question. UseClaimsTransformation is defined here: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication/ClaimsTransformationAppBuilderExtensions.cs#L45
It's an extension method on Microsoft.AspNet.Builder.IApplicationBuilder. You need to include the Microsoft.AspNet.Authentication package and the Microsoft.AspNet.Builder namespace. 

It's also not clear what any of this has to do with windows auth.

**Comment by vinny-Jo** [comment]
I am trying to use UseClaimsTransformation but it is not exposed from configure (startup method). Yes I included Authentication and Builder as reference but [[Internal]].ApplicationBuilder does not have the UseClaimsTransformation exposed so it can used as app.UseClaimsTransformation(o => o.Transformer = new ProspectClaimsTransformer());

**Comment by Tratcher** [comment]
Before:
```
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Serialization;
using Microsoft.AspNet.Authorization;
…
public void Configure(Microsoft.AspNet.Builder.IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            Microsoft.AspNet.Builder.Internal.ApplicationBuilder appBuild = (Microsoft.AspNet.Builder.Internal.ApplicationBuilder)app;
            app.UseClaimsTransformation(o => o.Transformer = new ProspectClaimsTransformer());
```
After:
```
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Serialization;
using Microsoft.AspNet.Authorization;
…
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            app.UseClaimsTransformation(o => o.Transformer = new ProspectClaimsTransformer());
```

**Comment by vinny-Jo** [comment]
Hi Chris,

Yes it is working…

Thanks very much.

Regards,



Vincent Jourdain

Architect/Lead Developer


D: 0800 408 1451

**Comment by vinny-Jo** [comment]
Yes it is working
