### ISSUE TITLE
I get a 500 on JWT token expiration 

### ISSUE THREAD

**Issue by tim-cools** [aspnet/Security#650]
When I call mu api after my JWT token has expired I get a 500 with following exception:

    SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired. ValidTo: '01/08/2016 17:09:45' Current time: '01/11/2016 10:40:22'.

My action is decorated with [AllowAnonymous] so I actually expect the exception to be swallowed and my user not to be authenticated. Or do I make a wrong assumption here?

Thanks in advance!

**Comment by PinpointTownes** [comment]
It's a known bug, that was fixed in RC2. You can read https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/191 for more information.

**Comment by tim-cools** [comment]
Thanks again!
