### ISSUE TITLE
rc1-final  HttpContext.Authentication.SignInAsync() do not work who can help me  thanks

### ISSUE THREAD

**Issue by 717009629** [aspnet/Security#651]
rc1-final  HttpContext.Authentication.SignInAsync() do not work, who can help me  thanks!!!!

```C#
 public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication();
        }

        public void Configure(IApplicationBuilder app, ILoggerFactory loggerfactory)
        {
            loggerfactory.AddConsole(LogLevel.Information);

            app.UseCookieAuthentication(options =>
            {
                options.AutomaticAuthenticate = true;
            });
            app.Run(async context =>
            {
                if (!context.User.Identities.Any(identity => identity.IsAuthenticated))
                {
                    var user = new ClaimsPrincipal(new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, "bob") }, CookieAuthenticationDefaults.AuthenticationScheme));
                    await context.Authentication.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, user);
                    context.Response.ContentType = "text/plain";
                    await context.Response.WriteAsync("Hello First timer");
                    return;
                }
               context.Response.ContentType = "text/plain";
                await context.Response.WriteAsync("Hello old timer");
            });
        }
        public static void Main(string[] args) => WebApplication.Run<Startup>(args);
    }
}
```

```JSON
"dependencies": {
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.DataProtection": "1.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final"
  }
```
![xl b p51pjy 6f3 d4swt m](https://cloud.githubusercontent.com/assets/16289643/12262331/3decb374-b962-11e5-97d7-8138b1301c1d.png)
After SignInAsync ,  the user  is not Authenticated!!!!!!!!

**Comment by blowdart** [comment]
You need to create the ClaimsIdentity with an authentication type. You've missed that out. If you check the principal you created, and the identity within it you'd also see IsAuthenticated is false.

For example

    var userIdentity = new ClaimsIdentity("SuperSecureLogin");
    userIdentity.AddClaims(claims);
    var userPrincipal = new ClaimsPrincipal(userIdentity);

**Comment by 717009629** [comment]
@blowdart  
but  i have  added an authentication type
var user = new ClaimsPrincipal(new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, "bob") }, CookieAuthenticationDefaults.AuthenticationScheme));

the code above can work？  my english is not good

**Comment by blowdart** [comment]
Oh yes, so you have. Before you call signinasync is the isauthenticated property on the principal's single identity true?

**Comment by 717009629** [comment]
@blowdart  not true， but after signinasync , the next request is also not authenticated

**Comment by blowdart** [comment]
OK so it needs to be true, before you call signin, because we don't change the principal, only persist it.

Could you try creating the identity in a line on its own?

**Comment by 717009629** [comment]
@blowdart   but this is the sample on github https://github.com/aspnet/Security/tree/dev/samples/CookieSample
i change the  version to rc1-release ,it does not work as expected

**Comment by 717009629** [comment]
@blowdart  thankyou  ！ I solved it !   it has nothting to do with the code , after i clear the browser cookies, it workes. thank you

**Comment by blowdart** [comment]
Ah yes. The simple sample doesn't do that :D
