### ISSUE TITLE
HttpAbstractions-DefaultAuthenticationManager Signin issue - "No authentication handler is configured to handle the scheme ..."

### ISSUE THREAD

**Issue by sebnema** [aspnet/Security#652]
Hi,
I created custom IdentityRoleStore and IdentityUserStore classes, which are retrieving claims from both AD and SQL Server.
          
During registration of a new account, “await _signInManager.SignInAsync(user, isPersistent: false)” code block raised error even trying many different combination of cookie and identity options.
Finally, We realized Microsoft.AspNet.Http.Authentication.Internal.DefaultAuthenticationManager  “SignInAsync” method didn’t run as expected. 
Even though “signInContext.Accepted” is true,  “No authentication handler is configured..” error raised  (if statement is not working!. See screenshot). But user’s signedin ticket and cookie are created. 

![httpabstraction no handler configured issue screenshot](https://cloud.githubusercontent.com/assets/10426499/12289645/627c3506-b9e5-11e5-97e0-f5f5656a3162.png)

Adding lock statement as below resolved the issue for now. But editing Microsoft.AspNet.Http would mean, we always need to manage the package by ourself – which is not an option at the customer. 

```
public override async Task SignInAsync(string authenticationScheme, ClaimsPrincipal principal, AuthenticationProperties properties)
        {
            if (string.IsNullOrEmpty(authenticationScheme))
            {
                throw new ArgumentException(nameof(authenticationScheme));
            }

            if (principal == null)
            {
                throw new ArgumentNullException(nameof(principal));
            }

            var handler = HttpAuthenticationFeature.Handler;

            var signInContext = new SignInContext(authenticationScheme, principal, properties?.Items);
            if (handler != null)
            {
                await handler.SignInAsync(signInContext);
            }

            lock (thisLock)
            {
                if (!signInContext.Accepted)
                {
                    throw new InvalidOperationException($"No authentication handler is configured to handle the scheme: {authenticationScheme}");
                }
            }
        }
```

Q1:  handler.SignInAsync(signInContext) method is setting **signInContext.Accepted**  to true, and already has “await” keyword on it. Shouldn’t it be enough to make it thread safe? Is this a bug or bydesign?

Q2:  When I checked the DefaultAuthenticationManager.SigninAsync call hierachy, I didn’t find any logic calling the method other than mine . 
Furthermore, why the debugger is stepping into the if statement, whilst **signInContext.Accepted**  is true (which is very wierd).

Q3: Can you please investigate the issue more? I can send my test code which reproducing the issue. 

Note: Identiy and cookie configuration at Startup is as below:

```
services.AddAuthentication();

services.AddIdentity<ApplicationUser, IdentityRole>(
               options =>
               {
                   options.Cookies.ApplicationCookie.AutomaticAuthenticate = true;
                   options.Cookies.ApplicationCookie.AutomaticChallenge = true;
                   options.Cookies.ApplicationCookieAuthenticationScheme = "ApplicationCookie";
                   options.Cookies.ApplicationCookie.AuthenticationScheme = IdentityCookieOptions.ApplicationCookieAuthenticationType = "ApplicationCookie";
                   options.Cookies.ApplicationCookie.LoginPath = new PathString("/User/Login");
                   options.Cookies.ApplicationCookie.LogoutPath = new PathString("/User/Logout");
                   options.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromMinutes(5);
                   options.Cookies.ApplicationCookie.ReturnUrlParameter = CookieAuthenticationDefaults.ReturnUrlParameter;
                   options.Cookies.ApplicationCookie.SlidingExpiration = true;
                   options.Cookies.ApplicationCookie.CookieHttpOnly = true;
                   options.Cookies.ApplicationCookie.CookieSecure = CookieSecureOption.SameAsRequest;
                   options.Cookies.ApplicationCookie.SystemClock = new SystemClock();
                   options.Cookies.ApplicationCookie.Events = new CookieAuthenticationEvents();
                   options.Cookies.ApplicationCookie.CookieName = "TBMMNet";
                   options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(10);
                   options.Lockout.MaxFailedAccessAttempts = 10;
                   options.Lockout.AllowedForNewUsers = false;
               })
               .AddUserStore<IdentityUserStore<ApplicationUser>>()
               .AddRoleStore<IdentityRoleStore<IdentityRole>>()
               .AddDefaultTokenProviders();
```

Thx. 

Sebnem

**Comment by russdaygh** [comment]
The statement in question negates the boolean so the exception is being thrown as expected.

        v
    if (!signInContext.Accepted)

**Comment by Tratcher** [comment]
Sounds like a strange race condition. Something in the SignIn call stack may not be correctly flowing Tasks.  Can you also share the section of your Startup.Configure with all of your authentication middleware?

Including the the stack trace for your debug break point above would also help us check if the issue was up the stack.

**Comment by Tratcher** [comment]
Uploading a repro app to a github repo is another good way to help.

**Comment by Eilon** [comment]
@sebnema please share a repro app with us (either internally or on GitHub).

**Comment by sebnema** [comment]
Hi,
I created a Git repo https://github.com/sebnema/HttpAbstractions-1.0.0-rc1-NoAuthHandler

What I did is;
- Downloaded HttpAbtractions 1.0.0-rc1 sources from https://github.com/aspnet/HttpAbstractions/tree/1.0.0-rc1
- Added CookieWebAppTest test project. 
- Set build configuration of all projects in the solution as "Produce outputs on build".
- Created Bootstrapper class which is an extension class of IServiceCollection, then added AddFormsAuthentication and UseFormsAuthentication methods for Cookie configuration. 
- Created custom Authentication classes under folders "Auth" and "Identity".

Repro Steps:
- I run CookieWebAppTest project and Click Register for a new account, It throws "no auth handler.." exception at Line: 142 in Microsoft.AspNet.Http.Authentication.Internal.DefaultAuthenticationManager class.
  I added lock to all "if(!signInContext.Accepted)" statements, then issue resolved.
- I clicked on Logoff, "No authentication handler is configured to handle the scheme: Microsoft.AspNet.Identity.External" error occurs. 
  Even if I use only one Applicationcookie, SigninManager is trying to signout from other cookie schemas as below. 

  SigninManager.cs: 
```
  public virtual async Task SignOutAsync()
        {
            await Context.Authentication.SignOutAsync(Options.Cookies.ApplicationCookieAuthenticationScheme);
            await Context.Authentication.SignOutAsync(Options.Cookies.ExternalCookieAuthenticationScheme);
            await Context.Authentication.SignOutAsync(Options.Cookies.TwoFactorUserIdCookieAuthenticationScheme);
        }
```

**Comment by Eilon** [comment]
@sebnema why are you running from source code? I highly recommend using the packages from NuGet.org.

**Comment by Eilon** [comment]
@Tratcher can you take a look at the repro app?

**Comment by sebnema** [comment]
To be able to find where the error occurred, I should have debugged. I couldn't find .pdb files on nuget.org. If there is, please let me know where to find.

**Comment by Tratcher** [comment]
@HaoK there's a bit too much Identity in this for me. Can you take a look?

**Comment by HaoK** [comment]
So the root issue is that identity expects several cookie middleware to be present and it registers them via UseIdentity typically.  ApplicationCookie is the only one you have registered.  It also expects an ExternalCookie/TwoFactor cookies.  Hence when it attempts to sign out the external cookie you get the error stating that no "external" handler was found for that authentication scheme.

Refer to: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/BuilderExtensions.cs#L36

**Comment by Tratcher** [comment]
@HaoK I think that only explains the log off scenario. I don't think that explains the Register race condition.

**Comment by Eilon** [comment]
@HaoK can you rummage through the code and see if we're missing an `await` somewhere?

**Comment by sebnema** [comment]
@HaoK For loggoff issue: I am only using Application Cookie. Why do I need to add other cookie configurations for External and Two factor, even if I did not use them. I couldn't get the essence here. Besides, I am not calling app.UseIdentity. Instead, I configured cookie as below.

 app.UseCookieAuthentication(options =>
            {
                options.AutomaticAuthenticate = true;
                options.AutomaticChallenge = true;
                options.AuthenticationScheme = "ApplicationCookie";
                options.LoginPath = new PathString("/User/Login");
                options.LogoutPath = new PathString("/User/Logout");
                options.AccessDeniedPath = new PathString("/User/AccessDenied");
                options.ExpireTimeSpan = TimeSpan.FromMinutes(5);
                options.ReturnUrlParameter = CookieAuthenticationDefaults.ReturnUrlParameter;
                options.SlidingExpiration = true;
                options.CookieHttpOnly = true;
                options.CookieSecure = CookieSecureOption.SameAsRequest;
                options.SystemClock = new SystemClock();
                options.Events = new CookieAuthenticationEvents();
            });

Thx.

**Comment by HaoK** [comment]
If you are calling SignInManager.SignOut with identity, it assumes you are using UseIdentity.  If you don't want to use all of identity, you are free to directly manage and use the cookies yourself, and via SignInAsync/SignOutAsync on HttpContext.Authentication

**Comment by HaoK** [comment]
@sebnema For the behavior with the lock:

'I run CookieWebAppTest project and Click Register for a new account, It throws "no auth handler.." exception at Line: 142 in Microsoft.AspNet.Http.Authentication.Internal.DefaultAuthenticationManager class. I added lock to all "if(!signInContext.Accepted)" statements, then issue resolved.'

What is the auth hander that its complaining about not finding?

**Comment by sebnema** [comment]
@HaoK  Handler is 

> Microsoft.AspNet.Authentication.Cookies.CookieAuthenticationHandler.

 
It seems login and logoff has the same issue. SignInAsync and SignoutAsync methods in AuthenticaitionHandler is calling context.Accept().
```
 public async Task SignInAsync(SignInContext context)
        {
            if (ShouldHandleScheme(context.AuthenticationScheme, handleAutomatic: false))
            {
                SignInAccepted = true;
                await HandleSignInAsync(context);
                Logger.LogInformation(3, "AuthenticationScheme: {scheme} signed in.", Options.AuthenticationScheme);
                context.Accept();
            }
            else if (PriorHandler != null)
            {
                await PriorHandler.SignInAsync(context);
            }
        }
```
It seems context.Accept(); doesn't finish its job or Accepted property it has set, is also called by somewhere else. Thus, every method in DefaultAuthenticationManager using the below code block is failing. 
```
if (!signInContext.Accepted)
                {
                    throw new InvalidOperationException($"No authentication handler is configured to handle the scheme: {authenticationScheme}");
                } await PriorHandler.SignOutAsync(context);
            }
```

**Comment by HaoK** [comment]
Can you see What the scheme that's being asked for is?

**Comment by sebnema** [comment]
ApplicationCookie. 
![shouldhandlescheme_signinasync](https://cloud.githubusercontent.com/assets/10426499/12797087/eb0a2630-caca-11e5-9647-7bcce8bb509b.PNG)

Are you able to debug?

**Comment by HaoK** [comment]
@sebnema can you update your app to latest rc2 bits and see if it still repros?  If it does, please update your repro and I will debug it locally

**Comment by cuiliang** [comment]
@sebnema  you can try comment out code that setting AuthenticationScheme.
I have this problem in rc1, and soved it if no custom AuthenticationScheme setted.

**Comment by Fosol** [comment]
This is definitely a bug.  Just spent a few hours debugging.  @cuiliang provided the key for me to get my stuff 'working'.  rc1 doesn't let you set the AuthenticationSchema successfully.

**Comment by HaoK** [comment]
I'll see if this still repros in RC2 and add test coverage either way covering using custom authentication schemes

**Comment by HaoK** [comment]
Okay I took a look and here's what I think is going on.

It looks to me like you don't really want to use sign in manager if you are registering your own cookie middleware.  What is going on mostly related to that mismatch.  You should replace the `SignInManager.LogOut` with direct calls to `context.Authentication.SignOut()` passing in the authenticationScheme you specify in the cookie options.

Try that and I think that should fix the issue you are seeing.

**Comment by HaoK** [comment]
Closing, I believe the root issue is that even though you changed the auth scheme of the cookies, your signout calls (especially if you are using identity) need to be updated as well to pass in the updated scheme.  Your repro is doing a hash of some identity and some not, which makes it easy to run into this misconfiguration.

**Comment by SzymonSasin** [comment]
I have similar setup and problem. 

 I am using the UseIdentity on app with a custom( but 95% the same) code for AddIdentity. My change is to not use roles and to provide a custom  IUserClaimsPrincipalFactory<TUser>.
When I run on IISExpress I am able to log ing/out only once, after that I am getting the " No authentication handler is configured". However if I switch to Kestrel, everything works just fine.

I want to add that I did not change the auth scheme at all.
