### ISSUE TITLE
Can't find working example of getting first_name claim using Facebook rc2

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Security#654]
I can get email and name from the authentication request But even looking through the source I can't work out how to get first_name or last_name.
I think I need to use the userendpoint.

It would be great if this could be added to the social sample.

**Comment by mikes-gh** [comment]
Looking at the source for

FacebookHandler

all the fields are added to the UserEndPoint request but only a few fields (hard coded) are read are read from the json.  So even if I put first_name in fields collection and I see the value in the json reponse it is not in the claims collection.
Still not sure how to proceed.

**Comment by Tratcher** [comment]
Hook into `Options.Events.CreatingTicket` and you can add additional claims.

**Comment by mikes-gh** [comment]
Ok Ill try and work that out myself are there any docs?

I think it would be useful to

Add  all the "free" Facebook fields from email and public_profile to the FacebookHelpers and FacebookHandler.

These include
#email scope
email (already mapped)

#public_profile scope
id (already mapped)
name (already mapped)
first_name (ClaimTypes.GivenName)
last_name (ClaimTypes.Surname)
age_range (urn:facebook:age_range)
link (already mapped)
gender (ClaimTypes.Gender)
locale (ClaimTypes.Locality)
timezone (urn:facebook:timezone)
updated_time (urn:facebook:updated_time)
verified (urn:facebook:verified)

Would you accept a PR for this?
Should be very straight forward I would just need a bit of guidance on the unknown mappings

Do you want to go

**Comment by mikes-gh** [comment]
@Tratcher 

Would you accept a PR for the above?
Its a very simple change.

**Comment by VijayBhatter** [comment]
I am stuck in my project as there is not much documentation on how to Hook into Options.Events.CreatingTicket and add additional claims.

And code example would be of great help.

**Comment by mikes-gh** [comment]
@Tratcher Trouble with this event is the JSON responce is no longer available and you have to construct a new request with the extra fields repeating all the logic in the handler and helper and resulting in an extra trip to the facebok userinfoenpoint.
As soon as this repo gets building again I have a change to add all the public_profile fields to the helper and handler plus a better set of defaults so we can have a minimal configure like the Google authentication.

**Comment by Tratcher** [comment]
The raw JSON should be available in OAuthCreatingTicketContext.TokenResponse.Response that's passed into CreatingTicket.

**Comment by mikes-gh** [comment]
That only gives the JSON for the access_token not for the fields requested from the userinfoendpoint.
Those are already saved as claims by the FacebookHandler.
The only way to get more fields is by resubmitting a new request to the userinfoendpoint and parsing the response

**Comment by Tratcher** [comment]
Ah, wrong field. Check OAuthCreatingTicketContext.User

**Comment by mikes-gh** [comment]
Got it
Man thats obscure especially as User in HttpContext is normally a claims principal.
Very confusing.

**Comment by mikes-gh** [comment]
The working code for reference

``` app.UseFacebookAuthentication(options =>
            {
                options.AppId = "9999999999999";
                options.AppSecret = "123456789";
                options.Scope.Add("email");
                options.Scope.Add("public_profile");
                options.Fields.Add("name");
                options.Fields.Add("email");
                options.Fields.Add("first_name");
                options.Fields.Add("last_name");
                // Only if you use a proxy server
                options.BackchannelHttpHandler = new HttpClientHandler()
                {
                    Proxy = new WebProxy("http://proxyserver:3128")
                };
                options.Events = new OAuthEvents
                {
                    OnCreatingTicket =  context =>
                    {
                        var user =  context.User;

                        var firstName = user.Value<string>("first_name");
                        if (!string.IsNullOrEmpty(firstName))
                        {
                            context.Identity.AddClaim(new Claim(
                                ClaimTypes.GivenName, firstName,
                                ClaimValueTypes.String, context.Options.ClaimsIssuer));
                        }

                        var lastName = user.Value<string>("last_name");
                        if (!string.IsNullOrEmpty(lastName))
                        {
                            context.Identity.AddClaim(new Claim(
                                ClaimTypes.Surname, lastName,
                                ClaimValueTypes.String, context.Options.ClaimsIssuer));
                        }
                        return Task.FromResult(0);
                    }
                };
            });
```

**Comment by mikes-gh** [comment]
@VijayBhatter  the above should help.

**Comment by VijayBhatter** [comment]
Thank you @mikes-gh for the help.

**Comment by mikes-gh** [comment]
I have a pull request which greatly simplifies config of Facebook authentication.
https://github.com/aspnet/Security/pull/677
