### ISSUE TITLE
Redundant mutliple local variables.

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#665]
In reviewing PR 33, https://github.com/aspnet/Security/pull/653/files I notice that the code around https://github.com/aspnet/Security/blob/tratcher/feedback/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L143 has a bunch on redundant var declarations. 

```C#
else if (Options.AuthenticationMethod == OpenIdConnectRedirectBehavior.FormPost)
{
    var inputs = new StringBuilder();
    foreach (var parameter in message.Parameters)
    {
        var name = HtmlEncoder.Encode(parameter.Key);
        var value = HtmlEncoder.Encode(parameter.Value);

        var input = string.Format(CultureInfo.InvariantCulture, InputTagFormat, name, value);
        inputs.AppendLine(input);
    }
```

could be written differently to reduce GC pressure:

                var inputs = new StringBuilder();
                foreach (var parameter in message.Parameters)
                {
                    inputs.AppendLine(
                        string.Format(CultureInfo.InvariantCulture, 
                        InputTagFormat, 
                        HtmlEncoder.Encode(parameter.Key), 
                        HtmlEncoder.Encode(parameter.Value)));
                }

**Comment by PinpointTownes** [comment]
To quote @davidfowl... "WTF"? :open_mouth:

**Comment by Tratcher** [comment]
This is just style, it has no functional or perf impact. I'd expect the same compiler output from both.
