### ISSUE TITLE
Authorization infrastructure does not handle "per action permissions" use case well

### ISSUE THREAD

**Issue by kwaclaw** [aspnet/Security#670]
In WebApi 2 we used an AuthorizationFlterAttribute to implement the following permissions based concept:
* Each controller action has a permission code associated.
* Roles are associated with a set of permissions. This set can change over time.
* A user has one or more roles.
* Authorization is determined by checking if any of the user's roles is associated with the action's permission code.

This was easy to use by the developer. He/she only had to decorate an action with the corresponding attribute.

It seems the new policy based approach in ASP.NET 5 makes it hard to implement his concept, because there is no way for the Handle method of the AuthorizationHandler to include the permission code in its arguments. The only way I could solve this problem was to create one new policy for each unique permission code. Since there is a large number of actions, I now have to create an equally large number of policies. It would not be a huge change to the infrastructure to be able to attach extra information to the attribute and pass it through to the handler in the AuthorizationContext, or even pass the attribute through itself. For example, the handler code could then look like this:

	protected override void Handle(AuthorizationContext context, PermissionRequirement requirement) {
		var userRoles = context.User.FindAll(System.Security.Claims.ClaimTypes.Role);
		var permissionsAttribute = context.Attribute as PermissionAttribute;
		if (permissionsAttribute == null)
			return;
		if (myPermissionsChecker.RolesHavePermission(userRoles, permissionsAttribute.Permission)) {
			context.Succeed(requirement);
		}
	}

This would only require a single policy, and the developer would not be burdened with having to create a new policy everytime a new controller action is added.

**Comment by brockallen** [comment]
This might help (in RC2): https://github.com/aspnet/Security/issues/630

**Comment by kwaclaw** [comment]
From where is the resource picked up? I don't see a change to the AuthorizeAttribute to include  a Resource property.

**Comment by brockallen** [comment]
You would pass it explicitly. It's the imperative approach. You're right that it's harder to from declaratively.

**Comment by kwaclaw** [comment]
I see. I would prefer the declarative option though.

**Comment by davidfowl** [comment]
When you're using MVC, the resource by default is the filter's authorization context. You can use that to get information about the action being executed and that's how you can discover the attribute:

```C#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();

        services.AddAuthorization(options =>
        {
            options.AddPolicy("Permissions", builder =>
            {
                builder.Requirements.Add(new PermissionsRequirement());
            });
        });

        services.AddSingleton<IAuthorizationHandler, PermissionsHandler>();
        services.AddSingleton<IPermissionService, PermissionService>();
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
    {
        loggerFactory.AddConsole(LogLevel.Debug);

        app.UseIISPlatformHandler();

        app.Use((context, next) =>
        {
            // This would be cookie or bearer auth, I'm just hacking to show how it works
            context.User = new ClaimsPrincipal(new ClaimsIdentity("Something"));

            return next();
        });

        app.UseMvc();
    }

    // Entry point for the application.
    public static void Main(string[] args) => WebApplication.Run<Startup>(args);
}

public class PermissionService : IPermissionService
{
    public bool RolesHavePermission(IEnumerable<Claim> userRoles, string permissions)
    {
        // Implement something real
        return string.Equals(permissions, "Teacher");
    }
}

public class PermissionsRequirement : IAuthorizationRequirement
{
}

public class PermissionsHandler : AuthorizationHandler<PermissionsRequirement, Microsoft.AspNet.Mvc.Filters.AuthorizationContext>
{
    private readonly IPermissionService _permissionService;
    public PermissionsHandler(IPermissionService permissionService)
    {
        _permissionService = permissionService;
    }

    protected override void Handle(Microsoft.AspNet.Authorization.AuthorizationContext context, PermissionsRequirement requirement, Microsoft.AspNet.Mvc.Filters.AuthorizationContext resource)
    {
        var userRoles = context.User.FindAll(ClaimTypes.Role);
        var permissionsAttribute = resource.ActionDescriptor.FilterDescriptors.Select(f => f.Filter).OfType<PermissionsAttribute>().SingleOrDefault();

        if (permissionsAttribute == null)
        {
            return;
        }

        if (_permissionService.RolesHavePermission(userRoles, permissionsAttribute.Permission))
        {
            context.Succeed(requirement);
        }
    }
}

public interface IPermissionService
{
    bool RolesHavePermission(IEnumerable<Claim> userRoles, string permissions);
}

[Authorize("Permissions")]
public class SomethingController
{
    [Permissions("Student")]
    [HttpGet("/")]
    public string Get()
    {
        return "Hello World";
    }
}

// Marking this attribute with IFilterMetadata makes it accessible on MVC primitives
public sealed class PermissionsAttribute : Attribute, IFilterMetadata
{
    public string Permission { get; }

    public PermissionsAttribute(string permission)
    {
        Permission = permission;
    }
}
```

**Comment by davidfowl** [comment]
Tiny improvement to get rid of the auth policy altogether:

```
public class PermissionsAuthorizationFilter : AuthorizeFilter
{
    public PermissionsAuthorizationFilter() : base(GetPolicy())
    {
    }

    private static AuthorizationPolicy GetPolicy()
    {
        var policy = new AuthorizationPolicyBuilder()
                .AddRequirements(Requires.Permissions)
                .Build();

        return policy;
    }

    public override Task OnAuthorizationAsync(Microsoft.AspNet.Mvc.Filters.AuthorizationContext context)
    {
        // Only check if there's a permissions attribute on the action
        if (context.ActionDescriptor.FilterDescriptors.Any(fd => fd.Filter is PermissionsAttribute))
        {
            return base.OnAuthorizationAsync(context);
        }

        return Task.FromResult(0);
    }
}
```

And Startup.Configure can be changed to:

```C#
services.AddMvc(options =>
{
    options.Filters.Add(new PermissionsAuthorizationFilter());
});

services.AddSingleton<IAuthorizationHandler, PermissionsHandler>();
services.AddSingleton<IPermissionService, PermissionService>();
```

**Comment by blowdart** [comment]
To be fair, creating a policy per permission is just as much work as adding a parameter onto each attribute.

**Comment by davidfowl** [comment]
> To be fair, creating a policy per permission is just as much work as adding a parameter onto each attribute.

Possibly, it depends on what data needs to be round tripped to the Handler. You can't really pass any data besides the policy name itself. If permissions was a flags enum for example you couldn't do the same thing.

**Comment by blowdart** [comment]
That's not true at all. Requirements can have parameters. That's how you pass them down. So you'd have a general permissions parameter which takes data in the constructor, and then that is passed as the requirement parameter into Handle.

**Comment by davidfowl** [comment]
You'd have to enumerate all permissions up front and add a policy for each with the same name:

`Startup.ConfigureServices`

```C#
services.AddAuthorization(options =>
{
    foreach (var permission in GetPermissions())
    {
        options.AddPolicy(permission, builder =>
        {
            builder.AddRequirements(new PermissionRequirement(permission));
        });
    }    
});
```

```C#
public class PermissionsRequirement : IAuthorizationRequirement
{
    public string Permissions { get; private set; }

    public PermissionsRequirement(string permissions)
    {
        Permissions = permissions;
    }
}

public class PermissionsHandler : AuthorizationHandler<PermissionsRequirement>
{
    private readonly IPermissionService _permissionService;
    public PermissionsHandler(IPermissionService permissionService)
    {
        _permissionService = permissionService;
    }

    protected override void Handle(Microsoft.AspNet.Authorization.AuthorizationContext context, PermissionsRequirement requirement)
    {
        var userRoles = context.User.FindAll(ClaimTypes.Role);

        if (_permissionService.RolesHavePermission(userRoles, requirement.Permissions))
        {
            context.Succeed(requirement);
        }
    }
}
```

**Comment by davidfowl** [comment]
That matches our pattern but does feel a bit cumbersome having to turn your permissions into a concrete class in order to round trip state. If you were trying to represent ACLs for example would you model it that way?

**Comment by blowdart** [comment]
ACLs are a strange think, and don't map to web permissions easily. Instead you'd probably see a claim like "DocumentPermissions" with a CRUD value which spans the library, and then you'd use resource based auth to further drill in, just like a file ACL acts on a file, not a path.

**Comment by blowdart** [comment]
Just like you enumerated all the permissions up front and put an attribute for each. It's much the same amount of work!

**Comment by davidfowl** [comment]
What if we turned this:

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authorization/AuthorizationOptions.cs#L9 into a Policy provider (like Cors has) and the default implementation would be based on the policy map, but in this case it could be implemented by making permissions based on whatever data source you were using.

```C#
public interface IAuthorizationPolicyProvider
{
  Policy GetPolicy(string name);
}
```

**Comment by blowdart** [comment]
Well now we're changing an entire feature between RC and RTM and you already know it's way too late for that.

**Comment by davidfowl** [comment]
It's not, It's adding an interface and come to think about it, it should have probably been implemented this way from the beginning.

**Comment by blowdart** [comment]
If you wanted to drag the permissions from a database then add an empty requirement, and inject the repository into the Handler class. Then just apply that single policy everywhere, and act according on route data (ugh, fragile)

**Comment by blowdart** [comment]
It's not just adding an interface. It's changing how we designed it. Which you signed off on :p We have a policy provider. It's the authorization service.

**Comment by davidfowl** [comment]
> If you wanted to drag the permissions from a database then add an empty requirement, and inject the repository into the Handler class. Then just apply that single policy everywhere, and act according on route data (ugh, fragile)

Super hacky.

> It's not just adding an interface. It's changing how we designed it. Which you signed off on :p We have a policy provider. It's the authorization service.

It really isn't. It's literally replacing calls to `AuthenticationOptions.GetPolicy` by a call to an interface, but that's an implementation detail.

> It's not just adding an interface. It's changing how we designed it. Which you signed off on :p We have a policy provider. It's the authorization service.

It's not, the `IAuthorizationService` does a *LOT* more than look up policies.

**Comment by blowdart** [comment]
Talk to @HaoK about it when he's back. But we've been told no more redesigns, we should *not* be changing this at such a late stage.

**Comment by davidfowl** [comment]
Sounds great :smile: 

For completeness, with this new interface, the above request would look like this:

```C#
public interface IAuthorizationPolicyProvider
{
    Task<AuthorizationPolicy> GetPolicy(string policyName);
}

public class PermissionsPolicyProvider : IAuthorizationPolicyProvider
{
    public Task<AuthorizationPolicy> GetPolicy(string policyName)
    {
        var policy = new AuthorizationPolicyBuilder()
                    .AddRequirements(new PermissionsRequirement(policyName))
                    .Build();

        return Task.FromResult(policy);
    }
}

public class PermissionsRequirement : IAuthorizationRequirement
{
    public string Permissions { get; private set; }

    public PermissionsRequirement(string permissions)
    {
        Permissions = permissions;
    }
}
```

```C#
public class PermissionsHandler : AuthorizationHandler<PermissionsRequirement>
{
    private readonly IPermissionService _permissionService;
    public PermissionsHandler(IPermissionService permissionService)
    {
        _permissionService = permissionService;
    }

    protected override void Handle(Microsoft.AspNet.Authorization.AuthorizationContext context, PermissionsRequirement requirement)
    {
        var userRoles = context.User.FindAll(ClaimTypes.Role);

        if (_permissionService.RolesHavePermission(userRoles, requirement.Permissions))
        {
            context.Succeed(requirement);
        }
    }
}
```

Startup.ConfigureServices

```C#
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc();

    services.AddSingleton<IAuthorizationPolicyProvider, PermissionsPolicyProvider>();
    services.AddSingleton<IAuthorizationHandler, PermissionsHandler>();
}
```

Controller

```C#
public class SomethingController
{
    [Authorize("Student")]
    [HttpGet("/")]
    public string Get()
    {
        return "Hello World";
    }
}
```

**Comment by davidfowl** [comment]
@kwaclaw Bottom line is that with the new authz system, there's always a bit of indirection with policies. If you need to round trip information from the callsite (the action method in this case), there's 2 options, using a policy or a resource. In the case of an MVC action, the resource will always be the an MVC specific AuthzContext, so the only thing you can do is map policy names to your permissions concept.

**Comment by kwaclaw** [comment]
Thanks for all the discussions.

Considering that authorization is often applied to specific actions, I would have expected that I can use any action-specific information that my use case requires in the processing of the authorization.

Well, since I am using MVC I still have the old AuthorizationFilterAttribute.

**Comment by davidfowl** [comment]
@kwaclaw You can. All @blowdart is saying that based on your requirements (or what we understood from them), you don't need anything specific other than the permissions decorated on the action. That's morally equivalent to a policy name. Do you do something more complex? (Even then, you can grab the Mvc AuthzContext to get more specific information about the action method).

**Comment by kwaclaw** [comment]
Yes, I can, but I have to create one policy per permission code. In the past, I just had to attach the attribute.
Now I have to add another step that should not be necessary.
And yes, I can use reflection to auto-create those policies on startup - but that means I am hacking the design.

**Comment by HaoK** [comment]
@davidfowl @blowdart RE the IPolicyProvider, that's been on my todo list for a long time but without an actual scenario to drive it, it kept getting pushed...  This was one tracking issue for it: https://github.com/aspnet/Security/issues/266

I agree that's we should have something that is only responsible for the policy mapping.  Is this something we want to try and do this week for Ask mode?

**Comment by HaoK** [comment]
00ceeb026262bc848404d056416709dc306a57df
