### ISSUE TITLE
ASP.NET 5 Identity with one table and 4 columns

### ISSUE THREAD

**Issue by kjanshair** [aspnet/Security#678]
I creating an ASP.NET MVC 6 application which uses Identity with Entity Framework on SQL Server. By default, it creates 5 tables in the database

AspNetRoles
AspNetClaims
AspNetLogins
AspNetRoles
AspNetUsers

But I want only 1 table in the database instead of these 5 with 4 columns integer Identity Column, UserName, Email and Password (Hashed). How do I implement or create a custom user store?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Identity#723
