### ISSUE TITLE
OAuth 2.0 Implicit Flow & CORS Conflict

### ISSUE THREAD

**Issue by DuNuNuBatman** [aspnet/Security#679]
I'm having an issue enabling both OAuth JWT Bearer tokens and CORS on the same service:

``` C#
public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options =>
            {
                options.AddPolicy("AllowAllOrigins", builder =>
                {
                    builder.AllowAnyOrigin();
                    builder.AllowAnyHeader();
                    builder.AllowAnyMethod();
                    builder.AllowCredentials();
                });
            });

            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseIISPlatformHandler();

            app.UseCors("AllowAllOrigins");

            app.UseJwtBearerAuthentication(options =>
            {
                options.AutomaticAuthenticate = true;
                options.RequireHttpsMetadata = false;
                options.Audience = "93b15e04-09d1-456c-a394-867e14bf4cc8";
                options.Authority = "domain.com";
            });

            app.UseMvc();
        }
````

The issue seems to be with the line: `options.AutomaticAuthenticate = true;`
When this is set to true, I'm not getting back the correct Access-Control-Allow-Origin header and I get the error: 
> No 'Access-Control-Allow-Origin' header is present on the requested resource.

Setting this value to false, I can access the unsecured controllers on the web service, but not secured ones.

**Comment by blowdart** [comment]
If you set automaticauthenticate to false you need to tell the secured endpoints which authentication scheme to use;

So, you'd do something like

    [Authorize(ActiveAuthenticationSchemes=JwtBearerDefaults.AuthenticationScheme]

Or if you prefer to do it in policy

    public void ConfigureServices(IServiceCollection services)
    {
        options.AddPolicy("WebApi", policy =>
        {
            policy.AuthenticationSchemes.Add(JwtBearerDefaults.AuthenticationScheme);
            policy.RequireAuthenticatedUser();
        });
    }

If you change the scheme name in the bearer options you'd need to use that instead of 'JwtBearerDefaults.AuthenticationScheme'
