### ISSUE TITLE
Authentication with ASP 5 and Identity/SignInManager

### ISSUE THREAD

**Issue by kylefowler** [aspnet/Security#681]
It seems from the limited documentation that this is intended to sit on top of and work with the Indentity framework, but there doesnt look to be an interface to create an `IdentityUser` as a result of logging in with Authentication methods. I'm not sure if this is a bug or something I'm missing. Taking a look at the Account controller from the default ASP 5 .NET project in VS, the method that expects to handle the successful login has the user logged in but not where it expects it.

```c#
public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null)
{
            if (HttpContext.User.Identities.Any(identity => identity.IsAuthenticated))
            {
                _logger.LogDebug("Users have been logged in by an oauth/facebook/google provider");
            }
            var info = await _signInManager.GetExternalLoginInfoAsync();
            // Always null
            if (info == null)
            {
                return RedirectToAction(nameof(Login));
            }
}
```

Is there a trick to get these two systems to work together or is it a bug that they authenticate on different levels?

**Comment by HaoK** [comment]
You create users via the UserManager.   The template flow creates a user in the confirmation method, see: https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Controllers/AccountController.cs#L201

**Comment by kylefowler** [comment]
In theory yes, but it never gets to that point. It bails out before forwarding there, https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Controllers/AccountController.cs#L165

Where it needs to get to here in order to get forwarded to the ExternalLoginConfirmation. https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Controllers/AccountController.cs#L192

**Comment by HaoK** [comment]
No, the external login identity its looking for specifically comes from the authenticationScheme defined in the identity options, by default its something like "Microsoft.AspNet.Identity.External".  HttpContext.User is not relevant to SignInManager at all

**Comment by HaoK** [comment]
So basically something needs to sign in using the authenticationScheme that this method is expecting if you are trying to get the template flow to work.  Note this external cookie flow is purely a mechanism that the templates created, you are free to replace this/roll your own at the end of the day

**Comment by kylefowler** [comment]
Ok, thanks. Just digging in from the templates it made it seem like they were interconnected. Good to know.
