### ISSUE TITLE
How to control Google/Facebook/Twitter cookie expiration?

### ISSUE THREAD

**Issue by pepevc** [aspnet/Security#682]
It looks Google maintains the user for 10 minutes logged in.

It is not clear in the documentation how to control this.

**Comment by brockallen** [comment]
You don't have control over google. You only have control over your own application's cookie. Configure your own application's cookie in the cookie authentication middleware options.

**Comment by pepevc** [comment]
It does not work. I set:

 ```
           app.UseCookieAuthentication(options =>
            {
                options.ExpireTimeSpan = TimeSpan.FromSeconds(10);
            });
```

and the cookie does not expire in 10 seconds.

**Comment by brockallen** [comment]
Are you also ASP.NET Identity? It registers its own cookie middleware and uses it.

**Comment by pepevc** [comment]
Does not work either:

`            services.AddIdentity<User, Role>((options =>
            {
                options.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromSeconds(60);
            }))`

This time it doesn't even store the cookie and does not log you in.

**Comment by brockallen** [comment]
You'll have to wait for Monday when Microsoft rolls in to help then :)

**Comment by Tratcher** [comment]
Please upload a repro app to github and describe the repro steps.

**Comment by pepevc** [comment]
It is just the initial template using Identity, adding:

            app.UseGoogleAuthentication(options => 
            {
                options.ClientId = Configuration["Authentication:Google:ClientId"];
                options.ClientSecret = Configuration["Authentication:Google:ClientSecret"];
            });

Another issue is Google asks the user for "offline" permission. The website logs out the user when it wants.

**Comment by pepevc** [comment]
The problem is Identity framework. I replaced it by a simple Cookie method it and it does not expire now.
