### ISSUE TITLE
ASP.NET 5 renames for project.json and some code comments

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Security#689]
ASP.NET 5 in description field in project.json and some code comments (about a dozen or so places) all in.
I don't mind doing the PR for this? or do you have an overall plan for this type of stuff?

ASP.NET 5 --> ASP.NET Core 1.0

**Comment by Tratcher** [comment]
https://blogs.msdn.microsoft.com/webdev/2016/02/01/an-update-on-asp-net-core-and-net-core/

**Comment by mikes-gh** [comment]
Thanks.  I thought thst refered to vnexc packages  and docs not source sorry for noise.

**Comment by Eilon** [comment]
@mikes-gh we're still in the process of updating all the various places that have the old text, but thanks for the offer!
