### ISSUE TITLE
__TwitterState cookie not deleted after authentication

### ISSUE THREAD

**Issue by Praburaj** [aspnet/Security#69]
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Security.Twitter/TwitterAuthenticationHandler.cs#L107

Probably needs to pass in cookie options while deleting here.

**Comment by cottsak** [comment]
Hey folks @Praburaj @Tratcher I think this is still broke.
I'm using `Microsoft.Owin.Security.Twitter` version 3.0.1 and my cookie is not being deleted. This is a pretty massive security hole.
