### ISSUE TITLE
Returning 401 and JSON

### ISSUE THREAD

**Issue by bragma** [aspnet/Security#699]
Hi,
I'm using UseJwtBearerAuthentication. On a failed authentication (ex: expired token), the middleware throws and exception causing the server to return 500. I'd like instead to return 401 and a JSON explaining the problem.
I'm not sure I've understood the "OnAuthenticationFailed" event, but I've not been able to do anything from there. So, I've resolved to "UseExceptionHandler" and I've been able to intercept Security related Exceptions, but I am not sure on how to allow other exception types to be handled by the default error handler, such as "UseDeveloperExceptionPage".

My setup is:

```
app.UseExceptionHandler(appBuilder =>
{
    appBuilder.Use(async (context, next) =>
    {
        var error = context.Features[typeof(IExceptionHandlerFeature)] as IExceptionHandlerFeature;

        if (error != null && error.Error is SecurityTokenExpiredException)
        {
            // Send expired response
        }
        else if (error != null && error.Error is SecurityTokenInvalidSignatureException)
        {
            // Send bad signature response
        }
        else if (error != null && error.Error != null)
        {
            // Another exception type. How to let it pass through so it's caught by UseDeveloperExceptionPage?
        }
        else
        {
            await next();
        }
    });
});
```

Is this the suggested way of handling Security exceptions?
Thanks!

**Comment by Tratcher** [comment]
OnAuthenticationFailed is the right place for this. You should be able to write your own response and call `context.HandleResponse()` to keep the exception from being re-thrown.

**Comment by bragma** [comment]
@Tratcher thanks for the answer, is there any example or can you please provide one? I've tried with this but it does not work:

```
					OnAuthenticationFailed = context =>
					{
						// Authentication failed
						context.Response.StatusCode = 401;
						context.HandleResponse();

						return Task.FromResult(0);
					}
```

**Comment by bragma** [comment]
I've checked the code, the magic seems to happen here:

https://github.com/aspnet/Security/blob/297c72aa2176265d680b0d102ac1932220919053/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L168

If I call "HandleResponse", the code calls Success and fails with another exception because Token is not set. What's weird is that even "SkipToNextMiddleware" somehow goes down a similar path and complains because Token is not set. In both cases, another exception is thrown (and I don't get my 401).

**Comment by gzak** [comment]
We ran into exactly the same issue, our workaround was to set a fake ticket on the `context` within the `OnAuthenticationFailed` handler.

**Comment by bragma** [comment]
@gzak Thanks, I'll try the same. Is the actual ticket returned or thrown away (I don't want it to reach the client)? Also did you "HandleResponse" or "SkipToNextMiddleware"?

**Comment by gzak** [comment]
Judging by the code in [AuthenticationHandler.cs](https://github.com/aspnet/Security/blob/a5b288897d2981c241133b8d37aa22136b653e3a/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs), I believe the ticket gets thrown away and the client gets a 403.

We are calling `HandleResponse()`, although looking through that code it doesn't appear to be necessary to do so. But we'll leave it in since it doesn't hurt anything now and presumably it will be needed instead of the fake ticket once this issue is resolved.

**Comment by akamud** [comment]
We're trying to force a `401` with this but we still get a `500`:

```C#
OnAuthenticationFailed = context =>
{
    context.Response.StatusCode = StatusCodes.Status401Unauthorized;
    context.AuthenticationTicket = new Microsoft.AspNet.Authentication.AuthenticationTicket(new ClaimsPrincipal(), new Microsoft.AspNet.Http.Authentication.AuthenticationProperties(), string.Empty);
    context.HandleResponse();

    return Task.FromResult(0);
}
```

**Comment by Tratcher** [comment]
@akamud your code and that error are unrelated. The error shows MVC trying to issue the initial challenge but none of the auth providers handled it. You either need to enable AutomaticChallenge on one of your auth providers, our tell MVC to challenge for specific providers.

**Comment by JimmyHannon** [comment]
The comment on the HandleResponse method states that all processing for the current request is discontinued and the request is returned to the client. However, i see that altough i call HandleResponse the middleware pipeline is continued and the next middleware gets called. 
In the JwtBearerHandler AuthenticateResult.Success is called when HandledResponse is true.

Is the comment wrong or is the JwtBearerHandler not implementing as intended?

**Comment by akamud** [comment]
That's confusing me too. From what we can see from documentation, `HandleResponse` should skip all subsequent middlewares, this is not what is happening at the moment, at least not for `Microsoft.AspNet.Authentication.BaseControlContext.HandleResponse()`

**Comment by Tratcher** [comment]
Hmm, that text is overly optimistic. There are only some code paths where the events can terminate the request early, and this isn't one of them. The HandleResponse mechanic is something we incorporated from the OIDC middleware and it looks like we haven't done a good job of plumbing it through the other middleware in a consistent way.  @HaoK, back to the whiteboard...

**Comment by Eilon** [comment]
As we are trying to shut down the work for RC2, we are moving this to the backlog.

**Comment by Ciantic** [comment]
This works for 401s:

```
// use JWT bearer authentication
app.UseJwtBearerAuthentication(new JwtBearerOptions()
{
	Events = new JwtBearerEvents()
	{
		OnChallenge = async (s) =>
		{
			if (s.Response.HasStarted)
			{
				return;
			}
			var jsonOpts = app.ApplicationServices.GetService<IOptions<MvcJsonOptions>>();
			var jsonOutput = JsonConvert.SerializeObject(new { error = "LOGIN_REQUIRED" }, jsonOpts.Value.SerializerSettings);
			var jsonBytes = Encoding.UTF8.GetBytes(jsonOutput);
			s.Response.StatusCode = objectResult.StatusCode ?? 401;
			s.Response.ContentLength = jsonBytes.Length;
			s.Response.ContentType = "application/json; charset=utf8";
			await s.Response.Body.WriteAsync(jsonBytes, 0, jsonBytes.Length);
		}
	},
	// ...
});
```

However for 403s there is no solution #872 :(

**Comment by vaindil** [comment]
So if I understand correctly, I basically shouldn't be using `OnAuthenticationFailed`? I cannot for the life of me figure out how I would use it. I have this basic code but no idea where to go with it.

```csharp
var jwtBearerOptions = new JwtBearerOptions
{
    // stuff
    Events = new JwtBearerEvents
    {
        OnAuthenticationFailed = context =>
        {
            context.HandleResponse();
            if (context.Exception.GetType() == typeof(SecurityTokenValidationException))
            {
                context.Response.StatusCode = 400;
                // ?
            }

            // ?
        }
    }
};
```

**Comment by vaindil** [comment]
My previous comment is still valid, but this is what I'm doing to work around it right now. This is not production-ready, I have no idea how to do this properly. It returns 200 because I'm unable to edit that myself, but at least the body gives the error message and real status code.

```csharp
var jwtBearerOptions = new JwtBearerOptions
{
    AutomaticAuthenticate = true,
    AutomaticChallenge = false,
    Events = new JwtBearerEvents
    {
        OnAuthenticationFailed = context =>
        {
            //context.Response.ContentType = "application/json";
            //context.Response.StatusCode = 401;
            var err = "";

            if (context.Exception.GetType() == typeof(SecurityTokenValidationException))
            {
                err = "invalid token";
            }
            else if (context.Exception.GetType() == typeof(SecurityTokenInvalidIssuerException))
            {
                err = "invalid issuer";
            }
            else if (context.Exception.GetType() == typeof(SecurityTokenExpiredException))
            {
                err = "token expired";
            }

            var resp = new
            {
                error = err,
                status = 401
            };

            context.Response.WriteAsync(JsonConvert.SerializeObject(resp, Formatting.Indented));

            return Task.FromResult<object>(0);
        }
    }
};
```

**Comment by Eilon** [comment]
@HaoK / @Tratcher can you comment?

**Comment by Tratcher** [comment]
This isn't going to work, the flow control implementation in the JWT middleware is incomplete. Here's an alternative approach we took to return these kind of errors: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L196-L260

**Comment by vaindil** [comment]
@Tratcher Where would I implement that code? Not sure how to intercept it early enough to alter the response. I'm registering my validator with this in `Startup.cs`:

```csharp
var jwtBearerOptions = new JwtBearerOptions
{
    // misc properties set
};

jwtBearerOptions.SecurityTokenValidators.Clear();
jwtBearerOptions.SecurityTokenValidators.Add(new JwtValidator());

app.UseJwtBearerAuthentication(jwtBearerOptions);
```

`JwtValidator` implements `ISecurityTokenValidator`:

```csharp
public class JwtValidator : ISecurityTokenValidator
{
    public bool CanValidateToken => true;
    public bool CanReadToken(string securityToken) => true;

    public int MaximumTokenSizeInBytes
    {
        get
        {
            throw new NotImplementedException();
        }
        set
        {
            throw new NotImplementedException();
        }
    }

    public ClaimsPrincipal ValidateToken(
        string securityToken,
        TokenValidationParameters validationParameters,
        out SecurityToken validatedToken)
    {
        // validates the token, throws exceptions on failure
        // SecurityTokenExpiredException, for example
        
        // build the ClaimsPrincipal if valid

        return new ClaimsPrincipal(identity);
    }
}
```

**Comment by Tratcher** [comment]
Inside the Challenge event
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L202
You can set headers but beware of writing to the body, it's easy to get into conflicts with other components.

**Comment by vaindil** [comment]
Awesome, it works! Thanks a ton, I greatly appreciate your help! My code is below for anyone else who comes here. Some is duplicated from above for completeness. (I'm sure this isn't the best way to accomplish this, but it works.)

I have a custom `JwtValidator` that handles, as you may have guessed, validation of tokens.

```csharp
public class JwtValidator : ISecurityTokenValidator
{
    // DI for Noda Time SystemClock
    readonly IClock _clock;

    public JwtValidator(IClock clock)
    {
        _clock = clock;
    }

    // none of these are used
    public bool CanValidateToken => true;
    public bool CanReadToken(string securityToken) => true;

    public int MaximumTokenSizeInBytes
    {
        get
        {
            throw new NotImplementedException();
        }
        set
        {
            throw new NotImplementedException();
        }
    }

    public ClaimsPrincipal ValidateToken(
        string securityToken,
        TokenValidationParameters validationParameters,
        out SecurityToken validatedToken)
    {
        validatedToken = null;
        Jwt decodedToken; // custom JWT class

        // validate the token, throw exceptions on failure
        try
        {
            decodedToken = JwtHandler.DecodeJwt(securityToken);
            if (decodedToken == null)
                throw new Exception();
        }
        catch
        {
            throw new SecurityTokenValidationException();
        }

        if (decodedToken.Issuer != validationParameters.ValidIssuer)
            throw new SecurityTokenInvalidIssuerException();

        if (decodedToken.ExpiresAt < _clock.GetCurrentInstant())
            throw new SecurityTokenExpiredException();
        
        // build the GenericIdentity
        var claims = new[]
        {
            new Claim(ClaimTypes.Id, decodedToken.Subject.ToString())
            // other claims
        };

        var identity = new GenericIdentity(decodedToken.Subject.ToString());
        identity.AddClaims(claims);

        // create the ClaimsPrincipal and return it
        return new ClaimsPrincipal(identity);
    }
}
```

I register the validator in `Configure()` of `Startup.cs`.

```csharp
var jwtBearerOptions = new JwtBearerOptions
{
    AuthenticationScheme = "Bearer",
    AutomaticAuthenticate = true,
    AutomaticChallenge = true,
    // I don't know if this ClaimsIssuer is necessary,
    // but I have it just in case
    ClaimsIssuer = "MyIssuer",
    TokenValidationParameters = new TokenValidationParameters
    {
        ValidIssuer = "MyIssuer"
    },
    Events = new JwtBearerEvents
    {
        // https://github.com/aspnet/Security/issues/699
        OnChallenge = context =>
        {
            if (context.HandledResponse || context.Skipped)
                return Task.FromResult<object>(0);

            context.Response.StatusCode = 401;
            var err = "";
            var desc = "";

            if (context.AuthenticateFailure.GetBaseException().GetType() == typeof(SecurityTokenValidationException))
            {
                err = "invalid_token";
                desc = "the provided token is invalid";
            }
            else if (context.AuthenticateFailure.GetBaseException().GetType() == typeof(SecurityTokenInvalidIssuerException))
            {
                err = "invalid_issuer";
                desc = "the provided token's issuer is invalid";
            }
            else if (context.AuthenticateFailure.GetBaseException().GetType() == typeof(SecurityTokenExpiredException))
            {
                err = "token_expired";
                desc = "the provided token is expired";
            }
            else
            {
                err = "unknown_error";
                desc = "an unknown error occurred processing the provided token";
            }

            context.Error = err;
            context.ErrorDescription = desc;

            return Task.FromResult<object>(0);
        }
    }
};

// clear the existing validators, add my own
// the parameter is an IClock service for Noda Time
jwtBearerOptions.SecurityTokenValidators.Clear();
jwtBearerOptions.SecurityTokenValidators.Add(new JwtValidator(app.ApplicationServices.GetService<IClock>()));
app.UseJwtBearerAuthentication(jwtBearerOptions);
```

**Comment by Tratcher** [comment]
Isn't that duplicating the built in messages?
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerHandler.cs#L289

**Comment by vaindil** [comment]
Oh jeez, all I have to do is set the status code and it does the rest for me. Don't know how I missed that. I'll update that comment, thanks again!

**Comment by lousaibiao** [comment]
```
app.UseJwtBearerAuthentication(new JwtBearerOptions()
            {
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                TokenValidationParameters = tokenValidationParams,
                RequireHttpsMetadata = env.IsProduction(),
                Events = new JwtBearerEvents()
                {
                    OnAuthenticationFailed = (context) =>
                    {
                        if (context.Exception is TokenExpireException) {
                            //set this state makes it works. I got 440 statuscode in Postman.
                            context.State = Microsoft.AspNetCore.Authentication.EventResultState.HandledResponse;
                            context.Response.StatusCode = 440;
                        }
                        return Task.FromResult(0);
                    }
                }

            });
```

**Comment by pwalecha** [comment]
I am also facing similar issue, what if we create a filter derived from ExceptionFilterAttribute and catching the SecurityTokenExpiredException. Inside the catch, changing the status code to 401 and calling base.OnException();

It seems it should work but not sure whether this is a good way to deal or not.

**Comment by mhosman** [comment]
The best way is to use OnAuthenticationFailed or a custom Middleware?

**Comment by Eilon** [comment]
Closing this because no specific action is planned for this issue. But we do plan to make some bigger improvements to auth that are tracked in this issue: https://github.com/aspnet/Security/issues/1359
