### ISSUE TITLE
There is no way to specify a different protocol in CallbackPath when using a reverse proxy

### ISSUE THREAD

**Issue by rchowe** [aspnet/Security#700]
I am running a web app using HttpPlatformHandler behind IIS, and I am using Azure AD through `app.UseOpenIdConnectAuthentication`. I have an HTTPS binding configured in IIS, however requests to the HTTPS binding are not being proxied into my app as HTTPS, which causes `RedirectUri` to be set to a HTTP URL, causing the redirect back to my app after the user is signed in to fail (because I don't have an HTTP binding configured).

The following is the contents of my `app.UseOpenIdConnectAuthentication` block:

```csharp
app.UseOpenIdConnectAuthentication(options =>
{
    options.DisplayName = "Azure AD Account";
    options.AutomaticChallenge = false;
    options.AuthenticationScheme = "Azure AD";

    options.Authority = Configuration["Authentication:AzureAD:Authority"];
    if ( env.IsDevelopment() )
	    options.RequireHttpsMetadata = false;

    options.ClientId = Configuration["Authentication:AzureAD:ClientId"];
    options.ClientSecret = Configuration["Authentication:AzureAD:ClientSecret"];

    options.Scope.Add("openid");
    options.Scope.Add("email");
    options.Scope.Add("api1");
}
```

**Comment by blowdart** [comment]
Install the Add the Microsoft.AspNet.HttpOverrides package

In your Configure() method add

    app.UseOverrideHeaders(new OverrideHeaderMiddlewareOptions
    {
        ForwardedOptions = ForwardedHeaders.XForwardedFor | 
                           ForwardedHeaders.XForwardedProto
    });

The app will now believe it's on HTTPS.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Announcements/issues/123#issuecomment-183464372
