### ISSUE TITLE
Add a way to use ClientCertificate and ClientAssertion in OIDC Code Flow

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#701]
There are three ways to show proof in the ConfidentialClient flow: SymmetricKey, Certificate, or SignedAssertion (JWT). The OM should support all three. Possibilities are adding additional properties to OIDC options.

**Comment by Eilon** [comment]
Moving to backlog.

@vibronet FYI

**Comment by patrickCode** [comment]
Any update to this? When can we expect the CertificateAssertion to be in place?

**Comment by Eilon** [comment]
Hi @patrickCode ,

Here are some comments from @vibronet from an email exchange we just had:

> [You] can manually redeem codes just like we do [...], by injecting its own notification handling

Plus, as far as we know this isn't yet ratified in an OIDC spec.

So for those reasons we have no plans to implement this and so I'm closing the issue for now.

Thanks,
Eilon

**Comment by mj1856** [comment]
See: AzureAD/azure-activedirectory-library-for-dotnet#598
