### ISSUE TITLE
Where to put secure file like database file or files that accessible by certain role only?

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Security#703]
https://support.microsoft.com/en-gb/kb/316871

Is there permission setting or should the web config like above to be used?

At this moment I can't upload new file to wwwroot path and unable to change anything at approot path.

**Comment by blowdart** [comment]
No, and there's no web.config anymore anyway.

Even with MVC in previous versions it was never a great idea, as file location never corresponded to routes.

**Comment by andrew-vandenbrink** [comment]
I have to put extra write permission to wwwroot

![image](https://cloud.githubusercontent.com/assets/12871379/13194481/c0a60b0e-d793-11e5-8c7e-434e4ecd2545.png)


before I can upload something to wwwroot

**Comment by andrew-vandenbrink** [comment]
If you have sqlite database, make sure you have **modify** permission too

**Comment by Eilon** [comment]
As @blowdart mentioned, `web.config` settings pertaining to ASP.NET 4.x and earlier are not used it all. `web.config` can still be used for IIS-specific settings (stuff in `system.webServer`), and they will be used when running on IIS and IIS Express.

NTFS settings are *always* respected because they are processed at the operating system layer. Of course, it applies when running on Windows :smile: (I suppose you could mount an NTFS volume in a non-Windows OS, but that is an unlikely scenario!)

**Comment by blowdart** [comment]
And as we don't supported integrated authentication with impersonation the process account your site runs under will always be the application pool identity.

**Comment by blowdart** [comment]
_(As an aside generally best practice would be to save uploads outside of your webroot, as that way no-one is going to overwrite anything important)_

**Comment by andrew-vandenbrink** [comment]
At this moment I have access to the vm and change the os permission, what about azure web app for example? Is it writeable by default? If now how can enable it?

**Comment by blowdart** [comment]
That would be a question for the azure websites team. It's an OS configuration issue, nothing to do with asp.net.

**Comment by andrew-vandenbrink** [comment]
I change the question to make it more pointed to what we would like to achieve. At this moment, everyone will say anywhere other than wwwroot, but then again where exactly?

Can we all agree to use 

```
IApplicationEnvironment appEnv;
var secureDirectory=appEnv.ApplicationBasePath;
```

This will solve this issue
https://github.com/aspnet/Identity/issues/751

![image](https://cloud.githubusercontent.com/assets/12871379/13485019/8360b626-e103-11e5-9f32-5c2069170389.png)


The second scenario that I would like to achieve is, where to put javascript file that only accessible by certain role? It will be silly if I put my javascript file in wwwroot as its accessible by public.
To achieve this,
1. Put js file inside IApplicationEnvironment ApplicationBasePath;
2. Create controller with authorized role and create action to fetch the js file

Is this the right approach?

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
