### ISSUE TITLE
Auth handlers should unregister themselves after Next

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#704]
Auth handlers should unregister themselves in a finally block after Next. Right now this only happens in a catch block for some reason:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/AuthenticationMiddleware.cs#L76

**Comment by codnee** [comment]
This seems pretty straightforward.

Since there is no risk of it masking the original exception. Would it make sense for the finally block to throw if for some reason the teardown fails?
