### ISSUE TITLE
How to authorise the user access in web API layer using claims

### ISSUE THREAD

**Issue by kumarabhimanyu** [aspnet/Security#705]
I just downloaded this project and it works fine. Now I want to authenticate my web service calls with same approach. Suppose my application has 2 project – a web project and a web api and both are running on same domain like app.mydomain.com and service.mydomain.com

During login from my web app, I am able to set claims and putting condition based on that in my web app controller. 

Now I want to do the same in web API and this web API can be called from Web project and/or JQuery also. (want to send the claim details in web API and check the role there). Please guide.

**Comment by blowdart** [comment]
What you would do is somewhere in your web project create a URL which is protected by cookie auth, and when loaded validates the user identity and creates a JWT token out of it.

You'd then send that to your web app, and configure the JWT middleware to validate the signing key. Then you'd get the identity on the other side.

There are no samples for this unfortunately.

**Comment by kumarabhimanyu** [comment]
Thanks for your quick response. Did get similar links and demo apps but none of them are working. Will have a fresh look again.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
