### ISSUE TITLE
What's the recommended approach for protecting a staging site from public access.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Security#706]
I have a staging website, `staging-xxx.azurewebsites.net` and I want to protect it from public access.
That's it: no search indexer find it, and no one without access to see it. Also, the website have user management (identity) and I want a solution that doesn't mess with the user authentication, so I can  be able to send to specific person (and grant access) for review and use, including registering, log in, etc. stuff that normally QA or a client would do.

I read a lot about OAuth2 and OpenIdConnect stuff and seems very complex for this simple scenario. (maybe not, but there are too many flows and none looks simple for this simple case).

I'm currently using `Basic-Auth` which I know is a crappy solution, that works perfect for my needs but I would love to make it right.
I read about restrict it via IP Address, unfortunately, in Uruguay (where I live) IPs changes every 12 hour, so having this kind of solution will not work in my scenario.

As I should not be writing security software, I'm asking for:

1) What is the recommended way to implement a solution for this? how is people doing it? It seems to me like a pretty general scenario, so someone should be doing it right. I just need to know what to learn/read/understand. Any guidance is welcome.

2) If possible, can you provide a sample I can take a look at?

Thanks!

**Comment by blowdart** [comment]
We don't have anything for this.

Azure Websites does support this sort of thing. In your site configure control panel there's a authentication / authorization section. That then shuts down access to anyone not inside your Azure AD.
