### ISSUE TITLE
Anyway to get the challenge URL from an MVC action?

### ISSUE THREAD

**Issue by csaloio** [aspnet/Security#707]
Was wondering if rather than calling
`context.Authentication.ChallengeAsync(authType, new AuthenticationProperties() { RedirectUri = "/" })`

if the URL that the client would be redirected to could be placed directly in the view as a link. But in order to do that somehow the controller needs to be able to ask the OAuth middleware to return what that URL string would be. Anyway for a controller to call into `BuildChallengeUrl()` or the like?

**Comment by Tratcher** [comment]
The closest you're going to get is to check `context.Response.Headers["Location"]` after calling ChallengeAsync.

Why are you trying to avoid the auto-redirect?

**Comment by csaloio** [comment]
My originally thinking was that is was unnecessary to have a link that sends them to an MVC action that just redirects them to the OAuth provider. I was thinking it was more efficient to simply link them directly to the OAuth provider in the view. You just need a way to setup the OAuth middleware to know where to redirect to after the OAuth provider sends them back. But it's not a huge deal. Just curious if there was a way to determine what that provider link was going to be.

**Comment by Eilon** [comment]
Because this is largely an implementation detail of particular auth protocols, there's no generic way to know where the redirect would go (because there might not even be a redirect).
