### ISSUE TITLE
JWT middleware not supported?

### ISSUE THREAD

**Issue by rabx88** [aspnet/Security#708]
Is there a plan to support the Microsoft.AspNet.Authentication.JwtBearer package on .NETPlatform version 5.4? We were using this with the last version and now it seems absent. Am I missing something?

Edit: It looks like the code is there, so is it an issue of release timing? Is there an ETA?

**Comment by blowdart** [comment]
The next release, RC2 will have it.

**Comment by rabx88** [comment]
Excellent, thanks! There was some misinformation/speculation out there.
