### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by Fosol** [aspnet/Security#713]
I've read somewhere you are not officially supporting RC1?  This is this true?

I'm spinning my wheels here on security.  I've got things running on my local machine, but as soon as I deploy to a different environment authentication fails.  While I'm fairly confident it's a configuration issue, I can't step through the code to see the issue when it's on the server.

1) Do you officially support RC1?  If you do, how do I go about receiving it?
2) Is there a decent strategy for debugging authentication when it's failing on the server?
3) Has any documentation been put together yet on the authentication and authorization process within MVC?

**Comment by blowdart** [comment]
1) I believe it's supported via the paid for support route. But obviously a github issue is cheaper.
2) Nope
3) We've documented pieces separately. What are you looking for?

**Comment by Fosol** [comment]
I'd like more information about the following;
1) Challenge Response
2) Many of the configuration properties and how they work (i.e. AutomaticAuthenticate, AutomaticChallenge).
3) Related to the above - The OWIN pipeline in relation to security plugins.

**Comment by Fosol** [comment]
What type of token is OpenIdConnect expecting?  If I use JwtBearer I know I need to add a "Bearer" header token.  Is there something similar for OpenIdConnect?

**Comment by PinpointTownes** [comment]
> What type of token is OpenIdConnect expecting?

OIDC requires JWT identity tokens (`id_token`) but you're free to use the format of your choice for access tokens (they must be treated as opaque by the client application).

**Comment by Fosol** [comment]
I guess what I don't understand is that under my current configuration I have to do the following so that it can accept the Bearer token;
```
app.UseJwtBearerAuthentication(...);
app.UseOpenIdConnectAuthentication(...);
```
If I remove the UseJwtBearerAuthentication it will fail.  What I'd expect is that the UseOpenIdConnectAuthentication would check for an appropriate token and I wouldn't need the JwtBearerAuthentication.  Am I expecting the wrong thing?  Is there a way to pass an appropriate token so I don't use JwtBearerAuthentication?

This is currently how I set the Bearer token;
```
var claim = _httpContext.User?.FindFirst("access_token");
if (claim != null)
      request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", claim.Value);
```

**Comment by PinpointTownes** [comment]
> Am I expecting the wrong thing?

Yes, you are. The OIDC middleware is not meant for token consumption/validation: it's JwtBearerMiddleware's job. Only use OpenIdConnectMiddleware if you want to support client authentication (only interactive flows)

**Comment by Fosol** [comment]
Currently I have an Oauth Server providing a way signin and generate tokens.  The Oauth Server uses an implementation of Identity 3.  The web application then provides a cookie for the client so that it maintains authentication information.  The web application then submits a token for all requests to the API.

The tokens however are expiring before the cookie does.  Thus the user successfully logs in and is able to perform requests to the API (via the web application) with the supplied token until the token expires.

How do I make the token keep the same lifespan as the cookie?  Is there an auto-renew option?

**Comment by PinpointTownes** [comment]
> How do I make the token keep the same lifespan as the cookie?

Which OIDC server are you using exactly? It should be configurable in the server options.

> Is there an auto-renew option?

No, it's up to you to ask for a refresh token and get new access tokens when you need to.

**Comment by Fosol** [comment]
OpenIdConnect

    "AspNet.Security.OpenIdConnect.Extensions": "1.0.0-beta4",
    "AspNet.Security.OpenIdConnect.Server": "1.0.0-beta4",

I would like to keep the backend oauth implementation transparent to the user.  They simply login to the way they're used to.  

How would I get the web application to request a new access token when the prior one expires?

**Comment by PinpointTownes** [comment]
The access token lifetime is configurable in the ASOS options:

```csharp
app.UseOpenIdConnectServer(options => {
    options.Provider = new AuthorizationProvider();
    options.AccessTokenLifetime = TimeSpan.FromHours(3);
});
```

> How would I get the web application to request a new access token when the prior one expires?

You can either [use a good old `HttpClient` and make a refresh token request](http://openid.net/specs/openid-connect-core-1_0.html#RefreshingAccessToken) or use a library to assist you, like [`Thinktecture.IdentityModel.Client`](https://www.nuget.org/packages/Thinktecture.IdentityModel.Client/)

**Comment by Fosol** [comment]
Thanks!
