### ISSUE TITLE
Query parameters for a returnUrl are lost

### ISSUE THREAD

**Issue by malichishti** [aspnet/Security#715]
Upon redirect after a successful login, my query parameters on original requested url gets lost.
Example: 
Registered Client with RedirectUri: http://abc/
Flow:
Requested Url: http://abc/def?Id=10
Unauthorized, redirecting to Identity Server
Successful login 
Redirected to http://abc/def
MISSING query parameter

I'm using Microsoft.Owin.Security.OpenIdConnect 3.0.1 with IdentityServer3

**Comment by blowdart** [comment]
Well yes, you are redirected to the redirectUri you set up in Identity server. Query strings are ignored. This would be a question for IdentityServer.

**Comment by brockallen** [comment]
I think he means the return URL captured in the properties before he leaves his app to IdSvr (or any other OIDC provider).

**Comment by blowdart** [comment]
Even then it's always going to drop the query string on return, right?

https://openid.net/specs/openid-connect-implicit-1_0.html#RequestParameters
> This URI MUST exactly match one of the Redirection URI values for the Client pre-registered at the OpenID Provider

**Comment by brockallen** [comment]
When the redirect is triggered from the katana OIDC MW, the current request URL is put into the properties as the "return url" (this can also be set explicitly in the AuthenticationProperties). Upon return from the OIDC provider, the katana OIDC MW does its job and once that's all successful then if there's a "return url" in the properties it's supposed to redirect the user to that. I think that's what the OP is asking about (so it's really unrelated to the OIDC redirect URI).

**Comment by brockallen** [comment]
And this is all conjecture from the way the OP's question was worded.

**Comment by malichishti** [comment]
@brockallen you are exactly right.

**Comment by blowdart** [comment]
@Tratcher

**Comment by Tratcher** [comment]
This appears to work fine with both Katana v3.0.1 and Core 1.0.0. Please share a repro app to github that has the issue.
