### ISSUE TITLE
Unable to external login when app behind proxy

### ISSUE THREAD

**Issue by hantleman** [aspnet/Security#716]
I try to authenticate via google, but my application behind proxy.
Local address is http://localhost:5000, but actual address is https://address.com/
See below:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L119
Is any way to change Request.Scheme and Host, or fix BuildRedirectUri function

**Comment by mikes-gh** [comment]
Working code from my app

```
app.UseGoogleAuthentication(options =>
            {
                options.ClientId = "someclientid";
                options.ClientSecret = "somesecret";
                options.BackchannelHttpHandler = new HttpClientHandler()
                {
                    Proxy = new WebProxy("http://someproxy.somedomain.local:3128")
                };
            });
```

**Comment by hantleman** [comment]
Application works in docker with which listen  http://*:5000, the real site address is https://address.com/ via apache. Google handler generate return uri http://localhost:5000/signin-google, but should https://address.com/signin-google

**Comment by mikes-gh** [comment]
My app is behind ARR (windows reverse proxy) so its a similar situation
Maybe it treats the headers differently than the Linux reverse proxy.
It definitely works.  I think the answer maybe in your reverse proxy config.

I also have this in my Startup.cs as well but I think that's more to do with Kestrel headers after the reverse proxy.

```
 app.UseOverrideHeaders(options =>
            {
                options.ForwardedOptions = ForwardedHeaders.All;
            });
app.UseHttpMethodOverride();
```

**Comment by hantleman** [comment]
It works for me, but needs some changes on apache: RequestHeader set X-Forwarded-Proto "https" for rc1

**Comment by Eilon** [comment]
Is there still an issue here or is this resolved?

**Comment by hantleman** [comment]
Thanks, the issue is resolved

**Comment by yashvit** [comment]
This issue with OAuth happens on MVC5 as well. So thought I would leave a note here on how to fix this for MVC 5.

     

        app.Use(async (context, next) =>      
        {
            if (string.Equals(context.Request.Headers["X-Forwarded-Proto"], "https", StringComparison.InvariantCultureIgnoreCase))
            {
                context.Request.Scheme = "https";
            }
            await next.Invoke();
        });

**Comment by debchy** [comment]
I have solved the problem. This problem is happening for proxy address which is not resolving with OIDC connection.
So, Instead of 
`options.Authority = "http://app.mycompany:5959/";`
I am now using IP address.
`options.Authority = "http://41.4.40.41:5959/";`
