### ISSUE TITLE
Ask to add the Async version of ISecurityTokenValidator.ValidateToken method

### ISSUE THREAD

**Issue by ORuban** [aspnet/Security#721]
It can be helpful to change the  ISecurityTokenValidator.ValidateToken method to async one and use it in JwtBearerHandler, OpenIdConnectHandler handlers. 

I have faced with the lack of async implementing my own validator for JwtBearerHandler. 
If you approve this idea I can make a PR with changes.

**Comment by Tratcher** [comment]
ISecurityTokenValidator is not implemented in this repo, it's over here:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/e6d903b4f8d3c6d7697dc70cd54ae905b18b65fe/src/System.IdentityModel.Tokens.Jwt/ISecurityTokenValidator.cs
