### ISSUE TITLE
Remove Katanaism vestiages from Options

### ISSUE THREAD

**Issue by HaoK** [aspnet/Security#722]
Fell out of IOptions discussions with @lodejard 

- ISystemClock should be a service dependency in middleware not on Options
- Review other service like things on the Options classes, general rule is that the Option should default to null for services and let the middleware set the default service

**Comment by HaoK** [comment]
Leaving unassigned for triage since I am a bit backed up for the near future

**Comment by anurse** [comment]
'wontfix' ?
