### ISSUE TITLE
Operation based authorization for AuthorizeAttribute

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Security#725]
Hi, having policies for authorization is a great step forward, however I think the current implementation still enforces a very strong coupling between the target (e.g. controller action) and the policy. Let's take a few examples from the docs:

```csharp
[Authorize(Policy = "Over21")]
public IActionResult Login() { ... }

[Authorize(Policy = "EmployeeOnly")]
public IActionResult VacationBalance() { ... }

[Authorize(Policy = "HumanResources")]
public IActionResult UpdateSalary() { ... }
```

This way, the condition is moved to a separate class and it can be reused. This is ok, but from my experience, most requirement changes are like these:
* Login should also be callable by "Employees", no matter how old they are
* UpdateSalary should also be callable by "Founders"

Putting the logic for these changes into the policy would be dangerous because you might not be sure, where it is used and if the change should be valid for all usages. In addition to that, the name of the policy wouldn't be correct anymore. So these examples still require a change to the AuthorizeAttribute usage and a re-deployment. 

The is necessary because the current system still forces us to put the **who** on the method. I believe that authorization rules should be completely decoupled from the methods in every complex application. We should only have to tell the authorization system **what** we want to authorize and it should figure out the rest. This would be an example for such a solution:

```csharp
[Authorize(Operation = "Accounting.UpdateSalary")]
public IActionResult UpdateSalary() { ... }
```

This would allow the authorization system to look up this operation and the assigned permissions for the current user. This way, many more requirement changes can be done without the need to change the method signature.

One might say that we could just use the current policies with `Authorize(Policy = "Accounting.UpdateSalary")` but I think that the current system is too static for this. As far as I understand, we would have to create separate policy objects for every action in our `Startup.ConfigureServices`-method. Even if this could be fetched from a database and done in a loop, we could end up with hundreds or thousands of policies in a large app. 

Do you think, using that many policies would actually be the correct solution?

If there's no way to make this a first class citizen, maybe it would be a compromise to see this as **one policy** that just needs the operation as an additional parameter. I think this would be similar to the [resource based authorization](https://docs.asp.net/en/latest/security/authorization/resourcebased.html) in which you can already pass an `OperationAuthorizationRequirement` to your authorization system:

```csharp
await authorizationService.AuthorizeAsync(User, document, Operations.Read);
```

But since we need to use this in an attribute we need simpler types. So maybe it could look like this:

```csharp
[Authorize(Policy = "OperationBased", Argument = "Accounting.UpdateSalary")]
```

This would still be a very flexible solution. Application developers could then make this more convenient by creating their own derived AuthorizeAttribute which always sets the policy and just needs the argument like in my sample above.

/cc @leastprivilege Your feedback would be great as well!

**Comment by Eilon** [comment]
For RC2 you can indeed to do something like `Authorize(Policy = "Accounting.UpdateSalary")` and use a policy provider to dynamically map this to specific operation policies.

At this time we are not planning to make any further changes here.

**Comment by cwe1ss** [comment]
I didn't know about the new provider abstraction. That's good news! Thank you, Eilon!
