### ISSUE TITLE
Consider renaming Microsoft.AspNetCore.Authorization to Microsoft.Extensions.Authorization

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Security#726]
Hi, I've seen that Microsoft.AspNetCore.Authorization does not have a dependency on any AspNetCore project. 

As far as I understand, this library is built in a way that would allow us to also use it within our core domain logic or other non ASP.NET libraries. In my opinion this makes it very similar to other cross-cutting concern libraries like Microsoft.Extensions.Logging, Microsoft.Extensions.Configuration and so on. 

For this reason, have you considerd renaming Microsoft.AspNetCore.Authorization to `Microsoft.Extensions.Authorization`?

**Comment by davidfowl** [comment]
Yea, I brought this up a while ago https://github.com/aspnet/Security/pull/671#issuecomment-174491766.

/cc @Eilon @HaoK @blowdart @leastprivilege

**Comment by cwe1ss** [comment]
Good to hear, that this has been discussed. To add further context about the usefulness of this library, here's my "real life scenario :tm:" :)

All of our business logic is in class libraries and is grouped into business contexts. Some of these contexts are written in DDD, some are not. But all libraries have a public contract which is implemented by having "application services". They represent the use-cases. We built our own authorization system at this level - the usage is pretty similar to this library. We have "Authorize" attributes and some authorization system validates it.

Right now, this business logic is hosted in ASP.NET Core WebAPIs but this is not really important - the hosts are just a facade around the "application services". We could easily switch to whatever hosting framework we want. 
We are using OAuth with Azure AD, so our Web API still uses this authorization system but just to make sure that there is *any* user and to convert the claims to our internal user object. The actual permissions are checked in our business logic.

I think that this library could be a good fit for our business logic, especially with the upcoming policy providers to better support operation based authorization #725.

**Comment by Eilon** [comment]
Not going to change this at this time. Even though this assembly says AspNetCore in it and doesn't depend on other ASP.NET Core features, it's still technically part of ASP.NET's authN/authZ system. And it's nevertheless just fine to have a non-ASP.NET project reference this. (If you take this to an extreme, there are always *some* projects that don't reference ASP.NET, and that doesn't mean that they themselves shouldn't be part of ASP.NET.)

**Comment by cwe1ss** [comment]
Fair enough. Thanks for taking the time to think about it!
