### ISSUE TITLE
Enable XML documentation generation

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#728]
Unlike other repositories, `aspnet/Security` hasn't been updated to enable XML documentation generation, which seems to be an opt-in feature with the new tooling (e.g https://github.com/aspnet/Mvc/commit/028c0fb13164bcdda2e22e01e9093ac8a5853b06)

/cc @Eilon

**Comment by Eilon** [comment]
@ajaybhargavb ?

**Comment by ajaybhargavb** [comment]
Good catch @PinpointTownes. Not sure how I missed this.

**Comment by ajaybhargavb** [comment]
9dfe4d96996cf65a7013b5b0eb329aab80434199

**Comment by PinpointTownes** [comment]
Thanks @ajaybhargavb! :clap:
