### ISSUE TITLE
release version does not compile without errors

### ISSUE THREAD

**Issue by Tgueth** [aspnet/Security#733]
I downloaded the Security release repository (I am assuming that this is RC1) to my computer and opened in Visual Studio 2015.  I want to use the code to walk through the authorization process of AuthorizeAsync.  However, the code does not compile, too many to list

A number of issues keep this from compiling:

1) references appear out of date or non-operable.  In some case, I can remove all frameworks but dnx451 but still compile fails.

2) All tests as well as some base code fail to compile.  Removed these to try and get to a point where I could use the base libraries.

3) Compile still fails. Here are some of the errors:

JwtBearerOptions - The type or namespace name 'TokenValidationParameters' could not be found 

OpenIdConnectOptions - same error

AuthenticationMiddleware - The type or namespace name 'RequestDelegate' could not be found

Is there an issue with the RC1 version code?

Is this an issue with Nuget pulling the wrong version of libraries?

What is the fix?

Tom

**Comment by Eilon** [comment]
You should never use the `release` branch - that's just for build stabilization while a release is being prepared. Instead, use `dev` for the latest, most up-to-date code, and use `master` for the latest public bits.

Can you try out `dev` or `master` and see if that works for you?

**Comment by Tgueth** [comment]
Sorry, misunderstood the terminology.  Still learning to dig into this.  I am not ready to move to RC2 (lots of breaking changes mainly) but working to understand the parts of the underlying architecture so the RC1 release is just fine as I move an application to MVC6.

 

Sorry for my ignorance.  Will let you know if this solves my problem.

 

Tom

**Comment by Tgueth** [comment]
Okay, you are correct.  Master version does compile.  Thank you for the clarification.

**Comment by Eilon** [comment]
Great, thanks!
