### ISSUE TITLE
Async handlers for resource based authorization

### ISSUE THREAD

**Issue by bragma** [aspnet/Security#739]
Hi,
I am trying to use resource based auth, but all available docs seem to override a synchronous "Handle" method. I need to access external resources and I'd like to keep everything async. In the example auth handlers inherit from class "AuthorizationHandler" which forces me to implement the sync Handle method, even if the system seems to be able to handle async through "HandleAsync". In particular this seems a bit fishy to me:

```
protected virtual Task HandleAsync(AuthorizationContext context, TRequirement requirement)
{
	Handle(context, requirement);
	return Task.FromResult(0);
}
```

Back to the main question, it seems to me I don't have to inherit from AuthorizationHandler but implement IAuthorizationHandler directly. As an example, I came out with this (as a simple example):
```
public class StringValueAuthorizationHandler : IAuthorizationHandler
{
	public async Task HandleAsync(AuthorizationContext context)
	{
		if (context.Resource is string)
		{
			foreach (var req in context.Requirements.OfType<OperationAuthorizationRequirement>())
			{
				// Do something async here...
				await Task.Delay(500);
				context.Succeed(req);
			}
		}
	}
}
```

Aside from refactoring into a class handling more generic resource and requirement types, does it make any sense?

Another option I have is to stick with AuthorizationHandler, override "HandleAsync(AuthorizationContext context, TRequirement requirement)" and implement a do-nothing, never-use "Handle(AuthorizationContext context, TRequirement requirement)" just because it's abstract.

Am I missing something?
Thanks!

**Comment by benfoster** [comment]
I'd like to +1 this. One benefit of separate authZ handlers is that we can encapsulate complex authZ logic and inject external services. A fairly common scenario will be to load permissions from a database which should be async.

**Comment by bragma** [comment]
FYI, I've solved my problem in this way:
```
public abstract class AsyncAuthorizationHandler<TRequirement> : IAuthorizationHandler
		where TRequirement : IAuthorizationRequirement
{
	public virtual async Task HandleAsync(AuthorizationContext context)
	{
		foreach (var req in context.Requirements.OfType<TRequirement>())
		{
			await HandleAsync(context, req);
		}
	}

	protected abstract Task HandleAsync(AuthorizationContext context, TRequirement requirement);
}

public abstract class AsyncAuthorizationHandler<TRequirement, TResource> : IAuthorizationHandler
	where TRequirement : IAuthorizationRequirement
{
	public virtual async Task HandleAsync(AuthorizationContext context)
	{
		if (context.Resource is TResource)
		{
			foreach (var req in context.Requirements.OfType<TRequirement>())
			{
				await HandleAsync(context, req, (TResource)context.Resource);
			}
		}
	}

	protected abstract Task HandleAsync(AuthorizationContext context, TRequirement requirement, TResource resource);
}
```

Then I inherit my handler classes from my AsyncAuthorizationHandler and override HandleAsync.

**Comment by Eilon** [comment]
@HaoK any idea if there's a reason we made this sync? Is it called from a sync call stack or is almost everything already async all the way down?

**Comment by HaoK** [comment]
In general most of the handlers today are sync so we optimized for this case.  Is the current situation that unreasonable since async only is not blocked, as metioned either by not using our sugar base class, or overriding the async method and ignoring/no-oping the abstract sync Handle.

**Comment by Eilon** [comment]
Ok then closing this out.

**Comment by leastprivilege** [comment]
> In general most of the handlers today are sync so we optimized for this case.

Because all you sample code pulls the data from the claims of the user.

I would say any serious resource authorization handler would need to do some sort of IO to come to a conclusion.

The default should be async.

**Comment by bragma** [comment]
In fact I was asking myself if I am doing something wrong. In my case, I have users that can have different roles on different tenants. Which roles they have is stored in different DB tables. One possible way for keeping authorization sync is to prepopulate the user with all the claims for the different roles, then just check the claims from the authorization. But this means hitting the DB to get all roles into claims even if authorization (in particular resource based) will never use them. Seems a waste to me.

**Comment by Eilon** [comment]
I think it's important to keep in mind that these checks are intended to be quick, because they'll be happening a lot. So going to a DB is fine, but it might need to be cached to get any real performance. And once it's cached, the check will be quick. So perhaps the first check will be a slower sync blocked call, but then after that it should be fast, and thus CPU bound and sync is fine. Perf would be good until the cache entry expires, and then it happens over again.

**Comment by benfoster** [comment]
@Eilon I don't think that's good justification for making a blocking sync call. We could use the same argument for the entire framework - "just cache it".

A better model would be something similar to action filters where we have an option to implement either a sync or async version.

**Comment by Eilon** [comment]
Per @HaoK 's comment earlier it sounds like it *is* possible to do async, but just not using some of the helper base classes that help some of the most common cases.

**Comment by leastprivilege** [comment]
even caching APIs typically use an async signature today.

Please re-open that for post RC2.

**Comment by HaoK** [comment]
The core APIs are already async, the helper is async as well, just override the HandleAsync.  We chose to make it slightly easier to implement sync only via the abstract virtual Handle, but there's nothing preventing you from doing whichever you like, or even implementing the interface directly if you so chose.

**Comment by bragma** [comment]
@Eilon I confirm it's entirely possible to do what you say without much work. I've posted a sample of my AsyncAuthorizationHandler classes.

Still I have to agree with @leastprivilege that even caches are async nowdays. Aside from the case of a single server application, all scaled out solutions probably require some sort of distributed caches and most of them use an async API. Just look at the new ASP NET Core's cache API with its GetAsync, SetAsync, etc. Sometimes there are also sync versions of the same methods, but it's not always the case.

My suggestion is to make the async pattern more evident in the documentation showing how to implement it. It's not difficult, but it requires to look at Security's source code for understanding what to do. Also notice it's possible to inherit directly from the provided "AuthorizationHandler" class without rewriting it, but it's kind of fishy because it requires you to provide some implementation for the sync "Handle" method which is abstract.

**Comment by davidfowl** [comment]
Sounds like a documentation bug to me.

**Comment by davidfowl** [comment]
> Also notice it's possible to inherit directly from the provided "AuthorizationHandler" class without rewriting it, but it's kind of fishy because it requires you to provide some implementation for the sync "Handle" method which is abstract.

That is a problem. We do the same thing in MVC with Filters for compatibility (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Filters/ActionFilterAttribute.cs) but nothing i abstract. Everything on the base should be virtual.

/cc @HaoK @Eilon

**Comment by HaoK** [comment]
If making the sync no-op virtual instead of abstract makes everyone happy that's an easy fix.  The only downside is it won't be very obvious which method needs to be implemented anymore but that can be up to samples/documentation
