### ISSUE TITLE
Attribute Authorize didn't work with simple Requirement Policy

### ISSUE THREAD

**Issue by SharpNoiZy** [aspnet/Security#740]
Hi,

I have strange issue, I configured a simple policy:
```C#
services.AddAuthorization(options =>
{
	options.AddPolicy("DavidUser", policy => policy.Requirements.Add(new DavidUserRequirement()));
});
```

The requirement is just empty.
The Handler does just Success().

The strange thing is, if I decorate my controller with it, I just see an empty white page and the handler code (Breakpoint) is not executed.
If I remove the attribute and call:
```C#
await _authz.AuthorizeAsync(User, "DavidUser")
```
inside the action the handler is called and everything works.

Ideas?

**Comment by blowdart** [comment]
Trace the traffic either with fiddler, or your browser's dev tools, or add in the status code error middleware. What status code are you seeing?

Are you sure you have an actual user? How are you authenticating?

**Comment by SharpNoiZy** [comment]
Traced with Fiddler, and it just returns 401 and blank page.
But without entering my Requirement. (What it does if I use "_authz.AuthorizeAsync")

**Comment by SharpNoiZy** [comment]
Can be closed, I followed a different tutorial and I think the issue was that I have to use HttpContext.Authentication.SignInAsync at some point of time to work with Requirements.
I thought that this would be just needed if I use the ASP Identity system.
