### ISSUE TITLE
SignOutAsync should take [] of AuthenticationSchemes

### ISSUE THREAD

**Issue by rustd** [aspnet/Security#742]
A user has to specify SignOut per authentication scheme as follows https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/OrganizationalAuth/Single/Controllers/AccountController.cs#L24
With this change we will have the same code as in Katana

**Comment by Tratcher** [comment]
This issue was moved to aspnet/HttpAbstractions#585

**Comment by PinpointTownes** [comment]
The syntax in MVC would be much better if https://github.com/aspnet/Mvc/pull/4259 was merged.

/cc @danroth27
