### ISSUE TITLE
RSAOpenSsl "Unable to load DLL 'ncrypt.dll': The specified module could not be found.\n (Exception from HRESULT: 0x8007007E)"

### ISSUE THREAD

**Issue by kennyrulez** [aspnet/Security#750]
Hello asp.net team!
Platform: dnx-coreclr-linux-x64.1.0.0-rc1-update1
I created an MVC6 website which uses bearer authentication. 
Here is the startup.cs snippet where i set up the key and the bearer:
```
var keyParams = new RSAOpenSsl(2048).ExportParameters(true);
key = new RsaSecurityKey(keyParams);
tokenOptions = new TokenAuthOptions()
{
     Audience = TokenAudience,
     Issuer = TokenIssuer,
     SigningCredentials = new SigningCredentials(key, SecurityAlgorithms.RsaSha256Signature)
};

services.AddInstance(tokenOptions);

// Enable the use of an [Authorize("Bearer")] attribute on methods and classes to protect.
services.AddAuthorization(auth =>
{
     auth.AddPolicy("Bearer", new AuthorizationPolicyBuilder()
                    .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme‌​)
                    .RequireAuthenticatedUser().Build());
});
```
But, every time I run this project, I get the error

> "Unable to load DLL 'ncrypt.dll': The specified module could not be found.\n (Exception from HRESULT: 0x8007007E)"

If I check on the output folder (after dnu restore && dnu publish ...) I cannot actually find any ncrypt.dll.

May you guys can help me?

**Comment by vcsjones** [comment]
This might be a better question for dotnet/corefx. It shouldn't be trying to load ncrypt (CNG) on Linux.

**Comment by PinpointTownes** [comment]
It was a Wilson bug, fixed in RC2: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/324.
