### ISSUE TITLE
Support getting the external login url without a traditional POST/redirect.

### ISSUE THREAD

**Issue by pauldotknopf** [aspnet/Security#751]
My use case is that I would like to open a popup window on the client for the user to authenticate with.

Right now, there is the ```ChallengeResult``` action result that will redirect the user (```Response.Redirect```) to the login page.

Instead, I would like to make a client-side post, returning a JSON object with the authentication url. Ignore now the intricacies of detecting a successful login in the popup.

```
{
  "success": true,"
  "redirectUri": "http://somewhere.com"
}
```

I managed to do it with a hack, but I'm wondering if it should be supported to have a ```Authentication.ChallengeAsync``` that returns a ```OAuthRedirectToAuthorizationContext``` for implementers to do with it as they like.

Here is my hack if anyone is interested.

```c#
app.UseGoogleAuthentication(options =>
{
    options.Events = new OAuthEvents()
    {
        OnRedirectToAuthorizationEndpoint = (context) =>
        {
            if (context.HttpContext.Items.ContainsKey("OnRedirectToAuthorizationEndpointRequest")
                && (bool) context.HttpContext.Items["OnRedirectToAuthorizationEndpointRequest"])
            {
                context.HttpContext.Items["OnRedirectToAuthorizationEndpoint"] = context;
            }
            return Task.FromResult(0);
        }
    };
});
```

```c#
[Route("externallogin")]
[HttpPost]
public async Task<object> ExternalLogin([FromBody]ExternalLoginModel model)
{
    var properties = _signInManager.ConfigureExternalAuthenticationProperties(model.Provider, "/account/externallogincallback");

    HttpContext.Items["OnRedirectToAuthorizationEndpointRequest"] = true;
    await HttpContext.Authentication.ChallengeAsync(model.Provider, properties);

    if (HttpContext.Items.ContainsKey("OnRedirectToAuthorizationEndpoint"))
    {
        var redirectContext = (OAuthRedirectToAuthorizationContext)HttpContext.Items["OnRedirectToAuthorizationEndpoint"];
        return new
        {
            success = true,
            redirectUri = redirectContext.RedirectUri
        };
    }

    return new
    {
        success = false
    };
}
```

**Comment by Eilon** [comment]
3rd party auth generally can't be run within a dialog in a traditional OAuth redirect - it requires a full-page handshake/post between the main app, and the auth provider. This can be done at most for local forms/cookie auth.

To do something like this you'd need to instead use the auth provider's client-side library, which might return a JWT token that can then be used with the main app using the JwtBearerMiddleware.
