### ISSUE TITLE
AuthorizeAsync should not require a resource to be provided when passing a requirement

### ISSUE THREAD

**Issue by benfoster** [aspnet/Security#753]
`IAuthorizationService` has the following extension for authorizing using an `IAuthorizationRequirement` that requires a resource to be provided.

```
Task<bool> AuthorizeAsync(this IAuthorizationService service, ClaimsPrincipal user, object resource, IAuthorizationRequirement requirement); 
```

The resource should be optional or another extension method provided that does not require it since there are cases where we want to invoke an authorization handler but pass contextual information such as the operation that is being attempted (so an attribute is not viable). A good example of this is when *creating* a resource:

```
        public async Task<IActionResult> Create(int siteId)
        {
            if (await authZ.AuthorizeAsync(User, null, ProjectOperations.Create))
            {
                return Ok();
            }
            else
            {
                return new ChallengeResult();
            }
        }
```

In any case, the above code actually works (passing `null` as the resource) but it's not clear that this is optional from the API.

**Comment by Eilon** [comment]
We will clear this up in the doc comments for the APIs.

**Comment by Eilon** [comment]
We will add docs for this for 1.0.0 in https://github.com/aspnet/Security/issues/816.

**Comment by HaoK** [comment]
Resolved via https://github.com/aspnet/Security/commit/666ad0fc3b6027e8efc0df3595abc982d6921478
