### ISSUE TITLE
Using Authorization Policies for permissions

### ISSUE THREAD

**Issue by benfoster** [aspnet/Security#754]
I started this discussion on Twitter with @blowdart based on my experience as described [here](https://gist.github.com/benfoster/38745e169a285320d57b).

Essentially I was looking for a way to decorate my API actions with the permissions that users must have in order to access them. Using RC1 I end up with a one-to-one mapping between policies and handlers which is far from ideal. Really we want to decorate our actions once and have a single handler that checks if the user has the appropriate permission claim e.g:

```
[RequirePermission("projects.create")]
public async Task<IActionResult> Create(int siteId)
{

}
```

@blowdart mentioned that in RC2 we can create a custom authorization policy provider and then pass the required permission in the policy name. This would work but doesn't seem like a great workaround, especially as we'll also be using policies in their originally designed manner. We'd end up having to create a provider with logic like this:

```
if (policyName.StartsWith("permission.")) 
{
	
} 
else 
{
	base.CreatePolicy(...)
}
```

We could do with better guidance on how to handle application permissions as they're common-place with role-based access control. The resource based policy handlers have their place when the authZ rules dependent on the resource itself but are overkill when our rules are based at the controller or action level.

**Comment by davidfowl** [comment]
When using the auth system with MVC the resource is the action itself. What's wrong with the policy provider approach? There's a general impedance mismatch as well because the whole idea was to decouple the system from mvc, so if you decorate controllers with data that you expect to flow to the handler then you're effectively coupling to mvc (which is maybe fine for your case).

**Comment by blowdart** [comment]
I talked to @HaoK who is currently in Vegas. To provide support for both your custom policy provider could just fallback to the default policy provider.

**Comment by benfoster** [comment]
Yeah I'm fine with that coupling. Our API is the entry point to our
resources. We'll still need some resource based policies but not
everywhere. I'd rather have this coupling than have to create a new policy
for every single permission in the app. Just my personal preference.

**Comment by Eilon** [comment]
Doesn't seem to be any further action required here. You should be able to try the latest stable RC2 bits from the MyGet feed at https://www.myget.org/gallery/aspnetrelease
