### ISSUE TITLE
DefaultAuthorizationService call to _logger.UserAuthorizationSucceeded always has a null user

### ISSUE THREAD

**Issue by strtdusty** [aspnet/Security#755]
All of my API call logs say "Authorization was successful for user: null" because Name is always null on user.Identity.  It seems the name would always be populated from an identity token which usually wouldn't be passed to an API.  It seems the best you could do here would be to log the sub claim?  Maybe I'm missing something though.

**Comment by blowdart** [comment]
@HaoK - probably need a few claims to look for here, not just name

**Comment by HaoK** [comment]
Yeah we assumed name would be universally available, guess not for API, We could trim the msg when there's no name.  Or is there a backup claim we can use instead of name?  NameIdentifier?

**Comment by blowdart** [comment]
Yea, fall back to NameIdentifier, then maybe SID & UPN? Are we checking the NameClaimType? We should honour that first

**Comment by HaoK** [comment]
We don't do much logic right now, we can replace the simple logic with a helper method that does fallback if name is null

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authorization/DefaultAuthorizationService.cs#L54

**Comment by blowdart** [comment]
Yea, that needs improving :)

**Comment by blowdart** [comment]
Can you squeeze it into RC2?

**Comment by HaoK** [comment]
This should go through triage since its only affecting logging messages

**Comment by blowdart** [comment]
Spoilsport :p I'm still leaving it assigned to you though

**Comment by brentschmaltz** [comment]
For OIDC, the 'sub' claim is required. 
@strtdusty what flow are you using? OIDC MW or OAuth MW.
What provider are you using?

**Comment by strtdusty** [comment]
OIDC MW using AAD

**Comment by brentschmaltz** [comment]
@strtdusty Identity.Name transitively maps to 'unique_name'.  There is a way to control which claim is used to back Identity.Name.

**Comment by blowdart** [comment]
OK so we need sub too :)

**Comment by strtdusty** [comment]
I think sub would work fine. Probably the best option if all that is
available is the access token.

**Comment by HaoK** [comment]
4d6ad51f8a9354d8e62cf8d66db97bd991b7d93c
