### ISSUE TITLE
Re-evaluate sync vs async extension points in AuthenticationHandler

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#76]
AuthenticatoinHandler has several abstract/virtial APIs where it has both a sync and async overload, and the developer can choose to implement one or the other.  It's very common for the sync implementation to call the async method and block.  The base handler calls the sync and async overloads in different circumstances, such as sync calls from OnSendingHeaders.

Theory 1: Get rid of the sync calls, make OnSendingHeaders async.
Theory 2: Get rid of any async calls that are only called from OnSendingHeaders. Make sure there is only one overload of each extension point, be it sync or async.

**Comment by HaoK** [comment]
Yup, identity is fully async, I'm not a huge fan of having sync and async overloads either, +1 for eliminating sync if possible

**Comment by HaoK** [comment]
@Tratcher is this something you think we can/should do?  It definitely would make things a lot cleaner

**Comment by HaoK** [comment]
Note: We will have to convince @lodejard but I think we should try if you agree that this is the 'right' thing to do...

**Comment by Tratcher** [comment]
@HaoK I tried working through it once without much success. It's hard to get around the OnSendingHeaders code path. Take a look and let me know if you agree/disagree.

**Comment by HaoK** [comment]
Sounds like this is DOA since we can't get any traction...closing

**Comment by PinpointTownes** [comment]
Any idea why this suggestion was not easy to implement?

**Comment by Tratcher** [comment]
OnSendingHeaders was the big blocker. It needs to be sync (due to Stream.Write), but we wanted everything else to be async, so we're left with dual code paths.

**Comment by PinpointTownes** [comment]
And calling `Wait()`/`GetAwaiter().GetResult()` in `Stream.Write` was not an option?
Of course, it's not perfect but it has one merit: only developers using the sync write method would pay the price of the blocking OSH callbacks.

**Comment by TheBreadmanWalking** [comment]
bit of a noob, here. but, I'm messing with auth middleware. on googling i came to here so thought id post. 

On my handler,  it is asking for AuthenticateCore as it is abstract, I already have async method, so slightly unsure what to do with it right now.  Right, now, some other things are not compiling, so i cant test but once I will let you know happens. 

I expect I am doing something completely wrong, and I expect this is totally unrelated to the onheader thing, but thought just say, that asyc/sync. thing can get little confusing.
nl

**Comment by Tratcher** [comment]
AuthenticateCore is required, AuthenticateCoreAsync is an optional overload if you need to do anything async. See https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication/AuthenticationHandler.cs#L242

**Comment by PinpointTownes** [comment]
@Tratcher no remark concerning my last question? :smile:

**Comment by Tratcher** [comment]
We don't want to have Wait's hidden in the server code, we want them to be a conscious choice at the middleware layer.

**Comment by PinpointTownes** [comment]
Like that? :smile: 

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/KestrelEngine.cs#L102
https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/FrameResponseStream.cs#L63
https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Listener.cs#L112

**Comment by Tratcher** [comment]
Citing kestrel code isn't going to help your argument, we already know it's broken :-).

**Comment by PinpointTownes** [comment]
Well, I don't have access to aspnet/WebListener or aspnet/Helios, so... :smile: 

The best argument I have is that currently, everybody is paying the price of a `Wait()` call when having an authentication middleware in an ASP.NET 5 app, even the ones who use `WriteAsync`. With this change, only the ones using the synchronous `Write` would pay for that. And ideally, everybody should be encouraged to use `WriteAsync`.
