### ISSUE TITLE
Counting of failed authentications to limit system-abuse

### ISSUE THREAD

**Issue by DovydasNavickas** [aspnet/Security#762]
We we're talking with @PinpointTownes and @MonkeyJamboree that it would be nice-to-have counting of failed authentications to limit system-abuse. Most probably not up until RTM, but some time in the future, it would be really helpful to have this.

Ideally there would be mechanism diagnosing the system-abuse and when it thinks that there is one - reports it via event for the developer to act. Not sure yet how would that work, but let's discuss :+1: 

Maybe we could make use of diagnostic sources stack?
Like AspNetCore.Hosting does it here:
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplication.cs#L43

/cc @avanderhoorn

**Comment by DovydasNavickas** [comment]
@MonkeyJamboree
>What makes sense to me is to have all of the middleware (server, introspection, validation) have the capability or hooks into something (if aspnet/Security adds something), since you could have resource servers that want to log invalid token requests in an attempt to prevent spamming/scanning attacks as well as the authorization server for the actual authentication requests.

Exactly what this issue is about: preventing abuse of both resource and authorization servers.

**Comment by Eilon** [comment]
In general the underlying authentication provider would have logic like this. For example, ASP.NET Core Identity has a "max failed login attempts" that it tracks, Azure AD has some similar behavior, etc.

There's an event for handling "remote failures" of authentication here: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/Events/IRemoteAuthenticationEvents.cs#L13

This leaves an open question for how to handle failures in processing JWT tokens, which isn't clear.

This layer of authentication coordination doesn't seem like the right place to handle things like rate limiting.
