### ISSUE TITLE
How to use cookie storage with JWT middleware?

### ISSUE THREAD

**Issue by abdelkader27** [aspnet/Security#763]
I have read that localstorage is unsafe for storing the jwt on the client browser. So is it possible to use cookies to save the token on the browser with the Jwt bearer middleware or I need to implement my own middleware to use cookies with jwt?

**Comment by blowdart** [comment]
Did what you read give a reason? If the reason was "It's unencrypted and anyone can change it" the same is true for cookies. JWT is meant to be stored client side, and sent client side outside of a cookie, storing it in a cookie takes away the CSRF protection bearer tokens give.

**Comment by abdelkader27** [comment]
It's possible to use Http only, so the cookie can't be read.

**Comment by blowdart** [comment]
That's not entirely true. It can only not be read by the browser. An attacker can still see it if they have access to the machine,

**Comment by dallancarr** [comment]
CSRF protection is least of your worries in that case.

**Comment by blowdart** [comment]
True. But remember you can't get access to localstorage unless you're hosted on a page on the website that set it. So you'd need XSS first.

**Comment by dallancarr** [comment]
Absolutely I am not sure of any useful vunerabilty around stealing a short lived jwt as there would be other safeguards one hopes.

**Comment by abdelkader27** [comment]
Thank you for your answers, I just hope that in the futur the developer will have the choice.

**Comment by blowdart** [comment]
To use cookies for JWT? Nope, opens up too much CSRF.
