### ISSUE TITLE
VS 2013 OpenIdConnectAuthenticationNotifications RedirectToIdentityProvider

### ISSUE THREAD

**Issue by dronlinux** [aspnet/Security#764]
Hello!

Can't find sample: How to add **timestamp** to URL in RedirectToIdentityProvider. ? I need this parameter for OpenId Connect 1.0 server

**Comment by blowdart** [comment]
This is not an ASP.NET Core issue if you're using VS2013. Please ask on StackOverflow.

**Comment by Tratcher** [comment]
The OpenIdConnectMessage is an open property bag, try `context.ProtocolMessage.Parameters["timestamp"] = myTimestamp;`
