### ISSUE TITLE
Application startup fails when registering AzureActiveDirectoryBearerAuthentication and the federation endpoint is down

### ISSUE THREAD

**Issue by emanoelxavier** [aspnet/Security#766]
On my service startup I am using UseWindowsAzureActiveDirectoryBearerAuthentication and providing the metadata address as part of the AuthenticationOptions. When the application starts the middleware is registered and if the provided address is not reachable the start up fails with:

[WebException: The remote name could not be resolved: 'login.windows-ppe2.net']
   System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) +764
   System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar) +78

[HttpRequestException: An error occurred while sending the request.]

[AggregateException: One or more errors occurred.]
   System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) +4455248
   Microsoft.Owin.Security.ActiveDirectory.WsFedMetadataRetriever.GetSigningKeys(String metadataEndpoint, TimeSpan backchannelTimeout, HttpMessageHandler backchannelHttpHandler) +215
   Microsoft.Owin.Security.ActiveDirectory.WsFedCachingSecurityTokenProvider.RetrieveMetadata() +223
   Microsoft.Owin.Security.ActiveDirectory.WsFedCachingSecurityTokenProvider..ctor(String metadataEndpoint, ICertificateValidator backchannelCertificateValidator, TimeSpan backchannelTimeout, HttpMessageHandler backchannelHttpHandler) +382
   Owin.WindowsAzureActiveDirectoryBearerAuthenticationExtensions.UseWindowsAzureActiveDirectoryBearerAuthentication(IAppBuilder app, WindowsAzureActiveDirectoryBearerAuthenticationOptions options) +199

Is there a way to ignore this failure and let the application start gracefully? I still need the middleware to be registered, it will be used for requests with a bearer token but it is unimportant for all other requests that don't have that token. My expectation is that, while the end point is down, requests with the token would fail and I would be able to log a message regarding the fact that the signing keys are not available. All other requests should succeed though (as allowed by a deeper custom authorization layer).

**Comment by blowdart** [comment]
This isn't an ASP.NET Core issue, so closing. It's an issue with previous versions. But to answer your question, no, there's no way to ignore the error.
