### ISSUE TITLE
It seems like PostLogoutRedirectUri doesn't do anything in OIDC

### ISSUE THREAD

**Issue by gzak** [aspnet/Security#767]
Looking though the RC1 branch, I only see that property getting set, I never see it getting read. Has this functionality simply not been implemented yet in RC1?

That's certainly what we're seeing in our app. On signout, we expect the user to get redirected to our identity server's logout path, but there's no redirect.

**Comment by Tratcher** [comment]
It's here: https://github.com/aspnet/Security/blob/1.0.0-rc1/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L82-L93

**Comment by Tratcher** [comment]
It sounds like you're confusing PostLogoutRedirectUri with EndSessionEndpoint from the config metadata. EndSessionEndpoint is where you're redirected to log out. PostLogoutRedirectUri is where you're redirected after the logout has finished.

**Comment by gzak** [comment]
You're right about my confusion of the two properties. The `options` for OIDC exposes a `PostLogoutRedirectUri` property, but no `EndSessionEndpoint` property. Should it be handled in an even handler? Or just do it in manually in our main signout action method?

Regarding the reference you pointed out, I saw that too but didn't see any subsequent usage of that property from the `message` object. So it gets assigned there, but then never used. Or am I missing it again?

**Comment by gzak** [comment]
Nvm, found it, it's in `options.Configuration` rather than on `options` directly. Will try and let you know what behavior I get.

**Comment by Tratcher** [comment]
PostLogoutRedirectUri isn't consumed locally, it's consumed by the identity server after sign-out.

**Comment by gzak** [comment]
Is there an example of setting the `EndSessionEndpoint` property? I noticed that in the `Action<OpenIdConnectOptions>` overload of configuring the OIDC options, the `options.Configuration` property is null. If I set it to a new instance with just the `EndSessionEndpoint

**Comment by Tratcher** [comment]
EndSessionEndpoint shouldn't be set locally, it should be set in the metadata document downloaded from the identity server. Failing that, you need to set the entire Configuration.

**Comment by gzak** [comment]
We're trying to enable [RP-initiated logout](http://openid.net/specs/openid-connect-session-1_0.html#RPLogout). But it looks like the only way to do so is to implement our own logout action on some controller, and in it, do something like this:

```
public async Task<IActionResult> Signout()
{
   await HttpContext.Authentication.SignOutAsync("Oidc");
   await HttpContext.Authentication.SignOutAsync("Cookies");

   return Redirect(_endSessionEndpoint);
}
```

Which means that I have to capture that endpoint from ID server's metadata response and expose it to the app. It feels a bit icky, spreading identity concerns throughout the app... but is that ultimately the best alternative?

**Comment by Tratcher** [comment]
It should be:

```
public async Task<IActionResult> Signout()
{
   await HttpContext.Authentication.SignOutAsync("Cookies");
   await HttpContext.Authentication.SignOutAsync("Oidc");

   return new EmptyResult();
}
```

What's the full response status and headers when you do this?

**Comment by gzak** [comment]
Interesting, I assumed that `Ok()` and `new EmptyResult()` were roughly the same, but it's definitely redirecting to the `EndSessionEndpoint` now as expected. The response from there was a 302 to the identity server's `/logout` route.

Thank you!

**Comment by Tratcher** [comment]
FYI: in RC2 this can all be replaced by `new SignOutResult("Cookies", "Oidc");` to avoid this kind of confusion.

**Comment by PinpointTownes** [comment]
... or better:

```
public IActionResult Signout() => SignOut("Cookies", "Oidc");
```
