### ISSUE TITLE
Supported for "hosted domain" authentication URI parameter?

### ISSUE THREAD

**Issue by adammodlin** [aspnet/Security#768]
I want to limit my Google Auth to a specific Google Apps custom domain. According to the Google documentation (https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters), you can do this by adding a "hosted domain" parameter to the authentication URI. 

If this isn't supported currently (and I don't think it is) I'd like to help implement it and would appreciate any pointers towards where to begin.

**Comment by adammodlin** [comment]
Specifically, it looks like the adding of the parameter might happen in GoogleHandler.cs around line 88. Would need to figure out how to inject the hd parameter and where to validate that the returned ID token has an hd claim as well.

**Comment by Tratcher** [comment]
OIDC is a superset of OAuth2.

I don’t see that property in the OAuth2 docs:
https://developers.google.com/identity/protocols/OAuth2WebServer#redirecting

I think you’d have to enforce this after the external login flow.

That said, you can also use the OpenIdConnect middleware with Google. In that case you’d hook one of the redirect events and add your property to the OpenIdConnectMessage.

**Comment by adammodlin** [comment]
I think I will just enforce it after the login flow which is currently what I have implemented. 

It looks like if you add that query param to google even for their OAuth2 redirection it is honored but since it's not part of their docs I understand why you wouldn't want to support it.

Appreciate the input, it would be nice if we had an out-of-the-box solution for this.

**Comment by Tratcher** [comment]
Adding the extra field to the url wouldn't be a big deal, but validating the result is a different matter. OAuth treats all the tokens as opaque, where OIDC has a defined format. The OAuth middleware isn't equipped to open up the token and validate the contents.

Maybe in the future we'll provide a GoogleOIDC middleware that implements quirks like this.

**Comment by adammodlin** [comment]
Thanks for explaining the differences, I'm not very familiar with them so I
appreciate it. That makes sense, I will just ensure that the email address
claim matches my custom domain inside of the login/register methods.

**Comment by Eilon** [comment]
Our recommendation for using OIDC with Google is to use the OIDC middleware that is also available in ASP.NET Core.

**Comment by adammodlin** [comment]
I see, so you recommend I use the generic OpenIDConnect middleware with Google if I need this functionality? Thanks for great responses, I am very excited for .NET Core.

**Comment by Tratcher** [comment]
Yes, with the generic OIDC middleware you have access to the protocol via Events to do this all in a more structured fashion.

**Comment by adammodlin** [comment]
I'm going to go ahead and close out this issue unless there are any objections. I appreciate the guidance.
