### ISSUE TITLE
AuthenticationScheme: Bearer was forbidden

### ISSUE THREAD

**Issue by Lutando** [aspnet/Security#769]
I have an RC2 application `rc2-20222` in which I am protecting my RESTful endpoints with resource scope claims.

Upon updating my project this morning I noticed that authentication was not working anymore.

In my Startup.cs

```
app.UseJwtBearerAuthentication(new JwtBearerOptions
{
	Authority = Configuration["Authorization:Authority"],
	Audience = Configuration["Authorization:Audience"],
	AutomaticAuthenticate = true,
	AutomaticChallenge = true,
	RequireHttpsMetadata = false
});
```

and I add my policies using the normal method.

```
.AddPolicy("myproject:resource:read", new AuthorizationPolicy(new IAuthorizationRequirement[]
{
        new ClaimsAuthorizationRequirement("scope", new [] { "myproject:resource:read" }),
        new DenyAnonymousAuthorizationRequirement(),
}, new[] { "Bearer" }));
```
here is a skeleton of my controller
```
[HttpGet("{value}")]
[Authorize("myproject:resource:read")]
public IActionResult GetResource(string value)
{
	return new OkResult();
}
```

And I am getting the following messages via log output:

```
Microsoft.AspNetCore.Routing.Tree.TreeRouter: Debug: Request successfully matched the route with name '' and template 'myresource/{value}'.
Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler: Debug: Executing action MyProject.Controllers.MyResourceController.GetResource (MyProject.Api)
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware: Information: AuthenticationScheme: Bearer was successfully authenticated.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed for user: 62520448-da4b-4d0a-bb44-c67247d6b5cb.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Warning: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Microsoft.AspNetCore.Mvc.ChallengeResult: Information: Executing ChallengeResult with authentication schemes (Bearer).
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware: Information: AuthenticationScheme: Bearer was forbidden.
Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler: Information: Executed action MyProject.Controllers.ResourcesController.GetResource 
```

that `user` is the subject_id within the bearer token

The token is valid as it works in my other rc1-update1 projects fine but not for this one. As the error message says, it says that the `AuthenticationScheme: Bearer was forbidden`

**Comment by Tratcher** [comment]
Your authentication seems fine, it's your authorization that's failing.
```
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed for user: 62520448-da4b-4d0a-bb44-c67247d6b5cb.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Warning: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
```
Start by making sure your AuthorizationPolicy is correct and that your user has the requisite claims.

**Comment by Tratcher** [comment]
@HaoK

**Comment by HaoK** [comment]
Yeah most likely the scope claim wasn't found since that's the most likely requirement to have failed.

**Comment by Lutando** [comment]
The scope claim is definitely exists in the JWT and it appears in the Auth header. I have a stripped down version of the application. Similar code works fine if I run this scenario in its `rc1-update1` variant. Maybe now is a good time to mention that I am targeting the `dnx451` framework.

Code that can reproduce the issue can be found here - > https://github.com/Lutando/SecurityIssue769

**Comment by Eilon** [comment]
@HaoK can you take a look at this?

**Comment by HaoK** [comment]
This repro is missing the important part of the repro which is what's in the JWT token/identity.  

One thing you can try, can you eliminate the explicit authentication scheme in your Auth?  That might be causing issues since you already have AuthomaticAuthenticate and Challenge enabled.

See if that makes any difference.

Basically get rid of the "Bearer" array

```
                options.AddPolicy("myscope", new AuthorizationPolicy(new IAuthorizationRequirement[]
                {
                    new ClaimsAuthorizationRequirement("Scope", new[] {"myscope"}),
                    new DenyAnonymousAuthorizationRequirement(),
                }, new[] { "Bearer" }));
```

**Comment by Lutando** [comment]
@HaoK then how can I register different policies for each of my endpoints? 

How will I do explicit authentication on my resources/actions then?

Basically I want different requirements for each of my API endpoints/resources. Nothing too complicated just that I want to model my scopes around my (different) resources that my API provides access to.

AuthorizationPolicy() requires an argument of enumerable list of authentication scheme names so that doesn't work out too well unless I am misunderstanding you.

**Comment by HaoK** [comment]
You can register a different policy per endpoint using different policy names.  You can pass in an empty list for the auth schemes, you can try the other overload which might be a little cleaner for that:

```
 options.AddPolicy("myscope", policy => policy
   .RequireClaim("Scope", "myscope")
   .RequireAuthenticatedUser());
```

From your simple repro, its almost certainly caused by no scope claim with "myscope" being found in the JwtBearer identity.

**Comment by Lutando** [comment]
When I try that I still get an error via Kestrel Logging:

```
Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
Executing ChallengeResult with authentication schemes ().
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[13]
AuthenticationScheme: Bearer was forbidden.
info: Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler[2]
```

I am certain that the scope claim exists in the JWT since it is there when I decode it and when I peek inside` HttpContext.User.Identity.Claims` within my controller (without Authorize annotation) I can see all the claims correctly populated there.

**Comment by HaoK** [comment]
Well there must be something wrong with your identity,

The following test works fine for me, so double check that your identity is actually Authenticated (does it have an authentication type specified or you can remove the RequireAuthenticatedUser to see if that lets it through, also that the casing is correct in your claims).

```
        [Fact]
        public async Task Authorize_ScopeTest()
        {
            // Arrange
            var authorizationService = BuildAuthorizationService(services =>
            {
                services.AddAuthorization(options =>
                {
                    options.AddPolicy("myscope", policy => policy.RequireClaim("Scope", "myscope").RequireAuthenticatedUser());
                });
            });
            var user = new ClaimsPrincipal(new ClaimsIdentity(new Claim[] { new Claim("Scope", "myscope") }, "myscope"));

            // Act
            var allowed = await authorizationService.AuthorizeAsync(user, "myscope");

            // Assert
            Assert.True(allowed);
        }
```

**Comment by HaoK** [comment]
Closing this as I can't reproduce any issue with the framework code, please reopen if you are still seeing issues

**Comment by mafshin** [comment]
I'm getting the same as detailed [here](http://stackoverflow.com/questions/39051705/bearer-was-forbidden-with-authorize-filter-in-identityserver4).

Is this issue the result of a misconfiguration or something else?

**Comment by spottedmahn** [comment]
I forgot to inject my `IAuthorizationHandler` and that caused this same error:

> AuthenticationScheme: Bearer was forbidden 

---

Custom policy-based authorization documentation -> [Handler Registration](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies#handler-registration)

```c#
services.AddSingleton<IAuthorizationHandler, YourHandlerClass>();
```

---

Shouldn't I been told "Hey, there are no handler for your policy?"

**Comment by Ibro** [comment]
I have the same problem as @ spottedmahn , I have a lot of Handlers in my app and forgot to register one of them and I get this error, which is **really** misleading.

Can someone look at this? @Eilon  @HaoK 
Thanks

**Comment by spottedmahn** [comment]
Hi @Ibro - since this issue is closed, it might not get much traction.  I've created a new issue #1676, FYI.

**Comment by Ibro** [comment]
Thanks @spottedmahn , good idea!
