### ISSUE TITLE
Multiple ASP.NET OpenID Connect cookies created .. eventually hitting browser limits

### ISSUE THREAD

**Issue by liquidboy** [aspnet/Security#770]
Our ASP.NET MVC Core application has OpenID Connect configured ...
We don't use ASP.NET session ...

Seems like the constant back and forth between the ASP.NET MVC application and an IdentityProvider site causes MANY "ASPNet.OpenIDConnect.Nonce & State" cookies to be created ... 

... and eventually there will be too many cookies and the browser crashes ... we hit these "no of cookies per domain" limits  [BrowserCookieLimits](http://browsercookielimits.squawky.net/)

![the excessive cookies built up in the space of minutes](https://pbs.twimg.com/media/CfZ03ioVIAQAZjZ.jpg:large
)

Our testers discovered this as there automation tests constantly moved back and forth between the IdentityProvider site and the ASP.NET Core MVC site (with OpenID connect configured) ..  

p.s. I also see from the source code that there is a default [15minute](https://github.com/aspnet/Security/search?utf8=%E2%9C%93&q=15+minute) timeout on these openid cookies

p.s. I will try to create a repo for this ....

**Comment by liquidboy** [comment]
I believe I found a similar issue related to the katana project :  http://katanaproject.codeplex.com/workitem/402

**Comment by liquidboy** [comment]
my apologies .. after more research it seems this is related to the already created issue  #179

**Comment by Tratcher** [comment]
Are you testing error scenarios or successful logins? Those cookies should be deleted durring sucessful login flows:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L439
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L789
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L399
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs#L167

They won't be cleaned up in error scenarios, which is what the timeout is for.

**Comment by jmickael** [comment]
I solved this issue by cleaning up the cookie before each signon.  I used a NuGet package called 
Kentor.OwinCookieSaver 1.1.1 
After using this package I haven't seen the problem since.  I added this to my Startup pipeline:

    public partial class Startup
    {
        /// <summary>
        /// Configures OpenIDConnect Authentication & Adds Custom Application Authorization Logic on User Login.
        /// </summary>
        /// <param name="app">The application represented by a <see cref="IAppBuilder"/> object.</param>
        public void ConfigureAuth(IAppBuilder app)
        {
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
            app.UseKentorOwinCookieSaver();
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                CookieSecure = CookieSecureOption.Always,
                ExpireTimeSpan = TimeSpan.FromMinutes(720),
                SlidingExpiration = true,
                CookieHttpOnly = true
            });
            //Configure OpenIDConnect, register callbacks for OpenIDConnect Notifications
            app.UseOpenIdConnectAuthentication(
                new OpenIdConnectAuthenticationOptions
                {
                ....

**Comment by Tratcher** [comment]
FYI: Kentor.OwinCookieSaver's approach is very brittle. https://github.com/KentorIT/owin-cookie-saver/blob/master/Kentor.OwinCookieSaver/KentorOwinCookieSaverMiddleware.cs#L32 Re-parsing cookies is problematic at best, and the same goes for setting headers after Next.

**Comment by liquidboy** [comment]
@Tratcher  I believe the problem is the test user isn't even logging in ....  they are hitting the IdentityProvider then going back to the ASP.NET Core MVC app  without logging in  (RegisterUser or ForgotPassword links)  ... see screen flow below ...  

Thus I believe this is why the Nonce cookies are not getting cleared out .. ie the test user isn't going thru the login process thus the nonce isn't getting cleared.

![user flow between IdentityProvider and ASP.NET Core MVC OpenID connect app](https://pbs.twimg.com/media/CfeJCOjUIAAJYlw.jpg:large)

**Comment by RonniePitts** [comment]
back on this subject again, I've noticed after multiple requests users will start failing to authentication.
It seems to get stuck after the notification OnResponseSignedIn and returns back unauthenticated.. Restarting the server temporary fixes the issue.
