### ISSUE TITLE
Push fixed IdentityModel packages to aspnetcidev

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#775]
IdentityModel was recently updated to fix a regression in the JWT stack that prevented JWT tokens from being correctly signed when calling `JwtSecurityTokenHandler.WriteToken`.

Sadly, all the ASP.NET MyGet feeds (including aspnetcidev) are still using the old package:

![image](https://cloud.githubusercontent.com/assets/6998306/14446595/302a394a-0058-11e6-9814-51ee234ac8f1.png)

![image](https://cloud.githubusercontent.com/assets/6998306/14446650/aad2a1d2-0058-11e6-8197-5a5d8db8bb55.png)

Any idea when the fixed package will be copied from the Azure AD nightly feed to the aspnetcidev feed?

Related topics:

https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/232
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/360
https://github.com/capesean/openiddict-test/issues/8
https://github.com/openiddict/openiddict-core/issues/84

/cc @Eilon @brentschmaltz
 
/cc @wesamco @capesean @sunsided @shima20 @SkyQuant

**Comment by kwaclaw** [comment]
Is there a workaround? Maybe appending RawSignature to token string?

**Comment by Eilon** [comment]
@PinpointTownes just so you know, this will happen automatically the next time we get a good build, so there's no specific action to take here.

**Comment by PinpointTownes** [comment]
@Eilon by "good build", I guess you mean coherent ASP.NET Core packages?

AFAICT, new ASP.NET Core packages were pushed a few times last week and probably 3 or 4 times yesterday (the last wave was pushed 7 hours ago, at the time of writing).

**Comment by Tratcher** [comment]
We only pull the identity model packages when we pull our other dependencies like core clr and cli. Some of those dependencies have been blocked for a few days.

**Comment by PinpointTownes** [comment]
Alright. The JWT bug is causing too much pain to the ASOS/OpenIddict users ATM so I'll update the aspnet-contrib feed to mirror the Azure AD packages.

Leaving this ticket open to make sure RC2-final gets the fixed package.

**Comment by Eilon** [comment]
Indeed, our build process takes a snapshot of the latest CLR, CLI, CoreFX, Roslyn, and Azure AD/Identity packages all at once, runs tests on that, and if it passes, it accepts them all. If anything fails, we block the acceptance so that we can investigate.

**Comment by PinpointTownes** [comment]
@Eilon thanks for the info. 

FYI, mirroring the Azure AD packages on the aspnet-contrib allowed us to fix the JWT bug.

**Comment by Eilon** [comment]
@PinpointTownes we now have `Microsoft.IdentityModel.*` v1.0.0-rc2-304071940 on aspnetvnext (dev) and aspnetrelease (release). Is that all you need?

**Comment by PinpointTownes** [comment]
Yep, thanks! That said, there's another (major) bug in Wilson, that impacts JSON array deserialization in the JWT stack: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/365.

I'd recommend keeping this ticket open to ensure RC2 final gets the appropriate fix.

**Comment by Eilon** [comment]
@PinpointTownes sure no problem.

**Comment by ryanbrandenburg** [comment]
@PinpointTownes we've had coherent builds since your note about the JSON de-serialization, is there a quick way you can double check that those fixes made it in or are you good?

**Comment by PinpointTownes** [comment]
@ryanbrandenburg thanks! I'll ping @stephenstroud tomorrow and see if the recent builds fixed the issue he was seeing with multiple claims/JSON arrays.

**Comment by PinpointTownes** [comment]
@ryanbrandenburg fix confirmed, thanks :clap: 

![image](https://cloud.githubusercontent.com/assets/6998306/14880980/44fed718-0d32-11e6-947e-7d8d2851d247.png)
