### ISSUE TITLE
JwtBearer deserializes multiple claims with same key

### ISSUE THREAD

**Issue by Kukkimonsuta** [aspnet/Security#779]
## Setup

JWT
```
{
    "aud": "http://test.local/api/",
    "exp": 1460647835,
    "emailaddress": [
        "foo1@bar.com",
        "foo2@bar.com"
    ],
    "name": "Foo Bar",
    "iss": "http://test.local/api/"
}
```

## Expected behavior

I get following in `HttpContext.User.Claims`

Type | Value | ValueType
------------ | ------------- | -------------
name | Foo Bar | http://www.w3.org/2001/XMLSchema#string
iss | http://test.local/api/ | http://www.w3.org/2001/XMLSchema#string
aud | http://test.local/api/ | http://www.w3.org/2001/XMLSchema#string
exp | 1460647835 | http://www.w3.org/2001/XMLSchema#integer64
emailaddress | foo1@bar.com | http://www.w3.org/2001/XMLSchema#string
emailaddress | foo2@bar.com | http://www.w3.org/2001/XMLSchema#string

## Actual behavior

I get following in `HttpContext.User.Claims` (note the type and value in emailaddress)

Type | Value | ValueType
------------ | ------------- | -------------
name | Foo Bar | http://www.w3.org/2001/XMLSchema#string
iss | http://test.local/api/ | http://www.w3.org/2001/XMLSchema#string
aud | http://test.local/api/ | http://www.w3.org/2001/XMLSchema#string
exp | 1460647835 | http://www.w3.org/2001/XMLSchema#integer64
emailaddress | "foo1@bar.com" | Newtonsoft.Json.Linq.JValue
emailaddress | "foo2@bar.com" | Newtonsoft.Json.Linq.JValue

Possibly related to #769

**Comment by Tratcher** [comment]
This issue was moved to AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#366
