### ISSUE TITLE
Authorization Block comments and change to IAuthorizationService

### ISSUE THREAD

**Issue by MonkeyJamboree** [aspnet/Security#785]
Hey all,

After some discussion with @PinpointTownes about the JWT middleware and looking at the Authorization block (at https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNetCore.Authorization), I have some comments and suggestions for improvement. 

First off, Awesome job at abstracting out the interfaces, particularly the `IAuthorizationRequirement` abstraction and `AuthorizationHandler` class. I think it was implemented well and allows the stack to handle custom implementations and custom authorization requirements as needed by consumers. I also like that the different `IAuthorizationRequirement` are completely separated out.

I'll post the improvements as separate issues so they can be tracked and resolved independently. This is the first:

The `IAuthorizationService` exposes `AuthorizeAsync` that requires a `ClaimsPrincipal`. Several use cases come to mind wherein a consumer of the Authorization Block might want to make authorization decisions based on something in the `HttpContext` itself rather than anything available in a `ClaimsPrincipal`:

- IP Address or host name based authorization for enterprise-level server trust authorization
- Using `AuthenticationProperties` in an `AuthenticationTicket` that shouldn't really be exposed as claims in a principal (example: OAuth/OIDC scopes, as discussed at https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/issues/8)
- Using tokens or other authentication mechanisms that are not explicitly tied to a principal, that may not conform to a standard or be associated with a principal (such as custom time- or use quantity-limited tokens, or server- or machine-level tokens)
- Custom `HttpRequest`/`HttpResponse` header or query string decisions (handling something similar to Google's "API key" seen at https://developers.google.com/+/web/api/rest/oauth#acquiring-and-using-an-api-key or writing custom WWW-Authenticate headers for simplistic authentication/authorization schemes)
- Request or server date/time scenarios where services are only available between specific hours
- Probably many others including supporting authorization schemes from legacy systems while migration to new approaches happens

The main reason behind requesting this change is that a `ClaimsPrincipal` is not really all that appropriate for all authorization decisions without a lot of hacky workarounds (such as creating specific custom claims for standard things already available in the `HttpContext` class).

**Comment by MonkeyJamboree** [comment]
What, exactly, is the reasoning for using ClaimsPrincipal instead of something more flexible or all-encompassing? Also, could generics be used on the handler/requirements so that the stack can be used without any explicit dependencies?

**Comment by Eilon** [comment]
At this time we are not looking to make such changes to the system. We believe that the current implementation supports a wide variety of scenarios, and is easy to use for most scenarios. Though we could certainly add more flexibility in some cases, we think it would make the more common scenarios more difficult to achieve.
