### ISSUE TITLE
Better abstraction for AuthorizationPolicyBuilder

### ISSUE THREAD

**Issue by MonkeyJamboree** [aspnet/Security#786]
I suggest moving most of the `Require*` methods on AuthorizationPolicyBuilder to extensions that rely on either the `AddRequirements` method or directly adds the requirements to the `Requirements` property.

The intent of this change would be to keep the builder's API simple and abstracted away from any given `IAuthorizationRequirement` implementation.

**Comment by Eilon** [comment]
At this time we are not looking to make such changes to the system.
