### ISSUE TITLE
Microsoft.AspNetCore.Authentication.Github

### ISSUE THREAD

**Issue by ikourfaln** [aspnet/Security#787]
hi,

please Im looking for configuring Github OAuth provider for ASP.NET Core.
I find this http://www.oauthforaspnet.com but its not for asp.net core.
plz can someone give me a source or a tut to find how ?

thanx for advance

**Comment by Tratcher** [comment]
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src/AspNet.Security.OAuth.GitHub

**Comment by ikourfaln** [comment]
Thanx a lot @Tratcher
