### ISSUE TITLE
Could not be resolved

### ISSUE THREAD

**Issue by gaia-ggm** [aspnet/Security#788]
Hi,

I am getting the following message when I try to restore packages for my project:

> The dependency Microsoft.AspNet.Authentication.JwtBearer >= 1.0.0-rc1-final could not be resolved. 

Do you know anything about this error?

**Comment by moozzyk** [comment]
The package is there: https://www.nuget.org/packages/Microsoft.AspNet.Authentication.JwtBearer/1.0.0-rc1-final 
Show your project.json

**Comment by gaia-ggm** [comment]
That's what I find strange. Here is my project.json file.

`{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Core.Model": "",
    "Core.Repositories": "",
    "Infrastructure.Repositories": "",
    "Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final",
    "Microsoft.AspNet.Cors": "6.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.Formatters.Json": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Newtonsoft.Json": "8.0.1-beta3"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx451": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}
`

**Comment by Eilon** [comment]
I just tried this by creating a `project.json` file with the JSON above, except that I removed these lines:

```
    "Core.Model": "",
    "Core.Repositories": "",
    "Infrastructure.Repositories": "",
```

Then I ran `dnu restore` and it succeeded.

**Comment by gaia-ggm** [comment]
The problem is now solved. Somehow the NuGet package soruce had been deselected in Visual Sudio. When I checked it again everything works again.

![image](https://cloud.githubusercontent.com/assets/15210260/14778279/5ab26730-0ad2-11e6-805f-e29edfaa11ef.png)
