### ISSUE TITLE
How to handle scenarios involving expires_in and refresh_token with OAuth

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Security#789]
We are using `CookieAuthenticationHandler` with `OAuthAuthenticationHandler`. Right now we are calling `context.RejectIdenty()` in the `ValidatePrincipal` event of the cookie authentication handler, but this has negative consequences for POST requests. 

We need to be able to invalidate users' authentication tickets when the `expires_in` limit has been reached, and we need to handle this opaquely, without obliterating the users' submitted form data in the case of a POST request. We would like to be able to issue a `refresh` request to the OAuth token endpoint in order to obtain the new `access_token` and `expires_in` value so that we can enforce re-validation of a user's access rights at an arbitrary interval.

Ideally this would take advantage of the existing OAuth handler -- the new implementation in this library has been great so far by eliminating a lot of boilerplate from our multitude of small, private web applications, but in order to handle this `refresh_token` scenario, I am concerned that we would have to end up adding the same boilerplate after all.

Problems I am running into with trying to devise a clean solution:

1. I cannot call `AuthenticateAsync` (or other methods) targeting an authentication provider that is registered after the cookie handler (`No authentication handler is configured to authenticate for the scheme...`)
2. I can extract the function that configures the `OAuthOptions` into a method in order to not have to declare the settings multiple times, allowing me to access those options from within `ValidatePrincipal`, but then I have to construct the `HttpClient` and the `refresh` request and the calls to the `OAuthEvents` and so on by myself, effectively duplicating the work that has already been done in `OAuthHandler`. Also, it doesn't seem that I could extend `OAuthHandler` to create a `RefreshOAuthHandler` or something and insert it into the pipeline, largely because of point 1
3. I guess I don't really have a point 3

Please offer any suggestions or thoughts you may have for making this happen. :8ball:

**Comment by tuespetre** [comment]
I have put together an initial working implementation. I am using RC1 and I know a couple of details will change with RC2.

In `ValidatePrincipal`, after checking some things:
```
if (attemptRefresh)
{
    try
    {
        var oauth = OAuthAuthenticationOptions(appSettings.Value);

        var newPrincipal = await oauth.Refresh(
            httpContext: context.HttpContext,
            currentPrincipal: context.Principal);

        context.ReplacePrincipal(newPrincipal);
        context.ShouldRenew = true;
    }
    catch
    {
        context.RejectPrincipal();
    }
}
```

The `Refresh` extension method:
```
public static async Task<ClaimsPrincipal> Refresh(
    this OAuthOptions oauthOptions, 
    HttpContext httpContext, 
    ClaimsPrincipal currentPrincipal)
{
    var client = new HttpClient(oauthOptions.BackchannelHttpHandler ?? new HttpClientHandler())
    {
        Timeout = oauthOptions.BackchannelTimeout,
    };

    var request = new HttpRequestMessage(HttpMethod.Post, oauthOptions.TokenEndpoint)
    {
        Headers =
        {
            Accept =
            {
                new MediaTypeWithQualityHeaderValue("application/json")
            }
        },
        Content = new FormUrlEncodedContent(new Dictionary<string, string>
        {
            ["client_id"] = oauthOptions.ClientId,
            ["client_secret"] = oauthOptions.ClientSecret,
            ["grant_type"] = "refresh_token",
            ["refresh_token"] = currentPrincipal.FindFirst("refresh_token").Value,
        }),
    };

    var response = await client.SendAsync(request, httpContext.RequestAborted);

    response.EnsureSuccessStatusCode();

    var payload = JObject.Parse(await response.Content.ReadAsStringAsync());

    var identity = new ClaimsIdentity(oauthOptions.AuthenticationScheme);

    var tokens = new OAuthTokenResponse(payload);

    var context = new OAuthCreatingTicketContext(httpContext, oauthOptions, client, tokens)
    {
        Principal = new ClaimsPrincipal(identity),
    };

    await oauthOptions.Events.CreatingTicket(context);

    return context.Principal;
}
```

It's not a super amount of code to have to paste in each project, but it would still be nice if the OAuth library offered functionality similar to this.

**Comment by HaoK** [comment]
Yeah there's nothing built in for this, Identity needed to do something similar and has its own SecurityStampValidator: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SecurityStampValidator.cs

**Comment by HaoK** [comment]
I'm not sure we would add something specifically for OAuth but I do agree that there could be value in making it easier to plug into the ValidatePrincipal event that doesn't require quite so many manual steps.

**Comment by Eilon** [comment]
Ultimately there's nothing we know of that can be automatically done to preserve the browser's POST. A particular app could implement a behavior where values are posted via JavaScript, or perhaps preserved in browser local storage, but it would be an app-specific behavior.

One possible app-specific mitigation is to have periodic pings of the server to keep various tokens/cookies alive, and detect if they go bad and alert the user in the browser UI.

It's also worth noting that in the AuthenticationProperties in the OAuth events you pre-set the cookie expiration values and then the cookie middleware will take care of the rest. See https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L1022-L1035 for how this is plugged in.

**Comment by tuespetre** [comment]
@Eilon my point was that the 'refresh token' feature of OAuth does in fact offer a means of keeping the posted data intact while obtaining a new access token for the user. Of course, nothing can be done for cases where the cookie itself has expired, or become corrupt or otherwise impossible to deserialize or use, or has gone 'missing' from the browser. I have ideas in mind to deal with such scenarios but that is beyond the scope of this issue.

I did not intend for this issue to be a request for a solution to the POST issue in itself. Instead, I intended for it to be a request for an out-of-the-box way to take advantage of a specific feature of OAuth in which see great value for solving problems like the POST problem.

**Comment by leastprivilege** [comment]
Refresh tokens are for native applications (either server or client side). Once you are in such an environment you have plenty of options to "encapsulate" the refresh and always have a fresh token.

Not sure why this has to be linked to cookies or a POST - they a different concepts.
 
I wrapped that e.g. in an HTTP message handler.

https://github.com/IdentityModel/IdentityModel/blob/master/source/IdentityModel.Shared/Client/RefreshTokenHandler.cs

**Comment by tuespetre** [comment]
> Refresh tokens are for native applications (either server or client side). Once you are in such an environment you have plenty of options to "encapsulate" the refresh and always have a fresh token.

The basic description of refresh tokens in the spec just mentions 'client', though under security considerations, it says that `Authorization servers MAY issue refresh tokens to web application
   clients and native application clients.`

> Not sure why this has to be linked to cookies or a POST - they a different concepts.

I was providing my use-case-slash-background-story. I'm sorry, I should have been more explicit in stating that this issue is supposed to be a feature request. Reading my post again, it reads more like a StackOverflow question.
