### ISSUE TITLE
Add example for Azure AD B2C

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Security#792]
Please consider adding an example for Azure AD B2C

**Comment by Tratcher** [comment]
@vibronet?

**Comment by grahamehorner** [comment]
I have found a sample which uses OWIN with Azure AD B2C and I'm looking to use this as a base for a ASP.NET CORE 1.0 version; however I have a blocker as I'm unable to allocate/convert the follow line of code or locate the referenced dictionary ?

OpenIdConnectConfiguration config = await mgr.GetConfigurationByPolicyAsync(CancellationToken.None, notification.OwinContext.Authentication.AuthenticationResponseChallenge.Properties.Dictionary[Startup.PolicyKey]);
               
where would I find AuthenticationResponseChallenge and/or the properties in the new framework OpenIdConnectEvents->OnRedirectToAuthenticationEndpoint ?

**Comment by Tratcher** [comment]
Can you link to that sample for context?

**Comment by grahamehorner** [comment]
here is the link for your reference https://github.com/AzureADQuickStarts/B2C-WebApp-OpenIDConnect-DotNet-SUSI  I would like to get this  working using ASP.NET CORE so that I can deploy on a Linux environment and/or with in Service Fabric and given this example is OWIN based it would be great to have a NON-OWIN implementation using kestrel.

**Comment by Tratcher** [comment]
This will be hard until https://github.com/aspnet/Security/pull/799 goes in.

**Comment by grahamehorner** [comment]
I don't understand how #799 relates? please explain I would have thought the config.json would be used for to hold the settings?

**Comment by muratg** [comment]
We're planning to release samples in RTM

**Comment by flagbug** [comment]
@muratg Any update on this?

**Comment by Eilon** [comment]
@vibronet can you point at any existing samples?

**Comment by Eilon** [comment]
@grahamehorner can you log a new issue on the https://github.com/AzureADQuickStarts/B2C-WebApp-OpenIDConnect-DotNet-SUSI repo?
