### ISSUE TITLE
OIDC argument validation

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#795]
The OIDC middleware does not validate if you set the ClientId or authority. It tries to fetch the metadata anyways, fails silently, and then generates redirects without any base uris.

We also need a better error if you fail to set the ClientSecret, but do enable one of the Code flows. Right now you'll get a 400/401 trying to redeem the code.

**Comment by PinpointTownes** [comment]
:+1: for requiring `ClientId` but :-1: for throwing an error if `ClientSecret` is not set, since one might want to use client authentication assertions instead of the good old `client_id`/`client_secret` couple.

**Comment by BrennanConroy** [comment]
962a74c4883e00da0666296c7c1751495f443ac0
