### ISSUE TITLE
The Postback from ADFS "4" to /signin-oidc in case of errors seems unhandled and results in a server error 500

### ISSUE THREAD

**Issue by lranders** [aspnet/Security#797]
Just for kicks I tried to misspell the **resource** parameter so ADFS couldn't find it.
The ADFS server is Windows 2016TP4.

That resulted in what looks like an unhandled exception and returned a blank page.
Is that supposed to happen?

I'm using the bits that come with ASP.NET 5 ("Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-rc1-final") pulled in from the standard app template as it stands right now.

Here are my options from startup.cs:

            app.UseOpenIdConnectAuthentication(opt =>
            {
                opt.AutomaticChallenge = true;
                opt.ClientId = Configuration["Authentication:ADFS:ClientId"];
                opt.MetadataAddress = Configuration["Authentication:ADFS:MetadataAddress"];
                opt.PostLogoutRedirectUri = Configuration["Authentication:ADFS:PostLogoutRedirectUri"];
                opt.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                opt.GetClaimsFromUserInfoEndpoint = true;
                opt.Resource = "https://myservice/myapix";
            });

If the resource exists, no error is produced and the application signs in just fine.

Here are the form data being posted back from ADFS:
> error=invalid_resource&error_description=MSIS9602%253a%2BThe%2Breceived%2B%2527resource%2527%2Bparameter%2Bis%2Binvalid.%2BThe%2Bauthorization%2Bserver%2Bcan%2Bnot%2Bfind%2Ba%2Bregistered%2Bresource%2Bwith%2Bthe%2Bspecified%2Bidentifier.&state=CfDJ8F-Np5GezkJPq6IqmCKE9OYaN5dzD_iisbmYXyVoJ446Tn8nLLYesNTGz1vytGa-LNNMnwKjMX24ahimN7eYe70r-LW8JF-KqAbXJYZw-7VTtdEaHdf2R_65RQDoF0jHJKDYZRiIOytCNGWIRTkQ5fjaFXaHPdvYhFJ4wlwrFtbzDpFJarkql4FOIVPGfz1IlcH473nMv7GT0-3qHkD1jCqntHympx5jnKDW8IgJTasC0FCJU5Q10MuXOXKfIGdSQIBHVvc5VPUw88yZkVSkSGKVwFnhwagL1OEggW35wzWARUEmMwxVuhz1tKzuPNtqxzAJNb_elaZAyJcEjR5HVaY

Once I remove the x from the end of **resource** i get the expected 302 and the application is signed in.

**Comment by Tratcher** [comment]
Enable the DeveloperExceptionPage to see the error.

This has improved in RC2.
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L404
Hook into the Options.Events.OnRemoteFailure event to handle it.
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/Events/RemoteAuthenticationEvents.cs#L11

**Comment by lranders** [comment]
Yes, I'm already using the DeveloperExceptionPage and it popped up when I had the MetadataAddress pointer spelled out with an **s** at the end. IDX10803/4.

That's why I noted the odd behavior with **resource** invalid; was expecting the same exception page, but got nothing. It wasn't until I was looking at the Network tab in Google Chrome (F12) that I noticed the status code 500 return from /signin-oidc.

Looking forward to RC2 .. :+1:

**Comment by muratg** [comment]
@brentschmaltz @tushargupta51 Could you guys take a look? (Please see the error above which seems to come from AAD)

cc @vibronet
