### ISSUE TITLE
Update CookieAuthenticationHandler.ApplyHeaders to honor AuthenticationProperties.RedirectUri

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#800]
Currently, this code doesn't work as `CookieAuthenticationHandler.ApplyHeaders` doesn't honor `AuthenticationProperties.RedirectUri` (instead, you get an empty result). It would be great to fix that in the next milestone.

```csharp
public IActionResult SignOut() {
    return SignOut(new AuthenticationProperties { RedirectUri = "/" },
        CookieAuthenticationDefaults.AuthenticationScheme);
}
```

**Comment by Tratcher** [comment]
Note that the use of RedirectUri varies. In cases like Challenge it is used as the final destination after authentication is complete. Using it directly for SignOut may be fine though.

**Comment by PinpointTownes** [comment]
Well, AFAICT, we've removed all the problematic uses of `RedirectUri` (e.g https://github.com/aspnet/Security/pull/275), which is now basically just a `ReturnUrl` and nothing more.

**Comment by muratg** [comment]
Let's investigate in 1.0.0.

**Comment by troydai** [comment]
Fixed in https://github.com/aspnet/Security/pull/940/commits/6a9f1f9887ec5983da5c20b4d8b788929d7b1b32
