### ISSUE TITLE
Responding with 401 redirects to login when *not* using cookie authentication

### ISSUE THREAD

**Issue by Jargon64** [aspnet/Security#804]
I have a project that uses Angular for the front-end and JWT authentication, and has no references to any kind of cookie authentication in `Startup.cs`. Yet when issuing a 401 it responds with a 302 and redirects the browser to `/Account/Login`.

My searches have yielded this issue https://github.com/aspnet/Security/issues/687 which states you cannot null the redirect because that's how cookie authentication is supposed to work, but as mentioned, I'm not using cookie authentication.

I'm really stumped and I can only think that cookie authentication is used by default (which I haven't seen written down anywhere) or it's a bug. Any ideas?

**Comment by Tratcher** [comment]
Are you using Identity or any other auth components?

**Comment by Jargon64** [comment]
@Tratcher I am, I map the JWT token to an Identity so I can use it throughout the rest of the app. Is there something I need to disable in its options?

**Comment by Tratcher** [comment]
Identity is cookies based, it does not integrate with JWT. Correct @HaoK?

**Comment by Jargon64** [comment]
@Tratcher Are you sure? I have a JWT bearer token resolving to an Identity and can be successfully tested with Postman without using any cookies.

**Comment by Tratcher** [comment]
I think we're confusing each other. By Identity I mean the Identity management framework https://github.com/aspnet/identity, not just a ClaimsIdentity.

**Comment by Jargon64** [comment]
Fair enough, but the project does use the Identity framework to deal with user registration and authentication before a JWT token is generated. Is this where the problem lies?

**Comment by Tratcher** [comment]
Ah, that's what I thought. Yes, Identity uses multiple cookie middleware internally. Your best option is not to return 403s directly, but to use HttpContext.Authentication.Forbid("Bearer") or Challenge("Bearer");

**Comment by Jargon64** [comment]
Thanks for the input, I'll have to work out how to go down this route cause the problematic endpoint itself is using a custom policy, which I have been unable to get working for other reasons (might be creating a separate issue for it soon). Returning the 401/403 manually was actually a workaround that is also proving problematic.

Anyway, just trying to understand the whole situation with the Identity framework. Is this actually an issue? The login redirect when using Identity (and, as such, indirectly cookies)? The argument for keeping the enforced login redirect with cookie authentication was "If you don't want it, don't use cookies", but surely people want to create an cookie-less API that uses the Identity framework and the redirect kind of breaks everything. Or is using the Identity framework for a web API not a good idea in the first place?

**Comment by Tratcher** [comment]
@haok?

**Comment by HaoK** [comment]
Identity basically has two pieces, `AddIdentity` adds the `UserManager` and the assorted other APIs needed to use the framework to your service collection.  `UseIdentity` is really only adding cookie middleware (which `SignInManager` implicitly works against).  So if you want to use the identity APIs but not cookies, then just remove the `UseIdentity` in your startup, and do not use SignInManager, you will have to manage the authentication yourself.

**Comment by HaoK** [comment]
@divega @blowdart Maybe we should rename `UseIdentity` => `UseIdentityCookies` to clarify what its actually doing.

**Comment by blowdart** [comment]
Works for me

**Comment by HaoK** [comment]
Or we could call it `UseSignInCookies`, since its really SignInManager that depends on the cookies

**Comment by divega** [comment]
Seems a good idea to change the name to make things clearer but we are running out if time for breaking changes. Is "use cookie authentication with Identity" a good way to convey what it means?

**Comment by HaoK** [comment]
Actually now that I think about it, I think we discussed something more specific in the past but decided UseIdentity was better since we could potentially add more than just cookies in the future, so this is better future proofing.

**Comment by divega** [comment]
If we decided to add "more than just cookies" in the future,  what is the likehood that we would need a separate method to add an alternative to cookies?

**Comment by HaoK** [comment]
I don't mean as an alternative to cookies, I mean UseIdentity could add some other middleware that is needed for new features

**Comment by brockallen** [comment]
@HaoK this thread: https://github.com/aspnet/Identity/issues/621

**Comment by ikourfaln** [comment]
Hi,
I found an article that resolve this problem by adding a nice trick 😉 
https://devblog.dymel.pl/2016/07/07/return-401-unauthorized-from-asp-net-core-api

**Comment by Darkseal** [comment]
It seems like I managed to fix it without having to use the "events" workaround in the following way:

    services.AddIdentity<ApplicationUser, IdentityRole>(config =>   {
        // ...
        config.Cookies.ApplicationCookie.AutomaticChallenge = false;
        // ...
    });

Let me know if it works for you guys too.

**Comment by jwhijazi** [comment]
Yeah... your solution for setting the AutomaticChagglenge to false worked for me.

**Comment by LimeyTX** [comment]
Setting AutomaticChallenge to false worked for me but it also inhibited the ability to login.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
