### ISSUE TITLE
How to access Http Request on Custom Authorization Policy Handle Event?

### ISSUE THREAD

**Issue by frapid** [aspnet/Security#805]
```
public class CustomAuthorizationPolicy : AuthorizationHandler<CustomAuthorizationPolicy>, IAuthorizationRequirement
{
        protected override void Handle(AuthorizationContext context, RestAuthorizeAttribute requirement)
        {
        }
}
```
I use a custom bearer based token authentication. The following requirements should be met to get authorized:

- The token was not revoked
- The user agent should match with what's stored

Now I wonder, how could I access the request headers here?

**Comment by muratg** [comment]
This is documented [here](https://docs.asp.net/en/latest/security/authorization/policies.html#accessing-request-context-in-handlers). Please have a look and let us know if it doesn't work for you.
