### ISSUE TITLE
Clash of AuthorizationContext naming with aspnetcirelease bits rc2-*

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Security#806]
Looks like someone did a rename recently causing my code to not compile
I know I can add a namespace but ...
```
C:\Users\mikes\Repos\Reports\src\Reports\Authorization\AccountNosAuthorizationHa
ndler.cs(21,40): error CS0104: 'AuthorizationContext' is an ambiguous reference
between 'Microsoft.AspNetCore.Authorization.AuthorizationContext' and 'System.Se
curity.Claims.AuthorizationContext'
```

Or is it a move?

**Comment by Eilon** [comment]
@Tratcher @HaoK didn't we talk about moving this or renaming it a long time ago? I can't seem to find a bug on it though.

**Comment by Tratcher** [comment]
I thought that was AuthenticationResult.

**Comment by Eilon** [comment]
Oh maybe.

**Comment by HaoK** [comment]
We might be able to hide AuthenticationContext once the public AuthenticateAsync that used to take it is goes away.

**Comment by Eilon** [comment]
Let's rename `Microsoft.AspNetCore.Authorization.AuthorizationContext'` to `Microsoft.AspNetCore.Authorization.AuthorizationHandlerContext`.

**Comment by BrennanConroy** [comment]
1a99fad0c69c75f81fc5f74d9044842ae3484e9b
