### ISSUE TITLE
Update OIDC package version to be 1.0.0-rc2

### ISSUE THREAD

**Issue by danroth27** [aspnet/Security#808]
Currently the OIDC package is 0.1.0. We should update it's version to align with the rest of the packages we plan to ship with RTW.

**Comment by Tratcher** [comment]
Has something changed? Last we discussed this it was going to stay 0.1 for RC2 and only be upgraded when it meets its RTM criteria.

**Comment by blowdart** [comment]
What @Tratcher said. The discussions ended up with OIDC reaching RTM after Core.

**Comment by Tratcher** [comment]
There's a chance it can make it at the same time as core, but it has some quality bars it needs to reach first.

**Comment by Eilon** [comment]
From an email with @vibronet, let's change this to 1.0.0-rc2.
