### ISSUE TITLE
why is CookieAuthenticationOptions in the namespace Microsoft.AspNetCore.Builder?

### ISSUE THREAD

**Issue by joeaudette** [aspnet/Security#809]
Forgive me if this is a silly question, maybe there are good reasons, but when reading the code for [CookieAuthenticationOptions](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs) I noticed it is in the namespace "Microsoft.AspNetCore.Builder"

To me that seems weird, I would expect it to be in the same namspace as the middleware that uses it, namely "Microsoft.AspNetCore.Authentication.Cookies"

Maybe there are good reasons but thought I would point it out in case it is unintended.

**Comment by PinpointTownes** [comment]
That's the direct consequence of abandoning the "delegate-style extensions": `CookieAuthenticationOptions` must be in a common namespace  (else, people would have to add a `using` to be able to configure the authentication options):

```
app.UseCookieAuthentication(new CookieAuthenticationOptions {
    ...
});
```

You can read [this thread](https://github.com/aspnet/Options/issues/105) for more information.

**Comment by joeaudette** [comment]
Thanks! Very enlightening!

**Comment by brockallen** [comment]
The short summary is that programming is hard (especially finding namespaces) :)

**Comment by PinpointTownes** [comment]
> The short summary is that programming is hard (especially finding namespaces) :)

Yep, that was a pretty good reason to keep the "delegate-style extensions" (and there were a few other ones: https://github.com/aspnet/Options/issues/105#issuecomment-168866368).

FWIW, I've decided to keep the overloads accepting an `Action<TOptions>` in all the _aspnet-contrib_ projects, including the OAuth2/OpenID2 social providers. They offer a so much nicer experience, IMHO.
