### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by chemitaxis** [aspnet/Security#810]
Hi, I'm using ASP.NET Core, RC1 Update 1, when use facebook login, I never obain the email, but all is fine. Any ideas? Thanks.

// REVIEW: handle case where email not in claims?
var email = loginInfo.ExternalPrincipal.FindFirstValue(ClaimTypes.Email);

**Comment by smbecker** [comment]
Is this what your looking for?

https://github.com/aspnet/Security/issues/783

**Comment by chemitaxis** [comment]
Yes, thanks ;)
