### ISSUE TITLE
Log failed authentication

### ISSUE THREAD

**Issue by anurse** [aspnet/Security#812]
Should failed authentication be logged at some level? Even on LogLevel.Debug, I don't see any logging. When I messed with the token to see if it would cause authentication to fail, it did (good) but it didn't log anything about the malformed token (bad, maybe?).

/cc @HaoK @blowdart @Tratcher

**Comment by muratg** [comment]
@anurse How did you cause the failure? What was the token type you messed with?

**Comment by Tratcher** [comment]
Offline notes: he manually edited the cookie and then it failed to decrypt.
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/DataHandler/SecureDataFormat.cs#L55
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/DataHandler/SecureDataFormat.cs#L67
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/DataHandler/SecureDataFormat.cs#L74

**Comment by troydai** [comment]
Run the same scenario just now, following output is among the logs. Chat with @anurse, we both agree the output is sufficient enough. 

```
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware[7]
      Cookies was not authenticated. Failure message: Unprotect ticket failed
```

Close as won't fix.
