### ISSUE TITLE
SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed.

### ISSUE THREAD

**Issue by LeandroPT** [aspnet/Security#813]
Hey,

Since yesterday i am getting an error logging in with the following:

`SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: EEAQF9KmrMLBL5bA26otNEfOY1k`

The actual problem is:
```
Exceptions caught:
'System.TypeLoadException: Could not load type 'System.Security.Cryptography.ECDsa' from assembly 'System.Security.Cryptography.Algorithms, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRemoteCallbackAsync>d__5.MoveNext()
```

Apparently there is a problem with references in the nuget package.

forcing in dependencies:
`"System.Security.Cryptography.Algorithms": "4.1.0-*"`

The apllication works, hover the following downgrade warning appear:

`NETStandard.Library (>= 1.5.0) -> System.Security.Cryptography.Algorithms (>= 4.2.0-rc3-24106-00)`

**Comment by Tratcher** [comment]
Looks like you've jumped to the post RC2 packages. Does it work if you go back to the RC2 packages via the Release feed? You may have to specify `-rc2-*` in your dependencies.
https://github.com/aspnet/Home/wiki/NuGet-feeds
