### ISSUE TITLE
UseJwtBearerAuthentication causes CORS 500 Error

### ISSUE THREAD

**Issue by StephenGilboy** [aspnet/Security#815]
I have an ASP.NET CORE WebAPI App that is using the JwtBearerAuthentication with Azure AD to authorize a client on a separate web host using AngularJS and the Adal library.

I've included the necessary files in a Gist
https://gist.github.com/StephenGilboy/456668f4f7f8298e801118b1a96c76bb

If you remove the `[Authorize]` attribute from the `Get()` method the client works fine, no CORS errors. If you add the `[Authorize]` attribute back you'll see an error message like: 

`:44377/api/v1/values:1 GET https://localhost:44377/api/v1/values`

`:44376/#:1 XMLHttpRequest cannot load https://localhost:44377/api/v1/values. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost:44376' is therefore not allowed access. The response had HTTP status code 500.`

This stackoverflow question mentions the same issue. http://stackoverflow.com/questions/35004673/asp-net-core-jwt-and-cors-headers

**Comment by Tratcher** [comment]
This looks similar to https://github.com/aspnet/Diagnostics/issues/247.

The 500 response implies that an exception is being thrown somewhere, probably in JwtBearerAuthentication. When the server or exception page catch the exception they clear the current headers (including the CORS headers).  Enable logging to track down what the exception is and deal with that first.

**Comment by StephenGilboy** [comment]
I've found that when I take the Bearer token out of my Angular call and put it into Postman I was having an issue w/ a bad Audience variable. When I fixed that I'm now getting a 502. 

`HTTP Error 502.3 - Bad Gateway
The specified CGI application encountered an error and the server terminated the process.`

**Comment by StephenGilboy** [comment]
And that error was caused by me trying to get the User from the HttpContext in the ValuesController. Everything is working now. Thanks!
