### ISSUE TITLE
Google OAuth package not compatible with 3rd party libraries

### ISSUE THREAD

**Issue by zabulus** [aspnet/Security#821]
Not sure about where the issue should be placed. So feel free to point me to another place.

I've developed single-page application using AngularJS. I've included satillizer to use as client-side login provider. Also I've added Microsoft.AspNet.Authentication.Google to web application. I've specified Microsoft.AspNet.Authentication.Google callback path in satellizer.

Errors occur on calling callback. Error in logs: "The oauth state was missing or invalid.". "state" is referring to AuthenticationProperties object, that sends from the app to auth endpoint and back.

As I understand Microsoft.AspNet.Authentication.Google is integrated only with AspNet.Authentication stuff and can't be used in other scenarios, except specified.

**Comment by Tratcher** [comment]
Those packages are built for an interactive flow. For SPA apps you should be using something like Bearer to authenticate with the server after doing a client side login.
