### ISSUE TITLE
Action<MicrosoftAccountOptions> was removed in AspNetCore

### ISSUE THREAD

**Issue by jbeen19** [aspnet/Security#825]
When you compare the Microsoft.AspNet.Builder.MicrosoftAccountAppBuilderExtensions to the Microsoft.AspNetCore.Builder.MicrosoftAccountAppBuilderExtensions you will discover the option of Action<MicrosoftAccountOptions> was removed. I kinda liked it once I understood how the data typed worked can you please add that back in. I thought it was one of those things I thought were really cool as I was learning how to build an MVC website.
![microsoftaccountoptions](https://cloud.githubusercontent.com/assets/9244161/15392938/4a53287e-1d98-11e6-98da-3780af5eb7f6.png)

**Comment by jbeen19** [comment]
To be honet, I wouldn't call this an issue, but I wasn't sure where I should leave a comment. It's my first post.

**Comment by Eilon** [comment]
Yeah this was a deliberate change to simplify some of the configuration logic.

**Comment by PinpointTownes** [comment]
> Yeah this was a deliberate change to simplify some of the configuration logic.

I'm not sure to understand how this can simplify the configuration logic as it works exactly the same way as the other overload.

This syntax had many advantages: https://github.com/aspnet/Options/issues/105#issuecomment-168866368. That would be great to reopen this ticket to have a real discussion.

**Comment by PinpointTownes** [comment]
For a real like example of why reintroducing this syntax would be ideal: https://github.com/aspnet/Security/issues/614#issuecomment-171820979

**Comment by Eilon** [comment]
@PinpointTownes interesting - I'm re-opening, but putting in the post-v1.0.0 milestone because either way we won't have time to get to this for this release. But certainly something we can reconsider (it's just a matter of adding overloads - no breaking change).

**Comment by PinpointTownes** [comment]
@Eilon if time is the only blocking factor for this work item, you can count on me to submit as many PRs as needed to bring back the "delegate-style" overloads, as the change itself is really trivial:

```csharp
public static IApplicationBuilder UseMicrosoftAccountAuthentication(
    this IApplicationBuilder app, Action<MicrosoftAccountOptions> configuration)
{
    if (app == null)
    {
        throw new ArgumentNullException(nameof(app));
    }
    if (configuration == null)
    {
        throw new ArgumentNullException(nameof(configuration));
    }

    var options = new MicrosoftAccountOptions();
    configuration(options);

    return app.UseMiddleware<MicrosoftAccountMiddleware>(Options.Create(options));
}
```

**Comment by HaoK** [comment]
Well I believe the motivating factor for removing these was the confusion around what happens when you configure options in `ConfigureServices` and use the delegate overload, there's confusion because the settings in `ConfigureServices` won't be picked up this way.  So although the change is trivial, it has a fair bit of repercussions...

**Comment by PinpointTownes** [comment]
Prior to the big options change, it used to work like that: you could configure the options from `ConfigureOptions`, and it had no impact on the options configured via  `UseTrucBiduleMiddleware(options => { })`).

AFAIK, nobody has ever complained about a possible risk of "confusion".

TBH, I'm not sure this very hypothetical risk is serious enough to justify removing this syntax, that helps solve many concrete use cases, like clearing a collection property or updating some properties in `OpenIdConnectOptions.TokenValidationParameters`.

**Comment by HaoK** [comment]
Well the full explanation is that options configured via configure services before were always ignored. The intent behind the change was to enable this scenario for the UseXyz() overload. And instance overloads are not ambiguous with that.  But the main motivation was to enable configuring options via ConfigureServices. So adding this overload back would introduce confusion that didn't exist before. 

Cc @divega for FYI.

**Comment by jbeen19** [comment]
I will confess that it did confuse the heck out of me when I was first learning ASP.NET three months ago; however, I saw the lambda expression an eventually figured it out what was going on and have been adding it to my own applications because of it.  

Personally, I think it looks more professional and plus it removed a using statement or having the entire namespace typed out in ASP.NET. (Obviously, the namespace is set differently in ASP.NET Core.) It is intellisense friendlier once you are past the lambda expression, which to me is far more useful.

Finally, I am sure if Bob Tabor added a lesson on lambda expression it would clear the "confusion" for beginners.

![microsoftaccountoptions2](https://cloud.githubusercontent.com/assets/9244161/15456312/3de91bda-203a-11e6-9f06-0112d07df19f.png)
