### ISSUE TITLE
Port OAuth Authorization Server from Katana

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Security#83]
I saw the discussion about this on #39. @Tratcher suggested to open up a new issue for this and here it is :smile: 

I personally want to see `OAuthAuthorizationServerMiddleware` ported here because of my selfish reasons :smile: as I used this inside a project which we consider porting over to vNext. I also see questions, feedback, etc. for `OAuthAuthorizationServerMiddleware` which indicates that it's being used.

However, I agree with @leastprivilege [here](https://github.com/aspnet/Security/issues/39#issuecomment-55697311). It should live inside its own world.

**Comment by cleftheris** [comment]
@Tratcher  IMHO IdentityServer v3 is fills all the nedded scenarios plus more. You can opt out of an advanced configuration if one is not deeded. BUT there is no indication that the project has event started to port to a aspnet core compatible version. That said we need something to work with until this happens.

**Comment by PinpointTownes** [comment]
@cleftheris you should give AspNet.Security.OpenIdConnect.Server (https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server) a try, it now fully supports __dnxcore50__ :smile:

**Comment by cleftheris** [comment]
@PinpointTownes I am already on this track. Having a bit of a trouble managing all the dependency chaos of beta5* (Abstractions/interfaces stuff) plus the shortcomings of the EF7 current status. But will eventually make it work.

**Comment by leastprivilege** [comment]
No we haven't started porting to CoreClr - don't see the need for that right now. It runs fine in ASP.NET 5 DNX451 and Mono.

On related news - IdentityServer3 is as of today a fully certified OpenID Connect implementation. So it depends on where your priorities are.

http://openid.net/certification/

**Comment by alikor** [comment]
DNX451 will not work on the Microsoft Nano Server or within a docker
container or even run on a mac/linux box so i can see a very strong reason
to port the application

**Comment by leastprivilege** [comment]
It runs fine on Mac/Linux using Mono.

But yeah - we will port at some point. That's not the question.

**Comment by eqbalsajadi** [comment]
Hi guys,

How to login to ASP.NET 5 Web Api by WebClient class in a .NetFramework 2 Windows Forms?
I have already done that for ASP.NET 4.5 using this article http://www.asp.net/web-api/overview/security/individual-accounts-in-web-api
But don't know how to do it for ASP.NET 5. It seems Authorization Server is not supported by it.
Is there any alternative? In a nut shell, what is your solution to secure an ASP.NET 5 Web Api that is used by third party clients such as mobile or windows application?

Please help

**Comment by Xacron** [comment]
For anyone still looking for the original OAuth Authorization Server in ASP.NET 5, I have ported the code and the original sample here:
https://github.com/XacronDevelopment/oauth-aspnet

The port includes backwards compatibility to allow ASP.NET 4.x resource servers to read the access tokens created by the authorization server.

The nuget packages are here:
https://www.nuget.org/packages/OAuth.AspNet.AuthServer
https://www.nuget.org/packages/OAuth.AspNet.Tokens
https://www.nuget.org/packages/OAuth.Owin.Tokens

**Comment by eqbalsajadi** [comment]
Thank you.

**Comment by Xacron** [comment]
I'm updating the source and packages now to remove explicit references to Microsoft.Framework.NotNullAttribute.Sources(Internal)

**Comment by leastprivilege** [comment]
Since this issue gets referenced every time somebody asks about token issuance in ASP.NET 5 - here's a small walkthrough how to do it with identityserver:

http://leastprivilege.com/2015/07/22/the-state-of-security-in-asp-net-5-and-mvc-6-oauth-2-0-openid-connect-and-identityserver/

**Comment by Eilon** [comment]
Closing because there are no plans to do this specific feature.

**Comment by PinpointTownes** [comment]
@Eilon it's worth noting that community projects are now listed here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/community (people looking for the same low level experience as with the OAuth2 authorization server middleware shipped with Katana should probably try ASOS).

**Comment by Eilon** [comment]
Ah, of course! I added a link to that doc from the readme as well: https://github.com/aspnet/Security/blob/dev/README.md
