### ISSUE TITLE
Making AuthorizeAttribute sealed

### ISSUE THREAD

**Issue by raffaeler** [aspnet/Security#834]
Is there a specific reason for AuthorizeAttribute not to be sealed?
As far as I can understand, the infrastructure will not care about any derived members.

**Comment by davidfowl** [comment]
Why seal it?

**Comment by raffaeler** [comment]
In the past people used to derive it to control authorization while now any derived member is ignored.
When you migrate the code, getting a compile error from being sealed, would help in understanding what needs to be rewritten.

**Comment by Eilon** [comment]
Not planning on sealing it. It's fairly harmless to leave it as-is.
