### ISSUE TITLE
oidc redirect_uri is http

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/Security#835]
Just updated to rc2 and found my authentication with OpenIdConnect is generating a non-secured reply address.

Authentication is coming from originating https request from https://mysite.azurewebsites.net and getting redirected to login.microsoftonline.com with parameters in the url of redirect_uri=http%3A%2F%2Fmysite.azurewebsites.net

Following this, I receive the Azure AD failure for "The reply address does not match the reply addresses configured for the application". This is due to the fact I only have https addresses configured for reply.

Why is the redirect_uri getting generated as http even though the request is originating from a secure url?

My setup in Startup.cs with `azureAd` being an options object with my configuration loaded into is:
```csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
{
    AutomaticAuthenticate = true,
    AutomaticChallenge = true,
    ClientId = azureAd.ClientId,
    Authority = azureAd.AADInstance + azureAd.Tenant,
    SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme
});
```

**Comment by Tratcher** [comment]
It's a known issue in Azure. Use this workaround: https://github.com/aspnet/IISIntegration/issues/140#issuecomment-215135928

**Comment by damienpontifex** [comment]
Thanks. The workaround fixed the issue. I will follow the other issue for resolution so feel free to close this @Tratcher if duplicate and no need to track.
