### ISSUE TITLE
Authorization failed for the request at filter 'Microsoft.AspNet.Mvc.Filters.AuthorizeFilter'.

### ISSUE THREAD

**Issue by lszomoru** [aspnet/Security#836]
I've got a site that is using RC1 and [role based authorization](https://docs.asp.net/en/latest/security/authorization/roles.html). Some users reported that they were unable to access pages even though they were part of the roles that had access to them. Looking through the event log I have noticed warnings with the following text:

> Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker
Authorization failed for the request at filter 'Microsoft.AspNet.Mvc.Filters.AuthorizeFilter'.

Through some testing I was able to track down the issue to the fact that when you specify multiple roles you need to make sure not to have any spaces in between the roles names otherwise you would hit this issue.
 
Instance of 
`[Authorize(Roles = "Administrator, PowerUser")]` 
you need to use
`[Authorize(Roles = "Administrator,PowerUser")]`

If this behavior is by design, I suggest fixing the [documentation] (https://docs.asp.net/en/latest/security/authorization/roles.html). Thanks!

**Comment by imranbaloch** [comment]
For me space should work. See https://github.com/aspnet/Security/blob/1.0.0-rc2/src/Microsoft.AspNetCore.Authorization/AuthorizationPolicy.cs#L91-L93 There might be some special character.

**Comment by PinpointTownes** [comment]
>I've got a site that is using RC1

This bug was fixed in RC2: https://github.com/aspnet/Security/issues/627

**Comment by lszomoru** [comment]
Thank you both! I will close the issue.
