### ISSUE TITLE
Null reference exception thrown when null is returned from HandleAuthenticateAsync()

### ISSUE THREAD

**Issue by blowdart** [aspnet/Security#837]
This used to work in RC

            if (string.IsNullOrEmpty(header) || !header.StartsWith("Bearer "))
            {
                return null;
            }

It causes a null reference exception in RC2. The correct code would return `Task.FromResult(AuthenticateResult.Skip());` but the exception is horrid.

**Comment by PinpointTownes** [comment]
I reported a similar bug (https://github.com/aspnet/Security/issues/760) and AFAIK, it's fixed in RC2.

Are you sure you're not returning a null `Task`?

**Comment by HaoK** [comment]
He is.

**Comment by PinpointTownes** [comment]
Then it's not a bug.

@blowdart there's a huge difference between returning a null `Task` and a `Task` that returns a null result (e.g via `Task.FromResult<AuthenticateResult>(null)`): trying to await a null `Task` will always result in an NRE.

BTW, it's absolutely not specific to this method and impacts almost every async method in the .NET Framework or in ASP.NET Core.

**Comment by blowdart** [comment]
I was just returning null, not even a task :) Meh, fair enough, my misunderstanding :D

**Comment by PinpointTownes** [comment]
> Meh, fair enough, my misunderstanding :D

Noob noob noob :trollface:

**Comment by anurse** [comment]
Just clarifying that this wasn't actually changed and tagging as 'wontfix' to ensure we're covering things right for RTM
