### ISSUE TITLE
Question: Custom authentication/authorization. What interfaces need to be overrided to make default [Authorize] attribute works?

### ISSUE THREAD

**Issue by ivankarpey** [aspnet/Security#838]
I'm using Mongodb as my primary data store and  need to implement my custom auth logic, since EF don't support mongodb atm. And my data-model is denormalized - I store roles assigned to user in the same document as other user information. Like
```

class User{
      string Token;
      IList<string> Roles;
      ....
}
```

And I sending user token via each request - this is how we protect out api currently.

What code I need to add and what interfaces implement to still be able using
`[Authorize]` and `[Authorize(Roles="Role1, Role2, Role3")]` attributes and being able to access Controller.User as well.

Thanks.

**Comment by ivankarpey** [comment]
Looks like to be able to implement custom authentication there should be abstract classes implemented. AuthenticationMiddleware<T>, AuthenticationHandler<T> and AuthenticationOptions and than custom middle ware should be added in startup class.

**Comment by Eilon** [comment]
Yes. Have a piece of 🍰.  😄
