### ISSUE TITLE
Settable Scope in OpenIdConnectOptions

### ISSUE THREAD

**Issue by rmja** [aspnet/Security#839]
A minor thing. It would be nice if, instead of this:

```
var options = new OpenIdConnectOptions(OpenIdConnectAuthenticationScheme)
            {
                SignInScheme = CookieAuthenticationScheme,
                Authority = authUrls.Authority,
                ClientId = "theclient",
                ResponseType = "id_token"
            };
            options.Scope.Clear();
            options.Scope.Add("openid");
            options.Scope.Add("profile");
            options.Scope.Add("roles");

            app.UseOpenIdConnectAuthentication(options);
```

one could write

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions(OpenIdConnectAuthenticationScheme)
            {
                SignInScheme = CookieAuthenticationScheme,
                Authority = authUrls.Authority,
                ClientId = "theclient",
                ResponseType = "id_token"
                Scope = new HashSet<string>() { "openid", "profile", "roles" }
            });
```

Basically, [this setter](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L156) should be assignable.

**Comment by brockallen** [comment]
Yea, I still feel the collection is icky (https://github.com/aspnet/Security/issues/614). This setter might be a nice compromise.

**Comment by PinpointTownes** [comment]
FWIW, publicly-settable collection properties are usually discouraged: https://msdn.microsoft.com/en-us/library/ms182327.aspx.

Why not using this syntax to add new items to the scope collection?

```csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions {
    SignInScheme = CookieAuthenticationScheme,
    Authority = authUrls.Authority,
    ClientId = "theclient",
    ResponseType = "id_token",
    Scope = { "roles" }
});
```

**Comment by brockallen** [comment]
> Why not using this syntax to add new items to the scope collection?

Also looks fine to me.

**Comment by rmja** [comment]
That doesn't replace the default scopes which is what I want:

![image](https://cloud.githubusercontent.com/assets/2112306/15504964/ae3615a4-21c1-11e6-8eac-ab4b46b95f55.png)

**Comment by rmja** [comment]
I guess that removing `profile` from the default scopes would solve that problem...

**Comment by PinpointTownes** [comment]
Sure, that's why I said "add new items" and not "clear" nor "remove" :smile: 

We're already discussing this point there: https://github.com/aspnet/Security/issues/614.

**Comment by leastprivilege** [comment]
The scope collection should contain openid only. Not profile.

**Comment by PinpointTownes** [comment]
> The scope collection should contain openid only. Not profile.

Agreed. And it would be consistent with the fact the userinfo request is not enabled by default.

**Comment by PinpointTownes** [comment]
Actually, the more I think about it, the more I realize that having `profile` set by default is probably a good compromise. Without this scope, the OP won't return the user name and `User.Identity.Name` will never be populated. It would be really disappointing for most people.

**Comment by leastprivilege** [comment]
IIdentity.Name only exists for backwards compatibility reasons. openid is the only required scope in OIDC. Adding to the collection has a nice C# syntax. Removing/clearing does not.

And since somebody decided that a collection is much more usable than a string - well - that should go into consideration.

**Comment by PinpointTownes** [comment]
> IIdentity.Name only exists for backwards compatibility reasons.

It doesn't change anything to the fact...
  1. It's still massively used.
  2. People will often need a user name in practice.

**Comment by PinpointTownes** [comment]
If we can't bring back the good old delegate-style extensions, making the `Scope` property settable as suggested by the OP seems to be a good compromise, even if it's not recommended.

**Comment by Eilon** [comment]
Though we are aware of some issues in the current design, we feel that is strikes a balance compared to other alternatives. It's generally a bad practice to have settable collection types, we want a default set of scopes, etc.

**Comment by PinpointTownes** [comment]
> It's generally a bad practice to have settable collection types

It's probably the best compromise if you don't reintroduce the `app.UseOpenIdConnectAuthentication(options => { ... })` overloads, tho.

**Comment by brockallen** [comment]
Tant pis, I guess :/

**Comment by qvsmith** [comment]
From a consumer's point of view I really hope this changes in the future...

A settable scope is nice but, if ICollection had AddRange or some fluent Add method that would have been an improvement over what exists right now imho.

**Comment by nikoudel** [comment]
Just has to struggle with this for hours - I don't want the profile scope because the only thing I'm interested in is user id. Scanned through all the documentation trying to find any clues about what's going on and why am I getting the "invalid scope: profile" message (didn't find any). It was a good exercise though, now I understand a bit better how the whole system works :))

**Comment by michael-freidgeim-webjet** [comment]
@qvsmith 
I've created a simple extension and can use it to pass an array/list of scopes:
` options.Scope.AddRange(new[] { "openid", "profile", "offline_access", "MyApi"});`


 ```
      public static ICollection<T> AddRange<T>(this ICollection<T> collection, ICollection<T> itemsToAdd)
        {
            foreach (var item in itemsToAdd)
            {
                if (!collection.Contains(item))
                {
                    collection.Add(item);
                }
            }
            return collection;
        }

```
