### ISSUE TITLE
Authorize policy attribute not compatible with dynamic policy provider

### ISSUE THREAD

**Issue by jburbach** [aspnet/Security#841]
I was attempting to implement something like the DynamicPolicyProvider in your unit tests where the idea is that you can specify the policy name at runtime and built it on the fly. While this passes your unit tests, if you try to actually declare something like [Authorize("MyPolicy")] on an action/controller you get an exception that states 

InvalidOperationException: The AuthorizationPolicy named: 'MyPolicy' was not found.

Is this by design, and if so, what am I missing? I assume this happens because the policy isn't declared at runtime, but how is that compatible with the idea of building it at runtime?

**Comment by Eilon** [comment]
@HaoK can you show how to wire this up?

Then give to @blowdart to document this more completely.

**Comment by HaoK** [comment]
Issues is that we aren't using the IPolicyProvider in AuthorizePolicy.Combine, which MVC AuthorizeFilter is using to combine policies

**Comment by smbecker** [comment]
Will this make it in RTM?

**Comment by HaoK** [comment]
Yeah it should make it.

**Comment by smbecker** [comment]
Awesome because this will make my life a lot easier
