### ISSUE TITLE
Please provide a way to re-authenticate in the same request (clear AuthenticationHandler<TOptions>._authenticateTask)

### ISSUE THREAD

**Issue by rwasef1830** [aspnet/Security#847]
Hello aspnet team,
Sometimes I store sensitive information in the user claims which needs to be recomputed when a user changes their password. This means that I need to call ```Context.Authentication.AuthenticateAsync``` to reissue the cookie (for example. in the case of CookieAuthenticationHandler) to do it transparently during the POST of the password change action.

However, because ```AuthenticationHandler<TOptions>.HandleAuthenticateOnceAsync()``` does a short-circuit check to check if a task is already present in ```_authenticateTask``` and simply returns, I cannot reissue the cookie. There is simply no code path that set ```_authenticateTask``` to null.

I'm forced to either: 
- Log the user out and ask them to re-login (to clear the cookie).
- Store this info outside claims somewhere else and have to duplicate encryption/security logic which is already nice and good in CookieAuthenticationHandler.

Is there any workaround I can use to force reissuance of the authentication ticket/cookie ? It is not easy to try to inherit from the authentication middleware because the offending logic is in the base AuthenticationHandler class and I'd have to duplicate the whole thing to implement it and reimplement all auth middleware to use my new base class.

**Comment by HaoK** [comment]
SignOut should clear the cookie, and you can call SignIn to issue a new cookie.  FYI Identity uses the OnValidateIdentity event on cookies to invalidate a cookie for a similar scenario, you should be able to do the same thing.

**Comment by brockallen** [comment]
Or they could just assign the User on the current HttpContext.

**Comment by HaoK** [comment]
Setting the user on the context doesn't affect anything past the current request, but that's certainly the easiest option if you just want to alter the claims for the current request.

**Comment by rwasef1830** [comment]
Thanks for the tip! I was able to get it to work by calling getting the claims on a variable, then calling ```SignOutAsync``` followed immediately by a ```SignInAsync``` passing in the claims.

One little ugliness was the need to call ```AuthenticateAsync``` to get at the ```AuthenticateContext``` from which I could reach the ```IsPersistent``` property (to maintain the cookie type).

Something must have changed here, I wasn't able to get it working in RC1 before.
Thanks again!

**Comment by brockallen** [comment]
Sure (as it has always been), but that's all they're asking for.

**Comment by rwasef1830** [comment]
No, I needed to alter the persisted claims in the cookie for all future requests, not just the current request, so just updating the claims in the context wasn't enough.

**Comment by rwasef1830** [comment]
Actually even calling SignOut wasn't needed.

**Comment by HaoK** [comment]
Nope, SignOut followed by SignIn on the same request is a no-op anyways,
since both modify the cookie and the last one will win.
