### ISSUE TITLE
AuthorizationHandler<TRequirement> design questions

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Security#849]
Link to the class: https://github.com/aspnet/Security/blob/2634fe318d8b81a3fc6e7e67a2dca980fb9bcc69/src/Microsoft.AspNetCore.Authorization/AuthorizationHandler.cs

#### Assert
This class contains 
- Handle(c)
- HandleAsync(c)
- Handle(c,r)
- HandleAsync(c,r)

It implements `IAuthorizationHandler` and hence its `HandlerAsync(context)` method is called for every requirement. 

The goal of this class is to let developers implement handlers that only get called for a specific requirement (of the generic type).

#### Arrange
1- Because of the goal of this class I think it should only expose `Handle(context, requirement)` and `HandleAsync(context, requirement)`. If a handler doesn't use the requirement, then it can implement the interface directly.
2- `Handle(context)` is currently dead code (not called, and can't be overrided)
3- `HandleAsync(context, req)` should not be `virtual`. IMO it just adds confusion as inheriting from the class show this member to be overridable, but this would break the inner logic of this class. Any reason to re-implement this method should actually be a custom implementation of the interface itself.
4- `Handle(context, req)` should not be `abstract`, as it makes it mandatory in any sub-class, even if we just want to implement `HandleAsync(context, req)`

#### Act
Here is my proposed implementation

```csharp
public abstract class AuthorizationHandler<TRequirement> : IAuthorizationHandler
        where TRequirement : IAuthorizationRequirement
{
    async Task IAuthorizationHandler.HandleAsync(AuthorizationHandlerContext context)
    {
        foreach (var req in context.Requirements.OfType<TRequirement>())
        {
            await HandleAsync(context, req);
        }
    }

    protected virtual void Handle(AuthorizationHandlerContext context, TRequirement requirement)
    {
        return;
    }

    protected virtual Task HandleAsync(AuthorizationHandlerContext context, TRequirement requirement)
    {
        Handle(context, requirement);
        return Task.FromResult(0);
    }
}
```

Any sub-class can then implement either `Handle(ctx, req)` or `HandleAsync(ctx, req)`.

The only drawback is that hiding `HandleAsync(ctx)` is a breaking change. But as mentioned, it would not make sense to override it as it the inner logic of the class, and all samples and the fact that `Handle(ctx, req)` is currently abstract already had you implement `Handle(ctx, req)` so the probability that anyone is doing that is low.

**Comment by divega** [comment]
Cc @haok @blowdart @muratg

**Comment by muratg** [comment]
cc @Eilon

**Comment by HaoK** [comment]
FYI this is a dupe of https://github.com/aspnet/Security/issues/739

That said, I think dropping the abstract and making it virtual is a decent compromise, I actually thought I already did that, but I had only mentally made that change instead of in reality.

I think that's a small change worth considering to make folks happy.

**Comment by blowdart** [comment]
Yup, should happen

**Comment by muratg** [comment]
@HaoK Do you have time to do this for RTM?

**Comment by sebastienros** [comment]
I created a PR if it can help you. It didn't do any breaking change in the current tests.

**Comment by HaoK** [comment]
Yeah I can take a look today

**Comment by HaoK** [comment]
35d0592701c4aa2edb6da919b629f87b8701807a
