### ISSUE TITLE
Cookie ExpireTimeSpan not honoured using Auzure AD OpenIDConnect authentication

### ISSUE THREAD

**Issue by jimmyrecardo** [aspnet/Security#855]
I am currently struggling with setting the timeout on the cookie/auth token when authenticating my .NET Core App using Azure AD via the OpenIdConnect authentication model.

The sign-in scheme is being set in the ConfigureServices method via the following:

    services.AddAuthentication(options => options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme);

I am then setting up my configuration as follows:

    app.UseCookieAuthentication(new CookieAuthenticationOptions()
    {
        CookieName = "MyCookie",
        ExpireTimeSpan = TimeSpan.FromHours(2)
    });

    app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions()
    {
        Authority = authorityUri.AbsoluteUri,
        ClientId = azureOptions.ClientId,
        ClientSecret = azureOptions.ClientSecret,
        ResponseType = OpenIdConnectResponseTypes.CodeIdToken,
        Events = new OpenIdConnectEvents()
        {
            OnAuthorizationCodeReceived = async context =>
            {
                await aAuthenticateMiddleware.OnAuthenticate(context, logger);
            }
        }
    });

    app.UseMiddleware<aAuthenticateMiddleware>();

Note, that I am not using the built in Identity (as its not practical for our purposes) but rather using a custom middleware.

Within the middleware layer I am checking whether the user is authenticated and if not a challenge is issued:

    var authenticationProperties = new AuthenticationProperties() { RedirectUri = context.Request.Path.Value ?? "/" };
    authenticationProperties.AllowRefresh = false;
    authenticationProperties.IssuedUtc = DateTime.Now;
    authenticationProperties.ExpiresUtc = DateTime.Now.AddHours(2);
    await context.Authentication.ChallengeAsync(
        authenticationManager.IdentityProvider.AuthenticationScheme,
        authenticationProperties,
        ChallengeBehavior.Automatic
    );

This is all works fine and authenticates the user correctly etc however this is issuing the auth token (and cookie) with a 15 minute expiry and ignoring my 2 hour expiry that I have tried setting.

I have been referring to the latest source examples from GitHub from the aspnet/security repository for examples.... however none of these mention anything about overriding the default expiry issued.

https://github.com/aspnet/Security/tree/dev/samples/OpenIdConnect.AzureAdSample

Most examples I have found are still referencing the old AspNet libraries rather than the AspNetCore libraries.

Some articles suggest that using the SignInAsync with persistent set to True allows the ExpireTimeSpan to be honored, however this throws a "Not Supported Exception" when calling it. Perhaps SignInAsync is not supported via Azure AD?

Not sure whether this is a bug???

**Comment by Tratcher** [comment]
AllowRefresh , IssuedUtc and ExpiresUtc do not apply for ChallengeAsync, only SignInAsync. OIDC does not directly support SignInAsync. You can hook into the OIDC Events and override where it calls SignInAsync.

Not sure why your CookieAuthenticationOptions.ExpireTimeSpan isn't working.

**Comment by dolly22** [comment]
Having the same issue. Effectively RemoteAuthenticationOptions.RemoteAuthenticationTimeout is used for cookie ticket lifetime.

@Tratcher This is probably a bug. AuthenticationProperties from short lived remote authentication ticket [RemoteAuthenticationHandler.cs#L57-L78](https://github.com/aspnet/Security/blob/1.0.0/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs#L57-L78) is used for signin request and later in [CookieAuthenticationHandler.cs#L223-L236](https://github.com/aspnet/Security/blob/1.0.0/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L223-L236) override values from options.

@jimmyrecardo You can workaround this in IRemoteAuthenticationEvents.OnTicketReceived callback, this works for me...

```csharp
var oidcOptions = new OpenIdConnectOptions
{
    ...
    Events = new OpenIdConnectEvents
    {
        OnTicketReceived = async ctx => {
            // reset ticket authentication properties
            ctx.Properties = new AuthenticationProperties();
        }
    }
};
```

**Comment by tuespetre** [comment]
:+1: on what @dolly22 said. Unfortunately the app of ours that best exhibits the bug was on RC1 before RTM came out so I can't confirm whether RC2 or RTM introduced the bug without digging in deeper.
