### ISSUE TITLE
AutomaticAuthenticate = true by default is dangerous

### ISSUE THREAD

**Issue by leastprivilege** [aspnet/Security#858]
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs#L27

I can already see people doing getting that wrong when they wire up a 2nd cookies MW for external authN. False was the more secure default.

**Comment by PinpointTownes** [comment]
Related topic: https://github.com/aspnet/Security/issues/569#issuecomment-154519589.

**Comment by Tratcher** [comment]
There's a trade off here between security and usability, and in this case we think the usability issues are more impactful.

**Comment by leastprivilege** [comment]
That's an OH ;)
