### ISSUE TITLE
JwtBearer should append WWW-Authenticate to any existing values

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#864]
WWW-Authenticate can officially exist as a single header comma separated header or as multiple header entries, but browsers only support the former format. Right now the middleware appends a new string to the StringValues array, but it needs to append to the string directly.

Actual:
```
www-authenticate: Bearer realm="http://example1.com"
www-authenticate: Bearer realm="http://example2.com"

```
Expected:
```
www-authenticate: Bearer realm="http://example1.com", Bearer realm="http://example2.com"
```

**Comment by PinpointTownes** [comment]
Adding `error`/`error_description`/`error_uri` in the equation makes thing much more complex:

```
WWW-Authenticate: Bearer realm="example1", error="invalid_token", error_description="The access token expired", Bearer realm="example1", error="invalid_token", error_description="The access token expired"
```

I doubt many clients will be able to parse that correctly.

**Comment by Tratcher** [comment]
I actually had to re-write the code for HttpWebRequest to parse that correctly, so I at least know that one works.

**Comment by Eilon** [comment]
We do this on purpose. Please talk to @Tratcher if you don't believe me 😄

**Comment by PinpointTownes** [comment]
> We do this on purpose.

Best explanation ever :trollface:

**Comment by Tratcher** [comment]
Yeah, I had it backwards. Browsers require separate headers for www-authenticate.

**Comment by PinpointTownes** [comment]
Ah, that's clearer :smile: 

I'm still not sure why you'd want multiple automatic authentication middleware to apply a challenge at the same time, but okay.

**Comment by Tratcher** [comment]
Basic, Bearer, Negotiate, and Kerberos are all compatible and the client can choose between them.

**Comment by PinpointTownes** [comment]
> Basic, Bearer

In theory, sure. But in practice I can't think of scenario where you'd like to mix basic and bearer :smile: 

> Negotiate, and Kerberos

IMHO, Negociate and Kerberos are unlikely to be added at the app/middleware level (unless someone is brave enough to write a managed implementation :smile:).

It's more something that should be handled at the host level. And in this case, what's supposed to happen if the app has already sent a `WWW-Authenticate` response header with `Basic` or `Bearer`? Will the host (e.g IIS or WebListener) send an additional challenge if WA is enabled?

**Comment by Tratcher** [comment]
WebListener is plugged into the Challenge pipeline to add the auth headers as needed. IIS can add headers as well.
