### ISSUE TITLE
AllowAnonymous at controller can not be overridden at action

### ISSUE THREAD

**Issue by brockallen** [aspnet/Security#865]
The code below allow anonymous users to access ~/Movie/Index. I'd expect the [Authorize] on the action to override the inherited [AllowAnonymous]. I don't recall MVC 5 allowing that?

```
    [AllowAnonymous]
    public class MovieController : Controller
    {
        [Authorize]
        public IActionResult Index(int page = 1)
        {
            return View();
        }
    }
```

**Comment by brockallen** [comment]
The same unexpected behavior is also allowed if you indicate a policy.

**Comment by dougbu** [comment]
@brockallen have you already tested the behaviour when using MVC 5?

Separately I suspect the relevant code is in the [MVC repo](https://github.com/aspnet/Mvc).

**Comment by mythjuha** [comment]
Is it nesceserry to put [AllowAnonymous] on top of the controller? Just remove it, and everything will be allowed anonymous except for those actions where you've put the Authorize attribute.  [AllowAnonymous] to override actions in a [authorize] controller.

**Comment by brockallen** [comment]
> Is it nesceserry to put [AllowAnonymous] on top of the controller

It is if you have a global authorization filter.

> @brockallen have you already tested the behaviour when using MVC 5?

MVC5 works the same, but now that I think about it a [OverrideAuthorization] was added at some point to fix this in MVC v.Old.

**Comment by Eilon** [comment]
This design is deliberate.

**Comment by brockallen** [comment]
> This design is deliberate.

Is there a plan to have the same [OverrideAuthorization] feature then as MVC 5?

**Comment by Eilon** [comment]
@brockallen no plan at this time. We have an issue tracking it here: https://github.com/aspnet/Mvc/issues/4203

There hasn't been much demand for it so far, and to be honest, we were never super happy about the design. So if we bring something like it back in the future, it would likely take a different shape (though we don't know quite what exactly).

**Comment by brockallen** [comment]
> There hasn't been much demand for it so far, and to be honest, we were never super happy about the design. So if we bring something like it back in the future, it would likely take a different shape (though we don't know quite what exactly).

Agreed, I don't like the [OverrideAuthorization], as if feels (and was IIRC) bolted on as an afterthought. Just as a FYI, semversioning allows for breaking changes when you go to v2.0 :)
