### ISSUE TITLE
Custom JSON response from Policy-Based Authorization is being overwritten

### ISSUE THREAD

**Issue by levitatejay** [aspnet/Security#872]
https://github.com/aspnet/Identity/issues/858

**Comment by Tratcher** [comment]
@HaoK?

The repro is very MVC specific, it may be an issue with the flow there.

**Comment by levitatejay** [comment]
In RC1 I was using AuthorizationFilterAttribute to check my requirements and create a custom JSON response with a message and 403 status code.

In RC2 the AuthorizationFilterAttribute has been removed (https://github.com/aspnet/Mvc/issues/4233) because authorization policies and requirements are now the recommended way to handle authorization.

However, I can't figure out how to use policies to return a custom message/status code. If any of my policy handlers fail then whatever middleware (I think its the middleware?) I use seems to intercept the response and overwrite it with a raw 403 response.

I've tried the following middleware:
app.UseIdentity()
app.UseJwtBearerAuthentication()
app.UseOAuthValidation() (AspNet.Security.OAuth.Validation)

**Comment by HaoK** [comment]
@blowdart for his thoughts as well.  but its not the Policy's job to return custom message or status code.  you should be able to handle authZ failures gracefully at a higher level.

**Comment by levitatejay** [comment]
What level should I be handling this at? I don't want to fill each controller action with authorization logic and the AuthorizationFilterAttribute has been removed...

It makes sense to me that I can decorate a controller action with something like:
`[Authorize(Policy = "ValidLicence")]`
and if someone submits a request with an out of date licence they get the response:
```
Status code: 403
Reason: "Your licence has expired"
```
Especially as I add more requirements to my policies... A client could receive a 403 for any number of reasons and its helpful if the client can know why it was forbidden.

I understand not wanting to return custom status codes from policies but what about a custom message? That way we can optionally tell a client/user what requirement they failed.

**Comment by blowdart** [comment]
Its not unreasonable, but it'd be hard to make generic so it flows over all different types of responses, headers, JSON or HTML. That's certainly outside of the scope for authorization itself, as it has no notion of presentation. 

Worth thinking about in 1.1.

**Comment by PinpointTownes** [comment]
@levitatejay I took the liberty to close [the related ticket you opened on the OpenIddict repository](https://github.com/openiddict/openiddict-core/issues/134), since OpenIddict is not responsible of applying the authorization policies.

> I've tried the following middleware:
app.UseIdentity()
app.UseJwtBearerAuthentication()
app.UseOAuthValidation() (AspNet.Security.OAuth.Validation)

As mentioned, the scenario you're trying to achieve will likely require important infrastructure changes in ASP.NET Core to make the authorization stack less opaque than it is currently (at least, to allow returning an error message).

Unfortunately, this is not something I can easily implement in the OAuth2 validation middleware (we'll port the `error`/`error_description`/`error_uri` handling from the JWT bearer middleware in alpha2, though).

Definitely a scenario to support in the next version, IMHO.

**Comment by levitatejay** [comment]
Could someone please recommend a workaround for the meantime? 

In RC1 I was creating a custom `AuthorizationFilterAttribute` for each case but they are gone in RC2.

I have a few ideas but I don't like any of them:
- Throw custom exceptions in my requirement handlers and catch them somewhere (where?) and modify the response then?
- Create a new scoped service with an `IAuthorizationRequirement FailedRequirement` property which the requirement handler would set when it fails and then write some new middleware that checks for a failed requirement and modifies the response.
- Write auth logic in every controller action and handle the response there.

**Comment by levitatejay** [comment]
Also where is the response body being overwritten? I can see in `Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs` the response status code is being overwritten: 
```
protected virtual Task<bool> HandleForbiddenAsync(ChallengeContext context)
        {
            Response.StatusCode = 403;
            return Task.FromResult(true);
        }
```
But where is the body overwritten?

**Comment by Tratcher** [comment]
It's probably not overwritten so much as merely ignored and never sent from `mvcContext.Result`.

**Comment by levitatejay** [comment]
@Tratcher Thank you! I just discovered that I can change the response from the requirement handler by using: `mvcContext.HttpContext.Response.Body.Write(data, 0, data.Length);`

It seems that writing to the response body causes the auth middleware to ignore the challenge... (HandleForbiddenAsync isn't getting called). I'm not sure why though?

Are you able to shed some light on why this works but setting the context.Result doesn't? Is there a way to use context.Result? It seems cleaner than using a stream writer

Is this okay as a workaround until there is a supported way to return messages for requirements? I'm nervous about interfering too much with the authentication pipeline

**Comment by Tratcher** [comment]
HandleForbiddenAsync can't run after you write to the body because the headers have already been sent. I don't recommend this approach as it can flush the headers before MVC is finished and may cause errors if MVC tries to set more headers.

**Comment by levitatejay** [comment]
> Its not unreasonable, but it'd be hard to make generic so it flows over all different types of responses, headers, JSON or HTML. That's certainly outside of the scope for authorization itself, as it has no notion of presentation.

If the authorization middleware has no concept of presentation then it should be possible for us to put in our own middleware in the pipeline that can inspect what requirements failed for the request and modify the response body accordingly.

**Comment by Ciantic** [comment]
> @levitatejay Thank you! I just discovered that I can change the response from the requirement handler 

Where is this handler? I also would like to return different JSON messages when different claim requirements fail. Right now I'm getting empty result with Status Code 403.

**Comment by Ciantic** [comment]
Apologies but I think this would be more nicely handled by status code pages extension, I opened an issue there: https://github.com/aspnet/Diagnostics/issues/316

**Comment by HaoK** [comment]
Will be tracked via https://github.com/aspnet/Security/issues/901 as well

**Comment by aiampogi** [comment]
I was able to send a custom authorization failure message by adding a custom error handling Middleware and let the AuthorizationHandler throw the exception (with the proper message) I am expecting in the Middleware and write to the httpContext.Response.

**Comment by hmvs** [comment]
I would double on that. Need a way to indicate the reason why policy is failed. In our case it is when user need to accept new "privacy policy".

**Comment by xKloc** [comment]
I would also like to be able to set a response body depending on the policy that failed.  Right now I'm using the events from `AddAuthentication` but this is too generic for the solution I'd like.

```
            services.AddAuthentication(_settings.AuthenticationScheme)
                .AddJwtBearer(_settings.AuthenticationScheme, options =>
                {
                    options.TokenValidationParameters = tokenValidationParameters;
                    options.Audience = _settings.Audience;
                    options.ClaimsIssuer = _settings.Issuer;
                    options.Challenge = "Bearer";
                    options.Events = new JwtBearerEvents
                    {
                        OnChallenge = context =>
                        {
                            context.HandleResponse();

                            var response = new Response(HttpStatusCode.Forbidden, "Your session has ended due to inactivity");

                            return context.Response.WriteAsync(JsonConvert.SerializeObject(response));
                        }
                    };
                });
```
