### ISSUE TITLE
How do I specifiy AccessDeniedPath?

### ISSUE THREAD

**Issue by alaatm** [aspnet/Security#878]
In RC2, it looks like we no longer use `app.UseCookieAuthentication(options => \* ... *\);` but instead `app.UseIdentity();`. In this case, how can I set a custom value for `AccessDeniedPath`?

Also, how do I prevent the cookie auth middleware from doing the redirect all together. I would like to receive a 403 when authorization fails and handle it through `app.UseStatusCodePagesWithReExecute("/h/{0}")`.

**Comment by Tratcher** [comment]
The relationship between UseCookieAuthentication and UseIdentity has not changed in RC2. If you're using the Identity components you need to use UseIdentity, which internally registers several cookie auth instances. You can configure these via:
```
services.AddIdentity(options =>
{
  options.Cookies.ApplicationCookie.AccessDeniedPath = ...
});
```
You can override the behavior via the events:
https://github.com/aspnet/Security/issues/588#issuecomment-169174022
