### ISSUE TITLE
AuthorizationHandlerContext responsibility split up & thread safety

### ISSUE THREAD

**Issue by 8snit** [aspnet/Security#879]
short background - we are currently bringing our ABAC approach forward, staying on the XACML path conceptually (architecture/flow) but replacing the language element part with "code" to make it more developer friendly (the "leave rules to business experts" thing didn't work out for us so far...)

first of all, thx for the great job with the authorization abstractions, without too much tweaking we were able to get "some kind of" PDP executing c# code (resp. ScriptCs scripts) running, in addition to the out of the box framework functionality we support

A. handler processing in parallel 
B. direct routing of requirements to handlers (instead of iterating through all registered handlers)
C. triggering webhooks after approval (~ simplified obligation stuff)
D. pluggable evaluation strategies (~ combining algorithm) e.g. with fail fast (not going through all handlers every time)
E. auditing information for all succeeded/failed requirements (in order!)

what is preventing us from going straight ahead with the current (and not a patched) AspNetCore.Authorization implementation is the "not very customizable nature" of the AuthorizationHandlerContext with its two responsibilites - holding current state and evaluating it:

- one thing we propose is to introduce an interface like
```
   public interface IAuthorizationEvaluator
   {
      bool HasFailed(AuthorizationHandlerContext context);
   
      bool HasSucceeded(AuthorizationHandlerContext context);
   }
```
which is injected and used within the IAuthorizationService (instead of the HasFailed/HasSucceeded properties of the AuthorizationHandlerContext) to make the decisions (see D)

- we also vote for an additive (see E) & thread safe (see A) implementation of the Succeed/Fail calls within the AuthorizationHandlerContext (instead of _pendingRequirements.Remove), 
```
    public class AuthorizationHandlerContext
    {
        ...

        public ConcurrentQueue<IAuthorizationRequirement> FailedRequirements { get; }

        public ConcurrentQueue<IAuthorizationRequirement> SucceededRequirements { get; }

        public void Fail(IAuthorizationRequirement requirement = null)
        {
            FailedRequirements.Enqueue(requirement);
        }

        public void Succeed(IAuthorizationRequirement requirement)
        {
            if (requirement == null)
            {
                throw new ArgumentNullException(nameof(requirement));
            }

            SucceededRequirements.Enqueue(requirement);
        }
    }
```
an interface/base class for AuthorizationHandlerContext combined with a factory approach could be an alternative

looking forward to feedback and hopefully a chance to contribute :)

**Comment by HaoK** [comment]
@blowdart thoughts on how important it is for our default implementations to be thread safe.  Imo if we make things pluggable, customers who need thread safety would still be able to plug in their threadsafe implementations (as opposed to making everything slower by default...)

**Comment by blowdart** [comment]
A run in parallel setting maybe? Or have two in box implementations users can swap accordingly?

**Comment by HaoK** [comment]
Well my point was more that we don't ensure thread safety in many places right now, it seems a little weird (and of questionable use) to support only in this one place

I'd suggest we start with just adding something like the `IAuthorizationEvaluator` to start, as that will enable many workarounds at least.  We can always add more implementations later if this becomes a common ask...

**Comment by HaoK** [comment]
Note: the `IAuthorizationEvaluator` is a pretty big new extensibility hook, as they will be able to change the semantics of what defines an authorization success (i.e. today we ensure that all requirements are met), with this interface, they could treat some requirements to be special.  Not saying this is bad, just pointing out plugging in your own evaluator can potentially invalidate some of the assertions we make today.

**Comment by HaoK** [comment]
6f15d616a8954420bcb277ed938de1b14f6dbd6f

**Comment by HaoK** [comment]
FYI, I'll be adding an option to have the default service fail fast as well https://github.com/aspnet/Security/issues/945
