### ISSUE TITLE
Microsoft.AspNetCore.Authentication.Salesforce

### ISSUE THREAD

**Issue by dallasclement** [aspnet/Security#880]
Hi.  Just wanted to check if anyone is working on some OAuth 2.0 Salesforce authentication for asp.net core?

**Comment by davidfowl** [comment]
It's here https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src

**Comment by davidfowl** [comment]
Specifically https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src/AspNet.Security.OAuth.Salesforce

**Comment by dallasclement** [comment]
Thanks davidfowl.  I'm looking for something that can support a salesforce connected app and can implement a callback handler for the oauth token.  I was imagining something that would follow a similar pattern to Microsoft.AspNetCore.Authentication.Google etc.

**Comment by PinpointTownes** [comment]
@dallasclement FYI all the aspnet-contrib social providers are based on the [OAuth2 generic middleware](https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNetCore.Authentication.OAuth) and follow exactly the same approach as the FB/Google/MSFT providers maintained by the ASP.NET team.

**Comment by dallasclement** [comment]
Got it.  Thanks @PinpointTownes.

**Comment by karyaevsm** [comment]
@PinpointTownes how about obeying the new .NetStandard versioning for those packages in nuget? Don't you think your answer is rather unfair?

**Comment by PinpointTownes** [comment]
@karyaevsm unfair? Not sure I understand what you mean...
