### ISSUE TITLE
[Question] Retrieve Scope

### ISSUE THREAD

**Issue by XcoderTeam** [aspnet/Security#885]
In configuration
```
app.UseFacebookAuthentication(new FacebookOptions {
                AppId = Configuration["Authentication:Facebook:AppId"],
                AppSecret = Configuration["Authentication:Facebook:AppSecret"],
                Scope = { "public_profile", "email", "user_birthday", "user_education_history"},
                Fields = { "email", "birthday", "education" }
            });
```

How to retrieve all the education since ClaimTypes does have education?
```
var dob = info.Principal.FindFirstValue(ClaimTypes.DateOfBirth);
var educations = info.Principal.FindAll("????????");
```

**Comment by Tratcher** [comment]
The middleware does not copy all of the user info into claims by default. Here's the list of built in fields:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Facebook/FacebookHandler.cs#L45-L127
If you want to map more fields to claims then you should use the OnCreatingTicket event:
```
new FacebookOptions()
{
  Events = new FacebookEvents()
  {
    OnCreatingTicket = context => { ... }
  }
}
```

**Comment by XcoderTeam** [comment]
@Tratcher 

I try this below code encounter an err RuntieBinderException
Can you provide the complete implementation?

`                Events = new OAuthEvents
                {
                    OnCreatingTicket = context => {
                        var educations = context.User.Value<dynamic>("education");

                        context.Identity.AddClaim(new Claim("education", educations));

                        return Task.FromResult(0);
                    }
                }`

                var education = info.Principal.FindAll("education");

**Comment by Tratcher** [comment]
@blowdart @danroth27 this is a good FAQ for docs: How to request more information via OAuth (e.g. Scopes), how to map that data to claims, and how to map those claims over into Identity.

**Comment by blowdart** [comment]
Are you volunteering @Tratcher ? If so, put an issue in the docs repo :)

**Comment by Tratcher** [comment]
https://github.com/aspnet/Docs/issues/86#issuecomment-228139133

**Comment by Tratcher** [comment]
@XcoderTeam don't use `dynamic`, just use `string` like here:
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Facebook/FacebookHelper.cs#L25

**Comment by Tratcher** [comment]
Here's another sample:
https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L221-L227

**Comment by XcoderTeam** [comment]
@Tratcher It work now
