### ISSUE TITLE
Not calling Dispose on HttpRequestMessage and HttpResponseMessage

### ISSUE THREAD

**Issue by PaulMiami** [aspnet/Security#886]
What is the best practice for calling Dispose (or not) on HttpRequestMessage and HttpResponseMessage?

Examples:

https://github.com/aspnet/Security/blob/1.0.0/src/Microsoft.AspNetCore.Authentication.Google/GoogleHandler.cs#L28-L34

        protected override async Task<AuthenticationTicket> CreateTicketAsync(ClaimsIdentity identity, AuthenticationProperties properties, OAuthTokenResponse tokens)
        {
            // Get the Google user
            var request = new HttpRequestMessage(HttpMethod.Get, Options.UserInformationEndpoint);
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", tokens.AccessToken);

            var response = await Backchannel.SendAsync(request, Context.RequestAborted);
            response.EnsureSuccessStatusCode();

            var payload = JObject.Parse(await response.Content.ReadAsStringAsync());
            ...
         }
and 
https://github.com/aspnet/Security/blob/1.0.0/src/Microsoft.AspNetCore.Authentication.Facebook/FacebookHandler.cs#L37-L40  
Both examples are not calling Dispose

Could this be an omission? or is there a valid reason behind it, maybe because the method is async?

**Comment by Tratcher** [comment]
It's not important in these scenarios. Disposing a request or response only calls Dispose on their Content field. Of the various HttpContent implementations, only StreamContent needs to dispose anything. HttpClient's default SendAsync fully buffers the response content and disposes the stream, so there's nothing the caller needs to do.

**Comment by PaulMiami** [comment]
got it, I am guilty of doing that on MemoryStream many times.
But to be clear, from a best practice point of view, if I were to implement similar functionality, there are no problems with me wrapping those objects in an using block.
I just don't want to have to rely on an intimate knowledge of some IDisposable class and keep track of implementation changes that might break my code down the line.

**Comment by Tratcher** [comment]
Calling Dispose should be fine, it's just noise we knew we didn't need.

**Comment by PaulMiami** [comment]
ok, thanks
