### ISSUE TITLE
Cannot get any user information

### ISSUE THREAD

**Issue by Brian-Ding** [aspnet/Security#887]
I am trying the social sample in this repo, and I cant get back any use info, link name or email address
![image](https://cloud.githubusercontent.com/assets/11363173/16442460/54a0ac42-3e05-11e6-9230-7f761ff071bb.png)

I comment out all other social provider except Microsoft account, and I am logging in with a outlook.com account.

So,  login with **UseMicrosoftAccountAuthentication** give me back all the user info I need
but with **UseOAuthAuthentication** everything is null like the screen shot

Anything am I missing here?

Thank you

**Comment by Tratcher** [comment]
You mean this one? https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L156-L167
Note that only retrieves the tokens, e.g. the access_token. It does not retrieve any claims.  See the github sample for manually retrieving claims: https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L207-L262

**Comment by Brian-Ding** [comment]
thank you! that works for me.

another question, if I have a uwp, and successfully obtain user's token, how can I use that token to access a controller/api  which has an Authorize attribute, of my mvc web app?

**Comment by Brian-Ding** [comment]
Ok, did a few more test
 create a new blank mvc app with individual authentication, add this code and nugget packages accordingly
![image](https://cloud.githubusercontent.com/assets/11363173/16481045/d9ee8e6a-3edb-11e6-82e1-52ba16290b9f.png)

add a new method in HomeController, like below
![image](https://cloud.githubusercontent.com/assets/11363173/16481124/275eacd4-3edc-11e6-8903-875ef37e652a.png)

In my uwp, I am calling the api like this
![image](https://cloud.githubusercontent.com/assets/11363173/16481116/20584e40-3edc-11e6-9c7b-c6537ce6b1bc.png)

calling https://graph.microsoft.com/v1.0/me gives me back what I am expecting, while calling {domain}/home/GetInfo redirect to login page

screen shot of fiddler
![image](https://cloud.githubusercontent.com/assets/11363173/16481203/89325b18-3edc-11e6-943f-59fa6d332761.png)
please notice the "invalid token" error

thank you

**Comment by Tratcher** [comment]
Those tokens are for use with the MSA APIs, not for 3rd parties. Their format and validation are opaque to us.
We primarily support JWTs via OpenIdConnect and Azure AD. See https://github.com/aspnet/Security/blob/dev/samples/JwtBearerSample/Startup.cs

**Comment by Brian-Ding** [comment]
thx for that, I will close the issue
