### ISSUE TITLE
Custom Authentication Namespace

### ISSUE THREAD

**Issue by supergibbs** [aspnet/Security#888]
I wrote another OAuth provider based on `Microsoft.AspNetCore.Authentication.Google` and wondering what namespace I should use. I also want to make an older OWIN compatible one so I don't want to use something generic and make it confusing. Can I put it in `Microsoft.AspNetCore.Authentication.ThirdParty`? If not, is there a recommended naming convention?

`ThirdParty.AspNetCore.Authentication`
`ThirdParty.Core.OAuth`

**Comment by davidfowl** [comment]
You should consider contributing it to https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src

**Comment by supergibbs** [comment]
Oh even better! Thanks!
