### ISSUE TITLE
Minor comment cleanup.

### ISSUE THREAD

**Issue by Zoltu** [aspnet/Security#891]
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationOptions.cs#L25 references Twitter yet it is in a generalized class.  Either this property should be extracted out into a Twitter specific handler or the comment should be generalized.

I don't actually understand what this does (which is why I was reading the comment) so I'm not sure what the right answer is.

**Comment by troydai** [comment]
Fixed in 7b7da43.
Thanks for reporting the issue @Zoltu .
