### ISSUE TITLE
ASP.NET Core authentication to Azure AD to get||set Role

### ISSUE THREAD

**Issue by wangkanai** [aspnet/Security#894]
I have a few questions i can't find regarding ASP.NET core connecting Azure AD using OpenIdConnect.
- How do i get the role that User is assigned to? `User.IsInRole("xxx")` also return `false`
- How do I set the role to the User? Don't know where to start :-(
- How do i add new claim to the User? Don't know where to start also

**Startup.cs**
```
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
{
    ClientId = Configuration["Authentication:AzureAd:ClientId"],
    ClientSecret = Configuration["Authentication:AzureAd:ClientSecret"],
    Authority = Configuration["Authentication:AzureAd:AADInstance"] 
       + Configuration["Authentication:AzureAd:TenantId"],
    CallbackPath = Configuration["Authentication:AzureAd:CallbackPath"],
    ResponseType = OpenIdConnectResponseType.CodeIdToken               
});
```
**Indes.cshtml**
```
<div>
    <h3>Claims</h3>
    <table class="table">
        <tr>
            <th>Type</th>
            <th>Value</th>
        </tr>
        @foreach (var claim in User.Claims)
        {
            <tr>
                <td>@claim.Type</td>
                <td>@claim.Value</td>
            </tr>
        }
    </table>
</div>
```
Type | Value
-------|----
aud | xxx
iss | xxx
iat | xxx
nbf | xxx
exp | xxx
http://schemas.microsoft.com/claims/authnmethodsreferences | xxx
c_hash | xxx
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname | xxx
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname | xxx
ipaddr | xxx
name | xxx
nonce | xxx
http://schemas.microsoft.com/identity/claims/objectidentifier | xxx
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier | xxx
http://schemas.microsoft.com/identity/claims/tenantid | xxx
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name | xxx
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn | xxx
ver | xxx

**Comment by Tratcher** [comment]
Here's an older sample that should help:
https://github.com/Azure-Samples/active-directory-dotnet-webapp-roleclaims/blob/master/WebApp-RoleClaims-DotNet/App_Start/Startup.Auth.cs#L55
https://github.com/Azure-Samples/active-directory-dotnet-webapp-roleclaims/blob/master/WebApp-RoleClaims-DotNet/Controllers/HomeController.cs#L47

Configuring roles:
https://azure.microsoft.com/en-us/documentation/articles/role-based-access-control-configure/

**Comment by wangkanai** [comment]
Thank you @Tratcher for help point out how to get the Roles of the current ClaimsPrincipal from Azure-Samples.

Duo configuring roles base access control configure is how i would like my app to be able for users to configure role in the app. But the sample seem to be specific for users roles in Azure Portal.
Role in OpenID Connection sound like user should be assign to Group of Azure Active Directory.
Is there a way for you to configure roles programming?

**Comment by Tratcher** [comment]
Not from this end of things, the OpenIdConnect protocol does not provide a way for us to modify data in the identity server (AAD). You should investigate the if this is possible via Azure's SDK.

**Comment by wangkanai** [comment]
Seem that GraphApi is what you use the query the active directory for user profile. But the mean time their dont have .net core library yet. 
Dont know if im correct or not?

**Comment by Eilon** [comment]
@vibronet

**Comment by muratg** [comment]
This is a missing feature in ADAL. Nothing to do in OIDC here. Feel free to ask any questions you may have to Azure AD.
