### ISSUE TITLE
Caching of RS256 info

### ISSUE THREAD

**Issue by jerriep** [aspnet/Security#896]
Hi,

I am using the JWT middleware and the middleware is automatically querying the OIDC wellknown endpoint to discover and subsequently download the public key which is used to validate JWTs.

I have some questions about the caching of the public key:

1. Does the public key get cached? (It seems like it does not download it every time)
2. How long does it get cached?
3. Is there any way to manually invalidate it and force it to be re-downloaded again? (I think Google for example cycles their keys every 24 hours)

Thanks!

**Comment by PinpointTownes** [comment]
Hey Jerrie ;)

> Does the public key get cached? (It seems like it does not download it every time)

Yes, by IdentityModel's `ConfigurationManager`: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs

> How long does it get cached?

By default, 1 day (in the last version, but IIRC, it was something like 5 days in the previous bits).

> Is there any way to manually invalidate it and force it to be re-downloaded again? (I think Google for example cycles their keys every 24 hours)

`ConfigurationManager` has a `RequestRefresh` method you can call for this purpose (the tricky part will be to access the configuration manager if you let the JWT bearer middleware instantiate it manually).

Note that the JWT bearer middleware automatically triggers a refresh when catching `SecurityTokenSignatureKeyNotFoundException` exceptions if you leave `RefreshOnIssuerKeyNotFound` to `true` in the JWT options. So in practice, manually refreshing the keys shouldn't be necessary.

**Comment by jerriep** [comment]
Thanks @PinpointTownes !
