### ISSUE TITLE
Authorize(Roles="Admin") not working.

### ISSUE THREAD

**Issue by Luigie** [aspnet/Security#899]
I havethe following setup for an api with identity server4

API call

        [HttpGet()]
        [EnableQuery()]
        [Authorize(Roles="admin")]
        public IQueryable<UserDTO> Get()
        {
            return userService.GetAllUsers().ProjectTo<UserDTO>();
        }
jwt token

```JSON
{
  "nbf": 1468419573,
  "exp": 1468423173,
  "iss": "https://localhost:44324",
  "aud": "https://localhost:44324/resources",
  "client_id": "platformAdmin",
  "scope": [
    "openid",
    "platformApi",
    "profile"
  ],
  "sub": "test@test.be",
  "auth_time": 1468419573,
  "idp": "idsrv",
  "name": "damienbodadmin",
  "given_name": "damienbodadmin",
  "email": "damien_bod@hotmail.com",
  "email_verified": true,
  **"role": [
    "admin",**
    "dataEventRecords.admin",
    "dataEventRecords.user",
    "dataEventRecords",
    "securedFiles.user",
    "securedFiles.admin",
    "securedFiles"
  ],
  "amr": [
    "password"
  ]
}
```

Request in postman

```
GET /odata/Users HTTP/1.1
Host: localhost:44306
Authorization: Bearer eyJhbGciOiJSUzI1................................GdJVw
Cache-Control: no-cache
Postman-Token: 37b690e5-827b-dfe3-5bd0-7ba5c2aa5732
```

Why is the role:admin not mapped to Roles="admin" in the Authorize attribute on the call?

also User.IsInRole is empty.

startup.cs contains: 

```C#
   JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

              app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "https://localhost:44324/", //Identity Server 4 host
                RequireHttpsMetadata = true,
                EnableCaching = false,
                ScopeName = "platformApi",
                AutomaticAuthenticate = true,
                AutomaticChallenge = true
            });

            app.UseOData<ODataModel>("odata");
            app.UseMvc(builder =>
            {
                builder.MapODataRoute<ODataModel>("odata");
            });
```

**Comment by leastprivilege** [comment]
try setting `RoleClaimType = "role"`

on the token validation MW. Also inspect the claims collection to be sure the claims from the token made it into MVC.

**Comment by PinpointTownes** [comment]
@leastprivilege hahaha, a perfect use case to illustrate my yesterday's tweets :trollface: 

Ironically, it would work flawlessly if you didn't recommend adding `JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();` everywhere.

**Comment by leastprivilege** [comment]
Yep I agree with you. Let's keep the people dumb so they don't need to understand what's going on under the covers. You won.
