### ISSUE TITLE
Swapping from ASP .Net Core 1.0.0-rc2-final to 1.0.0 causes iOS app authentication to fail

### ISSUE THREAD

**Issue by dumbledad** [aspnet/Security#904]
I have an ASP .Net Core 1.0.0-rc2-final web service up and running in Azure. If I swap the service in the Azure portal to a deployment made with 1.0.0 then the iOS client authentication seems to fail.  There are code changes between the two deployments, but after much debugging I think the issue may be with the version swap. 

We are using Azure Active Directory B2C for our authentication.

Here's what goes wrong. 

1. The iOS app successfully makes authenticated API calls  
2. We swap deployment slots from one written in ASP .Net Core 1.0.0-rc2-final to one in 1.0.0  
3. The iOS app now gets 500 errors from the same API calls  
4. If the user logs out of the iOS app and then back in again the API calls are now successful  

Is there anything different between the pre-release RC2 and the released ASP .Net Core that would cause Azure AD B2C authentication to fail without a log-off and log-on refresh?

**Comment by Tratcher** [comment]
What security components are you're using? Have you turned on the server logs to see if there's an Exception triggering the 500?

**Comment by dumbledad** [comment]
I'll look at the server log idea, thanks. 

It's proving incredibly difficult to debug because

1. Since moving to 1.0.0 from RC2 non of our machines will build the version that's deployed and live without upgrading it first; and  
2. the service is live so I dare not swap out the running API again (users calls started failing last time)

**Comment by Eilon** [comment]
@dumbledad can you tell us more about how the iOS app is doing its auth? Is it using bearer tokens? Something else? Using ADAL or MSAL?

We suspect that this might be due to Azure App Services not using the same data protection keys between slots, so when you do a swap, the keys become invalid. We are working with the Azure App Service team to see if this can be addressed in a future update.

**Comment by dumbledad** [comment]
Not sure I understand those acronyms, sorry. It's code I have inherited and uses Azure B2C. I think that's ADAL. We do pass up tokens (and have a refresh token). Looking in the Startup.cs we have this call in the Configure method: `UseJwtBearerAuthentication` so I think the answer is bearer tokens and ADAL.

I now think the error is from RC2 correctly reporting a 401 error (which our iOS client uses to trigger a token refresh if the 401 response's data contains the string "SecurityTokenExpiredException") and the released ASP.Net Core which instead returns a 500 error. I'll post that issue separately here:  https://github.com/aspnet/Security/issues/927

**Comment by Eilon** [comment]
Ok so we'll track just the new issue then.
