### ISSUE TITLE
Support for Cookie "SameSite" Flag

### ISSUE THREAD

**Issue by mariusschulz** [aspnet/Security#908]
Are there any plans to implement support for the cookie [`SameSite` flag](https://en.wikipedia.org/wiki/HTTP_cookie#SameSite_cookie) within the cookie authentication middleware? The flag helps mitigate CSRF attacks and is currently recognized by Chrome and Opera, and possibly [more browsers soon](https://www.chromestatus.com/feature/4672634709082112).

I'm thinking about a new property on `CookieAuthenticationOptions`, as illustrated here:

``` cs
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
    SameSite = SameSitePolicy.Always // or SameSitePolicy.None
    // ...
});
```

I think this feature has a very good cost-benefit ratio. The implementation should be relatively straightforward, and it wouldn't hurt to have an additional protection measure against CSRF besides antiforgery tokens.

**Comment by Tratcher** [comment]
This was previously discussed here: https://github.com/aspnet/Security/issues/831#issuecomment-222013829

SameSite is still in draft form: https://tools.ietf.org/html/draft-west-first-party-cookies-07

We may add support for it when the spec is finished.

**Comment by Tratcher** [comment]
@blowdart has requested this be re-triaged.

**Comment by Tratcher** [comment]
Depends on https://github.com/aspnet/HttpAbstractions/issues/710

**Comment by Eilon** [comment]
Need to also make sure we update the Cookie Policy middleware to allow setting this.

**Comment by Eilon** [comment]
And Security-related cookies from this repo, plus also Antiforgery cookies would have SameSite enabled by default. We'd have to evaluate all other cookies created by ASP.NET Core to see what they should have by default.

**Comment by Eilon** [comment]
Antiforgery work tracked here: https://github.com/aspnet/Antiforgery/issues/127
