### ISSUE TITLE
How to UseFacebookAuthentication (and other external services) for multiple domain site

### ISSUE THREAD

**Issue by Eilon** [aspnet/Security#910]
Moved from https://github.com/aspnet/Mvc/issues/4900
By @NGancevich

---

Hello I have site that has multiple domains. For instance example.com, example.gb .... All these domains are linked to one site. I need something like this

``` c#
app.UseFacebookAuthentication(new FacebookOptions
            {
                AppId = Configuration["Authentication:Facebook:AppId1"],
                AppSecret = Configuration["Authentication:Facebook:AppSecret1"],


            });

app.UseFacebookAuthentication(new FacebookOptions
            {
                AppId = Configuration["Authentication:Facebook:AppId2"],
                AppSecret = Configuration["Authentication:Facebook:AppSecret2"],


            });
```

but depending on domain name. Or may I can implement this using filters.

**Comment by Eilon** [comment]
@NGancevich can you share more about what you might have tried, and what issues you've run into?

**Comment by NGancevich** [comment]
I have site that is linked to multiple domains. For example mysite.com, mysite.net, ....

asp.net core allows only set up AppId and AppSecret once per application.  For instance in facebook 
for mysite.com (AppId = "1111", AppSecret="Secret1111") , for mysite.net (App = "2222", AppSecret="Secr2222"). But physically mysite.com and mysite.net it's one asp.net core site
 

I'd like something like this

//for mysite.com
app.UseFacebookAuthentication(new FacebookOptions
            {
                AppId = Configuration["Authentication:Facebook:AppId1"],
                AppSecret = Configuration["Authentication:Facebook:AppSecret1"],
domain = "mysite.com"

            });

and

////for mysite.net
app.UseFacebookAuthentication(new FacebookOptions
            {
                AppId = Configuration["Authentication:Facebook:AppId2"],
                AppSecret = Configuration["Authentication:Facebook:AppSecret2"],
domain = "mysite.net"

            });

**Comment by HaoK** [comment]
So you can use AuthenticationScheme to accomplish this today,
```
//for mysite.com
app.UseFacebookAuthentication(new FacebookOptions
            {
                AuthenticationScheme = "FacebookMySiteCom",
                AppId = Configuration["Authentication:Facebook:AppId1"],
                AppSecret = Configuration["Authentication:Facebook:AppSecret1"],
domain = "mysite.com"

            });
and

////for mysite.net
app.UseFacebookAuthentication(new FacebookOptions
            {
                AuthenticationScheme = "FacebookMySiteNet",
                AppId = Configuration["Authentication:Facebook:AppId2"],
                AppSecret = Configuration["Authentication:Facebook:AppSecret2"],
domain = "mysite.net"

            });
```

You would of course need to authenticate against the right facebook middleware depending on which domain you are serving.

**Comment by NGancevich** [comment]
Thank you! I'll try to implement this.

**Comment by Tratcher** [comment]
You also want to give them unique CallbackPath's

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
