### ISSUE TITLE
Use multiple instances of OpenIDConnect middleware in one app

### ISSUE THREAD

**Issue by dstrockis** [aspnet/Security#912]
Long story short: for Azure AD B2C, we need to use multiple instances of the OIDC middleware in a single app.  Each one needs its own `AuthenticationScheme` so that I can invoke the proper middleware via challenges.

I've set up the instances like so:

```
// The CreateOptionsFromPolicy sets the policy id as the AuthenticationScheme
app.UseOpenIdConnectAuthentication(CreateOptionsFromPolicy(SignUpPolicyId));
app.UseOpenIdConnectAuthentication(CreateOptionsFromPolicy(SignInPolicyId));
```

Let's say I execute a challenge with `AuthenticationScheme=SignInPolicyId`.  The requests gets sent to Azure AD, the user logs in, and the response comes back to the app with a valid OIDC message & id_token.

AspNetCore first tries to validate the incoming message using the middleware instance with `AuthenticationScheme=SignUpPolicyId`.  Problem is (I think) that the `state` in the OIDC request/response was encrypted/protected with the authentication scheme.  So the "sign up" middleware instance fails to decrypt the `state` parameter, and fails the authentication.  It never tries to validate the message using the other middleware instance.

In Katana, when this same failure occurred, the sign in request did not fail - instead the next instance of the middleware was attempted (and succeeded).  I was expecting the same behavior here.

Let me know if this makes sense.  Happy to provide sample code if necessary.  And if you wouldn't mind, please tag (@) me in any responses you want me to see so I can keep track.

**Comment by Eilon** [comment]
One possibility for this would be to use `app.Map(...)` to "fork" the middleware pipeline given different request roots. Then you'll never have a case where both auth middlesware run on the same request.

But we'll need to wait for @Tratcher to return to figure this out.

**Comment by brockallen** [comment]
I think you will need 2 different `CallbackPath` set so they don't step on each other.

**Comment by Tratcher** [comment]
This worked with Katana because it would read all requests and fall through if it didn't recognize the message. You can use OpenIdConnectOptions.SkipUnrecognizedRequests = true to get this behavior, but we don't recomend it. Instead you should assign each instance a unique CallbackPath as @brockallen suggested.

**Comment by dstrockis** [comment]
Alright, I'll give it a shot. Thanks guys.

**Comment by dstrockis** [comment]
Reopening to ask a related question, not really a new issue.

In this scenario (see original message), the user might be logged into the app with one instance of the OIDC middleware.  Then the developer invokes a different instance of the middleware using `ChallengeAsync(AuthenticationSchemeUsedForDifferentInstance, AuthenticationProperties)`.  I expected this call to trigger an auth request to the IDP.

Instead it hit this code path (https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L346) and redirected the user to the CookieMiddleware's AccessDeniedPath.

To workaround, I had to change the call to `ChallengeAsync(AuthenticationSchemeUsedForDifferentInstance, AuthenticationProperties, Microsoft.AspNetCore.Http.Features.Authentication.ChallengeBehavior.Unauthorized)`.

My question is mostly about the comment in the line referenced above.  If a UserPrincipal already exists, why do we invoke the "Forbidden" handler path (of which I'm sure the OpenIDConnectMiddleware has none)?

**Comment by Tratcher** [comment]
@dstrockis this was recently fixed here: https://github.com/aspnet/Security/pull/980

The Forbidden call is to avoid infinite auth challenge loops. If you already had a valid user for this provider then there's no reason to believe another login will grant the same user different permissions.

**Comment by dstrockis** [comment]
@Tratcher awesome, thanks.

One important scenario we have is what we call "incremental consent".  This is where a single application signs the user in initially using a basic set of scopes, like `?scope=openid email profile`.  Then, when the user tries to perform some action, the app asks for additional permissions, like `?scope=openid profile email https://graph.microsoft.com/mail.send`.

In my mind this would have worked with a single provider.  The way I implemented this in Katana was to pass the required scopes in the `AuthenticationProperties`, then extract them in `RedirectToIdentityProvider` and append them to the outbound auth request.

I don't think it's the end of the world if in this scenario the developer needs to pass `ChallengeBehavior.Unauthorized`.  This comes to mind as a valid case where another login with grant the same user different permissions.  Food for thought.
