### ISSUE TITLE
How do we capture and decrypt traffic between the ASP.NET Core client and Authorization server?

### ISSUE THREAD

**Issue by shaunluttin** [aspnet/Security#913]
We've tried Fiddler, WireShark, RawCap, Npcap, and other approaches like setting a new route. [We haven't been able to view the access code, access token, and id token from Google during an OpenID Connect flow.](http://security.stackexchange.com/questions/130571/view-the-access-code-access-token-and-id-token-from-google-during-an-openid-co/130586#130586)

We're on Windows 10 (which uses IPv6 for localhost.)

```
git clone git@github.com:aspnet/Security.git
cd samples/OpenIdConnectSample
dotnet restore
dotnet user-secrets set oidc:clientid <Client Id>
dotnet user-secrets set oidc:clientsecret <Client Secret>
dotnet user-secrets set oidc:authority https://accounts.google.com
dotnet run
```

How do we decrypt and view all the traffic between the client, user-agent, and Google.

**Comment by Eilon** [comment]
Ultimately the answer here will not be specific to ASP.NET. There's presumably some Windows policy or Fiddler/etc. setting that needs to be configured to enable monitoring of these requests.

Hopefully your post on StackExchange will yield some answers...

**Comment by lranders** [comment]
We're using Fiddler 4 and it works just fine as an SSL proxy. We're running the client and the user agent on the same box mind you. Only the AS, in our case the ADFS 2016 server is on a virtual instance in a seperate box. I don't know if it makes a difference, but we are capturing IPV4 traffic, not IPV6. We did not need to tweak any Windows policies, but Fiddler has to be told to proxy the SSL traffic.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
