### ISSUE TITLE
Feature Request Authorization with multiple Claims in Attribute

### ISSUE THREAD

**Issue by ruchanb** [aspnet/Security#914]
Here is a scenario
I have collection of Access levels according to different modules. ie Module1Read, Module1Write, Module2.. and so on
On previous version on asp.net i would create a custom Authorization Attribute an handle these access codes there and use them like
`[CustomAuthorize(Claims= "Module1Read")]`

Now this is to be handled through policy in the asp.net core
https://docs.asp.net/en/latest/security/authorization/policies.html#security-authorization-policies-based

Now here is the problem i find with policy, I have to create policy for each and every Access Levels there is. And the policies are not simple as "**EmployeeOnly**", "**Under21**" as given in the examples. 

It would be great help if you provide a way of adding these access codes and its handler somewhere so i can use them where ever necessary without needing to add a policy for each of them.

**Comment by HaoK** [comment]
See https://github.com/aspnet/Security/issues/670 and the IPolicyProvider, you can dynamically generate your requirements based on the policy name which should let you do something similar
