### ISSUE TITLE
AuthenticationTokenExtensions should have an UpdateToken

### ISSUE THREAD

**Issue by brockallen** [aspnet/Security#916]
Some API where we can update just one token (e.g. a refresh token or an access token) and the rest of what's in there is preserved. 

This is what a client app must do now (which is requires too much internal knowledge): https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Clients/src/MvcHybrid/Controllers/HomeController.cs#L46

**Comment by HaoK** [comment]
Something like this is what you are asking for? You probably are still left with doing your own copy into a subsequent properties to send down new tokens.  

```
 public static Task UpdateTokenValueAsync(this AuthenticationProperties properties, string name, string newValue) {
   var tokens = await HttpContext.Authentication.GetTokensAsync().Where(t => t.Name == name);
   foreach (var tok in tokens) tok.Value = newValue;
 }
```

**Comment by brockallen** [comment]
Well, given that there's some logic to the access token expiration, I'd almost prefer slightly higher order APIs -- one for access token with optional expiration param, one for RT. All of course could be built on the above more general API.

**Comment by brockallen** [comment]
Thanks

-Brock
