### ISSUE TITLE
is there a built-in way to cache the claims of same user? or something maybe like 'IUserClaimFactory' I can implement to generate claims of current user before I use UserClaims?

### ISSUE THREAD

**Issue by anobaka** [aspnet/Security#918]
**Backgrounds**

I **register all operations(from a webapi service) to global policies** after website starting, and I **invoke all available operations(from a webapi service) of current user and set them to user claims** in my authorization middleware after my authentication middleware.

**Register All Operations** 

```	        
//get all opeations by web api service
//...
//register all operations to global policies
if (allOperations != null)
{
	foreach (var opt in allOperations)
	{
		authOptions.AddPolicy(opt.Name, b =>
		{
			b.RequireClaim(opt.Name);
		});
	}
}
```

**and In my authorization middleware**

```
//get currentUserOperations by web api service
//...
//set them to UserClaims
(httpContext.User.Identity as ClaimsIdentity)?.AddClaims(
    currentUserOperations.Select(o => new Claim(o.Name, "")));
```

**and use it like**
```
[Authorize("SetProductPrice")]
public async Task<IActionResult> SetProductPrice(){...}
```

**Questions**

1. Every request will pass through my authorization middleware so there are too many costs to invoke available operations of current user and some requests do not need authorized still pass through this middleware. Use session to cache them may work, but I want to be sure is there a built-in way to cache the claims of same user?

2. If I do not cache user claims, and make claims of current user be populated only when I need them. Is there something maybe like 'IUserClaimFactory' I can implement to generate claims of current user automatically before I use user claims?

Maybe my design is bad or I missed something important, please help me improve, thanks

**Comment by Tratcher** [comment]
How are you persisting the user information? Via cookies? If so, you can add the claims once when they log in and persist it with the rest of the information in the auth cookie. However, if there are too many claims this can cause cookie size issues. The cookie auth middleware has a few different ways of dealing with large users.

**Comment by anobaka** [comment]
@Tratcher , gotcha, it works, really appreciate it!
