### ISSUE TITLE
Returning true from HandleUnauthorizedAsync doesn't prevent the other automatic handlers from being invoked

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#930]
When refactoring ASOS code, I discovered a weird bug in `AuthenticationHandler` that prevents `HandleUnauthorizedAsync` from working correctly. The following conditions must be met for this annoying bug to occur:

  - The ASP.NET Core pipeline must contain at least 2 authentication middleware (e.g cookies + a custom middleware).

  - The first authentication middleware must be configured with `AutomaticChallenge = true`. The challenge mode - automatic or manual - used for the second middleware is not important.

  - The second authentication middleware must override `HandleUnauthorizedAsync` and must return `true` (which is supposed to prevent the prior handlers from being invoked).

  - `AuthenticationManager.ChallengeAsync` must be called with the authentication scheme associed with the second middleware.

When all these conditions are met, returning `true` from `HandleUnauthorizedAsync` has no effect: the first automatic middleware is still ultimately called and overrides the challenge applied by the second one (which is the only one that should handle it).

This bug is likely caused by `AuthenticationHandler.HandleAutomaticChallengeIfNeeded`.

Unlike `AuthenticationHandler.ChallengeAsync`, this method - executed by all the authentication handlers in the pipeline when headers are sent - doesn't check whether the prior handler handled the challenge and blindly calls `HandleUnauthorizedAsync`.

```csharp
private async Task HandleAutomaticChallengeIfNeeded()
{
    if (!ChallengeCalled && Options.AutomaticChallenge && Response.StatusCode == 401)
    {
        await HandleUnauthorizedAsync(new ChallengeContext(Options.AuthenticationScheme));
    }
}
```

Ironically, the JWT middleware is not impacted by this bug because it returns `false` to allow the other middleware to handle the challenge: the `ChallengeAsync` of all the prior handlers is called, which automatically sets `ChallengeCalled`. Since the authentication scheme doesn't correspond to the prior middleware, `ChallengeAsync` ignores the challenge and things work like they are supposed to.

/cc @HaoK @Tratcher

**Comment by HaoK** [comment]
Ick, I will take a look

**Comment by PinpointTownes** [comment]
Okay, note for me: never say "ick" :trollface: 

![image](https://cloud.githubusercontent.com/assets/6998306/17258245/384003f8-55c6-11e6-9bad-84a87c498572.png)

![image](https://cloud.githubusercontent.com/assets/6998306/17258256/46b0038e-55c6-11e6-8d55-12352a2b74f5.png)

**Comment by HaoK** [comment]
Lolz, I don't think it really has that meaning in general, don't trust urban dictonary always :)

**Comment by HaoK** [comment]
http://www.dictionary.com/browse/ick

Is more apt: "(used as an expression of distaste or repugnance.)"

**Comment by PinpointTownes** [comment]
@HaoK haha, thanks! I hide the other definitions, they were horrible :smile: 

On a more serious note, I can't seem to reproduce this bug on Katana so not sure when it has regressed.

I guess one - hack - way to solve this bug would be to store a marker in the `HttpContext `items and check if it's there before calling `HandleUnauthorizedAsync`.

**Comment by HaoK** [comment]
I think the behavior was probably introduced as part of this PR, I'm still not entirely sure this behavior is bad or not, as Automatic challenge has a bit of a different semantic than Challenge("SomeType")...

https://github.com/aspnet/Security/pull/283

**Comment by PinpointTownes** [comment]
> I'm still not entirely sure this behavior is bad or not, as Automatic challenge has a bit of a different semantic than Challenge("SomeType")...

The problem is that calling `Challenge("SomeType")` invokes all the automatic handlers when `HandleUnauthorizedAsync` returns `true`. It seems wrong, IMO.

**Comment by HaoK** [comment]
So at the most basic level AutomaticChallenge = true means `HandleUnauthorizedAsync` is getting called for your auth handler, irrespective of what other handlers have done.

As a result the rule basically is whenever you are mixing JWT/cookies together, you need to turn off AutomaticChallenge, for exactly the reason you ran into...

cc @blowdart who I think ran into this issue early on as well.

**Comment by blowdart** [comment]
What Hao said :D

**Comment by PinpointTownes** [comment]
> As a result the rule basically is whenever you are mixing JWT/cookies together, you need to turn off AutomaticChallenge, for exactly the reason you ran into...

Isn't that what `[Authorize(ActiveAuthenticationSchemes = "custom-scheme")]` is all about? Picking a specific scheme to decide which middleware is allowed to be invoked?

**Comment by blowdart** [comment]
Kinda of, it allows you to pick what you see *and*, if it's not automatic, run it. But automatic means automatic, as in, run on every request,

**Comment by PinpointTownes** [comment]
Thing is it worked fine with Katana, that had the same active/passive authentication mode concept :sweat_smile: 

Really feels like a regression for me.

**Comment by PinpointTownes** [comment]
Also, it doesn't make any sense that prior automatic middleware are not invoked when `HandleUnauthorizedAsync` returns `false` and are invoked when it returns `true`.

**Comment by HaoK** [comment]
Well, AutomaticChallenge just ensuring that challenge is called on the handler once per request.  If Challenge is called as a result of an explicit Challenge due to HandleUnauthorizedAsync returning false, that satisfies the AutomaticChallenge

**Comment by Tratcher** [comment]
The real oddity is HandleAutomaticChallengeIfNeeded. This didn't repro in Katana because Katana preserved the challenge schemes and applied them as the request unwound. Core does not preserve the challenge schemes, it applies them immediately.

**Comment by HaoK** [comment]
@Tratcher do you think we need to consider revisting any of this behavior at this point?

**Comment by HaoK** [comment]
To be honest I've always hated the return bool to signal control flow, but that seems like too big of a change to make now.

**Comment by Tratcher** [comment]
This is definitely a weird behavior, but I don't know that the bools are the problem. HandleAutomaticChallengeIfNeeded may be too eager.

**Comment by HaoK** [comment]
So today its basically a blind challenge on any 401 status code if challenge hasn't already been called

```
            if (!ChallengeCalled && Options.AutomaticChallenge && Response.StatusCode == 401)
```

The ask seems to be additional smarts detecting if any other middleware has handled this challenge (yet kept the status code as 401?)

The behavior today maybe be dumb, but its at least somewhat easy to explain and in reality, isn't AutomaticChallenge there primarily for single middleware scenarios?

**Comment by HaoK** [comment]
@Tratcher do you think we need to revisit anything here or are we 'happy enough' with the current behavior...

**Comment by Tratcher** [comment]
The only improvement I can think to make here is for Challenge to always call PriorHandler and let ShouldHandleScheme in the next middleware deal with it (or have Challenge check ChallengeContext.Accepted?). That way ChallengeCalled will be set so HandleAutomaticChallengeIfNeeded will short circuit.

Invoking all the handlers on Challenge should be fine as ShouldHandleScheme should only be true in one of them. The current avoidance of calling PriorHandler is more of a perf optimization than a functional requirement.

**Comment by HaoK** [comment]
The problem with changing this behavior is how subtle it is, so we are likely to randomly break any apps who accidentally or not are relying on the current behavior in some subtle hard to discover way.

Since this issue only occurs if there are multiple auth middleware, where one of them has AutomaticChallenge set to true right?  Can we just state that isn't really well supported scenario, and that its usually a good idea to disable Automatic challenge in these kinds of multi challenge scenarios

**Comment by PinpointTownes** [comment]
> Since this issue only occurs if there are multiple auth middleware, where one of them has AutomaticChallenge set to true right? Can we just state that isn't really well supported scenario.

So basically any app that uses Identity with the default configuration? You're making me regret using it... really.

**Comment by blowdart** [comment]
Be fair, for most apps using identity, cookies are the only middleware. That's the default in all the templates too.

**Comment by HaoK** [comment]
Plus its not that you can't use cookies + other auth middleware, its just that you should avoid relying on AutomaticChallenge in that situation, you should be able to do the equivalent of what automatic challenge is doing

**Comment by PinpointTownes** [comment]
Again, you're missing the whole point: calling `ChallengeAsync("scheme corresponding to a middleware with AutomaticChallenge = false")` SHOULDN'T result in the other automatic handlers being invoked.

This is definitely a bug.

**Comment by HaoK** [comment]
So the original design was that any auth middleware which has AutomaticChallenge set to true will have Challenge run at the end request if the auth middleware hasn't been challenged yet.  So we've always known that having cookies set to auto would stomp on other kinds of challenges (why we say don't mix cookies with auto challenge true)

**Comment by PinpointTownes** [comment]
> So the original design was that any auth middleware which has AutomaticChallenge set to true will have Challenge run at the end request if the auth middleware hasn't been challenged yet.

What's the point of returning a bool from `HandleUnauthorizedAsync`, then? The original design (i.e the one used in Katana) was that automatic challenges were only applied if no challenge was manually returned. This is not what happens here.

**Comment by PinpointTownes** [comment]
If you don't want to fix this bug, please at least provide a way to work around it (e.g. by making `HandleAutomaticChallengeIfNeeded` protected virtual).

**Comment by HaoK** [comment]
That seems like the safest change, making it protected virtual in 1.1 works

**Comment by PinpointTownes** [comment]
Forget that, this won't work (or I'd have to create a custom cookies middleware and force my users to rely on it)

**Comment by Tratcher** [comment]
Offline discussion: We'll try ignoring the handled result in ChallengeAsync and always call PriorHandler. This makes ChallengeCalled get set in all the middleware so HandleAutomaticChallengeIfNeeded can short circuit. The additional middleware should no-op due to ShouldHandleScheme.

**Comment by PinpointTownes** [comment]
@Tratcher thanks, you rock :+1:

**Comment by HaoK** [comment]
e12838e38f5f8be8371c0a7b02d9ce47e0663ce0

**Comment by HaoK** [comment]
Should we put up an announcement for this change?

**Comment by HaoK** [comment]
Ironically, we didn't fix the bug title, we made that the new official behavior :)

**Comment by Tratcher** [comment]
Let's not, nobody would know what we were talking about :-).

**Comment by PinpointTownes** [comment]
Outch, looks like this thread was muted and I didn't see your replies :scream: 

> Ironically, we didn't fix the bug title, we made that the new official behavior :)

Yes, you actually generalized the "bad behavior" I was trying to fix, which has a very negative impact when you have 2 automatic middleware in the same pipeline (e.g Identity + JWT), as the two challenges collide.

> The additional middleware should no-op due to ShouldHandleScheme.

Unfortunately, it does pretty much the opposite :face_with_head_bandage:

**Comment by c-s-n** [comment]
Underlining the "bad feeling about this change" from @HaoK , I now have to report one use case that most likely got broken due to this questionable change, noted when upgrading from ASP.NET Core 1.0.1 to 1.1.0.

**Background**
I use the IISIntegration with `IISOptions.AutomaticAuthentication = true` and `IISOptions.ForwardWindowsAuthentication = true`. Furthermore I use the Cookie Authentication (without Identity) with `CookieAuthenticationOptions.AutomaticAuthenticate = true` and `CookieAuthenticationOptions.AutomaticChallenge = true`. This should be fine in combination (see e.g. also [this comment](https://github.com/aspnet/Security/issues/1054#issuecomment-263483995)).

**Problem**
When a not yet authenticated user accesses a controller with an authorization policy applied that requires an authenticated user, but no explicit authentication schemes, then following - actually desired behavior - used to happen (pre 1.1.0):
* _Authorization failed for user: (null)._
* _Executing ChallengeResult with authentication schemes ()._
* _AuthenticationScheme: Cookies was challenged._
* `CookieAuthenticationEvents.OnRedirectToLogin` gets called once and redirects to the `CookieAuthenticationOptions.LoginPath`
* Response is 302
* Login page is shown

What DOES happen since 1.1.0:
* _Authorization failed for user: (null)._
* _Executing ChallengeResult with authentication schemes ()._
* _AuthenticationScheme: Cookies was challenged._
* `CookieAuthenticationEvents.OnRedirectToLogin` gets called and calls `context.Response.Redirect`
* Response is 401 though
* Same page/path is requested again by the browser
* Above sequence runs again
* After 401 is returned the second time, the browser's Windows Auth popup is shown

So: The Windows Authentication always ignores the challenge from the Cookies Authentication. I don't think this is the desired way with automatic authentication schemes.

**Notes**
The old and new behavior can be switched by changing only the "Microsoft.AspNetCore.Authentication.Cookies" package from/to version 1.1.0 resp. 1.0.0.

**Comment by Tratcher** [comment]
@c-s-n Please open a new issue for this so it doesn't get lost. We have test coverage for this scenario and it appears to be working. Are all of your packages 1.1? It won't work if you mix 1.1 cookies with 1.0 IISIntegration.

**Comment by c-s-n** [comment]
Yes, there are all on 1.1.0. I will open a new ticket, thanks.
