### ISSUE TITLE
Requiring authorization in ASP.NET Core

### ISSUE THREAD

**Issue by imsam67** [aspnet/Security#932]
The following code in ConfigureServices() method in Startup.cs was working fine in my ASP.NET Core 1.0 RC1 project. Now, I'm migrating it to the final version but this line is giving me an error that says "AuthorizationPolicyBuilder does not contain a constructor that takes that many arguments".

```
services.AddMvc(options =>
   // Require authenticated users throughout the application
   options.Filters.Add(new AuthorizeFilter(new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build()));
   );
```

How do I make sure that my ASP.NET Core app requires users to be authorized throughout the app?

**Comment by Tratcher** [comment]
That's odd, the constructors haven't changed since RC1.
https://github.com/aspnet/Security/blob/1.0.0-rc1/src/Microsoft.AspNet.Authorization/AuthorizationPolicyBuilder.cs
https://github.com/aspnet/Security/blob/1.0.0/src/Microsoft.AspNetCore.Authorization/AuthorizationPolicyBuilder.cs

**Comment by imsam67** [comment]
I changed it to `services.AddMvcCore(options =>...` and now it seems to be working but not 100% sure yet as I'm getting other errors.

One error was 

> "No service for type 'Microsoft.AspNetCore.Authorization.IAuthorizationService' has been registered."

 so I added `services.AddAuthorization()`. That seemed to help but now I'm getting 404.15 (query string is too long" error.

BTW, my app uses Facebook and Google authentication.
