### ISSUE TITLE
Aes encryption algorithm how to implement

### ISSUE THREAD

**Issue by 188** [aspnet/Security#933]
in .net core
Aes encryption algorithm how to implement

**Comment by imranbaloch** [comment]
Just use Aes.Create https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/Aes.cs#L38

**Comment by 188** [comment]
Thanks
