### ISSUE TITLE
Implementing custom authentication middleware.

### ISSUE THREAD

**Issue by optlink** [aspnet/Security#938]
I haven't been able to find a lot of information on this topic so everything I've learned has been from reading the source for the cookie authentication middleware. The middleware is written and works great except for failure cases. Returning `AuthenticateResult.Fail()` from `HandleAuthenticateAsync()` apparently does nothing. `HandleUnauthorizedAsync` and `HandleForbiddenAsync` do not get called  while my controller methods using the `Authorize` attribute continue executing anyway. `AutomaticAuthenticate` and `AutomaticChallence` are both set to true. I'm trying to return 401 responses for failed authentication and any help would be appreciated.

**Comment by Eilon** [comment]
@optlink can you upload your project to GitHub so that we can take a look? It's definitely sometimes a bit tricky to write authN middleware so if we can take a look at your code we can try to help debug it.

**Comment by optlink** [comment]
[DummyAuthentication.zip](https://github.com/aspnet/Security/files/419305/DummyAuthentication.zip)

While creating this example I discovered that the problem was being caused by the use of `services.AddMvcCore().AddJsonFormatters()` instead of `services.AddMvcCore().AddJsonFormatters().AddAuthorization()` or `services.AddMvc()`. However, there is another issue. The request is being authenticated (in this example all one has to do is send any data at all with the `Authentication` header) but fails with a 403 response. The documentation seems to imply that simple authentication with no authorization should work with this code.

**Comment by Tratcher** [comment]
I don't see anything obviously wrong. @troydai can you try debugging it?

**Comment by troydai** [comment]
@optlink the problem is that when the `ClaimsIdentity` is created in handler it is not given an authenticate type. As a result it's regarded as __not__ authenticated. (https://msdn.microsoft.com/en-us/library/system.security.claims.claimsidentity.isauthenticated(v=vs.110).aspx)

A quick fix is to assign it a string represents any authentication type:

```
            var identity = new ClaimsIdentity("DummyAuthentication");
            var principal = new ClaimsPrincipal(identity);
            identity.AddClaim(new Claim("claim", "dummy"));
```

**Comment by optlink** [comment]
@troydai that fixed it, thank you.
