### ISSUE TITLE
Add RedirectToPostLogoutRedirectUri to OpenIdConnect auth

### ISSUE THREAD

**Issue by troydai** [aspnet/Security#942]
Proposed in PR: https://github.com/aspnet/Security/pull/925

Requires change to the IOpenIdConnectEvent: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/Events/IOpenIdConnectEvents.cs.

**Comment by Tratcher** [comment]
Note this is a breaking change to add interface members and cannot be done until 2.0. Consider removing the interface pattern entirely to avoid this limitation in the future.
