### ISSUE TITLE
consider making Invoke virtual virtual on AuthenticationMiddleware

### ISSUE THREAD

**Issue by rposener** [aspnet/Security#944]
In cases such as some HMAC authentication algorithms, we need to inspect the stream during the Authentication Middleware.  In this case, it would be nice if we could go ahead and read the stream in only in the cases where it's necessary, replacing the body with a buffered stream.  This would prevent having to add buffered stream middleware in blanketly to every request, when it's only necessary in certain situations (e.g. certain Authroization header is present).

**Comment by troydai** [comment]
Hi @rposener, is you scenario achievable through customize a middleware and added before any authentication middleware?
