### ISSUE TITLE
Windows groupsid not translated to ClaimTypes.Role for Trusted Domain

### ISSUE THREAD

**Issue by recalde** [aspnet/Security#951]
Using .NET 4.6 with ASP.NET Core I am unable to use windows domain global groups on ClaimsPrincipal for Authorization without manually translating groupsid to NTAccount and adding back to ClaimsPincipal as new Claim(ClaimTypes.Role, roleName).

This code tests claim principal for all Claims:
`principal.Claims.Select(c => string.Format("{0}-{1}", c.Type, c.Value)).ToArray();`

This returns only groupsids from windows domain:
> http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid-S-1-5-21-1777081478-1322062499-644039835-1173957

This code will translate groupsid to windows group name:
```
public static IEnumerable<string> FindGroupsBySid(this ClaimsPrincipal claimsPrincipal)
{
    foreach (var claim in claimsPrincipal.Claims.Where(c => c.Type == ClaimTypes.GroupSid))
    {
        string groupName = null;
        try
        {
            var sid = new SecurityIdentifier(claim.Value);
            var ntAccount = sid.Translate(typeof(NTAccount));
            groupName = ntAccount.Value;
        }
        catch (IdentityNotMappedException)
        {
        }

        if (groupName != null)
        {
            yield return groupName;
        }
    }
}
```

**Comment by recalde** [comment]
Using UseIISIntegration with forwardWindowsAuthToken
`<aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" forwardWindowsAuthToken="true" stdoutLogEnabled="false" />`

**Comment by Tratcher** [comment]
@brentschmaltz?

**Comment by recalde** [comment]
Should we expect **ClaimsPrincipal** and **Authorization** attribute to work with Windows Groups by default or is it expected behavior to fix-up claims principal to add them as roles?

**Comment by recalde** [comment]
I have also seen Stackoverflow comments about hard-coding GroupSids as constants to workaround this issue.

**Comment by Eilon** [comment]
The Authorize attribute should already work in this case if you are using the Roles property.

This only works for a WindowsPrincipal. which is what you will get with IIS Integration.

As soon as you treat it as a ClaimsPrincipal isInRole will not work.

So what are you trying to do on a ClaimsPrincipal?

**Comment by recalde** [comment]
@Eilon very sorry to waste your time, this is working as expected.  This might have been an issue we had with RC1 that's been fixed since then and I just didn't have a chance to re-test with the snippet removed.

I should have tested with RTM more before logging the issue (or logged it back in February when encountered it...

**Comment by Eilon** [comment]
Glad you got it working!
