### ISSUE TITLE
OpenIdConnectOptions - resolve ClientId / ClientSecret dynamically

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#953]
_Moved from https://github.com/openiddict/openiddict-core/issues/202._

-----------

I have a ASP.Net WEB API application that is a "client" to a OpenIddict server. This API is used by various customers. And refresh token should be provided by the OpenIddict server in the correct customer scope. When configuring UseOpenIdConnectAuthentication on the WEB API Startup, we can set the ClientId / ClientSecret. But we would like to set these fields per request, depending on the customer token that the WEB API client provides. So can we set ClientId / ClientSecret dynamically per request, using a callback for example? Or what would be the preferred way of supporting this scenario?

**Comment by Tratcher** [comment]
We call this multi-tenancy, and currently there's no support for it.

https://github.com/aspnet/Security/issues/35

**Comment by PinpointTownes** [comment]
Actually, I had an idea soon after moving this ticket: I'm pretty sure this scenario could be achieved using the `RedirectToIdentityProvider`/`AuthorizationCodeReceived` events (by dynamically replacing the `client_id` parameter from the authorization/token request).

/cc @tedvanderveen

**Comment by Tratcher** [comment]
That assumes the metadata is the same for each client

**Comment by tedvanderveen** [comment]
@Tratcher @PinpointTownes Yes one could call it multi-tenancy, but in a very basic way. That is, only the client_id and client_secret should vary, the other metadata/Options stay the same from the perspective of the multi-tenant application (in this case the ASP.Net Web API application that authenticated against the OpenID server).
So basically we need to direct the OpenID server on what Application instance to select. I like the idea @PinpointTownes suggested by using `RedirectToIdentityProvider` and `AuthorizationCodeReceived` to transport the client_id and client_secret params.
