### ISSUE TITLE
What happened to SaveTokensAsClaims property? Disappeared during rename?

### ISSUE THREAD

**Issue by adrian-cy** [aspnet/Security#960]
Hi,

There was a property (SaveTokensAsClaims) in OpenIdConnectOptions.cs that seems to have disappeared without any explanation during the renaming of the namespace from Microsoft.AspNet.* to Microsoft.AspNetCore.* 

Link to last commit in history for the file:
[The History](https://github.com/aspnet/Security/commits/00c81d41aaeeb2d9ba48932c083681a9ba7a20a7/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenIdConnectOptions.cs)
[The Commit](https://github.com/aspnet/Security/commit/835903892771b9e833985c43bc3b967f66f31892)

After the rename:
[The History](https://github.com/aspnet/Security/commits/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs)
[The rename commit](https://github.com/aspnet/Security/blob/ba757d7a458398d3c2a7874b6556e86648f094be/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs)

As you can see, the property disappears in thin air with absolutely no explanation to why and even less so how to migrate.

NB: The weird part is that the commit messages clearly state it's rename only with no changes.

**Comment by Tratcher** [comment]
See SaveTokens https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationOptions.cs

**Comment by adrian-cy** [comment]
@Tratcher Thanks
