### ISSUE TITLE
Additional ClaimsIdentity lost when authorizing with ActiveAuthenticationSchemes

### ISSUE THREAD

**Issue by c-s-n** [aspnet/Security#961]
### Title
Any manually added `ClaimsIdentity` on an **existing** `ClaimsPrincipal` is lost when using an `AuthorizeAttribute` specifying a (non-empty) `ActiveAuthenticationSchemes`.

### Functional impact
When using Windows Authentication we want to add custom claims to the list of claims for the current `ClaimsPrincipal`. Therefore we use a custom middleware that looks up the user via its login name in an external system and adds the user's properties as custom claims (using an additional `ClaimsIdentity` *1).
For some controllers we need to specify what authentication scheme is to be used and thus apply an `AuthorizeAttribute` with `ActiveAuthenticationSchemes`.

-> In these controllers the added (and actually needed) identity and claims are gone, while in controllers without `ActiveAuthenticationSchemes` they still exist.

### Minimal repro steps
Configure the pipeline with cookie authentication and a custom middleware
```C#
app.UseCookieAuthentication();
app.UseMiddleware<AddIdentityMiddleware>();
```
In the custom `AddIdentityMiddleware` perform the following
```C#
context.User.AddIdentity(new ClaimsIdentity(new Claim[] { new Claim("testclaim", "testguid") }, "customAuthenticationType"));
```
Create a new controller, which returns the available claims, but is limited to a certain `ActiveAuthenticationSchemes`
```C#
[Authorize(ActiveAuthenticationSchemes = "Cookies")]
public class SchemeController : Controller
{
    [HttpGet]
    public IEnumerable<string> Get()
    {
        return Request.HttpContext.User.Claims.Select(c => c.Type + ": " + c.Value);
    }
}
```
Have a dummy user logged in somewhere via following code
```C#
var claims = new List<Claim>();
claims.Add(new Claim(ClaimTypes.Name, "testuser", ClaimValueTypes.String, "https://contoso.com"));
var userPrincipal = new ClaimsPrincipal(new ClaimsIdentity(claims, "mainAuthenticationType"));
await HttpContext.Authentication.SignInAsync("Cookies", userPrincipal);
```

Run application and access the SchemeController

### Expected result
Response with the following information
```
["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: testuser","testclaim: testguid"]
```
i.e. the claims from both claims identities serialized.
While #323 was closed with the argument that custom claims principals were not supported, I don't feel that the same should go for additional claims identities for the given claims principal (e.g. the property `ClaimsPrincipal.Claims` is designed to work perfectly fine with multiple claims identities).

### Actual result
Response with the following information
```
["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: testuser"]
```
The `HttpContext.User` has "lost" its second claims identity.
@PinpointTownes [mentioned](https://github.com/aspnet/Security/issues/323#issuecomment-118279159) that the authorization layer replaces the `HttpContext.User`. I think it should still retain all identities.

### Further technical details
The issue seems to not occur with authentication scheme NTLM when no cookie authentication has been performed yet resp. when no cookie exists.

ASP.NET Core 1.0.0 with .NET Framework 4.5.2 target

### Notes
*1) We figured out that we could alternatively cast the user's primary claims `IIdentity` to `ClaimsIdentity` and call `AddClaim` on it, but still wanted to file this bug.

**Comment by Eilon** [comment]
The problem in the repro code seems to be that the `[Authorize]` attribute is requesting one type of authorization (Cookies, in this case), yet the provided identity wasn't created by the Cookies middleware, it was created using a custom authentication scheme. Those two values need to match.

cc @blowdart
