### ISSUE TITLE
Microsoft.AspNetCore.Authentication.Twitter's package description is incorrect

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Security#962]
The Twitter provider uses OAuth 1.0, not OAuth 2.0 (that's why it doesn't inherit from `OAuthMiddleware`): https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/114#issuecomment-243774529

@Eilon pretty sure that one is for you :smile: 

/cc @arielcloud

**Comment by Eilon** [comment]
I'll let @troydai fix it. I'll review 😄

**Comment by PinpointTownes** [comment]
Fixed: https://github.com/aspnet/Security/commit/5aae7ded010dd80dfb24ca17fc719ff4f4658cd6.
