### ISSUE TITLE
OIDC - Consider adding distributed claims support

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Security#963]
The OIDC specs define distributed claims.
See http://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims

A distributed claim is represented by the source url of the claims provider in the userinfo response.
By providing the HttpClient in the UserInformationReceived event, it will be easy to implement this optionnal part of the OIDC specifications.

Another way to achieve this would be to implement directly into the GetClaimsFromUserinfoAsync() method.

**Comment by Eilon** [comment]
We will consider this in a future version. Just re-using the HttpClient would sometimes be a nice perf optimization, but we'll look into providing a more complete and useful implementation of distributed claims.

**Comment by Eilon** [comment]
Closing this issue because we have no plans to implement this.
