### ISSUE TITLE
Third-Party Providers - Add a LinkedIn Provider

### ISSUE THREAD

**Issue by jasongaylord** [aspnet/Security#964]
Currently, there are providers for Facebook, Google, Microsoft, and Twitter. There are also generic OAuth and OpenId providers. Can we have a LinkedIn OAuth provider?

**Comment by Tratcher** [comment]
See https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src/AspNet.Security.OAuth.LinkedIn

**Comment by jasongaylord** [comment]
So it's safe to say additional providers should be through the contrib project?

**Comment by Eilon** [comment]
Yeah no plans on adding more 3rd party providers at this time.

@jasongaylord yep in general through contrib.
