### ISSUE TITLE
do you want intuit QuickBooks provider?

### ISSUE THREAD

**Issue by arielcloud** [aspnet/Security#965]
I'm implementing a QuickBooks provider (OAuth 1.0, I started with the twitter code).
If I'll open a PR, will you want to add this? or should i add it as external nuget package?

**Comment by Tratcher** [comment]
https://github.com/aspnet-contrib is probobly the best place for a QuickBooks provider.

**Comment by Eilon** [comment]
Yeah no plans on adding more 3rd party providers at this time.
