### ISSUE TITLE
Google handler should include claim for profile image url

### ISSUE THREAD

**Issue by hempels** [aspnet/Security#969]
Google returns the user's profile url as well as the profile image url. Currently only the profile url is included as a claim. The image is useful data and should be included as a claim also.

**Comment by Eilon** [comment]
We generally don't include extra data because not all apps need them, and can make the cookie size get excessively large. However, we made it fairly easy to add the right scopes (if necessary), and then map the claims into the data you request.

**Comment by hempels** [comment]
It is possible to map the claims, but having gone through the process, I'm not convinced it's easy. The method is not at all intuitive and is entirely undocumented apart from sample code. While I applaud the effort, as an end user the current solution is far too time consuming. I'm finding this to be fairly consistently the case with ASP.NET Core. My hope is that some of this prodding will prompt you guys to consider not just whether you've made something possible, but also whether you've made it useable.

**Comment by Eilon** [comment]
@hempels understood, so I'm re-opening this issue. Can you give an example of what you found to be not easy, and perhaps propose a syntax that you would find to be easier to use?

**Comment by muratg** [comment]
We could potentially consider adding a feature where a user app can map a JSON filed to a claim to make this easier.

**Comment by Tratcher** [comment]
Idea:
`options.AddClaimMap(jsonKey, claimName, claimType);`

**Comment by HaoK** [comment]
We should just generalize the functionality that's currently hardcoded in Facebook/Google handler that's copying claims over into the default claim map, and let that be the source of truth for what's done before the creating ticket event is fired.

**Comment by Tratcher** [comment]
Similar issue mapping custom challenge parameters: https://github.com/aspnet/Security/issues/990

**Comment by StummeJ** [comment]
@hempels do you remember what sample code explained how to do this custom mapping?
