### ISSUE TITLE
ExternalLoginInfo.AuthenticationTokens is empty

### ISSUE THREAD

**Issue by hempels** [aspnet/Security#970]
After successful external auth, there doesn't appear to be a simple way to retrieve the access tokens returned, at least from the Google authentication handler. There's a property on ExternalLoginInfo named AuthenticationTokens, but it seems to always be empty.

Is there another way to retrieve the access tokens that were returned during Google auth?

**Comment by Tratcher** [comment]
You have to opt-in by setting SaveTokens = true;
https://github.com/aspnet/Security/blob/59fc691f4152e6d5017176c0b700ee9834640481/samples/SocialSample/Startup.cs#L111

**Comment by hempels** [comment]
Brilliant! Thank you.

Would be even better if it was in the docs, but things are coming along nicely. :+1:

**Comment by Eilon** [comment]
@Tratcher can you have a look at the docs and see what needs to be updated there?

**Comment by Tratcher** [comment]
Filed https://github.com/aspnet/Docs/issues/1883 for doc updates
