### ISSUE TITLE
Google middleware authorization should use prompt instead of approval_prompt

### ISSUE THREAD

**Issue by hempels** [aspnet/Security#971]
I see support in GoogleHandler.BuildChallengeUrl for approval_prompt via:
`AddQueryString(queryStrings, properties, "approval_prompt");`

First, I can't figure out how to apply that property. Setting it in CookieAuthenticationEvents.OnSigningIn doesn't seem to cause any different behavior by Google.

Second, it's not the right property. Google deprecated it in favor of prompt, which has four possible values: "none", "consent", "select_account", or "select_account consent".
see: https://developers.google.com/identity/protocols/OAuth2WebServer

I've managed to work around this limitation by adding ?prompt=select_account to the AuthorizationEndpoint in GoogleOptions, but it's a pretty ugly hack.

**Comment by Tratcher** [comment]
Those property overrides can be specified in the initial call to Challenge with the AuthenticationProperties collection.

As for approval_prompt, we'll have to dig up the official list of parameters and update it.

**Comment by hempels** [comment]
One note, I think the current solution is perhaps creating extra work for you guys and for consumers of the API. I struggle to come up with a reason it wouldn't make sense to just provide a parameters dictionary so any value can be passed to the target API. That approach seems to work for WebRequest headers, etc. The way this is implemented now, the library will constantly be chasing API revisions.

**Comment by Eilon** [comment]
We should check the Google docs if `approval_prompt` is still the right field, and if not, update our codes.

**Comment by troydai** [comment]
`approval_prompt` is renamed to `prompt` for Google API. I'll make changes in our code accordingly.

**Comment by troydai** [comment]
`approval_prompt` is a legacy parameter. Though it is not in the official document, it is still working. `prompt` is a different parameter for different usage. We will keep both.

**Comment by troydai** [comment]
Issue is fixed in ddeef1f9ac09c34c2a2c28e35923ae7288b1049e

I filed additional issue #990 to track @hempels 's feedback on auth query parameters.
