### ISSUE TITLE
AddAuthorization should chain AddOptions

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Security#972]
```C#
var serviceProvider = new ServiceCollection().AddAuthorization().BuildServiceProvider();
var policyProvider = serviceProvider.GetService(typeof(IAuthorizationPolicyProvider));
```

Expected: Get the `DefaultAuthorizationPolicyProvider`
Actual: 
Unable to resolve service for type 'Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.Authorization.AuthorizationOptions]' while attempting to activate 'Microsoft.AspNetCore.Authorization.DefaultAuthorizationPolicyProvider'.

`AddAuthorization` should chain `AddOptions` so that you don't have to explicitly call it.

**Comment by HaoK** [comment]
Good catch!

**Comment by Tratcher** [comment]
Except Hosting always adds Options so most of the components don't have to.
https://github.com/aspnet/Hosting/blob/0a7cf6b5a0d090fe085a16e56eb8c8931d31e073/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L196

**Comment by HaoK** [comment]
Yeah I guess we don't add options anywhere else, Identity/MVC all rely on hosting (or the unit test setup) to call AddOptions

**Comment by HaoK** [comment]
Options are special and assumed to be present I guess :)

**Comment by Eilon** [comment]
Not a high priority.
