### ISSUE TITLE
Remove the IAuthorizationRequirement interface

### ISSUE THREAD

**Issue by dotnetjunkie** [aspnet/Security#977]
The `Microsoft.AspNetCore.Authorization` namespace contains the [IAuthorizationRequirement](https://github.com/aspnet/Security/blob/34ee0212d0c6de76a40609b70df77545dbdde3bf/src/Microsoft.AspNetCore.Authorization/IAuthorizationRequirement.cs) interface. This interface is a marker interface; it contains no members. It is used to mark DTOs as authorization requirement and is solely used as generic type constraint in the `AuthorizationHandler<TRequirement>` class.

The existence of this interface however makes it harder for users to write code that is decoupled from the Microsoft.AspNetCore (presentation) framework). Simple DTOs that the user defines as authorization requirement must be marked with the `IAuthorizationRequirement`, which means this DTO must live in a presentation project (since a business layer should typically not depend on an application framework).

The existence of this interface also seems a violation of the Framework Design Guidelines that states (second edition, paragraph 4.6, page 99):

> AVOID using marker interfaces 

The only benefit the existence of this interface has, it that developers can't accidentally use a wrong type as generic type in the `AuthorizationHandler<TRequirement>` class. Chances of this happening however are actually really slim, since a developer will always create its `AuthorizationHandler<TRequirement>` derivative together with its authorization requirement DTO.

My advice is to take the breaking change and remove this marker interface.

**Comment by muratg** [comment]
We won't be doing this change, this is a breaking change and marker interfaces are sometimes necessary.

**Comment by dotnetjunkie** [comment]
Can you explain what the need is for the marker.interface in this particular case?

**Comment by muratg** [comment]
It's representational -- it prevents usage of an incorrect type as the generic type.

**Comment by SilasReinagel** [comment]
Marker interface do not prevent usage of incorrect types. Any type can implement a marker interface.
