### ISSUE TITLE
Switch MSA to use the consumer endpoints

### ISSUE THREAD

**Issue by danroth27** [aspnet/Security#979]
Currently, MSA is using the "converged" endpoints for MSA and AAD and is pointing to `/common`. This means that an app using the MSA middleware might someone in using the AAD account by accident, instead of their MSA. We should consider switching to the `/consumer` endpoints instead, which would limit the flow to just MSA.

@vibronet

**Comment by Tratcher** [comment]
Breaking change?

**Comment by danroth27** [comment]
You mean where an app is relying on the ability to sign in with an org account when MSA is configured? That was never really the intention . . .

**Comment by muratg** [comment]
@danroth27 We talked about this in the Security triage. This is by design and by request from AAD. 

Talk to @vibronet 😄

**Comment by vibronet** [comment]
@muratg what triage meeting are you referring to? I wasn't in today's one, and I am not sure I understand why AD would request this. MSA is in the name of the middleware, it think it is legitimate for the developer to expect to drive authentication with an MSA. Whereas /common in the v2 endpoint allows user to authenticate with both organizational and consumer accounts, throwing a home realm discovery experience in the middle, /consumers restricts the operation to MSA accounts only and seems better in line with the intent of the middleware. If a developer does want to work with both account types, he or she can always use the v2 /common from the OIDC middleware. 
What am I missing?
