### ISSUE TITLE
OpenIdConnect - ASP.NET webapi silent authentication

### ISSUE THREAD

**Issue by lszomoru** [aspnet/Security#981]
I have created a web application based on the OpenIdConnect.AzureAdSample project. Apart from the MVC model, views, and controllers, I have also added a couple of web apis which are being called from client side code. The site is being hosted using IIS, with the data protection registry hive created as documented [here](https://docs.asp.net/en/latest/publishing/iis.html#create-a-data-protection-registry-hive here).

When I launch the application, I sign in with my AAD credentials and everything is working as expected. The problem is that if I keep the page opened for some time, after a period of time the auth token expires and when I try to call the web api from the client side code (without refreshing the complete page) I am getting the following error message: 

_XMLHttpRequest cannot load https://login.microsoftonline.com/GUID/<REMOVED>. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://webapplication' is therefore not allowed access._

Did I miss something when setting up the web application? Thanks in advance!

**Comment by Tratcher** [comment]
You're sharing a cookie for interactive calls and webapi calls. Cookies are not appropriate for web-api calls because they require user-interaction to renew. WebApis should use bearer tokens instead (e.g. JWT). You can use something like IdentityServer4 to exchange your cookie for a bearer token. https://github.com/IdentityServer/IdentityServer4

**Comment by lszomoru** [comment]
Thank @Tratcher for getting back to me on this. I will read up on IdentityServer4.

**Comment by leastprivilege** [comment]
http://docs.identityserver.io
