### ISSUE TITLE
Add support for JWE tokens

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/Security#983]
JWE tokens require access to private asymmetric or symmetric keys. 
IdentityModel is adding support for JWE, while possible to set the keys on the IdentityModel OM, that would require users to work at the IdentityModel layer for this feature.

A collection something like would work:

``` c#
ICollection<SecurityKey> xyzOptions.DecryptionKeys()
```

It may also make sense to have a delegate that can return a key. Dropping to IdentityModel may make sense here.

**Comment by PinpointTownes** [comment]
Really great news :+1: 

Related ticket: https://github.com/aspnet/Security/issues/430

**Comment by Tratcher** [comment]
There are several more scenarios to consider. If they keys are retrieved from metadata (directly or indirectly) then OIDC will have to pass them down to TVP like it does with signing keys.
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L1127

**Comment by Eilon** [comment]
Per @brentschmaltz , JWE is implemented in IdentityModel 5.1.3.

@brentschmaltz - can you give us a sample of configuring these things at the IdentityModel layer?

**Comment by muratg** [comment]
Punting because not much time left in 2.0.0.

**Comment by Tratcher** [comment]
From @brentschmaltz:

Sample for consuming a JWE in a asp.net core app is here: https://github.com/brentschmaltz/AspNetCore/tree/master/JweSample
One possible solution for a user is to set a key: https://github.com/brentschmaltz/AspNetCore/blob/master/JweSample/JweSample/Startup.cs#L74

Possibilities are:
1.	Set a single key: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L321
2.	Set multiple keys that we cycle through: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L502  
3.	Make use of a delegate to return a specific key: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L333

**Comment by nickkhan** [comment]
@brentschmaltz  is there code sample for sts handling jwe?

**Comment by brentschmaltz** [comment]
@nickkhan are you referring to creating a JWE?

**Comment by nickkhan** [comment]
@brentschmaltz  yes.

**Comment by brentschmaltz** [comment]
@nickkhan are you asking for a creation sample?

**Comment by nickkhan** [comment]
@brentschmaltz sure, it be nice if you want to/can create a sample showing JWE specifically.

**Comment by brentschmaltz** [comment]
@nickkhan I dropped a sample here of JWE with symmetric and asymmetric keys.
https://github.com/brentschmaltz/Wilson5x/blob/master/src/CreateTokens/CreateTokens/Program.cs#L39
