### ISSUE TITLE
Check the response's content type is application/json for authorization response.

### ISSUE THREAD

**Issue by troydai** [aspnet/Security#985]
Code: https://github.com/aspnet/Security/blob/25f39dd0f5f9a9199b720c2a53a2002cad26a8c4/src/Microsoft.AspNetCore.Authentication.OAuth/OAuthHandler.cs#L152

Though we did set the `Accept` header to `application/json`, the response's content type is not actually verified.

**Comment by PinpointTownes** [comment]
Please be extremely careful before implementing such a check: while the OAuth2 specification mandates the use of JSON for the token endpoint, AFAIK, it doesn't say you have to return a `Content-Type` header, which is an optional response header (it's just recommended by the HTTP 1.1 spec).

I wouldn't be surprised if well-known providers didn't return a `Content-Type` header... they really do crazy things sometimes :smile: (e.g StackExchange's userinfo endpoint always return GZipped content, even if you don't specify an `Accept-Encoding` header: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/113#issue-173646778)

**Comment by muratg** [comment]
We decided to not do this. If the content-type is wrong or empty, and body is correctly parseable JSON, we'll be OK. otherwise JSON parsing will throw. We'll keep being lenient in receive. Besides this would be a breaking change.
