### ISSUE TITLE
How to set a custom message for unauthorized request 

### ISSUE THREAD

**Issue by rsen253** [aspnet/Security#987]
context.Succeed(requirement) // 
If it return a success result it will go inside the controller otherwise It will be an unauthorized access. But in case unauthorized access how can I show custom message(string / json / object) to the user .

**Comment by HaoK** [comment]
This is basically a dupe of https://github.com/aspnet/Security/issues/872

**Comment by rsen253** [comment]
/*in controller level */
[Authorize(Policy ="UserToken")]
    public class XYZController : Controller
    {
          public IActionResult Post([FromBody]GetPrescriberViewModel model)
          {
                        ///do something 
                        return model
          }
    }

/*  HandleRequirementAsync */
protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, UserToken userToken)
        {
            // Some logic
            if (Some condition is true)
            {
                context.Succeed(userToken);
            }
            
            return Task.FromResult(0);
        }

/*  In start up  */
services.AddAuthorization(options =>
            {
                options.AddPolicy("UserToken",
                                  policy => policy.Requirements.Add(new UserToken()));
            });
            services.AddSingleton<IAuthorizationHandler, UserTokenHandler>();

This is working fine and I am getting the expected output. But if the authorization failed how can I show some custom message

**Comment by Tratcher** [comment]
There's no direct way for authorization failures to send a custom response. These failures trigger an authentication challenge, and the mechanics of that challenge depend on the type of auth you're using. The authentication middleware end up generating the response.

**Comment by turbotmy** [comment]
i have the same concern with custom message with different policy aren't compliance, how can i write back to custome message type if different policy aren't meet ?
