### ISSUE TITLE
How to use AuthorizationEndpoint which contains query string parameters with OAuth.

### ISSUE THREAD

**Issue by ademcaglin** [aspnet/Security#988]
Is there an easy way to use `AuthorizationEndpoint `which contains query string parameters?  For example below code doesn't work as i expect

        var facebookOptions = new FacebookOptions
        {
              //...
              AuthorizationEndpoint = FacebookDefaults.AuthorizationEndpoint + "?param1=param1",
        };

Only way i found to solve this problem is using event:

       var facebookOptions = new FacebookOptions
        {
              //...
              Events = new OAuthEvents()
                {
                    OnRedirectToAuthorizationEndpoint = ctx =>
                    {
                        ctx.HttpContext.Response.Redirect(ctx.RedirectUri + "&param1=param1");
                        return Task.FromResult(0);
                    }
                }
        };

**Comment by Tratcher** [comment]
That's it for now. RE: https://github.com/aspnet/Security/issues/988

**Comment by troydai** [comment]
Related https://github.com/aspnet/Security/issues/990
