### ISSUE TITLE
Support additional authentication request parameters

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#99]
[Ported from https://katanaproject.codeplex.com/workitem/325]

Support additional authentication request parameters as defined in [3.1.2.1. Authentication Request] of the OIDC Core Spec. 

Keep in mind that some parameters need to be configured per challenge request (e.g. prompt, login_hint). It makes no sense to set those parameters in OpenIdConnectAuthenticationOptions! It would be good to have an additional parameter dictionary at Challenge() so that the parameters can be set per Challenge request.

**Comment by brentschmaltz** [comment]
I agree. Is '0 - Backlog', the highest priority? This should be a high priority.

**Comment by Tratcher** [comment]
Backlog is the lowest priority.

**Comment by cruikshj** [comment]
domain_hint would also be useful

**Comment by Tratcher** [comment]
Related: https://github.com/aspnet/AspNetKatana/pull/81/files

**Comment by Eilon** [comment]
Closing because the demand for this feature is very low.
