### ISSUE TITLE
[OAuth] Allow developer to easily customize query parameters on authorization endpoint

### ISSUE THREAD

**Issue by troydai** [aspnet/Security#990]
Today what parameter to be put on the query is hardcoded: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OAuth/OAuthHandler.cs#L210. There are two existing ways to customize the list of parameters to be added.
1. Override the `BuildChallengeUrl` method. That requires a deeper overwrite to the handler.
2. Override the event `RedirectToAuthorizationEndpoint`. It is simpler than the first approach but still impose unnecessary difficulties. 

We may be add a list of allowed parameter names to the OAuth options and let the OAuth handler to dynamically build the query string.

**Comment by Tratcher** [comment]
The Google middleware has a feature where it allows you to specify parameters via the AuthProperties in the challenge.
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Google/GoogleHandler.cs#L98
Unfortunately these are hard-coded and get out of date. Consider changing this to a list of KVP of kyes to take from the auth properties and add to the query.
