### ISSUE TITLE
Sharing authentication cookie with subdomain

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Security#993]
_From @ge6a93 on September 11, 2016 15:39_

Hi,

I have an ASP.NET Core website and for each registered user I provide a subdomain route: _user1.mysite.com_. The problem is that when the user goes to _mysite.com_ and logs in, they get redirected to _user1.mysite.com_ but it says that the user is not logged in - the authentication cookie is not shared across subdomains. I found this article - [https://docs.asp.net/en/latest/security/data-protection/compatibility/cookie-sharing.html](https://docs.asp.net/en/latest/security/data-protection/compatibility/cookie-sharing.html) but it didn't solve my problem. It shows how to share auth cookies between TWO applications but in my case I have only one application.  

Is there any solution to this problem? I believe I'm not the only one struggling with it. Thanks!

_Copied from original issue: aspnet/Home#1747_

**Comment by Tratcher** [comment]
Wouldn't this work if you set CookieAuthenticationOptions.CookieDomain to "mysite.com"?

**Comment by blowdart** [comment]
It should ...

**Comment by blowdart** [comment]
@ge6a93 could you get this into a simple repo?

**Comment by Eilon** [comment]
@blowdart can you try to repro this?

**Comment by Eilon** [comment]
We are not able to reproduce this. Setting the cookie domain should just work.
