### ISSUE TITLE
Adding external login throws 401, denied access

### ISSUE THREAD

**Issue by devharis** [aspnet/Security#997]
I've noticed that adding your first external login works successfully, however when I try to add another one directly after I get redirected to Account/AccessDenied.

Ive traced down the issue to a session called Identity.External, as soon as I remove it and try adding external login it works. Then on success this session is created and i get Account/AccessDenied again.

My current workaround is to remove that session on success.
FYI: I've also tried creating a new project, generated from template and I still got this error.

**Comment by Tratcher** [comment]
This was recently fixed. See https://github.com/aspnet/Security/pull/980

**Comment by devharis** [comment]
Cool, thanks for the info!

**Comment by troydai** [comment]
@devharis please feel free to reopen if it is still an issue.
